import IXITransactFaceLabFrame from"../../components/ixi-face-studio/IXITransactFaceLabFrame";
import IXIGeneralLedgerApp from"../../components/ixi-aos/transact/modules/general-ledger/IXIGeneralLedgerApp";
const context={primary:{objectId:"ENTITY-IXI",passportId:"PASS-IXI",objectType:"entity",label:"IRONXCHANGE LLC"},entity:{objectId:"ENTITY-IXI",passportId:"PASS-IXI",objectType:"entity",label:"IRONXCHANGE LLC"},location:{objectId:"LOC-MIDLAND",passportId:"PASS-MIDLAND",objectType:"location",label:"MIDLAND YARD"},actor:{employeeId:"EMP-SARAH",passportId:"PASS-SARAH",displayName:"SARAH JONES",label:"SARAH JONES"},permissions:[]};
const object={objectId:"ENTITY-IXI",passportId:"PASS-IXI",objectType:"entity",label:"IRONXCHANGE LLC"};
const records=[
{documentType:"invoice",documentId:"INV-1001",input:{documentNumber:"SINV-1001",invoiceType:"service-invoice",invoiceDate:"2026-08-05",dueDate:"2026-08-30",total:14870,financialState:"receivable",references:[{role:"entity",passportId:"PASS-IXI",label:"IRONXCHANGE LLC"},{role:"customer",passportId:"PASS-CUST",label:"ABC CONTRACTORS"},{role:"asset",passportId:"PASS-CAT336",label:"CAT 336"}]}},
{documentType:"bill",documentId:"BILL-19482",input:{documentNumber:"884921",documentDate:"2026-08-08",dueDate:"2026-08-28",total:4250,financialState:"billed",category:"utilities",references:[{role:"entity",passportId:"PASS-IXI",label:"IRONXCHANGE LLC"},{role:"vendor",externalId:"V-TXU",label:"TXU ENERGY"}]}},
{documentType:"expense",documentId:"EXP-2042",input:{documentNumber:"EXP-2042",documentDate:"2026-08-10",amount:850,category:"repair",paymentMethod:"company card",references:[{role:"entity",passportId:"PASS-IXI",label:"IRONXCHANGE LLC"},{role:"asset",passportId:"PASS-CAT336",label:"CAT 336"}]}},
{documentType:"payment",documentId:"PAY-9001",input:{documentNumber:"PAY-9001",documentDate:"2026-08-12",amount:5000,direction:"in",financialState:"received",relatedInvoiceId:"INV-1001",accountId:"TR-ACT-OPERATING",accountName:"Operating Checking",references:[{role:"entity",passportId:"PASS-IXI",label:"IRONXCHANGE LLC"}]}}
];
export default function GeneralLedgerFaceLabPage(){return <IXITransactFaceLabFrame title="GENERAL LEDGER / CLOSE" route="/facelab/general-ledger"><IXIGeneralLedgerApp context={context} object={object} financialRecords={records} initialJournals={[]} initialRules={[]} arSubledger={9870} apSubledger={4250} treasuryCash={5000} bankReconciliations={[{status:"reconciled",statement:{date:"2026-08-31"}}]} onBack={()=>{}} onRecordChange={async()=>{}}/></IXITransactFaceLabFrame>}
