export const OEM_COLOR_PROFILES = {
  CATERPILLAR: {
    primaryColorFamily: "warm_gold_yellow",
    maxSaturationLift: 0.045,
    maxBrightnessLift: 0.06,
    maxContrastLift: 0.16,
    hueShiftTolerance: 2.5,
    protectDecals: true,
    protectBlackTrim: true,
    preserveFadedPaint: true,
    recommendedDefaultPreset: "clean",
  },

  JOHN_DEERE: {
    primaryColorFamily: "industrial_yellow",
    maxSaturationLift: 0.04,
    maxBrightnessLift: 0.055,
    maxContrastLift: 0.15,
    hueShiftTolerance: 2.5,
    protectDecals: true,
    protectBlackTrim: true,
    preserveFadedPaint: true,
    recommendedDefaultPreset: "clean",
  },

  KOMATSU: {
    primaryColorFamily: "lemon_warm_yellow",
    maxSaturationLift: 0.035,
    maxBrightnessLift: 0.05,
    maxContrastLift: 0.15,
    hueShiftTolerance: 2,
    protectDecals: true,
    protectBlackTrim: true,
    preserveFadedPaint: true,
    recommendedDefaultPreset: "clean",
  },

  VOLVO: {
    primaryColorFamily: "pale_warm_yellow_dark_gray",
    maxSaturationLift: 0.03,
    maxBrightnessLift: 0.045,
    maxContrastLift: 0.14,
    hueShiftTolerance: 2,
    protectDecals: true,
    protectBlackTrim: true,
    preserveFadedPaint: true,
    recommendedDefaultPreset: "clean",
  },

  CASE: {
    primaryColorFamily: "power_yellow_power_tan",
    maxSaturationLift: 0.035,
    maxBrightnessLift: 0.05,
    maxContrastLift: 0.145,
    hueShiftTolerance: 2.5,
    protectDecals: true,
    protectBlackTrim: true,
    preserveFadedPaint: true,
    recommendedDefaultPreset: "clean",
  },

  DEFAULT: {
    primaryColorFamily: "unknown_equipment_color",
    maxSaturationLift: 0.03,
    maxBrightnessLift: 0.05,
    maxContrastLift: 0.14,
    hueShiftTolerance: 2,
    protectDecals: true,
    protectBlackTrim: true,
    preserveFadedPaint: true,
    recommendedDefaultPreset: "clean",
  },
};
