import { useMemo, useState } from "react";
import { IXI_AUTHORITY_CAPABILITIES, IXI_AUTHORITY_SUBJECT_TYPES, IXI_AUTHORITY_SCOPE_TYPES } from "../../../authority/IXIAuthorityRegistry";
import { createIXIAuthorityPolicy, normalizeIXIAuthorityPolicy } from "../../../authority/IXIAuthorityContract";
import IXIAuthorityClient from "../../../authority/IXIAuthorityClient";

const clean=v=>String(v??"").trim();
const arr=v=>Array.isArray(v)?v:[];
const obj=v=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
const unique=v=>Array.from(new Set(arr(v).map(clean).filter(Boolean)));
const targetOf=(context,source)=>({passportId:clean(context?.primary?.passportId||source?.passportId||source?.ixiPassportId),objectId:clean(context?.primary?.objectId||source?.objectId||source?.id),objectType:clean(context?.primary?.objectType||source?.objectType||source?.type),label:clean(context?.primary?.label||source?.displayName||source?.name)||"AOS OBJECT"});
const newRule=passportId=>({ruleId:`rule_${Date.now()}`,effect:"allow",subject:{type:"role",id:""},capabilities:["aos.view"],scope:{type:"target",passportId:clean(passportId)},conditions:{},limits:{},enabled:true,note:""});

export default function IXIAccessPolicyApp({context={},object:sourceObject={},actor={},authority={},initialPolicy=null,onBack=null,onPolicyChange=null,onIdentityChange=null}){
  const target=useMemo(()=>targetOf(context,sourceObject),[context,sourceObject]);
  const actorPassportId=clean(context?.actor?.passportId||actor?.passportId||actor?.ixiPassportId);
  const permissions=unique([...arr(context?.permissions),...arr(actor?.permissions),...arr(authority?.permissions)]);
  const canManage=authority?.canManage===true||permissions.includes("authority.manage")||permissions.includes("security.permissions.manage");
  const canInvite=canManage||permissions.includes("identity.invite")||permissions.includes("security.identity.invite");
  const principal=obj(sourceObject?.principal||sourceObject?.accessPrincipal||authority?.principal);
  const [policy,setPolicy]=useState(()=>normalizeIXIAuthorityPolicy(initialPolicy||sourceObject?.authorityPolicy||createIXIAuthorityPolicy({target,actorPassportId,inheritance:{inheritFromAncestors:true,propagateToChildren:true}})));
  const [selectedRuleId,setSelectedRuleId]=useState("");
  const [email,setEmail]=useState(clean(principal.email||sourceObject?.fields?.workEmail||sourceObject?.fields?.email));
  const [roleId,setRoleId]=useState(clean(principal.roleIds?.[0]));
  const [busy,setBusy]=useState("");
  const [message,setMessage]=useState("");
  const selected=policy.rules.find(rule=>rule.ruleId===selectedRuleId)||null;
  const grouped=useMemo(()=>IXI_AUTHORITY_CAPABILITIES.reduce((out,item)=>{(out[item.family]||(out[item.family]=[])).push(item);return out;},{}),[]);
  const patchPolicy=patch=>setPolicy(current=>normalizeIXIAuthorityPolicy({...current,...patch,target}));
  const patchRule=(id,patch)=>setPolicy(current=>normalizeIXIAuthorityPolicy({...current,target,rules:current.rules.map(rule=>rule.ruleId===id?{...rule,...patch}:rule)}));
  function addRule(){const rule=newRule(target.passportId);patchPolicy({rules:[...policy.rules,rule]});setSelectedRuleId(rule.ruleId);}
  function removeRule(id){patchPolicy({rules:policy.rules.filter(rule=>rule.ruleId!==id)});if(selectedRuleId===id)setSelectedRuleId("");}
  async function save(){if(!canManage||busy)return;setBusy("save");setMessage("");try{if(!target.passportId)throw new Error("This object needs a Passport before policy can be persisted.");const next=normalizeIXIAuthorityPolicy({...policy,target,audit:{...obj(policy.audit),updatedAt:new Date().toISOString(),updatedBy:actorPassportId}});const response=typeof onPolicyChange==="function"?await onPolicyChange(next,context):await IXIAuthorityClient.putIXIAuthorityPolicy({passportId:target.passportId,policy:next,accessToken:clean(actor?.accessToken||authority?.accessToken),entityId:clean(actor?.entityId||authority?.entityId)});setPolicy(normalizeIXIAuthorityPolicy(response?.data?.policy||response?.policy||next));setMessage("ACCESS POLICY SAVED");}catch(error){setMessage(clean(error?.message)||"ACCESS POLICY SAVE FAILED");}finally{setBusy("");}}
  async function invite(){if(!canInvite||busy)return;if(!clean(email)){setMessage("EMAIL IS REQUIRED TO GRANT LOGIN ACCESS");return;}setBusy("invite");setMessage("");const payload={target,email:clean(email),roleIds:roleId?[clean(roleId)]:[],directGrants:[],directDenies:[],scopes:target.passportId?[target.passportId]:[]};try{const response=typeof onIdentityChange==="function"?await onIdentityChange({action:"invite",...payload},context):await IXIAuthorityClient.inviteIXIPrincipal({...payload,accessToken:clean(actor?.accessToken||authority?.accessToken),entityId:clean(actor?.entityId||authority?.entityId)});setMessage(response?.data?.invitationId?`INVITATION SENT · ${response.data.invitationId}`:"INVITATION SENT");}catch(error){setMessage(clean(error?.message)||"INVITATION FAILED");}finally{setBusy("");}}

  return <div className="access-app">
    <header><div><small>IXI AUTHORITY</small><strong>ACCESS / POLICY</strong><span>{target.label}</span></div><button onClick={()=>onBack?.()}>BACK</button></header>
    <main>
      <section><div className="head"><b>IDENTITY ACCESS</b><em>{clean(principal.status)||"NO LOGIN"}</em></div><div className="passport">{target.passportId||"PASSPORT REQUIRED"}</div>{canInvite?<><label>EMAIL<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label><label>INITIAL ROLE<input value={roleId} onChange={e=>setRoleId(e.target.value)} placeholder="role id"/></label><button className="primary" disabled={busy==="invite"} onClick={invite}>{busy==="invite"?"SENDING…":"GRANT / RESEND LOGIN ACCESS"}</button></>:<p>Read-only effective access. An authorized administrator can manage identity and policy.</p>}</section>
      <section><div className="head"><b>OBJECT POLICY</b><em>{canManage?"ADMIN":"READ ONLY"}</em></div><label className="check"><input type="checkbox" checked={policy.inheritance.inheritFromAncestors} disabled={!canManage} onChange={e=>patchPolicy({inheritance:{...policy.inheritance,inheritFromAncestors:e.target.checked}})}/> INHERIT ANCESTOR POLICY</label><label className="check"><input type="checkbox" checked={policy.inheritance.propagateToChildren} disabled={!canManage} onChange={e=>patchPolicy({inheritance:{...policy.inheritance,propagateToChildren:e.target.checked}})}/> PROPAGATE TO CHILDREN</label><div className="rules">{policy.rules.length?policy.rules.map(rule=><button key={rule.ruleId} className={selectedRuleId===rule.ruleId?"rule active":"rule"} onClick={()=>setSelectedRuleId(rule.ruleId)}><strong>{rule.effect.toUpperCase()}</strong><span>{rule.subject.type}:{rule.subject.id||"*"}</span><em>{rule.capabilities.length} CAP</em></button>):<p>NO EXPLICIT RULES · DEFAULT DENY</p>}</div>{canManage?<button className="secondary" onClick={addRule}>+ ADD POLICY RULE</button>:null}</section>
      {selected?<section><div className="head"><b>RULE</b>{canManage?<button onClick={()=>removeRule(selected.ruleId)}>REMOVE</button>:null}</div><div className="two"><label>EFFECT<select disabled={!canManage} value={selected.effect} onChange={e=>patchRule(selected.ruleId,{effect:e.target.value})}><option value="allow">ALLOW</option><option value="deny">DENY</option></select></label><label>SUBJECT<select disabled={!canManage} value={selected.subject.type} onChange={e=>patchRule(selected.ruleId,{subject:{...selected.subject,type:e.target.value}})}>{IXI_AUTHORITY_SUBJECT_TYPES.map(type=><option key={type}>{type}</option>)}</select></label></div><label>SUBJECT ID<input disabled={!canManage||selected.subject.type==="all-authenticated"} value={selected.subject.id} onChange={e=>patchRule(selected.ruleId,{subject:{...selected.subject,id:e.target.value}})}/></label><label>SCOPE<select disabled={!canManage} value={selected.scope.type} onChange={e=>patchRule(selected.ruleId,{scope:{...selected.scope,type:e.target.value,passportId:target.passportId}})}>{IXI_AUTHORITY_SCOPE_TYPES.map(type=><option key={type}>{type}</option>)}</select></label><div className="capgrid">{Object.entries(grouped).map(([family,items])=><div className="capfamily" key={family}><b>{family.toUpperCase()}</b>{items.map(item=>{const checked=selected.capabilities.includes(item.id);return <label className="check" key={item.id}><input type="checkbox" disabled={!canManage} checked={checked} onChange={e=>patchRule(selected.ruleId,{capabilities:e.target.checked?[...selected.capabilities,item.id]:selected.capabilities.filter(id=>id!==item.id)})}/> {item.label}</label>})}</div>)}</div></section>:null}
      {message?<div className="message">{message}</div>:null}
    </main>
    <footer><span>{canManage?"POLICY ADMINISTRATION":"EFFECTIVE ACCESS"}</span>{canManage?<button className="primary" disabled={busy==="save"} onClick={save}>{busy==="save"?"SAVING…":"SAVE POLICY"}</button>:null}</footer>
    <style jsx>{`.access-app{position:relative;width:298px;height:471px;overflow:hidden;border:1px solid #303630;border-radius:7px;background:#080a09;color:#eef1ef;font-family:Arial,sans-serif}.access-app *{box-sizing:border-box}header{height:52px;display:flex;align-items:center;justify-content:space-between;padding:7px 8px;border-bottom:1px solid #303630;background:#121613}header small,header strong,header span{display:block}header small{font-size:5px;color:#818983}header strong{margin-top:2px;font-size:8px;color:#ffc400}header span{margin-top:3px;max-width:210px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:6px;color:#c7cdc9}button{cursor:pointer}header button,.head button{height:22px;border:1px solid #3c443f;border-radius:4px;background:#0c0f0d;color:#b8bfba;font-size:5px;font-weight:900}main{position:absolute;inset:52px 0 42px;overflow-y:auto;padding:7px}section{margin-bottom:7px;padding:7px;border:1px solid #2d332e;border-radius:5px;background:#111512}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:7px}.head b{font-size:6px;color:#ffc400}.head em{font-size:5px;color:#828b85;font-style:normal}.passport,p{padding:6px;border:1px dashed #343b36;border-radius:4px;color:#7f8882;font-size:5px}.passport{margin-bottom:7px}label{display:block;margin-bottom:6px;color:#929b95;font-size:5px;font-weight:900}input:not([type=checkbox]),select{width:100%;height:25px;margin-top:3px;padding:0 6px;border:1px solid #343b36;border-radius:4px;background:#090c0a;color:#eef1ef;font-size:6px}.check{margin:0 0 4px}.primary,.secondary{height:25px;padding:0 8px;border-radius:4px;font-size:6px;font-weight:950}.primary{border:1px solid #846f19;background:#29250f;color:#ffc400}.secondary{border:1px solid #3b433e;background:#0c0f0d;color:#d5dad7}.rules{display:flex;flex-direction:column;gap:4px;margin:6px 0}.rule{height:27px;display:grid;grid-template-columns:42px 1fr 34px;align-items:center;gap:3px;padding:0 6px;border:1px solid #303732;border-radius:4px;background:#0b0e0c;color:#c6ccc8;text-align:left}.rule.active{border-color:#75631e;background:#19180d}.rule strong{font-size:5px;color:#ffc400}.rule span{font-size:5px;overflow:hidden;text-overflow:ellipsis}.rule em{font-size:4.5px;color:#7f8882;font-style:normal}.two,.capgrid{display:grid;grid-template-columns:1fr 1fr;gap:5px}.capfamily{padding:5px;border:1px solid #2b312d;border-radius:4px;background:#0c0f0d}.capfamily>b{display:block;margin-bottom:5px;color:#ffc400;font-size:5px}.capfamily .check{font-size:4.7px}.message{padding:7px;border:1px solid #5c521f;border-radius:4px;background:#18160c;color:#ffc400;font-size:5.5px;font-weight:900}footer{position:absolute;left:0;right:0;bottom:0;height:42px;display:flex;align-items:center;justify-content:space-between;padding:0 7px;border-top:1px solid #2c322e;background:#0d100e}footer span{font-size:5px;color:#737c76;font-weight:900}`}</style>
  </div>;
}
