import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
const clean = value => String(value ?? "").trim();
const usd = value => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value || 0));
export default function SalesSignPage() {
  const router = useRouter(); const token = clean(router.query.token); const [order, setOrder] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [form, setForm] = useState({ signerName: "", signerTitle: "", signerDate: new Date().toISOString().slice(0,10), signatureValue: "", consent: false });
  useEffect(() => { if (!token) return; fetch(`/api/ixi/sales-signing/${encodeURIComponent(token)}`, { credentials: "omit" }).then(async r => { const p = await r.json(); if (!r.ok || !p.ok) throw new Error(p?.errors?.[0]?.message || "Sales Order unavailable."); setOrder(p.data.order); }).catch(e => setError(clean(e.message))); }, [token]);
  async function sign() { setBusy(true); setError(""); try { const response = await fetch(`/api/ixi/sales-signing/${encodeURIComponent(token)}/complete`, { method: "POST", credentials: "omit", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, signatureType: "typed" }) }); const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error(payload?.errors?.[0]?.message || "Signature could not be completed."); await router.push(`/run-your-business-on-ixi?completed=sales-order&invoice=${encodeURIComponent(payload?.data?.invoice?.documentNumber || "generated")}`); } catch (e) { setError(clean(e.message)); } finally { setBusy(false); } }
  if (error && !order) return <main className="sign-shell"><div className="sign-error"><h1>THIS SIGNING LINK IS NOT AVAILABLE</h1><p>{error}</p></div><Styles /></main>;
  if (!order) return <main className="sign-shell"><h1>LOADING SECURE SALES ORDER…</h1><Styles /></main>;
  return <><Head><title>Review and Sign {order?.identity?.number}</title><meta name="robots" content="noindex,nofollow" /></Head><main className="sign-shell"><header><div><small>{order?.brand?.companyName}</small><h1>REVIEW &amp; SIGN</h1></div><b>{order?.identity?.number}</b></header><section className="sign-summary"><div><span>CUSTOMER</span><strong>{order?.customer?.name}</strong></div><div><span>EQUIPMENT</span><strong>{order?.asset?.label}</strong><small>Serial / VIN {order?.asset?.serialNumber}</small></div><div><span>AGREED TOTAL</span><strong>{usd(order?.totals?.total)}</strong><small>Balance due {usd(order?.totals?.balanceDue)}</small></div></section><section className="sign-order"><h2>SALES ORDER</h2><dl><dt>Payment</dt><dd>{order?.commercial?.paymentTerms}</dd><dt>Delivery</dt><dd>{order?.commercial?.deliveryTerms}</dd><dt>Deposit</dt><dd>{usd(order?.totals?.deposit)}</dd><dt>Tax</dt><dd>{usd(order?.totals?.tax)}</dd><dt>Trade allowance</dt><dd>{usd(order?.totals?.tradeAllowance)}</dd></dl></section><section className="sign-terms"><h2>TERMS &amp; CONDITIONS · 2 PAGES</h2><p>Document {order?.termsDocument?.documentId} · Version {order?.termsDocument?.version}</p><iframe title="Terms and Conditions" src={order?.termsDocument?.url} /></section><section className="sign-form"><h2>CUSTOMER ACCEPTANCE</h2><label>FULL LEGAL NAME<input value={form.signerName} onChange={e => setForm({...form, signerName:e.target.value, signatureValue:e.target.value})} /></label><label>TITLE<input value={form.signerTitle} onChange={e => setForm({...form, signerTitle:e.target.value})} /></label><label>DATE<input type="date" value={form.signerDate} onChange={e => setForm({...form, signerDate:e.target.value})} /></label><label className="consent"><input type="checkbox" checked={form.consent} onChange={e => setForm({...form, consent:e.target.checked})} /><span>I have reviewed this Sales Order and both pages of the attached Terms &amp; Conditions. I agree to the price, tax treatment, allowances, payment and delivery terms shown.</span></label><div className="signature"><span>ELECTRONIC SIGNATURE</span><strong>{form.signatureValue || "Your signature appears here"}</strong></div>{error ? <p className="failure">{error}</p> : null}<button disabled={busy || !form.consent || clean(form.signerName).length < 2} onClick={sign}>{busy ? "SECURING AGREEMENT & GENERATING INVOICE…" : "SIGN & ACCEPT SALES ORDER"}</button></section><footer>Protected by IXI TRAN$ACT · The completed agreement and audit evidence are retained with the transaction record.</footer></main><Styles /></>;
}
function Styles(){return <style jsx global>{`body{margin:0;background:#070707}.sign-shell{max-width:980px;margin:auto;min-height:100vh;background:#f6f4ef;color:#111;font-family:Arial,sans-serif;padding:30px;box-sizing:border-box}.sign-shell>header{display:flex;justify-content:space-between;align-items:end;border-bottom:6px solid #111}.sign-shell h1{font-size:38px;margin:6px 0}.sign-shell h2{font-size:13px;letter-spacing:1.5px}.sign-summary{display:grid;grid-template-columns:1fr 1.5fr 1fr;gap:10px;margin:25px 0}.sign-summary>div{background:#111;color:#fff;padding:18px;display:flex;flex-direction:column;gap:7px}.sign-summary span,label>span{font-size:9px;letter-spacing:1px;color:#ffc400}.sign-summary strong{font-size:18px}.sign-order,.sign-terms,.sign-form{background:#fff;border:1px solid #ccc;padding:22px;margin-bottom:15px}.sign-order dl{display:grid;grid-template-columns:160px 1fr}.sign-order dt,.sign-order dd{padding:8px;border-bottom:1px solid #ddd;margin:0}.sign-terms iframe{width:100%;height:680px;border:1px solid #aaa}.sign-form{display:grid;gap:12px}.sign-form label{display:grid;gap:5px;font-size:10px;font-weight:bold}.sign-form input{padding:12px;border:1px solid #777;font-size:15px}.sign-form .consent{display:flex;align-items:flex-start;gap:10px;background:#f1eddc;padding:15px}.sign-form .consent input{width:20px;height:20px}.sign-form .consent span{color:#111;font-size:12px;line-height:1.5}.signature{border-bottom:2px solid #111;padding:25px 10px 8px;display:flex;flex-direction:column}.signature strong{font:italic 30px Georgia}.sign-form button{padding:16px;background:#ffc400;border:0;font-weight:900;font-size:15px}.sign-form button:disabled{opacity:.4}.failure,.sign-error{background:#7a1919;color:#fff;padding:15px}.sign-shell>footer{text-align:center;padding:20px;font-size:10px}@media(max-width:680px){.sign-shell{padding:15px}.sign-summary{grid-template-columns:1fr}.sign-terms iframe{height:480px}}`}</style>}
