import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import IXITransactDashboardNavigation from "./IXITransactDashboardNavigation";
import IXITransactDashboardHeader from "./IXITransactDashboardHeader";
import IXITransactDashboardRecordDrawer from "./IXITransactDashboardRecordDrawer";
import IXITransactDashboardStyles from "./IXITransactDashboardStyles";
import IXITransactWorkspaceStyles from "./IXITransactWorkspaceStyles";
import IXITransactHealthStyles from "./IXITransactHealthStyles";
import IXIExecutiveDashboard from "./executive/IXIExecutiveDashboard";
import IXIAccountsReceivableDesktop from "./workspaces/IXIAccountsReceivableDesktop";
import IXIAccountsPayableDesktop from "./workspaces/IXIAccountsPayableDesktop";
import IXITreasuryDesktop from "./workspaces/IXITreasuryDesktop";
import IXIGeneralLedgerDesktop from "./workspaces/IXIGeneralLedgerDesktop";
import IXIFinancialReportingDesktop from "./workspaces/IXIFinancialReportingDesktop";
import IXIWorkOrdersDesktop from "./workspaces/IXIWorkOrdersDesktop";
import { createIXITransactDashboardQuery } from "./data/IXITransactDashboardQueryContract";
import { loadIXITransactDashboardProjection, checkIXIFinancialHealth } from "./data/IXITransactDashboardClient";
import { createIXIExecutiveDesktopModel, getIXIProjectionFreshness } from "./data/IXITransactDashboardProjectionAdapter";
import {createIXIARDesktopModel,createIXIAPDesktopModel,createIXITreasuryDesktopModel,createIXIGLDesktopModel,createIXIReportingDesktopModel,createIXIOperationsDesktopModel} from "./data/IXITransactDesktopWorkspaceAdapter";
const clean=value=>String(value??"").trim();
const safeObject=value=>value&&typeof value==="object"&&!Array.isArray(value)?value:{};
function Placeholder({workspace}){const label=clean(workspace).replace(/-/g," ").toUpperCase();return <div className="td-workspace-placeholder"><div className="td-workspace-title"><div><span>IXI TRAN$ACT · V13 DESKTOP</span><h1>{label}</h1></div></div><div className="td-empty-state"><span>WORKSPACE FOUNDATION ACTIVE</span><strong>{label}</strong><p>This workspace will consume canonical IXI Financial / TRAN$ACT projections. No local accounting truth is fabricated.</p></div></div>}
export default function IXITransactDashboardApp({entityPassportIds=[],entityLabel="",accountingPeriod="",from="",through="",locationPassportIds=[],locationLabel="ALL LOCATIONS",currency="USD",apiBaseUrl="",initialWorkspace="executive",initialProjection=null,workspaceFilters={},onWorkspaceChange=null,onWorkspaceFiltersChange=null,onOpenCanonicalRecord=null}){
 const[workspace,setWorkspace]=useState(initialWorkspace||"executive"),[projection,setProjection]=useState(initialProjection),[status,setStatus]=useState(initialProjection?"current":"idle"),[error,setError]=useState(""),[selectedRecord,setSelectedRecord]=useState(null),[searchValue,setSearchValue]=useState(""),[financialHealth,setFinancialHealth]=useState({ok:false,label:"CHECKING"});
 const requestRef=useRef(null),healthRef=useRef(null);const normalizedFilters=safeObject(workspaceFilters);const queryKey=JSON.stringify({entityPassportIds,locationPassportIds,from,through,accountingPeriod,currency,workspace,filters:normalizedFilters});
 const query=useMemo(()=>createIXITransactDashboardQuery({scope:{entityPassportIds,locationPassportIds},period:{from,through,accountingPeriod},currency,filters:{workspace,...normalizedFilters},include:["executive","attention","ar","ap","treasury","gl-controls","reporting","operations","work-orders"]}),[queryKey]);
 const hasEntityScope=entityPassportIds.some(Boolean),hasPeriod=Boolean(clean(accountingPeriod||through));
 useEffect(()=>{const next=clean(initialWorkspace||"executive");setWorkspace(current=>next&&next!==current?next:current)},[initialWorkspace]);
 useEffect(()=>{healthRef.current?.abort?.();const controller=new AbortController();healthRef.current=controller;checkIXIFinancialHealth({apiBaseUrl,signal:controller.signal}).then(setFinancialHealth).catch(()=>{});return()=>controller.abort()},[apiBaseUrl]);
 const selectWorkspace=next=>{const resolved=clean(next||"executive");setWorkspace(resolved);setSelectedRecord(null);onWorkspaceChange?.(resolved)};
 const loadProjection=useCallback(async({bypassCache=false}={})=>{if(!hasEntityScope||!hasPeriod)return;requestRef.current?.abort?.();const controller=new AbortController();requestRef.current=controller;setStatus(current=>current==="idle"?"loading":"refreshing");setError("");try{const result=await loadIXITransactDashboardProjection({query,apiBaseUrl,signal:controller.signal,bypassCache});setProjection(result);setStatus(result.status||"current");setFinancialHealth(current=>({...current,ok:true,label:"ONLINE"}))}catch(cause){if(cause?.name==="AbortError")return;setError(cause?.message||"IXI Financial projection unavailable.");setStatus("error")}},[hasEntityScope,hasPeriod,query,apiBaseUrl]);
 useEffect(()=>{if(!initialProjection)loadProjection();return()=>requestRef.current?.abort?.()},[loadProjection,initialProjection]);
 const executiveModel=useMemo(()=>createIXIExecutiveDesktopModel(projection||{}),[projection]),arModel=useMemo(()=>createIXIARDesktopModel(projection||{}),[projection]),apModel=useMemo(()=>createIXIAPDesktopModel(projection||{}),[projection]),treasuryModel=useMemo(()=>createIXITreasuryDesktopModel(projection||{}),[projection]),glModel=useMemo(()=>createIXIGLDesktopModel(projection||{}),[projection]),reportingModel=useMemo(()=>createIXIReportingDesktopModel(projection||{}),[projection]),operationsModel=useMemo(()=>createIXIOperationsDesktopModel(projection||{}),[projection]);
 const freshness=useMemo(()=>status==="error"?{label:"ERROR",state:"stale"}:status==="loading"?{label:"LOADING",state:"aging"}:status==="refreshing"?{label:"REFRESHING",state:"aging"}:status==="partial"?{label:"PARTIAL",state:"aging"}:getIXIProjectionFreshness(executiveModel),[executiveModel,status]);
 const handleSearch=value=>{const q=clean(value);if(q)setSelectedRecord({title:q,sourceRecordId:q,type:"search",detail:"Global deterministic record search requires the server record resolver. No local financial records are guessed."})};let content=null;
 const commonWorkspaceProps={filters:normalizedFilters,onFiltersChange:onWorkspaceFiltersChange,onOpenRecord:setSelectedRecord};
 if(!hasEntityScope)content=<div className="td-empty-state"><span>FINANCIAL SCOPE REQUIRED</span><strong>SELECT AN AUTHORIZED ENTITY</strong><p>IXI TRAN$ACT will not show company financial numbers until an authorized entity Passport has been resolved.</p></div>;else if(!hasPeriod)content=<div className="td-empty-state"><span>ACCOUNTING PERIOD REQUIRED</span><strong>SELECT PERIOD / AS-OF DATE</strong><p>Reporting semantics are period-aware. The dashboard will not invent a default reporting period.</p></div>;else if(!projection&&(status==="loading"||status==="refreshing"))content=<div className="td-empty-state"><span>IXI FINANCIAL</span><strong>LOADING VERIFIED PROJECTION</strong><p>Requesting entity, period and control projections from AWS IXI Financial.</p></div>;else if(status==="error"&&!projection)content=<div className="td-empty-state"><span>PROJECTION UNAVAILABLE</span><strong>NO FINANCIAL TRUTH DISPLAYED</strong><p>{error}</p><button type="button" onClick={()=>loadProjection({bypassCache:true})}>RETRY IXI FINANCIAL</button></div>;else if(workspace==="executive")content=<IXIExecutiveDashboard model={executiveModel} onOpenRecord={setSelectedRecord}/>;else if(workspace==="ar")content=<IXIAccountsReceivableDesktop model={arModel} {...commonWorkspaceProps}/>;else if(workspace==="ap")content=<IXIAccountsPayableDesktop model={apModel} {...commonWorkspaceProps}/>;else if(workspace==="treasury")content=<IXITreasuryDesktop model={treasuryModel} onOpenRecord={setSelectedRecord}/>;else if(workspace==="gl"||workspace==="close")content=<IXIGeneralLedgerDesktop model={glModel} onOpenRecord={setSelectedRecord}/>;else if(workspace==="reporting"||workspace==="profitability")content=<IXIFinancialReportingDesktop model={reportingModel} onOpenRecord={setSelectedRecord}/>;else if(workspace==="work-orders")content=<IXIWorkOrdersDesktop model={operationsModel} {...commonWorkspaceProps}/>;else content=<Placeholder workspace={workspace}/>;
 return <div className="ixi-transact-desktop"><IXITransactDashboardNavigation activeWorkspace={workspace} onSelect={selectWorkspace} financialHealth={financialHealth}/><IXITransactDashboardHeader entityLabel={entityLabel||entityPassportIds[0]||"ENTITY"} accountingPeriod={accountingPeriod||through} locationLabel={locationLabel} freshness={freshness} generatedAt={executiveModel.generatedAt} attentionCount={executiveModel.attention?.length||0} onRefresh={()=>loadProjection({bypassCache:true})} searchValue={searchValue} onSearchChange={setSearchValue} onSearch={handleSearch}/><main className="td-main">{status==="error"&&projection?<div className="td-drawer-note">STALE / LAST USABLE PROJECTION · Refresh failed: {error}</div>:null}{status==="partial"&&projection?<div className="td-drawer-note">PARTIAL IXI FINANCIAL PROJECTION · Missing: {(projection.missingSections||[]).join(", ")||"server sections"}</div>:null}{content}</main><IXITransactDashboardRecordDrawer record={selectedRecord} onClose={()=>setSelectedRecord(null)} onOpenCanonical={onOpenCanonicalRecord}/><IXITransactDashboardStyles/><IXITransactWorkspaceStyles/><IXITransactHealthStyles/></div>;
}
