export default function IXITransactDashboardStyles() {
  return <style jsx global>{`
    .ixi-transact-desktop,.ixi-transact-desktop *{box-sizing:border-box}
    .ixi-transact-desktop{--tx-yellow:#ffc400;--tx-bg:#090b0a;--tx-panel:#0e1110;--tx-panel2:#111513;--tx-line:#2a2f2c;--tx-soft:#7d857f;--tx-white:#f3f5f3;--tx-green:#3bd47b;--tx-red:#ff6565;--tx-cyan:#5fc7d8;position:fixed;inset:0;display:grid;grid-template-columns:236px minmax(0,1fr);grid-template-rows:64px minmax(0,1fr);background:radial-gradient(circle at 54% -10%,rgba(255,255,255,.05),transparent 31%),linear-gradient(180deg,#0d100f,#080a09 55%,#0b0e0c);color:var(--tx-white);font-family:"Arial Narrow",Arial,sans-serif;overflow:hidden}
    .td-nav{grid-row:1/3;display:flex;min-height:0;flex-direction:column;border-right:1px solid var(--tx-line);background:linear-gradient(180deg,#0f1210,#090b0a 70%);box-shadow:8px 0 30px rgba(0,0,0,.18)}
    .td-nav-brand{height:64px;padding:12px 15px 9px;border-bottom:1px solid var(--tx-line)}
    .td-nav-brand span{display:block;color:var(--tx-yellow);font-size:8px;font-weight:950;letter-spacing:.18em}.td-nav-brand strong{display:block;margin-top:2px;font-size:21px;line-height:1;font-weight:950;letter-spacing:-.03em}.td-nav-brand small{display:block;margin-top:4px;color:#59605b;font-size:6px;font-weight:950;letter-spacing:.12em}
    .td-nav-scroll{flex:1;overflow:auto;padding:8px 7px 15px;scrollbar-width:thin;scrollbar-color:#333 transparent}.td-nav-group{margin-bottom:10px}.td-nav-group-label{padding:4px 8px;color:#555d58;font-size:7px;font-weight:950;letter-spacing:.16em}.td-nav-item{position:relative;width:100%;min-height:39px;margin:1px 0;padding:7px 9px 6px;border:1px solid transparent;border-radius:4px;background:transparent;color:#b8beb9;text-align:left;cursor:pointer}.td-nav-item:hover{background:#111412;border-color:#252a27}.td-nav-item.on{border-color:rgba(255,196,0,.22);background:linear-gradient(90deg,rgba(255,196,0,.09),rgba(255,196,0,.018));color:#fff}.td-nav-item.on:before{content:"";position:absolute;left:-1px;top:6px;bottom:6px;width:2px;background:var(--tx-yellow)}.td-nav-item span{display:block;font-size:9px;font-weight:950;letter-spacing:.02em}.td-nav-item small{display:block;margin-top:3px;color:#59605b;font-size:6px;font-weight:850}.td-nav-item.on small{color:#8d948f}
    .td-nav-foot{height:34px;padding:10px 12px;border-top:1px solid var(--tx-line);color:#5e665f;font-size:6px;font-weight:950;letter-spacing:.09em}.td-live-dot{display:inline-block;width:6px;height:6px;margin-right:5px;border-radius:50%;background:var(--tx-green);box-shadow:0 0 8px rgba(59,212,123,.45)}
    .td-header{grid-column:2;display:grid;grid-template-columns:minmax(390px,1fr) minmax(300px,520px) auto;align-items:stretch;border-bottom:1px solid var(--tx-line);background:rgba(10,12,11,.94);backdrop-filter:blur(14px)}
    .td-scope{display:flex;min-width:0}.td-scope-block{min-width:150px;padding:12px 14px;border-right:1px solid #202522}.td-scope-block span,.td-workspace-meta span{display:block;color:#626a64;font-size:6px;font-weight:950;letter-spacing:.14em}.td-scope-block strong{display:block;margin-top:4px;max-width:210px;overflow:hidden;color:#e6e9e6;font-size:9px;font-weight:950;text-overflow:ellipsis;white-space:nowrap}.td-scope-location{min-width:180px}
    .td-command-search{align-self:center;height:34px;display:flex;align-items:center;margin:0 10px;border:1px solid #2b312d;border-radius:5px;background:#0b0e0c}.td-command-search span{padding:0 9px;color:var(--tx-yellow);font-size:8px;font-weight:950}.td-command-search input{width:100%;height:100%;border:0;outline:0;background:transparent;color:#e9ece9;font:850 8px "Arial Narrow",Arial,sans-serif;letter-spacing:.02em}.td-command-search input::placeholder{color:#4d554f}
    .td-header-actions{display:flex;align-items:stretch}.td-header-actions button{border:0;border-left:1px solid #202522;background:transparent;color:#8f9791;font:950 7px "Arial Narrow",Arial,sans-serif;cursor:pointer}.td-status{min-width:108px;padding:7px 10px;text-align:left}.td-status b{font-size:7px}.td-status small{display:block;margin-top:3px;color:#505750;font-size:5px}.td-status[data-state="stale"] .td-live-dot,.td-status[data-state="unknown"] .td-live-dot{background:var(--tx-red);box-shadow:none}.td-status[data-state="aging"] .td-live-dot{background:var(--tx-yellow);box-shadow:none}.td-attention-button{min-width:88px}.td-attention-button b{display:inline-flex;min-width:17px;height:17px;margin-left:4px;align-items:center;justify-content:center;border-radius:9px;background:rgba(255,196,0,.11);color:var(--tx-yellow)}.td-user-button{width:55px}
    .td-main{grid-column:2;min-width:0;min-height:0;overflow:auto;padding:17px 18px 26px;scrollbar-width:thin;scrollbar-color:#333 transparent}.td-workspace-title{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:12px}.td-workspace-title span{color:var(--tx-yellow);font-size:7px;font-weight:950;letter-spacing:.15em}.td-workspace-title h1{margin:3px 0 0;font-size:24px;line-height:1;font-weight:950;letter-spacing:-.035em}.td-workspace-meta{text-align:right}.td-workspace-meta strong{display:block;margin-top:4px;color:#78807a;font-size:7px}
    .td-kpi-strip{display:grid;grid-template-columns:repeat(6,minmax(120px,1fr));border:1px solid var(--tx-line);background:#0c0f0d}.td-kpi{min-height:92px;padding:12px 13px;border:0;border-right:1px solid var(--tx-line);background:linear-gradient(180deg,rgba(255,255,255,.016),transparent);color:#f2f4f2;text-align:left;cursor:pointer}.td-kpi:last-child{border-right:0}.td-kpi:hover{background:rgba(255,196,0,.025)}.td-kpi span{display:block;color:#6e766f;font-size:7px;font-weight:950;letter-spacing:.08em}.td-kpi strong{display:block;margin-top:8px;font-size:19px;font-weight:950;letter-spacing:-.03em}.td-kpi small{display:block;margin-top:6px;color:#525952;font-size:5.5px;font-weight:900}.td-kpi.good strong{color:var(--tx-green)}.td-kpi.bad strong{color:var(--tx-red)}
    .td-exec-grid{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(320px,.78fr);grid-auto-rows:minmax(250px,auto);gap:10px;margin-top:10px}.td-panel{position:relative;min-width:0;border:1px solid var(--tx-line);border-radius:5px;background:linear-gradient(180deg,rgba(255,255,255,.014),transparent 32%),#0d100e;overflow:hidden}.td-panel-head{height:47px;display:flex;align-items:center;justify-content:space-between;padding:9px 11px;border-bottom:1px solid #232824}.td-panel-head span{display:block;color:#646c66;font-size:6px;font-weight:950;letter-spacing:.13em}.td-panel-head strong{display:block;margin-top:3px;font-size:10px;font-weight:950}.td-panel-head small{color:#525a54;font-size:6px;font-weight:950}.td-panel-head>b{color:var(--tx-yellow);font-size:17px}.td-chart-stage{height:165px;padding:16px 14px 6px;color:var(--tx-yellow);background:repeating-linear-gradient(0deg,transparent,transparent 39px,rgba(255,255,255,.035) 40px)}.td-chart-stage.cash{color:var(--tx-cyan)}.td-mini-chart{width:100%;height:100%;overflow:visible}.td-chart-empty{height:100%;display:flex;align-items:center;justify-content:center;color:#505750;font-size:7px;font-weight:950;letter-spacing:.08em}.td-panel-foot-grid{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #232824}.td-panel-foot-grid>div{padding:10px;border-right:1px solid #232824}.td-panel-foot-grid>div:last-child{border-right:0}.td-panel-foot-grid span,.td-large-number span{display:block;color:#616862;font-size:6px;font-weight:950}.td-panel-foot-grid b{display:block;margin-top:4px;font-size:10px}.td-large-number{padding:12px;border-top:1px solid #232824}.td-large-number strong{display:block;margin-top:4px;font-size:18px}
    .td-attention-list{max-height:244px;overflow:auto}.td-attention-item{width:100%;min-height:48px;display:grid;grid-template-columns:8px 1fr auto;gap:8px;align-items:center;padding:8px 10px;border:0;border-bottom:1px solid #202522;background:transparent;color:#e7e9e7;text-align:left;cursor:pointer}.td-attention-item:hover{background:#121613}.td-attention-item i{width:5px;height:28px;border-radius:2px;background:var(--tx-yellow)}.td-attention-item.sev-critical i,.td-attention-item.sev-warning i{background:var(--tx-red)}.td-attention-item.sev-info i{background:var(--tx-cyan)}.td-attention-item strong{display:block;font-size:8px}.td-attention-item span{display:block;margin-top:3px;color:#69716a;font-size:6px}.td-attention-item>b{color:var(--tx-yellow);font-size:8px}
    .td-profit-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));padding:8px;gap:6px}.td-profit-list button{min-height:76px;padding:9px;border:1px solid #252a27;border-radius:4px;background:#0a0d0b;color:#ddd;text-align:left;cursor:pointer}.td-profit-list button:hover{border-color:rgba(255,196,0,.28)}.td-profit-list span{display:block;overflow:hidden;font-size:8px;font-weight:950;text-overflow:ellipsis;white-space:nowrap}.td-profit-list b{display:block;margin-top:8px;color:var(--tx-green);font-size:13px}.td-profit-list b.negative{color:var(--tx-red)}.td-profit-list small{display:block;margin-top:3px;color:#565e57;font-size:5.5px;font-weight:900}
    .td-position-strip{display:grid;grid-template-columns:repeat(6,1fr);margin-top:10px;border:1px solid var(--tx-line);background:#0b0e0c}.td-position-strip>div{min-height:70px;padding:11px 12px;border-right:1px solid var(--tx-line)}.td-position-strip>div:last-child{border-right:0}.td-position-strip span{display:block;color:#626a63;font-size:6px;font-weight:950;letter-spacing:.08em}.td-position-strip strong{display:block;margin-top:7px;font-size:13px}.td-position-strip .good strong{color:var(--tx-green)}.td-position-strip .bad strong{color:var(--tx-red)}
    .td-empty-state{min-height:260px;display:flex;flex-direction:column;align-items:center;justify-content:center;border:1px solid #2b302d;border-radius:5px;background:#0c0f0d;text-align:center}.td-empty-state.compact{min-height:130px;border:0;background:transparent;color:#505851;font-size:7px;font-weight:950}.td-empty-state span{color:var(--tx-yellow);font-size:7px;font-weight:950;letter-spacing:.16em}.td-empty-state strong{margin-top:8px;font-size:18px}.td-empty-state p{max-width:540px;margin:8px 20px 0;color:#727a73;font-size:8px;line-height:1.5}.td-empty-state button{margin-top:13px;padding:8px 13px;border:1px solid rgba(255,196,0,.34);border-radius:4px;background:rgba(255,196,0,.06);color:var(--tx-yellow);font:950 7px "Arial Narrow",Arial,sans-serif;cursor:pointer}
    .td-workspace-placeholder{padding-top:4px}.td-workspace-placeholder .td-empty-state{min-height:430px}
    .td-drawer-backdrop{position:fixed;inset:64px 0 0 236px;z-index:18;background:rgba(0,0,0,.28);backdrop-filter:blur(1px)}.td-record-drawer{position:fixed;z-index:19;right:0;top:64px;bottom:0;width:min(520px,42vw);display:flex;flex-direction:column;border-left:1px solid #383e3a;background:linear-gradient(180deg,#111512,#090c0a);box-shadow:-20px 0 60px rgba(0,0,0,.42)}.td-drawer-head{display:flex;justify-content:space-between;align-items:flex-start;padding:15px;border-bottom:1px solid var(--tx-line)}.td-drawer-head span{color:var(--tx-yellow);font-size:6px;font-weight:950}.td-drawer-head strong{display:block;margin-top:4px;font-size:18px}.td-drawer-head small{display:block;margin-top:5px;color:#6a726b;font-size:7px}.td-drawer-head button{border:1px solid #353a37;border-radius:4px;background:#090b0a;color:var(--tx-yellow);font:950 8px "Arial Narrow",Arial,sans-serif;padding:7px 9px}.td-drawer-body{overflow:auto;padding:12px 14px}.td-drawer-field{padding:10px 0;border-bottom:1px solid #232824}.td-drawer-field span{display:block;color:#646c65;font-size:6px;font-weight:950}.td-drawer-field strong{display:block;margin-top:5px;font-size:10px}.td-drawer-note{margin-top:14px;padding:10px;border-left:2px solid var(--tx-yellow);background:rgba(255,196,0,.04);color:#8d958f;font-size:7px;line-height:1.5}
    @media(max-width:1439px){.ixi-transact-desktop{grid-template-columns:196px minmax(0,1fr)}.td-drawer-backdrop{left:196px}.td-header{grid-template-columns:minmax(310px,1fr) minmax(240px,360px) auto}.td-scope-location{display:none}.td-kpi-strip{grid-template-columns:repeat(3,1fr)}.td-kpi:nth-child(3){border-right:0}.td-kpi:nth-child(-n+3){border-bottom:1px solid var(--tx-line)}.td-exec-grid{grid-template-columns:1fr}.td-position-strip{grid-template-columns:repeat(3,1fr)}}
    @media(max-width:1023px){.ixi-transact-desktop{grid-template-columns:68px minmax(0,1fr)}.td-nav-brand strong,.td-nav-brand small,.td-nav-group-label,.td-nav-item small,.td-nav-item span{font-size:0}.td-nav-item{height:42px}.td-nav-item:after{content:"•";display:block;text-align:center;color:#737b74;font-size:14px}.td-nav-item.on:after{color:var(--tx-yellow)}.td-drawer-backdrop{left:68px}.td-header{grid-template-columns:1fr auto}.td-command-search{display:none}.td-scope-block{min-width:130px}.td-main{padding:12px}.td-workspace-title h1{font-size:19px}.td-kpi-strip{grid-template-columns:repeat(2,1fr)}.td-kpi:nth-child(odd){border-right:1px solid var(--tx-line)}.td-kpi:nth-child(even){border-right:0}.td-record-drawer{width:70vw}}
  `}</style>;
}
