import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import IXITransactDashboardNavigation from "./IXITransactDashboardNavigation";
import IXITransactDashboardHeader from "./IXITransactDashboardHeader";
import IXITransactDashboardRecordDrawer,{createIXIRecordIdentifier} from "./IXITransactDashboardRecordDrawer";
import IXITransactDashboardStyles from "./IXITransactDashboardStyles";
import IXITransactWorkspaceStyles from "./IXITransactWorkspaceStyles";
import IXITransactHealthStyles from "./IXITransactHealthStyles";
import IXIExecutiveDashboard from "./executive/IXIExecutiveDashboard";
import IXIAccountsReceivableDesktop from "./workspaces/IXIAccountsReceivableDesktop";
import IXICustomerInvoicesDesktop from "./workspaces/IXICustomerInvoicesDesktop";
import IXIAssetSalesDesktop from "./workspaces/IXIAssetSalesDesktop";
import IXIAccountsPayableDesktop from "./workspaces/IXIAccountsPayableDesktop";
import IXIBillsDesktop from "./workspaces/IXIBillsDesktop";
import IXIPurchaseOrdersDesktop from "./workspaces/IXIPurchaseOrdersDesktop";
import IXITreasuryDesktop from "./workspaces/IXITransactDashboardHeader";
