const aerialLiftDnaKeywords = [
  /* -------------------- */
  /* LIFT ARCHITECTURE DNA */
  /* -------------------- */

  "SCISSOR LIFT",
  "SLAB SCISSOR",
  "ROUGH TERRAIN SCISSOR",
  "ELECTRIC SCISSOR",
  "DIESEL SCISSOR",
  "HYBRID SCISSOR",
  "ARTICULATING BOOM",
  "TELESCOPIC BOOM",
  "STRAIGHT BOOM",
  "KNUCKLE BOOM",
  "VERTICAL MAST",
  "PERSONNEL LIFT",
  "PUSH AROUND LIFT",
  "SELF PROPELLED LIFT",
  "TOWABLE BOOM",
  "TRAILER MOUNTED BOOM",
  "SPIDER LIFT",
  "CRAWLER BOOM",
  "ATRIUM LIFT",
  "BUCKET TRUCK",
  "TELEHANDLER",
  "ROTATING TELEHANDLER",
  "FIXED BOOM TELEHANDLER",
  "FORKLIFT",
  "REACH TRUCK",
  "ORDER PICKER",
  "PALLET JACK",
  "WALKIE STACKER",
  "TRUCK MOUNTED FORKLIFT",

  /* -------------------- */
  /* BOOM SYSTEM DNA */
  /* -------------------- */

  "DUAL RISER BOOM",
  "PRIMARY BOOM",
  "SECONDARY BOOM",
  "RISER BOOM",
  "UPPER BOOM",
  "LOWER BOOM",
  "EXTENDING BOOM",
  "FIXED BOOM",
  "ROTATING BOOM",
  "BOOM EXTENSION",
  "BOOM WEAR PADS",
  "BOOM LIFT CYLINDER",
  "BOOM TELESCOPE CYLINDER",
  "BOOM CABLES",
  "BOOM CHAINS",
  "BOOM REST",
  "LOW PROFILE BOOM",
  "ULTRA BOOM",
  "X BOOM",
  "XC BOOM",
  "HIGH CAPACITY BOOM",

  /* -------------------- */
  /* JIB SYSTEM DNA */
  /* -------------------- */

  "JIB",
  "ARTICULATING JIB",
  "TELESCOPIC JIB",
  "ROTATING JIB",
  "JIB PLUS",
  "JIB BOOM",
  "PENDULAR JIB",
  "VERTICAL JIB",
  "HORIZONTAL JIB ROTATION",
  "JIB LIFT CYLINDER",
  "JIB ROTATOR",
  "JIB EXTENSION",
  "NO JIB",

  /* -------------------- */
  /* PLATFORM DNA */
  /* -------------------- */

  "PLATFORM",
  "WORK PLATFORM",
  "ROTATING PLATFORM",
  "PLATFORM ROTATION",
  "HYDRAULIC PLATFORM ROTATION",
  "MANUAL PLATFORM ROTATION",
  "SELF LEVELING PLATFORM",
  "PLATFORM LEVELING",
  "PLATFORM EXTENSION",
  "ROLL OUT DECK",
  "EXTENSION DECK",
  "DUAL EXTENSION DECK",
  "POWERED DECK EXTENSION",
  "MANUAL DECK EXTENSION",
  "HIGH CAPACITY PLATFORM",
  "DUAL CAPACITY PLATFORM",
  "WIDE PLATFORM",
  "NARROW PLATFORM",
  "MATERIAL CARRIER",
  "PIPE RACK",
  "GLAZIER PACKAGE",
  "PANEL CARRIER",
  "PLATFORM GATE",
  "SWING GATE",
  "SALoon GATE",
  "PLATFORM CONTROLS",
  "GROUND CONTROLS",
  "AC POWER TO PLATFORM",
  "AIR LINE TO PLATFORM",

  /* -------------------- */
  /* SCISSOR STACK DNA */
  /* -------------------- */

  "SCISSOR STACK",
  "SINGLE SCISSOR STACK",
  "DOUBLE SCISSOR STACK",
  "HEAVY DUTY SCISSOR STACK",
  "SCISSOR ARM",
  "SCISSOR LINKAGE",
  "LIFT CYLINDER",
  "DUAL LIFT CYLINDERS",
  "POTHOLE PROTECTION",
  "FIXED RAILS",
  "FOLDING RAILS",
  "ROLL OUT EXTENSION",
  "DECK EXTENSION",
  "SLAB SCISSOR CHASSIS",
  "ROUGH TERRAIN SCISSOR CHASSIS",

  /* -------------------- */
  /* MAST LIFT DNA */
  /* -------------------- */

  "TELESCOPIC MAST",
  "ALUMINUM MAST",
  "SINGLE MAST",
  "DUAL MAST",
  "MAST BOOM",
  "MAST JIB",
  "PERSONNEL LIFT MAST",
  "PUSH AROUND MAST",
  "SELF PROPELLED MAST",
  "DRIVABLE MAST LIFT",
  "STOCK PICKER",
  "ORDER PICKER PLATFORM",
  "LOW LEVEL ACCESS LIFT",

  /* -------------------- */
  /* OUTRIGGER DNA */
  /* -------------------- */

  "OUTRIGGERS",
  "HYDRAULIC OUTRIGGERS",
  "MANUAL OUTRIGGERS",
  "AUTO LEVELING OUTRIGGERS",
  "SELF LEVELING OUTRIGGERS",
  "SPIDER OUTRIGGERS",
  "A FRAME OUTRIGGERS",
  "H TYPE OUTRIGGERS",
  "VERTICAL OUTRIGGERS",
  "OUTRIGGER PADS",
  "OUTRIGGER INTERLOCK",
  "OUTRIGGER CONTROLS",
  "STABILIZERS",
  "HYDRAULIC STABILIZERS",
  "MANUAL STABILIZERS",
  "NO OUTRIGGERS",

  /* -------------------- */
  /* DRIVE SYSTEM DNA */
  /* -------------------- */

  "SELF PROPELLED",
  "TOWABLE",
  "PUSH AROUND",
  "2WD",
  "4WD",
  "ALL WHEEL DRIVE",
  "FRONT WHEEL DRIVE",
  "REAR WHEEL DRIVE",
  "TRACK DRIVE",
  "CRAWLER DRIVE",
  "HYDROSTATIC DRIVE",
  "ELECTRIC DRIVE",
  "HYDRAULIC DRIVE",
  "DIRECT ELECTRIC DRIVE",
  "AC DRIVE MOTORS",
  "DC DRIVE MOTORS",
  "WHEEL DRIVE MOTORS",
  "TRACK DRIVE MOTORS",
  "OSCILLATING AXLE",
  "ACTIVE OSCILLATION",
  "AUTOMATIC TRACTION CONTROL",
  "LIMITED SLIP DIFFERENTIAL",
  "DIFFERENTIAL LOCK",
  "GRADEABILITY PACKAGE",

  /* -------------------- */
  /* STEERING DNA */
  /* -------------------- */

  "TWO WHEEL STEER",
  "FOUR WHEEL STEER",
  "FRONT WHEEL STEER",
  "REAR WHEEL STEER",
  "CRAB STEER",
  "COORDINATED STEER",
  "OSCILLATING STEER AXLE",
  "ZERO INSIDE TURNING RADIUS",
  "TIGHT TURNING RADIUS",
  "HYDRAULIC STEERING",
  "ELECTRIC STEERING",
  "STEER CYLINDERS",
  "STEER AXLE",
  "DRIVE AND STEER AXLE",

  /* -------------------- */
  /* TRACK / TIRE DNA */
  /* -------------------- */

  "CRAWLER",
  "TRACKED MACHINE",
  "RUBBER TRACKS",
  "NON MARKING TRACKS",
  "STEEL TRACKS",
  "TRACKED CRAWLER",
  "SPIDER TRACKS",
  "OUTRIGGER TRACK CHASSIS",
  "NON MARKING TIRES",
  "ROUGH TERRAIN TIRES",
  "FOAM FILLED TIRES",
  "SOLID TIRES",
  "PNEUMATIC TIRES",
  "TURF TIRES",
  "HIGH FLOATATION TIRES",
  "LUG TREAD TIRES",
  "BAR LUG TIRES",
  "INDUSTRIAL TIRES",
  "CUSHION TIRES",
  "PNEUMATIC FORKLIFT TIRES",
  "DUAL FRONT TIRES",
  "WIDE TIRES",
  "NARROW TIRES",

  /* -------------------- */
  /* POWERTRAIN DNA */
  /* -------------------- */

  "ELECTRIC",
  "DIESEL",
  "GAS",
  "LPG",
  "DUAL FUEL",
  "BI ENERGY",
  "HYBRID",
  "DIESEL ELECTRIC HYBRID",
  "BATTERY ELECTRIC",
  "DC ELECTRIC",
  "AC ELECTRIC",
  "ENGINE POWERED",
  "GENERATOR POWERED",
  "AUXILIARY POWER UNIT",
  "HYDROSTATIC TRANSMISSION",
  "POWERSHIFT TRANSMISSION",
  "TORQUE CONVERTER TRANSMISSION",
  "DIRECT DRIVE TRANSMISSION",
  "ELECTRIC DRIVE MOTORS",

  /* -------------------- */
  /* BATTERY / ELECTRIC DNA */
  /* -------------------- */

  "LEAD ACID BATTERY",
  "AGM BATTERY",
  "LITHIUM BATTERY",
  "LITHIUM ION",
  "48V SYSTEM",
  "24V SYSTEM",
  "36V SYSTEM",
  "80V SYSTEM",
  "ONBOARD CHARGER",
  "OFFBOARD CHARGER",
  "FAST CHARGE",
  "BATTERY TRAY",
  "BATTERY ROLL OUT",
  "BATTERY WATERING SYSTEM",
  "BATTERY MANAGEMENT SYSTEM",
  "AC DRIVE",
  "DC DRIVE",
  "ELECTRIC LIFT PUMP",
  "ELECTRIC HYDRAULIC PUMP",

  /* -------------------- */
  /* ROUGH TERRAIN DNA */
  /* -------------------- */

  "ROUGH TERRAIN",
  "RT",
  "ROUGH TERRAIN PACKAGE",
  "4WD ROUGH TERRAIN",
  "FOAM FILLED ROUGH TERRAIN TIRES",
  "HIGH GROUND CLEARANCE",
  "TILT ALARM",
  "LEVEL SENSOR",
  "AXLE LOCK",
  "TRACTION CONTROL",

  /* -------------------- */
  /* HEIGHT / REACH DNA */
  /* -------------------- */

  "HIGH REACH",
  "SUPER BOOM",
  "XTRA CAPACITY",
  "XC",
  "DUAL CAPACITY",
  "UNRESTRICTED CAPACITY",
  "RESTRICTED CAPACITY",
  "HORIZONTAL OUTREACH",
  "UP AND OVER REACH",
  "WORKING HEIGHT",
  "PLATFORM HEIGHT",
  "OUTREACH LIMITING",
  "ENVELOPE CONTROL",
  "LOAD MOMENT LIMITING",
  "RANGE MANAGEMENT",

  /* -------------------- */
  /* ROTATION / SWING DNA */
  /* -------------------- */

  "TURNTABLE ROTATION",
  "CONTINUOUS ROTATION",
  "NON CONTINUOUS ROTATION",
  "360 ROTATION",
  "355 ROTATION",
  "180 PLATFORM ROTATION",
  "160 PLATFORM ROTATION",
  "HYDRAULIC ROTATION",
  "ELECTRIC ROTATION",
  "SWING DRIVE",
  "SWING MOTOR",
  "SWING BEARING",
  "TURNTABLE LOCK",
  "ROTO TELEHANDLER",
  "SLEWING TELEHANDLER",

  /* -------------------- */
  /* CHASSIS DNA */
  /* -------------------- */

  "SLAB CHASSIS",
  "ROUGH TERRAIN CHASSIS",
  "COMPACT CHASSIS",
  "NARROW CHASSIS",
  "WIDE CHASSIS",
  "CRAWLER CHASSIS",
  "TRAILER CHASSIS",
  "TRUCK MOUNT CHASSIS",
  "LOW PROFILE CHASSIS",
  "HIGH CLEARANCE CHASSIS",
  "TELESCOPIC AXLES",
  "EXTENDABLE AXLES",
  "NARROW WIDTH",
  "COMPACT WIDTH",
  "MICRO SCISSOR CHASSIS",
  "MINI SCISSOR CHASSIS",
  "COUNTERWEIGHT",
  "COUNTERWEIGHTED CHASSIS",

  /* -------------------- */
  /* TELEHANDLER DNA */
  /* -------------------- */

  "HIGH REACH TELEHANDLER",
  "HEAVY LIFT TELEHANDLER",
  "COMPACT TELEHANDLER",
  "LOW PROFILE TELEHANDLER",
  "TELESCOPIC BOOM TELEHANDLER",
  "BOOM CARRIAGE",
  "QUICK ATTACH CARRIAGE",
  "STANDARD CARRIAGE",
  "SIDE TILT CARRIAGE",
  "SWING CARRIAGE",
  "ROTATING CARRIAGE",
  "FORK POSITIONER",
  "HYDRAULIC FORK POSITIONER",
  "AUXILIARY HYDRAULICS",
  "FRAME LEVELING",
  "CHASSIS LEVELING",
  "OUTRIGGER TELEHANDLER",
  "STABILIZER TELEHANDLER",

  /* -------------------- */
  /* FORKLIFT TYPE DNA */
  /* -------------------- */

  "COUNTERBALANCE FORKLIFT",
  "ELECTRIC FORKLIFT",
  "DIESEL FORKLIFT",
  "LPG FORKLIFT",
  "DUAL FUEL FORKLIFT",
  "CUSHION TIRE FORKLIFT",
  "PNEUMATIC TIRE FORKLIFT",
  "ROUGH TERRAIN FORKLIFT",
  "COMPACT FORKLIFT",
  "HEAVY CAPACITY FORKLIFT",
  "HIGH CAPACITY FORKLIFT",
  "PIGGYBACK FORKLIFT",
  "MOFFETT STYLE FORKLIFT",
  "REACH STACKER",
  "CONTAINER HANDLER",
  "EMPTY CONTAINER HANDLER",
  "LOADED CONTAINER HANDLER",

  /* -------------------- */
  /* MAST / CARRIAGE DNA */
  /* -------------------- */

  "TWO STAGE MAST",
  "THREE STAGE MAST",
  "QUAD MAST",
  "DUPLEX MAST",
  "TRIPLEX MAST",
  "FULL FREE LIFT",
  "FREE LIFT MAST",
  "HIGH VISIBILITY MAST",
  "STANDARD MAST",
  "WIDE VIEW MAST",
  "FORK CARRIAGE",
  "CLASS II CARRIAGE",
  "CLASS III CARRIAGE",
  "CLASS IV CARRIAGE",
  "CLASS V CARRIAGE",
  "INTEGRAL SIDESHIFT",
  "HANG ON SIDESHIFT",
  "LOAD BACKREST",
  "FORKS",
  "PALLET FORKS",
  "LUMBER FORKS",
  "FORK EXTENSIONS",

  /* -------------------- */
  /* WAREHOUSE LIFT DNA */
  /* -------------------- */

  "DOUBLE REACH TRUCK",
  "STAND UP REACH",
  "STAND UP COUNTERBALANCE",
  "TURRET TRUCK",
  "SWING REACH TRUCK",
  "VERY NARROW AISLE",
  "VNA",
  "RIDER PALLET JACK",
  "WALKIE PALLET JACK",
  "CENTER RIDER PALLET JACK",
  "END RIDER PALLET JACK",
  "LOW LEVEL ORDER PICKER",
  "HIGH LEVEL ORDER PICKER",
  "MAN UP TRUCK",
  "MAN DOWN TRUCK",
  "STRADDLE STACKER",
  "COUNTERBALANCE STACKER",

  /* -------------------- */
  /* HYDRAULIC SYSTEM DNA */
  /* -------------------- */

  "HYDRAULIC LIFT",
  "HYDRAULIC BOOM",
  "HYDRAULIC JIB",
  "HYDRAULIC PLATFORM LEVELING",
  "HIGH FLOW HYDRAULICS",
  "LOW FLOW HYDRAULICS",
  "PROPORTIONAL HYDRAULICS",
  "LOAD SENSING HYDRAULICS",
  "ELECTROHYDRAULIC CONTROLS",
  "MANUAL HYDRAULIC CONTROLS",
  "HYDRAULIC EMERGENCY LOWERING",
  "MANUAL EMERGENCY LOWERING",

  /* -------------------- */
  /* CONTROL / AUTOMATION DNA */
  /* -------------------- */

  "PROPORTIONAL CONTROLS",
  "JOYSTICK CONTROLS",
  "DRIVE ENABLE",
  "REMOTE CONTROL",
  "WIRELESS REMOTE",
  "PLATFORM CONTROL BOX",
  "GROUND CONTROL BOX",
  "AUTO LEVELING",
  "SELF LEVELING",
  "AUTOMATIC OUTRIGGER LEVELING",
  "LOAD SENSING",
  "LOAD MOMENT INDICATOR",
  "DRIVE CUTOUT",
  "LIFT CUTOUT",
  "HEIGHT LIMITING",
  "TELEMATICS",
  "ACCESS MANAGER",
  "MACHINE CONTROL MODULE",
  "DIAGNOSTIC DISPLAY",

  /* -------------------- */
  /* SAFETY SYSTEM DNA */
  /* -------------------- */

  "SECONDARY GUARDING",
  "SKYGUARD",
  "ANTI CRUSH",
  "OPERATOR PROTECTION SYSTEM",
  "LOAD SENSE SYSTEM",
  "OVERLOAD SENSOR",
  "TILT SENSOR",
  "DESCENT ALARM",
  "MOTION ALARM",
  "OSCILLATING AXLE LOCKOUT",
  "DRIVE ENABLE SYSTEM",
  "PLATFORM GATE INTERLOCK",
  "EMERGENCY LOWERING",
  "AUXILIARY LOWERING",
  "EMERGENCY STOP",
  "FALL ARREST ANCHORS",

  /* -------------------- */
  /* CAB / OPERATOR DNA */
  /* -------------------- */

  "OPEN OPERATOR STATION",
  "ENCLOSED CAB",
  "ROPS CAB",
  "FOPS CAB",
  "LOW PROFILE CAB",
  "ROTATING OPERATOR STATION",
  "ELEVATING OPERATOR PLATFORM",
  "STAND UP OPERATOR COMPARTMENT",
  "SIT DOWN OPERATOR COMPARTMENT",
  "CAB HEATER",
  "AIR CONDITIONED CAB",
  "SUSPENSION SEAT",
  "OPERATOR PRESENCE SYSTEM",
  "DUAL CONTROLS",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4 FINAL",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF"
];

export default aerialLiftDnaKeywords;
