const agricultureHarvesterDnaKeywords = [
  /* -------------------- */
  /* COMBINE TYPE DNA */
  /* -------------------- */

  "CONVENTIONAL COMBINE",
  "WALKER COMBINE",
  "ROTARY COMBINE",
  "AXIAL-FLOW COMBINE",
  "SINGLE ROTOR COMBINE",
  "TWIN ROTOR COMBINE",
  "HYBRID COMBINE",
  "CYLINDER WALKER COMBINE",
  "TRANSVERSE ROTOR COMBINE",
  "LONGITUDINAL ROTOR COMBINE",
  "SELF-LEVELING COMBINE",
  "HILLSIDE COMBINE",
  "SIDEHILL COMBINE",
  "TRACK COMBINE",
  "WHEELED COMBINE",

  /* -------------------- */
  /* THRESHING SYSTEM DNA */
  /* -------------------- */

  "RASP BAR CYLINDER",
  "SPIKE TOOTH CYLINDER",
  "PEG TOOTH CYLINDER",
  "TRANSVERSE THRESHING CYLINDER",
  "AXIAL ROTOR THRESHING",
  "SINGLE ROTOR THRESHING",
  "DUAL ROTOR THRESHING",
  "TWIN ROTOR THRESHING",
  "ACCELERATED PRE-SEPARATION",
  "PRE-THRESHING CYLINDER",
  "APS THRESHING SYSTEM",
  "CROSS-FLOW THRESHING",
  "HIGH-INERTIA ROTOR",
  "SMALL WIRE CONCAVE",
  "LARGE WIRE CONCAVE",
  "ROUND BAR CONCAVE",
  "MAX ROUND BAR CONCAVE",
  "KEELED CONCAVE",
  "SECTIONAL CONCAVE",
  "ADJUSTABLE CONCAVE",
  "HYDRAULIC CONCAVE ADJUSTMENT",
  "ELECTRIC CONCAVE ADJUSTMENT",
  "STONE TRAP",
  "ROCK TRAP",
  "FEED ACCELERATOR",
  "THRESHING BEATER",
  "DISCHARGE BEATER",

  /* -------------------- */
  /* SEPARATION SYSTEM DNA */
  /* -------------------- */

  "STRAW WALKER SEPARATION",
  "ROTARY SEPARATION",
  "AXIAL SEPARATION",
  "TWIN ROTOR SEPARATION",
  "HYBRID ROTOR SEPARATION",
  "SEPARATION GRATES",
  "ROTOR CAGE",
  "ACTIVE SEPARATION",
  "PASSIVE SEPARATION",
  "MULTI-STAGE SEPARATION",
  "SEPARATOR BEATER",
  "REAR BEATER",
  "STRAW WALKER RISERS",
  "ROTARY SEPARATOR",
  "TINE SEPARATOR",
  "POWER SEPARATOR",
  "CENTRIFUGAL SEPARATION",
  "LONGITUDINAL FLOW SEPARATION",

  /* -------------------- */
  /* CLEANING SYSTEM DNA */
  /* -------------------- */

  "CHAFFER SIEVE",
  "SHOE SIEVE",
  "CLEANING SHOE",
  "HIGH-CAPACITY CLEANING SHOE",
  "SELF-LEVELING CLEANING SHOE",
  "HILLSIDE CLEANING SHOE",
  "CROSS-FLOW CLEANING FAN",
  "VARIABLE SPEED CLEANING FAN",
  "ELECTRIC SIEVE ADJUSTMENT",
  "IN-CAB SIEVE ADJUSTMENT",
  "TAILINGS RETURN",
  "TAILINGS RE-THRESHER",
  "ACTIVE TAILINGS SYSTEM",
  "GRAIN LOSS MONITOR",
  "CLEAN GRAIN ELEVATOR",
  "RETURN ELEVATOR",
  "PRE-CLEANER",
  "CASCADE PAN",
  "PREPARATION PAN",
  "DIVIDED CLEANING SHOE",
  "3D CLEANING SYSTEM",
  "4D CLEANING SYSTEM",

  /* -------------------- */
  /* FEEDERHOUSE DNA */
  /* -------------------- */

  "STANDARD FEEDERHOUSE",
  "VARIABLE SPEED FEEDERHOUSE",
  "FIXED SPEED FEEDERHOUSE",
  "LATERAL TILT FEEDERHOUSE",
  "CONTOUR FEEDERHOUSE",
  "REVERSER FEEDERHOUSE",
  "HYDRAULIC FEEDERHOUSE REVERSER",
  "ELECTRIC FEEDERHOUSE REVERSER",
  "HEAVY DUTY FEEDERHOUSE",
  "HIGH CAPACITY FEEDERHOUSE",
  "TILTING FEEDERHOUSE FACEPLATE",
  "HYDRAULIC FORE/AFT FEEDERHOUSE",
  "HEADER HEIGHT CONTROL",
  "AUTO CONTOUR HEADER CONTROL",
  "MULTI-COUPLER HEADER HOOKUP",
  "SINGLE POINT HYDRAULIC COUPLER",
  "HEADER DRIVE SHAFT",
  "PTO HEADER DRIVE",
  "HYDRAULIC HEADER DRIVE",
  "BELT HEADER DRIVE",

  /* -------------------- */
  /* HEADER ADAPTER DNA */
  /* -------------------- */

  "JOHN DEERE ADAPTER",
  "CASE IH ADAPTER",
  "NEW HOLLAND ADAPTER",
  "CLAAS ADAPTER",
  "AGCO ADAPTER",
  "MASSEY FERGUSON ADAPTER",
  "LEXION ADAPTER",
  "FENDT ADAPTER",
  "MACDON ADAPTER",
  "UNIVERSAL HEADER ADAPTER",
  "BISH ADAPTER",
  "FEEDERHOUSE ADAPTER",
  "FORAGE HARVESTER ADAPTER",
  "QUICK ATTACH HEADER ADAPTER",
  "PICKUP HEADER ADAPTER",
  "CORN HEAD ADAPTER",
  "DRAPER ADAPTER",
  "PLATFORM ADAPTER",

  /* -------------------- */
  /* CORN HEAD DNA */
  /* -------------------- */

  "CORN HEAD",
  "RIGID CORN HEAD",
  "FOLDING CORN HEAD",
  "CHOPPING CORN HEAD",
  "NON-CHOPPING CORN HEAD",
  "STALK CHOPPER CORN HEAD",
  "INTERMESHING KNIFE ROLLS",
  "OPPOSED KNIFE ROLLS",
  "FLUTED STALK ROLLS",
  "STRAIGHT FLUTE ROLLS",
  "TAPERED STALK ROLLS",
  "HYDRAULIC DECK PLATES",
  "MANUAL DECK PLATES",
  "AUTO DECK PLATES",
  "POLY SNOUTS",
  "STEEL SNOUTS",
  "LOW PROFILE SNOUTS",
  "DOWN CORN REEL",
  "ROW SENSE CORN HEAD",
  "CORN HEAD AUGER",
  "CORN HEAD GATHERING CHAINS",
  "CORN HEAD ROW UNIT",
  "CORN HEAD SLIP CLUTCH",
  "CORN HEAD STALK STOMPERS",
  "CORN HEAD HEIGHT SENSORS",

  /* -------------------- */
  /* CORN HEAD ROW DNA */
  /* -------------------- */

  "2 ROW CORN HEAD",
  "3 ROW CORN HEAD",
  "4 ROW CORN HEAD",
  "5 ROW CORN HEAD",
  "6 ROW CORN HEAD",
  "8 ROW CORN HEAD",
  "10 ROW CORN HEAD",
  "12 ROW CORN HEAD",
  "16 ROW CORN HEAD",
  "18 ROW CORN HEAD",
  "20 ROW CORN HEAD",
  "24 ROW CORN HEAD",
  "20 INCH ROW CORN HEAD",
  "22 INCH ROW CORN HEAD",
  "30 INCH ROW CORN HEAD",
  "36 INCH ROW CORN HEAD",
  "38 INCH ROW CORN HEAD",
  "NARROW ROW CORN HEAD",
  "WIDE ROW CORN HEAD",
  "TWIN ROW CORN HEAD",

  /* -------------------- */
  /* DRAPER HEADER DNA */
  /* -------------------- */

  "DRAPER HEADER",
  "FLEX DRAPER",
  "RIGID DRAPER",
  "HINGED DRAPER",
  "CENTER FEED DRAPER",
  "SIDE FEED DRAPER",
  "SPLIT REEL DRAPER",
  "HYDRAULIC FORE/AFT REEL",
  "PICKUP REEL",
  "BATT REEL",
  "FINGER REEL",
  "CAM REEL",
  "REEL FLIPOVER KIT",
  "HYDRAULIC REEL DRIVE",
  "MECHANICAL REEL DRIVE",
  "DRAPER BELT FEED",
  "CENTER DRAPER BELT",
  "SIDE DRAPER BELTS",
  "FLOAT WING DRAPER",
  "FLEX FLOAT CUTTERBAR",
  "RIGID CUTTERBAR",
  "SICKLE CUTTERBAR",
  "DOUBLE KNIFE DRIVE",
  "SCH SICKLE DRIVE",
  "KNIFE DRIVE",
  "GUARD SYSTEM",
  "CROP DIVIDERS",
  "END DIVIDERS",
  "SKID SHOES",
  "GAUGE WHEELS",
  "TRANSPORT WHEELS",

  /* -------------------- */
  /* PLATFORM HEADER DNA */
  /* -------------------- */

  "AUGER PLATFORM",
  "FLEX PLATFORM",
  "RIGID PLATFORM",
  "GRAIN PLATFORM",
  "HYDRA-FLEX PLATFORM",
  "FULL FINGER AUGER",
  "STANDARD AUGER",
  "AIR REEL PLATFORM",
  "AIR BAR PLATFORM",
  "PICKUP REEL PLATFORM",
  "BAT REEL PLATFORM",
  "FLEX CUTTERBAR",
  "LOCKED RIGID CUTTERBAR",
  "FLOATING CUTTERBAR",
  "HYDRAULIC FORE/AFT REEL",
  "HEADER HEIGHT SENSING",
  "LATERAL TILT SENSING",
  "LOW DAM",
  "HIGH DAM",
  "SHORT-LONG DIVIDERS",

  /* -------------------- */
  /* STRIPPER HEADER DNA */
  /* -------------------- */

  "STRIPPER HEADER",
  "SHELBOURNE STRIPPER HEADER",
  "ROTARY STRIPPER HEADER",
  "VARIABLE SPEED STRIPPER ROTOR",
  "FIXED SPEED STRIPPER ROTOR",
  "STRIPPER ROTOR",
  "STRIPPING FINGERS",
  "CROP DEFLECTOR",
  "STRIPPER HEADER AUGER",
  "RICE STRIPPER HEADER",
  "CEREAL STRIPPER HEADER",

  /* -------------------- */
  /* PICKUP / SWATH DNA */
  /* -------------------- */

  "PICKUP HEADER",
  "BELT PICKUP",
  "DRAPER PICKUP",
  "SWATH PICKUP",
  "WINDROW PICKUP",
  "PICKUP BELT",
  "PICKUP TEETH",
  "PICKUP AUGER",
  "PICKUP ROLLER",
  "PICKUP GAUGE WHEELS",
  "PICKUP HEADER FLOAT",
  "HYDRAULIC PICKUP DRIVE",
  "VARIABLE SPEED PICKUP",
  "CROP PRESS ROLLER",
  "SWATH ROLLER",

  /* -------------------- */
  /* FORAGE HARVESTER TYPE DNA */
  /* -------------------- */

  "SELF-PROPELLED FORAGE HARVESTER",
  "PULL-TYPE FORAGE HARVESTER",
  "PTO FORAGE HARVESTER",
  "TRAILED FORAGE HARVESTER",
  "TRACK FORAGE HARVESTER",
  "WHEELED FORAGE HARVESTER",
  "CORN FORAGE HARVESTER",
  "GRASS FORAGE HARVESTER",
  "WHOLECROP FORAGE HARVESTER",

  /* -------------------- */
  /* FORAGE FEEDROLL DNA */
  /* -------------------- */

  "FORAGE FEEDROLLS",
  "4 ROLL FEEDROLL SYSTEM",
  "5 ROLL FEEDROLL SYSTEM",
  "6 ROLL FEEDROLL SYSTEM",
  "HYDRAULIC FEEDROLL DRIVE",
  "HYDROSTATIC FEEDROLL DRIVE",
  "VARIABLE SPEED FEEDROLLS",
  "METAL DETECTOR FEEDROLLS",
  "STONE DETECTOR FEEDROLLS",
  "FEEDROLL REVERSER",
  "PRE-COMPRESSION ROLLERS",
  "CROP PRESS ROLLERS",

  /* -------------------- */
  /* FORAGE CUTTERHEAD DNA */
  /* -------------------- */

  "CUTTERHEAD",
  "V-CLASSIC CUTTERHEAD",
  "V-MAX CUTTERHEAD",
  "MAXFLOW CUTTERHEAD",
  "BIOMASS CUTTERHEAD",
  "GRASS CUTTERHEAD",
  "MAIZE CUTTERHEAD",
  "20 KNIFE CUTTERHEAD",
  "24 KNIFE CUTTERHEAD",
  "28 KNIFE CUTTERHEAD",
  "36 KNIFE CUTTERHEAD",
  "40 KNIFE CUTTERHEAD",
  "48 KNIFE CUTTERHEAD",
  "56 KNIFE CUTTERHEAD",
  "DRUM CUTTERHEAD",
  "KNIFE DRUM",
  "SHEAR BAR",
  "AUTOMATIC KNIFE SHARPENER",
  "KNIFE SHARPENING SYSTEM",
  "SHEAR BAR ADJUSTMENT",
  "ELECTRIC SHEAR BAR ADJUSTMENT",

  /* -------------------- */
  /* KERNEL PROCESSOR DNA */
  /* -------------------- */

  "KERNEL PROCESSOR",
  "CORN CRACKER",
  "ROLLER MILL",
  "SHREDLAGE PROCESSOR",
  "MCC PROCESSOR",
  "MCC MAX PROCESSOR",
  "MCC CLASSIC PROCESSOR",
  "INTENSIVE CRACKER",
  "DISC KERNEL PROCESSOR",
  "ROLL KERNEL PROCESSOR",
  "SAWTOOTH PROCESSOR ROLLS",
  "SPIRAL CUT PROCESSOR ROLLS",
  "CHROME PROCESSOR ROLLS",
  "PROCESSOR ROLL GAP ADJUSTMENT",
  "PROCESSOR ROLL SPEED DIFFERENTIAL",
  "KERNEL PROCESSOR LIFT",
  "KERNEL PROCESSOR REMOVAL SYSTEM",

  /* -------------------- */
  /* FORAGE HEAD DNA */
  /* -------------------- */

  "ROTARY CORN HEAD",
  "ROW INDEPENDENT CORN HEAD",
  "ROW DEPENDENT CORN HEAD",
  "SMALL DRUM CORN HEAD",
  "LARGE DRUM CORN HEAD",
  "DISC MOWER HEADER",
  "DIRECT CUT HEADER",
  "DIRECT DISC HEADER",
  "WHOLECROP HEADER",
  "GRASS PICKUP HEADER",
  "FORAGE PICKUP HEADER",
  "PICKUP HEAD",
  "ORBIS HEAD",
  "KEMPER HEAD",
  "EASY COLLECT HEAD",
  "RU HEAD",
  "PU PICKUP",
  "DIRECT DISC",
  "XDISC HEADER",
  "EASY FLOW PICKUP",

  /* -------------------- */
  /* SPOUT / BLOWER DNA */
  /* -------------------- */

  "FORAGE BLOWER",
  "ACCELERATOR PADDLES",
  "CROP ACCELERATOR",
  "DISCHARGE SPOUT",
  "HIGH ARC SPOUT",
  "LOW ARC SPOUT",
  "HYDRAULIC SPOUT ROTATION",
  "ELECTRIC SPOUT ROTATION",
  "SPOUT DEFLECTOR",
  "AUTO FILL SPOUT CONTROL",
  "TRUCK FILL CONTROL",

  /* -------------------- */
  /* COTTON HARVESTER TYPE DNA */
  /* -------------------- */

  "COTTON PICKER",
  "COTTON STRIPPER",
  "BASKET COTTON PICKER",
  "BASKET COTTON STRIPPER",
  "ONBOARD MODULE COTTON PICKER",
  "ONBOARD MODULE COTTON STRIPPER",
  "ROUND MODULE COTTON PICKER",
  "ROUND MODULE COTTON HARVESTER",
  "MODULE EXPRESS COTTON PICKER",
  "COTTON EXPRESS STRIPPER",
  "SELF-PROPELLED COTTON HARVESTER",

  /* -------------------- */
  /* COTTON ROW UNIT DNA */
  /* -------------------- */

  "2 ROW COTTON HARVESTER",
  "4 ROW COTTON HARVESTER",
  "5 ROW COTTON HARVESTER",
  "6 ROW COTTON HARVESTER",
  "8 ROW COTTON HARVESTER",
  "30 INCH COTTON ROWS",
  "36 INCH COTTON ROWS",
  "38 INCH COTTON ROWS",
  "40 INCH COTTON ROWS",
  "NARROW ROW COTTON HARVESTER",
  "WIDE ROW COTTON HARVESTER",
  "PRO-16 PICKING UNITS",
  "HIGH CAPACITY PICKING UNITS",
  "COTTON STRIPPER ROW UNITS",
  "BUR EXTRACTOR",
  "FIELD CLEANER",
  "PLANT LIFTERS",
  "ROW GUIDANCE COTTON",
  "SPINDLE PICKER UNITS",
  "BRUSH STRIPPER UNITS",
  "BRUSH AUGER",
  "DOFFER SYSTEM",
  "MOISTENER SYSTEM",
  "GREEN BOLL SEPARATOR",

  /* -------------------- */
  /* COTTON MODULE DNA */
  /* -------------------- */

  "ROUND MODULE BUILDER",
  "ONBOARD MODULE BUILDER",
  "MODULE CHAMBER",
  "MODULE WRAP SYSTEM",
  "MODULE HANDLER",
  "MODULE EJECTOR",
  "BASKET DUMP SYSTEM",
  "HIGH DUMP BASKET",
  "COTTON PACKER",
  "COTTON COMPACTOR",
  "TARPING SYSTEM",
  "WRAP ROLL SYSTEM",

  /* -------------------- */
  /* GRAIN HANDLING DNA */
  /* -------------------- */

  "GRAIN TANK",
  "HIGH CAPACITY GRAIN TANK",
  "FOLDING GRAIN TANK EXTENSIONS",
  "POWER FOLD GRAIN TANK",
  "MANUAL GRAIN TANK EXTENSIONS",
  "BUBBLE-UP AUGER",
  "CLEAN GRAIN AUGER",
  "UNLOADING AUGER",
  "HIGH RATE UNLOAD AUGER",
  "FOLDING UNLOAD AUGER",
  "EXTENDED UNLOAD AUGER",
  "PIVOTING UNLOAD AUGER",
  "POWERCAST UNLOAD SPOUT",
  "ADJUSTABLE UNLOAD SPOUT",
  "GRAIN SAMPLE DOOR",
  "GRAIN MOISTURE SENSOR",
  "YIELD SENSOR",
  "MASS FLOW SENSOR",

  /* -------------------- */
  /* RESIDUE MANAGEMENT DNA */
  /* -------------------- */

  "STRAW CHOPPER",
  "FINE CUT CHOPPER",
  "PREMIUM CHOPPER",
  "INTEGRATED CHOPPER",
  "CHOPPER KNIVES",
  "STATIONARY KNIVES",
  "CHOPPER SPEED CHANGE",
  "STRAW SPREADER",
  "CHAFF SPREADER",
  "DUAL DISC SPREADER",
  "POWER SPREADER",
  "HYDRAULIC SPREADER",
  "RESIDUE SPREADER",
  "CHOPPER DEFLECTOR",
  "WINDROW DOOR",
  "CHOP / DROP SELECTOR",
  "CHOPPER WINDROW MODE",
  "ADVANCED POWERCAST TAILBOARD",
  "TAILBOARD SPREADER",
  "CHOPPER HOOD",

  /* -------------------- */
  /* DRIVE / TRANSMISSION DNA */
  /* -------------------- */

  "HYDROSTATIC DRIVE",
  "HYDROSTATIC TRANSMISSION",
  "MECHANICAL TRANSMISSION",
  "POWERSHIFT TRANSMISSION",
  "PRODRIVE TRANSMISSION",
  "VARIABLE SPEED DRIVE",
  "BELT DRIVE",
  "PTO DRIVE",
  "4WD COMBINE",
  "2WD COMBINE",
  "REAR WHEEL ASSIST",
  "MECHANICAL REAR WHEEL DRIVE",
  "HYDRAULIC REAR WHEEL DRIVE",
  "DIFFERENTIAL LOCK",
  "FINAL DRIVES",
  "PLANETARY FINAL DRIVES",
  "HEAVY DUTY FINAL DRIVES",

  /* -------------------- */
  /* TRACK / TIRE DNA */
  /* -------------------- */

  "TERRA TRAC",
  "SMARTTRAX",
  "CAMSO TRACKS",
  "FACTORY TRACKS",
  "AFTERMARKET TRACKS",
  "HALF TRACKS",
  "RUBBER TRACKS",
  "NARROW TRACKS",
  "WIDE TRACKS",
  "30 INCH TRACKS",
  "36 INCH TRACKS",
  "40 INCH TRACKS",
  "DUAL FRONT TIRES",
  "SINGLE FRONT TIRES",
  "FLOATATION TIRES",
  "RICE TIRES",
  "R1 TIRES",
  "R2 TIRES",
  "VF TIRES",
  "IF TIRES",
  "DUAL REAR TIRES",
  "POWER REAR AXLE",
  "STEERABLE REAR AXLE",

  /* -------------------- */
  /* GUIDANCE / AUTOMATION DNA */
  /* -------------------- */

  "AUTOSTEER READY",
  "INTEGRATED AUTOSTEER",
  "GPS GUIDANCE",
  "RTK GUIDANCE",
  "ROW SENSE",
  "AUTO TRAC",
  "AUTOPILOT",
  "PILOT SYSTEM",
  "YIELD MAPPING",
  "MOISTURE MAPPING",
  "HARVEST MONITOR",
  "MACHINE SYNC",
  "HEADER HEIGHT AUTOMATION",
  "AUTO HEADER HEIGHT",
  "AUTO CONTOUR",
  "LATERAL TILT AUTOMATION",
  "AUTO CROP SETTINGS",
  "AUTOMATIC COMBINE ADJUSTMENT",
  "CEMOS AUTOMATIC",
  "HARVESTSMART",
  "CRUISE PILOT",
  "AUTO SLOPE",
  "AUTO FILL",
  "TRUCK FILL AUTOMATION",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-EMISSIONS",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4 FINAL",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF",

  /* -------------------- */
  /* SPECIALTY HARVESTER DNA */
  /* -------------------- */

  "PULL TYPE CORN PICKER",
  "MOUNTED CORN PICKER",
  "EAR CORN PICKER",
  "CORN SHELLER",
  "SHELLING BED",
  "SNAPPING ROLLS",
  "HUSKING BED",
  "PEANUT COMBINE",
  "POTATO HARVESTER",
  "BEET HARVESTER",
  "VEGETABLE HARVESTER",
  "SEED CORN HARVESTER",
  "VINE CROP HARVESTER",
  "OXBO CORN HEAD",
  "OXBO SEED CORN HARVESTER",
  "OXBO VEGETABLE HARVESTER"
];

export default agricultureHarvesterDnaKeywords;
