const articulatedTruckDnaKeywords = [
  /* -------------------- */
  /* CHASSIS / FRAME DNA */
  /* -------------------- */

  "ARTICULATED CHASSIS",
  "RIGID FRAME",
  "CENTER ARTICULATED FRAME",
  "BOX SECTION FRAME",
  "HEAVY DUTY FRAME",
  "HIGH STRENGTH FRAME",
  "LOW PROFILE FRAME",
  "LOW CENTER OF GRAVITY",
  "DOUBLE FRAME",
  "REINFORCED FRAME",
  "MINING FRAME",
  "UNDERGROUND FRAME",
  "SUPPORT CHASSIS",
  "WATER TRUCK CHASSIS",
  "LUBE TRUCK CHASSIS",
  "SERVICE TRUCK CHASSIS",
  "HOOKLIFT CHASSIS",
  "ROLL OFF CHASSIS",
  "TRUCK CHASSIS",
  "TRACTOR CHASSIS",
  "LONG WHEELBASE",
  "SHORT WHEELBASE",
  "NARROW CHASSIS",
  "WIDE CHASSIS",

  /* -------------------- */
  /* ARTICULATION DNA */
  /* -------------------- */

  "ARTICULATION JOINT",
  "CENTER ARTICULATION",
  "OSCILLATING HITCH",
  "OSCILLATING ARTICULATION",
  "ARTICULATION LOCK",
  "HYDRAULIC ARTICULATION",
  "ARTICULATION CYLINDERS",
  "FRAME OSCILLATION",
  "CENTER HINGE",
  "TURNING RING",
  "STEERING HINGE",
  "ARTICULATED STEERING",
  "REAR FRAME OSCILLATION",

  /* -------------------- */
  /* SUSPENSION DNA */
  /* -------------------- */

  "BOGIE SUSPENSION",
  "RUBBER SUSPENSION",
  "RUBBER BOGIE SUSPENSION",
  "HYDRAULIC SUSPENSION",
  "HYDROPNEUMATIC SUSPENSION",
  "FULL SUSPENSION",
  "FRONT SUSPENSION",
  "REAR SUSPENSION",
  "TRAILING ARM SUSPENSION",
  "A FRAME SUSPENSION",
  "WALKING BEAM SUSPENSION",
  "SOLID AXLE SUSPENSION",
  "OSCILLATING AXLE",
  "LOAD EQUALIZING SUSPENSION",
  "SELF LEVELING SUSPENSION",
  "INDEPENDENT FRONT SUSPENSION",
  "LEAF SPRING SUSPENSION",
  "AIR SUSPENSION",

  /* -------------------- */
  /* DRIVE SYSTEM DNA */
  /* -------------------- */

  "6X6",
  "6X4",
  "4X4",
  "ALL WHEEL DRIVE",
  "TANDEM DRIVE",
  "TRIPLE AXLE DRIVE",
  "FRONT AXLE DRIVE",
  "REAR AXLE DRIVE",
  "MECHANICAL DRIVE",
  "ELECTRIC DRIVE",
  "AC DRIVE",
  "DC DRIVE",
  "HYDROSTATIC DRIVE",
  "DIRECT DRIVE",
  "PLANETARY FINAL DRIVES",
  "INBOARD PLANETARY DRIVES",
  "OUTBOARD PLANETARY DRIVES",
  "FINAL DRIVES",
  "WHEEL MOTOR DRIVE",
  "TRACTION DRIVE",

  /* -------------------- */
  /* DIFFERENTIAL / TRACTION DNA */
  /* -------------------- */

  "DIFF LOCK",
  "DIFFERENTIAL LOCK",
  "CROSS AXLE LOCK",
  "INTER AXLE LOCK",
  "LIMITED SLIP DIFFERENTIAL",
  "TRACTION CONTROL",
  "AUTOMATIC TRACTION CONTROL",
  "SPIN CONTROL",
  "NO SPIN DIFFERENTIAL",
  "LOCKING DIFFERENTIAL",
  "AUTOMATIC DIFFERENTIAL LOCK",
  "WHEEL SLIP CONTROL",
  "TORQUE PROPORTIONING",
  "AXLE DIFFERENTIAL",
  "CENTER DIFFERENTIAL",

  /* -------------------- */
  /* TRANSMISSION DNA */
  /* -------------------- */

  "AUTOMATIC TRANSMISSION",
  "POWERSHIFT TRANSMISSION",
  "ELECTRONIC POWERSHIFT",
  "PLANETARY POWERSHIFT",
  "AUTOSHIFT TRANSMISSION",
  "FULL POWERSHIFT",
  "TORQUE CONVERTER TRANSMISSION",
  "LOCKUP TORQUE CONVERTER",
  "DIRECT DRIVE TRANSMISSION",
  "ELECTRIC DRIVE TRANSMISSION",
  "AC ELECTRIC DRIVE",
  "RETARDER TRANSMISSION",
  "TRANSMISSION RETARDER",
  "COUNTERSHAFT TRANSMISSION",
  "HYDROMECHANICAL TRANSMISSION",
  "MULTI SPEED TRANSMISSION",
  "FORWARD REVERSE SHUTTLE",

  /* -------------------- */
  /* BODY SYSTEM DNA */
  /* -------------------- */

  "STANDARD BODY",
  "ROCK BODY",
  "HEAPED BODY",
  "LIGHT MATERIAL BODY",
  "COAL BODY",
  "SIDE DUMP BODY",
  "EJECTOR BODY",
  "FLAT FLOOR BODY",
  "DOUBLE V BODY",
  "V BODY",
  "SEMI V BODY",
  "QUARRY BODY",
  "ABRASION RESISTANT BODY",
  "LINED BODY",
  "RUBBER LINED BODY",
  "HARDOX BODY",
  "HIGH VOLUME BODY",
  "LOW PROFILE BODY",
  "HIGH LIFT BODY",
  "UNDERGROUND BODY",
  "WATER TANK",
  "FUEL TANK BODY",
  "LUBE BODY",
  "SERVICE BODY",
  "HOOKLIFT BODY",
  "ROLL OFF BODY",
  "CONTAINER BODY",
  "AGGREGATE BODY",
  "MINE SPEC BODY",
  "BODY LINERS",
  "BODY HEATERS",
  "BODY WEAR PLATES",
  "BODY CANOPY",
  "BODY EXTENSIONS",

  /* -------------------- */
  /* DUMP / EJECTOR DNA */
  /* -------------------- */

  "REAR DUMP",
  "SIDE DUMP",
  "BOTTOM DUMP",
  "EJECTOR",
  "HYDRAULIC EJECTOR",
  "CHAIN EJECTOR",
  "PUSH PLATE EJECTOR",
  "DUMP CYLINDERS",
  "DUAL STAGE HOIST CYLINDERS",
  "SINGLE STAGE HOIST",
  "TELESCOPIC HOIST CYLINDER",
  "UNDERBODY HOIST",
  "BODY HOIST",
  "HYDRAULIC HOIST",
  "BODY PROP",
  "BODY RETENTION SYSTEM",
  "BODY SAFETY LOCK",
  "BODY POSITION SENSOR",

  /* -------------------- */
  /* TAILGATE DNA */
  /* -------------------- */

  "TAILGATE",
  "HIGH LIFT TAILGATE",
  "HYDRAULIC TAILGATE",
  "CHAIN TAILGATE",
  "SEALING TAILGATE",
  "AUTO TAILGATE",
  "SIDE SWING TAILGATE",
  "TOP HINGED TAILGATE",
  "BOTTOM HINGED TAILGATE",
  "TAILGATE CYLINDERS",
  "TAILGATE LOCKS",
  "TAILGATE RETENTION",
  "NO TAILGATE",

  /* -------------------- */
  /* HYDRAULIC SYSTEM DNA */
  /* -------------------- */

  "LOAD SENSING HYDRAULICS",
  "PRESSURE COMPENSATED HYDRAULICS",
  "CLOSED CENTER HYDRAULICS",
  "OPEN CENTER HYDRAULICS",
  "ELECTROHYDRAULIC CONTROLS",
  "HOIST HYDRAULICS",
  "BODY HYDRAULICS",
  "EJECTOR HYDRAULICS",
  "TAILGATE HYDRAULICS",
  "STEERING HYDRAULICS",
  "BRAKE COOLING HYDRAULICS",
  "HYDRAULIC RETARDER",
  "AUXILIARY HYDRAULICS",
  "WET KIT",
  "HIGH FLOW HYDRAULICS",
  "SERVICE HYDRAULICS",
  "HYDRAULIC COOLER",
  "HYDRAULIC FILTER SYSTEM",

  /* -------------------- */
  /* RETARDER / BRAKING DNA */
  /* -------------------- */

  "RETARDER",
  "ENGINE BRAKE",
  "EXHAUST BRAKE",
  "TRANSMISSION RETARDER",
  "HYDRAULIC RETARDER",
  "ELECTRIC RETARDER",
  "DYNAMIC RETARDER",
  "OIL COOLED BRAKES",
  "WET DISC BRAKES",
  "DRY DISC BRAKES",
  "MULTI DISC BRAKES",
  "PARK BRAKE",
  "SERVICE BRAKES",
  "SECONDARY BRAKES",
  "AUTO RETARDER",
  "DESCENT CONTROL",
  "DOWNHILL SPEED CONTROL",
  "BRAKE COOLING SYSTEM",
  "BRAKE ACCUMULATORS",

  /* -------------------- */
  /* TIRE SYSTEM DNA */
  /* -------------------- */

  "RADIAL TIRES",
  "BIAS TIRES",
  "ROCK TIRES",
  "EARTHMOVER TIRES",
  "FLOATATION TIRES",
  "LOW GROUND PRESSURE TIRES",
  "WIDE BASE TIRES",
  "DUAL REAR TIRES",
  "SINGLE REAR TIRES",
  "LGP TIRES",
  "TRACTION TIRES",
  "MINE SPEC TIRES",
  "CUT RESISTANT TIRES",
  "HEAT RESISTANT TIRES",
  "ALL TERRAIN TIRES",
  "TIRE CHAINS",
  "CENTRAL TIRE INFLATION",
  "AUTOMATIC TIRE INFLATION",

  /* -------------------- */
  /* CAB / OPERATOR DNA */
  /* -------------------- */

  "CAB",
  "ROPS CAB",
  "FOPS CAB",
  "C/H/A",
  "ENCLOSED CAB",
  "PRESSURIZED CAB",
  "AIR CONDITIONED CAB",
  "HEATED CAB",
  "SUSPENSION SEAT",
  "AIR RIDE SEAT",
  "DELUXE CAB",
  "LOW PROFILE CAB",
  "DUAL OPERATOR CONTROLS",
  "JOYSTICK STEERING",
  "STEERING WHEEL CONTROLS",
  "MULTIFUNCTION DISPLAY",
  "OPERATOR PRESENCE SYSTEM",
  "CAB ISOLATION MOUNTS",
  "TINTED GLASS",
  "SUN VISOR",

  /* -------------------- */
  /* AUTOMATION / PAYLOAD DNA */
  /* -------------------- */

  "PAYLOAD SYSTEM",
  "ONBOARD WEIGH SYSTEM",
  "PAYLOAD MONITOR",
  "LOAD SCALE",
  "PRODUCTION MONITORING",
  "HAUL CYCLE MONITORING",
  "AUTOMATIC TRACTION CONTROL",
  "AUTOMATIC DIFFERENTIAL LOCK",
  "DESCENT CONTROL",
  "HILL HOLD",
  "AUTOMATIC RETARDER CONTROL",
  "AUTONOMOUS READY",
  "AUTONOMOUS HAUL READY",
  "COMMAND FOR HAULING",
  "TELEMATICS",
  "PRODUCT LINK",
  "VHMS",
  "CARETRACK",
  "KOMTRAX",
  "JD LINK",
  "ACTIVECARE",
  "REMOTE DIAGNOSTICS",
  "GPS MONITORING",
  "360 CAMERA",
  "REAR CAMERA",
  "SURROUND CAMERA SYSTEM",

  /* -------------------- */
  /* SAFETY SYSTEM DNA */
  /* -------------------- */

  "FIRE SUPPRESSION",
  "AUTO LUBE",
  "CENTRALIZED GREASING",
  "EMERGENCY STEERING",
  "EMERGENCY SHUTDOWN",
  "GROUND LEVEL SHUTDOWN",
  "BRAKE TEST SYSTEM",
  "BACKUP ALARM",
  "PROXIMITY DETECTION",
  "COLLISION AVOIDANCE",
  "ROLL STABILITY CONTROL",
  "SEAT BELT MONITOR",
  "HANDRAILS",
  "ACCESS STAIRS",
  "ESCAPE LADDER",
  "WHEEL CHOCKS",
  "LOCKOUT TAGOUT",
  "SERVICE LOCKS",
  "BODY SAFETY PROP",
  "LED LIGHTS",
  "WORK LIGHT PACKAGE",
  "BEACON LIGHTS",

  /* -------------------- */
  /* WATER / LUBE / SUPPORT DNA */
  /* -------------------- */

  "WATER TRUCK",
  "WATER TANK",
  "SPRAY BAR",
  "WATER CANNON",
  "DUST SUPPRESSION SYSTEM",
  "LUBE TRUCK",
  "FUEL AND LUBE TRUCK",
  "SERVICE TRUCK",
  "SERVICE MODULE",
  "FUEL TANK MODULE",
  "GREASE SYSTEM",
  "OIL DISPENSING SYSTEM",
  "HOSE REELS",
  "COMPRESSOR PACKAGE",
  "GENERATOR PACKAGE",
  "HOOKLIFT",
  "ROLL OFF SYSTEM",
  "SERVICE CRANE",
  "WORK PLATFORM",
  "WELDER PACKAGE",
  "JUMP START SYSTEM",

  /* -------------------- */
  /* UNDERGROUND / MINING DNA */
  /* -------------------- */

  "UNDERGROUND TRUCK",
  "LOW PROFILE UNDERGROUND",
  "UNDERGROUND DUMP BODY",
  "UNDERGROUND CAB",
  "MINE SPEC PACKAGE",
  "AC ELECTRIC DRIVE",
  "DC ELECTRIC DRIVE",
  "TROLLEY ASSIST",
  "TROLLEY READY",
  "HIGH ALTITUDE PACKAGE",
  "EXTREME DUTY PACKAGE",
  "XLP BODY",
  "CMD PACKAGE",

  /* -------------------- */
  /* LIGHTING / ELECTRICAL DNA */
  /* -------------------- */

  "LED LIGHTS",
  "HALOGEN LIGHTS",
  "HID LIGHTS",
  "WORK LIGHT PACKAGE",
  "BEACON",
  "STROBE LIGHTS",
  "BATTERY DISCONNECT",
  "MASTER DISCONNECT",
  "HIGH OUTPUT ALTERNATOR",
  "JUMP START RECEPTACLE",
  "COLD WEATHER PACKAGE",
  "ARCTIC PACKAGE",
  "BLOCK HEATER",
  "ETHER START",
  "AUTO IDLE SHUTDOWN",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4 FINAL",
  "T4F",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF",
  "PRE-DEF",
  "DEF DELETE"
];

export default articulatedTruckDnaKeywords;
