const loaderBackhoeDnaKeywords = [
  /* -------------------- */
  /* CHASSIS / FRAME DNA */
  /* -------------------- */

  "STANDARD CHASSIS",
  "CENTER MOUNT",
  "SIDE SHIFT",
  "CENTER PIVOT FRAME",
  "HEAVY DUTY FRAME",
  "TOOL CARRIER",
  "INTEGRATED TOOL CARRIER",
  "IT",
  "LOW PROFILE CHASSIS",
  "COMPACT CHASSIS",
  "WHEELBASE FRAME",
  "BOX SECTION FRAME",
  "ONE PIECE FRAME",
  "ARTICULATED FRAME",
  "UTILITY FRAME",
  "INDUSTRIAL FRAME",
  "REINFORCED FRAME",
  "OFFSET BOOM FRAME",

  /* -------------------- */
  /* LOADER SYSTEM DNA */
  /* -------------------- */

  "LOADER ARMS",
  "PARALLEL LIFT LOADER",
  "SELF LEVELING",
  "MECHANICAL SELF LEVELING",
  "HYDRAULIC SELF LEVELING",
  "LOADER LINKAGE",
  "Z BAR LINKAGE",
  "TOOL CARRIER LOADER",
  "IT LOADER",
  "LOADER QUICK ATTACH",
  "HYDRAULIC QUICK ATTACH",
  "MANUAL QUICK ATTACH",
  "LOADER RIDE CONTROL",
  "LOADER FLOAT",
  "LOADER RETURN TO DIG",
  "LOADER POSITION CONTROL",
  "LOADER LIFT CYLINDERS",
  "LOADER TILT CYLINDERS",
  "LOADER AUXILIARY HYDRAULICS",
  "HIGH LIFT LOADER",
  "UTILITY LOADER",
  "MATERIAL HANDLING LOADER",

  /* -------------------- */
  /* BUCKET DNA */
  /* -------------------- */

  "GENERAL PURPOSE BUCKET",
  "MULTI PURPOSE BUCKET",
  "4 IN 1 BUCKET",
  "6 IN 1 BUCKET",
  "LOADER BUCKET",
  "DITCHING BUCKET",
  "GRADING BUCKET",
  "TILT BUCKET",
  "SKELETON BUCKET",
  "ROCK BUCKET",
  "LIGHT MATERIAL BUCKET",
  "HIGH CAPACITY BUCKET",
  "LOW PROFILE BUCKET",
  "SMOOTH EDGE BUCKET",
  "TOOTH BUCKET",
  "BOLT ON EDGE",
  "REVERSIBLE CUTTING EDGE",
  "BUCKET LEVEL INDICATOR",
  "SIDE DUMP BUCKET",
  "CLAM BUCKET",

  /* -------------------- */
  /* BACKHOE BOOM DNA */
  /* -------------------- */

  "BACKHOE BOOM",
  "CENTER MOUNT BACKHOE",
  "SIDE SHIFT BACKHOE",
  "OFFSET BACKHOE",
  "CURVED BOOM",
  "STRAIGHT BOOM",
  "EXCAVATOR STYLE BOOM",
  "BOX SECTION BOOM",
  "HEAVY DUTY BOOM",
  "LONG REACH BACKHOE",
  "POWERLIFT BACKHOE",
  "BACKHOE SWING CYLINDERS",
  "BACKHOE STABILIZER FRAME",
  "BOOM LOCK",
  "BACKHOE LIFT CYLINDERS",
  "BACKHOE DIPPER",
  "DIPPER STICK",
  "LONG DIPPER",
  "SHORT DIPPER",

  /* -------------------- */
  /* EXTENDAHOE DNA */
  /* -------------------- */

  "EXTENDAHOE",
  "TELESCOPIC DIPPER",
  "SLIDING EXTENDAHOE",
  "HYDRAULIC EXTENDAHOE",
  "MECHANICAL EXTENDAHOE",
  "INNER EXTENDABLE DIPPER",
  "OUTER EXTENDABLE DIPPER",
  "EXTENDAHOE WEAR PADS",
  "EXTENDAHOE LOCK",
  "EXTENDABLE STICK",
  "LONG STICK",
  "NO EXTENDAHOE",

  /* -------------------- */
  /* SIDE SHIFT / CENTER MOUNT DNA */
  /* -------------------- */

  "HYDRAULIC SIDE SHIFT",
  "MANUAL SIDE SHIFT",
  "CENTER SWING",
  "SIDE SHIFT CARRIAGE",
  "SIDE SHIFT FRAME",
  "SIDE SHIFT LOCK",
  "CENTER PIVOT BACKHOE",
  "OFFSET SWING",

  /* -------------------- */
  /* STABILIZER DNA */
  /* -------------------- */

  "STABILIZERS",
  "BOX BLADE STABILIZERS",
  "PADFOOT STABILIZERS",
  "STREET PADS",
  "RUBBER PADS",
  "STABILIZER PADS",
  "SWING DOWN STABILIZERS",
  "VERTICAL STABILIZERS",
  "HYDRAULIC STABILIZERS",
  "EXTENDABLE STABILIZERS",
  "STABILIZER LOCKS",
  "STABILIZER GUARDS",
  "REAR STABILIZER FRAME",

  /* -------------------- */
  /* HYDRAULIC SYSTEM DNA */
  /* -------------------- */

  "OPEN CENTER HYDRAULICS",
  "CLOSED CENTER HYDRAULICS",
  "LOAD SENSING HYDRAULICS",
  "PRESSURE COMPENSATED HYDRAULICS",
  "HIGH FLOW",
  "HIGH FLOW HYDRAULICS",
  "AUX HYDRAULICS",
  "SECONDARY AUX HYDRAULICS",
  "THIRD FUNCTION HYDRAULICS",
  "FOURTH FUNCTION HYDRAULICS",
  "ELECTROHYDRAULIC CONTROLS",
  "PILOT HYDRAULICS",
  "HYDRAULIC COOLER",
  "POWER BEYOND",
  "AUXILIARY VALVE",
  "HAMMER CIRCUIT",
  "BIDIRECTIONAL FLOW",
  "ONE WAY FLOW",
  "VARIABLE FLOW HYDRAULICS",
  "FLOW CONTROL",
  "HYDRAULIC QUICK COUPLERS",

  /* -------------------- */
  /* ATTACHMENT READY DNA */
  /* -------------------- */

  "HAMMER READY",
  "BREAKER READY",
  "AUGER READY",
  "TRENCHER READY",
  "GRAPPLE READY",
  "PLATE COMPACTOR READY",
  "MULCHER READY",
  "BROOM READY",
  "SNOWPLOW READY",
  "PALLET FORK READY",
  "FORK FRAME READY",
  "TILTROTATOR READY",
  "ATTACHMENT READY",
  "HIGH FLOW ATTACHMENT READY",

  /* -------------------- */
  /* COUPLER DNA */
  /* -------------------- */

  "QUICK COUPLER",
  "HYDRAULIC COUPLER",
  "MANUAL COUPLER",
  "PIN GRABBER COUPLER",
  "WEDGE COUPLER",
  "BACKHOE COUPLER",
  "LOADER COUPLER",
  "IT COUPLER",
  "SKID STEER COUPLER",
  "UNIVERSAL QUICK ATTACH",
  "COUPLER LOCK",
  "COUPLER SAFETY SYSTEM",

  /* -------------------- */
  /* THUMB DNA */
  /* -------------------- */

  "HYDRAULIC THUMB",
  "MANUAL THUMB",
  "MECHANICAL THUMB",
  "PROGRESSIVE LINK THUMB",
  "WELD ON THUMB",
  "PIN ON THUMB",
  "BACKHOE THUMB",
  "NO THUMB",

  /* -------------------- */
  /* TRANSMISSION DNA */
  /* -------------------- */

  "POWERSHIFT",
  "AUTOSHIFT",
  "FULL POWERSHIFT",
  "PARTIAL POWERSHIFT",
  "POWER SHUTTLE",
  "POWER REVERSER",
  "SYNCHRO SHUTTLE",
  "HYDROSTATIC",
  "LOCKUP TORQUE CONVERTER",
  "TORQUE CONVERTER TRANSMISSION",
  "DIRECT DRIVE TRANSMISSION",
  "CREEPER GEAR",
  "AUTO SHIFT",
  "FORWARD REVERSE SHUTTLE",
  "ELECTRONIC TRANSMISSION",
  "TRANSMISSION DISCONNECT",
  "INCHING PEDAL",

  /* -------------------- */
  /* DRIVE SYSTEM DNA */
  /* -------------------- */

  "2WD",
  "4X4",
  "MFWD",
  "ALL WHEEL DRIVE",
  "4 WHEEL DRIVE",
  "4 WHEEL STEER",
  "CRAB STEER",
  "FRONT WHEEL DRIVE",
  "REAR WHEEL DRIVE",
  "LIMITED SLIP DIFFERENTIAL",
  "DIFFERENTIAL LOCK",
  "PLANETARY AXLES",
  "HEAVY DUTY AXLES",
  "OUTBOARD PLANETARIES",
  "INBOARD PLANETARIES",

  /* -------------------- */
  /* STEERING DNA */
  /* -------------------- */

  "2 WHEEL STEER",
  "FRONT WHEEL STEER",
  "HYDRAULIC STEERING",
  "PILOT STEERING",
  "ARTICULATED STEERING",
  "STEERING MODES",
  "ROAD MODE STEERING",
  "COORDINATED STEERING",

  /* -------------------- */
  /* RIDE CONTROL DNA */
  /* -------------------- */

  "RIDE CONTROL",
  "BOOM SUSPENSION",
  "ACCUMULATOR RIDE CONTROL",
  "AUTOMATIC RIDE CONTROL",
  "MANUAL RIDE CONTROL",
  "RIDE CONTROL LOCKOUT",

  /* -------------------- */
  /* CONTROL SYSTEM DNA */
  /* -------------------- */

  "PILOT CONTROLS",
  "JOYSTICK CONTROLS",
  "MECHANICAL CONTROLS",
  "ISO CONTROLS",
  "SAE CONTROLS",
  "PATTERN CHANGER",
  "CONTROL PATTERN SELECTOR",
  "SINGLE LEVER CONTROLS",
  "DUAL LEVER CONTROLS",
  "FINGERTIP CONTROLS",
  "LOAD SENSING CONTROLS",
  "STABILIZER CONTROLS",
  "BACKHOE CONTROL PODS",

  /* -------------------- */
  /* AUTOMATION / GRADE DNA */
  /* -------------------- */

  "LASER READY",
  "GPS READY",
  "2D GRADE CONTROL",
  "3D GRADE CONTROL",
  "MACHINE CONTROL READY",
  "GRADE CONTROL READY",
  "AUTO LEVEL",
  "AUTO RETURN TO DIG",
  "AUTO STABILIZER",
  "PAYLOAD SYSTEM",
  "ONBOARD WEIGH SYSTEM",
  "TELEMATICS",
  "PRODUCT LINK",
  "JD LINK",
  "CASE SITEWATCH",
  "CARETRACK",
  "KOMTRAX",
  "REMOTE DIAGNOSTICS",
  "REAR CAMERA",
  "360 CAMERA",

  /* -------------------- */
  /* CAB / OPERATOR DNA */
  /* -------------------- */

  "C/H/A",
  "CAB",
  "ROPS CAB",
  "FOPS CAB",
  "OPEN STATION",
  "ENCLOSED CAB",
  "AIR CONDITIONED CAB",
  "HEATED CAB",
  "DELUXE CAB",
  "LOW PROFILE CAB",
  "AIR RIDE SEAT",
  "SUSPENSION SEAT",
  "SWIVEL SEAT",
  "ROTATING SEAT",
  "RIDE SEAT",
  "AM/FM RADIO",
  "BLUETOOTH RADIO",
  "TOUCHSCREEN DISPLAY",
  "MULTIFUNCTION DISPLAY",
  "LED LIGHTS",
  "HALOGEN LIGHTS",
  "WORK LIGHT PACKAGE",
  "BEACON",
  "SUNSHADE",

  /* -------------------- */
  /* TIRE / AXLE DNA */
  /* -------------------- */

  "INDUSTRIAL TIRES",
  "R4 TIRES",
  "R1 TIRES",
  "RADIAL TIRES",
  "BIAS TIRES",
  "FOAM FILLED TIRES",
  "NON MARKING TIRES",
  "OSCILLATING FRONT AXLE",
  "FRONT AXLE SUSPENSION",
  "REAR AXLE LOCK",
  "TIRE CHAINS",

  /* -------------------- */
  /* GUARDING DNA */
  /* -------------------- */

  "BOOM GUARDS",
  "CYLINDER GUARDS",
  "LIGHT GUARDS",
  "GRILLE GUARD",
  "BELLY PAN",
  "TRANSMISSION GUARDS",
  "HYDRAULIC LINE GUARDS",
  "ROD GUARDS",
  "FENDER PACKAGE",

  /* -------------------- */
  /* ENGINE / POWERTRAIN DNA */
  /* -------------------- */

  "TURBOCHARGED",
  "INTERCOOLED",
  "COMMON RAIL",
  "MECHANICAL INJECTION",
  "HIGH IDLE SYSTEM",
  "AUTO IDLE",
  "ENGINE SHUTDOWN TIMER",
  "BLOCK HEATER",
  "COLD WEATHER PACKAGE",
  "REVERSING FAN",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-DEF",
  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4",
  "TIER 4 FINAL",
  "T4F",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF",
  "DEF DELETE"
];

export default loaderBackhoeDnaKeywords;
