// /lib/compactionRollersTaxonomy.js

const compactionRollersTaxonomy = [
  //
  //CATERPILLAR
  //

{ make: "CATERPILLAR", model: "815" },
{ make: "CATERPILLAR", model: "815A" },
{ make: "CATERPILLAR", model: "815B" },
{ make: "CATERPILLAR", model: "815C" },
{ make: "CATERPILLAR", model: "815F" },
{ make: "CATERPILLAR", model: "815F2" },
{ make: "CATERPILLAR", model: "815K" },
{ make: "CATERPILLAR", model: "816" },
{ make: "CATERPILLAR", model: "816B" },
{ make: "CATERPILLAR", model: "816C" },
{ make: "CATERPILLAR", model: "816F" },
{ make: "CATERPILLAR", model: "816F2" },
{ make: "CATERPILLAR", model: "816K" },
{ make: "CATERPILLAR", model: "825" },
{ make: "CATERPILLAR", model: "825B" },
{ make: "CATERPILLAR", model: "825C" },
{ make: "CATERPILLAR", model: "825G" },
{ make: "CATERPILLAR", model: "825G2" },
{ make: "CATERPILLAR", model: "825H" },
{ make: "CATERPILLAR", model: "825K" },
{ make: "CATERPILLAR", model: "826" },
{ make: "CATERPILLAR", model: "826C" },
{ make: "CATERPILLAR", model: "826G" },
{ make: "CATERPILLAR", model: "826G2" },
{ make: "CATERPILLAR", model: "826H" },
{ make: "CATERPILLAR", model: "826K" },
{ make: "CATERPILLAR", model: "836" },
{ make: "CATERPILLAR", model: "836C" },
{ make: "CATERPILLAR", model: "836G" },
{ make: "CATERPILLAR", model: "836H" },
{ make: "CATERPILLAR", model: "836K" },
{ make: "CATERPILLAR", model: "CB1.7" },
{ make: "CATERPILLAR", model: "CB1.8" },
{ make: "CATERPILLAR", model: "CB2.5" },
{ make: "CATERPILLAR", model: "CB2.7" },
{ make: "CATERPILLAR", model: "CB4.0" },
{ make: "CATERPILLAR", model: "CB4.4" },
{ make: "CATERPILLAR", model: "CB7" },
{ make: "CATERPILLAR", model: "CB10" },
{ make: "CATERPILLAR", model: "CB13" },
{ make: "CATERPILLAR", model: "CB14" },
{ make: "CATERPILLAR", model: "CB14B" },
{ make: "CATERPILLAR", model: "CB15" },
{ make: "CATERPILLAR", model: "CB16" },
{ make: "CATERPILLAR", model: "CB22" },
{ make: "CATERPILLAR", model: "CB22B" },
{ make: "CATERPILLAR", model: "CB24" },
{ make: "CATERPILLAR", model: "CB24B" },
{ make: "CATERPILLAR", model: "CB24XT" },
{ make: "CATERPILLAR", model: "CB34" },
{ make: "CATERPILLAR", model: "CB34B" },
{ make: "CATERPILLAR", model: "CB34XW" },
{ make: "CATERPILLAR", model: "CB34XW" },
{ make: "CATERPILLAR", model: "CB36" },
{ make: "CATERPILLAR", model: "CB36B" },
{ make: "CATERPILLAR", model: "CB44" },
{ make: "CATERPILLAR", model: "CB44B" },
{ make: "CATERPILLAR", model: "CB54" },
{ make: "CATERPILLAR", model: "CB54B" },
{ make: "CATERPILLAR", model: "CB54XW" },
{ make: "CATERPILLAR", model: "CB64" },
{ make: "CATERPILLAR", model: "CB64B" },
{ make: "CATERPILLAR", model: "CB66B" },
{ make: "CATERPILLAR", model: "CB68B" },
{ make: "CATERPILLAR", model: "CB-114" },
{ make: "CATERPILLAR", model: "CB-214C" },
{ make: "CATERPILLAR", model: "CB-224B" },
{ make: "CATERPILLAR", model: "CB-224C" },
{ make: "CATERPILLAR", model: "CB-224E" },
{ make: "CATERPILLAR", model: "CB-225D" },
{ make: "CATERPILLAR", model: "CB-225E" },
{ make: "CATERPILLAR", model: "CB-334D" },
{ make: "CATERPILLAR", model: "CB-334E" },
{ make: "CATERPILLAR", model: "CB-335E" },
{ make: "CATERPILLAR", model: "CB-434" },
{ make: "CATERPILLAR", model: "CB-434C" },
{ make: "CATERPILLAR", model: "CB-434D" },
{ make: "CATERPILLAR", model: "CB-514" },
{ make: "CATERPILLAR", model: "CB-534" },
{ make: "CATERPILLAR", model: "CB-534C" },
{ make: "CATERPILLAR", model: "CB-534D" },
{ make: "CATERPILLAR", model: "CB-534DXW" },
{ make: "CATERPILLAR", model: "CB-544" },
{ make: "CATERPILLAR", model: "CB-564D" },
{ make: "CATERPILLAR", model: "CB-634" },
{ make: "CATERPILLAR", model: "CB-634C" },
{ make: "CATERPILLAR", model: "CB-634D" },
{ make: "CATERPILLAR", model: "CC2.7" },
{ make: "CATERPILLAR", model: "CC2.7 GC" },
{ make: "CATERPILLAR", model: "CC4.0" },
{ make: "CATERPILLAR", model: "CC24" },
{ make: "CATERPILLAR", model: "CC34" },
{ make: "CATERPILLAR", model: "CC34B" },
{ make: "CATERPILLAR", model: "CCS9" },
{ make: "CATERPILLAR", model: "CD8" },
{ make: "CATERPILLAR", model: "CD54" },
{ make: "CATERPILLAR", model: "CD54B" },
{ make: "CATERPILLAR", model: "CP5" },
{ make: "CATERPILLAR", model: "CP7" },
{ make: "CATERPILLAR", model: "CP11GC" },
{ make: "CATERPILLAR", model: "CP12GC" },
{ make: "CATERPILLAR", model: "CP13GC" },
{ make: "CATERPILLAR", model: "CP16" },
{ make: "CATERPILLAR", model: "CP34" },
{ make: "CATERPILLAR", model: "CP44" },
{ make: "CATERPILLAR", model: "CP44B" },
{ make: "CATERPILLAR", model: "CP54" },
{ make: "CATERPILLAR", model: "CP54B" },
{ make: "CATERPILLAR", model: "CP56" },
{ make: "CATERPILLAR", model: "CP56B" },
{ make: "CATERPILLAR", model: "CP64" },
{ make: "CATERPILLAR", model: "CP68B" },
{ make: "CATERPILLAR", model: "CP74" },
{ make: "CATERPILLAR", model: "CP74B" },
{ make: "CATERPILLAR", model: "CP76" },
{ make: "CATERPILLAR", model: "CP-323" },
{ make: "CATERPILLAR", model: "CP-323C" },
{ make: "CATERPILLAR", model: "CP-433B" },
{ make: "CATERPILLAR", model: "CP-433C" },
{ make: "CATERPILLAR", model: "CP-433E" },
{ make: "CATERPILLAR", model: "CP-443B" },
{ make: "CATERPILLAR", model: "CP-533E" },
{ make: "CATERPILLAR", model: "CP-563" },
{ make: "CATERPILLAR", model: "CP-563C" },
{ make: "CATERPILLAR", model: "CP-563D" },
{ make: "CATERPILLAR", model: "CP-563E" },
{ make: "CATERPILLAR", model: "CP-573E" },
{ make: "CATERPILLAR", model: "CS5" },
{ make: "CATERPILLAR", model: "CS7" },
{ make: "CATERPILLAR", model: "CS10" },
{ make: "CATERPILLAR", model: "CS10GC" },
{ make: "CATERPILLAR", model: "CS11" },
{ make: "CATERPILLAR", model: "CS11GC" },
{ make: "CATERPILLAR", model: "CS12" },
{ make: "CATERPILLAR", model: "CS12GC" },
{ make: "CATERPILLAR", model: "CS13" },
{ make: "CATERPILLAR", model: "CS13GC" },
{ make: "CATERPILLAR", model: "CS14" },
{ make: "CATERPILLAR", model: "CS16" },
{ make: "CATERPILLAR", model: "CS17" },
{ make: "CATERPILLAR", model: "CS34" },
{ make: "CATERPILLAR", model: "CS44" },
{ make: "CATERPILLAR", model: "CS44B" },
{ make: "CATERPILLAR", model: "CS54" },
{ make: "CATERPILLAR", model: "CS54B" },
{ make: "CATERPILLAR", model: "CS56" },
{ make: "CATERPILLAR", model: "CS56B" },
{ make: "CATERPILLAR", model: "CS64" },
{ make: "CATERPILLAR", model: "CS64B" },
{ make: "CATERPILLAR", model: "CS66B" },
{ make: "CATERPILLAR", model: "CS68B" },
{ make: "CATERPILLAR", model: "CS74" },
{ make: "CATERPILLAR", model: "CS74B" },
{ make: "CATERPILLAR", model: "CS76" },
{ make: "CATERPILLAR", model: "CS76 XT" },
{ make: "CATERPILLAR", model: "CS76B" },
{ make: "CATERPILLAR", model: "CS78B" },
{ make: "CATERPILLAR", model: "CS-323C" },
{ make: "CATERPILLAR", model: "CS-423E" },
{ make: "CATERPILLAR", model: "CS-433B" },
{ make: "CATERPILLAR", model: "CS-433C" },
{ make: "CATERPILLAR", model: "CS-433E" },
{ make: "CATERPILLAR", model: "CS-531C" },
{ make: "CATERPILLAR", model: "CS-533" },
{ make: "CATERPILLAR", model: "CS-533C" },
{ make: "CATERPILLAR", model: "CS-533E" },
{ make: "CATERPILLAR", model: "CS-533E XT" },
{ make: "CATERPILLAR", model: "CS-563" },
{ make: "CATERPILLAR", model: "CS-563C" },
{ make: "CATERPILLAR", model: "CS-563D" },
{ make: "CATERPILLAR", model: "CS-563DAW" },
{ make: "CATERPILLAR", model: "CS-563E" },
{ make: "CATERPILLAR", model: "CS-573E" },
{ make: "CATERPILLAR", model: "CS-583C" },
{ make: "CATERPILLAR", model: "CS-583D" },
{ make: "CATERPILLAR", model: "CS-583E" },
{ make: "CATERPILLAR", model: "CS-663E" },
{ make: "CATERPILLAR", model: "CS-683E" },
{ make: "CATERPILLAR", model: "CW14" },
{ make: "CATERPILLAR", model: "CW16" },
{ make: "CATERPILLAR", model: "CW34" },
{ make: "CATERPILLAR", model: "PF-300" },
{ make: "CATERPILLAR", model: "PS-130" },
{ make: "CATERPILLAR", model: "PS-150" },
{ make: "CATERPILLAR", model: "PS-300" },
{ make: "CATERPILLAR", model: "PS-360" },
{ make: "CATERPILLAR", model: "OTHER" },
 //
  //BOMAG
  //
{ make: "BOMAG", model: "BC473" },
{ make: "BOMAG", model: "BC571" },
{ make: "BOMAG", model: "BC572" },
{ make: "BOMAG", model: "BC601" },
{ make: "BOMAG", model: "BC671" },
{ make: "BOMAG", model: "BC672" },
{ make: "BOMAG", model: "BC772" },
{ make: "BOMAG", model: "BC972" },
{ make: "BOMAG", model: "BC1172" },
{ make: "BOMAG", model: "BMP851" },
{ make: "BOMAG", model: "BMP8500" },
{ make: "BOMAG", model: "BP10" },
{ make: "BOMAG", model: "BP12" },
{ make: "BOMAG", model: "BP15" },
{ make: "BOMAG", model: "BP20" },
{ make: "BOMAG", model: "BP25" },
{ make: "BOMAG", model: "BPH80" },
{ make: "BOMAG", model: "BPR25" },
{ make: "BOMAG", model: "BPR30" },
{ make: "BOMAG", model: "BPR35" },
{ make: "BOMAG", model: "BPR45" },
{ make: "BOMAG", model: "BPR50" },
{ make: "BOMAG", model: "BPR55" },
{ make: "BOMAG", model: "BPR60" },
{ make: "BOMAG", model: "BPR70" },
{ make: "BOMAG", model: "BPR100" },
{ make: "BOMAG", model: "BPR95" },
{ make: "BOMAG", model: "BT50" },
{ make: "BOMAG", model: "BT60" },
{ make: "BOMAG", model: "BT65" },
{ make: "BOMAG", model: "BVP10" },
{ make: "BOMAG", model: "BVP12" },
{ make: "BOMAG", model: "BVP18" },
{ make: "BOMAG", model: "BVT65" },
{ make: "BOMAG", model: "BW4" },
{ make: "BOMAG", model: "BW6" },
{ make: "BOMAG", model: "BW9" },
{ make: "BOMAG", model: "BW11" },
{ make: "BOMAG", model: "BW12" },
{ make: "BOMAG", model: "BW24" },
{ make: "BOMAG", model: "BW25" },
{ make: "BOMAG", model: "BW27" },
{ make: "BOMAG", model: "BW28" },
{ make: "BOMAG", model: "BW55" },
{ make: "BOMAG", model: "BW60" },
{ make: "BOMAG", model: "BW65" },
{ make: "BOMAG", model: "BW71" },
{ make: "BOMAG", model: "BW75" },
{ make: "BOMAG", model: "BW76" },
{ make: "BOMAG", model: "BW80" },
{ make: "BOMAG", model: "BW90" },
{ make: "BOMAG", model: "BW100" },
{ make: "BOMAG", model: "BW120" },
{ make: "BOMAG", model: "BW122" },
{ make: "BOMAG", model: "BW124" },
{ make: "BOMAG", model: "BW125" },
{ make: "BOMAG", model: "BW130" },
{ make: "BOMAG", model: "BW131" },
{ make: "BOMAG", model: "BW135" },
{ make: "BOMAG", model: "BW137" },
{ make: "BOMAG", model: "BW138" },
{ make: "BOMAG", model: "BW141" },
{ make: "BOMAG", model: "BW144" },
{ make: "BOMAG", model: "BW145" },
{ make: "BOMAG", model: "BW151" },
{ make: "BOMAG", model: "BW154" },
{ make: "BOMAG", model: "BW160" },
{ make: "BOMAG", model: "BW161" },
{ make: "BOMAG", model: "BW164" },
{ make: "BOMAG", model: "BW170" },
{ make: "BOMAG", model: "BW172" },
{ make: "BOMAG", model: "BW174" },
{ make: "BOMAG", model: "BW177" },
{ make: "BOMAG", model: "BW178" },
{ make: "BOMAG", model: "BW179" },
{ make: "BOMAG", model: "BW184" },
{ make: "BOMAG", model: "BW190" },
{ make: "BOMAG", model: "BW191" },
{ make: "BOMAG", model: "BW200" },
{ make: "BOMAG", model: "BW201" },
{ make: "BOMAG", model: "BW202" },
{ make: "BOMAG", model: "BW203" },
{ make: "BOMAG", model: "BW205" },
{ make: "BOMAG", model: "BW206" },
{ make: "BOMAG", model: "BW211" },
{ make: "BOMAG", model: "BW212" },
{ make: "BOMAG", model: "BW213" },
{ make: "BOMAG", model: "BW216" },
{ make: "BOMAG", model: "BW217" },
{ make: "BOMAG", model: "BW219" },
{ make: "BOMAG", model: "BW226" },
{ make: "BOMAG", model: "BW266" },
{ make: "BOMAG", model: "BW278" },
{ make: "BOMAG", model: "BW284" },
{ make: "BOMAG", model: "BW600" },
{ make: "BOMAG", model: "BW850" },
{ make: "BOMAG", model: "BW900" },
{ make: "BOMAG", model: "K300" },
{ make: "BOMAG", model: "K351" },
{ make: "BOMAG", model: "OTHER" },
  //
  //HAMM
  //
 { make: "HAMM", model: "311" },
{ make: "HAMM", model: "320" },
{ make: "HAMM", model: "2210" },
{ make: "HAMM", model: "2310" },
{ make: "HAMM", model: "2311" },
{ make: "HAMM", model: "2320" },
{ make: "HAMM", model: "2420" },
{ make: "HAMM", model: "2422" },
{ make: "HAMM", model: "3012" },
{ make: "HAMM", model: "3205" },
{ make: "HAMM", model: "3307" },
{ make: "HAMM", model: "3410" },
{ make: "HAMM", model: "3411" },
{ make: "HAMM", model: "3412" },
{ make: "HAMM", model: "3414" },
{ make: "HAMM", model: "3518" },
{ make: "HAMM", model: "3520" },
{ make: "HAMM", model: "3625" },
{ make: "HAMM", model: "DV06" },
{ make: "HAMM", model: "DV3" },
{ make: "HAMM", model: "DV6" },
{ make: "HAMM", model: "DV8" },
{ make: "HAMM", model: "DV65" },
{ make: "HAMM", model: "DV70" },
{ make: "HAMM", model: "DV+70" },
{ make: "HAMM", model: "DV85" },
{ make: "HAMM", model: "DV90" },
{ make: "HAMM", model: "DV+90" },
{ make: "HAMM", model: "GRW5" },
{ make: "HAMM", model: "GRW10" },
{ make: "HAMM", model: "GRW15" },
{ make: "HAMM", model: "GRW18" },
{ make: "HAMM", model: "GRW180I" },
{ make: "HAMM", model: "GRW280" },
{ make: "HAMM", model: "GRW280I" },
{ make: "HAMM", model: "H5" },
{ make: "HAMM", model: "H7" },
{ make: "HAMM", model: "H10" },
{ make: "HAMM", model: "H11" },
{ make: "HAMM", model: "H12" },
{ make: "HAMM", model: "H13" },
{ make: "HAMM", model: "H14" },
{ make: "HAMM", model: "H16" },
{ make: "HAMM", model: "H18" },
{ make: "HAMM", model: "H20" },
{ make: "HAMM", model: "H25" },
{ make: "HAMM", model: "H200" },
{ make: "HAMM", model: "HC50" },
{ make: "HAMM", model: "HC70" },
{ make: "HAMM", model: "HC100" },
{ make: "HAMM", model: "HC120" },
{ make: "HAMM", model: "HC130" },
{ make: "HAMM", model: "HC160" },
{ make: "HAMM", model: "HC180" },
{ make: "HAMM", model: "HC200" },
{ make: "HAMM", model: "HD8" },
{ make: "HAMM", model: "HD9" },
{ make: "HAMM", model: "HD10" },
{ make: "HAMM", model: "HD12" },
{ make: "HAMM", model: "HD13" },
{ make: "HAMM", model: "HD14" },
{ make: "HAMM", model: "HD70" },
{ make: "HAMM", model: "HD75" },
{ make: "HAMM", model: "HD85" },
{ make: "HAMM", model: "HD90" },
{ make: "HAMM", model: "HD110" },
{ make: "HAMM", model: "HD120" },
{ make: "HAMM", model: "HD128" },
{ make: "HAMM", model: "HD130" },
{ make: "HAMM", model: "HC119" },
{ make: "HAMM", model: "HD138" },
{ make: "HAMM", model: "HD140" },
{ make: "HAMM", model: "HDO120" },
{ make: "HAMM", model: "HD+70" },
{ make: "HAMM", model: "HD+80" },
{ make: "HAMM", model: "HD+90" },
{ make: "HAMM", model: "HD+110" },
{ make: "HAMM", model: "HD+120" },
{ make: "HAMM", model: "HD+120I" },
{ make: "HAMM", model: "HD+140" },
{ make: "HAMM", model: "HP100" },
{ make: "HAMM", model: "HP180" },
{ make: "HAMM", model: "HP280" },
{ make: "HAMM", model: "HTC15" },
{ make: "HAMM", model: "HW90" },
{ make: "HAMM", model: "HW2304" },
{ make: "HAMM", model: "HX70IOV" },
{ make: "HAMM", model: "HX90" },
{ make: "HAMM", model: "OTHER" },
 //
  //DYNAPAC
  //
{ make: "DYNAPAC", model: "CA15" },
{ make: "DYNAPAC", model: "CA25" },
{ make: "DYNAPAC", model: "CA30" },
{ make: "DYNAPAC", model: "CA55" },
{ make: "DYNAPAC", model: "CA121" },
{ make: "DYNAPAC", model: "CA134" },
{ make: "DYNAPAC", model: "CA150" },
{ make: "DYNAPAC", model: "CA151" },
{ make: "DYNAPAC", model: "CA152" },
{ make: "DYNAPAC", model: "CA250" },
{ make: "DYNAPAC", model: "CA251" },
{ make: "DYNAPAC", model: "CA252" },
{ make: "DYNAPAC", model: "CA255" },
{ make: "DYNAPAC", model: "CA260" },
{ make: "DYNAPAC", model: "CA262" },
{ make: "DYNAPAC", model: "CA301" },
{ make: "DYNAPAC", model: "CA302" },
{ make: "DYNAPAC", model: "CA305" },
{ make: "DYNAPAC", model: "CA362" },
{ make: "DYNAPAC", model: "CA511" },
{ make: "DYNAPAC", model: "CA512" },
{ make: "DYNAPAC", model: "CA602" },
{ make: "DYNAPAC", model: "CA612" },
{ make: "DYNAPAC", model: "CA1300" },
{ make: "DYNAPAC", model: "CA1400" },
{ make: "DYNAPAC", model: "CA1500" },
{ make: "DYNAPAC", model: "CA2500" },
{ make: "DYNAPAC", model: "CA2800" },
{ make: "DYNAPAC", model: "CA3500" },
{ make: "DYNAPAC", model: "CA4000" },
{ make: "DYNAPAC", model: "CA4600" },
{ make: "DYNAPAC", model: "CA5000" },
{ make: "DYNAPAC", model: "CA6000" },
{ make: "DYNAPAC", model: "CA6500" },
{ make: "DYNAPAC", model: "CC41" },
{ make: "DYNAPAC", model: "CC42" },
{ make: "DYNAPAC", model: "CC50" },
{ make: "DYNAPAC", model: "CC82" },
{ make: "DYNAPAC", model: "CC92" },
{ make: "DYNAPAC", model: "CC101" },
{ make: "DYNAPAC", model: "CC122" },
{ make: "DYNAPAC", model: "CC125" },
{ make: "DYNAPAC", model: "CC142" },
{ make: "DYNAPAC", model: "CC143" },
{ make: "DYNAPAC", model: "CC211" },
{ make: "DYNAPAC", model: "CC222" },
{ make: "DYNAPAC", model: "CC224" },
{ make: "DYNAPAC", model: "CC232" },
{ make: "DYNAPAC", model: "CC234" },
{ make: "DYNAPAC", model: "CC322" },
{ make: "DYNAPAC", model: "CC384" },
{ make: "DYNAPAC", model: "CC412" },
{ make: "DYNAPAC", model: "CC421" },
{ make: "DYNAPAC", model: "CC422" },
{ make: "DYNAPAC", model: "CC424" },
{ make: "DYNAPAC", model: "CC425" },
{ make: "DYNAPAC", model: "CC501" },
{ make: "DYNAPAC", model: "CC522" },
{ make: "DYNAPAC", model: "CC524" },
{ make: "DYNAPAC", model: "CC622" },
{ make: "DYNAPAC", model: "CC722" },
{ make: "DYNAPAC", model: "CC800" },
{ make: "DYNAPAC", model: "CC900" },
{ make: "DYNAPAC", model: "CC950" },
{ make: "DYNAPAC", model: "CC1000" },
{ make: "DYNAPAC", model: "CC1100" },
{ make: "DYNAPAC", model: "CC1200" },
{ make: "DYNAPAC", model: "CC1300" },
{ make: "DYNAPAC", model: "CC1400" },
{ make: "DYNAPAC", model: "CC2200" },
{ make: "DYNAPAC", model: "CC2300" },
{ make: "DYNAPAC", model: "CC3200" },
{ make: "DYNAPAC", model: "CC4200" },
{ make: "DYNAPAC", model: "CC5200" },
{ make: "DYNAPAC", model: "CC6200" },
{ make: "DYNAPAC", model: "CC7200" },
{ make: "DYNAPAC", model: "CO4200" },
{ make: "DYNAPAC", model: "CO5200" },
{ make: "DYNAPAC", model: "CP132" },
{ make: "DYNAPAC", model: "CP142" },
{ make: "DYNAPAC", model: "CP215" },
{ make: "DYNAPAC", model: "CP221" },
{ make: "DYNAPAC", model: "CP224" },
{ make: "DYNAPAC", model: "CP271" },
{ make: "DYNAPAC", model: "CP274" },
{ make: "DYNAPAC", model: "CP1200" },
{ make: "DYNAPAC", model: "CP2100" },
{ make: "DYNAPAC", model: "CP2700" },
{ make: "DYNAPAC", model: "CS12" },
{ make: "DYNAPAC", model: "CS141" },
{ make: "DYNAPAC", model: "CS142" },
{ make: "DYNAPAC", model: "CT25" },
{ make: "DYNAPAC", model: "CT260" },
{ make: "DYNAPAC", model: "CT262" },
{ make: "DYNAPAC", model: "CT3000" },
{ make: "DYNAPAC", model: "D.ONE" },
{ make: "DYNAPAC", model: "DFP7" },
{ make: "DYNAPAC", model: "DFP9" },
{ make: "DYNAPAC", model: "DFP10" },
{ make: "DYNAPAC", model: "DR6" },
{ make: "DYNAPAC", model: "DR7" },
{ make: "DYNAPAC", model: "DRP25" },
{ make: "DYNAPAC", model: "DRP45" },
{ make: "DYNAPAC", model: "DRP60" },
{ make: "DYNAPAC", model: "DRP70" },
{ make: "DYNAPAC", model: "DRQ15" },
{ make: "DYNAPAC", model: "LF70" },
{ make: "DYNAPAC", model: "LG200" },
{ make: "DYNAPAC", model: "LG500" },
{ make: "DYNAPAC", model: "LP750" },
{ make: "DYNAPAC", model: "LP8500" },
{ make: "DYNAPAC", model: "SR130" },
{ make: "DYNAPAC", model: "OTHER" },
   //
  //WACKER NUESON
  //
  { make: "WACKER NUESON", model: "AP1840" },
{ make: "WACKER NUESON", model: "AP1850" },
{ make: "WACKER NUESON", model: "APS" },
{ make: "WACKER NUESON", model: "APU3050" },
{ make: "WACKER NUESON", model: "AS50" },
{ make: "WACKER NUESON", model: "AS60" },
{ make: "WACKER NUESON", model: "BPS1030" },
{ make: "WACKER NUESON", model: "BPS1135" },
{ make: "WACKER NUESON", model: "BPS1340" },
{ make: "WACKER NUESON", model: "BPS1550" },
{ make: "WACKER NUESON", model: "BPU2540" },
{ make: "WACKER NUESON", model: "BPU3050" },
{ make: "WACKER NUESON", model: "BPU3750" },
{ make: "WACKER NUESON", model: "BPU4045" },
{ make: "WACKER NUESON", model: "BPU5260" },
{ make: "WACKER NUESON", model: "BPU5545" },
{ make: "WACKER NUESON", model: "BS50" },
{ make: "WACKER NUESON", model: "BS60" },
{ make: "WACKER NUESON", model: "BS62" },
{ make: "WACKER NUESON", model: "BS68" },
{ make: "WACKER NUESON", model: "BS70" },
{ make: "WACKER NUESON", model: "DPU40" },
{ make: "WACKER NUESON", model: "DPU45" },
{ make: "WACKER NUESON", model: "DPU80" },
{ make: "WACKER NUESON", model: "DPU90" },
{ make: "WACKER NUESON", model: "DPU100" },
{ make: "WACKER NUESON", model: "DPU110" },
{ make: "WACKER NUESON", model: "DPU130" },
{ make: "WACKER NUESON", model: "DPU2950" },
{ make: "WACKER NUESON", model: "DPU3050" },
{ make: "WACKER NUESON", model: "DPU4045" },
{ make: "WACKER NUESON", model: "DPU4545" },
{ make: "WACKER NUESON", model: "DPU5545" },
{ make: "WACKER NUESON", model: "DPU6055" },
{ make: "WACKER NUESON", model: "DPU6555" },
{ make: "WACKER NUESON", model: "RC50" },
{ make: "WACKER NUESON", model: "RC70" },
{ make: "WACKER NUESON", model: "RC110" },
{ make: "WACKER NUESON", model: "RD7" },
{ make: "WACKER NUESON", model: "RD11" },
{ make: "WACKER NUESON", model: "RD12" },
{ make: "WACKER NUESON", model: "RD12" },
{ make: "WACKER NUESON", model: "RD16" },
{ make: "WACKER NUESON", model: "RD18" },
{ make: "WACKER NUESON", model: "RD24" },
{ make: "WACKER NUESON", model: "RD25" },
{ make: "WACKER NUESON", model: "RD27" },
{ make: "WACKER NUESON", model: "RD28" },
{ make: "WACKER NUESON", model: "RD40" },
{ make: "WACKER NUESON", model: "RD45" },
{ make: "WACKER NUESON", model: "RD880" },
{ make: "WACKER NUESON", model: "RT" },
{ make: "WACKER NUESON", model: "RT560" },
{ make: "WACKER NUESON", model: "RT820" },
{ make: "WACKER NUESON", model: "RT825" },
{ make: "WACKER NUESON", model: "RTDSC4" },
{ make: "WACKER NUESON", model: "RTSC" },
{ make: "WACKER NUESON", model: "RTX" },
{ make: "WACKER NUESON", model: "RW25" },
{ make: "WACKER NUESON", model: "VP1135" },
{ make: "WACKER NUESON", model: "VP1550" },
{ make: "WACKER NUESON", model: "VP2050" },
{ make: "WACKER NUESON", model: "W65" },
{ make: "WACKER NUESON", model: "WP1550" },
{ make: "WACKER NUESON", model: "WPU1550" },
{ make: "WACKER NUESON", model: "OTHER" },
    //
  //VOLVO
  //
{ make: "VOLVO", model: "CR30" },
{ make: "VOLVO", model: "CR35" },
{ make: "VOLVO", model: "DD15" },
{ make: "VOLVO", model: "DD16" },
{ make: "VOLVO", model: "DD22" },
{ make: "VOLVO", model: "DD24" },
{ make: "VOLVO", model: "DD25" },
{ make: "VOLVO", model: "DD29" },
{ make: "VOLVO", model: "DD30" },
{ make: "VOLVO", model: "DD31" },
{ make: "VOLVO", model: "DD35" },
{ make: "VOLVO", model: "DD70" },
{ make: "VOLVO", model: "DD90" },
{ make: "VOLVO", model: "DD105" },
{ make: "VOLVO", model: "DD110" },
{ make: "VOLVO", model: "DD112" },
{ make: "VOLVO", model: "DD118" },
{ make: "VOLVO", model: "DD120" },
{ make: "VOLVO", model: "DD128" },
{ make: "VOLVO", model: "DD132" },
{ make: "VOLVO", model: "DD138" },
{ make: "VOLVO", model: "DD140" },
{ make: "VOLVO", model: "LC450" },
{ make: "VOLVO", model: "PT125" },
{ make: "VOLVO", model: "PT240" },
{ make: "VOLVO", model: "SD25" },
{ make: "VOLVO", model: "SD45" },
{ make: "VOLVO", model: "SD70" },
{ make: "VOLVO", model: "SD75" },
{ make: "VOLVO", model: "SD77" },
{ make: "VOLVO", model: "SD100" },
{ make: "VOLVO", model: "SD105" },
{ make: "VOLVO", model: "SD110" },
{ make: "VOLVO", model: "SD115" },
{ make: "VOLVO", model: "SD116" },
{ make: "VOLVO", model: "SD122" },
{ make: "VOLVO", model: "SD135" },
{ make: "VOLVO", model: "SD160" },
{ make: "VOLVO", model: "SD200" },
{ make: "VOLVO", model: "OTHER" },
    //
  //SAKAI
  //
{ make: "SAKAI", model: "CR270" },
{ make: "SAKAI", model: "CR271" },
{ make: "SAKAI", model: "CV550" },
{ make: "SAKAI", model: "GW750" },
{ make: "SAKAI", model: "GW751" },
{ make: "SAKAI", model: "GW754" },
{ make: "SAKAI", model: "HD67" },
{ make: "SAKAI", model: "PC600" },
{ make: "SAKAI", model: "PC800" },
{ make: "SAKAI", model: "PF150" },
{ make: "SAKAI", model: "R2" },
{ make: "SAKAI", model: "RS65" },
{ make: "SAKAI", model: "RS75" },
{ make: "SAKAI", model: "SA33" },
{ make: "SAKAI", model: "SV70" },
{ make: "SAKAI", model: "SV91" },
{ make: "SAKAI", model: "SV201" },
{ make: "SAKAI", model: "SV204" },
{ make: "SAKAI", model: "SV400" },
{ make: "SAKAI", model: "SV410" },
{ make: "SAKAI", model: "SV412" },
{ make: "SAKAI", model: "SV414" },
{ make: "SAKAI", model: "SV500" },
{ make: "SAKAI", model: "SV505" },
{ make: "SAKAI", model: "SV510" },
{ make: "SAKAI", model: "SV513" },
{ make: "SAKAI", model: "SV540" },
{ make: "SAKAI", model: "SV544" },
{ make: "SAKAI", model: "SV640" },
{ make: "SAKAI", model: "SW250" },
{ make: "SAKAI", model: "SW320" },
{ make: "SAKAI", model: "SW330" },
{ make: "SAKAI", model: "SW352" },
{ make: "SAKAI", model: "SW354" },
{ make: "SAKAI", model: "SW502" },
{ make: "SAKAI", model: "SW504" },
{ make: "SAKAI", model: "SW654" },
{ make: "SAKAI", model: "SW770" },
{ make: "SAKAI", model: "SW774" },
{ make: "SAKAI", model: "SW800" },
{ make: "SAKAI", model: "SW850" },
{ make: "SAKAI", model: "SW880" },
{ make: "SAKAI", model: "SW884" },
{ make: "SAKAI", model: "SW900" },
{ make: "SAKAI", model: "SW990" },
{ make: "SAKAI", model: "SW994" },
{ make: "SAKAI", model: "T2" },
{ make: "SAKAI", model: "TS31" },
{ make: "SAKAI", model: "TS160" },
{ make: "SAKAI", model: "TS200" },
{ make: "SAKAI", model: "TS7409" },
{ make: "SAKAI", model: "TW70" },
{ make: "SAKAI", model: "TW100" },
{ make: "SAKAI", model: "TW330" },
{ make: "SAKAI", model: "TW354" },
{ make: "SAKAI", model: "TW500" },
{ make: "SAKAI", model: "TW504" },
{ make: "SAKAI", model: "OTHER" },
    //
  //AMMANN
  //
{ make: "AMMANN", model: "AC90" },
{ make: "AMMANN", model: "ACR68" },
{ make: "AMMANN", model: "ACR70" },
{ make: "AMMANN", model: "AP240" },
{ make: "AMMANN", model: "APF1033" },
{ make: "AMMANN", model: "APF1240" },
{ make: "AMMANN", model: "APF1540" },
{ make: "AMMANN", model: "APF1550" },
{ make: "AMMANN", model: "APF2050" },
{ make: "AMMANN", model: "APH5020" },
{ make: "AMMANN", model: "APH5030" },
{ make: "AMMANN", model: "APH6530" },
{ make: "AMMANN", model: "APH6585" },
{ make: "AMMANN", model: "APR2240" },
{ make: "AMMANN", model: "APR2550" },
{ make: "AMMANN", model: "APR3020" },
{ make: "AMMANN", model: "APR3050" },
{ make: "AMMANN", model: "APR3060" },
{ make: "AMMANN", model: "APR4920" },
{ make: "AMMANN", model: "APR5920" },
{ make: "AMMANN", model: "ARP95" },
{ make: "AMMANN", model: "ARR1575" },
{ make: "AMMANN", model: "ARR1585" },
{ make: "AMMANN", model: "ARS30" },
{ make: "AMMANN", model: "ARS50" },
{ make: "AMMANN", model: "ARS70" },
{ make: "AMMANN", model: "ARS110" },
{ make: "AMMANN", model: "ARS110.2" },
{ make: "AMMANN", model: "ARS122" },
{ make: "AMMANN", model: "ARS130" },
{ make: "AMMANN", model: "ARS200" },
{ make: "AMMANN", model: "ART35" },
{ make: "AMMANN", model: "ART240" },
{ make: "AMMANN", model: "ART280" },
{ make: "AMMANN", model: "ARW65" },
{ make: "AMMANN", model: "ARX10.1" },
{ make: "AMMANN", model: "ARX12" },
{ make: "AMMANN", model: "ARX16" },
{ make: "AMMANN", model: "ARX20" },
{ make: "AMMANN", model: "ARX23" },
{ make: "AMMANN", model: "ARX26" },
{ make: "AMMANN", model: "ARX36" },
{ make: "AMMANN", model: "ARX40" },
{ make: "AMMANN", model: "ARX45" },
{ make: "AMMANN", model: "ARX90" },
{ make: "AMMANN", model: "ARX140" },
{ make: "AMMANN", model: "ASC30" },
{ make: "AMMANN", model: "ASC70" },
{ make: "AMMANN", model: "ASC100" },
{ make: "AMMANN", model: "ASC110" },
{ make: "AMMANN", model: "ASC130" },
{ make: "AMMANN", model: "ASC150" },
{ make: "AMMANN", model: "ASC200" },
{ make: "AMMANN", model: "ATR60" },
{ make: "AMMANN", model: "ATR68" },
{ make: "AMMANN", model: "AV12" },
{ make: "AMMANN", model: "AV16" },
{ make: "AMMANN", model: "AV26" },
{ make: "AMMANN", model: "AV70" },
{ make: "AMMANN", model: "AV85" },
{ make: "AMMANN", model: "AV95" },
{ make: "AMMANN", model: "AV130" },
{ make: "AMMANN", model: "AVH5020" },
{ make: "AMMANN", model: "AVP1240" },
{ make: "AMMANN", model: "AVP1850" },
{ make: "AMMANN", model: "DT200" },
{ make: "AMMANN", model: "DTV143" },
{ make: "AMMANN", model: "DTV903" },
{ make: "AMMANN", model: "EARX26-2" },
{ make: "AMMANN", model: "RW1800" },
{ make: "AMMANN", model: "RAMMAX" },
{ make: "AMMANN", model: "SV216" },
{ make: "AMMANN", model: "VP2400" },
{ make: "AMMANN", model: "OTHER" },
  
];

export default compactionRollersTaxonomy;
