// /lib/cranesTaxonomy.js

const cranesTaxonomy = [
  
  //
  //ALTEC
  //
{ make: "ALTEC", model: "A40" },
{ make: "ALTEC", model: "A55" },
{ make: "ALTEC", model: "A65" },
{ make: "ALTEC", model: "A35" },
{ make: "ALTEC", model: "A72" },
{ make: "ALTEC", model: "A75" },
{ make: "ALTEC", model: "A77" },
{ make: "ALTEC", model: "A470" },
{ make: "ALTEC", model: "A771" },
{ make: "ALTEC", model: "AA28" },
{ make: "ALTEC", model: "AA55" },
{ make: "ALTEC", model: "AA60" },
{ make: "ALTEC", model: "AA77" },
{ make: "ALTEC", model: "AA280" },
{ make: "ALTEC", model: "AA600" },
{ make: "ALTEC", model: "AA755" },
{ make: "ALTEC", model: "AC18" },
{ make: "ALTEC", model: "AC23" },
{ make: "ALTEC", model: "AC26" },
{ make: "ALTEC", model: "AC30" },
{ make: "ALTEC", model: "AC38" },
{ make: "ALTEC", model: "AC40" },
{ make: "ALTEC", model: "AC45" },
{ make: "ALTEC", model: "AH85" },
{ make: "ALTEC", model: "AH100" },
{ make: "ALTEC", model: "AH125" },
{ make: "ALTEC", model: "AM50" },
{ make: "ALTEC", model: "AM55" },
{ make: "ALTEC", model: "AM60" },
{ make: "ALTEC", model: "AM450" },
{ make: "ALTEC", model: "AM650" },
{ make: "ALTEC", model: "AM855" },
{ make: "ALTEC", model: "AM900" },
{ make: "ALTEC", model: "AN55" },
{ make: "ALTEC", model: "AN67" },
{ make: "ALTEC", model: "AN546" },
{ make: "ALTEC", model: "AN652" },
{ make: "ALTEC", model: "SN50" },
{ make: "ALTEC", model: "SN55" },
{ make: "ALTEC", model: "AN67" },
{ make: "ALTEC", model: "AN546" },
{ make: "ALTEC", model: "AN652" },
{ make: "ALTEC", model: "AP36" },
{ make: "ALTEC", model: "AP40" },
{ make: "ALTEC", model: "AT35" },
{ make: "ALTEC", model: "AT37" },
{ make: "ALTEC", model: "AT40" },
{ make: "ALTEC", model: "AT41" },
{ make: "ALTEC", model: "AT48" },
{ make: "ALTEC", model: "AT200" },
{ make: "ALTEC", model: "AT235" },
{ make: "ALTEC", model: "AT237" },
{ make: "ALTEC", model: "AT238" },
{ make: "ALTEC", model: "AT248" },
{ make: "ALTEC", model: "D820" },
{ make: "ALTEC", model: "D842" },
{ make: "ALTEC", model: "D845" },
{ make: "ALTEC", model: "D945" },
{ make: "ALTEC", model: "D947" },
{ make: "ALTEC", model: "D1000" },
{ make: "ALTEC", model: "D2045" },
{ make: "ALTEC", model: "D2050" },
{ make: "ALTEC", model: "D2055" },
{ make: "ALTEC", model: "D3050" },
{ make: "ALTEC", model: "D3055" },
{ make: "ALTEC", model: "D3060" },
{ make: "ALTEC", model: "D4050" },
{ make: "ALTEC", model: "D4060" },
{ make: "ALTEC", model: "D4065" },
{ make: "ALTEC", model: "DB35" },
{ make: "ALTEC", model: "DB37" },
{ make: "ALTEC", model: "DB41" },
{ make: "ALTEC", model: "DC45" },
{ make: "ALTEC", model: "DC47" },
{ make: "ALTEC", model: "DL42" },
{ make: "ALTEC", model: "DL45" },
{ make: "ALTEC", model: "DM45" },
{ make: "ALTEC", model: "DM47" },
{ make: "ALTEC", model: "DT65" },
{ make: "ALTEC", model: "DT80" },
{ make: "ALTEC", model: "DT105" },
{ make: "ALTEC", model: "ENTERGY AT37" },
{ make: "ALTEC", model: "HL125" },
{ make: "ALTEC", model: "L36" },
{ make: "ALTEC", model: "L37" },
{ make: "ALTEC", model: "L42" },
{ make: "ALTEC", model: "L44" },
{ make: "ALTEC", model: "L45" },
{ make: "ALTEC", model: "LR7" },
{ make: "ALTEC", model: "LR760" },
{ make: "ALTEC", model: "LRIII55" },
{ make: "ALTEC", model: "LRV55" },
{ make: "ALTEC", model: "LRV56" },
{ make: "ALTEC", model: "LRV57" },
{ make: "ALTEC", model: "LRV58" },
{ make: "ALTEC", model: "LRV60" },
{ make: "ALTEC", model: "LS40" },
{ make: "ALTEC", model: "LS49" },
{ make: "ALTEC", model: "LS60" },
{ make: "ALTEC", model: "LS87" },
{ make: "ALTEC", model: "LS63" },
{ make: "ALTEC", model: "T40" },
{ make: "ALTEC", model: "TA37" },
{ make: "ALTEC", model: "TA40" },
{ make: "ALTEC", model: "TA41" },
{ make: "ALTEC", model: "TA45" },
{ make: "ALTEC", model: "TA50" },
{ make: "ALTEC", model: "TA60" },
{ make: "ALTEC", model: "OTHER" },
//
//TEREX
//
{ make: "TEREX", model: "5TC-55" },
{ make: "TEREX", model: "AC30" },
{ make: "TEREX", model: "AC35" },
{ make: "TEREX", model: "AC40" },
{ make: "TEREX", model: "AC40/2" },
{ make: "TEREX", model: "AC50" },
{ make: "TEREX", model: "AC55" },
{ make: "TEREX", model: "AC60" },
{ make: "TEREX", model: "AC70" },
{ make: "TEREX", model: "AC100" },
{ make: "TEREX", model: "AC200" },
{ make: "TEREX", model: "AC350" },
{ make: "TEREX", model: "AC500" },
{ make: "TEREX", model: "AT15" },
{ make: "TEREX", model: "AT20" },
{ make: "TEREX", model: "AT40" },
{ make: "TEREX", model: "ATT400" },
{ make: "TEREX", model: "ATT1300" },
{ make: "TEREX", model: "BT2047" },
{ make: "TEREX", model: "BT3060" },
{ make: "TEREX", model: "BT3400" },
{ make: "TEREX", model: "BT3470" },
{ make: "TEREX", model: "BT3870" },
{ make: "TEREX", model: "BT3874" },
{ make: "TEREX", model: "BT4772" },
{ make: "TEREX", model: "BT4792" },
{ make: "TEREX", model: "BT5092" },
{ make: "TEREX", model: "BT28106" },
{ make: "TEREX", model: "CBR36" },
{ make: "TEREX", model: "CBR40" },
{ make: "TEREX", model: "CC400" },
{ make: "TEREX", model: "CC2500" },
{ make: "TEREX", model: "CC2800" },
{ make: "TEREX", model: "CC3800" },
{ make: "TEREX", model: "CD225" },
{ make: "TEREX", model: "CHALLENGER 3160" },
{ make: "TEREX", model: "COMMANDER 4040" },
{ make: "TEREX", model: "COMMANDER 4042" },
{ make: "TEREX", model: "COMMANDER 4045" },
{ make: "TEREX", model: "COMMANDER 4047" },
{ make: "TEREX", model: "COMMANDER 4050" },
{ make: "TEREX", model: "COMMANDER 5045" },
{ make: "TEREX", model: "COMMANDER 5048" },
{ make: "TEREX", model: "COMMANDER 5050" },
{ make: "TEREX", model: "COMMANDER 5052" },
{ make: "TEREX", model: "COMMANDER 6000" },
{ make: "TEREX", model: "COMMANDER 6054" },
{ make: "TEREX", model: "COMMANDER 6060" },
{ make: "TEREX", model: "COMMANDER 7000" },
{ make: "TEREX", model: "CROSSOVER 4500" },
{ make: "TEREX", model: "CROSSOVER 6000" },
{ make: "TEREX", model: "CROSSOVER 8000" },
{ make: "TEREX", model: "CTL140" },
{ make: "TEREX", model: "CTL 260" },
{ make: "TEREX", model: "CTYL 430" },
{ make: "TEREX", model: "CTL 630" },
{ make: "TEREX", model: "CTT121" },
{ make: "TEREX", model: "CTT132" },
{ make: "TEREX", model: "CTT172" },
{ make: "TEREX", model: "CTT181" },
{ make: "TEREX", model: "CTT182" },
{ make: "TEREX", model: "CTT202" },
{ make: "TEREX", model: "CTT331" },
{ make: "TEREX", model: "CT332" },
{ make: "TEREX", model: "CTT531" },
{ make: "TEREX", model: "CTT561" },
{ make: "TEREX", model: "CTT321" },
{ make: "TEREX", model: "EXPLORER 5500" },
{ make: "TEREX", model: "EXPLORER 5800" },
{ make: "TEREX", model: "GENERAL 54" },
{ make: "TEREX", model: "GENERAL 65" },
{ make: "TEREX", model: "GENERAL 80" },
{ make: "TEREX", model: "HC80" },
{ make: "TEREX", model: "HC110" },
{ make: "TEREX", model: "HC120" },
{ make: "TEREX", model: "HC230" },
{ make: "TEREX", model: "HC275" },
{ make: "TEREX", model: "HC285" },
{ make: "TEREX", model: "HI RANGER 6TC-65" },
{ make: "TEREX", model: "HR37" },
{ make: "TEREX", model: "HR40" },
{ make: "TEREX", model: "HR46" },
{ make: "TEREX", model: "HR50" },
{ make: "TEREX", model: "HR55" },
{ make: "TEREX", model: "HR5TC" },
{ make: "TEREX", model: "HRX52" },
{ make: "TEREX", model: "HRX55" },
{ make: "TEREX", model: "HIRANGER 5FC-60" },
{ make: "TEREX", model: "HIRANGER 5TC-52" },
{ make: "TEREX", model: "HIRANGER 5TC-55" },
{ make: "TEREX", model: "HIRANGER 50M" },
{ make: "TEREX", model: "HIRANGER" },
{ make: "TEREX", model: "HR46M" },
{ make: "TEREX", model: "HIRANGER 52M" },
{ make: "TEREX", model: "HIRANGER HRX-60" },
{ make: "TEREX", model: "HIRANGER LT40" },
{ make: "TEREX", model: "HIRANGER TC55" },
{ make: "TEREX", model: "HIRANGER HRX-60" },
{ make: "TEREX", model: "HIRANGER LT40" },
{ make: "TEREX", model: "HIRANGER TC55" },
{ make: "TEREX", model: "HIRANGER TL37M" },
{ make: "TEREX", model: "HIRANGER TL45" },
{ make: "TEREX", model: "HIRANGER TL55" },
{ make: "TEREX", model: "HIRANGER XT55" },
{ make: "TEREX", model: "HIRANGER XT60" },
{ make: "TEREX", model: "L4040" },
{ make: "TEREX", model: "LRT110" },
{ make: "TEREX", model: "LT38" },
{ make: "TEREX", model: "LT40" },
{ make: "TEREX", model: "LTM40" },
{ make: "TEREX", model: "MAC 25" },
{ make: "TEREX", model: "NT29" },
{ make: "TEREX", model: "OPTIMA HRX55" },
{ make: "TEREX", model: "OPTIMA TC55" },
{ make: "TEREX", model: "OPTIMA TCX55" },
{ make: "TEREX", model: "POWERLIFT 1000" },
{ make: "TEREX", model: "QUADSTAR 1065" },
{ make: "TEREX", model: "QUADSTAR 1075" },
{ make: "TEREX", model: "QUADSTAR 1100" },
{ make: "TEREX", model: "RC30" },
{ make: "TEREX", model: "RM75/100" },
{ make: "TEREX", model: "RM4792" },
{ make: "TEREX", model: "RS600" },
{ make: "TEREX", model: "RS70100" },
{ make: "TEREX", model: "RT90" },
{ make: "TEREX", model: "RT100" },
{ make: "TEREX", model: "RT130" },
{ make: "TEREX", model: "RT160" },
{ make: "TEREX", model: "RT190" },
{ make: "TEREX", model: "RT230" },
{ make: "TEREX", model: "RT335" },
{ make: "TEREX", model: "RT345" },
{ make: "TEREX", model: "RT445" },
{ make: "TEREX", model: "RT555" },
{ make: "TEREX", model: "RT665" },
{ make: "TEREX", model: "RT670" },
{ make: "TEREX", model: "RT780" },
{ make: "TEREX", model: "SC45" },
{ make: "TEREX", model: "SK415" },
{ make: "TEREX", model: "SK575" },
{ make: "TEREX", model: "SW35" },
{ make: "TEREX", model: "T230" },
{ make: "TEREX", model: "T292" },
{ make: "TEREX", model: "T335" },
{ make: "TEREX", model: "T340" },
{ make: "TEREX", model: "T550" },
{ make: "TEREX", model: "T560" },
{ make: "TEREX", model: "T775" },
{ make: "TEREX", model: "T780" },
{ make: "TEREX", model: "TC40" },
{ make: "TEREX", model: "TC55" },
{ make: "TEREX", model: "TC2863" },
{ make: "TEREX", model: "TC3063" },
{ make: "TEREX", model: "TC3470" },
{ make: "TEREX", model: "TC3874" },
{ make: "TEREX", model: "TCX55" },
{ make: "TEREX", model: "TCX65/100" },
{ make: "TEREX", model: "TEXOMA 650" },
{ make: "TEREX", model: "TL37" },
{ make: "TEREX", model: "TL38" },
{ make: "TEREX", model: "TL41" },
{ make: "TEREX", model: "TL50" },
{ make: "TEREX", model: "TM100" },
{ make: "TEREX", model: "TM105" },
{ make: "TEREX", model: "TM125" },
{ make: "TEREX", model: "TM3851" },
{ make: "TEREX", model: "TRT40" },
{ make: "TEREX", model: "TRT55" },
{ make: "TEREX", model: "TRT70" },
{ make: "TEREX", model: "TRT80" },
{ make: "TEREX", model: "TRT100" },
{ make: "TEREX", model: "XL4045" },
{ make: "TEREX", model: "XM55" },
{ make: "TEREX", model: "XT PRO 56" },
{ make: "TEREX", model: "XT PRTO 60" },
{ make: "TEREX", model: "XT PRO 60/70" },
{ make: "TEREX", model: "OTHER" },
//
//GROVE
//
{ make: "GROVE", model: "68" },
{ make: "GROVE", model: "315" },
{ make: "GROVE", model: "AP206" },
{ make: "GROVE", model: "AP308" },
{ make: "GROVE", model: "AT633" },
{ make: "GROVE", model: "AT700" },
{ make: "GROVE", model: "AT735" },
{ make: "GROVE", model: "AT750" },
{ make: "GROVE", model: "GCD09" },
{ make: "GROVE", model: "GCD15" },
{ make: "GROVE", model: "GCD20" },
{ make: "GROVE", model: "GCD25" },
{ make: "GROVE", model: "GCK3045" },
{ make: "GROVE", model: "GHC55" },
{ make: "GROVE", model: "GHC75" },
{ make: "GROVE", model: "GHC85" },
{ make: "GROVE", model: "GHC110" },
{ make: "GROVE", model: "GHC130" },
{ make: "GROVE", model: "GHC140" },
{ make: "GROVE", model: "GMK2035" },
{ make: "GROVE", model: "GMK3050" },
{ make: "GROVE", model: "GMK3055" },
{ make: "GROVE", model: "GMK3060" },
{ make: "GROVE", model: "GMK4075" },
{ make: "GROVE", model: "GMK4080" },
{ make: "GROVE", model: "GMK4090" },
{ make: "GROVE", model: "GMK4100" },
{ make: "GROVE", model: "GMK4115" },
{ make: "GROVE", model: "GMK5090" },
{ make: "GROVE", model: "GMK5095" },
{ make: "GROVE", model: "GMK5100" },
{ make: "GROVE", model: "GMK5110" },
{ make: "GROVE", model: "GMK5120" },
{ make: "GROVE", model: "GMK5130" },
{ make: "GROVE", model: "GMK5150" },
{ make: "GROVE", model: "GMK5160" },
{ make: "GROVE", model: "GMK5165" },
{ make: "GROVE", model: "GMK5175" },
{ make: "GROVE", model: "GMK5180" },
{ make: "GROVE", model: "GMK5200" },
{ make: "GROVE", model: "GMK5210" },
{ make: "GROVE", model: "GMK5220" },
{ make: "GROVE", model: "GMK5225" },
{ make: "GROVE", model: "GMK5240" },
{ make: "GROVE", model: "GMK5250" },
{ make: "GROVE", model: "GMK5275" },
{ make: "GROVE", model: "GMK6220" },
{ make: "GROVE", model: "GMK6250" },
{ make: "GROVE", model: "GMK6300" },
{ make: "GROVE", model: "GMK6350" },
{ make: "GROVE", model: "GMK6400" },
{ make: "GROVE", model: "GMK6450" },
{ make: "GROVE", model: "GMK7450" },
{ make: "GROVE", model: "GMK7550" },
{ make: "GROVE", model: "GRT650" },
{ make: "GROVE", model: "GRT655" },
{ make: "GROVE", model: "GRT765" },
{ make: "GROVE", model: "GRT780" },
{ make: "GROVE", model: "GRT880" },
{ make: "GROVE", model: "GRT8090" },
{ make: "GROVE", model: "GRT8100" },
{ make: "GROVE", model: "GRT8120" },
{ make: "GROVE", model: "GRT9165" },
{ make: "GROVE", model: "HL150" },
{ make: "GROVE", model: "IND24" },
{ make: "GROVE", model: "IND36" },
{ make: "GROVE", model: "MLC150" },
{ make: "GROVE", model: "RT58" },
{ make: "GROVE", model: "RT59" },
{ make: "GROVE", model: "RT60" },
{ make: "GROVE", model: "RT65" },
{ make: "GROVE", model: "RT75" },
{ make: "GROVE", model: "RT422" },
{ make: "GROVE", model: "RT500" },
{ make: "GROVE", model: "RT518" },
{ make: "GROVE", model: "RT522" },
{ make: "GROVE", model: "RT525" },
{ make: "GROVE", model: "RT528" },
{ make: "GROVE", model: "RT530" },
{ make: "GROVE", model: "RT535" },
{ make: "GROVE", model: "RT540" },
{ make: "GROVE", model: "RT550" },
{ make: "GROVE", model: "RT600" },
{ make: "GROVE", model: "RT620" },
{ make: "GROVE", model: "RT625" },
{ make: "GROVE", model: "RT630" },
{ make: "GROVE", model: "RT635" },
{ make: "GROVE", model: "RT640" },
{ make: "GROVE", model: "RT650" },
{ make: "GROVE", model: "RT700" },
{ make: "GROVE", model: "RT740" },
{ make: "GROVE", model: "RT745" },
{ make: "GROVE", model: "RT750" },
{ make: "GROVE", model: "RT760" },
{ make: "GROVE", model: "RT765" },
{ make: "GROVE", model: "RT770" },
{ make: "GROVE", model: "RT800" },
{ make: "GROVE", model: "RT855" },
{ make: "GROVE", model: "RT865" },
{ make: "GROVE", model: "RT870" },
{ make: "GROVE", model: "RT875" },
{ make: "GROVE", model: "RT880" },
{ make: "GROVE", model: "RT890" },
{ make: "GROVE", model: "RT980" },
{ make: "GROVE", model: "RT9100" },
{ make: "GROVE", model: "RT9130" },
{ make: "GROVE", model: "RT9150" },
{ make: "GROVE", model: "TD180" },
{ make: "GROVE", model: "TM80/88T" },
{ make: "GROVE", model: "TM150" },
{ make: "GROVE", model: "TM500" },
{ make: "GROVE", model: "TM550" },
{ make: "GROVE", model: "TM750" },
{ make: "GROVE", model: "TM800" },
{ make: "GROVE", model: "TM890" },
{ make: "GROVE", model: "TM1150" },
{ make: "GROVE", model: "TM1275" },
{ make: "GROVE", model: "TMSS225" },
{ make: "GROVE", model: "TMS250" },
{ make: "GROVE", model: "TMS300" },
{ make: "GROVE", model: "TMS375" },
{ make: "GROVE", model: "TMS475" },
{ make: "GROVE", model: "TMS500" },
{ make: "GROVE", model: "TMS520" },
{ make: "GROVE", model: "TMS635" },
{ make: "GROVE", model: "TMS640" },
{ make: "GROVE", model: "TMS700" },
{ make: "GROVE", model: "TMS760" },
{ make: "GROVE", model: "TMS800" },
{ make: "GROVE", model: "TMS870" },
{ make: "GROVE", model: "TMS880" },
{ make: "GROVE", model: "TMS900" },
{ make: "GROVE", model: "TMS9000" },
{ make: "GROVE", model: "TTS870" },
{ make: "GROVE", model: "YB4409" },
{ make: "GROVE", model: "YB4410" },
{ make: "GROVE", model: "YB4411" },
{ make: "GROVE", model: "YB5515" },
{ make: "GROVE", model: "YB7725" },
{ make: "GROVE", model: "OTHER" },
//
//XCMG
//
{ make: "XCMG", model: "APC6013" },
{ make: "XCMG", model: "GKS28" },
{ make: "XCMG", model: "GSQS200" },
{ make: "XCMG", model: "GSQS300" },
{ make: "XCMG", model: "GSQS350" },
{ make: "XCMG", model: "GSQS400" },
{ make: "XCMG", model: "QAY 160" },
{ make: "XCMG", model: "QAY 200" },
{ make: "XCMG", model: "QAY 240" },
{ make: "XCMG", model: "QAY 260" },
{ make: "XCMG", model: "QAY 300" },
{ make: "XCMG", model: "QAY 400" },
{ make: "XCMG", model: "QAY 500" },
{ make: "XCMG", model: "QAY 650" },
{ make: "XCMG", model: "QAY 800" },
{ make: "XCMG", model: "QAY 1000" },
{ make: "XCMG", model: "QAY 1200" },
{ make: "XCMG", model: "QTZ63" },
{ make: "XCMG", model: "QUY55" },
{ make: "XCMG", model: "QUY80" },
{ make: "XCMG", model: "QUY500" },
{ make: "XCMG", model: "QY12" },
{ make: "XCMG", model: "QY16" },
{ make: "XCMG", model: "QY20" },
{ make: "XCMG", model: "QY25" },
{ make: "XCMG", model: "QY30" },
{ make: "XCMG", model: "QY35" },
{ make: "XCMG", model: "QY40" },
{ make: "XCMG", model: "QY50" },
{ make: "XCMG", model: "QY55" },
{ make: "XCMG", model: "QY60" },
{ make: "XCMG", model: "QY70" },
{ make: "XCMG", model: "QY75" },
{ make: "XCMG", model: "QY80" },
{ make: "XCMG", model: "QY95" },
{ make: "XCMG", model: "QY100" },
{ make: "XCMG", model: "QY110" },
{ make: "XCMG", model: "QY130" },
{ make: "XCMG", model: "QY180" },
{ make: "XCMG", model: "SQS300" },
{ make: "XCMG", model: "SQS350" },
{ make: "XCMG", model: "TSQ3SK2Q" },
{ make: "XCMG", model: "XCA40" },
{ make: "XCMG", model: "XCA60" },
{ make: "XCMG", model: "XCA80" },
{ make: "XCMG", model: "XCA100" },
{ make: "XCMG", model: "XCA130" },
{ make: "XCMG", model: "XCA160" },
{ make: "XCMG", model: "XCA180" },
{ make: "XCMG", model: "XCA200" },
{ make: "XCMG", model: "XCA220" },
{ make: "XCMG", model: "XCA230" },
{ make: "XCMG", model: "XCA250" },
{ make: "XCMG", model: "XCA260" },
{ make: "XCMG", model: "XCA300" },
{ make: "XCMG", model: "XCA350" },
{ make: "XCMG", model: "XCA460" },
{ make: "XCMG", model: "XCA500" },
{ make: "XCMG", model: "XCA550" },
{ make: "XCMG", model: "XCA600" },
{ make: "XCMG", model: "XCA700" },
{ make: "XCMG", model: "XCA750" },
{ make: "XCMG", model: "XCA1200" },
{ make: "XCMG", model: "XCA1600" },
{ make: "XCMG", model: "XCP330" },
{ make: "XCMG", model: "XCR25" },
{ make: "XCMG", model: "XCR30" },
{ make: "XCMG", model: "XCR40" },
{ make: "XCMG", model: "XCR50" },
{ make: "XCMG", model: "XCR55" },
{ make: "XCMG", model: "XCR60" },
{ make: "XCMG", model: "XCR70" },
{ make: "XCMG", model: "XCR90" },
{ make: "XCMG", model: "XCR90" },
{ make: "XCMG", model: "XCR100" },
{ make: "XCMG", model: "XCR130" },
{ make: "XCMG", model: "XCT12" },
{ make: "XCMG", model: "XCT16" },
{ make: "XCMG", model: "XCT20" },
{ make: "XCMG", model: "XCT25" },
{ make: "XCMG", model: "XCT45" },
{ make: "XCMG", model: "XCT80" },
{ make: "XCMG", model: "XCT95" },
{ make: "XCMG", model: "XCT100" },
{ make: "XCMG", model: "XCT110" },
{ make: "XCMG", model: "XCT30" },
{ make: "XCMG", model: "XCT35" },
{ make: "XCMG", model: "XCT40" },
{ make: "XCMG", model: "XCT50" },
{ make: "XCMG", model: "XCT55" },
{ make: "XCMG", model: "XCT60" },
{ make: "XCMG", model: "XCT70" },
{ make: "XCMG", model: "XCT75" },
{ make: "XCMG", model: "XCT85" },
{ make: "XCMG", model: "XCT90" },
{ make: "XCMG", model: "XCT100" },
{ make: "XCMG", model: "XCT130" },
{ make: "XCMG", model: "XGA5610" },
{ make: "XCMG", model: "XGA6012" },
{ make: "XCMG", model: "XGA6013" },
{ make: "XCMG", model: "XGC25" },
{ make: "XCMG", model: "XGC30" },
{ make: "XCMG", model: "XGC40" },
{ make: "XCMG", model: "XGC55" },
{ make: "XCMG", model: "XGC75" },
{ make: "XCMG", model: "XGC85" },
{ make: "XCMG", model: "XGC100" },
{ make: "XCMG", model: "XGC130" },
{ make: "XCMG", model: "XGC150" },
{ make: "XCMG", model: "XGC180" },
{ make: "XCMG", model: "XGC260" },
{ make: "XCMG", model: "XGC300" },
{ make: "XCMG", model: "XGC400" },
{ make: "XCMG", model: "XGC500" },
{ make: "XCMG", model: "XGC650" },
{ make: "XCMG", model: "XGC800" },
{ make: "XCMG", model: "XGC2100" },
{ make: "XCMG", model: "XGC11000" },
{ make: "XCMG", model: "XGC12000" },
{ make: "XCMG", model: "XGC15000" },
{ make: "XCMG", model: "XGC16000" },
{ make: "XCMG", model: "XGC28000" },
{ make: "XCMG", model: "XGT360" },
{ make: "XCMG", model: "XGT600" },
{ make: "XCMG", model: "XGT1350" },
{ make: "XCMG", model: "XGT5610" },
{ make: "XCMG", model: "XGT6010" },
{ make: "XCMG", model: "XGT6013" },
{ make: "XCMG", model: "XGT6015" },
{ make: "XCMG", model: "XGT6018" },
{ make: "XCMG", model: "XGT6513" },
{ make: "XCMG", model: "XGT6515" },
{ make: "XCMG", model: "XGT6522" },
{ make: "XCMG", model: "XGT7020" },
{ make: "XCMG", model: "XGT7022" },
{ make: "XCMG", model: "XGT7026" },
{ make: "XCMG", model: "XGT7528" },
{ make: "XCMG", model: "XGTL120" },
{ make: "XCMG", model: "XLC260M" },
{ make: "XCMG", model: "XZJ5290" },
{ make: "XCMG", model: "OTHER" },
//
//LIEBHERR
//
{ make: "LIEBHERR", model: "20K" },
{ make: "LIEBHERR", model: "24K" },
{ make: "LIEBHERR", model: "56K" },
{ make: "LIEBHERR", model: "81K" },
{ make: "LIEBHERR", model: "112K" },
{ make: "LIEBHERR", model: "120K" },
{ make: "LIEBHERR", model: "200" },
{ make: "LIEBHERR", model: "245" },
{ make: "LIEBHERR", model: "290" },
{ make: "LIEBHERR", model: "355" },
{ make: "LIEBHERR", model: "357" },
{ make: "LIEBHERR", model: "420" },
{ make: "LIEBHERR", model: "550" },
{ make: "LIEBHERR", model: "710" },
{ make: "LIEBHERR", model: "HS841" },
{ make: "LIEBHERR", model: "HS842" },
{ make: "LIEBHERR", model: "HS843" },
{ make: "LIEBHERR", model: "HS845" },
{ make: "LIEBHERR", model: "HS853" },
{ make: "LIEBHERR", model: "HS855" },
{ make: "LIEBHERR", model: "HS872" },
{ make: "LIEBHERR", model: "HS873" },
{ make: "LIEBHERR", model: "HS875" },
{ make: "LIEBHERR", model: "HS883" },
{ make: "LIEBHERR", model: "HS885" },
{ make: "LIEBHERR", model: "HS8100" },
{ make: "LIEBHERR", model: "HS8130" },
{ make: "LIEBHERR", model: "HS8200" },
{ make: "LIEBHERR", model: "LG1550" },
{ make: "LIEBHERR", model: "LG1750" },
{ make: "LIEBHERR", model: "LGD1550" },
{ make: "LIEBHERR", model: "LGD1800" },
{ make: "LIEBHERR", model: "LHM250" },
{ make: "LIEBHERR", model: "LHM400" },
{ make: "LIEBHERR", model: "LHM1200" },
{ make: "LIEBHERR", model: "LHM1300" },
{ make: "LIEBHERR", model: "LR1100" },
{ make: "LIEBHERR", model: "LR1110" },
{ make: "LIEBHERR", model: "LR1130" },
{ make: "LIEBHERR", model: "LR1140" },
{ make: "LIEBHERR", model: "LR1160" },
{ make: "LIEBHERR", model: "LR1200" },
{ make: "LIEBHERR", model: "LR1250" },
{ make: "LIEBHERR", model: "LR1280" },
{ make: "LIEBHERR", model: "LR1300" },
{ make: "LIEBHERR", model: "LR1350" },
{ make: "LIEBHERR", model: "LR1400" },
{ make: "LIEBHERR", model: "LR1500" },
{ make: "LIEBHERR", model: "LR1550" },
{ make: "LIEBHERR", model: "LR1600" },
{ make: "LIEBHERR", model: "LR1650" },
{ make: "LIEBHERR", model: "LR1750" },
{ make: "LIEBHERR", model: "LR1800" },
{ make: "LIEBHERR", model: "LR11000" },
{ make: "LIEBHERR", model: "LTR11350" },
{ make: "LIEBHERR", model: "LRT1090" },
{ make: "LIEBHERR", model: "LRT1100" },
{ make: "LIEBHERR", model: "LT1055" },
{ make: "LIEBHERR", model: "LTC1045" },
{ make: "LIEBHERR", model: "LTC1050" },
{ make: "LIEBHERR", model: "LTC1055" },
{ make: "LIEBHERR", model: "LTF1035" },
{ make: "LIEBHERR", model: "LTF1045" },
{ make: "LIEBHERR", model: "LTL1030" },
{ make: "LIEBHERR", model: "LTM1025" },
{ make: "LIEBHERR", model: "LTM1030" },
{ make: "LIEBHERR", model: "LTM1035" },
{ make: "LIEBHERR", model: "LTM1040" },
{ make: "LIEBHERR", model: "LTM1045" },
{ make: "LIEBHERR", model: "LTM1050" },
{ make: "LIEBHERR", model: "LTM1055" },
{ make: "LIEBHERR", model: "LTM1060" },
{ make: "LIEBHERR", model: "LTM1070" },
{ make: "LIEBHERR", model: "LTM1080" },
{ make: "LIEBHERR", model: "LTM1090" },
{ make: "LIEBHERR", model: "LTM1095" },
{ make: "LIEBHERR", model: "LTM1100" },
{ make: "LIEBHERR", model: "LTM1110" },
{ make: "LIEBHERR", model: "LTM1120" },
{ make: "LIEBHERR", model: "LTM1130" },
{ make: "LIEBHERR", model: "LTM1150" },
{ make: "LIEBHERR", model: "LTM1160" },
{ make: "LIEBHERR", model: "LTM1200" },
{ make: "LIEBHERR", model: "LTM1220" },
{ make: "LIEBHERR", model: "LTM1225" },
{ make: "LIEBHERR", model: "LTM1230" },
{ make: "LIEBHERR", model: "LTM1250" },
{ make: "LIEBHERR", model: "LTM1300" },
{ make: "LIEBHERR", model: "LTM1350" },
{ make: "LIEBHERR", model: "LTM1400" },
{ make: "LIEBHERR", model: "LTM1450" },
{ make: "LIEBHERR", model: "LTM1500" },
{ make: "LIEBHERR", model: "LTM1650" },
{ make: "LIEBHERR", model: "LTM1750" },
{ make: "LIEBHERR", model: "LTM1800" },
{ make: "LIEBHERR", model: "LTM11200" },
{ make: "LIEBHERR", model: "LTR1060" },
{ make: "LIEBHERR", model: "LTR1100" },
{ make: "LIEBHERR", model: "LTR1150" },
{ make: "LIEBHERR", model: "LTR1220" },
{ make: "LIEBHERR", model: "LTR11200" },
{ make: "LIEBHERR", model: "MK63" },
{ make: "LIEBHERR", model: "MK88" },
{ make: "LIEBHERR", model: "MK100" },
{ make: "LIEBHERR", model: "MK140" },
{ make: "LIEBHERR", model: "OTHER" },
  //
//TADANO
//
{ make: "TADANO", model: "AC2" },
{ make: "TADANO", model: "AC3" },
{ make: "TADANO", model: "AC4" },
{ make: "TADANO", model: "AC5" },
{ make: "TADANO", model: "AC6" },
{ make: "TADANO", model: "AC7" },
{ make: "TADANO", model: "AC8" },
{ make: "TADANO", model: "AR1000" },
{ make: "TADANO", model: "AT250" },
{ make: "TADANO", model: "ATF40" },
{ make: "TADANO", model: "ATF45" },
{ make: "TADANO", model: "ATF50" },
{ make: "TADANO", model: "ATF60" },
{ make: "TADANO", model: "ATF65" },
{ make: "TADANO", model: "ATF70" },
{ make: "TADANO", model: "ATF80" },
{ make: "TADANO", model: "ATF100" },
{ make: "TADANO", model: "ATF110" },
{ make: "TADANO", model: "ATF130" },
{ make: "TADANO", model: "ATF160" },
{ make: "TADANO", model: "ATF200" },
{ make: "TADANO", model: "ATF220" },
{ make: "TADANO", model: "ATF400" },
{ make: "TADANO", model: "ATF500" },
{ make: "TADANO", model: "CC24" },
{ make: "TADANO", model: "CC28" },
{ make: "TADANO", model: "CC38" },
{ make: "TADANO", model: "CC68" },
{ make: "TADANO", model: "CC88" },
{ make: "TADANO", model: "EGR100" },
{ make: "TADANO", model: "GR120" },
{ make: "TADANO", model: "GR150" },
{ make: "TADANO", model: "GR160" },
{ make: "TADANO", model: "GR250" },
{ make: "TADANO", model: "GR300" },
{ make: "TADANO", model: "GR350" },
{ make: "TADANO", model: "GR500" },
{ make: "TADANO", model: "GR550" },
//
//LINK BELT
// 
{ make: "LINK-BELT", model: "65" },
{ make: "LINK-BELT", model: "75" },
{ make: "LINK-BELT", model: "80" },
{ make: "LINK-BELT", model: "85" },
{ make: "LINK-BELT", model: "90" },
{ make: "LINK-BELT", model: "100" },
{ make: "LINK-BELT", model: "110" },
{ make: "LINK-BELT", model: "120" },
{ make: "LINK-BELT", model: "138" },
{ make: "LINK-BELT", model: "175" },
{ make: "LINK-BELT", model: "218" },
{ make: "LINK-BELT", model: "228" },
{ make: "LINK-BELT", model: "238" },
{ make: "LINK-BELT", model: "248" },
{ make: "LINK-BELT", model: "298" },
{ make: "LINK-BELT", model: "300" },
{ make: "LINK-BELT", model: "348" },
{ make: "LINK-BELT", model: "ATC822" },
{ make: "LINK-BELT", model: "ATC3210" },
{ make: "LINK-BELT", model: "ATC3250" },
{ make: "LINK-BELT", model: "ATC3275" },
{ make: "LINK-BELT", model: "HC108" },
{ make: "LINK-BELT", model: "HC138" },
{ make: "LINK-BELT", model: "HC218" },
{ make: "LINK-BELT", model: "HC228" },
{ make: "LINK-BELT", model: "HC238" },
{ make: "LINK-BELT", model: "HC258" },
{ make: "LINK-BELT", model: "HC268" },
{ make: "LINK-BELT", model: "HC278" },
{ make: "LINK-BELT", model: "HC518" },
{ make: "LINK-BELT", model: "HSP25" },
{ make: "LINK-BELT", model: "HSP4035" },
{ make: "LINK-BELT", model: "HSP8018" },
{ make: "LINK-BELT", model: "HSP8030" },
{ make: "LINK-BELT", model: "HSP8040" },
{ make: "LINK-BELT", model: "HSP8050" },
{ make: "LINK-BELT", model: "HSP8055" },
{ make: "LINK-BELT", model: "HSP8060" },
{ make: "LINK-BELT", model: "HT300" },
{ make: "LINK-BELT", model: "HT400" },
{ make: "LINK-BELT", model: "HTC14" },
{ make: "LINK-BELT", model: "HTC25" },
{ make: "LINK-BELT", model: "HTC35" },
{ make: "LINK-BELT", model: "HTC50" },
{ make: "LINK-BELT", model: "HTC835" },
{ make: "LINK-BELT", model: "HTC850" },
{ make: "LINK-BELT", model: "HTC867" },
{ make: "LINK-BELT", model: "HTC1040" },
{ make: "LINK-BELT", model: "HTC3140" },
{ make: "LINK-BELT", model: "HTC8040" },
{ make: "LINK-BELT", model: "htc83635" },
{ make: "LINK-BELT", model: "HTC8640" },
{ make: "LINK-BELT", model: "HTC8650" },
{ make: "LINK-BELT", model: "HTC8660" },
{ make: "LINK-BELT", model: "HTC8670" },
{ make: "LINK-BELT", model: "HTC8675" },
{ make: "LINK-BELT", model: "HTC8690" },
{ make: "LINK-BELT", model: "HTC11100" },
{ make: "LINK-BELT", model: "HTC86100" },
{ make: "LINK-BELT", model: "HTC86110" },
{ make: "LINK-BELT", model: "HTT8675" },
{ make: "LINK-BELT", model: "HTT86100" },
{ make: "LINK-BELT", model: "LS78" },
{ make: "LINK-BELT", model: "LS98" },
{ make: "LINK-BELT", model: "LS108" },
{ make: "LINK-BELT", model: "LS118" },
{ make: "LINK-BELT", model: "LS128" },
{ make: "LINK-BELT", model: "LS138" },
{ make: "LINK-BELT", model: "LS218" },
{ make: "LINK-BELT", model: "LS238" },
{ make: "LINK-BELT", model: "LS248" },
{ make: "LINK-BELT", model: "LS278" },
{ make: "LINK-BELT", model: "LS318" },
{ make: "LINK-BELT", model: "LS338" },
{ make: "LINK-BELT", model: "LS348" },
{ make: "LINK-BELT", model: "LS408" },
{ make: "LINK-BELT", model: "LS418" },
{ make: "LINK-BELT", model: "LS518" },
{ make: "LINK-BELT", model: "LS718" },
{ make: "LINK-BELT", model: "RTC8030" },
{ make: "LINK-BELT", model: "RTC8035" },
{ make: "LINK-BELT", model: "RTYC8040" },
{ make: "LINK-BELT", model: "RTC8050" },
{ make: "LINK-BELT", model: "RTC8060" },
{ make: "LINK-BELT", model: "RTC8065" },
{ make: "LINK-BELT", model: "RTC8070" },
{ make: "LINK-BELT", model: "RTC8075" },
{ make: "LINK-BELT", model: "RTC8080" },
{ make: "LINK-BELT", model: "RTC8090" },
{ make: "LINK-BELT", model: "RTC80100" },
{ make: "LINK-BELT", model: "RTC80110" },
{ make: "LINK-BELT", model: "RTC80130" },
{ make: "LINK-BELT", model: "RTC80150" },
{ make: "LINK-BELT", model: "RTC80160" },
{ make: "LINK-BELT", model: "TCC450" },
{ make: "LINK-BELT", model: "TCC500" },
{ make: "LINK-BELT", model: "TCC550" },
{ make: "LINK-BELT", model: "TCC800" },
{ make: "LINK-BELT", model: "TCC750" },
{ make: "LINK-BELT", model: "TCC1100" },
{ make: "LINK-BELT", model: "TCC1200" },
{ make: "LINK-BELT", model: "TC1400" },
{ make: "LINK-BELT", model: "TCC2500" },
{ make: "LINK-BELT", model: "UC108" },
{ make: "LINK-BELT", model: "OTHER" },
//
//VERSALIFT
//
{ make: "VERSALIFT", model: "CTA130" },
{ make: "VERSALIFT", model: "ET25" },
{ make: "VERSALIFT", model: "ET32" },
{ make: "VERSALIFT", model: "PHX" },
{ make: "VERSALIFT", model: "SHV28" },
{ make: "VERSALIFT", model: "SHV35" },
{ make: "VERSALIFT", model: "SST36" },
{ make: "VERSALIFT", model: "SST37" },
{ make: "VERSALIFT", model: "SST40" },
{ make: "VERSALIFT", model: "STP36" },
{ make: "VERSALIFT", model: "T34I" },
{ make: "VERSALIFT", model: "TEL29" },
{ make: "VERSALIFT", model: "TEL35" },
{ make: "VERSALIFT", model: "TM3000" },
{ make: "VERSALIFT", model: "TM3045" },
{ make: "VERSALIFT", model: "TMD2047" },
{ make: "VERSALIFT", model: "TMD2050" },
{ make: "VERSALIFT", model: "TMD4060" },
{ make: "VERSALIFT", model: "V0270" },
{ make: "VERSALIFT", model: "VAN TEL 29" },
{ make: "VERSALIFT", model: "VN50I05" },
{ make: "VERSALIFT", model: "VN555MHI" },
{ make: "VERSALIFT", model: "VO29" },
{ make: "VERSALIFT", model: "VO32" },
{ make: "VERSALIFT", model: "VO40" },
{ make: "VERSALIFT", model: "VO42" },
{ make: "VERSALIFT", model: "VO43" },
{ make: "VERSALIFT", model: "VO50" },
{ make: "VERSALIFT", model: "VO55" },
{ make: "VERSALIFT", model: "VO260" },
{ make: "VERSALIFT", model: "V0270" },
{ make: "VERSALIFT", model: "VO350" },
{ make: "VERSALIFT", model: "VO355" },
{ make: "VERSALIFT", model: "VO360" },
{ make: "VERSALIFT", model: "VO455" },
{ make: "VERSALIFT", model: "VO460" },
{ make: "VERSALIFT", model: "VST40" },
{ make: "VERSALIFT", model: "VST43" },
{ make: "VERSALIFT", model: "VST47" },
{ make: "VERSALIFT", model: "VST50" },
{ make: "VERSALIFT", model: "VST52" },
{ make: "VERSALIFT", model: "VST55" },
{ make: "VERSALIFT", model: "VST240" },
{ make: "VERSALIFT", model: "VST5000" },
{ make: "VERSALIFT", model: "VST5500" },
{ make: "VERSALIFT", model: "VST6000" },
{ make: "VERSALIFT", model: "VST7100" },
{ make: "VERSALIFT", model: "VST7500" },
{ make: "VERSALIFT", model: "VST9000" },
{ make: "VERSALIFT", model: "VST9500" },
{ make: "VERSALIFT", model: "VT28" },
{ make: "VERSALIFT", model: "VT29" },
{ make: "VERSALIFT", model: "VTP40" },
{ make: "VERSALIFT", model: "VXD47" },
{ make: "VERSALIFT", model: "OTHER" },
//
//MANITEX
//
{ make: "MANITEX", model: "102" },
{ make: "MANITEX", model: "124" },
{ make: "MANITEX", model: "1161" },
{ make: "MANITEX", model: "1970" },
{ make: "MANITEX", model: "2250" },
{ make: "MANITEX", model: "2281" },
{ make: "MANITEX", model: "2892" },
{ make: "MANITEX", model: "3051" },
{ make: "MANITEX", model: "3071" },
{ make: "MANITEX", model: "4596" },
{ make: "MANITEX", model: "22101" },
{ make: "MANITEX", model: "26101" },
{ make: "MANITEX", model: "28100" },
{ make: "MANITEX", model: "30100" },
{ make: "MANITEX", model: "30102" },
{ make: "MANITEX", model: "30112" },
{ make: "MANITEX", model: "35124" },
{ make: "MANITEX", model: "38124" },
{ make: "MANITEX", model: "40124" },
{ make: "MANITEX", model: "45110" },
{ make: "MANITEX", model: "50110" },
{ make: "MANITEX", model: "50128" },
{ make: "MANITEX", model: "50155" },
{ make: "MANITEX", model: "A62" },
{ make: "MANITEX", model: "CD110" },
{ make: "MANITEX", model: "CD4430" },
{ make: "MANITEX", model: "M150" },
{ make: "MANITEX", model: "M300" },
{ make: "MANITEX", model: "M2592" },
{ make: "MANITEX", model: "MAC 15525" },
{ make: "MANITEX", model: "PL74" },
{ make: "MANITEX", model: "SC62" },
{ make: "MANITEX", model: "SC75" },
{ make: "MANITEX", model: "TC700" },
{ make: "MANITEX", model: "TC400" },
{ make: "MANITEX", model: "TC450" },
{ make: "MANITEX", model: "TC500" },
{ make: "MANITEX", model: "TC650" },
{ make: "MANITEX", model: "TM200" },
{ make: "MANITEX", model: "TM240" },
{ make: "MANITEX", model: "OTHER" },
//
//NATIONAL
//
{ make: "NATIONAL", model: "6T" },
{ make: "NATIONAL", model: "300" },
{ make: "NATIONAL", model: "400" },
{ make: "NATIONAL", model: "500" },
{ make: "NATIONAL", model: "600" },
{ make: "NATIONAL", model: "800" },
{ make: "NATIONAL", model: "880" },
{ make: "NATIONAL", model: "900" },
{ make: "NATIONAL", model: "1100" },
{ make: "NATIONAL", model: "1200" },
{ make: "NATIONAL", model: "1300" },
{ make: "NATIONAL", model: "1400" },
{ make: "NATIONAL", model: "1500" },
{ make: "NATIONAL", model: "1800" },
{ make: "NATIONAL", model: "8000" },
{ make: "NATIONAL", model: "8100" },
{ make: "NATIONAL", model: "9000" },
{ make: "NATIONAL", model: "9100" },
{ make: "NATIONAL", model: "13000" },
{ make: "NATIONAL", model: "14000" },
{ make: "NATIONAL", model: "18000" },
{ make: "NATIONAL", model: "N50" },
{ make: "NATIONAL", model: "N65" },
{ make: "NATIONAL", model: "N80" },
{ make: "NATIONAL", model: "N85" },
{ make: "NATIONAL", model: "N95" },
{ make: "NATIONAL", model: "N160" },
{ make: "NATIONAL", model: "N205" },
{ make: "NATIONAL", model: "NBT14" },
{ make: "NATIONAL", model: "NBT16" },
{ make: "NATIONAL", model: "NBT30" },
{ make: "NATIONAL", model: "NBT36" },
{ make: "NATIONAL", model: "NBT40" },
{ make: "NATIONAL", model: "NBT45" },
{ make: "NATIONAL", model: "NBT50" },
{ make: "NATIONAL", model: "NBT55" },
{ make: "NATIONAL", model: "NBT60" },
{ make: "NATIONAL", model: "OTHER" },
//
//AMERICAN
//
{ make: "AMERICAN", model: "595" },
{ make: "AMERICAN", model: "597" },
{ make: "AMERICAN", model: "599" },
{ make: "AMERICAN", model: "797" },
{ make: "AMERICAN", model: "850" },
{ make: "AMERICAN", model: "998" },
{ make: "AMERICAN", model: "999" },
{ make: "AMERICAN", model: "4250" },
{ make: "AMERICAN", model: "4260" },
{ make: "AMERICAN", model: "4460" },
{ make: "AMERICAN", model: "5030" },
{ make: "AMERICAN", model: "5220" },
{ make: "AMERICAN", model: "5299" },
{ make: "AMERICAN", model: "5300" },
{ make: "AMERICAN", model: "5530" },
{ make: "AMERICAN", model: "5680" },
{ make: "AMERICAN", model: "7150" },
{ make: "AMERICAN", model: "7220" },
{ make: "AMERICAN", model: "7250" },
{ make: "AMERICAN", model: "7260" },
{ make: "AMERICAN", model: "7460" },
{ make: "AMERICAN", model: "7510" },
{ make: "AMERICAN", model: "7530" },
{ make: "AMERICAN", model: "8460" },
{ make: "AMERICAN", model: "8470" },
{ make: "AMERICAN", model: "9260" },
{ make: "AMERICAN", model: "9299" },
{ make: "AMERICAN", model: "9310" },
{ make: "AMERICAN", model: "9320" },
{ make: "AMERICAN", model: "9520" },
{ make: "AMERICAN", model: "9750" },
{ make: "AMERICAN", model: "11320" },
{ make: "AMERICAN", model: "A100" },
{ make: "AMERICAN", model: "A1500" },
{ make: "AMERICAN", model: "HC80" },
{ make: "AMERICAN", model: "HC110" },
{ make: "AMERICAN", model: "OTHER" },  
//
//AUTO CRANE
//
{ make: "AUTO CRANE", model: "3200" },
{ make: "AUTO CRANE", model: "3203" },
{ make: "AUTO CRANE", model: "4004" },
{ make: "AUTO CRANE", model: "6006" },
{ make: "AUTO CRANE", model: "A72A" },
{ make: "AUTO CRANE", model: "EHC32" },
{ make: "AUTO CRANE", model: "EHC-4 20" },
{ make: "AUTO CRANE", model: "HC6" },
{ make: "AUTO CRANE", model: "HC7" },
{ make: "AUTO CRANE", model: "HC8" },
{ make: "AUTO CRANE", model: "HC10" },
{ make: "AUTO CRANE", model: "HC12" },
{ make: "AUTO CRANE", model: "TITAN 38" },
{ make: "AUTO CRANE", model: "OTHER" },
//
//BRODERSON
//
{ make: "BRODERSON", model: "IC20" },
{ make: "BRODERSON", model: "IC35" },
{ make: "BRODERSON", model: "IC40" },
{ make: "BRODERSON", model: "IC80" },
{ make: "BRODERSON", model: "IC100" },
{ make: "BRODERSON", model: "IC200" },
{ make: "BRODERSON", model: "IC250" },
{ make: "BRODERSON", model: "IC280" },
{ make: "BRODERSON", model: "IC400" },
{ make: "BRODERSON", model: "RT200" },
{ make: "BRODERSON", model: "RT300" },
{ make: "BRODERSON", model: "RT400" },
{ make: "BRODERSON", model: "OTHER" },
//
//BIK
//  
{ make: "BIK", model: "65" },
{ make: "BIK", model: "70" },
{ make: "BIK", model: "FC67" },
{ make: "BIK", model: "FC70" },
{ make: "BIK", model: "FC75" },
{ make: "BIK", model: "FC76" },
{ make: "BIK", model: "FC81" },
{ make: "BIK", model: "FC92" },
{ make: "BIK", model: "FC110" },
{ make: "BIK", model: "HL40" },
{ make: "BIK", model: "HL45" },
{ make: "BIK", model: "HL58" },
{ make: "BIK", model: "HL86" },
{ make: "BIK", model: "HL100" },
{ make: "BIK", model: "RC31" },
{ make: "BIK", model: "RC41" },
{ make: "BIK", model: "TC70" },
{ make: "BIK", model: "TC78" },
{ make: "BIK", model: "TC92" },
{ make: "BIK", model: "TC98" },
{ make: "BIK", model: "TC104" },
{ make: "BIK", model: "TC106" },
{ make: "BIK", model: "TC118" },
{ make: "BIK", model: "TC124" },
{ make: "BIK", model: "TC126" },
{ make: "BIK", model: "TC170" },
{ make: "BIK", model: "WC75" },
{ make: "BIK", model: "OTHER" },
//
//CORMACH
//
{ make: "CORMACH", model: "6800" },
{ make: "CORMACH", model: "110000" },
{ make: "CORMACH", model: "12000" },
{ make: "CORMACH", model: "14000" },
{ make: "CORMACH", model: "16600" },
{ make: "CORMACH", model: "19000" },
{ make: "CORMACH", model: "22500" },
{ make: "CORMACH", model: "28000" },
{ make: "CORMACH", model: "28200" },
{ make: "CORMACH", model: "30000" },
{ make: "CORMACH", model: "34000" },
{ make: "CORMACH", model: "39000" },
{ make: "CORMACH", model: "40400" },
{ make: "CORMACH", model: "50000" },
{ make: "CORMACH", model: "51800" },
{ make: "CORMACH", model: "60000" },
{ make: "CORMACH", model: "75000" },
{ make: "CORMACH", model: "95000" },
{ make: "CORMACH", model: "150000" },
{ make: "CORMACH", model: "185000" },
{ make: "CORMACH", model: "240000" },
{ make: "CORMACH", model: "575000" },
{ make: "CORMACH", model: "OTHER" },
//
//DALL'AGIO NEWCRANES
//
{ make: "DALL'AGLIO NEWCRANES", model: "DN2.7" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN3.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN3.6" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN4.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN5.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN6.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN7.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN7.7" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN8.7" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN9.7" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN9.7" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN12.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN13.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN15.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN17.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN19.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN22.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN243.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN24.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN27.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN30.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN33.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN37.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DN44.0" },
{ make: "DALL'AGLIO NEWCRANES", model: "DNM1.1" },
{ make: "DALL'AGLIO NEWCRANES", model: "DNM1.4" },
{ make: "DALL'AGLIO NEWCRANES", model: "DNM1.9" },
{ make: "DALL'AGLIO NEWCRANES", model: "DNM2.2" },
{ make: "DALL'AGLIO NEWCRANES", model: "DNM2.7" },
{ make: "DALL'AGLIO NEWCRANES", model: "DNM3.3" },
{ make: "DALL'AGLIO NEWCRANES", model: "DNM3.8" },
{ make: "DALL'AGLIO NEWCRANES", model: "DNM4.3" },
{ make: "DALL'AGLIO NEWCRANES", model: "OTHER" },  
//
//DEMAG
//
{ make: "DEMAG", model: "5T" },
{ make: "DEMAG", model: "AC25" },
{ make: "DEMAG", model: "AC30" },
{ make: "DEMAG", model: "AC40" },
{ make: "DEMAG", model: "AC50" },
{ make: "DEMAG", model: "AC55" },
{ make: "DEMAG", model: "AC60" },
{ make: "DEMAG", model: "AC70" },
{ make: "DEMAG", model: "AC80" },
{ make: "DEMAG", model: "AC100" },
{ make: "DEMAG", model: "AC120" },
{ make: "DEMAG", model: "AC140" },
{ make: "DEMAG", model: "AC160" },
{ make: "DEMAG", model: "AC180" },
{ make: "DEMAG", model: "AC200" },
{ make: "DEMAG", model: "AC205" },
{ make: "DEMAG", model: "AC220" },
{ make: "DEMAG", model: "AC250" },
{ make: "DEMAG", model: "AC300" },
{ make: "DEMAG", model: "AC350" },
{ make: "DEMAG", model: "AC500" },
{ make: "DEMAG", model: "AC535" },
{ make: "DEMAG", model: "AC700" },
{ make: "DEMAG", model: "AC1000" },
{ make: "DEMAG", model: "AC1200" },
{ make: "DEMAG", model: "AC1300" },
{ make: "DEMAG", model: "CC280" },
{ make: "DEMAG", model: "CC300" },
{ make: "DEMAG", model: "CC600" },
{ make: "DEMAG", model: "CC1100" },
{ make: "DEMAG", model: "CC1800" },
{ make: "DEMAG", model: "CC2200" },
{ make: "DEMAG", model: "CC2400" },
{ make: "DEMAG", model: "CC2500" },
{ make: "DEMAG", model: "CC2600" },
{ make: "DEMAG", model: "CC2800" },
{ make: "DEMAG", model: "CC3800" },
{ make: "DEMAG", model: "CC4800" },
{ make: "DEMAG", model: "CC6800" },
{ make: "DEMAG", model: "CC8800" },
{ make: "DEMAG", model: "MHC360" },
{ make: "DEMAG", model: "TC2600" },
{ make: "DEMAG", model: "TC2800" },
{ make: "DEMAG", model: "TC3200" },
{ make: "DEMAG", model: "OTHER" },
//
//DUR-A-LIFT
//
{ make: "DUR-A-LIFT", model: "DCP36" },
{ make: "DUR-A-LIFT", model: "DHT34" },
{ make: "DUR-A-LIFT", model: "DLT2" },
{ make: "DUR-A-LIFT", model: "DO32" },
{ make: "DUR-A-LIFT", model: "DO36" },
{ make: "DUR-A-LIFT", model: "DPM2" },
{ make: "DUR-A-LIFT", model: "DPM52" },
{ make: "DUR-A-LIFT", model: "DTA2" },
{ make: "DUR-A-LIFT", model: "DT29" },
{ make: "DUR-A-LIFT", model: "DTA35" },
{ make: "DUR-A-LIFT", model: "DTAS35" },
{ make: "DUR-A-LIFT", model: "DTAXS39" },
{ make: "DUR-A-LIFT", model: "DTAX2" },
{ make: "DUR-A-LIFT", model: "DTAX39" },
{ make: "DUR-A-LIFT", model: "DTS29" },
{ make: "DUR-A-LIFT", model: "DVS29" },
{ make: "DUR-A-LIFT", model: "DVT29" },
{ make: "DUR-A-LIFT", model: "V34" },
{ make: "DUR-A-LIFT", model: "OTHER" },
//
//ELLIOT
//
{ make: "ELLIOT", model: "1056" },
{ make: "ELLIOT", model: "1860" },
{ make: "ELLIOT", model: "1870" },
{ make: "ELLIOT", model: "1881" },
{ make: "ELLIOT", model: "2695" },
{ make: "ELLIOT", model: "26105" },
{ make: "ELLIOT", model: "30105" },
{ make: "ELLIOT", model: "32105" },
{ make: "ELLIOT", model: "36127" },
{ make: "ELLIOT", model: "40105" },
{ make: "ELLIOT", model: "40142" },
{ make: "ELLIOT", model: "45127" },
{ make: "ELLIOT", model: "45142" },
{ make: "ELLIOT", model: "A41" },
{ make: "ELLIOT", model: "D86" },
{ make: "ELLIOT", model: "D100" },
{ make: "ELLIOT", model: "D105" },
{ make: "ELLIOT", model: "E145" },
{ make: "ELLIOT", model: "E160" },
{ make: "ELLIOT", model: "ECA411" },
{ make: "ELLIOT", model: "ECE3" },
{ make: "ELLIOT", model: "ECI3" },
{ make: "ELLIOT", model: "G85" },
{ make: "ELLIOT", model: "H57" },
{ make: "ELLIOT", model: "H60" },
{ make: "ELLIOT", model: "H70" },
{ make: "ELLIOT", model: "H110" },
{ make: "ELLIOT", model: "I50" },
{ make: "ELLIOT", model: "L50" },
{ make: "ELLIOT", model: "L55" },
{ make: "ELLIOT", model: "L60" },
{ make: "ELLIOT", model: "L65" },
{ make: "ELLIOT", model: "M43" },
{ make: "ELLIOT", model: "M87" },
{ make: "ELLIOT", model: "UC40142" },
{ make: "ELLIOT", model: "V60" },
{ make: "ELLIOT", model: "V63" },
{ make: "ELLIOT", model: "OTHER" },
//
//ETI
//
{ make: "ETI", model: "800-40" },
{ make: "ETI", model: "ETA37" },
{ make: "ETI", model: "ETC35SNT" },
{ make: "ETI", model: "ETC37IH" },
{ make: "ETI", model: "ETC40IH" },
{ make: "ETI", model: "ETC" },
{ make: "ETI", model: "ETCMH" },
{ make: "ETI", model: "ETOMH" },
{ make: "ETI", model: "ETT29" },
{ make: "ETI", model: "OTHER" }, 
//
//FASSI
//
{ make: "FASSI", model: "F26" },
{ make: "FASSI", model: "F32" },
{ make: "FASSI", model: "F50" },
{ make: "FASSI", model: "F40" },
{ make: "FASSI", model: "F60" },
{ make: "FASSI", model: "F65" },
{ make: "FASSI", model: "F85" },
{ make: "FASSI", model: "F95" },
{ make: "FASSI", model: "F110" },
{ make: "FASSI", model: "F115" },
{ make: "FASSI", model: "F130" },
{ make: "FASSI", model: "F135" },
{ make: "FASSI", model: "F145" },
{ make: "FASSI", model: "F155" },
{ make: "FASSI", model: "F165" },
{ make: "FASSI", model: "F170" },
{ make: "FASSI", model: "F185" },
{ make: "FASSI", model: "F190" },
{ make: "FASSI", model: "F195" },
{ make: "FASSI", model: "F200" },
{ make: "FASSI", model: "F215" },
{ make: "FASSI", model: "F230" },
{ make: "FASSI", model: "F235" },
{ make: "FASSI", model: "F240" },
{ make: "FASSI", model: "F245" },
{ make: "FASSI", model: "F250" },
{ make: "FASSI", model: "F255" },
{ make: "FASSI", model: "F260" },
{ make: "FASSI", model: "F270" },
{ make: "FASSI", model: "F275" },
{ make: "FASSI", model: "F280" },
{ make: "FASSI", model: "F290" },
{ make: "FASSI", model: "F295" },
{ make: "FASSI", model: "F315" },
{ make: "FASSI", model: "F330" },
{ make: "FASSI", model: "F335" },
{ make: "FASSI", model: "F340" },
{ make: "FASSI", model: "F345" },
{ make: "FASSI", model: "F360" },
{ make: "FASSI", model: "F365" },
{ make: "FASSI", model: "F375" },
{ make: "FASSI", model: "F385" },
{ make: "FASSI", model: "F390" },
{ make: "FASSI", model: "F420" },
{ make: "FASSI", model: "F425" },
{ make: "FASSI", model: "F450" },
{ make: "FASSI", model: "F455" },
{ make: "FASSI", model: "F485" },
{ make: "FASSI", model: "F545" },
{ make: "FASSI", model: "F660" },
{ make: "FASSI", model: "F805" },
{ make: "FASSI", model: "F905" },
{ make: "FASSI", model: "F1050" },
{ make: "FASSI", model: "F1150" },
{ make: "FASSI", model: "F1250" },
{ make: "FASSI", model: "F1950" },
{ make: "FASSI", model: "F2350" },
{ make: "FASSI", model: "MICRO M10" },
{ make: "FASSI", model: "MICRO M20" },
{ make: "FASSI", model: "MICRO M25" },
{ make: "FASSI", model: "MICRO M30" },
{ make: "FASSI", model: "OTHER" },
//
//HIAB
//
{ make: "HIAB", model: "007" },
{ make: "HIAB", model: "045" },
{ make: "HIAB", model: "060" },
{ make: "HIAB", model: "070" },
{ make: "HIAB", model: "071" },
{ make: "HIAB", model: "077" },
{ make: "HIAB", model: "081" },
{ make: "HIAB", model: "090" },
{ make: "HIAB", model: "095" },
{ make: "HIAB", model: "105" },
{ make: "HIAB", model: "111" },
{ make: "HIAB", model: "122" },
{ make: "HIAB", model: "125" },
{ make: "HIAB", model: "135" },
{ make: "HIAB", model: "144" },
{ make: "HIAB", model: "166" },
{ make: "HIAB", model: "175" },
{ make: "HIAB", model: "200" },
{ make: "HIAB", model: "225" },
{ make: "HIAB", model: "244" },
{ make: "HIAB", model: "250" },
{ make: "HIAB", model: "255" },
{ make: "HIAB", model: "288" },
{ make: "HIAB", model: "300" },
{ make: "HIAB", model: "335" },
{ make: "HIAB", model: "1100" },
{ make: "HIAB", model: "2650" },
{ make: "HIAB", model: "J145" },
{ make: "HIAB", model: "J245" },
{ make: "HIAB", model: "JOEBOY" },
{ make: "HIAB", model: "K-HIPRO 425" },
{ make: "HIAB", model: "K-HIPRO 505" },
{ make: "HIAB", model: "L-HIPRO 235" },
{ make: "HIAB", model: "R240" },
{ make: "HIAB", model: "R300" },
{ make: "HIAB", model: "S-CLX 100 D-2" },
{ make: "HIAB", model: "X-CLX 128" },
{ make: "HIAB", model: "X-DUO 078" },
{ make: "HIAB", model: "X-DUO 102" },
{ make: "HIAB", model: "X-DUO 128" },
{ make: "HIAB", model: "X-DUO 178" },
{ make: "HIAB", model: "X-HIDUO 082" },
{ make: "HIAB", model: "X-HIDUO 118" },
{ make: "HIAB", model: "X-HIDUO 138" },
{ make: "HIAB", model: "X-HIDUO 158" },
{ make: "HIAB", model: "X-HIDUO 258" },
{ make: "HIAB", model: "X-HIDUO 232" },
{ make: "HIAB", model: "X-HIPRO 352" },
{ make: "HIAB", model: "X-HIPRO 358" },
{ make: "HIAB", model: "X-HIPRO 418" },
{ make: "HIAB", model: "X-HIPRO 558" },
{ make: "HIAB", model: "XS033" },
{ make: "HIAB", model: "XS055" },
{ make: "HIAB", model: "XS099" },
{ make: "HIAB", model: "XS122" },
{ make: "HIAB", model: "XS111" },
{ make: "HIAB", model: "XS144" },
{ make: "HIAB", model: "XS166" },
{ make: "HIAB", model: "XS211" },
{ make: "HIAB", model: "XS244" },
{ make: "HIAB", model: "XS255" },
{ make: "HIAB", model: "XS288" },
{ make: "HIAB", model: "XS322" },
{ make: "HIAB", model: "XS335" },
{ make: "HIAB", model: "XS377" },
{ make: "HIAB", model: "XS422" },
{ make: "HIAB", model: "XS477" },
{ make: "HIAB", model: "XS600" },
{ make: "HIAB", model: "8108-2" },
{ make: "HIAB", model: "OTHER" },  
//
//HITACHI
//
{ make: "HITACHI", model: "FK150" },
{ make: "HITACHI", model: "FK300" },
{ make: "HITACHI", model: "KH100" },
{ make: "HITACHI", model: "KH125" },
{ make: "HITACHI", model: "KH150" },
{ make: "HITACHI", model: "KH180" },
{ make: "HITACHI", model: "KH230" },
{ make: "HITACHI", model: "KH300" },
{ make: "HITACHI", model: "KH500" },
{ make: "HITACHI", model: "KH700" },
{ make: "HITACHI", model: "KH850" },
{ make: "HITACHI", model: "KH1000" },
{ make: "HITACHI", model: "PD135" },
{ make: "HITACHI", model: "OTHER" },
//
//HORYONG
//
{ make: "HORYONG", model: "MR450A" },
{ make: "HORYONG", model: "SKY450" },
{ make: "HORYONG", model: "SKY600" },
{ make: "HORYONG", model: "SKY750" },
{ make: "HORYONG", model: "SKY2804" },
{ make: "HORYONG", model: "SKY3004" },
{ make: "HORYONG", model: "OTHER" },
//
//IMT
//
{ make: "IMT", model: "2.5/18" },
{ make: "IMT", model: "10/65" },
{ make: "IMT", model: "11/76" },
{ make: "IMT", model: "12/86" },
{ make: "IMT", model: "14/98" },
{ make: "IMT", model: "15/105" },
{ make: "IMT", model: "16/117" },
{ make: "IMT", model: "32/222" },
{ make: "IMT", model: "40/275" },
{ make: "IMT", model: "50/345" },
{ make: "IMT", model: "425" },
{ make: "IMT", model: "810" },
{ make: "IMT", model: "1030" },
{ make: "IMT", model: "1123" },
{ make: "IMT", model: "1610" },
{ make: "IMT", model: "1730" },
{ make: "IMT", model: "2020" },
{ make: "IMT", model: "2530" },
{ make: "IMT", model: "2820" },
{ make: "IMT", model: "3203" },
{ make: "IMT", model: "3820" },
{ make: "IMT", model: "4004" },
{ make: "IMT", model: "4300" },
{ make: "IMT", model: "5200" },
{ make: "IMT", model: "6025" },
{ make: "IMT", model: "7500" },
{ make: "IMT", model: "9600" },
{ make: "IMT", model: "9500" },
{ make: "IMT", model: "10000" },
{ make: "IMT", model: "12000" },
{ make: "IMT", model: "16000" },
{ make: "IMT", model: "20017" },
{ make: "IMT", model: "24562" },
{ make: "IMT", model: "28562" },
{ make: "IMT", model: "42684" },
{ make: "IMT", model: "DOMINATOR II" },
{ make: "IMT", model: "EZ300" },
{ make: "IMT", model: "OTHER" },
//
//JEKKO
//
{ make: "JEKKO", model: "JF235" },
{ make: "JEKKO", model: "JF545" },
{ make: "JEKKO", model: "JF990" },
{ make: "JEKKO", model: "JVM800" },
{ make: "JEKKO", model: "MPK06" },
{ make: "JEKKO", model: "MPK06.2" },
{ make: "JEKKO", model: "MPK10" },
{ make: "JEKKO", model: "MPK20" },
{ make: "JEKKO", model: "MPK50" },
{ make: "JEKKO", model: "SPB209" },
{ make: "JEKKO", model: "SPD360" },
{ make: "JEKKO", model: "SPK60" },
{ make: "JEKKO", model: "SPX309" },
{ make: "JEKKO", model: "SPX312" },
{ make: "JEKKO", model: "SPX328" },
{ make: "JEKKO", model: "SPX424" },
{ make: "JEKKO", model: "SPX509" },
{ make: "JEKKO", model: "SPX527" },
{ make: "JEKKO", model: "SPX532" },
{ make: "JEKKO", model: "SPX536" },
{ make: "JEKKO", model: "SPX650" },
{ make: "JEKKO", model: "SPX1040" },
{ make: "JEKKO", model: "SPX1275" },
{ make: "JEKKO", model: "SPX1280" },
{ make: "JEKKO", model: "OTHER" },
//
//KATO
//
{ make: "KATO", model: "CCH1000" },
{ make: "KATO", model: "CR350" },
{ make: "KATO", model: "KR10" },
{ make: "KATO", model: "KR25" },
{ make: "KATO", model: "KR35" },
{ make: "KATO", model: "KR45" },
{ make: "KATO", model: "KR50" },
{ make: "KATO", model: "KR65" },
{ make: "KATO", model: "KR70" },
{ make: "KATO", model: "MR100" },
{ make: "KATO", model: "MR220" },
{ make: "KATO", model: "NK200" },
{ make: "KATO", model: "NK250" },
{ make: "KATO", model: "NK500" },
{ make: "KATO", model: "NK550" },
{ make: "KATO", model: "NK800" },
{ make: "KATO", model: "NK1200" },
{ make: "KATO", model: "NK1600" },
{ make: "KATO", model: "SS500SPV-1" },
{ make: "KATO", model: "SR250" },
{ make: "KATO", model: "SS250" },
{ make: "KATO", model: "SS500" },
{ make: "KATO", model: "OTHER" },
//
//KOBELCO
//  
{ make: "KOBELCO", model: "7035" },
{ make: "KOBELCO", model: "7055" },
{ make: "KOBELCO", model: "7065" },
{ make: "KOBELCO", model: "7080" },
{ make: "KOBELCO", model: "7100" },
{ make: "KOBELCO", model: "7120" },
{ make: "KOBELCO", model: "7150" },
{ make: "KOBELCO", model: "7200" },
{ make: "KOBELCO", model: "7250" },
{ make: "KOBELCO", model: "7300" },
{ make: "KOBELCO", model: "7450" },
{ make: "KOBELCO", model: "7800" },
{ make: "KOBELCO", model: "9170" },
{ make: "KOBELCO", model: "BM500" },
{ make: "KOBELCO", model: "BM600" },
{ make: "KOBELCO", model: "BM700" },
{ make: "KOBELCO", model: "BM900" },
{ make: "KOBELCO", model: "BM1000" },
{ make: "KOBELCO", model: "BM1200" },
{ make: "KOBELCO", model: "BMS1000" },
{ make: "KOBELCO", model: "CK800" },
{ make: "KOBELCO", model: "CK850" },
{ make: "KOBELCO", model: "CK1000" },
{ make: "KOBELCO", model: "CK1100" },
{ make: "KOBELCO", model: "CK1200" },
{ make: "KOBELCO", model: "CK1600" },
{ make: "KOBELCO", model: "CK2000" },
{ make: "KOBELCO", model: "CK2500" },
{ make: "KOBELCO", model: "CK2750" },
{ make: "KOBELCO", model: "CK3300" },
{ make: "KOBELCO", model: "CKE800" },
{ make: "KOBELCO", model: "CKE900" },
{ make: "KOBELCO", model: "CKE1800" },
{ make: "KOBELCO", model: "CKE2500" },
{ make: "KOBELCO", model: "CKE3000" },
{ make: "KOBELCO", model: "CKE4000" },
{ make: "KOBELCO", model: "CKS800" },
{ make: "KOBELCO", model: "CKS1350" },
{ make: "KOBELCO", model: "CKS2500" },
{ make: "KOBELCO", model: "MK500" },
{ make: "KOBELCO", model: "RK70" },
{ make: "KOBELCO", model: "RK120" },
{ make: "KOBELCO", model: "RK250" },
{ make: "KOBELCO", model: "RK450" },
{ make: "KOBELCO", model: "RK500" },
{ make: "KOBELCO", model: "SL4500" },
{ make: "KOBELCO", model: "SL6000" },
{ make: "KOBELCO", model: "TK750" },
{ make: "KOBELCO", model: "OTHER" },
//
//MANITOWOC
//  
{ make: "MANITOWOC", model: "40" },
{ make: "MANITOWOC", model: "60" },
{ make: "MANITOWOC", model: "222" },
{ make: "MANITOWOC", model: "555" },
{ make: "MANITOWOC", model: "777" },
{ make: "MANITOWOC", model: "888" },
{ make: "MANITOWOC", model: "999" },
{ make: "MANITOWOC", model: "2250" },
{ make: "MANITOWOC", model: "2900" },
{ make: "MANITOWOC", model: "3339" },
{ make: "MANITOWOC", model: "3600" },
{ make: "MANITOWOC", model: "3900" },
{ make: "MANITOWOC", model: "4000" },
{ make: "MANITOWOC", model: "4100" },
{ make: "MANITOWOC", model: "4500" },
{ make: "MANITOWOC", model: "4600" },
{ make: "MANITOWOC", model: "8000" },
{ make: "MANITOWOC", model: "8500" },
{ make: "MANITOWOC", model: "10000" },
{ make: "MANITOWOC", model: "11000" },
{ make: "MANITOWOC", model: "12000" },
{ make: "MANITOWOC", model: "14000" },
{ make: "MANITOWOC", model: "15000" },
{ make: "MANITOWOC", model: "16000" },
{ make: "MANITOWOC", model: "18000" },
{ make: "MANITOWOC", model: "21000" },
{ make: "MANITOWOC", model: "GMK5095" },
{ make: "MANITOWOC", model: "M250" },
{ make: "MANITOWOC", model: "MLC80" },
{ make: "MANITOWOC", model: "MLC100" },
{ make: "MANITOWOC", model: "MLC150" },
{ make: "MANITOWOC", model: "MLC165" },
{ make: "MANITOWOC", model: "MLC200" },
{ make: "MANITOWOC", model: "MLC250" },
{ make: "MANITOWOC", model: "MLC300" },
{ make: "MANITOWOC", model: "MLC650" },
{ make: "MANITOWOC", model: "SHUTTLEFT SCD09" },
{ make: "MANITOWOC", model: "OTHER" },
//
//NORTHWEST
//  
{ make: "NORTHWEST", model: "6" },
{ make: "NORTHWEST", model: "25" },
{ make: "NORTHWEST", model: "28" },
{ make: "NORTHWEST", model: "41" },
{ make: "NORTHWEST", model: "50" },
{ make: "NORTHWEST", model: "80" },
{ make: "NORTHWEST", model: "95" },
{ make: "NORTHWEST", model: "180" },
{ make: "NORTHWEST", model: "190" },
{ make: "NORTHWEST", model: "1200" },
{ make: "NORTHWEST", model: "5065" },
{ make: "NORTHWEST", model: "7060" },
{ make: "NORTHWEST", model: "9570" },
{ make: "NORTHWEST", model: "OTHER" },  
//
//PALFINGER
//
{ make: "PALFINGER", model: "ETC35" },
{ make: "PALFINGER", model: "ETC37" },
{ make: "PALFINGER", model: "ETC40" },
{ make: "PALFINGER", model: "ETT29" },
{ make: "PALFINGER", model: "M100" },
{ make: "PALFINGER", model: "P250" },
{ make: "PALFINGER", model: "P280" },
{ make: "PALFINGER", model: "P300" },
{ make: "PALFINGER", model: "PBO5548" },
{ make: "PALFINGER", model: "PK5.001" },
{ make: "PALFINGER", model: "PK7.001" },
{ make: "PALFINGER", model: "PK8.501" },
{ make: "PALFINGER", model: "PK9.501" },
{ make: "PALFINGER", model: "PK12.501" },
{ make: "PALFINGER", model: "PK20.501" },
{ make: "PALFINGER", model: "PK307" },
{ make: "PALFINGER", model: "PK2700" },
{ make: "PALFINGER", model: "PK2900" },
{ make: "PALFINGER", model: "PK4200" },
{ make: "PALFINGER", model: "PK4501" },
{ make: "PALFINGER", model: "PK6001" },
{ make: "PALFINGER", model: "PK7501" },
{ make: "PALFINGER", model: "PK8080" },
{ make: "PALFINGER", model: "PK9001" },
{ make: "PALFINGER", model: "PK9501" },
{ make: "PALFINGER", model: "PK9700" },
{ make: "PALFINGER", model: "PK10000" },
{ make: "PALFINGER", model: "PK11000" },
{ make: "PALFINGER", model: "PK11001" },
{ make: "PALFINGER", model: "PK12000" },
{ make: "PALFINGER", model: "PK12002" },
{ make: "PALFINGER", model: "PK13000" },
{ make: "PALFINGER", model: "PK13001" },
{ make: "PALFINGER", model: "PK14002" },
{ make: "PALFINGER", model: "PK15002" },
{ make: "PALFINGER", model: "PK15500" },
{ make: "PALFINGER", model: "PK17502" },
{ make: "PALFINGER", model: "PK18002" },
{ make: "PALFINGER", model: "PK18500" },
{ make: "PALFINGER", model: "PK20002" },
{ make: "PALFINGER", model: "PK21502" },
{ make: "PALFINGER", model: "PK22002" },
{ make: "PALFINGER", model: "PK23002" },
{ make: "PALFINGER", model: "PK23080" },
{ make: "PALFINGER", model: "PK23500" },
{ make: "PALFINGER", model: "PK24001" },
{ make: "PALFINGER", model: "PK26002" },
{ make: "PALFINGER", model: "PK27002" },
{ make: "PALFINGER", model: "PK29002" },
{ make: "PALFINGER", model: "PK30002" },
{ make: "PALFINGER", model: "PK32080" },
{ make: "PALFINGER", model: "PK33002" },
{ make: "PALFINGER", model: "PK34002" },
{ make: "PALFINGER", model: "PK36002" },
{ make: "PALFINGER", model: "PK40002" },
{ make: "PALFINGER", model: "PK41002" },
{ make: "PALFINGER", model: "PK42002" },
{ make: "PALFINGER", model: "PK42502" },
{ make: "PALFINGER", model: "PK50002" },
{ make: "PALFINGER", model: "PK53002" },
{ make: "PALFINGER", model: "PK54000" },
{ make: "PALFINGER", model: "PK60002" },
{ make: "PALFINGER", model: "PK74002" },
{ make: "PALFINGER", model: "PK85002" },
{ make: "PALFINGER", model: "PK100002" },
{ make: "PALFINGER", model: "PK200002" },
{ make: "PALFINGER", model: "PKG12001" },
{ make: "PALFINGER", model: "PRL260" },
{ make: "PALFINGER", model: "PSC3216" },
{ make: "PALFINGER", model: "PSC4329" },
{ make: "PALFINGER", model: "PSC5025" },
{ make: "PALFINGER", model: "PSC6025" },
{ make: "PALFINGER", model: "PSC6229" },
{ make: "PALFINGER", model: "PSC8029" },
{ make: "PALFINGER", model: "PSC10829" },
{ make: "PALFINGER", model: "PW325" },
{ make: "PALFINGER", model: "PW360" },
{ make: "PALFINGER", model: "PW400" },
{ make: "PALFINGER", model: "PW35001" },
{ make: "PALFINGER", model: "PW32001" },
{ make: "PALFINGER", model: "PW38001" },
{ make: "PALFINGER", model: "PW42001" },
{ make: "PALFINGER", model: "OTHER" },
//
//PM
//
{ make: "PM", model: "2" },
{ make: "PM", model: "3" },
{ make: "PM", model: "6" },
{ make: "PM", model: "8" },
{ make: "PM", model: "9.5" },
{ make: "PM", model: "10" },
{ make: "PM", model: "11" },
{ make: "PM", model: "11.5" },
{ make: "PM", model: "12" },
{ make: "PM", model: "14" },
{ make: "PM", model: "15.5" },
{ make: "PM", model: "16" },
{ make: "PM", model: "16.5" },
{ make: "PM", model: "18" },
{ make: "PM", model: "20" },
{ make: "PM", model: "21" },
{ make: "PM", model: "21.5" },
{ make: "PM", model: "23.5" },
{ make: "PM", model: "26.5" },
{ make: "PM", model: "27.5" },
{ make: "PM", model: "28.5" },
{ make: "PM", model: "32" },
{ make: "PM", model: "34" },
{ make: "PM", model: "38.5" },
{ make: "PM", model: "40" },
{ make: "PM", model: "41" },
{ make: "PM", model: "43" },
{ make: "PM", model: "45" },
{ make: "PM", model: "47.5" },
{ make: "PM", model: "48" },
{ make: "PM", model: "50" },
{ make: "PM", model: "63" },
{ make: "PM", model: "65" },
{ make: "PM", model: "100" },
{ make: "PM", model: "150" },
{ make: "PM", model: "210" },
{ make: "PM", model: "450" },
{ make: "PM", model: "PL74" },
{ make: "PM", model: "WB60" },
{ make: "PM", model: "OTHER" },
//
//POTAIN
//
{ make: "POTAIN", model: "325" },
{ make: "POTAIN", model: "EVY" },
{ make: "POTAIN", model: "GTMR" },
{ make: "POTAIN", model: "HD40" },
{ make: "POTAIN", model: "HDT80" },
{ make: "POTAIN", model: "HUP" },
{ make: "POTAIN", model: "IGO15" },
{ make: "POTAIN", model: "IGO32" },
{ make: "POTAIN", model: "IGO50" },
{ make: "POTAIN", model: "IGO MA21" },
{ make: "POTAIN", model: "IGO T85" },
{ make: "POTAIN", model: "IGO T99" },
{ make: "POTAIN", model: "IGO T130" },
{ make: "POTAIN", model: "MC85" },
{ make: "POTAIN", model: "MC230" },
{ make: "POTAIN", model: "MC310" },
{ make: "POTAIN", model: "MC475" },
{ make: "POTAIN", model: "MCR225" },
{ make: "POTAIN", model: "MCT88" },
{ make: "POTAIN", model: "MCT188" },
{ make: "POTAIN", model: "MCT200" },
{ make: "POTAIN", model: "MCT385" },
{ make: "POTAIN", model: "MD175" },
{ make: "POTAIN", model: "MD208" },
{ make: "POTAIN", model: "MD265" },
{ make: "POTAIN", model: "MD345" },
{ make: "POTAIN", model: "MD485" },
{ make: "POTAIN", model: "MD509" },
{ make: "POTAIN", model: "MD560" },
{ make: "POTAIN", model: "MD569" },
{ make: "POTAIN", model: "MD689" },
{ make: "POTAIN", model: "MDT98" },
{ make: "POTAIN", model: "MDT109" },
{ make: "POTAIN", model: "MDT178" },
{ make: "POTAIN", model: "MDT219" },
{ make: "POTAIN", model: "MDT302" },
{ make: "POTAIN", model: "MDT319" },
{ make: "POTAIN", model: "MDT389" },
{ make: "POTAIN", model: "MR90" },
{ make: "POTAIN", model: "MR418" },
{ make: "POTAIN", model: "MR608" },
{ make: "POTAIN", model: "MR615" },
{ make: "POTAIN", model: "OTHER" },
//
//SANY
//
{ make: "SANY", model: "QY25" },
{ make: "SANY", model: "QY50" },
{ make: "SANY", model: "QY100" },
{ make: "SANY", model: "SAC600" },
{ make: "SANY", model: "SAC1300" },
{ make: "SANY", model: "SAC1600" },
{ make: "SANY", model: "SAC2200" },
{ make: "SANY", model: "SAC2600" },
{ make: "SANY", model: "SAC3000" },
{ make: "SANY", model: "SAC3500" },
{ make: "SANY", model: "SAC4500" },
{ make: "SANY", model: "SAC5000" },
{ make: "SANY", model: "SAC6000" },
{ make: "SANY", model: "SAC7000" },
{ make: "SANY", model: "SAC8000" },
{ make: "SANY", model: "SCA9000" },
{ make: "SANY", model: "SCA1000" },
{ make: "SANY", model: "SCA1100" },
{ make: "SANY", model: "SCA1350" },
{ make: "SANY", model: "SCA1600" },
{ make: "SANY", model: "SCA2600" },
{ make: "SANY", model: "SCA4000" },
{ make: "SANY", model: "SCC500" },
{ make: "SANY", model: "SCC550" },
{ make: "SANY", model: "SCC600" },
{ make: "SANY", model: "SCC750" },
{ make: "SANY", model: "SCC800" },
{ make: "SANY", model: "SCC850" },
{ make: "SANY", model: "SCC900" },
{ make: "SANY", model: "SCC1000" },
{ make: "SANY", model: "SCC1350" },
{ make: "SANY", model: "SCC1500" },
{ make: "SANY", model: "SCC2000" },
{ make: "SANY", model: "SCC2500" },
{ make: "SANY", model: "SCC3500" },
{ make: "SANY", model: "SCC6500" },
{ make: "SANY", model: "SCC8000" },
{ make: "SANY", model: "SCC8100" },
{ make: "SANY", model: "SCC8300" },
{ make: "SANY", model: "SCC19000" },
{ make: "SANY", model: "SCD150" },
{ make: "SANY", model: "SCE600" },
{ make: "SANY", model: "SCE800" },
{ make: "SANY", model: "SCE1000" },
{ make: "SANY", model: "SCE1500" },
{ make: "SANY", model: "SCE2600" },
{ make: "SANY", model: "SRA350" },
{ make: "SANY", model: "SRA550" },
{ make: "SANY", model: "SRA750" },
{ make: "SANY", model: "SRA1000" },
{ make: "SANY", model: "SRA1200" },
{ make: "SANY", model: "SRC650" },
{ make: "SANY", model: "SRC840" },
{ make: "SANY", model: "SRC865" },
{ make: "SANY", model: "SRC885" },
{ make: "SANY", model: "SRE600" },
{ make: "SANY", model: "STB500" },
{ make: "SANY", model: "STC120" },
{ make: "SANY", model: "STC250" },
{ make: "SANY", model: "STC300" },
{ make: "SANY", model: "STC500" },
{ make: "SANY", model: "STC550" },
{ make: "SANY", model: "STC600" },
{ make: "SANY", model: "STC700" },
{ make: "SANY", model: "STC750" },
{ make: "SANY", model: "STC800" },
{ make: "SANY", model: "STC1000" },
{ make: "SANY", model: "STC1250" },
{ make: "SANY", model: "STC1300" },
{ make: "SANY", model: "STC1600" },
{ make: "SANY", model: "SYM5405" },
{ make: "SANY", model: "OTHER" },
//
//STELLAR
//
{ make: "STELLAR", model: "4500" },
{ make: "STELLAR", model: "5520" },
{ make: "STELLAR", model: "5521" },
{ make: "STELLAR", model: "6000" },
{ make: "STELLAR", model: "7621" },
{ make: "STELLAR", model: "7630" },
{ make: "STELLAR", model: "8621" },
{ make: "STELLAR", model: "8630" },
{ make: "STELLAR", model: "12621" },
{ make: "STELLAR", model: "12630" },
{ make: "STELLAR", model: "EC3200" },
{ make: "STELLAR", model: "EC4000" },
{ make: "STELLAR", model: "TMAX1-11" },
{ make: "STELLAR", model: "TMAX2-11" },
{ make: "STELLAR", model: "TMAX2-14" },
{ make: "STELLAR", model: "10621" },
{ make: "STELLAR", model: "3200" },
{ make: "STELLAR", model: "OTHER" },  
  
];

  export default cranesTaxonomy;
