const craneDnaKeywords = [
  /* -------------------- */
  /* CRANE TYPE DNA */
  /* -------------------- */

  "CRAWLER CRANE",
  "ROUGH TERRAIN CRANE",
  "ALL TERRAIN CRANE",
  "TRUCK CRANE",
  "BOOM TRUCK",
  "CARRY DECK CRANE",
  "PICK AND CARRY CRANE",
  "TELESCOPIC CRANE",
  "LATTICE BOOM CRANE",
  "HYDRAULIC CRANE",
  "FRICTION CRANE",
  "TOWER CRANE",
  "SELF ERECTING TOWER CRANE",
  "MOBILE TOWER CRANE",
  "GANTRY CRANE",
  "KNUCKLE BOOM CRANE",
  "LOADER CRANE",
  "ARTICULATING CRANE",
  "SERVICE CRANE",
  "MECHANIC TRUCK CRANE",
  "MINI CRANE",
  "SPIDER CRANE",
  "PICKER TRUCK",
  "MATERIAL HANDLER CRANE",
  "DIGGER DERRICK",
  "BUCKET TRUCK",

  /* -------------------- */
  /* CHASSIS SYSTEM DNA */
  /* -------------------- */

  "CRAWLER CHASSIS",
  "ROUGH TERRAIN CHASSIS",
  "ALL TERRAIN CHASSIS",
  "TRUCK MOUNT CHASSIS",
  "COMMERCIAL TRUCK CHASSIS",
  "CARRIER CHASSIS",
  "CARRY DECK CHASSIS",
  "PICK AND CARRY CHASSIS",
  "SPIDER CRANE CHASSIS",
  "TOWER CRANE BASE",
  "GANTRY FRAME",
  "SERVICE BODY CHASSIS",
  "LOW PROFILE CHASSIS",
  "COMPACT CHASSIS",
  "EXTENDABLE CHASSIS",
  "HYDRAULIC EXPANDING CHASSIS",
  "CARBODY",
  "CRANE UPPER",
  "CRANE LOWER",
  "UPPER STRUCTURE",
  "LOWER CARRIER",

  /* -------------------- */
  /* CARRIER SYSTEM DNA */
  /* -------------------- */

  "SINGLE ENGINE CARRIER",
  "DUAL ENGINE CARRIER",
  "HYDRAULIC CARRIER",
  "MECHANICAL CARRIER",
  "ROADABLE CARRIER",
  "OFF ROAD CARRIER",
  "SELF PROPELLED CARRIER",
  "TRUCK CARRIER",
  "CUSTOM CRANE CARRIER",
  "COMMERCIAL CARRIER",
  "CARRIER CAB",
  "LOWER CAB",
  "CARRIER TRANSMISSION",
  "CARRIER SUSPENSION",
  "CARRIER OUTRIGGERS",
  "CARRIER COUNTERWEIGHT",
  "CARRIER AXLES",

  /* -------------------- */
  /* BOOM SYSTEM DNA */
  /* -------------------- */

  "TELESCOPIC BOOM",
  "LATTICE BOOM",
  "HYDRAULIC BOOM",
  "FULL POWER BOOM",
  "PINNED BOOM",
  "MECHANICAL BOOM",
  "MAIN BOOM",
  "BASE BOOM",
  "INNER BOOM",
  "MID BOOM",
  "OUTER BOOM",
  "BOOM SECTIONS",
  "LATTICE INSERTS",
  "BOOM INSERTS",
  "LONG BOOM",
  "HIGH REACH BOOM",
  "HEAVY LIFT BOOM",
  "LIFTING BOOM",
  "AUXILIARY BOOM",
  "BOOM EXTENSION",
  "HYDRAULIC BOOM EXTENSION",
  "MANUAL BOOM EXTENSION",
  "POWER PIN BOOM",
  "MEGAFORM BOOM",
  "TWIN LOCK BOOM",
  "TELEMATIK BOOM",
  "BOOM DOLLY",
  "BOOM REST",
  "BOOM ANGLE INDICATOR",
  "BOOM HOIST",
  "BOOM HOIST CYLINDERS",
  "BOOM HOIST WINCH",
  "BOOM PENDANTS",
  "BOOM BACKSTOPS",
  "BOOM NOSE",
  "AUXILIARY BOOM NOSE",
  "ROOSTER SHEAVE",

  /* -------------------- */
  /* JIB SYSTEM DNA */
  /* -------------------- */

  "JIB",
  "FLY JIB",
  "LATTICE JIB",
  "LUFFING JIB",
  "SWINGAWAY JIB",
  "HYDRAULIC JIB",
  "PINNED JIB",
  "FIXED JIB",
  "OFFSETTABLE JIB",
  "BI-FOLD JIB",
  "TELESCOPIC JIB",
  "FOLDING JIB",
  "POWER TILT JIB",
  "MANUAL OFFSET JIB",
  "HYDRAULIC OFFSET JIB",
  "AUXILIARY JIB",
  "HEAVY LIFT JIB",
  "LONG JIB",
  "JIB INSERTS",
  "JIB EXTENSION",
  "JIB STOWAGE",
  "NO JIB",

  /* -------------------- */
  /* LUFFING / FLY SYSTEM DNA */
  /* -------------------- */

  "LUFFING SYSTEM",
  "LUFFING FLY JIB",
  "LUFFING BOOM",
  "LUFFING MAST",
  "LUFFING WINCH",
  "LUFFING CYLINDER",
  "LUFFING PENDANTS",
  "FIXED FLY",
  "LATTICE FLY",
  "HYDRAULIC FLY",
  "POWER LUFFING JIB",
  "VARIABLE LUFFING JIB",
  "HEAVY LIFT LUFFING JIB",

  /* -------------------- */
  /* KNUCKLE / LOADER CRANE DNA */
  /* -------------------- */

  "KNUCKLE BOOM",
  "ARTICULATING BOOM",
  "LOADER CRANE",
  "FOLDING BOOM CRANE",
  "KNUCKLE JIB",
  "HYDRAULIC EXTENSIONS",
  "MANUAL EXTENSIONS",
  "OUTER BOOM EXTENSIONS",
  "INNER BOOM EXTENSIONS",
  "FLY JIB EXTENSION",
  "HYDRAULIC ROTATOR",
  "MANUAL ROTATOR",
  "GRAPPLE READY",
  "WINCH READY",
  "REMOTE CONTROL LOADER CRANE",
  "TOP SEAT CONTROLS",
  "SIDE MOUNT CONTROLS",
  "GROUND CONTROLS",
  "HIGH STAND CONTROLS",
  "A FRAME OUTRIGGERS",
  "H FRAME OUTRIGGERS",

  /* -------------------- */
  /* COUNTERWEIGHT DNA */
  /* -------------------- */

  "COUNTERWEIGHT",
  "COUNTERWEIGHT PACKAGE",
  "CARBODY COUNTERWEIGHT",
  "UPPER COUNTERWEIGHT",
  "LOWER COUNTERWEIGHT",
  "STACKABLE COUNTERWEIGHT",
  "REMOVABLE COUNTERWEIGHT",
  "HYDRAULIC COUNTERWEIGHT REMOVAL",
  "SELF INSTALLING COUNTERWEIGHT",
  "SELF REMOVING COUNTERWEIGHT",
  "VARIABLE COUNTERWEIGHT",
  "VPC COUNTERWEIGHT",
  "TRAY COUNTERWEIGHT",
  "COUNTERWEIGHT TRAY",
  "COUNTERWEIGHT SLABS",
  "COUNTERWEIGHT WAGON",
  "SUPERLIFT COUNTERWEIGHT",
  "CENTRAL BALLAST",
  "ADDITIONAL BALLAST",

  /* -------------------- */
  /* SUPERLIFT DNA */
  /* -------------------- */

  "SUPERLIFT",
  "SUPERLIFT PACKAGE",
  "SUPERLIFT MAST",
  "SUPERLIFT COUNTERWEIGHT",
  "SUPERLIFT TRAY",
  "SUPERLIFT DERRICK",
  "Y GUY SYSTEM",
  "GUYING SYSTEM",
  "BOOM GUYING",
  "DERRICK MAST",
  "HEAVY LIFT ATTACHMENT",
  "LIFT ENHANCER PACKAGE",
  "VPC MAX",
  "MAX-ER ATTACHMENT",

  /* -------------------- */
  /* OUTRIGGER DNA */
  /* -------------------- */

  "OUTRIGGERS",
  "FULL OUTRIGGERS",
  "VARIABLE OUTRIGGERS",
  "HYDRAULIC OUTRIGGERS",
  "MANUAL OUTRIGGERS",
  "A FRAME OUTRIGGERS",
  "H TYPE OUTRIGGERS",
  "X TYPE OUTRIGGERS",
  "VERTICAL OUTRIGGERS",
  "HORIZONTAL OUTRIGGERS",
  "FRONT OUTRIGGERS",
  "REAR OUTRIGGERS",
  "MID OUTRIGGERS",
  "OUT AND DOWN OUTRIGGERS",
  "OUTRIGGER BEAMS",
  "OUTRIGGER JACKS",
  "OUTRIGGER FLOATS",
  "OUTRIGGER PADS",
  "OUTRIGGER MATS",
  "OUTRIGGER MONITORING",
  "OUTRIGGER POSITION SENSING",
  "AUTO LEVELING OUTRIGGERS",
  "SELF LEVELING OUTRIGGERS",
  "ASYMMETRICAL OUTRIGGERS",
  "FIFTH OUTRIGGER",
  "FRONT STABILIZER",
  "REAR STABILIZER",

  /* -------------------- */
  /* TRACK / TIRE DNA */
  /* -------------------- */

  "CRAWLER",
  "TRACK DRIVE",
  "CRAWLER TRACKS",
  "EXTENDABLE CRAWLER TRACKS",
  "HYDRAULIC EXTENDABLE TRACKS",
  "RETRACTABLE TRACKS",
  "WIDE TRACKS",
  "NARROW TRACKS",
  "TRACK PADS",
  "FLAT TRACK PADS",
  "SELF ASSEMBLING CRAWLERS",
  "REMOVABLE CRAWLERS",
  "CRAWLER SIDE FRAMES",
  "CARBODY JACKS",
  "RUBBER TRACKS",
  "STEEL TRACKS",
  "PNEUMATIC TIRES",
  "ROUGH TERRAIN TIRES",
  "HIGH FLOATATION TIRES",
  "ALL TERRAIN TIRES",
  "SUPER SINGLE TIRES",
  "DUAL TIRES",
  "FOAM FILLED TIRES",
  "SOLID TIRES",
  "TIRE PRESSURE MONITORING",

  /* -------------------- */
  /* STEERING DNA */
  /* -------------------- */

  "ALL WHEEL STEER",
  "4 WHEEL STEER",
  "2 WHEEL STEER",
  "FRONT WHEEL STEER",
  "REAR WHEEL STEER",
  "CRAB STEER",
  "COORDINATED STEER",
  "INDEPENDENT REAR STEER",
  "MULTI AXLE STEERING",
  "ELECTRONIC STEERING",
  "HYDRAULIC STEERING",
  "ROAD STEER MODE",
  "OFF ROAD STEER MODE",
  "STEERING AXLES",
  "COUNTER STEER",
  "PICK AND CARRY STEERING",

  /* -------------------- */
  /* SUSPENSION DNA */
  /* -------------------- */

  "HYDRAULIC SUSPENSION",
  "HYDROPNEUMATIC SUSPENSION",
  "PNEUMATIC SUSPENSION",
  "AIR SUSPENSION",
  "LEAF SPRING SUSPENSION",
  "OSCILLATING AXLE",
  "ACTIVE SUSPENSION",
  "SUSPENSION LOCKOUT",
  "AXLE LOCKOUT",
  "LOAD EQUALIZING SUSPENSION",
  "INDEPENDENT SUSPENSION",
  "CARRIER SUSPENSION",
  "ROUGH TERRAIN SUSPENSION",

  /* -------------------- */
  /* HOIST / WINCH DNA */
  /* -------------------- */

  "MAIN WINCH",
  "AUXILIARY WINCH",
  "THIRD DRUM",
  "FOURTH DRUM",
  "HOIST WINCH",
  "BOOM HOIST WINCH",
  "LUFFING WINCH",
  "TAGLINE WINCH",
  "SERVICE WINCH",
  "WINCH PACKAGE",
  "SINGLE WINCH",
  "DUAL WINCH",
  "FREE FALL",
  "CONTROLLED FREE FALL",
  "HYDRAULIC WINCH",
  "MECHANICAL WINCH",
  "FRICTION WINCH",
  "ELECTRIC WINCH",
  "HIGH SPEED WINCH",
  "PLANETARY WINCH",
  "WINCH BRAKE",
  "HOIST BRAKE",
  "WIRE ROPE",
  "HOIST ROPE",
  "ANTI TWO BLOCK",

  /* -------------------- */
  /* HYDRAULIC SYSTEM DNA */
  /* -------------------- */

  "HYDRAULIC CRANE",
  "LOAD SENSING HYDRAULICS",
  "OPEN CENTER HYDRAULICS",
  "CLOSED CENTER HYDRAULICS",
  "PRESSURE COMPENSATED HYDRAULICS",
  "PROPORTIONAL HYDRAULICS",
  "ELECTROHYDRAULIC CONTROLS",
  "HYDRAULIC BOOM",
  "HYDRAULIC JIB",
  "HYDRAULIC OUTRIGGERS",
  "HYDRAULIC COUNTERWEIGHT",
  "HYDRAULIC SWING",
  "HYDRAULIC WINCH",
  "HYDRAULIC BOOM EXTENSION",
  "AUXILIARY HYDRAULICS",
  "HIGH FLOW HYDRAULICS",
  "HYDRAULIC COOLER",
  "HYDRAULIC OIL HEATER",
  "PUMP DRIVE",
  "PISTON PUMP",
  "GEAR PUMP",
  "VARIABLE DISPLACEMENT PUMP",

  /* -------------------- */
  /* LIFT CONTROL DNA */
  /* -------------------- */

  "LOAD MOMENT INDICATOR",
  "LMI",
  "RATED CAPACITY LIMITER",
  "RCL",
  "LOAD CHART SYSTEM",
  "LOAD INDICATOR",
  "BOOM ANGLE SENSOR",
  "BOOM LENGTH SENSOR",
  "LOAD SENSOR",
  "OUTRIGGER POSITION SENSOR",
  "COUNTERWEIGHT SENSOR",
  "ANTI TWO BLOCK",
  "A2B",
  "TWO BLOCK WARNING",
  "OVERLOAD PROTECTION",
  "WORKING RANGE LIMITER",
  "ENVELOPE CONTROL",
  "ZONE LIMITING",
  "SLEW LIMITING",
  "HEIGHT LIMITING",
  "TELESCOPING MODE SELECT",
  "CRANE CONTROL SYSTEM",

  /* -------------------- */
  /* SWING SYSTEM DNA */
  /* -------------------- */

  "SWING SYSTEM",
  "360 DEGREE ROTATION",
  "CONTINUOUS ROTATION",
  "NON CONTINUOUS ROTATION",
  "FULL ROTATION",
  "LIMITED ROTATION",
  "SWING DRIVE",
  "SWING MOTOR",
  "SWING BEARING",
  "SWING BRAKE",
  "SWING LOCK",
  "SWING AWAY",
  "FREE SWING",
  "POWER SWING",
  "HYDRAULIC SWING",
  "ELECTRIC SWING",
  "SLEW DRIVE",
  "SLEW RING",

  /* -------------------- */
  /* CAB / OPERATOR DNA */
  /* -------------------- */

  "UPPER CAB",
  "LOWER CAB",
  "DUAL CAB",
  "TILT CAB",
  "HYDRAULIC TILT CAB",
  "ELEVATING CAB",
  "SLIDING CAB",
  "CARRIER CAB",
  "CRANE CAB",
  "OPERATOR CAB",
  "OPEN OPERATOR STATION",
  "ENCLOSED CAB",
  "ROPS CAB",
  "FOPS CAB",
  "C/H/A",
  "AIR CONDITIONED CAB",
  "HEATED CAB",
  "PRESSURIZED CAB",
  "SUSPENSION SEAT",
  "AIR RIDE SEAT",
  "CAB RISER",
  "CAB CATWALK",
  "SKY CONTROL CAB",
  "REMOTE OPERATOR STATION",
  "JOYSTICK CONTROLS",
  "HYDRAULIC CONTROLS",
  "ELECTRONIC CONTROLS",

  /* -------------------- */
  /* BOOM EXTENSION DNA */
  /* -------------------- */

  "HYDRAULIC BOOM EXTENSION",
  "PINNED BOOM EXTENSION",
  "MANUAL BOOM EXTENSION",
  "BOOM EXTENSION",
  "TELESCOPIC EXTENSION",
  "LATTICE EXTENSION",
  "INSERT SECTION",
  "BOOM INSERT",
  "JIB EXTENSION",
  "FOLDING EXTENSION",
  "POWER EXTENSION",
  "OFFSET EXTENSION",
  "FIXED EXTENSION",

  /* -------------------- */
  /* RIGGING DNA */
  /* -------------------- */

  "HOOK BLOCK",
  "HEADACHE BALL",
  "OVERHAUL BALL",
  "SWIVEL HOOK",
  "MULTI SHEAVE BLOCK",
  "SINGLE SHEAVE BLOCK",
  "LOAD BLOCK",
  "AUXILIARY BALL",
  "MAIN HOOK",
  "AUXILIARY HOOK",
  "WEDGE SOCKET",
  "WIRE ROPE",
  "SLINGS",
  "SPREADER BAR",
  "LIFTING BEAM",
  "BOOM PENDANTS",
  "JIB PENDANTS",
  "GUY LINES",
  "REEVING",
  "MULTI PART LINE",
  "SINGLE PART LINE",

  /* -------------------- */
  /* AUTOMATION / LOAD DNA */
  /* -------------------- */

  "TELEMATICS",
  "REMOTE CONTROL",
  "WIRELESS REMOTE",
  "RADIO REMOTE",
  "LOAD MONITORING",
  "LIFT PLANNING SYSTEM",
  "AUTO LEVELING",
  "AUTO OUTRIGGER LEVELING",
  "AUTO COUNTERWEIGHT DETECTION",
  "AUTO TELESCOPING",
  "AUTO BOOM MODE",
  "AUTO RIGGING MODE",
  "SELF ASSEMBLY",
  "SELF DISASSEMBLY",
  "SELF ERECTING",
  "SELF LOADING",
  "SELF INSTALLING COUNTERWEIGHT",
  "DIAGNOSTIC DISPLAY",
  "REMOTE DIAGNOSTICS",
  "CAMERA SYSTEM",
  "WINCH CAMERA",
  "REAR CAMERA",
  "RIGHT SIDE CAMERA",
  "360 CAMERA",

  /* -------------------- */
  /* TRANSPORT DNA */
  /* -------------------- */

  "BOOM DOLLY",
  "BOOM TRAILER",
  "DOLLY PREP",
  "TRANSPORT DOLLY",
  "COUNTERWEIGHT TRANSPORT",
  "SELF TRANSPORT",
  "ROADABLE CONFIGURATION",
  "TRANSPORT MODE",
  "REMOVABLE COUNTERWEIGHT",
  "REMOVABLE CRAWLERS",
  "REMOVABLE SIDE FRAMES",
  "TRANSPORT WIDTH CONFIGURATION",
  "TRANSPORT HEIGHT CONFIGURATION",
  "FOLDING JIB",
  "STOWABLE JIB",
  "STOWABLE OUTRIGGERS",
  "AXLE REMOVAL SYSTEM",
  "SELF ASSEMBLY TRANSPORT",

  /* -------------------- */
  /* TOWER CRANE DNA */
  /* -------------------- */

  "TOWER CRANE",
  "SELF ERECTING TOWER CRANE",
  "FLAT TOP TOWER CRANE",
  "HAMMERHEAD TOWER CRANE",
  "LUFFING TOWER CRANE",
  "TOP SLEWING TOWER CRANE",
  "BOTTOM SLEWING TOWER CRANE",
  "MOBILE TOWER CRANE",
  "TOWER MAST",
  "MAST SECTIONS",
  "TOWER JIB",
  "COUNTER JIB",
  "TROLLEY JIB",
  "TROLLEY MECHANISM",
  "CLIMBING SYSTEM",
  "INTERNAL CLIMBING",
  "EXTERNAL CLIMBING",
  "ANCHORING FRAME",
  "TIE IN FRAME",
  "BASE BALLAST",
  "TOWER COUNTERWEIGHT",
  "ERECTION HYDRAULICS",

  /* -------------------- */
  /* GANTRY / INDUSTRIAL DNA */
  /* -------------------- */

  "GANTRY CRANE",
  "MOBILE GANTRY",
  "PORTAL CRANE",
  "RAIL MOUNTED GANTRY",
  "RUBBER TIRED GANTRY",
  "INDUSTRIAL CARRY DECK",
  "PICK AND CARRY",
  "CARRY DECK",
  "DECK CARRIER",
  "LOW HEADROOM CRANE",
  "SHOP CRANE",
  "SERVICE CRANE",
  "TELESCOPIC SERVICE CRANE",
  "ELECTRIC SERVICE CRANE",
  "HYDRAULIC SERVICE CRANE",

  /* -------------------- */
  /* BUCKET / DIGGER DERRICK DNA */
  /* -------------------- */

  "DIGGER DERRICK",
  "BUCKET TRUCK",
  "MATERIAL HANDLING BUCKET TRUCK",
  "INSULATED BOOM",
  "NON INSULATED BOOM",
  "OVER CENTER BOOM",
  "NON OVER CENTER BOOM",
  "TELESCOPIC AERIAL BOOM",
  "ARTICULATING AERIAL BOOM",
  "MATERIAL HANDLING JIB",
  "POLE CLAWS",
  "POLE GUIDES",
  "AUGER DRIVE",
  "DIGGER BOOM",
  "WINCH LINE",
  "PERSONNEL PLATFORM",
  "FIBERGLASS PLATFORM",
  "STEEL PLATFORM",
  "PLATFORM ROTATOR",
  "PLATFORM LEVELING",

  /* -------------------- */
  /* DRIVE / POWERTRAIN DNA */
  /* -------------------- */

  "SINGLE ENGINE",
  "DUAL ENGINE",
  "DIESEL ENGINE",
  "ELECTRIC POWER",
  "HYBRID POWER",
  "PTO DRIVE",
  "PUMP DRIVE",
  "HYDROSTATIC DRIVE",
  "MECHANICAL DRIVE",
  "ALL WHEEL DRIVE",
  "4X4",
  "6X6",
  "8X4",
  "8X6",
  "8X8",
  "10X6",
  "10X8",
  "12X8",
  "TRANSMISSION",
  "AUTOMATIC TRANSMISSION",
  "POWERSHIFT TRANSMISSION",
  "ALLISON TRANSMISSION",
  "CARRIER DRIVE",
  "CRAWLER DRIVE",
  "FINAL DRIVES",

  /* -------------------- */
  /* BRAKING / RETARDER DNA */
  /* -------------------- */

  "AIR BRAKES",
  "HYDRAULIC BRAKES",
  "WET DISC BRAKES",
  "DRY DISC BRAKES",
  "SPRING APPLIED BRAKES",
  "PARK BRAKE",
  "SERVICE BRAKES",
  "SWING BRAKE",
  "WINCH BRAKE",
  "HOIST BRAKE",
  "ENGINE BRAKE",
  "TRANSMISSION RETARDER",
  "HYDRAULIC RETARDER",

  /* -------------------- */
  /* SAFETY SYSTEM DNA */
  /* -------------------- */

  "ANTI TWO BLOCK",
  "A2B",
  "OVERLOAD PROTECTION",
  "LOAD MOMENT LIMITER",
  "RATED CAPACITY LIMITER",
  "EMERGENCY STOP",
  "EMERGENCY LOWERING",
  "SWING ALARM",
  "TRAVEL ALARM",
  "BACKUP ALARM",
  "WORK AREA LIMITER",
  "OUTRIGGER INTERLOCK",
  "BOOM ANGLE LIMITER",
  "HOIST LIMITER",
  "LIMIT SWITCHES",
  "FIRE SUPPRESSION",
  "AUTO LUBE",
  "CENTRALIZED GREASING",
  "WIND SPEED INDICATOR",
  "AVIATION LIGHTS",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-DEF",
  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4",
  "TIER 4 FINAL",
  "T4F",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF",
  "DEF DELETE"
];

export default craneDnaKeywords;
