// /lib/cranesTaxonomy.js
const cranesTaxonomy = [
  //
  //ALTEC
  //
{ make: "ALTEC", model: "A40" },
{ make: "ALTEC", model: "A55" },
{ make: "ALTEC", model: "A65" },
{ make: "ALTEC", model: "A35" },
{ make: "ALTEC", model: "A72" },
{ make: "ALTEC", model: "A75" },
{ make: "ALTEC", model: "A77" },
{ make: "ALTEC", model: "A470" },
{ make: "ALTEC", model: "A771" },
{ make: "ALTEC", model: "AA28" },
{ make: "ALTEC", model: "AA55" },
{ make: "ALTEC", model: "AA60" },
{ make: "ALTEC", model: "AA77" },
{ make: "ALTEC", model: "AA280" },
{ make: "ALTEC", model: "AA600" },
{ make: "ALTEC", model: "AA755" },
{ make: "ALTEC", model: "AC18" },
{ make: "ALTEC", model: "AC23" },
{ make: "ALTEC", model: "AC26" },
{ make: "ALTEC", model: "AC30" },
{ make: "ALTEC", model: "AC38" },
{ make: "ALTEC", model: "AC40" },
{ make: "ALTEC", model: "AC45" },
{ make: "ALTEC", model: "AH85" },
{ make: "ALTEC", model: "AH100" },
{ make: "ALTEC", model: "AH125" },
{ make: "ALTEC", model: "AM50" },
{ make: "ALTEC", model: "AM55" },
{ make: "ALTEC", model: "AM60" },
{ make: "ALTEC", model: "AM450" },
{ make: "ALTEC", model: "AM650" },
{ make: "ALTEC", model: "AM855" },
{ make: "ALTEC", model: "AM900" },
{ make: "ALTEC", model: "AN55" },
{ make: "ALTEC", model: "AN67" },
{ make: "ALTEC", model: "AN546" },
{ make: "ALTEC", model: "AN652" },
{ make: "ALTEC", model: "SN50" },
{ make: "ALTEC", model: "SN55" },
{ make: "ALTEC", model: "AN67" },
{ make: "ALTEC", model: "AN546" },
{ make: "ALTEC", model: "AN652" },
{ make: "ALTEC", model: "AP36" },
{ make: "ALTEC", model: "AP40" },
{ make: "ALTEC", model: "AT35" },
{ make: "ALTEC", model: "AT37" },
{ make: "ALTEC", model: "AT40" },
{ make: "ALTEC", model: "AT41" },
{ make: "ALTEC", model: "AT48" },
{ make: "ALTEC", model: "AT200" },
{ make: "ALTEC", model: "AT235" },
{ make: "ALTEC", model: "AT237" },
{ make: "ALTEC", model: "AT238" },
{ make: "ALTEC", model: "AT248" },
{ make: "ALTEC", model: "D820" },
{ make: "ALTEC", model: "D842" },
{ make: "ALTEC", model: "D845" },
{ make: "ALTEC", model: "D945" },
{ make: "ALTEC", model: "D947" },
{ make: "ALTEC", model: "D1000" },
{ make: "ALTEC", model: "D2045" },
{ make: "ALTEC", model: "D2050" },
{ make: "ALTEC", model: "D2055" },
{ make: "ALTEC", model: "D3050" },
{ make: "ALTEC", model: "D3055" },
{ make: "ALTEC", model: "D3060" },
{ make: "ALTEC", model: "D4050" },
{ make: "ALTEC", model: "D4060" },
{ make: "ALTEC", model: "D4065" },
{ make: "ALTEC", model: "DB35" },
{ make: "ALTEC", model: "DB37" },
{ make: "ALTEC", model: "DB41" },
{ make: "ALTEC", model: "DC45" },
{ make: "ALTEC", model: "DC47" },
{ make: "ALTEC", model: "DL42" },
{ make: "ALTEC", model: "DL45" },
{ make: "ALTEC", model: "DM45" },
{ make: "ALTEC", model: "DM47" },
{ make: "ALTEC", model: "DT65" },
{ make: "ALTEC", model: "DT80" },
{ make: "ALTEC", model: "DT105" },
{ make: "ALTEC", model: "ENTERGY AT37" },
{ make: "ALTEC", model: "HL125" },
{ make: "ALTEC", model: "L36" },
{ make: "ALTEC", model: "L37" },
{ make: "ALTEC", model: "L42" },
{ make: "ALTEC", model: "L44" },
{ make: "ALTEC", model: "L45" },
{ make: "ALTEC", model: "LR7" },
{ make: "ALTEC", model: "LR760" },
{ make: "ALTEC", model: "LRIII55" },
{ make: "ALTEC", model: "LRV55" },
{ make: "ALTEC", model: "LRV56" },
{ make: "ALTEC", model: "LRV57" },
{ make: "ALTEC", model: "LRV58" },
{ make: "ALTEC", model: "LRV60" },
{ make: "ALTEC", model: "LS40" },
{ make: "ALTEC", model: "LS49" },
{ make: "ALTEC", model: "LS60" },
{ make: "ALTEC", model: "LS87" },
{ make: "ALTEC", model: "LS63" },
{ make: "ALTEC", model: "T40" },
{ make: "ALTEC", model: "TA37" },
{ make: "ALTEC", model: "TA40" },
{ make: "ALTEC", model: "TA41" },
{ make: "ALTEC", model: "TA45" },
{ make: "ALTEC", model: "TA50" },
{ make: "ALTEC", model: "TA60" },
{ make: "ALTEC", model: "OTHER" },
//
//TEREX
//
{ make: "TEREX", model: "5TC-55" },
{ make: "TEREX", model: "AC30" },
{ make: "TEREX", model: "AC35" },
{ make: "TEREX", model: "AC40" },
{ make: "TEREX", model: "AC40/2" },
{ make: "TEREX", model: "AC50" },
{ make: "TEREX", model: "AC55" },
{ make: "TEREX", model: "AC60" },
{ make: "TEREX", model: "AC70" },
{ make: "TEREX", model: "AC100" },
{ make: "TEREX", model: "AC200" },
{ make: "TEREX", model: "AC350" },
{ make: "TEREX", model: "AC500" },
{ make: "TEREX", model: "AT15" },
{ make: "TEREX", model: "AT20" },
{ make: "TEREX", model: "AT40" },
{ make: "TEREX", model: "ATT400" },
{ make: "TEREX", model: "ATT1300" },
{ make: "TEREX", model: "BT2047" },
{ make: "TEREX", model: "BT3060" },
{ make: "TEREX", model: "BT3400" },
{ make: "TEREX", model: "BT3470" },
{ make: "TEREX", model: "BT3870" },
{ make: "TEREX", model: "BT3874" },
{ make: "TEREX", model: "BT4772" },
{ make: "TEREX", model: "BT4792" },
{ make: "TEREX", model: "BT5092" },
{ make: "TEREX", model: "BT28106" },
{ make: "TEREX", model: "CBR36" },
{ make: "TEREX", model: "CBR40" },
{ make: "TEREX", model: "CC400" },
{ make: "TEREX", model: "CC2500" },
{ make: "TEREX", model: "CC2800" },
{ make: "TEREX", model: "CC3800" },
{ make: "TEREX", model: "CD225" },
{ make: "TEREX", model: "CHALLENGER 3160" },
{ make: "TEREX", model: "COMMANDER 4040" },
{ make: "TEREX", model: "COMMANDER 4042" },
{ make: "TEREX", model: "COMMANDER 4045" },
{ make: "TEREX", model: "COMMANDER 4047" },
{ make: "TEREX", model: "COMMANDER 4050" },
{ make: "TEREX", model: "COMMANDER 5045" },
{ make: "TEREX", model: "COMMANDER 5048" },
{ make: "TEREX", model: "COMMANDER 5050" },
{ make: "TEREX", model: "COMMANDER 5052" },
{ make: "TEREX", model: "COMMANDER 6000" },
{ make: "TEREX", model: "COMMANDER 6054" },
{ make: "TEREX", model: "COMMANDER 6060" },
{ make: "TEREX", model: "COMMANDER 7000" },
{ make: "TEREX", model: "CROSSOVER 4500" },
{ make: "TEREX", model: "CROSSOVER 6000" },
{ make: "TEREX", model: "CROSSOVER 8000" },
{ make: "TEREX", model: "CTL140" },
{ make: "TEREX", model: "CTL 260" },
{ make: "TEREX", model: "CTYL 430" },
{ make: "TEREX", model: "CTL 630" },
{ make: "TEREX", model: "CTT121" },
{ make: "TEREX", model: "CTT132" },
{ make: "TEREX", model: "CTT172" },
{ make: "TEREX", model: "CTT181" },
{ make: "TEREX", model: "CTT182" },
{ make: "TEREX", model: "CTT202" },
{ make: "TEREX", model: "CTT331" },
{ make: "TEREX", model: "CT332" },
{ make: "TEREX", model: "CTT531" },
{ make: "TEREX", model: "CTT561" },
{ make: "TEREX", model: "CTT321" },
{ make: "TEREX", model: "EXPLORER 5500" },
{ make: "TEREX", model: "EXPLORER 5800" },
{ make: "TEREX", model: "GENERAL 54" },
{ make: "TEREX", model: "GENERAL 65" },
{ make: "TEREX", model: "GENERAL 80" },
{ make: "TEREX", model: "HC80" },
{ make: "TEREX", model: "HC110" },
{ make: "TEREX", model: "HC120" },
{ make: "TEREX", model: "HC230" },
{ make: "TEREX", model: "HC275" },
{ make: "TEREX", model: "HC285" },
{ make: "TEREX", model: "HI RANGER 6TC-65" },
{ make: "TEREX", model: "HR37" },
{ make: "TEREX", model: "HR40" },
{ make: "TEREX", model: "HR46" },
{ make: "TEREX", model: "HR50" },
{ make: "TEREX", model: "HR55" },
{ make: "TEREX", model: "HR5TC" },
{ make: "TEREX", model: "HRX52" },
{ make: "TEREX", model: "HRX55" },
{ make: "TEREX", model: "HIRANGER 5FC-60" },
{ make: "TEREX", model: "HIRANGER 5TC-52" },
{ make: "TEREX", model: "HIRANGER 5TC-55" },
{ make: "TEREX", model: "HIRANGER 50M" },
{ make: "TEREX", model: "HIRANGER" },
{ make: "TEREX", model: "HR46M" },
{ make: "TEREX", model: "HIRANGER 52M" },
{ make: "TEREX", model: "HIRANGER HRX-60" },
{ make: "TEREX", model: "HIRANGER LT40" },
{ make: "TEREX", model: "HIRANGER TC55" },
{ make: "TEREX", model: "HIRANGER HRX-60" },
{ make: "TEREX", model: "HIRANGER LT40" },
{ make: "TEREX", model: "HIRANGER TC55" },
{ make: "TEREX", model: "HIRANGER TL37M" },
{ make: "TEREX", model: "HIRANGER TL45" },
{ make: "TEREX", model: "HIRANGER TL55" },
{ make: "TEREX", model: "HIRANGER XT55" },
{ make: "TEREX", model: "HIRANGER XT60" },
{ make: "TEREX", model: "L4040" },
{ make: "TEREX", model: "LRT110" },
{ make: "TEREX", model: "LT38" },
{ make: "TEREX", model: "LT40" },
{ make: "TEREX", model: "LTM40" },
{ make: "TEREX", model: "MAC 25" },
{ make: "TEREX", model: "NT29" },
{ make: "TEREX", model: "OPTIMA HRX55" },
{ make: "TEREX", model: "OPTIMA TC55" },
{ make: "TEREX", model: "OPTIMA TCX55" },
{ make: "TEREX", model: "POWERLIFT 1000" },
{ make: "TEREX", model: "QUADSTAR 1065" },
{ make: "TEREX", model: "QUADSTAR 1075" },
{ make: "TEREX", model: "QUADSTAR 1100" },
{ make: "TEREX", model: "RC30" },
{ make: "TEREX", model: "RM75/100" },
{ make: "TEREX", model: "RM4792" },
{ make: "TEREX", model: "RS600" },
{ make: "TEREX", model: "RS70100" },
{ make: "TEREX", model: "RT90" },
{ make: "TEREX", model: "RT100" },
{ make: "TEREX", model: "RT130" },
{ make: "TEREX", model: "RT160" },
{ make: "TEREX", model: "RT190" },
{ make: "TEREX", model: "RT230" },
{ make: "TEREX", model: "RT335" },
{ make: "TEREX", model: "RT345" },
{ make: "TEREX", model: "RT445" },
{ make: "TEREX", model: "RT555" },
{ make: "TEREX", model: "RT665" },
{ make: "TEREX", model: "RT670" },
{ make: "TEREX", model: "RT780" },
{ make: "TEREX", model: "SC45" },
{ make: "TEREX", model: "SK415" },
{ make: "TEREX", model: "SK575" },
{ make: "TEREX", model: "SW35" },
{ make: "TEREX", model: "T230" },
{ make: "TEREX", model: "T292" },
{ make: "TEREX", model: "T335" },
{ make: "TEREX", model: "T340" },
{ make: "TEREX", model: "T550" },
{ make: "TEREX", model: "T560" },
{ make: "TEREX", model: "T775" },
{ make: "TEREX", model: "T780" },
{ make: "TEREX", model: "TC40" },
{ make: "TEREX", model: "TC55" },
{ make: "TEREX", model: "TC2863" },
{ make: "TEREX", model: "TC3063" },
{ make: "TEREX", model: "TC3470" },
{ make: "TEREX", model: "TC3874" },
{ make: "TEREX", model: "TCX55" },
{ make: "TEREX", model: "TCX65/100" },
{ make: "TEREX", model: "TEXOMA 650" },
{ make: "TEREX", model: "TL37" },
{ make: "TEREX", model: "TL38" },
{ make: "TEREX", model: "TL41" },
{ make: "TEREX", model: "TL50" },
{ make: "TEREX", model: "TM100" },
{ make: "TEREX", model: "TM105" },
{ make: "TEREX", model: "TM125" },
{ make: "TEREX", model: "TM3851" },
{ make: "TEREX", model: "TRT40" },
{ make: "TEREX", model: "TRT55" },
{ make: "TEREX", model: "TRT70" },
{ make: "TEREX", model: "TRT80" },
{ make: "TEREX", model: "TRT100" },
{ make: "TEREX", model: "XL4045" },
{ make: "TEREX", model: "XM55" },
{ make: "TEREX", model: "XT PRO 56" },
{ make: "TEREX", model: "XT PRTO 60" },
{ make: "TEREX", model: "XT PRO 60/70" },
{ make: "TEREX", model: "OTHER" },
//
//GROVE
//
{ make: "GROVE", model: "68" },
{ make: "GROVE", model: "315" },
{ make: "GROVE", model: "AP206" },
{ make: "GROVE", model: "AP308" },
{ make: "GROVE", model: "AT633" },
{ make: "GROVE", model: "AT700" },
{ make: "GROVE", model: "AT735" },
{ make: "GROVE", model: "AT750" },
{ make: "GROVE", model: "GCD09" },
{ make: "GROVE", model: "GCD15" },
{ make: "GROVE", model: "GCD20" },
{ make: "GROVE", model: "GCD25" },
{ make: "GROVE", model: "GCK3045" },
{ make: "GROVE", model: "GHC55" },
{ make: "GROVE", model: "GHC75" },
{ make: "GROVE", model: "GHC85" },
{ make: "GROVE", model: "GHC110" },
{ make: "GROVE", model: "GHC130" },
{ make: "GROVE", model: "GHC140" },
{ make: "GROVE", model: "GMK2035" },
{ make: "GROVE", model: "GMK3050" },
{ make: "GROVE", model: "GMK3055" },
{ make: "GROVE", model: "GMK3060" },
{ make: "GROVE", model: "GMK4075" },
{ make: "GROVE", model: "GMK4080" },
{ make: "GROVE", model: "GMK4090" },
{ make: "GROVE", model: "GMK4100" },
{ make: "GROVE", model: "GMK4115" },
{ make: "GROVE", model: "GMK5090" },
{ make: "GROVE", model: "GMK5095" },
{ make: "GROVE", model: "GMK5100" },
{ make: "GROVE", model: "GMK5110" },
{ make: "GROVE", model: "GMK5120" },
{ make: "GROVE", model: "GMK5130" },
{ make: "GROVE", model: "GMK5150" },
{ make: "GROVE", model: "GMK5160" },
{ make: "GROVE", model: "GMK5165" },
{ make: "GROVE", model: "GMK5175" },
{ make: "GROVE", model: "GMK5180" },
{ make: "GROVE", model: "GMK5200" },
{ make: "GROVE", model: "GMK5210" },
{ make: "GROVE", model: "GMK5220" },
{ make: "GROVE", model: "GMK5225" },
{ make: "GROVE", model: "GMK5240" },
{ make: "GROVE", model: "GMK5250" },
{ make: "GROVE", model: "GMK5275" },
{ make: "GROVE", model: "GMK6220" },
{ make: "GROVE", model: "GMK6250" },
{ make: "GROVE", model: "GMK6300" },
{ make: "GROVE", model: "GMK6350" },
{ make: "GROVE", model: "GMK6400" },
{ make: "GROVE", model: "GMK6450" },
{ make: "GROVE", model: "GMK7450" },
{ make: "GROVE", model: "GMK7550" },
{ make: "GROVE", model: "GRT650" },
{ make: "GROVE", model: "GRT655" },
{ make: "GROVE", model: "GRT765" },
{ make: "GROVE", model: "GRT780" },
{ make: "GROVE", model: "GRT880" },
{ make: "GROVE", model: "GRT8090" },
{ make: "GROVE", model: "GRT8100" },
{ make: "GROVE", model: "GRT8120" },
{ make: "GROVE", model: "GRT9165" },
{ make: "GROVE", model: "HL150" },
{ make: "GROVE", model: "IND24" },
{ make: "GROVE", model: "IND36" },
{ make: "GROVE", model: "MLC150" },
{ make: "GROVE", model: "RT58" },
{ make: "GROVE", model: "RT59" },
{ make: "GROVE", model: "RT60" },
{ make: "GROVE", model: "RT65" },
{ make: "GROVE", model: "RT75" },
{ make: "GROVE", model: "RT422" },
{ make: "GROVE", model: "RT500" },
{ make: "GROVE", model: "RT518" },
{ make: "GROVE", model: "RT522" },
{ make: "GROVE", model: "RT525" },
{ make: "GROVE", model: "RT528" },
{ make: "GROVE", model: "RT530" },
{ make: "GROVE", model: "RT535" },
{ make: "GROVE", model: "RT540" },
{ make: "GROVE", model: "RT550" },
{ make: "GROVE", model: "RT600" },
{ make: "GROVE", model: "RT620" },
{ make: "GROVE", model: "RT625" },
{ make: "GROVE", model: "RT630" },
{ make: "GROVE", model: "RT635" },
{ make: "GROVE", model: "RT640" },
{ make: "GROVE", model: "RT650" },
{ make: "GROVE", model: "RT700" },
{ make: "GROVE", model: "RT740" },
{ make: "GROVE", model: "RT745" },
{ make: "GROVE", model: "RT750" },
{ make: "GROVE", model: "RT760" },
{ make: "GROVE", model: "RT765" },
{ make: "GROVE", model: "RT770" },
{ make: "GROVE", model: "RT800" },
{ make: "GROVE", model: "RT855" },
{ make: "GROVE", model: "RT865" },
{ make: "GROVE", model: "RT870" },
{ make: "GROVE", model: "RT875" },
{ make: "GROVE", model: "RT880" },
{ make: "GROVE", model: "RT890" },
{ make: "GROVE", model: "RT980" },
{ make: "GROVE", model: "RT9100" },
{ make: "GROVE", model: "RT9130" },
{ make: "GROVE", model: "RT9150" },
{ make: "GROVE", model: "TD180" },
{ make: "GROVE", model: "TM80/88T" },
{ make: "GROVE", model: "TM150" },
{ make: "GROVE", model: "TM500" },
{ make: "GROVE", model: "TM550" },
{ make: "GROVE", model: "TM750" },
{ make: "GROVE", model: "TM800" },
{ make: "GROVE", model: "TM890" },
{ make: "GROVE", model: "TM1150" },
{ make: "GROVE", model: "TM1275" },
{ make: "GROVE", model: "TMSS225" },
{ make: "GROVE", model: "TMS250" },
{ make: "GROVE", model: "TMS300" },
{ make: "GROVE", model: "TMS375" },
{ make: "GROVE", model: "TMS475" },
{ make: "GROVE", model: "TMS500" },
{ make: "GROVE", model: "TMS520" },
{ make: "GROVE", model: "TMS635" },
{ make: "GROVE", model: "TMS640" },
{ make: "GROVE", model: "TMS700" },
{ make: "GROVE", model: "TMS760" },
{ make: "GROVE", model: "TMS800" },
{ make: "GROVE", model: "TMS870" },
{ make: "GROVE", model: "TMS880" },
{ make: "GROVE", model: "TMS900" },
{ make: "GROVE", model: "TMS9000" },
{ make: "GROVE", model: "TTS870" },
{ make: "GROVE", model: "YB4409" },
{ make: "GROVE", model: "YB4410" },
{ make: "GROVE", model: "YB4411" },
{ make: "GROVE", model: "YB5515" },
{ make: "GROVE", model: "YB7725" },
{ make: "GROVE", model: "OTHER" },
//
//XCMG
//



  
]


  export default cranesTaxonomy;
