const excavatorsTaxonomy = [

 // CATERPILLAR EXCAVATORS 

// MINI / COMPACT EXCAVATORS (0 - 6 ton)
{ make: "Caterpillar", model: "300.9D" },
{ make: "Caterpillar", model: "301.4C" },
{ make: "Caterpillar", model: "301.5" },
{ make: "Caterpillar", model: "301.5CR" },
{ make: "Caterpillar", model: "301.6" },
{ make: "Caterpillar", model: "301.6C" },
{ make: "Caterpillar", model: "301.7CR" },
{ make: "Caterpillar", model: "301.7D" },
{ make: "Caterpillar", model: "301.7D CR" },
{ make: "Caterpillar", model: "301.8" },
{ make: "Caterpillar", model: "301.8C" },
{ make: "Caterpillar", model: "302C CR" },
{ make: "Caterpillar", model: "302CR" },
{ make: "Caterpillar", model: "302.2D" },
{ make: "Caterpillar", model: "302.4D" },
{ make: "Caterpillar", model: "302.5" },
{ make: "Caterpillar", model: "302.5C" },
{ make: "Caterpillar", model: "302.5E SR" },
{ make: "Caterpillar", model: "302.7CR" },
{ make: "Caterpillar", model: "302.7D" },
{ make: "Caterpillar", model: "302.7D CR" },
{ make: "Caterpillar", model: "303C CR" },
{ make: "Caterpillar", model: "303CR" },
{ make: "Caterpillar", model: "303E CR" },
{ make: "Caterpillar", model: "303GR" },
{ make: "Caterpillar", model: "303.5" },
{ make: "Caterpillar", model: "303.5C" },
{ make: "Caterpillar", model: "303.5C CR" },
{ make: "Caterpillar", model: "303.5CR" },
{ make: "Caterpillar", model: "303.5D CR" },
{ make: "Caterpillar", model: "303.5E CR" },
{ make: "Caterpillar", model: "303.5E2 CR" },
{ make: "Caterpillar", model: "304" },
{ make: "Caterpillar", model: "304C" },
{ make: "Caterpillar", model: "304C CR" },
{ make: "Caterpillar", model: "304CR" },
{ make: "Caterpillar", model: "304D CR" },
{ make: "Caterpillar", model: "304E CR" },
{ make: "Caterpillar", model: "304E2 CR" },
{ make: "Caterpillar", model: "304.5" },
{ make: "Caterpillar", model: "305" },
{ make: "Caterpillar", model: "305C" },
{ make: "Caterpillar", model: "305C CR" },
{ make: "Caterpillar", model: "305CR" },
{ make: "Caterpillar", model: "305D" },
{ make: "Caterpillar", model: "305D CR" },
{ make: "Caterpillar", model: "305E CR" },
{ make: "Caterpillar", model: "305E2" },
{ make: "Caterpillar", model: "305E2 CR" },
{ make: "Caterpillar", model: "305SR" },
{ make: "Caterpillar", model: "305.5" },
{ make: "Caterpillar", model: "305.5D CR" },
{ make: "Caterpillar", model: "305.5E" },
{ make: "Caterpillar", model: "305.5E CR" },
{ make: "Caterpillar", model: "305.5E2" },
{ make: "Caterpillar", model: "305.5E2 CR" },
{ make: "Caterpillar", model: "306" },
{ make: "Caterpillar", model: "306CR" },
{ make: "Caterpillar", model: "306D" },
{ make: "Caterpillar", model: "306E" },
{ make: "Caterpillar", model: "306.5" },
{ make: "Caterpillar", model: "307" },
{ make: "Caterpillar", model: "307B" },
{ make: "Caterpillar", model: "307C" },
{ make: "Caterpillar", model: "307D" },
{ make: "Caterpillar", model: "307E" },
{ make: "Caterpillar", model: "307EII" },
{ make: "Caterpillar", model: "307SSR" },
{ make: "Caterpillar", model: "307.5" },
{ make: "Caterpillar", model: "308 CR" },
{ make: "Caterpillar", model: "308B CR" },
{ make: "Caterpillar", model: "308C" },
{ make: "Caterpillar", model: "308C CR" },
{ make: "Caterpillar", model: "308D" },
{ make: "Caterpillar", model: "308D CR" },
{ make: "Caterpillar", model: "308E" },
{ make: "Caterpillar", model: "308E CR" },
{ make: "Caterpillar", model: "308E SR" },
{ make: "Caterpillar", model: "308E2" },
{ make: "Caterpillar", model: "308E2 CR" },
{ make: "Caterpillar", model: "308.5" },
{ make: "Caterpillar", model: "308.5E2" },
{ make: "Caterpillar", model: "309CR" },
{ make: "Caterpillar", model: "310" },

// SMALL / MIDI (approx 6 - 12 ton)
{ make: "Caterpillar", model: "311" },
{ make: "Caterpillar", model: "311B" },
{ make: "Caterpillar", model: "311C" },
{ make: "Caterpillar", model: "311C U" },
{ make: "Caterpillar", model: "311D" },
{ make: "Caterpillar", model: "311DLRR" },
{ make: "Caterpillar", model: "311F RR" },
{ make: "Caterpillar", model: "311FLRR" },
{ make: "Caterpillar", model: "312" },
{ make: "Caterpillar", model: "312B" },
{ make: "Caterpillar", model: "312BL" },
{ make: "Caterpillar", model: "312C" },
{ make: "Caterpillar", model: "312CL" },
{ make: "Caterpillar", model: "312D" },
{ make: "Caterpillar", model: "312D2" },
{ make: "Caterpillar", model: "312D2 GC" },
{ make: "Caterpillar", model: "312DL" },
{ make: "Caterpillar", model: "312E" },
{ make: "Caterpillar", model: "312EL" },
{ make: "Caterpillar", model: "312F" },
{ make: "Caterpillar", model: "312FGC" },
{ make: "Caterpillar", model: "312GC" },
{ make: "Caterpillar", model: "313" },
{ make: "Caterpillar", model: "313B CR" },
{ make: "Caterpillar", model: "313C" },
{ make: "Caterpillar", model: "313CSR" },
{ make: "Caterpillar", model: "313D" },
{ make: "Caterpillar", model: "313D CR" },
{ make: "Caterpillar", model: "313D2" },
{ make: "Caterpillar", model: "313D2 GC" },
{ make: "Caterpillar", model: "313D2 L" },
{ make: "Caterpillar", model: "313FL" },
{ make: "Caterpillar", model: "313FLGC" },
{ make: "Caterpillar", model: "313GC" },
{ make: "Caterpillar", model: "314C" },
{ make: "Caterpillar", model: "314C CR" },
{ make: "Caterpillar", model: "314C LCR" },
{ make: "Caterpillar", model: "314D LCR" },
{ make: "Caterpillar", model: "314E CR" },
{ make: "Caterpillar", model: "314E LCR" },
{ make: "Caterpillar", model: "314E SR" },
{ make: "Caterpillar", model: "314EL" },
{ make: "Caterpillar", model: "314F" },
{ make: "Caterpillar", model: "314F CR" },

// MID-SIZE / STANDARD (12 - 35 ton)
{ make: "Caterpillar", model: "315" },
{ make: "Caterpillar", model: "315BL" },
{ make: "Caterpillar", model: "315C" },
{ make: "Caterpillar", model: "315CL" },
{ make: "Caterpillar", model: "315D" },
{ make: "Caterpillar", model: "315D2 GC" },
{ make: "Caterpillar", model: "315D2L" },
{ make: "Caterpillar", model: "315DL" },
{ make: "Caterpillar", model: "315F" },
{ make: "Caterpillar", model: "315F LCR" },
{ make: "Caterpillar", model: "315FL" },
{ make: "Caterpillar", model: "315L" },
{ make: "Caterpillar", model: "315D2" },
{ make: "Caterpillar", model: "315E" },
{ make: "Caterpillar", model: "316E" },
{ make: "Caterpillar", model: "316EL" },
{ make: "Caterpillar", model: "316FL" },
{ make: "Caterpillar", model: "316GC" },
{ make: "Caterpillar", model: "317" },
{ make: "Caterpillar", model: "317B" },
{ make: "Caterpillar", model: "317BL" },
{ make: "Caterpillar", model: "317GC" },
{ make: "Caterpillar", model: "318B" },
{ make: "Caterpillar", model: "318C" },
{ make: "Caterpillar", model: "318CL" },
{ make: "Caterpillar", model: "318CN" },
{ make: "Caterpillar", model: "318D" },
{ make: "Caterpillar", model: "318D2L" },
{ make: "Caterpillar", model: "318DL" },
{ make: "Caterpillar", model: "318EL" },
{ make: "Caterpillar", model: "318FL" },
{ make: "Caterpillar", model: "319CLN" },
{ make: "Caterpillar", model: "319D" },
{ make: "Caterpillar", model: "319DL" },
{ make: "Caterpillar", model: "320" },
{ make: "Caterpillar", model: "320B" },
{ make: "Caterpillar", model: "320BL" },
{ make: "Caterpillar", model: "320C" },
{ make: "Caterpillar", model: "320C FM" },
{ make: "Caterpillar", model: "320C LC" },
{ make: "Caterpillar", model: "320C LU" },
{ make: "Caterpillar", model: "320CL" },
{ make: "Caterpillar", model: "320CLN" },
{ make: "Caterpillar", model: "320D" },
{ make: "Caterpillar", model: "320D FM" },
{ make: "Caterpillar", model: "320D2" },
{ make: "Caterpillar", model: "320D2 GC" },
{ make: "Caterpillar", model: "320D2L" },
{ make: "Caterpillar", model: "320D3DC" },
{ make: "Caterpillar", model: "320D3GC" },
{ make: "Caterpillar", model: "320DL" },
{ make: "Caterpillar", model: "320DLRR" },
{ make: "Caterpillar", model: "320E" },
{ make: "Caterpillar", model: "320EL" },
{ make: "Caterpillar", model: "320EL CF" },
{ make: "Caterpillar", model: "320ELRR" },
{ make: "Caterpillar", model: "320ERR" },
{ make: "Caterpillar", model: "320FL" },
{ make: "Caterpillar", model: "320GC" },
{ make: "Caterpillar", model: "320GX" },
{ make: "Caterpillar", model: "320L" },
{ make: "Caterpillar", model: "321" },
{ make: "Caterpillar", model: "321B LCR" },
{ make: "Caterpillar", model: "321C" },
{ make: "Caterpillar", model: "321C LCR" },
{ make: "Caterpillar", model: "321D CR" },
{ make: "Caterpillar", model: "321D LCR" },
{ make: "Caterpillar", model: "322B" },
{ make: "Caterpillar", model: "322BL" },
{ make: "Caterpillar", model: "322C" },
{ make: "Caterpillar", model: "322CL" },
{ make: "Caterpillar", model: "322L" },
{ make: "Caterpillar", model: "323" },
{ make: "Caterpillar", model: "323D" },
{ make: "Caterpillar", model: "323D2" },
{ make: "Caterpillar", model: "323D2L" },
{ make: "Caterpillar", model: "323D3" },
{ make: "Caterpillar", model: "323DL" },
{ make: "Caterpillar", model: "323DL ME" },
{ make: "Caterpillar", model: "323DLN" },
{ make: "Caterpillar", model: "323EL" },
{ make: "Caterpillar", model: "323ELN" },
{ make: "Caterpillar", model: "323ESA" },
{ make: "Caterpillar", model: "323F SA" },
{ make: "Caterpillar", model: "323FL" },
{ make: "Caterpillar", model: "323GC" },
{ make: "Caterpillar", model: "323GX" },
{ make: "Caterpillar", model: "324" },
{ make: "Caterpillar", model: "324D" },
{ make: "Caterpillar", model: "324D FM" },
{ make: "Caterpillar", model: "324D2" },
{ make: "Caterpillar", model: "324D2L" },
{ make: "Caterpillar", model: "324DL" },
{ make: "Caterpillar", model: "324DLN" },
{ make: "Caterpillar", model: "324E" },
{ make: "Caterpillar", model: "324EL" },
{ make: "Caterpillar", model: "324ELN" },
{ make: "Caterpillar", model: "325" },
{ make: "Caterpillar", model: "325B" },
{ make: "Caterpillar", model: "325BL" },
{ make: "Caterpillar", model: "325C" },
{ make: "Caterpillar", model: "325C CR" },
{ make: "Caterpillar", model: "325C LCR" },
{ make: "Caterpillar", model: "325CL" },
{ make: "Caterpillar", model: "325CLN" },
{ make: "Caterpillar", model: "325D" },
{ make: "Caterpillar", model: "325D2" },
{ make: "Caterpillar", model: "325D2L" },
{ make: "Caterpillar", model: "325DL" },
{ make: "Caterpillar", model: "325DLN" },
{ make: "Caterpillar", model: "325FL" },
{ make: "Caterpillar", model: "325FLCR" },
{ make: "Caterpillar", model: "325L" },
{ make: "Caterpillar", model: "326" },
{ make: "Caterpillar", model: "326D2" },
{ make: "Caterpillar", model: "326D2L" },
{ make: "Caterpillar", model: "326F" },
{ make: "Caterpillar", model: "326FL" },
{ make: "Caterpillar", model: "326FLN" },
{ make: "Caterpillar", model: "326GC" },
{ make: "Caterpillar", model: "328D" },
{ make: "Caterpillar", model: "328D LCR" },
{ make: "Caterpillar", model: "329D" },
{ make: "Caterpillar", model: "329D2" },
{ make: "Caterpillar", model: "329D2L" },
{ make: "Caterpillar", model: "329DL" },
{ make: "Caterpillar", model: "329DL ME" },
{ make: "Caterpillar", model: "329DLN" },
{ make: "Caterpillar", model: "329E" },
{ make: "Caterpillar", model: "329EL" },
{ make: "Caterpillar", model: "329ELN" },
{ make: "Caterpillar", model: "329F" },
{ make: "Caterpillar", model: "329FL" },
{ make: "Caterpillar", model: "330" },
{ make: "Caterpillar", model: "330 LC" },
{ make: "Caterpillar", model: "330B" },
{ make: "Caterpillar", model: "330BL" },
{ make: "Caterpillar", model: "330BL UHD" },
{ make: "Caterpillar", model: "330BLN" },
{ make: "Caterpillar", model: "330C" },
{ make: "Caterpillar", model: "330CL" },
{ make: "Caterpillar", model: "330CL UHD" },
{ make: "Caterpillar", model: "330CLN" },
{ make: "Caterpillar", model: "330D" },
{ make: "Caterpillar", model: "330D2" },
{ make: "Caterpillar", model: "330D2L" },
{ make: "Caterpillar", model: "330DL" },
{ make: "Caterpillar", model: "330DL UHD" },
{ make: "Caterpillar", model: "330F" },
{ make: "Caterpillar", model: "330FL" },
{ make: "Caterpillar", model: "330FLN" },
{ make: "Caterpillar", model: "330GC" },
{ make: "Caterpillar", model: "330L" },
{ make: "Caterpillar", model: "330 UHD" },
{ make: "Caterpillar", model: "333" },
{ make: "Caterpillar", model: "335" },
{ make: "Caterpillar", model: "335F LCR" },
{ make: "Caterpillar", model: "335FL" },
{ make: "Caterpillar", model: "336" },
{ make: "Caterpillar", model: "336D" },
{ make: "Caterpillar", model: "336D2" },
{ make: "Caterpillar", model: "336D2 LME" },
{ make: "Caterpillar", model: "336D2L" },
{ make: "Caterpillar", model: "336DL" },
{ make: "Caterpillar", model: "336DL ME" },
{ make: "Caterpillar", model: "336DLN" },
{ make: "Caterpillar", model: "336E" },
{ make: "Caterpillar", model: "336EH" },
{ make: "Caterpillar", model: "336EL" },
{ make: "Caterpillar", model: "336EL H" },
{ make: "Caterpillar", model: "336ELN" },
{ make: "Caterpillar", model: "336F" },
{ make: "Caterpillar", model: "336F L ME" },
{ make: "Caterpillar", model: "336F L XE" },
{ make: "Caterpillar", model: "336FL" },
{ make: "Caterpillar", model: "336FLN" },
{ make: "Caterpillar", model: "336GC" },
{ make: "Caterpillar", model: "340" },
{ make: "Caterpillar", model: "340D" },
{ make: "Caterpillar", model: "340D2L" },
{ make: "Caterpillar", model: "340DL" },
{ make: "Caterpillar", model: "340F" },
{ make: "Caterpillar", model: "345" },
{ make: "Caterpillar", model: "345B" },
{ make: "Caterpillar", model: "345B II" },
{ make: "Caterpillar", model: "345BL" },
{ make: "Caterpillar", model: "345BL II" },
{ make: "Caterpillar", model: "345BL ME" },
{ make: "Caterpillar", model: "345BL UHD" },
{ make: "Caterpillar", model: "345CL" },
{ make: "Caterpillar", model: "345D" },
{ make: "Caterpillar", model: "345DL" },
{ make: "Caterpillar", model: "345DL ME" },
{ make: "Caterpillar", model: "345GC" },
{ make: "Caterpillar", model: "349" },
{ make: "Caterpillar", model: "349D" },
{ make: "Caterpillar", model: "349D LME" },
{ make: "Caterpillar", model: "349D2" },
{ make: "Caterpillar", model: "349D2L" },
{ make: "Caterpillar", model: "349DL" },
{ make: "Caterpillar", model: "349E" },
{ make: "Caterpillar", model: "349E LME" },
{ make: "Caterpillar", model: "349EL" },
{ make: "Caterpillar", model: "349EL VG" },
{ make: "Caterpillar", model: "349F" },
{ make: "Caterpillar", model: "349F L XE" },
{ make: "Caterpillar", model: "349FL" },
{ make: "Caterpillar", model: "350" },
{ make: "Caterpillar", model: "350L" },
{ make: "Caterpillar", model: "352" },
{ make: "Caterpillar", model: "352F" },
{ make: "Caterpillar", model: "352FXE" },
{ make: "Caterpillar", model: "352FL" },
{ make: "Caterpillar", model: "355" },
{ make: "Caterpillar", model: "365" },
{ make: "Caterpillar", model: "365BL" },
{ make: "Caterpillar", model: "365BL II" },
{ make: "Caterpillar", model: "365C" },
{ make: "Caterpillar", model: "365CL" },
{ make: "Caterpillar", model: "365CL ME" },
{ make: "Caterpillar", model: "374" },
{ make: "Caterpillar", model: "374D" },
{ make: "Caterpillar", model: "374DL" },
{ make: "Caterpillar", model: "374D LME" },
{ make: "Caterpillar", model: "374F" },
{ make: "Caterpillar", model: "374F L ME" },
{ make: "Caterpillar", model: "374FL" },
{ make: "Caterpillar", model: "375" },
{ make: "Caterpillar", model: "375 ME" },
{ make: "Caterpillar", model: "375L" },
{ make: "Caterpillar", model: "375L ME" },
{ make: "Caterpillar", model: "385B" },
{ make: "Caterpillar", model: "385BL" },
{ make: "Caterpillar", model: "385C" },
{ make: "Caterpillar", model: "385CL" },
{ make: "Caterpillar", model: "385CL ME" },
{ make: "Caterpillar", model: "390D" },
{ make: "Caterpillar", model: "390DL" },
{ make: "Caterpillar", model: "390DL ME" },
{ make: "Caterpillar", model: "390F" },
{ make: "Caterpillar", model: "390F L ME" },
{ make: "Caterpillar", model: "390FL" },
{ make: "Caterpillar", model: "395" },
{ make: "Caterpillar", model: "5080" },
{ make: "Caterpillar", model: "5130" },
{ make: "Caterpillar", model: "5230" },
{ make: "Caterpillar", model: "6015" },
{ make: "Caterpillar", model: "6015B" },
{ make: "Caterpillar", model: "6015FS" },
{ make: "Caterpillar", model: "6018ACFS" },
{ make: "Caterpillar", model: "6020B" },
{ make: "Caterpillar", model: "6030" },
{ make: "Caterpillar", model: "6040" },
{ make: "Caterpillar", model: "6040ACFS" },
{ make: "Caterpillar", model: "6040FS" },
{ make: "Caterpillar", model: "6060" },
{ make: "Caterpillar", model: "6060FS" },

// WHEEL EXCAVATORS
{ make: "Caterpillar", model: "M312" },
{ make: "Caterpillar", model: "M313C" },
{ make: "Caterpillar", model: "M313D" },
{ make: "Caterpillar", model: "M314" },
{ make: "Caterpillar", model: "M314F" },
{ make: "Caterpillar", model: "M315" },
{ make: "Caterpillar", model: "M315C" },
{ make: "Caterpillar", model: "M315D" },
{ make: "Caterpillar", model: "M315D2" },
{ make: "Caterpillar", model: "M315F" },
{ make: "Caterpillar", model: "M315GC" },
{ make: "Caterpillar", model: "M316" },
{ make: "Caterpillar", model: "M316C" },
{ make: "Caterpillar", model: "M316D" },
{ make: "Caterpillar", model: "M316F" },
{ make: "Caterpillar", model: "M317F" },
{ make: "Caterpillar", model: "M318" },
{ make: "Caterpillar", model: "M318C" },
{ make: "Caterpillar", model: "M318D" },
{ make: "Caterpillar", model: "M318F" },
{ make: "Caterpillar", model: "M319" },
{ make: "Caterpillar", model: "M320" },
{ make: "Caterpillar", model: "M320D2" },
{ make: "Caterpillar", model: "M320F" },
{ make: "Caterpillar", model: "M322" },
{ make: "Caterpillar", model: "M322C" },
{ make: "Caterpillar", model: "M322D" },
{ make: "Caterpillar", model: "M322F" },
{ make: "Caterpillar", model: "M323F" },

{ make: "Caterpillar", model: "OTHER" }

  // DEERE

  // KOMATSU

  // CASE

  // LIEBHERR

  // DRESSTA

  // SHANTUI

  // XCMG

  // SANY

  // LIUGONG

];

export default excavatorsTaxonomy;
