const featureKeywords = [
  { match: ["smartgrade", "smart grade"], label: "SmartGrade" },
  { match: ["topcon"], label: "Topcon" },
  { match: ["trimble"], label: "Trimble" },
  { match: ["gps"], label: "GPS" },
  { match: ["3d grade", "3d grade control"], label: "3D Grade Control" },
  { match: ["2d grade", "2d grade control"], label: "2D Grade Control" },
  { match: ["machine control"], label: "Machine Control" },
  { match: ["laser ready", "laser receiver"], label: "Laser Ready" },
  { match: ["joystick controls", "joystick"], label: "Joystick Controls" },
  { match: ["pilot controls"], label: "Pilot Controls" },
  { match: ["electro hydraulic", "eh controls"], label: "Electro-Hydraulic Controls" },

  { match: ["aux hydraulics", "auxiliary hydraulics"], label: "Aux Hydraulics" },
  { match: ["high flow", "hi-flow"], label: "High Flow" },
  { match: ["quick coupler", "hydraulic coupler"], label: "Hydraulic Coupler" },
  { match: ["quick attach"], label: "Quick Attach" },
  { match: ["hydraulic thumb"], label: "Hydraulic Thumb" },
  { match: ["mechanical thumb"], label: "Mechanical Thumb" },
  { match: ["hammer ready", "breaker ready"], label: "Hammer Ready" },
  { match: ["third function", "3rd function"], label: "3rd Function" },
  { match: ["tilt bucket"], label: "Tilt Bucket" },
  { match: ["cleanup bucket", "clean up bucket"], label: "Cleanup Bucket" },
  { match: ["digging bucket"], label: "Digging Bucket" },
  { match: ["rock bucket"], label: "Rock Bucket" },
  { match: ["4 in 1", "4-in-1"], label: "4-in-1 Bucket" },
  { match: ["42\" bucket", "42 inch bucket", "42 in bucket"], label: "42\" Bucket" },
  { match: ["48\" bucket", "48 inch bucket", "48 in bucket"], label: "48\" Bucket" },
  { match: ["60\" bucket", "60 inch bucket", "60 in bucket"], label: "60\" Bucket" },
  { match: ["forks", "pallet forks"], label: "Pallet Forks" },
  { match: ["grapple"], label: "Grapple" },
  { match: ["mulcher"], label: "Mulcher" },
  { match: ["breaker", "hydraulic breaker"], label: "Hydraulic Breaker" },

  { match: ["push block", "pushblock"], label: "Push Block" },
  { match: ["rear ripper", "ripper"], label: "Rear Ripper" },
  { match: ["scarifier"], label: "Scarifier" },
  { match: ["winch"], label: "Winch" },
  { match: ["pat blade", "power angle tilt"], label: "PAT Blade" },
  { match: ["6 way blade", "6-way blade"], label: "6-Way Blade" },
  { match: ["angle blade"], label: "Angle Blade" },
  { match: ["straight blade"], label: "Straight Blade" },
  { match: ["snow wing"], label: "Snow Wing" },
  { match: ["moldboard"], label: "Moldboard" },
  { match: ["circle drive"], label: "Circle Drive" },
  { match: ["ejector"], label: "Ejector" },
  { match: ["cushion hitch"], label: "Cushion Hitch" },

  { match: ["ride control"], label: "Ride Control" },
  { match: ["payload scale", "payload scales", "weigh system"], label: "Payload Scale" },
  { match: ["auto lube", "autolube", "central lube"], label: "Auto Lube" },
  { match: ["aggregate configuration", "aggregate package"], label: "Aggregate Package" },
  { match: ["high lift"], label: "High Lift" },
  { match: ["return to dig"], label: "Return To Dig" },
  { match: ["self leveling", "self-leveling"], label: "Self Leveling" },
  { match: ["z bar", "z-bar"], label: "Z-Bar Linkage" },
  { match: ["tool carrier"], label: "Tool Carrier" },
  { match: ["loadrite"], label: "Loadrite Scale" },
  { match: ["scale system"], label: "Scale System" },

  { match: ["cold ac", "cold a/c", "cold air"], label: "Cold A/C" },
  { match: ["heat"], label: "Heat" },
  { match: ["enclosed cab"], label: "Enclosed Cab" },
  { match: ["rops"], label: "ROPS" },
  { match: ["fops"], label: "FOPS" },
  { match: ["backup camera", "rear camera"], label: "Backup Camera" },
  { match: ["360 camera"], label: "360 Camera" },
  { match: ["led lights", "work lights"], label: "LED Lights" },
  { match: ["beacon", "strobe"], label: "Beacon / Strobe" },
  { match: ["air ride seat"], label: "Air Ride Seat" },

  { match: ["20.5", "20.5 tires", "20.5r25"], label: "20.5 Tires" },
  { match: ["23.5", "23.5 tires", "23.5r25"], label: "23.5 Tires" },
  { match: ["26.5", "26.5 tires", "26.5r25"], label: "26.5 Tires" },
  { match: ["29.5", "29.5 tires", "29.5r25"], label: "29.5 Tires" },
  { match: ["radial tires"], label: "Radial Tires" },
  { match: ["foam filled", "foam-filled"], label: "Foam Filled Tires" },
  { match: ["solid tires"], label: "Solid Tires" },
  { match: ["good undercarriage"], label: "Good Undercarriage" },
  { match: ["new undercarriage"], label: "New Undercarriage" },
  { match: ["rubber tracks"], label: "Rubber Tracks" },
  { match: ["steel tracks"], label: "Steel Tracks" },
  { match: ["lgp", "low ground pressure"], label: "LGP" },

  { match: ["no def", "def deleted", "de-tier", "detier"], label: "No DEF" },
  { match: ["tier 3"], label: "Tier 3" },
  { match: ["tier 4 final"], label: "Tier 4 Final" },
  { match: ["fresh service", "recent service"], label: "Fresh Service" },
  { match: ["service records"], label: "Service Records" },
  { match: ["fleet maintained"], label: "Fleet Maintained" },
  { match: ["dealer maintained"], label: "Dealer Maintained" },
  { match: ["one owner"], label: "One Owner" },
  { match: ["municipal owned"], label: "Municipal Owned" },
  { match: ["low hours"], label: "Low Hours" },
  { match: ["new engine"], label: "New Engine" },
  { match: ["reman engine", "rebuilt engine"], label: "Rebuilt Engine" },

  { match: ["air brakes"], label: "Air Brakes" },
  { match: ["wet kit"], label: "Wet Kit" },
  { match: ["pto"], label: "PTO" },
  { match: ["air ride"], label: "Air Ride" },
  { match: ["lift axle", "drop axle"], label: "Lift Axle" },
  { match: ["hydraulic ramps"], label: "Hydraulic Ramps" },
  { match: ["detach", "detachable"], label: "Detachable Neck" },
  { match: ["generator"], label: "Generator" },
  { match: ["air compressor"], label: "Air Compressor" },
  { match: ["light tower"], label: "Light Tower" }
];

export default featureKeywords;
