const forkliftTelehandlerDnaKeywords = [
  /* -------------------- */
  /* MACHINE TYPE DNA */
  /* -------------------- */

  "STRAIGHT MAST",
  "INDUSTRIAL FORKLIFT",
  "WAREHOUSE FORKLIFT",
  "PNEUMATIC TIRE FORKLIFT",
  "CUSHION TIRE FORKLIFT",
  "ROUGH TERRAIN FORKLIFT",
  "TELEHANDLER",
  "STRAIGHT BOOM TELEHANDLER",
  "ROTATING TELEHANDLER",
  "REACH FORKLIFT",
  "HIGH REACH TELEHANDLER",
  "CONTAINER HANDLER",
  "EMPTY CONTAINER HANDLER",
  "HEAVY FORKLIFT",
  "SIDE LOADER",
  "ARTICULATED FORKLIFT",
  "COMBI LIFT",
  "TRUCK MOUNTED FORKLIFT",
  "PIGGYBACK FORKLIFT",
  "MOOFFETT",
  "COMPACT TELEHANDLER",
  "ELECTRIC FORKLIFT",
  "ORDER PICKER",
  "REACH TRUCK",
  "PALLET JACK",
  "STACKER",
  "TURRET TRUCK",
  "VERY NARROW AISLE",
  "VNA",
  "WALKIE STACKER",
  "RIDING PALLET JACK",
  "TOW TRACTOR",

  /* -------------------- */
  /* CHASSIS DNA */
  /* -------------------- */

  "RIGID FRAME",
  "ARTICULATED FRAME",
  "ROUGH TERRAIN CHASSIS",
  "INDUSTRIAL CHASSIS",
  "WAREHOUSE CHASSIS",
  "COMPACT CHASSIS",
  "LOW PROFILE CHASSIS",
  "HEAVY DUTY FRAME",
  "HIGH CAPACITY FRAME",
  "SIDE LOADER FRAME",
  "TRUCK MOUNT FRAME",
  "ROTATING UPPER",
  "ROTO CHASSIS",
  "SELF LEVELING CHASSIS",
  "FRAME LEVELING",
  "FRAME SWAY",
  "LEVELING FRAME",
  "NARROW AISLE CHASSIS",
  "CONTAINER HANDLER CHASSIS",

  /* -------------------- */
  /* MAST SYSTEM DNA */
  /* -------------------- */

  "STRAIGHT MAST",
  "SIMPLEX MAST",
  "DUPLEX MAST",
  "TRIPLEX MAST",
  "QUAD MAST",
  "FULL FREE LIFT",
  "LIMITED FREE LIFT",
  "FREE LIFT",
  "TWO STAGE MAST",
  "THREE STAGE MAST",
  "FOUR STAGE MAST",
  "HI VISIBILITY MAST",
  "LOW PROFILE MAST",
  "CONTAINER MAST",
  "HEAVY DUTY MAST",
  "WIDE VIEW MAST",
  "NARROW AISLE MAST",
  "TILTING MAST",
  "HYDRAULIC MAST",
  "MAST TILT",
  "MAST SIDE SHIFT",
  "MAST POSITIONER",
  "MAST LOWERING CONTROL",
  "MAST CUSHION",
  "MAST LOCK",

  /* -------------------- */
  /* BOOM SYSTEM DNA */
  /* -------------------- */

  "STRAIGHT BOOM",
  "FIXED BOOM",
  "TELESCOPIC BOOM",
  "ROTATING BOOM",
  "ROTO BOOM",
  "TELESCOPIC EXTENSION",
  "MULTI SECTION BOOM",
  "BOOM FLOAT",
  "BOOM SUSPENSION",
  "BOOM CYLINDERS",
  "BOOM SIDE SHIFT",
  "HEAVY LIFT BOOM",
  "HIGH REACH BOOM",
  "COMPACT BOOM",
  "LOW PROFILE BOOM",
  "ARTICULATING BOOM",
  "BOOM ANGLE SENSOR",
  "BOOM EXTENSION SENSOR",
  "BOOM LOCK",
  "BOOM DAMPING",

  /* -------------------- */
  /* REACH SYSTEM DNA */
  /* -------------------- */

  "REACH SYSTEM",
  "REACH TRUCK",
  "PANTOGRAPH REACH",
  "SCISSOR REACH",
  "DEEP REACH",
  "DOUBLE DEEP REACH",
  "TURRET REACH",
  "EXTENDING CARRIAGE",
  "MOVING MAST REACH",
  "REACH EXTENSION",
  "REACH CARRIAGE",
  "REACH FORK POSITIONER",

  /* -------------------- */
  /* FORK CARRIAGE DNA */
  /* -------------------- */

  "CARRIAGE",
  "STANDARD CARRIAGE",
  "WIDE CARRIAGE",
  "SIDE SHIFT",
  "FORK POSITIONER",
  "HYDRAULIC FORKS",
  "PALLET FORKS",
  "PIN TYPE FORKS",
  "HOOK TYPE FORKS",
  "FORK EXTENSIONS",
  "FORK SPREADER",
  "ROTATING CARRIAGE",
  "SWING CARRIAGE",
  "TILT CARRIAGE",
  "SIDESHIFT CARRIAGE",
  "INTEGRATED SIDESHIFT",
  "FORK LEVELING",
  "HYDRAULIC FORK POSITIONER",
  "ROTATOR",
  "PAPER ROLL CLAMP",
  "BALE CLAMP",
  "DRUM CLAMP",
  "PUSH PULL ATTACHMENT",
  "MULTI PALLET HANDLER",
  "LOAD BACKREST",
  "FORK LOCK",

  /* -------------------- */
  /* ATTACHMENT DNA */
  /* -------------------- */

  "QUICK ATTACH",
  "HYDRAULIC QUICK ATTACH",
  "CARRIAGE MOUNT",
  "PALLET FORKS",
  "JIB",
  "WINCH",
  "WORK PLATFORM READY",
  "PERSONNEL PLATFORM",
  "BUCKET ATTACHMENT",
  "SWEEPER ATTACHMENT",
  "LUMBER FORKS",
  "PIPE HANDLER",
  "TIRE HANDLER",
  "COIL RAM",
  "HINGED FORKS",
  "HOOK ATTACHMENT",
  "VACUUM LIFTER",
  "CONTAINER SPREADER",
  "EMPTY CONTAINER SPREADER",
  "TOP PICK SPREADER",
  "SIDE PICK SPREADER",
  "ROTATING ATTACHMENT",
  "AUXILIARY CARRIAGE",
  "MULTI FUNCTION ATTACHMENT",

  /* -------------------- */
  /* AUXILIARY HYDRAULIC DNA */
  /* -------------------- */

  "AUX HYDRAULICS",
  "AUXILIARY HYDRAULICS",
  "HIGH FLOW HYDRAULICS",
  "STANDARD FLOW HYDRAULICS",
  "LOW FLOW HYDRAULICS",
  "THIRD FUNCTION HYDRAULICS",
  "FOURTH FUNCTION HYDRAULICS",
  "MULTI FUNCTION HYDRAULICS",
  "AUXILIARY HOSE KIT",
  "HYDRAULIC QUICK COUPLERS",
  "ATTACHMENT HYDRAULICS",
  "BOOM AUXILIARY HYDRAULICS",
  "CARRIAGE AUXILIARY HYDRAULICS",
  "HYDRAULIC TOOL CIRCUIT",
  "CONTINUOUS FLOW",
  "FLOW CONTROL",
  "PRESSURE CONTROL",

  /* -------------------- */
  /* DRIVE SYSTEM DNA */
  /* -------------------- */

  "2WD",
  "4WD",
  "ALL WHEEL DRIVE",
  "HYDROSTATIC",
  "HYDROSTATIC DRIVE",
  "POWERSHIFT",
  "TORQUE CONVERTER",
  "DIRECT DRIVE",
  "ELECTRIC DRIVE",
  "AC DRIVE",
  "DC DRIVE",
  "DUAL DRIVE MOTORS",
  "TRAVEL DRIVE",
  "PLANETARY FINAL DRIVE",
  "TWO SPEED",
  "CREEP MODE",
  "INCHING PEDAL",
  "DIFFERENTIAL LOCK",
  "TRACTION CONTROL",

  /* -------------------- */
  /* STEERING DNA */
  /* -------------------- */

  "ALL WHEEL STEER",
  "CRAB STEER",
  "FRONT WHEEL STEER",
  "REAR WHEEL STEER",
  "COORDINATED STEER",
  "ARTICULATED STEERING",
  "HYDRAULIC STEERING",
  "POWER STEERING",
  "STEERING AXLE",
  "OSCILLATING AXLE",
  "SWAY CONTROL",
  "FRAME LEVELING",
  "SELF LEVELING",
  "AUTO LEVELING",

  /* -------------------- */
  /* TIRE DNA */
  /* -------------------- */

  "SOLID TIRES",
  "PNEUMATIC TIRES",
  "FOAM FILLED TIRES",
  "CUSHION TIRES",
  "INDUSTRIAL TIRES",
  "ROUGH TERRAIN TIRES",
  "NON MARKING TIRES",
  "DUAL TIRES",
  "WIDE TIRES",
  "NARROW TIRES",
  "FLOTATION TIRES",
  "TRACTION TIRES",
  "SMOOTH TIRES",
  "AIR FILLED TIRES",
  "POLY TIRES",
  "SUPER ELASTIC TIRES",

  /* -------------------- */
  /* OUTRIGGER / STABILIZER DNA */
  /* -------------------- */

  "OUTRIGGERS",
  "STABILIZERS",
  "HYDRAULIC OUTRIGGERS",
  "FRAME LEVELING",
  "SELF LEVELING",
  "LEVELING JACKS",
  "AUTO LEVELING",
  "SWAY CONTROL",
  "STABILIZER INTERLOCK",
  "OUTRIGGER POSITION SENSOR",
  "OUTRIGGER PADS",

  /* -------------------- */
  /* LIFT SYSTEM DNA */
  /* -------------------- */

  "FREE LIFT",
  "FULL FREE LIFT",
  "LIMITED FREE LIFT",
  "HIGH LIFT",
  "HIGH REACH",
  "LOAD BACKREST",
  "LIFT CYLINDERS",
  "MAST LIFT CYLINDERS",
  "BOOM LIFT CYLINDERS",
  "CUSHIONED LOWERING",
  "LOAD CUSHION",
  "RIDE CONTROL",
  "BOOM SUSPENSION",
  "MAST SUSPENSION",
  "LOAD STABILIZER",
  "LIFT LOCKOUT",
  "HEIGHT LIMITER",

  /* -------------------- */
  /* ROTATION DNA */
  /* -------------------- */

  "ROTATING UPPER",
  "360 DEGREE ROTATION",
  "CONTINUOUS ROTATION",
  "ROTO TELEHANDLER",
  "ROTATING CARRIAGE",
  "SWING CARRIAGE",
  "ROTATING ATTACHMENT",
  "ROTATION LOCK",
  "SWING MOTOR",
  "SWING DRIVE",
  "SWING BRAKE",
  "ROTARY MANIFOLD",

  /* -------------------- */
  /* HYDRAULIC SYSTEM DNA */
  /* -------------------- */

  "OPEN CENTER HYDRAULICS",
  "CLOSED CENTER HYDRAULICS",
  "LOAD SENSING HYDRAULICS",
  "PRESSURE COMPENSATED HYDRAULICS",
  "VARIABLE DISPLACEMENT PUMP",
  "PISTON PUMP",
  "GEAR PUMP",
  "HYDRAULIC COOLER",
  "HYDRAULIC FILTER",
  "ELECTROHYDRAULIC CONTROLS",
  "PROPORTIONAL HYDRAULICS",
  "AUXILIARY HYDRAULICS",
  "HYDRAULIC FLOW CONTROL",
  "HYDRAULIC PRESSURE CONTROL",
  "ATTACHMENT FLOW CONTROL",
  "BOOM HYDRAULICS",
  "CARRIAGE HYDRAULICS",

  /* -------------------- */
  /* CONTROL SYSTEM DNA */
  /* -------------------- */

  "JOYSTICK CONTROLS",
  "SINGLE JOYSTICK",
  "DUAL JOYSTICK",
  "PILOT CONTROLS",
  "ELECTROHYDRAULIC CONTROLS",
  "FINGERTIP CONTROLS",
  "PROPORTIONAL CONTROLS",
  "MULTIFUNCTION JOYSTICK",
  "STEERING COLUMN CONTROLS",
  "INCHING PEDAL",
  "DIRECTIONAL CONTROL LEVER",
  "TRANSMISSION INCHING",
  "SIDE SHIFT CONTROL",
  "FORK POSITIONER CONTROL",
  "LOAD SENSING CONTROLS",
  "DRIVE MODE SELECT",
  "WORK MODE SELECT",

  /* -------------------- */
  /* SUSPENSION DNA */
  /* -------------------- */

  "RIDE CONTROL",
  "BOOM SUSPENSION",
  "HYDRAULIC SUSPENSION",
  "OSCILLATING AXLE",
  "LOCKING AXLE",
  "FRAME LEVELING",
  "SWAY FRAME",
  "FLOATING AXLE",
  "AXLE SUSPENSION",
  "LOAD STABILIZATION",

  /* -------------------- */
  /* SAFETY / LOAD DNA */
  /* -------------------- */

  "LOAD MOMENT INDICATOR",
  "LMI",
  "LOAD SCALE",
  "LOAD WEIGHING SYSTEM",
  "LOAD CHART SYSTEM",
  "LOAD LIMITER",
  "OVERLOAD PROTECTION",
  "BOOM ANGLE SENSOR",
  "HEIGHT LIMITER",
  "REACH LIMITER",
  "ANTI TIP SYSTEM",
  "STABILITY CONTROL",
  "CAMERA SYSTEM",
  "REAR CAMERA",
  "360 CAMERA",
  "BACKUP ALARM",
  "OBJECT DETECTION",
  "PROXIMITY SENSOR",
  "SEAT BELT INTERLOCK",
  "OPERATOR PRESENCE SYSTEM",

  /* -------------------- */
  /* TELEMATICS / AUTOMATION DNA */
  /* -------------------- */

  "TELEMATICS",
  "REMOTE DIAGNOSTICS",
  "GPS TRACKING",
  "FLEET MANAGEMENT",
  "REMOTE MONITORING",
  "LOAD DATA LOGGING",
  "SERVICE MONITOR",
  "MACHINE MONITORING",
  "ACCESS CONTROL",
  "PIN CODE START",
  "KEYLESS START",
  "AUTO IDLE",
  "AUTO SHUTDOWN",
  "WORK ZONE LIMITING",
  "HEIGHT LIMIT CONTROL",
  "BOOM POSITION MEMORY",

  /* -------------------- */
  /* CAB / OPERATOR DNA */
  /* -------------------- */

  "OPEN ROPS",
  "ROPS",
  "FOPS",
  "C/H/A",
  "ENCLOSED CAB",
  "AIR CONDITIONED CAB",
  "HEATED CAB",
  "PRESSURIZED CAB",
  "LOW PROFILE CAB",
  "HIGH VISIBILITY CAB",
  "PANORAMIC CAB",
  "DELUXE CAB",
  "SUSPENSION SEAT",
  "AIR RIDE SEAT",
  "HEATED SEAT",
  "SWIVEL SEAT",
  "TILTING CAB",
  "CAB RISER",
  "CAB GUARDING",
  "LED LIGHTS",
  "HALOGEN LIGHTS",
  "WORK LIGHT PACKAGE",
  "BEACON",
  "WINDSHIELD GUARD",
  "ROOF WINDOW",

  /* -------------------- */
  /* POWERTRAIN DNA */
  /* -------------------- */

  "DIESEL",
  "LP GAS",
  "LPG",
  "GASOLINE",
  "DUAL FUEL",
  "ELECTRIC",
  "BATTERY ELECTRIC",
  "AC ELECTRIC",
  "DC ELECTRIC",
  "LITHIUM ION",
  "LEAD ACID BATTERY",
  "HYBRID POWERTRAIN",
  "TURBOCHARGED",
  "COMMON RAIL",
  "MECHANICAL INJECTION",
  "AUTO IDLE",
  "REVERSING FAN",
  "HIGH CAPACITY COOLING",
  "BLOCK HEATER",

  /* -------------------- */
  /* CONTAINER HANDLER DNA */
  /* -------------------- */

  "EMPTY CONTAINER HANDLER",
  "LADEN CONTAINER HANDLER",
  "TOP PICK CONTAINER HANDLER",
  "REACH STACKER",
  "SPREADER",
  "TOP LIFT SPREADER",
  "SIDE PICK SPREADER",
  "CONTAINER LOCKS",
  "TWIST LOCKS",
  "STACKING FRAME",
  "HIGH CAPACITY COUNTERWEIGHT",
  "HEAVY DUTY MAST",
  "CONTAINER ATTACHMENT",
  "STACKING ASSIST",

  /* -------------------- */
  /* SIDE LOADER DNA */
  /* -------------------- */

  "SIDE LOADER",
  "MULTI DIRECTIONAL FORKLIFT",
  "COMBI LIFT",
  "FOUR WAY STEERING",
  "SIDE SHIFT MAST",
  "SIDE LOAD CARRIAGE",
  "LONG LOAD HANDLER",
  "GUIDED AISLE MODE",
  "VNA SIDE LOADER",

  /* -------------------- */
  /* ROUGH TERRAIN DNA */
  /* -------------------- */

  "ROUGH TERRAIN FORKLIFT",
  "ROUGH TERRAIN PACKAGE",
  "HIGH GROUND CLEARANCE",
  "OFF ROAD AXLES",
  "ROUGH TERRAIN MAST",
  "PNEUMATIC ROUGH TERRAIN TIRES",
  "4WD",
  "FRAME LEVELING",
  "OSCILLATING AXLE",
  "ROUGH TERRAIN CAB",
  "OUTRIGGER PACKAGE",

  /* -------------------- */
  /* TRUCK MOUNTED DNA */
  /* -------------------- */

  "TRUCK MOUNTED FORKLIFT",
  "PIGGYBACK FORKLIFT",
  "TRUCK CARRIER MOUNT",
  "REAR MOUNTED FORKLIFT",
  "MOFFETT STYLE MOUNT",
  "THREE WHEEL FORKLIFT",
  "SIDE MOUNTED OPERATOR",
  "TRUCK MOUNT KIT",
  "TRUCK LOCKING SYSTEM",
  "MOUNTING FRAME",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-DEF",
  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4",
  "TIER 4 FINAL",
  "T4F",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
   "EGR",
  "SCR",
  "DEF",
  "DPF"
];

export default forkliftDnaKeywords;
