const motorGradersTaxonomy = [

  // KOMATSU
  { make: "KOMATSU", model: "GD300" },
  { make: "KOMATSU", model: "GD405" },
  { make: "KOMATSU", model: "GD505" },
  { make: "KOMATSU", model: "GD511" },
  { make: "KOMATSU", model: "GD521" },
  { make: "KOMATSU", model: "GD530" },
  { make: "KOMATSU", model: "GD535" },
  { make: "KOMATSU", model: "GD555" },
  { make: "KOMATSU", model: "GD605" },
  { make: "KOMATSU", model: "GD623" },
  { make: "KOMATSU", model: "GD633" },
  { make: "KOMATSU", model: "GD650" },
  { make: "KOMATSU", model: "GD655" },
  { make: "KOMATSU", model: "GD661" },
  { make: "KOMATSU", model: "GD675" },
  { make: "KOMATSU", model: "GD705" },
  { make: "KOMATSU", model: "GD825" },

  // DEERE
  { make: "DEERE", model: "670A" },
  { make: "DEERE", model: "670B" },
  { make: "DEERE", model: "670CH" },
  { make: "DEERE", model: "670D" },
  { make: "DEERE", model: "670G" },
  { make: "DEERE", model: "670GP" },
  { make: "DEERE", model: "672G" },
  { make: "DEERE", model: "672GP" },
  { make: "DEERE", model: "770A" },
  { make: "DEERE", model: "770B" },
  { make: "DEERE", model: "770BH" },
  { make: "DEERE", model: "770CH" },
  { make: "DEERE", model: "770D" },
  { make: "DEERE", model: "770G" },
  { make: "DEERE", model: "770GP" },
  { make: "DEERE", model: "772G" },
  { make: "DEERE", model: "772GP" },
  { make: "DEERE", model: "870A" },
  { make: "DEERE", model: "870B" },
  { make: "DEERE", model: "870C" },
  { make: "DEERE", model: "870D" },
  { make: "DEERE", model: "870G" },
  { make: "DEERE", model: "870GP" },
  { make: "DEERE", model: "872G" },
  { make: "DEERE", model: "872GP" },

  // CATERPILLAR
  { make: "CATERPILLAR", model: "12G" },
  { make: "CATERPILLAR", model: "12H" },
  { make: "CATERPILLAR", model: "12M" },
  { make: "CATERPILLAR", model: "120G" },
  { make: "CATERPILLAR", model: "120H" },
  { make: "CATERPILLAR", model: "120K" },
  { make: "CATERPILLAR", model: "120M" },
  { make: "CATERPILLAR", model: "130G" },
  { make: "CATERPILLAR", model: "135H" },
  { make: "CATERPILLAR", model: "140G" },
  { make: "CATERPILLAR", model: "140H" },
  { make: "CATERPILLAR", model: "140K" },
  { make: "CATERPILLAR", model: "140M" },
  { make: "CATERPILLAR", model: "140M2" },
  { make: "CATERPILLAR", model: "140M3" },
  { make: "CATERPILLAR", model: "160H" },
  { make: "CATERPILLAR", model: "160K" },
  { make: "CATERPILLAR", model: "160M" },
  { make: "CATERPILLAR", model: "160M2" },
  { make: "CATERPILLAR", model: "160M3" },

  // XCMG
  { make: "XCMG", model: "GR100" },
  { make: "XCMG", model: "GR135" },
  { make: "XCMG", model: "GR165" },
  { make: "XCMG", model: "GR180" },
  { make: "XCMG", model: "GR190" },
  { make: "XCMG", model: "GR200" },
  { make: "XCMG", model: "GR215" },
  { make: "XCMG", model: "GR220" },
  { make: "XCMG", model: "GR240" },
  { make: "XCMG", model: "GR260" },
  { make: "XCMG", model: "GR280" },
  { make: "XCMG", model: "GR300" },

  // VOLVO
  { make: "VOLVO", model: "G720" },
  { make: "VOLVO", model: "G730" },
  { make: "VOLVO", model: "G740" },
  { make: "VOLVO", model: "G746" },
  { make: "VOLVO", model: "G780" },
  { make: "VOLVO", model: "G930" },
  { make: "VOLVO", model: "G940" },
  { make: "VOLVO", model: "G946" },
  { make: "VOLVO", model: "G960" },
  { make: "VOLVO", model: "G970" },
  { make: "VOLVO", model: "G976" },
  { make: "VOLVO", model: "G990" },

  // CHAMPION
  { make: "CHAMPION", model: "710" },
  { make: "CHAMPION", model: "715" },
  { make: "CHAMPION", model: "720" },
  { make: "CHAMPION", model: "730" },
  { make: "CHAMPION", model: "740" },
  { make: "CHAMPION", model: "750" },
  { make: "CHAMPION", model: "760" },
  { make: "CHAMPION", model: "780" },
  { make: "CHAMPION", model: "C70" },
  { make: "CHAMPION", model: "C80" },

    // UHI
  { make: "UHI", model: "MG130" },
  { make: "UHI", model: "MG160" },
  { make: "UHI", model: "MG180" },

  // SANY
  { make: "SANY", model: "SMG200" },
  { make: "SANY", model: "SMG220" },
  { make: "SANY", model: "SMG260" },

  // LEEBOY
  { make: "LEEBOY", model: "685B" },
  { make: "LEEBOY", model: "685C" },
  { make: "LEEBOY", model: "685D" },
  { make: "LEEBOY", model: "785" },
  { make: "LEEBOY", model: "8510" },

  // SEM
  { make: "SEM", model: "915" },
  { make: "SEM", model: "919" },
  { make: "SEM", model: "921" },
  { make: "SEM", model: "922 AWD" },

  // CASE
  { make: "CASE", model: "845" },
  { make: "CASE", model: "865" },
  { make: "CASE", model: "885" },
  { make: "CASE", model: "836C" },
  { make: "CASE", model: "856C" },
  { make: "CASE", model: "865B" },
  { make: "CASE", model: "885B" },

  // NEW HOLLAND
  { make: "NEW HOLLAND", model: "F106.6" },
  { make: "NEW HOLLAND", model: "F156.6" },
  { make: "NEW HOLLAND", model: "F156.7" },
  { make: "NEW HOLLAND", model: "F156.8" },
  { make: "NEW HOLLAND", model: "F206.6" },
  { make: "NEW HOLLAND", model: "F255" },

  // NORAM
  { make: "NORAM", model: "65E" },
  { make: "NORAM", model: "65ET" },
  { make: "NORAM", model: "75E" },
  { make: "NORAM", model: "75ET" },

  // GALION
  { make: "GALION", model: "118" },
  { make: "GALION", model: "125" },
  { make: "GALION", model: "130" },
  { make: "GALION", model: "150" },
  { make: "GALION", model: "503" },
  { make: "GALION", model: "503A" },
  { make: "GALION", model: "503B" },
  { make: "GALION", model: "T500" },
  { make: "GALION", model: "T600" },

];

export default motorGradersTaxonomy;
