const motorGraderDnaKeywords = [
  /* -------------------- */
  /* MOLDBOARD DNA */
  /* -------------------- */

  "MOLDBOARD",
  "STANDARD MOLDBOARD",
  "HEAVY DUTY MOLDBOARD",
  "HIGH PROFILE MOLDBOARD",
  "LOW PROFILE MOLDBOARD",
  "12 FT MOLDBOARD",
  "13 FT MOLDBOARD",
  "14 FT MOLDBOARD",
  "16 FT MOLDBOARD",
  "HYDRAULIC MOLDBOARD SLIDE",
  "MANUAL MOLDBOARD SLIDE",
  "MOLDBOARD TIP",
  "HYDRAULIC MOLDBOARD TIP",
  "MOLDBOARD PITCH",
  "MOLDBOARD LIFT CYLINDERS",
  "MOLDBOARD SIDESHIFT",
  "POWER SIDESHIFT",
  "BLADE LIFT ACCUMULATORS",
  "CUTTING EDGE",
  "BOLT-ON CUTTING EDGE",
  "CURVED CUTTING EDGE",
  "FLAT CUTTING EDGE",
  "SCARIFIER CUTTING EDGE",
  "END BITS",

  /* -------------------- */
  /* CIRCLE DNA */
  /* -------------------- */

  "CIRCLE",
  "DRAWBAR CIRCLE MOLDBOARD",
  "CIRCLE DRIVE",
  "CIRCLE SLIP CLUTCH",
  "CIRCLE FRICTION CLUTCH",
  "CIRCLE GEAR",
  "CIRCLE PINION",
  "SEALED CIRCLE",
  "TOP-ADJUST CIRCLE",
  "CIRCLE WEAR STRIPS",
  "CIRCLE SHOES",
  "CIRCLE GUIDES",
  "CIRCLE LOCK",
  "HYDRAULIC CIRCLE DRIVE",
  "MECHANICAL CIRCLE DRIVE",
  "LOW MAINTENANCE CIRCLE",
  "CENTERSHIFT LOCK",
  "CIRCLE SIDESHIFT",
  "DRAWBAR SIDESHIFT",
  "HYDRAULIC DRAWBAR SIDESHIFT",

  /* -------------------- */
  /* FRONT AXLE DNA */
  /* -------------------- */

  "FRONT AXLE",
  "OSCILLATING FRONT AXLE",
  "LEANING FRONT WHEELS",
  "FRONT WHEEL LEAN",
  "HYDRAULIC WHEEL LEAN",
  "MECHANICAL WHEEL LEAN",
  "FRONT AXLE OSCILLATION",
  "FRONT AXLE LOCK",
  "FRONT FENDERS",
  "FRONT AXLE GUARDS",
  "FRONT STEERING CYLINDERS",
  "HEAVY DUTY FRONT AXLE",

  /* -------------------- */
  /* FRONT DRIVE DNA */
  /* -------------------- */

  "ALL WHEEL DRIVE",
  "AWD",
  "FRONT WHEEL DRIVE",
  "HYDROSTATIC FRONT WHEEL DRIVE",
  "MECHANICAL FRONT WHEEL DRIVE",
  "VARIABLE FRONT WHEEL DRIVE",
  "ON-DEMAND AWD",
  "AWD CREEP MODE",
  "AWD MODE",
  "FRONT DRIVE MOTORS",
  "FRONT HUB MOTORS",
  "FRONT DRIVE DISCONNECT",
  "NO AWD",

  /* -------------------- */
  /* TANDEM DRIVE DNA */
  /* -------------------- */

  "TANDEM DRIVE",
  "TANDEM AXLES",
  "OSCILLATING TANDEMS",
  "HEAVY DUTY TANDEMS",
  "CHAIN DRIVE TANDEMS",
  "GEAR DRIVE TANDEMS",
  "TANDEM CASE",
  "TANDEM CHAINS",
  "TANDEM SPROCKETS",
  "TANDEM WALKING BEAM",
  "TANDEM FLOAT",
  "STANDARD TANDEMS",
  "LONG WHEELBASE TANDEMS",
  "SHORT WHEELBASE TANDEMS",

  /* -------------------- */
  /* DIFFERENTIAL DNA */
  /* -------------------- */

  "LIMITED SLIP DIFFERENTIAL",
  "LOCKING DIFFERENTIAL",
  "DIFFERENTIAL LOCK",
  "AUTOMATIC DIFFERENTIAL LOCK",
  "MANUAL DIFFERENTIAL LOCK",
  "NO-SPIN DIFFERENTIAL",
  "PLANETARY FINAL DRIVES",
  "INBOARD PLANETARY FINAL DRIVES",
  "OUTBOARD PLANETARY FINAL DRIVES",
  "FINAL DRIVE",
  "REAR AXLE",
  "HEAVY DUTY REAR AXLE",

  /* -------------------- */
  /* TRANSMISSION DNA */
  /* -------------------- */

  "POWERSHIFT TRANSMISSION",
  "DIRECT DRIVE TRANSMISSION",
  "HYDROSTATIC TRANSMISSION",
  "TORQUE CONVERTER TRANSMISSION",
  "AUTOMATIC TRANSMISSION",
  "AUTOSHIFT TRANSMISSION",
  "ELECTRONIC POWERSHIFT",
  "COUNTERSHAFT TRANSMISSION",
  "FULL POWERSHIFT",
  "MANUAL TRANSMISSION",
  "CREEPER GEAR",
  "INCHING PEDAL",
  "TRANSMISSION MODULATION",
  "FINGER TIP SHIFT",
  "FNR SHUTTLE",
  "FORWARD REVERSE SHUTTLE",

  /* -------------------- */
  /* STEERING DNA */
  /* -------------------- */

  "STEERING WHEEL CONTROLS",
  "JOYSTICK CONTROLS",
  "DUAL JOYSTICK CONTROLS",
  "LEVER CONTROLS",
  "PILOT CONTROLS",
  "HYDRAULIC STEERING",
  "ORBITAL STEERING",
  "SECONDARY STEERING",
  "ARTICULATION STEERING",
  "FRONT WHEEL STEERING",
  "COMBINATION STEERING",
  "STEERABLE FRONT AXLE",
  "STEERING CYLINDERS",
  "STEERING WHEEL AND LEVER CONTROLS",

  /* -------------------- */
  /* ARTICULATION DNA */
  /* -------------------- */

  "ARTICULATED FRAME",
  "CENTER ARTICULATION",
  "FRAME ARTICULATION",
  "ARTICULATION LOCK",
  "ARTICULATION JOINT",
  "ARTICULATION CYLINDERS",
  "REAR FRAME",
  "FRONT FRAME",
  "BOX SECTION FRAME",
  "HEAVY DUTY FRAME",
  "WELDED FRAME",
  "BOLTED FRAME",
  "FRAME LOCK BAR",

  /* -------------------- */
  /* GRADE CONTROL DNA */
  /* -------------------- */

  "GRADE CONTROL READY",
  "2D GRADE CONTROL",
  "3D GRADE CONTROL",
  "GPS GRADE CONTROL",
  "GNSS GRADE CONTROL",
  "LASER GRADE CONTROL",
  "SONIC GRADE CONTROL",
  "CROSS SLOPE CONTROL",
  "AUTOMATIC CROSS SLOPE",
  "SLOPE CONTROL",
  "DUAL MAST GRADE CONTROL",
  "SINGLE MAST GRADE CONTROL",
  "MASTLESS GRADE CONTROL",
  "TOPCON GRADE CONTROL",
  "TRIMBLE GRADE CONTROL",
  "LEICA GRADE CONTROL",
  "CAT GRADE CONTROL",
  "JOHN DEERE SMARTGRADE",
  "SMARTGRADE",
  "GRADE PRO",
  "GRADE PRO CONTROLS",
  "ACCUGRADE READY",
  "AUTOMATIC BLADE CONTROL",
  "BLADE SLOPE SENSOR",
  "ROTATION SENSOR",
  "MOLDBOARD SLOPE SENSOR",
  "CROSS SLOPE SENSOR",

  /* -------------------- */
  /* HYDRAULIC DNA */
  /* -------------------- */

  "LOAD SENSING HYDRAULICS",
  "PRESSURE COMPENSATED HYDRAULICS",
  "CLOSED CENTER HYDRAULICS",
  "OPEN CENTER HYDRAULICS",
  "ELECTROHYDRAULIC CONTROLS",
  "PILOT HYDRAULICS",
  "MECHANICAL HYDRAULIC CONTROLS",
  "AUXILIARY HYDRAULICS",
  "FRONT AUXILIARY HYDRAULICS",
  "REAR AUXILIARY HYDRAULICS",
  "MID-MOUNT HYDRAULICS",
  "RIPPER HYDRAULICS",
  "SCARIFIER HYDRAULICS",
  "SNOW WING HYDRAULICS",
  "FRONT LIFT GROUP HYDRAULICS",
  "HYDRAULIC LOCK VALVES",
  "FLOAT FUNCTION",
  "BLADE FLOAT",
  "HYDRAULIC ACCUMULATORS",

  /* -------------------- */
  /* SCARIFIER DNA */
  /* -------------------- */

  "MID-MOUNT SCARIFIER",
  "FRONT SCARIFIER",
  "REAR SCARIFIER",
  "V-TYPE SCARIFIER",
  "STRAIGHT SCARIFIER",
  "SCARIFIER SHANKS",
  "SCARIFIER TEETH",
  "HYDRAULIC SCARIFIER",
  "MANUAL SCARIFIER",
  "SCARIFIER LIFT CYLINDER",
  "SCARIFIER BAR",
  "SCARIFIER GROUP",

  /* -------------------- */
  /* RIPPER DNA */
  /* -------------------- */

  "REAR RIPPER",
  "MULTI-SHANK RIPPER",
  "PARALLELOGRAM RIPPER",
  "HYDRAULIC RIPPER",
  "RIPPER SCARIFIER",
  "RIPPER SHANKS",
  "RIPPER TEETH",
  "RIPPER MOUNTING GROUP",
  "RIPPER LIFT CYLINDER",
  "REAR RIPPER HYDRAULICS",
  "NO RIPPER",

  /* -------------------- */
  /* FRONT ATTACHMENT DNA */
  /* -------------------- */

  "FRONT PUSH BLOCK",
  "FRONT COUNTERWEIGHT",
  "FRONT LIFT GROUP",
  "FRONT DOZER BLADE",
  "FRONT BLADE",
  "FRONT SCARIFIER",
  "FRONT SNOW PLOW",
  "FRONT V-PLOW",
  "FRONT HYDRAULIC LIFT",
  "FRONT ATTACHMENT MOUNT",
  "FRONT QUICK ATTACH",
  "PUSH PLATE",
  "FRONT BUMPER",
  "FRONT DRAWBAR",

  /* -------------------- */
  /* SNOW WING DNA */
  /* -------------------- */

  "SNOW WING",
  "SIDE WING",
  "RIGHT HAND SNOW WING",
  "LEFT HAND SNOW WING",
  "HYDRAULIC SNOW WING",
  "MID-MOUNT WING",
  "REAR-MOUNT WING",
  "HIGH BENCHING WING",
  "SNOW WING POST",
  "SNOW WING MAST",
  "WING PUSH ARM",
  "WING BRACE",
  "WING LIFT CYLINDER",
  "WING TOE CYLINDER",
  "WING HEEL CYLINDER",
  "ONE WAY SNOW PLOW",
  "V-PLOW",
  "REVERSIBLE SNOW PLOW",

  /* -------------------- */
  /* CAB DNA */
  /* -------------------- */

  "ROPS CAB",
  "EROPS CAB",
  "OPEN ROPS",
  "CANOPY",
  "LOW PROFILE CAB",
  "HIGH VISIBILITY CAB",
  "AIR CONDITIONED CAB",
  "HEATED CAB",
  "DEFROSTER",
  "SUSPENSION SEAT",
  "AIR RIDE SEAT",
  "JOYSTICK CAB",
  "LEVER CONTROL CAB",
  "STEERING WHEEL CAB",
  "CAB RISER",
  "CAB PRE-CLEANER",
  "PRESSURIZED CAB",

  /* -------------------- */
  /* GUARDING DNA */
  /* -------------------- */

  "ENGINE SIDE SHIELDS",
  "BELLY GUARDS",
  "TRANSMISSION GUARDS",
  "TANDEM GUARDS",
  "AXLE GUARDS",
  "FRONT AXLE GUARDS",
  "HYDRAULIC LINE GUARDS",
  "LIGHT GUARDS",
  "WINDOW GUARDS",
  "SCREEN GUARDS",
  "RADIATOR GUARD",
  "REAR GUARDING",
  "FENDER PACKAGE",

  /* -------------------- */
  /* TIRE / WHEEL DNA */
  /* -------------------- */

  "13.00-24 TIRES",
  "14.00-24 TIRES",
  "15.5-25 TIRES",
  "17.5-25 TIRES",
  "20.5-25 TIRES",
  "BIAS TIRES",
  "RADIAL TIRES",
  "G2 TIRES",
  "L2 TIRES",
  "L3 TIRES",
  "RIB FRONT TIRES",
  "TRACTION TIRES",
  "SNOW TIRES",
  "CHAINS",
  "FRONT TIRE CHAINS",
  "REAR TIRE CHAINS",
  "SINGLE PIECE WHEELS",
  "MULTI PIECE WHEELS",
  "WHEEL WEIGHTS",
  "FRONT WHEEL WEIGHTS",
  "REAR WHEEL WEIGHTS",

  /* -------------------- */
  /* BRAKE DNA */
  /* -------------------- */

  "HYDRAULIC BRAKES",
  "AIR BRAKES",
  "OIL DISC BRAKES",
  "WET DISC BRAKES",
  "DRY DISC BRAKES",
  "SERVICE BRAKES",
  "PARK BRAKE",
  "SECONDARY BRAKES",

  /* -------------------- */
  /* LIGHTING / ELECTRICAL DNA */
  /* -------------------- */

  "HALOGEN WORK LIGHTS",
  "LED WORK LIGHTS",
  "HID WORK LIGHTS",
  "FRONT WORK LIGHTS",
  "REAR WORK LIGHTS",
  "MOLDBOARD LIGHTS",
  "SNOW WING LIGHTS",
  "BEACON",
  "STROBE LIGHT",
  "BACKUP ALARM",
  "BATTERY DISCONNECT",
  "COLD START PACKAGE",
  "BLOCK HEATER",
  "ETHER START",

  /* -------------------- */
  /* AUTOMATION DNA */
  /* -------------------- */

  "AUTOMATIC BLADE CONTROL",
  "AUTOMATIC ARTICULATION",
  "AUTO SHIFT",
  "AUTO DIFFERENTIAL LOCK",
  "AUTO CROSS SLOPE",
  "RETURN TO STRAIGHT",
  "MACHINE CONTROL READY",
  "INTEGRATED MACHINE CONTROL",
  "REMOTE DIAGNOSTICS",
  "TELEMATICS",
  "PRODUCT LINK",
  "JD LINK",
  "KOMTRAX",
  "CARETRACK",
  "GRADE CONTROL JOYSTICKS",
  "ELECTRONIC IMPLEMENT CONTROLS",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4 FINAL",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF"
];

export default motorGraderDnaKeywords;
