const scraperDnaKeywords = [
  /* -------------------- */
  /* SCRAPER TYPE DNA */
  /* -------------------- */

  "MOTOR SCRAPER",
  "WHEEL TRACTOR SCRAPER",
  "PULL SCRAPER",
  "PULL TYPE SCRAPER",
  "DIRECT MOUNT SCRAPER",
  "DOLLY WHEEL SCRAPER",
  "OPEN BOWL SCRAPER",
  "ELEVATING SCRAPER",
  "PADDLE WHEEL SCRAPER",
  "EJECTOR SCRAPER",
  "FORCE EJECTION SCRAPER",
  "CARRY ALL SCRAPER",
  "CARRY-ALL SCRAPER",
  "TANDEM ENGINE SCRAPER",
  "SINGLE ENGINE SCRAPER",
  "PUSH PULL SCRAPER",
  "AUGER SCRAPER",
  "ADT SCRAPER",
  "SCRAPER TRAIN",
  "TANDEM SCRAPER",
  "DOUBLE SCRAPER",
  "BOX SCRAPER",
  "LAND LEVELER",
  "EJECTION PAN",

  /* -------------------- */
  /* BOWL SYSTEM DNA */
  /* -------------------- */

  "OPEN BOWL",
  "ELEVATING BOWL",
  "EJECTOR BOWL",
  "AUGER BOWL",
  "CARRY ALL BOWL",
  "HEAPED BOWL",
  "LIGHT MATERIAL BOWL",
  "COAL BOWL",
  "HIGH CAPACITY BOWL",
  "LOW PROFILE BOWL",
  "WIDE BOWL",
  "NARROW BOWL",
  "BOWL EXTENSIONS",
  "SIDEBOARD EXTENSIONS",
  "SPILL GUARDS",
  "BOWL LINERS",
  "WEAR LINERS",
  "BOWL FLOOR",
  "BOWL SIDEWALLS",
  "BOWL APRON",
  "BOWL LIFT CYLINDERS",
  "BOWL FLOAT",
  "BOWL CUSHION",
  "BOWL DEPTH CONTROL",
  "BOWL DRAFT CONTROL",
  "CUTTING EDGE",
  "BOLT ON CUTTING EDGE",
  "REVERSIBLE CUTTING EDGE",
  "ROUTER BITS",
  "SIDE CUTTERS",
  "WEAR PLATES",

  /* -------------------- */
  /* APRON SYSTEM DNA */
  /* -------------------- */

  "APRON",
  "OPEN APRON",
  "HYDRAULIC APRON",
  "MECHANICAL APRON",
  "APR0N CYLINDERS",
  "APRON LIFT CYLINDERS",
  "APRON LOCK",
  "APRON EJECTOR LINKAGE",
  "APRONLESS BOWL",
  "FRONT APRON",
  "HEAVY DUTY APRON",
  "APRON WEAR PLATES",

  /* -------------------- */
  /* EJECTOR SYSTEM DNA */
  /* -------------------- */

  "EJECTOR",
  "FORCE EJECTION",
  "EJECTOR WALL",
  "PUSH PLATE EJECTOR",
  "ROLL OUT EJECTOR",
  "EJECTOR GATE",
  "EJECTOR FLOOR",
  "EJECTOR CYLINDER",
  "EJECTOR HYDRAULICS",
  "EJECTOR CHAIN",
  "EJECTOR ROLLERS",
  "EJECTOR TRACKS",
  "REAR EJECTOR",
  "FORWARD EJECTOR",
  "HYDRAULIC EJECTOR",

  /* -------------------- */
  /* ELEVATOR SYSTEM DNA */
  /* -------------------- */

  "ELEVATOR",
  "ELEVATING SYSTEM",
  "PADDLE WHEEL",
  "PADDLE ELEVATOR",
  "ELEVATOR CHAIN",
  "ELEVATOR FLIGHTS",
  "ELEVATOR PADDLES",
  "ELEVATOR MOTOR",
  "HYDRAULIC ELEVATOR",
  "MECHANICAL ELEVATOR",
  "ELEVATOR DRIVE",
  "ELEVATOR SPEED CONTROL",
  "REVERSIBLE ELEVATOR",
  "ELEVATOR FRAME",
  "ELEVATOR GUARDS",
  "AUGER ELEVATOR",
  "AUGER ASSIST",
  "LOADING AUGER",

  /* -------------------- */
  /* PUSH-PULL SYSTEM DNA */
  /* -------------------- */

  "PUSH PULL",
  "PUSH-PULL",
  "PUSH PULL HITCH",
  "PUSH PULL BAIL",
  "PUSH PULL BLOCK",
  "PUSH BLOCK",
  "PUSH PLATE",
  "PUSH PULL HOOK",
  "REAR PUSH BLOCK",
  "FRONT PUSH BLOCK",
  "PUSH LOADING READY",
  "PUSH BAR",
  "BAIL HOOK",
  "PUSH PULL COUPLER",
  "PUSH PULL CUSHION HITCH",
  "PUSH PULL PACKAGE",

  /* -------------------- */
  /* HITCH / DRAWBAR DNA */
  /* -------------------- */

  "DRAWBAR HITCH",
  "BAIL HITCH",
  "GOOSENECK HITCH",
  "DIRECT MOUNT HITCH",
  "DOLLY WHEEL HITCH",
  "PULL SCRAPER HITCH",
  "TRACTOR HITCH",
  "ARTICULATING HITCH",
  "SWIVEL HITCH",
  "BALL HITCH",
  "PINTLE HITCH",
  "SCRAPER HITCH",
  "QUICK HITCH",
  "HYDRAULIC HITCH",
  "CUSHION HITCH",
  "HITCH CYLINDERS",
  "HITCH ACCUMULATORS",
  "HITCH LOCK",
  "REAR HITCH",
  "FRONT HITCH",

  /* -------------------- */
  /* TRACTOR / POWER UNIT DNA */
  /* -------------------- */

  "SCRAPER TRACTOR",
  "WHEEL TRACTOR",
  "TRACTOR SCRAPER",
  "ARTICULATED TRACTOR",
  "2WD TRACTOR",
  "4WD TRACTOR",
  "ALL WHEEL DRIVE TRACTOR",
  "ADT TRACTOR",
  "RUBBER TRACK TRACTOR",
  "TRACK TRACTOR PULL SCRAPER",
  "DOZER PULLED SCRAPER",
  "AG TRACTOR PULL SCRAPER",
  "DIRECT MOUNT TRACTOR",
  "OEM SCRAPER TRACTOR",
  "SCRAPER SPECIAL TRACTOR",

  /* -------------------- */
  /* ENGINE CONFIGURATION DNA */
  /* -------------------- */

  "SINGLE ENGINE",
  "TANDEM ENGINE",
  "TWIN ENGINE",
  "DUAL ENGINE",
  "FRONT ENGINE",
  "REAR ENGINE",
  "PUSHER ENGINE",
  "DIESEL ENGINE",
  "TURBOCHARGED",
  "INTERCOOLED",
  "COMMON RAIL",
  "MECHANICAL INJECTION",
  "ELECTRONIC ENGINE",
  "ENGINE RETARDER",
  "AUTO IDLE",
  "ENGINE SHUTDOWN TIMER",
  "BLOCK HEATER",
  "COLD WEATHER PACKAGE",

  /* -------------------- */
  /* TRANSMISSION / DRIVE DNA */
  /* -------------------- */

  "POWERSHIFT",
  "DIRECT DRIVE",
  "TORQUE CONVERTER",
  "LOCKUP TORQUE CONVERTER",
  "PLANETARY POWERSHIFT",
  "AUTOMATIC TRANSMISSION",
  "MANUAL TRANSMISSION",
  "ELECTRONIC TRANSMISSION",
  "POWER TRAIN",
  "2WD",
  "4WD",
  "ALL WHEEL DRIVE",
  "FRONT WHEEL DRIVE",
  "REAR WHEEL DRIVE",
  "TANDEM DRIVE",
  "FINAL DRIVES",
  "PLANETARY FINAL DRIVES",
  "DIFFERENTIAL LOCK",
  "TRACTION CONTROL",
  "AUTO TRACTION CONTROL",
  "WHEEL SLIP CONTROL",
  "DIFF LOCK",

  /* -------------------- */
  /* AXLE / TIRE DNA */
  /* -------------------- */

  "RADIAL TIRES",
  "BIAS TIRES",
  "FLOTATION TIRES",
  "EARTHMOVER TIRES",
  "SCRAPER TIRES",
  "LOW GROUND PRESSURE TIRES",
  "LGP TIRES",
  "WIDE BASE TIRES",
  "DUAL TIRES",
  "SINGLE TIRES",
  "EJECTOR SCRAPER TIRES",
  "DOLLY WHEELS",
  "DOLLY AXLE",
  "WHEEL SPINDLES",
  "OSCILLATING AXLE",
  "REAR AXLE",
  "FRONT AXLE",
  "HEAVY DUTY AXLE",
  "PLANETARY AXLES",
  "WHEEL BEARINGS",
  "TIRE SCRAPERS",

  /* -------------------- */
  /* STEERING / ARTICULATION DNA */
  /* -------------------- */

  "ARTICULATED STEERING",
  "HYDRAULIC STEERING",
  "CENTER ARTICULATION",
  "ARTICULATION HITCH",
  "STEERING CYLINDERS",
  "SCRAPER STEERING",
  "TRACTOR STEERING",
  "REAR STEER",
  "DOLLY STEER",
  "FOLLOW STEER",
  "PIVOT STEERING",
  "LOAD COMPENSATED STEERING",

  /* -------------------- */
  /* HYDRAULIC SYSTEM DNA */
  /* -------------------- */

  "OPEN CENTER HYDRAULICS",
  "CLOSED CENTER HYDRAULICS",
  "LOAD SENSING HYDRAULICS",
  "PRESSURE COMPENSATED HYDRAULICS",
  "BOWL HYDRAULICS",
  "APRON HYDRAULICS",
  "EJECTOR HYDRAULICS",
  "ELEVATOR HYDRAULICS",
  "HITCH HYDRAULICS",
  "STEERING HYDRAULICS",
  "AUX HYDRAULICS",
  "AUXILIARY HYDRAULICS",
  "HIGH FLOW HYDRAULICS",
  "SCRAPER HYDRAULICS",
  "TRACTOR HYDRAULICS",
  "REMOTE HYDRAULICS",
  "HYDRAULIC QUICK COUPLERS",
  "HYDRAULIC ACCUMULATORS",
  "HYDRAULIC COOLER",
  "ELECTROHYDRAULIC CONTROLS",

  /* -------------------- */
  /* CUSHION HITCH / RIDE DNA */
  /* -------------------- */

  "CUSHION HITCH",
  "HYDRAULIC CUSHION HITCH",
  "CUSHION HITCH ACCUMULATORS",
  "CUSHION HITCH CYLINDERS",
  "RIDE CONTROL",
  "SCRAPER RIDE CONTROL",
  "HITCH SUSPENSION",
  "LOAD CUSHION",
  "DRAFT CUSHION",
  "BOWL CUSHION",
  "SUSPENDED HITCH",
  "OSCILLATING HITCH",

  /* -------------------- */
  /* GRADE CONTROL / LASER DNA */
  /* -------------------- */

  "GRADE CONTROL",
  "LASER READY",
  "GPS READY",
  "GNSS READY",
  "2D GRADE CONTROL",
  "3D GRADE CONTROL",
  "MACHINE CONTROL READY",
  "AUTOLOAD",
  "LOAD ASSIST",
  "AUTO LOAD",
  "AUTOMATIC LOAD ASSIST",
  "CUT DEPTH CONTROL",
  "BOWL DEPTH CONTROL",
  "LASER RECEIVER MAST",
  "GRADE SENSOR",
  "SLOPE SENSOR",
  "SCRAPER CONTROL SYSTEM",
  "TRIMBLE READY",
  "TOPCON READY",
  "JOHN DEERE I-GRADE",
  "I-GRADE READY",

  /* -------------------- */
  /* CAB / OPERATOR DNA */
  /* -------------------- */

  "OPEN ROPS",
  "ROPS",
  "FOPS",
  "C/H/A",
  "CAB",
  "ENCLOSED CAB",
  "AIR CONDITIONED CAB",
  "HEATED CAB",
  "PRESSURIZED CAB",
  "SUSPENSION SEAT",
  "AIR RIDE SEAT",
  "JOYSTICK CONTROLS",
  "ELECTROHYDRAULIC CONTROLS",
  "SCRAPER CONTROLS",
  "BOWL CONTROL LEVER",
  "APRON CONTROL",
  "EJECTOR CONTROL",
  "ELEVATOR CONTROL",
  "MULTIFUNCTION DISPLAY",
  "PAYLOAD DISPLAY",
  "REAR CAMERA",
  "BOWL CAMERA",
  "WORK LIGHTS",
  "LED LIGHTS",
  "BEACON",

  /* -------------------- */
  /* PUSH BLOCK / REAR SYSTEM DNA */
  /* -------------------- */

  "PUSH BLOCK",
  "PUSH PLATE",
  "REAR PUSH BLOCK",
  "REAR PUSH PLATE",
  "FRONT PUSH BLOCK",
  "PUSH LOADING BLOCK",
  "REAR BUMPER",
  "SCRAPER REAR FRAME",
  "REAR HITCH",
  "REAR DRAWBAR",
  "REAR TOW EYE",
  "REAR COUNTERWEIGHT",
  "REAR RADIATOR GUARD",
  "REAR ENGINE GUARD",
  "PUSH PULL REAR SYSTEM",

  /* -------------------- */
  /* PULL SCRAPER TRAIN DNA */
  /* -------------------- */

  "SCRAPER TRAIN",
  "TANDEM SCRAPER TRAIN",
  "DOUBLE SCRAPER TRAIN",
  "TWIN SCRAPER TRAIN",
  "TANDEM PULL SCRAPER",
  "DUAL PULL SCRAPER",
  "FRONT SCRAPER",
  "REAR SCRAPER",
  "LEAD SCRAPER",
  "TRAIL SCRAPER",
  "TRAIN HITCH",
  "REAR SCRAPER HITCH",
  "PULL SCRAPER TANDEM HITCH",
  "SCRAPER TRAIN HYDRAULICS",
  "TRAIN CONTROL VALVE",
  "TRAIN HARNESS",
  "ADT SCRAPER TRAIN",

  /* -------------------- */
  /* PULL SCRAPER BODY DNA */
  /* -------------------- */

  "PULL SCRAPER",
  "DIRECT MOUNT",
  "DOLLY WHEEL",
  "DOLLY SCRAPER",
  "CARRY ALL",
  "PULL PAN",
  "EJECTOR PAN",
  "OPEN FRONT PAN",
  "HYDRAULIC EJECTOR PAN",
  "PADDLE EJECTOR PAN",
  "FORCE EJECTION PAN",
  "HIGH CAPACITY PAN",
  "LOW PROFILE PAN",
  "WIDE PAN",
  "NARROW PAN",
  "SCRAPER PAN",
  "BOLT TOGETHER PAN",
  "RIGID PAN",
  "FLEX PAN",
  "FOLDING PAN",
  "HINGED PAN",

  /* -------------------- */
  /* SUPPORT / SAFETY DNA */
  /* -------------------- */

  "AUTO LUBE",
  "CENTRALIZED GREASING",
  "FIRE SUPPRESSION",
  "BATTERY DISCONNECT",
  "MASTER DISCONNECT",
  "BACKUP ALARM",
  "TRAVEL ALARM",
  "BOWL SAFETY LOCK",
  "EJECTOR SAFETY LOCK",
  "APRON SAFETY LOCK",
  "SERVICE LOCKS",
  "TOWING EYE",
  "TRANSPORT LOCKS",
  "SAFETY CHAINS",
  "SMV SIGN",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-DEF",
  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4",
  "TIER 4 FINAL",
  "T4F",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF",
  "DEF DELETE"
];

export default scraperDnaKeywords;
