// SCRAPERS

const scraperTaxonomy = [
 // CATERPILLAR
{ make: "CATERPILLAR", model: "40" },
{ make: "CATERPILLAR", model: "60" },
{ make: "CATERPILLAR", model: "70" },
{ make: "CATERPILLAR", model: "80" },
{ make: "CATERPILLAR", model: "463" },
{ make: "CATERPILLAR", model: "613" },
{ make: "CATERPILLAR", model: "613A" },
{ make: "CATERPILLAR", model: "613B" },
{ make: "CATERPILLAR", model: "613C" },
{ make: "CATERPILLAR", model: "613C II" },
{ make: "CATERPILLAR", model: "613G" },
{ make: "CATERPILLAR", model: "613G II" },
{ make: "CATERPILLAR", model: "615" },
{ make: "CATERPILLAR", model: "615C" },
{ make: "CATERPILLAR", model: "615C II" },
{ make: "CATERPILLAR", model: "615C II WHEEL TRACTOR-SCRAPER" },
{ make: "CATERPILLAR", model: "621" },
{ make: "CATERPILLAR", model: "621B" },
{ make: "CATERPILLAR", model: "621E" },
{ make: "CATERPILLAR", model: "621F" },
{ make: "CATERPILLAR", model: "621G" },
{ make: "CATERPILLAR", model: "621H" },
{ make: "CATERPILLAR", model: "621K" },
{ make: "CATERPILLAR", model: "621K OEM" },
{ make: "CATERPILLAR", model: "623" },
{ make: "CATERPILLAR", model: "623B" },
{ make: "CATERPILLAR", model: "623E" },
{ make: "CATERPILLAR", model: "623F" },
{ make: "CATERPILLAR", model: "623F II" },
{ make: "CATERPILLAR", model: "623G" },
{ make: "CATERPILLAR", model: "623H" },
{ make: "CATERPILLAR", model: "623K" },
{ make: "CATERPILLAR", model: "623K OEM" },
{ make: "CATERPILLAR", model: "627" },
{ make: "CATERPILLAR", model: "627B" },
{ make: "CATERPILLAR", model: "627E" },
{ make: "CATERPILLAR", model: "627F" },
{ make: "CATERPILLAR", model: "627G" },
{ make: "CATERPILLAR", model: "627H" },
{ make: "CATERPILLAR", model: "627K" },
{ make: "CATERPILLAR", model: "627K OEM" },
{ make: "CATERPILLAR", model: "631" },
{ make: "CATERPILLAR", model: "631B" },
{ make: "CATERPILLAR", model: "631C" },
{ make: "CATERPILLAR", model: "631D" },
{ make: "CATERPILLAR", model: "631E" },
{ make: "CATERPILLAR", model: "631E II" },
{ make: "CATERPILLAR", model: "631F" },
{ make: "CATERPILLAR", model: "631G" },
{ make: "CATERPILLAR", model: "631K" },
{ make: "CATERPILLAR", model: "631K OEM" },
{ make: "CATERPILLAR", model: "633" },
{ make: "CATERPILLAR", model: "633C" },
{ make: "CATERPILLAR", model: "633D" },
{ make: "CATERPILLAR", model: "637" },
{ make: "CATERPILLAR", model: "637C" },
{ make: "CATERPILLAR", model: "637D" },
{ make: "CATERPILLAR", model: "637E" },
{ make: "CATERPILLAR", model: "637G" },
{ make: "CATERPILLAR", model: "637K" },
{ make: "CATERPILLAR", model: "637K OEM" },
{ make: "CATERPILLAR", model: "641" },
{ make: "CATERPILLAR", model: "641B" },
{ make: "CATERPILLAR", model: "651" },
{ make: "CATERPILLAR", model: "651B" },
{ make: "CATERPILLAR", model: "651E" },
{ make: "CATERPILLAR", model: "651G" },
{ make: "CATERPILLAR", model: "657" },
{ make: "CATERPILLAR", model: "657B" },
{ make: "CATERPILLAR", model: "657E" },
{ make: "CATERPILLAR", model: "657G" },
{ make: "CATERPILLAR", model: "657G TWIN ENGINE" },
{ make: "CATERPILLAR", model: "657G AUGER" },
{ make: "CATERPILLAR", model: "657K" },
{ make: "CATERPILLAR", model: "DW20" },
{ make: "CATERPILLAR", model: "DW21" },
{ make: "CATERPILLAR", model: "DW21G" },
{ make: "CATERPILLAR", model: "DW10" },
{ make: "CATERPILLAR", model: "OTHER" },

  // K-TEC
{ make: "K-TEC", model: "1030" },
{ make: "K-TEC", model: "1228" },
{ make: "K-TEC", model: "1228 TRAIN" },
{ make: "K-TEC", model: "1228 ADT" },
{ make: "K-TEC", model: "1230" },
{ make: "K-TEC", model: "1233" },
{ make: "K-TEC", model: "1233 ADT" },
{ make: "K-TEC", model: "1233 TRAIN" },
{ make: "K-TEC", model: "1236" },
{ make: "K-TEC", model: "1237" },
{ make: "K-TEC", model: "1237 ADT" },
{ make: "K-TEC", model: "1243" },
{ make: "K-TEC", model: "1243 ADT" },
{ make: "K-TEC", model: "1254" },
{ make: "K-TEC", model: "1263" },
{ make: "K-TEC", model: "1613" },
{ make: "K-TEC", model: "2016 FLEX" },
{ make: "K-TEC", model: "2822" },
{ make: "K-TEC", model: "3100" },
{ make: "K-TEC", model: "RL12" },
{ make: "K-TEC", model: "OTHER" },
  
 // ASHLAND
{ make: "ASHLAND", model: "35" },
{ make: "ASHLAND", model: "50" },
{ make: "ASHLAND", model: "61" },
{ make: "ASHLAND", model: "140" },
{ make: "ASHLAND", model: "155" },
{ make: "ASHLAND", model: "175" },
{ make: "ASHLAND", model: "220" },
{ make: "ASHLAND", model: "500" },
{ make: "ASHLAND", model: "950" },
{ make: "ASHLAND", model: "1410" },
{ make: "ASHLAND", model: "1509" },
{ make: "ASHLAND", model: "1812" },
{ make: "ASHLAND", model: "2012" },
{ make: "ASHLAND", model: "2114" },
{ make: "ASHLAND", model: "2311" },
{ make: "ASHLAND", model: "2411" },
{ make: "ASHLAND", model: "2811" },
{ make: "ASHLAND", model: "3013" },
{ make: "ASHLAND", model: "3250" },
{ make: "ASHLAND", model: "3413" },
{ make: "ASHLAND", model: "B300" },
{ make: "ASHLAND", model: "CS18" },
{ make: "ASHLAND", model: "I-100" },
{ make: "ASHLAND", model: "I-130" },
{ make: "ASHLAND", model: "I-140" },
{ make: "ASHLAND", model: "I-155" },
{ make: "ASHLAND", model: "I-180" },
{ make: "ASHLAND", model: "I-900" },
{ make: "ASHLAND", model: "I-950" },
{ make: "ASHLAND", model: "OTHER" },

  // DEERE
{ make: "DEERE", model: "650" },
{ make: "DEERE", model: "700" },
{ make: "DEERE", model: "760" },
{ make: "DEERE", model: "760A" },
{ make: "DEERE", model: "762" },
{ make: "DEERE", model: "762A" },
{ make: "DEERE", model: "762B" },
{ make: "DEERE", model: "762B II" },
{ make: "DEERE", model: "840" },
{ make: "DEERE", model: "860" },
{ make: "DEERE", model: "860A" },
{ make: "DEERE", model: "862" },
{ make: "DEERE", model: "862B" },
{ make: "DEERE", model: "862B II" },
{ make: "DEERE", model: "1312" },
{ make: "DEERE", model: "1312C" },
{ make: "DEERE", model: "1510" },
{ make: "DEERE", model: "1510C" },
{ make: "DEERE", model: "1510DC" },
{ make: "DEERE", model: "1512" },
{ make: "DEERE", model: "1612" },
{ make: "DEERE", model: "1612DE" },
{ make: "DEERE", model: "1810" },
{ make: "DEERE", model: "1810E" },
{ make: "DEERE", model: "1812" },
{ make: "DEERE", model: "1812C" },
{ make: "DEERE", model: "1812DC" },
{ make: "DEERE", model: "1814" },
{ make: "DEERE", model: "1814C" },
{ make: "DEERE", model: "2010" },
{ make: "DEERE", model: "2010DE" },
{ make: "DEERE", model: "2112" },
{ make: "DEERE", model: "2112C" },
{ make: "DEERE", model: "2112DC" },
{ make: "DEERE", model: "2112E" },
{ make: "DEERE", model: "2412" },
{ make: "DEERE", model: "2412DE" },
{ make: "DEERE", model: "2412E" },
{ make: "DEERE", model: "OTHER" },
  
  // REYNOLDS
{ make: "REYNOLDS", model: "6C" },
{ make: "REYNOLDS", model: "8C" },
{ make: "REYNOLDS", model: "8TF" },
{ make: "REYNOLDS", model: "9C" },
{ make: "REYNOLDS", model: "9CB" },
{ make: "REYNOLDS", model: "10C" },
{ make: "REYNOLDS", model: "10P" },
{ make: "REYNOLDS", model: "12C" },
{ make: "REYNOLDS", model: "12C10" },
{ make: "REYNOLDS", model: "12C12" },
{ make: "REYNOLDS", model: "12CFBR" },
{ make: "REYNOLDS", model: "12CR" },
{ make: "REYNOLDS", model: "12P" },
{ make: "REYNOLDS", model: "12.5" },
{ make: "REYNOLDS", model: "13P" },
{ make: "REYNOLDS", model: "14C" },
{ make: "REYNOLDS", model: "14C10 LGP" },
{ make: "REYNOLDS", model: "14E" },
{ make: "REYNOLDS", model: "15C" },
{ make: "REYNOLDS", model: "15.5" },
{ make: "REYNOLDS", model: "16C" },
{ make: "REYNOLDS", model: "16E" },
{ make: "REYNOLDS", model: "17C" },
{ make: "REYNOLDS", model: "17E" },
{ make: "REYNOLDS", model: "18C" },
{ make: "REYNOLDS", model: "20E" },
{ make: "REYNOLDS", model: "484" },
{ make: "REYNOLDS", model: "672A" },
{ make: "REYNOLDS", model: "C14E" },
{ make: "REYNOLDS", model: "LSE12" },
{ make: "REYNOLDS", model: "OTHER" },

  // ROME
{ make: "ROME", model: "14C" },
{ make: "ROME", model: "18E14.5" },
{ make: "ROME", model: "AG12" },
{ make: "ROME", model: "C14" },
{ make: "ROME", model: "GK12" },
{ make: "ROME", model: "GK16" },
{ make: "ROME", model: "GKCSP10" },
{ make: "ROME", model: "GKCSP16" },
{ make: "ROME", model: "PG12" },
{ make: "ROME", model: "PG16" },
{ make: "ROME", model: "R56H" },
{ make: "ROME", model: "RAFS20" },
{ make: "ROME", model: "RAFS20EP" },
{ make: "ROME", model: "RAFS24" },
{ make: "ROME", model: "RAFS24EP" },
{ make: "ROME", model: "RALS16" },
{ make: "ROME", model: "RALSE16" },
{ make: "ROME", model: "RC150" },
{ make: "ROME", model: "RLS10" },
{ make: "ROME", model: "RLS12" },
{ make: "ROME", model: "RLS14" },
{ make: "ROME", model: "RLS16" },
{ make: "ROME", model: "RLS18" },
{ make: "ROME", model: "RP16E14" },
{ make: "ROME", model: "RP17.5E14" },
{ make: "ROME", model: "RP18" },
{ make: "ROME", model: "RP90" },
{ make: "ROME", model: "RP120" },
{ make: "ROME", model: "RP150" },
{ make: "ROME", model: "RP175" },
{ make: "ROME", model: "RP180" },
{ make: "ROME", model: "RP190" },
{ make: "ROME", model: "RP212HDE" },
{ make: "ROME", model: "RP21E15" },
{ make: "ROME", model: "RP2412HDE" },
{ make: "ROME", model: "RP2812HDE" },
{ make: "ROME", model: "P3612HDE" },
{ make: "ROME", model: "OTHER" },

  // ORTHMAN
{ make: "ORTHMAN", model: "PS" },
{ make: "ORTHMAN", model: "SM50" },
{ make: "ORTHMAN", model: "SM850" },
{ make: "ORTHMAN", model: "SOILMOVER 10" },
{ make: "ORTHMAN", model: "SOILMOVER 10RO" },
{ make: "ORTHMAN", model: "SOILMOVER 15RO" },
{ make: "ORTHMAN", model: "SOILMOVER 21R" },
{ make: "ORTHMAN", model: "SOILMOVER 25R" },
{ make: "ORTHMAN", model: "SOILMOVER 30RF" },
{ make: "ORTHMAN", model: "SOILMOVER 50RF" },
{ make: "ORTHMAN", model: "SOILMOVER 101S" },
{ make: "ORTHMAN", model: "SOILMOVER 425RF" },
{ make: "ORTHMAN", model: "SOILMOVER 625RF" },
{ make: "ORTHMAN", model: "SOILMOVER 700" },
{ make: "ORTHMAN", model: "SOILMOVER 700RF" },
{ make: "ORTHMAN", model: "SOILMOVER FE775" },
{ make: "ORTHMAN", model: "SOILMOVER 7521" },
{ make: "ORTHMAN", model: "SOILMOVER 7522" },
{ make: "ORTHMAN", model: "SOILMOVER 8120" },
{ make: "ORTHMAN", model: "SOILMOVER FX775" },
{ make: "ORTHMAN", model: "SOILMOVER SM75" },
{ make: "ORTHMAN", model: "SOILMOVER SM850RF" },
{ make: "ORTHMAN", model: "225-RF" },
{ make: "ORTHMAN", model: "OTHER" },

 // MOBILE TRACK SOLUTIONS
{ make: "MOBILE TRACK SOLUTIONS", model: "23-28" },
{ make: "MOBILE TRACK SOLUTIONS", model: "28-33" },
{ make: "MOBILE TRACK SOLUTIONS", model: "MT-14" },
{ make: "MOBILE TRACK SOLUTIONS", model: "MT-23" },
{ make: "MOBILE TRACK SOLUTIONS", model: "MT-28" },
{ make: "MOBILE TRACK SOLUTIONS", model: "MT-30" },
{ make: "MOBILE TRACK SOLUTIONS", model: "MT-33" },
{ make: "MOBILE TRACK SOLUTIONS", model: "MT-35" },
{ make: "MOBILE TRACK SOLUTIONS", model: "MT-42" },
{ make: "MOBILE TRACK SOLUTIONS", model: "OTHER" },

  // ROWSE
{ make: "ROWSE", model: "500" },
{ make: "ROWSE", model: "700" },
{ make: "ROWSE", model: "3002" },
{ make: "ROWSE", model: "5002" },
{ make: "ROWSE", model: "5004" },
{ make: "ROWSE", model: "7002" },
{ make: "ROWSE", model: "7004" },
{ make: "ROWSE", model: "OTHER" },

  // TOREQ
{ make: "TOREQ", model: "6000" },
{ make: "TOREQ", model: "9000" },
{ make: "TOREQ", model: "10000" },
{ make: "TOREQ", model: "11500" },
{ make: "TOREQ", model: "13000" },
{ make: "TOREQ", model: "14000" },
{ make: "TOREQ", model: "16000" },
{ make: "TOREQ", model: "18000" },
{ make: "TOREQ", model: "OTHER" },

  // BIG DOG
{ make: "BIG DOG", model: "8 YD" },
{ make: "BIG DOG", model: "S6.5" },
{ make: "BIG DOG", model: "S8" },
{ make: "BIG DOG", model: "S10" },
{ make: "BIG DOG", model: "S11" },
{ make: "BIG DOG", model: "OTHER" },

  // DURABILT
{ make: "DURABILT", model: "DP60" },
{ make: "DURABILT", model: "DP84" },
{ make: "DURABILT", model: "OTHER" },

  // EVERSMAN
{ make: "EVERSMAN", model: "2S" },
{ make: "EVERSMAN", model: "2SD" },
{ make: "EVERSMAN", model: "25D" },
{ make: "EVERSMAN", model: "410" },
{ make: "EVERSMAN", model: "600" },
{ make: "EVERSMAN", model: "650" },
{ make: "EVERSMAN", model: "700" },
{ make: "EVERSMAN", model: "750" },
{ make: "EVERSMAN", model: "OTHER" },

  // GARFIELD
{ make: "GARFIELD", model: "550" },
{ make: "GARFIELD", model: "850" },
{ make: "GARFIELD", model: "950" },
{ make: "GARFIELD", model: "1200" },
{ make: "GARFIELD", model: "1350" },
{ make: "GARFIELD", model: "GCA550" },
{ make: "GARFIELD", model: "GCA550HC" },
{ make: "GARFIELD", model: "GCA950HC" },
{ make: "GARFIELD", model: "GCA1350HC" },
{ make: "GARFIELD", model: "GGB1600" },
{ make: "GARFIELD", model: "GHDST16" },
{ make: "GARFIELD", model: "OTHER" },

  // HOLCOMB
{ make: "HOLCOMB", model: "800" },
{ make: "HOLCOMB", model: "1000" },
{ make: "HOLCOMB", model: "1200" },
{ make: "HOLCOMB", model: "1400" },
{ make: "HOLCOMB", model: "1600" },
{ make: "HOLCOMB", model: "OTHER" },

  // HUMDINGER
{ make: "HUMDINGER", model: "622E" },
{ make: "HUMDINGER", model: "628E" },
{ make: "HUMDINGER", model: "631E" },
{ make: "HUMDINGER", model: "631E ADT" },
{ make: "HUMDINGER", model: "H619" },
{ make: "HUMDINGER", model: "H620G" },
{ make: "HUMDINGER", model: "OTHER" },

  // ICON
{ make: "ICON", model: "17C" },
{ make: "ICON", model: "18D" },
{ make: "ICON", model: "19C" },
{ make: "ICON", model: "20E" },
{ make: "ICON", model: "418" },
{ make: "ICON", model: "721" },
{ make: "ICON", model: "821" },
{ make: "ICON", model: "AG11" },
{ make: "ICON", model: "AG13" },
{ make: "ICON", model: "CEM17" },
{ make: "ICON", model: "OTHER" },

  // LANDOLL ICON
{ make: "LANDOLL ICON", model: "1230" },
{ make: "LANDOLL ICON", model: "1432" },
{ make: "LANDOLL ICON", model: "1632" },
{ make: "LANDOLL ICON", model: "1642" },
{ make: "LANDOLL ICON", model: "AG10" },
{ make: "LANDOLL ICON", model: "OTHER" },

  // NOBLE
{ make: "NOBLE", model: "417" },
{ make: "NOBLE", model: "OTHER" },

  // TEREX
{ make: "TEREX", model: "S11" },
{ make: "TEREX", model: "S24" },
{ make: "TEREX", model: "TS14" },
{ make: "TEREX", model: "TS14B" },
{ make: "TEREX", model: "TS14C" },
{ make: "TEREX", model: "TS14G" },
{ make: "TEREX", model: "TS14HP" },
{ make: "TEREX", model: "TS18" },
{ make: "TEREX", model: "TS24" },
{ make: "TEREX", model: "TS46C" },
{ make: "TEREX", model: "OTHER" },

];

export default scraperTaxonomy;
