const skidSteerCtlDnaKeywords = [
  /* -------------------- */
  /* MACHINE TYPE DNA */
  /* -------------------- */

  "SKID STEER",
  "SKID STEER LOADER",
  "COMPACT TRACK LOADER",
  "CTL",
  "MULTI TERRAIN LOADER",
  "MTL",
  "TRACK LOADER",
  "WHEELED SKID STEER",
  "TRACKED SKID STEER",
  "MINI SKID STEER",
  "STAND ON LOADER",
  "COMPACT UTILITY LOADER",
  "WALK BEHIND LOADER",
  "ARTICULATED SKID STEER",
  "DOZER LOADER",
  "COMPACT DOZER LOADER",
  "ELECTRIC SKID STEER",
  "ELECTRIC CTL",

  /* -------------------- */
  /* CHASSIS DNA */
  /* -------------------- */

  "RIGID FRAME",
  "COMPACT CHASSIS",
  "WIDE FRAME",
  "NARROW FRAME",
  "LOW PROFILE CHASSIS",
  "RADIAL LIFT CHASSIS",
  "VERTICAL LIFT CHASSIS",
  "TRACK CHASSIS",
  "WHEEL CHASSIS",
  "MINI LOADER CHASSIS",
  "STAND ON PLATFORM",
  "WALK BEHIND PLATFORM",
  "DOZER LOADER CHASSIS",
  "HEAVY DUTY FRAME",
  "REINFORCED FRAME",
  "COUNTERWEIGHT READY",
  "REAR COUNTERWEIGHT",
  "SIDE COUNTERWEIGHTS",
  "ADDITIONAL COUNTERWEIGHTS",

  /* -------------------- */
  /* LIFT PATH DNA */
  /* -------------------- */

  "RADIAL LIFT",
  "VERTICAL LIFT",
  "R SERIES LIFT",
  "V SERIES LIFT",
  "SUPER BOOM",
  "LIFT LINKAGE",
  "LOADER LINKAGE",
  "PARALLEL LIFT",
  "SELF LEVELING",
  "HYDRAULIC SELF LEVELING",
  "MECHANICAL SELF LEVELING",
  "RETURN TO DIG",
  "BUCKET POSITIONING",
  "LIFT ARM FLOAT",
  "LOADER FLOAT",
  "HIGH LIFT",
  "EXTENDED REACH LIFT",

  /* -------------------- */
  /* LOADER ARM DNA */
  /* -------------------- */

  "LOADER ARMS",
  "RADIAL LIFT ARMS",
  "VERTICAL LIFT ARMS",
  "HEAVY DUTY LOADER ARMS",
  "REINFORCED LOADER ARMS",
  "BOX SECTION LOADER ARMS",
  "LOW PROFILE LOADER ARMS",
  "LIFT ARM SUPPORT",
  "LIFT ARM CYLINDERS",
  "BUCKET TILT CYLINDERS",
  "CYLINDER GUARDS",
  "LOADER ARM GUARDS",
  "BOOM LOCK",
  "LIFT ARM LOCK",

  /* -------------------- */
  /* TRACK SYSTEM DNA */
  /* -------------------- */

  "RUBBER TRACK",
  "STEEL TRACK",
  "DEDICATED TRACK SYSTEM",
  "MULTI TERRAIN TRACK SYSTEM",
  "SUSPENDED TRACK SYSTEM",
  "RIGID TRACK SYSTEM",
  "TORSION SUSPENSION TRACK SYSTEM",
  "POSI-TRACK",
  "ASV POSI-TRACK",
  "CAT MTL UNDERCARRIAGE",
  "CTL UNDERCARRIAGE",
  "WIDE TRACK",
  "NARROW TRACK",
  "LOW GROUND PRESSURE TRACK",
  "LGP TRACK",
  "HIGH FLOATATION TRACK",
  "BAR TREAD TRACK",
  "BLOCK TREAD TRACK",
  "TURF TRACK",
  "SMOOTH TRACK",
  "ZIG ZAG TRACK",
  "C PATTERN TRACK",
  "TRACK BELT",
  "TRACK LUGS",
  "TRACK ROLLERS",
  "BOGIE WHEELS",
  "IDLER WHEELS",
  "DRIVE SPROCKETS",
  "TRACK TENSIONER",
  "HYDRAULIC TRACK TENSIONER",
  "GREASE TRACK TENSIONER",
  "OVER THE TIRE TRACKS",
  "OTT TRACKS",
  "STEEL OVER THE TIRE TRACKS",
  "RUBBER OVER THE TIRE TRACKS",

  /* -------------------- */
  /* TIRE DNA */
  /* -------------------- */

  "PNEUMATIC TIRES",
  "SOLID TIRES",
  "FOAM FILLED TIRES",
  "AIR FILLED TIRES",
  "NON MARKING TIRES",
  "TURF TIRES",
  "INDUSTRIAL TIRES",
  "FLOTATION TIRES",
  "SEVERE DUTY TIRES",
  "HEAVY DUTY TIRES",
  "SKID STEER TIRES",
  "BAR LUG TIRES",
  "SNOW TIRES",
  "SMOOTH TIRES",
  "WIDE TIRES",
  "NARROW TIRES",
  "TIRE CHAINS",
  "WHEEL SPACERS",
  "BEADLOCK WHEELS",
  "STEEL WHEELS",

  /* -------------------- */
  /* HYDRAULIC FLOW DNA */
  /* -------------------- */

  "STANDARD FLOW",
  "HIGH FLOW",
  "ENHANCED HIGH FLOW",
  "HIGH FLOW XPS",
  "XPS",
  "XHP",
  "HIGH FLOW XHP",
  "SUPER FLOW",
  "FLOW PLUS",
  "FLOW+",
  "HIGH CAPACITY HYDRAULICS",
  "HIGH PERFORMANCE HYDRAULICS",
  "HIGH OUTPUT HYDRAULICS",
  "LOW FLOW",
  "VARIABLE FLOW",
  "HYDRAULIC FLOW CONTROL",
  "HYDRAULIC PRESSURE CONTROL",
  "ATTACHMENT FLOW CONTROL",
  "ATTACHMENT PRESSURE CONTROL",
  "CASE DRAIN",
  "MOTOR RETURN",
  "HYDRAULIC COOLER",
  "AUXILIARY HYDRAULIC COOLER",

  /* -------------------- */
  /* AUXILIARY HYDRAULIC DNA */
  /* -------------------- */

  "AUX HYDRAULICS",
  "AUXILIARY HYDRAULICS",
  "FRONT AUXILIARY HYDRAULICS",
  "REAR AUXILIARY HYDRAULICS",
  "PRIMARY AUXILIARY HYDRAULICS",
  "SECONDARY AUX",
  "SECONDARY AUXILIARY HYDRAULICS",
  "THIRD FUNCTION HYDRAULICS",
  "FOURTH FUNCTION HYDRAULICS",
  "MULTI FUNCTION HYDRAULICS",
  "ONE WAY HYDRAULICS",
  "TWO WAY HYDRAULICS",
  "BIDIRECTIONAL HYDRAULICS",
  "CONTINUOUS FLOW",
  "AUXILIARY DETENT",
  "AUXILIARY ELECTRIC CONTROL",
  "HYDRAULIC QUICK COUPLERS",
  "FLAT FACE COUPLERS",
  "PRESSURE RELEASE COUPLERS",
  "14 PIN AUXILIARY CONTROL",
  "7 PIN AUXILIARY CONTROL",
  "8 PIN AUXILIARY CONTROL",

  /* -------------------- */
  /* COUPLER DNA */
  /* -------------------- */

  "MANUAL COUPLER",
  "HYDRAULIC COUPLER",
  "POWER COUPLER",
  "QUICK ATTACH",
  "UNIVERSAL QUICK ATTACH",
  "SKID STEER QUICK ATTACH",
  "BOBCAT QUICK ATTACH",
  "CAT QUICK COUPLER",
  "JCB QUICKHITCH",
  "HYDRAULIC QUICK ATTACH",
  "MANUAL QUICK ATTACH",
  "POWER BOB-TACH",
  "BOB-TACH",
  "MECHANICAL BOB-TACH",
  "COUPLER LOCK",
  "COUPLER SAFETY LOCK",
  "ATTACHMENT LOCK",
  "PIN ON ATTACHMENT",

  /* -------------------- */
  /* CONTROL SYSTEM DNA */
  /* -------------------- */

  "PILOT CONTROLS",
  "JOYSTICK CONTROLS",
  "SJC",
  "SELECTABLE JOYSTICK CONTROLS",
  "EH CONTROLS",
  "ELECTROHYDRAULIC CONTROLS",
  "ISO CONTROLS",
  "H PATTERN",
  "HAND FOOT CONTROLS",
  "MECHANICAL HAND FOOT CONTROLS",
  "DUAL LEVER CONTROLS",
  "T BAR CONTROLS",
  "CASE H PATTERN CONTROLS",
  "ADVANCED CONTROL SYSTEM",
  "ACS",
  "SELECTABLE CONTROLS",
  "PATTERN SELECTOR",
  "CONTROL PATTERN CHANGER",
  "JOYSTICK ROLLER CONTROLS",
  "PROPORTIONAL AUXILIARY CONTROLS",
  "FINGERTIP CONTROLS",
  "FOOT THROTTLE",
  "HAND THROTTLE",

  /* -------------------- */
  /* DRIVE SYSTEM DNA */
  /* -------------------- */

  "HYDROSTATIC DRIVE",
  "HYDRAULIC DRIVE",
  "MECHANICAL DRIVE",
  "DIRECT DRIVE",
  "CHAIN CASE DRIVE",
  "CHAIN DRIVE",
  "BELT DRIVE",
  "WHEEL DRIVE",
  "TRACK DRIVE",
  "DUAL PATH HYDROSTATIC",
  "TWO SPEED",
  "SINGLE SPEED",
  "TWO SPEED TRAVEL",
  "HIGH SPEED TRAVEL",
  "CREEP MODE",
  "SPEED MANAGEMENT",
  "DRIVE RESPONSE",
  "AUTO SHIFT",
  "DRIVE MOTORS",
  "FINAL DRIVES",
  "PLANETARY FINAL DRIVES",
  "AXLE DRIVE",
  "SKID STEER DRIVE",

  /* -------------------- */
  /* TRACTION DNA */
  /* -------------------- */

  "TRACTION CONTROL",
  "AUTOMATIC TRACTION CONTROL",
  "ANTI SLIP CONTROL",
  "LIMITED SLIP",
  "DIFFERENTIAL LOCK",
  "TRACK SLIP CONTROL",
  "TORQUE MANAGEMENT",
  "POWER MANAGEMENT",
  "LOAD MANAGEMENT",
  "ENGINE ANTI STALL",
  "HYDROSTATIC TRACTION CONTROL",

  /* -------------------- */
  /* RIDE CONTROL DNA */
  /* -------------------- */

  "RIDE CONTROL",
  "LOADER RIDE CONTROL",
  "BOOM RIDE CONTROL",
  "HYDRAULIC RIDE CONTROL",
  "ACCUMULATOR RIDE CONTROL",
  "AUTO RIDE CONTROL",
  "RIDE CONTROL ACCUMULATOR",
  "LOAD CUSHION",
  "BOOM SUSPENSION",

  /* -------------------- */
  /* SUSPENSION DNA */
  /* -------------------- */

  "TORSION SUSPENSION",
  "SUSPENDED UNDERCARRIAGE",
  "RIGID UNDERCARRIAGE",
  "BOGIE SUSPENSION",
  "INDEPENDENT TORSION AXLES",
  "ROLLER SUSPENSION",
  "FLOATING ROLLER SYSTEM",
  "SUSPENDED TRACK FRAME",
  "RUBBER TORSION AXLE",
  "SPRING SUSPENSION",
  "AXLE SUSPENSION",

  /* -------------------- */
  /* BUCKET DNA */
  /* -------------------- */

  "GENERAL PURPOSE BUCKET",
  "GP BUCKET",
  "LOW PROFILE BUCKET",
  "HEAVY DUTY BUCKET",
  "LIGHT MATERIAL BUCKET",
  "HIGH CAPACITY BUCKET",
  "MULTI PURPOSE BUCKET",
  "4 IN 1 BUCKET",
  "TOOTH BUCKET",
  "SMOOTH EDGE BUCKET",
  "ROCK BUCKET",
  "GRAPPLE BUCKET",
  "SKELETON BUCKET",
  "SIDE DISCHARGE BUCKET",
  "SNOW BUCKET",
  "MANURE BUCKET",
  "BUCKET TEETH",
  "BOLT ON CUTTING EDGE",
  "REVERSIBLE CUTTING EDGE",
  "WELD ON EDGE",
  "SIDE CUTTERS",
  "BUCKET LEVEL INDICATOR",

  /* -------------------- */
  /* FORESTRY / MULCHING DNA */
  /* -------------------- */

  "FORESTRY PACKAGE",
  "MULCHING PACKAGE",
  "LAND MANAGEMENT PACKAGE",
  "LM PACKAGE",
  "FORESTRY DOOR",
  "POLYCARB DOOR",
  "POLYCARBONATE DOOR",
  "FORESTRY FRONT DOOR",
  "FRONT DOOR",
  "DOOR DELETE",
  "FORESTRY CAB",
  "PRESSURIZED CAB",
  "FULL GUARDING",
  "CAB GUARDING",
  "SIDE GUARDS",
  "REAR GUARDS",
  "LIFT ARM GUARDS",
  "CYLINDER GUARDS",
  "HOSE GUARDS",
  "BELLY GUARDS",
  "UNDERCARRIAGE GUARDS",
  "TRACK GUARDS",
  "FINAL DRIVE GUARDS",
  "LIGHT GUARDS",
  "FUEL TANK GUARD",
  "HYDRAULIC TANK GUARD",
  "REAR SCREEN",
  "TOP SCREEN",
  "DEBRIS SCREEN",
  "SEVERE DUTY DOOR",
  "DEMOLITION DOOR",
  "FRONT GUARD PACKAGE",
  "FIRE EXTINGUISHER MOUNT",
  "FIRE SUPPRESSION",
  "MULCHER READY",
  "FORESTRY MULCHER READY",

  /* -------------------- */
  /* COOLING DNA */
  /* -------------------- */

  "COOLING PACKAGE",
  "HIGH CAPACITY COOLING",
  "HIGH AMBIENT COOLING",
  "FORESTRY COOLING PACKAGE",
  "MULCHING COOLING PACKAGE",
  "HYDRAULIC OIL COOLER",
  "AUXILIARY HYDRAULIC COOLER",
  "REVERSING FAN",
  "AUTO REVERSING FAN",
  "DEBRIS PACKAGE",
  "DEBRIS SCREEN",
  "RADIATOR SCREEN",
  "SIDE BY SIDE COOLERS",
  "SWING OUT COOLER",
  "COOLING CLEANOUT",
  "HIGH FLOW COOLING",

  /* -------------------- */
  /* ATTACHMENT READY DNA */
  /* -------------------- */

  "ATTACHMENT READY",
  "MULCHER READY",
  "BRUSH CUTTER READY",
  "COLD PLANER READY",
  "MILLING READY",
  "HAMMER READY",
  "BREAKER READY",
  "AUGER READY",
  "GRAPPLE READY",
  "TRENCHER READY",
  "SNOW READY",
  "BROOM READY",
  "SWEEPER READY",
  "STUMP GRINDER READY",
  "TREE SHEAR READY",
  "TREE PULLER READY",
  "TILLER READY",
  "ROCK WHEEL READY",
  "CONCRETE SAW READY",
  "SOIL CONDITIONER READY",
  "BOX BLADE READY",
  "DOZER BLADE READY",
  "GRADE BLADE READY",
  "LAND PLANE READY",
  "LASER BOX BLADE READY",
  "HIGH FLOW ATTACHMENT READY",
  "SMART ATTACHMENT READY",

  /* -------------------- */
  /* ELECTRICAL / ATTACHMENT CONTROL DNA */
  /* -------------------- */

  "14 PIN CONNECTOR",
  "7 PIN CONNECTOR",
  "8 PIN CONNECTOR",
  "ATTACHMENT CONTROL HARNESS",
  "ELECTRICAL ATTACHMENT CONTROL",
  "AUXILIARY ELECTRICAL CONNECTOR",
  "SMART ATTACHMENT",
  "SMART ATTACHMENT CONTROL",
  "CAN BUS ATTACHMENT CONTROL",
  "HIGH OUTPUT ALTERNATOR",
  "BATTERY DISCONNECT",
  "MASTER DISCONNECT",
  "POWER PORT",
  "12V OUTLET",
  "LED LIGHTS",
  "HALOGEN LIGHTS",
  "WORK LIGHT PACKAGE",
  "ROAD LIGHT PACKAGE",
  "BEACON",
  "STROBE LIGHT",

  /* -------------------- */
  /* AUTOMATION / GRADE DNA */
  /* -------------------- */

  "GRADE CONTROL",
  "GRADE CONTROL READY",
  "LASER READY",
  "GPS READY",
  "GNSS READY",
  "2D GRADE CONTROL",
  "3D GRADE CONTROL",
  "MACHINE CONTROL READY",
  "BOX BLADE CONTROL",
  "DOZER BLADE CONTROL",
  "SMARTGRADE",
  "TOPCON READY",
  "TRIMBLE READY",
  "LASER RECEIVER READY",
  "SELF LEVELING",
  "RETURN TO DIG",
  "WORK TOOL POSITIONER",
  "ATTACHMENT POSITION CONTROL",
  "PAYLOAD SYSTEM",
  "ONBOARD WEIGH SYSTEM",
  "TELEMATICS",
  "PRODUCT LINK",
  "JD LINK",
  "BOBCAT MACHINE IQ",
  "CASE SITEWATCH",
  "KOMTRAX",
  "REMOTE DIAGNOSTICS",
  "FLEET MANAGEMENT",
  "REAR CAMERA",
  "BACKUP CAMERA",
  "CAMERA SYSTEM",

  /* -------------------- */
  /* CAB / OPERATOR DNA */
  /* -------------------- */

  "OPEN ROPS",
  "ROPS",
  "FOPS",
  "CAB",
  "ENCLOSED CAB",
  "CAB ENCLOSURE",
  "C/H/A",
  "AIR CONDITIONED CAB",
  "HEATED CAB",
  "PRESSURIZED CAB",
  "FORESTRY CAB",
  "DELUXE CAB",
  "PREMIUM CAB",
  "ONE ARM CAB",
  "SIDE ENTRY CAB",
  "FRONT ENTRY CAB",
  "ROLL UP DOOR",
  "SWING OUT DOOR",
  "POLYCARB DOOR",
  "GLASS DOOR",
  "HIGH BACK SEAT",
  "SUSPENSION SEAT",
  "AIR RIDE SEAT",
  "HEATED SEAT",
  "VENTED SEAT",
  "ARMREST CONTROLS",
  "MULTIFUNCTION DISPLAY",
  "TOUCHSCREEN DISPLAY",
  "RADIO READY",
  "BLUETOOTH RADIO",

  /* -------------------- */
  /* MINI / STAND ON DNA */
  /* -------------------- */

  "MINI SKID STEER",
  "COMPACT UTILITY LOADER",
  "STAND ON LOADER",
  "WALK BEHIND LOADER",
  "RIDE ON PLATFORM",
  "FOLD UP PLATFORM",
  "NARROW TRACK MINI LOADER",
  "WIDE TRACK MINI LOADER",
  "WHEELED MINI LOADER",
  "TRACKED MINI LOADER",
  "AUXILIARY HYDRAULICS",
  "MINI QUICK ATTACH",
  "UNIVERSAL MINI MOUNT",
  "BOB-TACH MINI MOUNT",
  "HYDRAULIC MINI COUPLER",
  "MANUAL MINI COUPLER",
  "GAS ENGINE MINI LOADER",
  "DIESEL MINI LOADER",
  "ELECTRIC MINI LOADER",

  /* -------------------- */
  /* DOZER LOADER DNA */
  /* -------------------- */

  "DOZER LOADER",
  "COMPACT DOZER LOADER",
  "6 WAY BLADE",
  "SIX WAY BLADE",
  "C FRAME",
  "DOZER BLADE",
  "GRADE BLADE",
  "BLADE FLOAT",
  "BLADE ANGLE",
  "BLADE TILT",
  "BLADE LIFT CYLINDERS",
  "TRACK LOADER DOZER MODE",
  "CTL DOZER PACKAGE",

  /* -------------------- */
  /* POWERTRAIN DNA */
  /* -------------------- */

  "DIESEL ENGINE",
  "GAS ENGINE",
  "BATTERY ELECTRIC",
  "ELECTRIC DRIVE",
  "LITHIUM ION",
  "LEAD ACID BATTERY",
  "ONBOARD CHARGER",
  "OFFBOARD CHARGER",
  "TURBOCHARGED",
  "INTERCOOLED",
  "COMMON RAIL",
  "MECHANICAL INJECTION",
  "ELECTRONIC ENGINE",
  "AUTO IDLE",
  "ENGINE SHUTDOWN TIMER",
  "ECO MODE",
  "AUTO THROTTLE",
  "COLD WEATHER PACKAGE",
  "BLOCK HEATER",
  "ETHER START",

  /* -------------------- */
  /* SAFETY / GUARDING DNA */
  /* -------------------- */

  "BACKUP ALARM",
  "TRAVEL ALARM",
  "HORN",
  "SEAT BAR",
  "LAP BAR",
  "SEAT BELT",
  "OPERATOR PRESENCE SYSTEM",
  "INTERLOCK SYSTEM",
  "LIFT ARM LOCK",
  "PARK BRAKE",
  "EMERGENCY STOP",
  "FIRE SUPPRESSION",
  "REAR VIEW CAMERA",
  "BACKUP CAMERA",
  "OBJECT DETECTION",
  "SERVICE BRAKE",
  "SPRING APPLIED PARK BRAKE",
  "VANDAL GUARDS",
  "LOCKABLE FUEL CAP",
  "LOCKABLE ENGINE COVER",

/* -------------------- */
/* SKID STEER BUCKET DNA */
/* -------------------- */

"GENERAL PURPOSE BUCKET",
"GP BUCKET",
"LOW PROFILE BUCKET",
"HEAVY DUTY BUCKET",
"SEVERE DUTY BUCKET",
"ROCK BUCKET",
"LIGHT MATERIAL BUCKET",
"HIGH CAPACITY BUCKET",
"MULTI PURPOSE BUCKET",
"4 IN 1 BUCKET",
"6 IN 1 BUCKET",
"UTILITY BUCKET",
"CONSTRUCTION BUCKET",
"SNOW BUCKET",
"MATERIAL HANDLING BUCKET",
"DIRT BUCKET",
"GRADING BUCKET",
"LANDSCAPE BUCKET",
"SKELETON BUCKET",
"SCREENING BUCKET",
"SHOOTING BUCKET",
"CONCRETE BUCKET",
"SIDE DISCHARGE BUCKET",
"V BUCKET",
"TILT BUCKET",
"HYDRAULIC TILT BUCKET",
"POWER ANGLE BUCKET",
"DOZER BUCKET",
"MIXING BUCKET",
"MANURE BUCKET",
"FEED BUCKET",
"SILAGE BUCKET",
"SCRAP BUCKET",
"WASTE BUCKET",
"TOOTH BUCKET",
"SMOOTH EDGE BUCKET",
"BOLT ON CUTTING EDGE",
"REVERSIBLE CUTTING EDGE",
"WEAR EDGE",
"BUCKET TEETH",
"ROCK TEETH",
"TIGER TEETH",
"CORNER TEETH",
"SIDE CUTTERS",
"WEAR PLATES",
"HEEL PLATES",
"HARDOX BUCKET",
"SEVERE DUTY WEAR PACKAGE",

/* -------------------- */
/* FORK DNA */
/* -------------------- */

"PALLET FORKS",
"HEAVY DUTY PALLET FORKS",
"WIDE FRAME PALLET FORKS",
"WALK THROUGH PALLET FORKS",
"HYDRAULIC PALLET FORKS",
"FORK POSITIONER",
"HYDRAULIC FORK POSITIONER",
"FLOATING FORKS",
"CONSTRUCTION FORKS",
"BRICK FORKS",
"LUMBER FORKS",
"HAY FORKS",
"BALE FORKS",
"MANURE FORKS",
"SILAGE FORKS",
"GRAPPLE FORKS",
"ROOT FORKS",
"LOG FORKS",
"PIPE FORKS",
"INDUSTRIAL FORKS",
"FORK EXTENSIONS",
"CLASS II FORKS",
"CLASS III FORKS",
"PIN ON FORKS",
"QUICK ATTACH FORKS",

/* -------------------- */
/* GRAPPLE DNA */
/* -------------------- */

"ROOT GRAPPLE",
"ROCK GRAPPLE",
"LOG GRAPPLE",
"INDUSTRIAL GRAPPLE",
"SCRAP GRAPPLE",
"WASTE GRAPPLE",
"DEMOLITION GRAPPLE",
"BRUSH GRAPPLE",
"BRUSH ROOT GRAPPLE",
"UTILITY GRAPPLE",
"MANURE GRAPPLE",
"SKELETON GRAPPLE",
"CLAM GRAPPLE",
"SINGLE CYLINDER GRAPPLE",
"DUAL CYLINDER GRAPPLE",
"INDEPENDENT CLAW GRAPPLE",
"HYDRAULIC GRAPPLE",
"GRAPPLE BUCKET",
"GRAPPLE FORKS",

/* -------------------- */
/* MULCHER / FORESTRY DNA */
/* -------------------- */

"FORESTRY MULCHER",
"DISC MULCHER",
"DRUM MULCHER",
"MULCHING HEAD",
"FORESTRY CUTTER",
"BRUSH CUTTER",
"ROTARY CUTTER",
"OPEN FRONT BRUSH CUTTER",
"CLOSED FRONT BRUSH CUTTER",
"DRUM CUTTER",
"FLAIL MOWER",
"FORESTRY MOWER",
"TREE SAW",
"TREE SHEAR",
"TREE PULLER",
"STUMP GRINDER",
"STUMP BUCKET",
"ROOT RAKE",
"FORESTRY RAKE",
"MULCHER READY",
"HIGH FLOW MULCHER",
"XHP MULCHER",
"CARBIDE TEETH MULCHER",
"KNIFE TOOTH MULCHER",
"FIXED TOOTH MULCHER",
"SWING HAMMER MULCHER",

/* -------------------- */
/* SNOW ATTACHMENT DNA */
/* -------------------- */

"SNOW PUSHER",
"SNOW BLADE",
"ANGLE SNOW BLADE",
"V PLOW",
"SNOW PLOW",
"BOX PUSHER",
"SNOW BUCKET",
"SNOW BLOWER",
"TWO STAGE SNOW BLOWER",
"HIGH FLOW SNOW BLOWER",
"HYDRAULIC CHUTE ROTATION",
"SALT SPREADER",
"SAND SPREADER",
"DROP SPREADER",
"TAILGATE SPREADER",
"SNOW WING",

/* -------------------- */
/* BROOM / SWEEPER DNA */
/* -------------------- */

"ANGLE BROOM",
"PICKUP BROOM",
"ROTARY BROOM",
"GUTTER BROOM",
"SWEEPER",
"SWEEPER BUCKET",
"UTILITY BROOM",
"POLY BROOM",
"WAFER BROOM",
"WIRE BROOM",
"DUST SUPPRESSION BROOM",
"WATER SPRAY BROOM",

/* -------------------- */
/* AUGER DNA */
/* -------------------- */

"AUGER DRIVE",
"PLANETARY AUGER DRIVE",
"HIGH TORQUE AUGER",
"LOW FLOW AUGER",
"HIGH FLOW AUGER",
"EARTH AUGER",
"ROCK AUGER",
"TREE AUGER",
"HEX DRIVE AUGER",
"ROUND DRIVE AUGER",
"AUGER EXTENSION",
"AUGER BIT",
"AUGER ADAPTER",
"AUGER CRADLE",

/* -------------------- */
/* TRENCHER DNA */
/* -------------------- */

"TRENCHER",
"CHAIN TRENCHER",
"WHEEL TRENCHER",
"ROCK TRENCHER",
"MICROTRENCHER",
"SIDE SHIFT TRENCHER",
"HIGH FLOW TRENCHER",
"LOW FLOW TRENCHER",
"DIRT CHAIN",
"ROCK CHAIN",
"COMBINATION CHAIN",
"AUGER SPOIL REMOVAL",
"CRUMBER BAR",

/* -------------------- */
/* BREAKER / HAMMER DNA */
/* -------------------- */

"HYDRAULIC BREAKER",
"HYDRAULIC HAMMER",
"LOW FLOW BREAKER",
"HIGH FLOW BREAKER",
"MOIL POINT BREAKER",
"CHISEL POINT BREAKER",
"BLUNT TOOL BREAKER",
"SILENCED BREAKER",
"BOX STYLE BREAKER",
"SIDE PLATE BREAKER",

/* -------------------- */
/* COLD PLANER DNA */
/* -------------------- */

"COLD PLANER",
"PLANER",
"MILLING ATTACHMENT",
"LOW FLOW PLANER",
"HIGH FLOW PLANER",
"DRUM PLANER",
"ASYMMETRICAL PLANER",
"SIDE SHIFT PLANER",
"HYDRAULIC DEPTH CONTROL",
"MANUAL DEPTH CONTROL",
"BIT HOLDER SYSTEM",
"CARBIDE CUTTING TEETH",

/* -------------------- */
/* DOZER / GRADE DNA */
/* -------------------- */

"DOZER BLADE",
"6 WAY BLADE",
"ANGLE BLADE",
"TILT BLADE",
"LASER BOX BLADE",
"BOX BLADE",
"LAND PLANE",
"POWER RAKE",
"SOIL CONDITIONER",
"HARLEY RAKE",
"LEVELER",
"GRADE BLADE",
"GRADER ATTACHMENT",
"LASER READY BLADE",
"GPS READY BLADE",
"2D GRADE BLADE",
"3D GRADE BLADE",

/* -------------------- */
/* COMPACTION DNA */
/* -------------------- */

"VIBRATORY ROLLER",
"SMOOTH DRUM ROLLER",
"PADFOOT ROLLER",
"SHEEPFOOT ROLLER",
"TRENCH COMPACTOR",
"PLATE COMPACTOR",
"VIBRATORY PLATE",
"COMPACTION WHEEL",
"ROLLER ATTACHMENT",
"DUAL DRUM ROLLER",
"SINGLE DRUM ROLLER",

/* -------------------- */
/* DEMOLITION DNA */
/* -------------------- */

"DEMOLITION SHEAR",
"CONCRETE CRUSHER",
"PULVERIZER",
"MULTI PROCESSOR",
"HYDRAULIC SHEAR",
"STEEL SHEAR",
"ROTATING SHEAR",
"FIXED PULVERIZER",
"ROTATING PULVERIZER",
"GRAPPLE SAW",
"DEMOLITION GRAPPLE",
"SCRAP PROCESSOR",

/* -------------------- */
/* MATERIAL HANDLING DNA */
/* -------------------- */

"BALE SPEAR",
"BALE GRAB",
"PIPE GRAPPLE",
"PIPE LAYER",
"CRANE BOOM",
"MATERIAL ARM",
"LIFT JIB",
"HOOK ATTACHMENT",
"VACUUM LIFTER",
"GLASS HANDLER",
"PANEL HANDLER",
"DRUM HANDLER",

/* -------------------- */
/* CONCRETE / ASPHALT DNA */
/* -------------------- */

"CONCRETE MIXER",
"CEMENT MIXER",
"CONCRETE PUMP",
"ASPHALT PLANER",
"ASPHALT CUTTER",
"PAVING ATTACHMENT",
"VIBRATORY ASPHALT ROLLER",
"SEALCOAT BROOM",

/* -------------------- */
/* AGRICULTURE DNA */
/* -------------------- */

"FEED PUSHER",
"SILAGE DEFACER",
"MANURE SCRAPER",
"BALE SQUEEZE",
"HAY SPEAR",
"PALLET SPEAR",
"FEED MIXER",
"GRAIN BUCKET",
"COMMODITY BUCKET",

/* -------------------- */
/* UTILITY / SPECIALTY DNA */
/* -------------------- */

"POWER BOX RAKE",
"LANDSCAPE RAKE",
"UTILITY FORKS",
"CABLE PLOW",
"REEL CARRIER",
"POST DRIVER",
"POST PULLER",
"VIBRATORY PLOW",
"IRRIGATION WHEEL",
"SEEDER",
"HYDRAULIC TILLER",
"SOIL MIXER",
"AERATOR",
"POWER ANGLE SWEEPER",
"PRESSURE WASHER",
"WATER TANK",
"SPRAYER",

/* -------------------- */
/* ATTACHMENT CONTROL DNA */
/* -------------------- */

"STANDARD FLOW ATTACHMENT",
"HIGH FLOW ATTACHMENT",
"ENHANCED HIGH FLOW ATTACHMENT",
"XPS ATTACHMENT",
"XHP ATTACHMENT",
"SUPER FLOW ATTACHMENT",
"LOW FLOW ATTACHMENT",
"14 PIN ATTACHMENT",
"7 PIN ATTACHMENT",
"8 PIN ATTACHMENT",
"SMART ATTACHMENT",
"CAN BUS ATTACHMENT",
"ELECTROHYDRAULIC ATTACHMENT",
"HYDRAULIC QUICK ATTACH",
"POWER QUICK ATTACH",
"UNIVERSAL QUICK ATTACH",
"SKID STEER MOUNT",
"MINI SKID STEER MOUNT",
"EURO ATTACHMENT PLATE",
"GLOBAL ATTACHMENT PLATE"  

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-DEF",
  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4",
  "TIER 4 FINAL",
  "T4F",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF",
  "DEF DELETE"
];

export default skidSteerCtlDnaKeywords;
