const taxonomyRegistry = [
  { name: "AERIAL LIFTS", awsName: "Aerial Equipment", awsId: "aerial-equipment", file: "aerialTaxonomy" },
  { name: "AGGREGATE EQUIPMENT", awsName: "Aggregate", awsId: "aggregate", file: "aggregateTaxonomy" },
  { name: "AGRICULTURE HARVESTERS", awsName: "Agriculture Harvesters", awsId: "agriculture-harvesters", file: "agricultureHarvestersTaxonomy" },
  { name: "AGRICULTURE TRACTORS", awsName: "Agriculture Tractors", awsId: "agriculture-tractors", file: "agricultureTractorsTaxonomy" },
  { name: "ASPHALT EQUIPMENT", awsName: "Asphalt Equipment", awsId: "asphalt-equipment", file: "asphaltEquipmentTaxonomy" },
  { name: "BACKHOE LOADERS", awsName: "Backhoe Loaders", awsId: "backhoe-loaders", file: "backhoeLoadersTaxonomy" },
  { name: "COMPACTION / ROLLERS", awsName: "Compaction / Rollers", awsId: "compaction-rollers", file: "compactionRollersTaxonomy" },
  { name: "CRANES", awsName: "Cranes", awsId: "cranes", file: "cranesTaxonomy" },
  { name: "CRAWLER CARRIERS", awsName: "Crawler Carriers / Loader", awsId: "crawler-carriers-loader", file: "crawlerCarriersTaxonomy" },
  { name: "DOZERS", awsName: "Dozers", awsId: "dozers", file: "dozersTaxonomy" },
  { name: "DRILLS / PILING", awsName: "Drills / Piling", awsId: "drills-piling", file: "drillsAndPilingTaxonomy" },
  { name: "DUMP TRUCKS", awsName: "Dump Trucks / Artic / Rigid", awsId: "dump-trucks-artic-rigid", file: "dumpTrucksTaxonomy" },
  { name: "EXCAVATORS", awsName: "Excavators", awsId: "excavators", file: "excavatorsTaxonomy" },
  { name: "FORKLIFTS", awsName: "Forklifts", awsId: "forklifts", file: "forkliftsTaxonomy" },
  { name: "MOTOR GRADERS", awsName: "Motor Graders", awsId: "motor-graders", file: "motorGradersTaxonomy" },
  { name: "SCRAPERS", awsName: "Scraper", awsId: "scraper", file: "scraperTaxonomy" },
  { name: "SKID STEER / CTL", awsName: "Skid Steer / CTL", awsId: "skid-steer-ctl", file: "skidSteerCtlTaxonomy" },
  { name: "TELEHANDLERS", awsName: "Telehandlers", awsId: "telehandlers", file: "telehandlersTaxonomy" },
  { name: "TRENCHERS", awsName: "Trenchers", awsId: "trenchers", file: "trenchersTaxonomy" },
  { name: "TRAILERS", awsName: "Trailers", awsId: "trailers", file: "trailersTaxonomy" },
  { name: "TRUCKS", awsName: "Trucks", awsId: "trucks", file: "trucksTaxonomy" },
  { name: "WHEEL LOADERS", awsName: "Wheel Loaders", awsId: "wheel-loaders", file: "wheelLoadersTaxonomy" },
  { name: "ATTACHMENTS / PARTS", awsName: "Attatchments / Parts", awsId: "attatchments-parts", file: "attachmentsPartsTaxonomy" },
  { name: "SUPPORT EQUIPMENT", awsName: "Support Equipment", awsId: "support-equipment", file: "supportEquipmentTaxonomy" },
  { name: "UTILITY CARTS", awsName: "Utility Carts", awsId: "utility-carts", file: "utilityCartsTaxonomy" },
  { name: "OTHER / SPECIALTY", awsName: "Other / Specialty", awsId: "other-specialty", file: null }
];

module.exports = taxonomyRegistry;
