const telehandlerDnaKeywords = [
  /* -------------------- */
  /* MACHINE TYPE DNA */
  /* -------------------- */

  "FIXED BOOM TELEHANDLER",
  "STRAIGHT BOOM TELEHANDLER",
  "ROTATING TELEHANDLER",
  "ROTO TELEHANDLER",
  "HIGH REACH TELEHANDLER",
  "HIGH CAPACITY TELEHANDLER",
  "COMPACT TELEHANDLER",
  "ROUGH TERRAIN TELEHANDLER",
  "INDUSTRIAL TELEHANDLER",
  "AG TELEHANDLER",
  "HEAVY LIFT TELEHANDLER",
  "CONTAINER TELEHANDLER",
  "ARTICULATED TELEHANDLER",
  "ELECTRIC TELEHANDLER",
  "HYBRID TELEHANDLER",

  /* -------------------- */
  /* CHASSIS DNA */
  /* -------------------- */

  "RIGID FRAME",
  "COMPACT CHASSIS",
  "LOW PROFILE CHASSIS",
  "HEAVY DUTY FRAME",
  "HIGH CAPACITY FRAME",
  "ROUGH TERRAIN CHASSIS",
  "ROTATING UPPER",
  "ROTO CHASSIS",
  "ARTICULATED CHASSIS",
  "FRAME LEVELING",
  "FRAME SWAY",
  "SELF LEVELING FRAME",
  "LEVELING FRAME",
  "STABILIZER CHASSIS",
  "OUTRIGGER CHASSIS",
  "COUNTERWEIGHTED CHASSIS",

  /* -------------------- */
  /* BOOM SYSTEM DNA */
  /* -------------------- */

  "FIXED BOOM",
  "STRAIGHT BOOM",
  "TELESCOPIC BOOM",
  "MULTI SECTION BOOM",
  "TWO SECTION BOOM",
  "THREE SECTION BOOM",
  "FOUR SECTION BOOM",
  "HIGH REACH BOOM",
  "HIGH CAPACITY BOOM",
  "HEAVY LIFT BOOM",
  "COMPACT BOOM",
  "LOW PROFILE BOOM",
  "BOOM EXTENSION",
  "BOOM RETRACTION",
  "BOOM FLOAT",
  "BOOM SUSPENSION",
  "BOOM RIDE CONTROL",
  "BOOM CYLINDERS",
  "BOOM ANGLE SENSOR",
  "BOOM EXTENSION SENSOR",
  "BOOM LOCK",
  "BOOM DAMPING",

  /* -------------------- */
  /* REACH SYSTEM DNA */
  /* -------------------- */

  "HIGH REACH",
  "LONG REACH",
  "COMPACT REACH",
  "TELESCOPIC REACH",
  "BOOM REACH",
  "REACH SENSOR",
  "REACH LIMITER",
  "REACH CONTROL",
  "BOOM LENGTH SENSOR",
  "LOAD CHART REACH SYSTEM",

  /* -------------------- */
  /* ROTATION DNA */
  /* -------------------- */

  "360 DEGREE ROTATION",
  "CONTINUOUS ROTATION",
  "NON CONTINUOUS ROTATION",
  "SLEW DRIVE",
  "SWING DRIVE",
  "SWING MOTOR",
  "SWING BRAKE",
  "ROTATION LOCK",
  "ROTARY MANIFOLD",
  "SLEW RING",
  "TURRET ROTATION",
  "ROTATING CARRIAGE",
  "SWING CARRIAGE",

  /* -------------------- */
  /* STABILIZER / OUTRIGGER DNA */
  /* -------------------- */

  "STABILIZERS",
  "OUTRIGGERS",
  "HYDRAULIC STABILIZERS",
  "HYDRAULIC OUTRIGGERS",
  "FRONT STABILIZERS",
  "REAR STABILIZERS",
  "FRONT OUTRIGGERS",
  "REAR OUTRIGGERS",
  "A FRAME OUTRIGGERS",
  "H TYPE OUTRIGGERS",
  "VERTICAL STABILIZERS",
  "SIDE SHIFT STABILIZERS",
  "VARIABLE OUTRIGGERS",
  "OUTRIGGER PADS",
  "OUTRIGGER POSITION SENSOR",
  "STABILIZER INTERLOCK",
  "AUTO LEVELING",
  "SELF LEVELING",
  "LEVELING JACKS",

  /* -------------------- */
  /* FORK CARRIAGE DNA */
  /* -------------------- */

  "STANDARD CARRIAGE",
  "WIDE CARRIAGE",
  "SIDE SHIFT",
  "SIDE SHIFT CARRIAGE",
  "FORK POSITIONER",
  "HYDRAULIC FORK POSITIONER",
  "TILT CARRIAGE",
  "FORK TILT",
  "CARRIAGE TILT",
  "FORK LEVELING",
  "CARRIAGE LEVELING",
  "PALLET FORKS",
  "HEAVY DUTY FORKS",
  "FLOATING FORKS",
  "HYDRAULIC FORKS",
  "FORK EXTENSIONS",
  "HOOK TYPE FORKS",
  "PIN TYPE FORKS",
  "LOAD BACKREST",
  "FORK LOCK",

  /* -------------------- */
  /* AUXILIARY HYDRAULIC DNA */
  /* -------------------- */

  "AUX HYDRAULICS",
  "AUXILIARY HYDRAULICS",
  "BOOM AUXILIARY HYDRAULICS",
  "CARRIAGE AUXILIARY HYDRAULICS",
  "FRONT AUXILIARY HYDRAULICS",
  "HIGH FLOW HYDRAULICS",
  "STANDARD FLOW HYDRAULICS",
  "LOW FLOW HYDRAULICS",
  "THIRD FUNCTION HYDRAULICS",
  "FOURTH FUNCTION HYDRAULICS",
  "MULTI FUNCTION HYDRAULICS",
  "ATTACHMENT HYDRAULICS",
  "HYDRAULIC QUICK COUPLERS",
  "FLAT FACE COUPLERS",
  "AUXILIARY HOSE KIT",
  "FLOW CONTROL",
  "PRESSURE CONTROL",
  "CONTINUOUS FLOW",

  /* -------------------- */
  /* ATTACHMENT DNA */
  /* -------------------- */

  "QUICK ATTACH",
  "HYDRAULIC QUICK ATTACH",
  "MANUAL QUICK ATTACH",
  "HYDRAULIC COUPLER",
  "MANUAL COUPLER",
  "TELEHANDLER CARRIAGE",
  "UNIVERSAL CARRIAGE",
  "JCB Q-FIT",
  "MANITOU CARRIAGE",
  "MERLO CARRIAGE",
  "JLG CARRIAGE",
  "GENIE CARRIAGE",
  "BUCKET",
  "LIGHT MATERIAL BUCKET",
  "GRAPPLE BUCKET",
  "TRUSS BOOM",
  "LIFTING JIB",
  "JIB",
  "WINCH",
  "HOOK ATTACHMENT",
  "CRANE BOOM",
  "MATERIAL HANDLING ARM",
  "WORK PLATFORM READY",
  "PERSONNEL PLATFORM READY",
  "MAN BASKET READY",
  "SWEEPING BROOM",
  "BALE SPEAR",
  "BALE CLAMP",
  "SIDE SHIFT ATTACHMENT",
  "FORK POSITIONER ATTACHMENT",
  "CONTAINER SPREADER",

  /* -------------------- */
  /* DRIVE SYSTEM DNA */
  /* -------------------- */

  "2WD",
  "4WD",
  "ALL WHEEL DRIVE",
  "HYDROSTATIC",
  "HYDROSTATIC DRIVE",
  "POWERSHIFT",
  "TORQUE CONVERTER",
  "DIRECT DRIVE",
  "CVT",
  "VARIPOWER",
  "ELECTRIC DRIVE",
  "TWO SPEED",
  "CREEP MODE",
  "INCHING PEDAL",
  "DRIVE MODE SELECT",
  "TRAVEL DRIVE",
  "PLANETARY FINAL DRIVE",
  "DIFFERENTIAL LOCK",
  "LIMITED SLIP DIFFERENTIAL",
  "TRACTION CONTROL",

  /* -------------------- */
  /* STEERING DNA */
  /* -------------------- */

  "ALL WHEEL STEER",
  "FOUR WHEEL STEER",
  "FRONT WHEEL STEER",
  "REAR WHEEL STEER",
  "CRAB STEER",
  "COORDINATED STEER",
  "ROUND STEER",
  "HYDRAULIC STEERING",
  "POWER STEERING",
  "STEERING AXLE",
  "OSCILLATING AXLE",
  "SWAY CONTROL",

  /* -------------------- */
  /* SUSPENSION DNA */
  /* -------------------- */

  "RIDE CONTROL",
  "LOAD CUSHION",
  "HYDRAULIC SUSPENSION",
  "AXLE SUSPENSION",
  "LOCKING AXLE",
  "FLOATING AXLE",
  "SWAY FRAME",
  "LOAD STABILIZATION",

  /* -------------------- */
  /* HYDRAULIC SYSTEM DNA */
  /* -------------------- */

  "OPEN CENTER HYDRAULICS",
  "CLOSED CENTER HYDRAULICS",
  "LOAD SENSING HYDRAULICS",
  "PRESSURE COMPENSATED HYDRAULICS",
  "VARIABLE DISPLACEMENT PUMP",
  "PISTON PUMP",
  "GEAR PUMP",
  "HYDRAULIC COOLER",
  "HYDRAULIC FILTER",
  "ELECTROHYDRAULIC CONTROLS",
  "PROPORTIONAL HYDRAULICS",
  "BOOM HYDRAULICS",
  "CARRIAGE HYDRAULICS",
  "OUTRIGGER HYDRAULICS",
  "STABILIZER HYDRAULICS",
  "HYDRAULIC FLOW CONTROL",
  "HYDRAULIC PRESSURE CONTROL",

  /* -------------------- */
  /* BOOM SUSPENSION DNA */
  /* -------------------- */

  "HYDRAULIC BOOM SUSPENSION",
  "ACCUMULATOR BOOM SUSPENSION",
  "RIDE CONTROL ACCUMULATOR",

  /* -------------------- */
  /* CAB / OPERATOR DNA */
  /* -------------------- */

  "OPEN ROPS",
  "ROPS",
  "FOPS",
  "C/H/A",
  "ENCLOSED CAB",
  "AIR CONDITIONED CAB",
  "HEATED CAB",
  "PRESSURIZED CAB",
  "LOW PROFILE CAB",
  "HIGH VISIBILITY CAB",
  "PANORAMIC CAB",
  "DELUXE CAB",
  "SUSPENSION SEAT",
  "AIR RIDE SEAT",
  "HEATED SEAT",
  "SWIVEL SEAT",
  "TILTING CAB",
  "CAB GUARDING",
  "ROOF WINDOW",
  "REAR CAMERA",
  "SIDE CAMERA",
  "CAMERA SYSTEM",
  "360 CAMERA",
  "LED LIGHTS",
  "HALOGEN LIGHTS",
  "WORK LIGHT PACKAGE",
  "BEACON",

  /* -------------------- */
  /* LOAD MANAGEMENT DNA */
  /* -------------------- */

  "LOAD MOMENT INDICATOR",
  "LMI",
  "LOAD MANAGEMENT SYSTEM",
  "LOAD SCALE",
  "LOAD WEIGHING SYSTEM",
  "LOAD CHART SYSTEM",
  "LOAD LIMITER",
  "OVERLOAD PROTECTION",
  "STABILITY CONTROL",
  "HEIGHT LIMITER",
  "STABILIZER POSITION SENSOR",
  "CARRIAGE POSITION SENSOR",
  "ANTI TIP SYSTEM",
  "LOAD HOLDING VALVES",

  /* -------------------- */
  /* AUTOMATION / TELEMATICS DNA */
  /* -------------------- */

  "TELEMATICS",
  "REMOTE DIAGNOSTICS",
  "GPS TRACKING",
  "FLEET MANAGEMENT",
  "REMOTE MONITORING",
  "LOAD DATA LOGGING",
  "SERVICE MONITOR",
  "MACHINE MONITORING",
  "ACCESS CONTROL",
  "PIN CODE START",
  "KEYLESS START",
  "AUTO IDLE",
  "AUTO SHUTDOWN",
  "WORK ZONE LIMITING",
  "HEIGHT LIMIT CONTROL",
  "BOOM POSITION MEMORY",
  "DIAGNOSTIC DISPLAY",

  /* -------------------- */
  /* TIRE DNA */
  /* -------------------- */

  "PNEUMATIC TIRES",
  "SOLID TIRES",
  "FOAM FILLED TIRES",
  "INDUSTRIAL TIRES",
  "ROUGH TERRAIN TIRES",
  "FLOTATION TIRES",
  "TRACTION TIRES",
  "NON MARKING TIRES",
  "AIR FILLED TIRES",
  "POLY TIRES",
  "SUPER ELASTIC TIRES",
  "WIDE TIRES",
  "NARROW TIRES",
  "DUAL TIRES",

  /* -------------------- */
  /* LIFT SYSTEM DNA */
  /* -------------------- */

  "HIGH LIFT",
  "HIGH CAPACITY",
  "HEAVY LIFT",
  "BOOM LIFT CYLINDERS",
  "LIFT CYLINDERS",
  "CUSHIONED LOWERING",
  "LIFT LOCKOUT",
  "LOAD STABILIZER",
  "BOOM HOLDING VALVES",
  "BOOM LOWERING CONTROL",

  /* -------------------- */
  /* CONTROL SYSTEM DNA */
  /* -------------------- */

  "JOYSTICK CONTROLS",
  "SINGLE JOYSTICK",
  "DUAL JOYSTICK",
  "PILOT CONTROLS",
  "FINGERTIP CONTROLS",
  "PROPORTIONAL CONTROLS",
  "MULTIFUNCTION JOYSTICK",
  "STEERING COLUMN CONTROLS",
  "DIRECTIONAL CONTROL LEVER",
  "SIDE SHIFT CONTROL",
  "FORK POSITIONER CONTROL",
  "AUXILIARY HYDRAULIC CONTROL",
  "WORK MODE SELECT",

  /* -------------------- */
  /* SAFETY DNA */
  /* -------------------- */

  "OBJECT DETECTION",
  "PROXIMITY SENSOR",
  "BACKUP ALARM",
  "TRAVEL ALARM",
  "SEAT BELT INTERLOCK",
  "OPERATOR PRESENCE SYSTEM",
  "PARK BRAKE",
  "EMERGENCY STOP",
  "FIRE SUPPRESSION",
  "BATTERY DISCONNECT",
  "MASTER DISCONNECT",

  /* -------------------- */
  /* POWERTRAIN DNA */
  /* -------------------- */

  "DIESEL ENGINE",
  "BATTERY ELECTRIC",
  "HYBRID POWERTRAIN",
  "TURBOCHARGED",
  "INTERCOOLED",
  "COMMON RAIL",
  "MECHANICAL INJECTION",
  "ELECTRONIC ENGINE",
  "REVERSING FAN",
  "HIGH CAPACITY COOLING",
  "BLOCK HEATER",
  "COLD WEATHER PACKAGE",

  /* -------------------- */
  /* ROTATING TELEHANDLER DNA */
  /* -------------------- */

  "ROTO",
  "OUTRIGGER PACKAGE",
  "STABILIZER PACKAGE",
  "REMOTE CONTROL READY",
  "WINCH READY",
  "JIB READY",

  /* -------------------- */
  /* HIGH CAPACITY DNA */
  /* -------------------- */

  "HEAVY DUTY BOOM",
  "HEAVY DUTY AXLES",
  "HIGH CAPACITY CARRIAGE",
  "ADDITIONAL COUNTERWEIGHT",
  "HEAVY COUNTERWEIGHT",
  "HIGH CAPACITY HYDRAULICS",

  /* -------------------- */
  /* AG / MULTIFARMER DNA */
  /* -------------------- */

  "AGRI PACKAGE",
  "AG PACKAGE",
  "MULTIFARMER",
  "THREE POINT HITCH",
  "REAR PTO",
  "FRONT PTO",
  "REAR HYDRAULICS",
  "HYDRAULIC TRAILER BRAKES",
  "PICKUP HITCH",
  "DRAWBAR",
  "TRAILER HITCH",
  "HYDRAULIC LOCKING CARRIAGE",

  /* -------------------- */
  /* CONTAINER / INDUSTRIAL DNA */
  /* -------------------- */

  "CONTAINER HANDLER",
  "TOP LIFT SPREADER",
  "SIDE PICK SPREADER",
  "TWIST LOCKS",
  "CONTAINER LOCKS",
  "INDUSTRIAL CARRIAGE",
  "HIGH CAPACITY FORK CARRIAGE",
  "LOW BOOM PIVOT",
  "HEAVY DUTY MAST STYLE CARRIAGE",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-DEF",
  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4",
  "TIER 4 FINAL",
  "T4F",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF",
  "DEF DELETE"
];

export default telehandlerDnaKeywords;
