const telehandlerDnaKeywords = [
  /* -------------------- */
  /* MACHINE TYPE DNA */
  /* -------------------- */

  "FIXED BOOM TELEHANDLER",
  "STRAIGHT BOOM TELEHANDLER",
  "ROTATING TELEHANDLER",
  "ROTO TELEHANDLER",
  "HIGH REACH TELEHANDLER",
  "HIGH CAPACITY TELEHANDLER",
  "COMPACT TELEHANDLER",
  "ROUGH TERRAIN TELEHANDLER",
  "INDUSTRIAL TELEHANDLER",
  "AG TELEHANDLER",
  "HEAVY LIFT TELEHANDLER",
  "CONTAINER TELEHANDLER",
  "ARTICULATED TELEHANDLER",
  "ELECTRIC TELEHANDLER",
  "HYBRID TELEHANDLER",

  /* -------------------- */
  /* CHASSIS DNA */
  /* -------------------- */

  "RIGID FRAME",
  "COMPACT CHASSIS",
  "LOW PROFILE CHASSIS",
  "HEAVY DUTY FRAME",
  "HIGH CAPACITY FRAME",
  "ROUGH TERRAIN CHASSIS",
  "ROTATING UPPER",
  "ROTO CHASSIS",
  "ARTICULATED CHASSIS",
  "FRAME LEVELING",
  "FRAME SWAY",
  "SELF LEVELING FRAME",
  "LEVELING FRAME",
  "STABILIZER CHASSIS",
  "OUTRIGGER CHASSIS",
  "COUNTERWEIGHTED CHASSIS",

  /* -------------------- */
  /* BOOM SYSTEM DNA */
  /* -------------------- */

  "FIXED BOOM",
  "STRAIGHT BOOM",
  "TELESCOPIC BOOM",
  "MULTI SECTION BOOM",
  "TWO SECTION BOOM",
  "THREE SECTION BOOM",
  "FOUR SECTION BOOM",
  "HIGH REACH BOOM",
  "HIGH CAPACITY BOOM",
  "HEAVY LIFT BOOM",
  "COMPACT BOOM",
  "LOW PROFILE BOOM",
  "BOOM EXTENSION",
  "BOOM RETRACTION",
  "BOOM FLOAT",
  "BOOM SUSPENSION",
  "BOOM RIDE CONTROL",
  "BOOM CYLINDERS",
  "BOOM ANGLE SENSOR",
  "BOOM EXTENSION SENSOR",
  "BOOM LOCK",
  "BOOM DAMPING",

  /* -------------------- */
  /* REACH SYSTEM DNA */
  /* -------------------- */

  "HIGH REACH",
  "LONG REACH",
  "COMPACT REACH",
  "TELESCOPIC REACH",
  "BOOM REACH",
  "REACH SENSOR",
  "REACH LIMITER",
  "REACH CONTROL",
  "BOOM LENGTH SENSOR",
  "LOAD CHART REACH SYSTEM",

  /* -------------------- */
  /* ROTATION DNA */
  /* -------------------- */

  "ROTATING TELEHANDLER",
  "ROTO TELEHANDLER",
  "ROTATING UPPER",
  "360 DEGREE ROTATION",
  "CONTINUOUS ROTATION",
  "NON CONTINUOUS ROTATION",
  "SLEW DRIVE",
  "SWING DRIVE",
  "SWING MOTOR",
  "SWING BRAKE",
  "ROTATION LOCK",
  "ROTARY MANIFOLD",
  "SLEW RING",
  "TURRET ROTATION",
  "ROTATING CARRIAGE",
  "SWING CARRIAGE",

  /* -------------------- */
  /* STABILIZER / OUTRIGGER DNA */
  /* -------------------- */

  "STABILIZERS",
  "OUTRIGGERS",
  "HYDRAULIC STABILIZERS",
  "HYDRAULIC OUTRIGGERS",
  "FRONT STABILIZERS",
  "REAR STABILIZERS",
  "FRONT OUTRIGGERS",
  "REAR OUTRIGGERS",
  "A FRAME OUTRIGGERS",
  "H TYPE OUTRIGGERS",
  "VERTICAL STABILIZERS",
  "SIDE SHIFT STABILIZERS",
  "VARIABLE OUTRIGGERS",
  "OUTRIGGER PADS",
  "OUTRIGGER POSITION SENSOR",
  "STABILIZER INTERLOCK",
  "AUTO LEVELING",
  "SELF LEVELING",
  "LEVELING JACKS",

  /* -------------------- */
  /* FORK CARRIAGE DNA */
  /* -------------------- */

  "STANDARD CARRIAGE",
  "WIDE CARRIAGE",
  "SIDE SHIFT",
  "SIDE SHIFT CARRIAGE",
  "FORK POSITIONER",
  "HYDRAULIC FORK POSITIONER",
  "SWING CARRIAGE",
  "ROTATING CARRIAGE",
  "TILT CARRIAGE",
  "FORK TILT",
  "CARRIAGE TILT",
  "FORK LEVELING",
  "CARRIAGE LEVELING",
  "PALLET FORKS",
  "HEAVY DUTY FORKS",
  "FLOATING FORKS",
  "HYDRAULIC FORKS",
  "FORK EXTENSIONS",
  "HOOK TYPE FORKS",
  "PIN TYPE FORKS",
  "LOAD BACKREST",
  "FORK LOCK",

  /* -------------------- */
  /* AUXILIARY HYDRAULIC DNA */
  /* -------------------- */

  "AUX HYDRAULICS",
  "AUXILIARY HYDRAULICS",
  "BOOM AUXILIARY HYDRAULICS",
  "CARRIAGE AUXILIARY HYDRAULICS",
  "FRONT AUXILIARY HYDRAULICS",
  "HIGH FLOW HYDRAULICS",
  "STANDARD FLOW HYDRAULICS",
  "LOW FLOW HYDRAULICS",
  "THIRD FUNCTION HYDRAULICS",
  "FOURTH FUNCTION HYDRAULICS",
  "MULTI FUNCTION HYDRAULICS",
  "ATTACHMENT HYDRAULICS",
  "HYDRAULIC QUICK COUPLERS",
  "FLAT FACE COUPLERS",
  "AUXILIARY HOSE KIT",
  "FLOW CONTROL",
  "PRESSURE CONTROL",
  "CONTINUOUS FLOW",

  /* -------------------- */
  /* ATTACHMENT DNA */
  /* -------------------- */

  "QUICK ATTACH",
  "HYDRAULIC QUICK ATTACH",
  "MANUAL QUICK ATTACH",
  "HYDRAULIC COUPLER",
  "MANUAL COUPLER",
  "TELEHANDLER CARRIAGE",
  "UNIVERSAL CARRIAGE",
  "JCB Q-FIT",
  "MANITOU CARRIAGE",
  "MERLO CARRIAGE",
  "JLG CARRIAGE",
  "GENIE CARRIAGE",
  "PALLET FORKS",
  "BUCKET",
  "LIGHT MATERIAL BUCKET",
  "GRAPPLE BUCKET",
  "TRUSS BOOM",
  "LIFTING JIB",
  "JIB",
  "WINCH",
  "HOOK ATTACHMENT",
  "CRANE BOOM",
  "MATERIAL HANDLING ARM",
  "WORK PLATFORM READY",
  "PERSONNEL PLATFORM READY",
  "MAN BASKET READY",
  "SWEEPING BROOM",
  "BALE SPEAR",
  "BALE CLAMP",
  "SIDE SHIFT ATTACHMENT",
  "FORK POSITIONER ATTACHMENT",
  "CONTAINER SPREADER",

  /* -------------------- */
  /* DRIVE SYSTEM DNA */
  /* -------------------- */

  "2WD",
  "4WD",
  "ALL WHEEL DRIVE",
  "HYDROSTATIC",
  "HYDROSTATIC DRIVE",
  "POWERSHIFT",
  "TORQUE CONVERTER",
  "DIRECT DRIVE",
  "CVT",
  "VARIPOWER",
  "ELECTRIC DRIVE",
  "TWO SPEED",
  "CREEP MODE",
  "INCHING PEDAL",
  "DRIVE MODE SELECT",
  "TRAVEL DRIVE",
  "PLANETARY FINAL DRIVE",
  "DIFFERENTIAL LOCK",
  "LIMITED SLIP DIFFERENTIAL",
  "TRACTION CONTROL",

  /* -------------------- */
  /* STEERING DNA */
  /* -------------------- */

  "ALL WHEEL STEER",
  "FOUR WHEEL STEER",
  "FRONT WHEEL STEER",
  "REAR WHEEL STEER",
  "CRAB STEER",
  "COORDINATED STEER",
  "ROUND STEER",
  "HYDRAULIC STEERING",
  "POWER STEERING",
  "STEERING AXLE",
  "OSCILLATING AXLE",
  "FRAME LEVELING",
  "SWAY CONTROL",
  "SELF LEVELING",
  "AUTO LEVELING",

  /* -------------------- */
  /* SUSPENSION DNA */
  /* -------------------- */

  "BOOM SUSPENSION",
  "RIDE CONTROL",
  "LOAD CUSHION",
  "HYDRAULIC SUSPENSION",
  "AXLE SUSPENSION",
  "OSCILLATING AXLE",
  "LOCKING AXLE",
  "FLOATING AXLE",
  "FRAME LEVELING",
  "SWAY FRAME",
  "LOAD STABILIZATION",

  /* -------------------- */
  /* HYDRAULIC SYSTEM DNA */
  /* -------------------- */

  "OPEN CENTER HYDRAULICS",
  "CLOSED CENTER HYDRAULICS",
  "LOAD SENSING HYDRAULICS",
  "PRESSURE COMPENSATED HYDRAULICS",
  "VARIABLE DISPLACEMENT PUMP",
  "PISTON PUMP",
  "GEAR PUMP",
  "HYDRAULIC COOLER",
  "HYDRAULIC FILTER",
  "ELECTROHYDRAULIC CONTROLS",
  "PROPORTIONAL HYDRAULICS",
  "BOOM HYDRAULICS",
  "CARRIAGE HYDRAULICS",
  "OUTRIGGER HYDRAULICS",
  "STABILIZER HYDRAULICS",
  "ATTACHMENT HYDRAULICS",
  "HYDRAULIC FLOW CONTROL",
  "HYDRAULIC PRESSURE CONTROL",

  /* -------------------- */
  /* BOOM SUSPENSION DNA */
  /* -------------------- */

  "BOOM SUSPENSION",
  "BOOM RIDE CONTROL",
  "LOAD CUSHION",
  "HYDRAULIC BOOM SUSPENSION",
  "ACCUMULATOR BOOM SUSPENSION",
  "BOOM DAMPING",
  "RIDE CONTROL ACCUMULATOR",

  /* -------------------- */
  /* CAB / OPERATOR DNA */
  /* -------------------- */

  "OPEN ROPS",
  "ROPS",
  "FOPS",
  "C/H/A",
  "ENCLOSED CAB",
  "AIR CONDITIONED CAB",
  "HEATED CAB",
  "PRESSURIZED CAB",
  "LOW PROFILE CAB",
  "HIGH VISIBILITY CAB",
  "PANORAMIC CAB",
  "DELUXE CAB",
  "SUSPENSION SEAT",
  "AIR RIDE SEAT",
  "HEATED SEAT",
  "SWIVEL SEAT",
  "TILTING CAB",
  "CAB GUARDING",
  "ROOF WINDOW",
  "REAR CAMERA",
  "SIDE CAMERA",
  "CAMERA SYSTEM",
  "360 CAMERA",
  "LED LIGHTS",
  "HALOGEN LIGHTS",
  "WORK LIGHT PACKAGE",
  "BEACON",

  /* -------------------- */
  /* LOAD MANAGEMENT DNA */
  /* -------------------- */

  "LOAD MOMENT INDICATOR",
  "LMI",
  "LOAD MANAGEMENT SYSTEM",
  "LOAD SCALE",
  "LOAD WEIGHING SYSTEM",
  "LOAD CHART SYSTEM",
  "LOAD LIMITER",
  "OVERLOAD PROTECTION",
  "STABILITY CONTROL",
  "BOOM ANGLE SENSOR",
  "BOOM LENGTH SENSOR",
  "REACH SENSOR",
  "HEIGHT LIMITER",
  "REACH LIMITER",
  "OUTRIGGER POSITION SENSOR",
  "STABILIZER POSITION SENSOR",
  "CARRIAGE POSITION SENSOR",
  "ANTI TIP SYSTEM",
  "LOAD HOLDING VALVES",

  /* -------------------- */
  /* AUTOMATION / TELEMATICS DNA */
  /* -------------------- */

  "TELEMATICS",
  "REMOTE DIAGNOSTICS",
  "GPS TRACKING",
  "FLEET MANAGEMENT",
  "REMOTE MONITORING",
  "LOAD DATA LOGGING",
  "SERVICE MONITOR",
  "MACHINE MONITORING",
  "ACCESS CONTROL",
  "PIN CODE START",
  "KEYLESS START",
  "AUTO IDLE",
  "AUTO SHUTDOWN",
  "WORK ZONE LIMITING",
  "HEIGHT LIMIT CONTROL",
  "BOOM POSITION MEMORY",
  "DIAGNOSTIC DISPLAY",

  /* -------------------- */
  /* TIRE DNA */
  /* -------------------- */

  "PNEUMATIC TIRES",
  "SOLID TIRES",
  "FOAM FILLED TIRES",
  "INDUSTRIAL TIRES",
  "ROUGH TERRAIN TIRES",
  "FLOTATION TIRES",
  "TRACTION TIRES",
  "NON MARKING TIRES",
  "AIR FILLED TIRES",
  "POLY TIRES",
  "SUPER ELASTIC TIRES",
  "WIDE TIRES",
  "NARROW TIRES",
  "DUAL TIRES",

  /* -------------------- */
  /* LIFT SYSTEM DNA */
  /* -------------------- */

  "HIGH REACH",
  "HIGH LIFT",
  "HIGH CAPACITY",
  "HEAVY LIFT",
  "BOOM LIFT CYLINDERS",
  "LIFT CYLINDERS",
  "CUSHIONED LOWERING",
  "LOAD CUSHION",
  "LIFT LOCKOUT",
  "HEIGHT LIMITER",
  "LOAD STABILIZER",
  "BOOM HOLDING VALVES",
  "BOOM LOWERING CONTROL",

  /* -------------------- */
  /* CONTROL SYSTEM DNA */
  /* -------------------- */

  "JOYSTICK CONTROLS",
  "SINGLE JOYSTICK",
  "DUAL JOYSTICK",
  "PILOT CONTROLS",
  "ELECTROHYDRAULIC CONTROLS",
  "FINGERTIP CONTROLS",
  "PROPORTIONAL CONTROLS",
  "MULTIFUNCTION JOYSTICK",
  "STEERING COLUMN CONTROLS",
  "INCHING PEDAL",
  "DIRECTIONAL CONTROL LEVER",
  "SIDE SHIFT CONTROL",
  "FORK POSITIONER CONTROL",
  "AUXILIARY HYDRAULIC CONTROL",
  "DRIVE MODE SELECT",
  "WORK MODE SELECT",

  /* -------------------- */
  /* SAFETY DNA */
  /* -------------------- */

  "OVERLOAD PROTECTION",
  "LOAD LIMITER",
  "ANTI TIP SYSTEM",
  "STABILITY CONTROL",
  "OBJECT DETECTION",
  "PROXIMITY SENSOR",
  "REAR CAMERA",
  "360 CAMERA",
  "BACKUP ALARM",
  "TRAVEL ALARM",
  "SEAT BELT INTERLOCK",
  "OPERATOR PRESENCE SYSTEM",
  "BOOM LOCK",
  "PARK BRAKE",
  "EMERGENCY STOP",
  "FIRE SUPPRESSION",
  "BATTERY DISCONNECT",
  "MASTER DISCONNECT",

  /* -------------------- */
  /* POWERTRAIN DNA */
  /* -------------------- */

  "DIESEL ENGINE",
  "ELECTRIC TELEHANDLER",
  "BATTERY ELECTRIC",
  "HYBRID POWERTRAIN",
  "TURBOCHARGED",
  "INTERCOOLED",
  "COMMON RAIL",
  "MECHANICAL INJECTION",
  "ELECTRONIC ENGINE",
  "AUTO IDLE",
  "AUTO SHUTDOWN",
  "REVERSING FAN",
  "HIGH CAPACITY COOLING",
  "BLOCK HEATER",
  "COLD WEATHER PACKAGE",

  /* -------------------- */
  /* ROTATING TELEHANDLER DNA */
  /* -------------------- */

  "ROTO",
  "ROTO TELEHANDLER",
  "ROTATING TELEHANDLER",
  "ROTATING UPPER",
  "360 DEGREE ROTATION",
  "CONTINUOUS ROTATION",
  "OUTRIGGER PACKAGE",
  "STABILIZER PACKAGE",
  "TURRET ROTATION",
  "SLEW RING",
  "SLEW DRIVE",
  "ROTATION LOCK",
  "REMOTE CONTROL READY",
  "WORK PLATFORM READY",
  "WINCH READY",
  "JIB READY",

  /* -------------------- */
  /* HIGH CAPACITY DNA */
  /* -------------------- */

  "HIGH CAPACITY",
  "HEAVY LIFT",
  "HIGH CAPACITY FRAME",
  "HEAVY DUTY BOOM",
  "HEAVY DUTY AXLES",
  "HIGH CAPACITY CARRIAGE",
  "HEAVY DUTY FORKS",
  "ADDITIONAL COUNTERWEIGHT",
  "HEAVY COUNTERWEIGHT",
  "HIGH CAPACITY HYDRAULICS",
  "LOAD CHART SYSTEM",
  "LOAD MOMENT INDICATOR",

  /* -------------------- */
  /* AG / MULTIFARMER DNA */
  /* -------------------- */

  "AGRI PACKAGE",
  "AG PACKAGE",
  "MULTIFARMER",
  "THREE POINT HITCH",
  "REAR PTO",
  "FRONT PTO",
  "REAR HYDRAULICS",
  "HYDRAULIC TRAILER BRAKES",
  "PICKUP HITCH",
  "DRAWBAR",
  "TRAILER HITCH",
  "CVT",
  "VARIPOWER",
  "BOOM SUSPENSION",
  "HYDRAULIC LOCKING CARRIAGE",

  /* -------------------- */
  /* CONTAINER / INDUSTRIAL DNA */
  /* -------------------- */

  "CONTAINER HANDLER",
  "CONTAINER SPREADER",
  "TOP LIFT SPREADER",
  "SIDE PICK SPREADER",
  "TWIST LOCKS",
  "CONTAINER LOCKS",
  "INDUSTRIAL CARRIAGE",
  "HIGH CAPACITY FORK CARRIAGE",
  "SOLID TIRES",
  "INDUSTRIAL TIRES",
  "LOW BOOM PIVOT",
  "HEAVY DUTY MAST STYLE CARRIAGE",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-DEF",
  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4",
  "TIER 4 FINAL",
  "T4F",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF",
  "DEF DELETE"
];

export default telehandlerDnaKeywords;
