// TRAILERS

const trailersTaxonomy = [
  // ASPHALT TRAILERS

{ make: "ASPHALT TRAILERS", model: "ETNYRE" },
{ make: "ASPHALT TRAILERS", model: "POLAR" },
{ make: "ASPHALT TRAILERS", model: "HEIL" },
{ make: "ASPHALT TRAILERS", model: "HARMON" },
{ make: "ASPHALT TRAILERS", model: "FRUEHAUF" },
{ make: "ASPHALT TRAILERS", model: "RETESA" },
{ make: "ASPHALT TRAILERS", model: "LBT" },
{ make: "ASPHALT TRAILERS", model: "TRAILMOBILE" },
{ make: "ASPHALT TRAILERS", model: "ADVANCE" },
{ make: "ASPHALT TRAILERS", model: "BRENNER" },
{ make: "ASPHALT TRAILERS", model: "ACRO" },
{ make: "ASPHALT TRAILERS", model: "BEALL" },
{ make: "ASPHALT TRAILERS", model: "BELL" },
{ make: "ASPHALT TRAILERS", model: "BUTLER" },
{ make: "ASPHALT TRAILERS", model: "FALCON" },
{ make: "ASPHALT TRAILERS", model: "JAMIESON" },
{ make: "ASPHALT TRAILERS", model: "KERSTEN" },
{ make: "ASPHALT TRAILERS", model: "MAC LTT" },
{ make: "ASPHALT TRAILERS", model: "MARATHON" },
{ make: "ASPHALT TRAILERS", model: "PENSKE" },
{ make: "ASPHALT TRAILERS", model: "PIONEER" },
{ make: "ASPHALT TRAILERS", model: "REMTEC" },
{ make: "ASPHALT TRAILERS", model: "TRETESA" },
{ make: "ASPHALT TRAILERS", model: "ROSCO" },
{ make: "ASPHALT TRAILERS", model: "STE" },
{ make: "ASPHALT TRAILERS", model: "TRAILMASTER" },
{ make: "ASPHALT TRAILERS", model: "VIM" },
{ make: "ASPHALT TRAILERS", model: "WESTMARK" },
{ make: "ASPHALT TRAILERS", model: "OTHER" },

  // BEVERAGE TRAILERS

{ make: "BEVERAGE TRAILERS", model: "HACKNEY" },
{ make: "BEVERAGE TRAILERS", model: "HESSE" },
{ make: "BEVERAGE TRAILERS", model: "HYUNDAI" },
{ make: "BEVERAGE TRAILERS", model: "MICKEY" },
{ make: "BEVERAGE TRAILERS", model: "PARCO-HESSE" },
{ make: "BEVERAGE TRAILERS", model: "OTHER" },

  // BLADE / TOWER TRAILERS

{ make: "BLADE / TOWER TRAILERS", model: "TRAIL KING" },
{ make: "BLADE / TOWER TRAILERS", model: "TEMISKO" },
{ make: "BLADE / TOWER TRAILERS", model: "XL SPECIALIZED" },
{ make: "BLADE / TOWER TRAILERS", model: "ASPEN" },
{ make: "BLADE / TOWER TRAILERS", model: "FAYMONVILLE" },
{ make: "BLADE / TOWER TRAILERS", model: "BOLSTER" },
{ make: "BLADE / TOWER TRAILERS", model: "LIDDELL" },
{ make: "BLADE / TOWER TRAILERS", model: "MASTER SOLUTIONS" },
{ make: "BLADE / TOWER TRAILERS", model: "GOLDHOFER" },
{ make: "BLADE / TOWER TRAILERS", model: "LOADCRAFT" },
{ make: "BLADE / TOWER TRAILERS", model: "SUPERIOR" },
{ make: "BLADE / TOWER TRAILERS", model: "OTHER" },

  // BOTTOM DUMP TRAILERS

{ make: "BOTTOM DUMP TRAILERS", model: "RANCO" },
{ make: "BOTTOM DUMP TRAILERS", model: "ARMOR LITE" },
{ make: "BOTTOM DUMP TRAILERS", model: "CPS" },
{ make: "BOTTOM DUMP TRAILERS", model: "MIDLAND" },
{ make: "BOTTOM DUMP TRAILERS", model: "ARNES" },
{ make: "BOTTOM DUMP TRAILERS", model: "MANAC" },
{ make: "BOTTOM DUMP TRAILERS", model: "CONST TRLR SPEC" },
{ make: "BOTTOM DUMP TRAILERS", model: "RENEGADE" },
{ make: "BOTTOM DUMP TRAILERS", model: "DURA HALL" },
{ make: "BOTTOM DUMP TRAILERS", model: "EXA" },
{ make: "BOTTOM DUMP TRAILERS", model: "ACE" },
{ make: "BOTTOM DUMP TRAILERS", model: "BEALL" },
{ make: "BOTTOM DUMP TRAILERS", model: "BRAZOS" },
{ make: "BOTTOM DUMP TRAILERS", model: "CLEMENT" },
{ make: "BOTTOM DUMP TRAILERS", model: "CROSS COUNTRY" },
{ make: "BOTTOM DUMP TRAILERS", model: "CUSTOM BUILT" },
{ make: "BOTTOM DUMP TRAILERS", model: "DECAP" },
{ make: "BOTTOM DUMP TRAILERS", model: "DOEPKER" },
{ make: "BOTTOM DUMP TRAILERS", model: "FRUEHAUF" },
{ make: "BOTTOM DUMP TRAILERS", model: "GALLEGOS" },
{ make: "BOTTOM DUMP TRAILERS", model: "HARD CORE" },
{ make: "BOTTOM DUMP TRAILERS", model: "IOWA TRAILER" },
{ make: "BOTTOM DUMP TRAILERS", model: "IRON LITE" },
{ make: "BOTTOM DUMP TRAILERS", model: "LOAD KING" },
{ make: "BOTTOM DUMP TRAILERS", model: "LOADLINE" },
{ make: "BOTTOM DUMP TRAILERS", model: "LOEWEN" },
{ make: "BOTTOM DUMP TRAILERS", model: "MIDLAND" },
{ make: "BOTTOM DUMP TRAILERS", model: "PUMA" },
{ make: "BOTTOM DUMP TRAILERS", model: "RED RIVER" },
{ make: "BOTTOM DUMP TRAILERS", model: "R-WAY" },
{ make: "BOTTOM DUMP TRAILERS", model: "TRAIL KING" },
{ make: "BOTTOM DUMP TRAILERS", model: "TRAVIS" },
{ make: "BOTTOM DUMP TRAILERS", model: "TTSA" },
{ make: "BOTTOM DUMP TRAILERS", model: "OTHER" },

  // CAR CARRIER TRAILERS

{ make: "CAR CARRIER TRAILERS", model: "COTTRELL" },
{ make: "CAR CARRIER TRAILERS", model: "SUN COUNTRY" },
{ make: "CAR CARRIER TRAILERS", model: "KAUFMAN" },
{ make: "CAR CARRIER TRAILERS", model: "LOHR" },
{ make: "CAR CARRIER TRAILERS", model: "BUCKEYE HAULER" },
{ make: "CAR CARRIER TRAILERS", model: "JJ TRAILER" },
{ make: "CAR CARRIER TRAILERS", model: "WALLY-MO" },
{ make: "CAR CARRIER TRAILERS", model: "KENTUCKY" },
{ make: "CAR CARRIER TRAILERS", model: "SUN VALLEY" },
{ make: "CAR CARRIER TRAILERS", model: "BOYDSTON" },
{ make: "CAR CARRIER TRAILERS", model: "BOYDSTUN" },
{ make: "CAR CARRIER TRAILERS", model: "GREAT DANE" },
{ make: "CAR CARRIER TRAILERS", model: "SHOP BILT" },
{ make: "CAR CARRIER TRAILERS", model: "TEXAS PRIDE" },
{ make: "CAR CARRIER TRAILERS", model: "SUN VALLEY" },
{ make: "CAR CARRIER TRAILERS", model: "OTHER" },

// CHEMICAL / ACID TANK TRAILERS

{ make: "CHEMICAL / ACID TANK TRAILERS", model: "POLAR" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "BRENNER" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "STE" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "HEIL" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "TREMCAR" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "FRUEHAUF" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "COMPTANK" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "MAC LTT" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "WABASH" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "BULK" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "ACRO" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "BAR-BEL" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "BEALL" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "BULK" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "ETNYRE" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "JAMIESON" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "KARIKOOL" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "KROHNERT" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "NOVA" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "OMNI" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "ROADRUNNER'" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "STEPHENS" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "SUNSHINE" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "TANKCON" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "TRAILMASTER" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "TROXELL" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "TSC" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "WABASH" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "WALKER" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "WESTMARK" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "WILCO" },
{ make: "CHEMICAL / ACID TANK TRAILERS", model: "OTHER" },
  // CHIP TRAILERS

{ make: "CHIP TRAILERS", model: "ALLIED" },
{ make: "CHIP TRAILERS", model: "ALLOY" },
{ make: "CHIP TRAILERS", model: "BARKER" },
{ make: "CHIP TRAILERS", model: "CUSTOM" },
{ make: "CHIP TRAILERS", model: "DORSEY" },
{ make: "CHIP TRAILERS", model: "IMCO IDAHO" },
{ make: "CHIP TRAILERS", model: "ITI" },
{ make: "CHIP TRAILERS", model: "KALYAN SEIBERT" },
{ make: "CHIP TRAILERS", model: "MAC" },
{ make: "CHIP TRAILERS", model: "MANAC" },
{ make: "CHIP TRAILERS", model: "NABORS" },
{ make: "CHIP TRAILERS", model: "PEERLESS" },
{ make: "CHIP TRAILERS", model: "BEALL" },
{ make: "CHIP TRAILERS", model: "BYRNE" },
{ make: "CHIP TRAILERS", model: "COLOMBIA" },
{ make: "CHIP TRAILERS", model: "FRONTIER" },
{ make: "CHIP TRAILERS", model: "GREAT DANE" },
{ make: "CHIP TRAILERS", model: "JD BERTOLINI" },
{ make: "CHIP TRAILERS", model: "PIERCE" },
{ make: "CHIP TRAILERS", model: "PITTS" },
{ make: "CHIP TRAILERS", model: "STOODLEY" },
{ make: "CHIP TRAILERS", model: "TEMISKO" },
{ make: "CHIP TRAILERS", model: "TYCROP" },
{ make: "CHIP TRAILERS", model: "OTHER" },
  
 // CRUDE OIL TRAILERS

{ make: "CRUDE OIL TRAILERS", model: "HEIL" },
{ make: "CRUDE OIL TRAILERS", model: "STEPHENS" },
{ make: "CRUDE OIL TRAILERS", model: "DRAGON PRODUCTS" },
{ make: "CRUDE OIL TRAILERS", model: "POLAR" },
{ make: "CRUDE OIL TRAILERS", model: "ADVANCE" },
{ make: "CRUDE OIL TRAILERS", model: "VANTAGE" },
{ make: "CRUDE OIL TRAILERS", model: "TREMCAR" },
{ make: "CRUDE OIL TRAILERS", model: "BRENNER" },
{ make: "CRUDE OIL TRAILERS", model: "LAZER INOX" },
{ make: "CRUDE OIL TRAILERS", model: "JASPER" },
{ make: "CRUDE OIL TRAILERS", model: "ACRO" },
{ make: "CRUDE OIL TRAILERS", model: "BEALL" },
{ make: "CRUDE OIL TRAILERS", model: "BTR" },
{ make: "CRUDE OIL TRAILERS", model: "CUSTOM" },
{ make: "CRUDE OIL TRAILERS", model: "DOWNS" },
{ make: "CRUDE OIL TRAILERS", model: "ETNYRE" },
{ make: "CRUDE OIL TRAILERS", model: "FRUEHAUF" },
{ make: "CRUDE OIL TRAILERS", model: "HAMMS" },
{ make: "CRUDE OIL TRAILERS", model: "HUTCHISON" },
{ make: "CRUDE OIL TRAILERS", model: "MAC LTT" },
{ make: "CRUDE OIL TRAILERS", model: "MUELLER" },
{ make: "CRUDE OIL TRAILERS", model: "SCHLUTZ" },
{ make: "CRUDE OIL TRAILERS", model: "TRAILMASTER" },
{ make: "CRUDE OIL TRAILERS", model: "TROXELL" },
{ make: "CRUDE OIL TRAILERS", model: "TRUXTON" },
{ make: "CRUDE OIL TRAILERS", model: "TYTAL" },
{ make: "CRUDE OIL TRAILERS", model: "VIM" },
{ make: "CRUDE OIL TRAILERS", model: "WABASH" },
{ make: "CRUDE OIL TRAILERS", model: "WOLF INNOVATION" },
{ make: "CRUDE OIL TRAILERS", model: "OTHER" },

 // CURTAIN TRAILER

{ make: "CURTAIN TRAILER", model: "REITNOUR" },
{ make: "CURTAIN TRAILER", model: "UTILITY" },
{ make: "CURTAIN TRAILER", model: "MANAC" },
{ make: "CURTAIN TRAILER", model: "MAC TRAILER MFG" },
{ make: "CURTAIN TRAILER", model: "GREAT DANE" },
{ make: "CURTAIN TRAILER", model: "MAXITRANS" },
{ make: "CURTAIN TRAILER", model: "NUVAN" },
{ make: "CURTAIN TRAILER", model: "VAWDREY" },
{ make: "CURTAIN TRAILER", model: "FONTAINE" },
{ make: "CURTAIN TRAILER", model: "EAST" },
{ make: "CURTAIN TRAILER", model: "AAA" },
{ make: "CURTAIN TRAILER", model: "ALUTREC" },
{ make: "CURTAIN TRAILER", model: "BARKER" },
{ make: "CURTAIN TRAILER", model: "BENSON" },
{ make: "CURTAIN TRAILER", model: "DORSEY" },
{ make: "CURTAIN TRAILER", model: "EXTREME TRAILERS" },
{ make: "CURTAIN TRAILER", model: "FREIGHTER" },
{ make: "CURTAIN TRAILER", model: "FREIGHTMORE TRANSPORT" },
{ make: "CURTAIN TRAILER", model: "FRUEHAUF" },
{ make: "CURTAIN TRAILER", model: "HYUNDAI" },
{ make: "CURTAIN TRAILER", model: "KRUEGER" },
{ make: "CURTAIN TRAILER", model: "LOAD KING" },
{ make: "CURTAIN TRAILER", model: "LODE KING" },
{ make: "CURTAIN TRAILER", model: "MEYER" },
{ make: "CURTAIN TRAILER", model: "RAVENS" },
{ make: "CURTAIN TRAILER", model: "ROADMASTER" },
{ make: "CURTAIN TRAILER", model: "ROLAND" },
{ make: "CURTAIN TRAILER", model: "SOUTHERN CROSS" },
{ make: "CURTAIN TRAILER", model: "SUPERIOR" },
{ make: "CURTAIN TRAILER", model: "TMC TRAILERS" },
{ make: "CURTAIN TRAILER", model: "TOP START" },
{ make: "CURTAIN TRAILER", model: "TRANSCRAFT" },
{ make: "CURTAIN TRAILER", model: "WABASH" },
{ make: "CURTAIN TRAILER", model: "WILSON" },
{ make: "CURTAIN TRAILER", model: "WESTERN TRAILERS" },
{ make: "CURTAIN TRAILER", model: "OTHER" },

  // DOUBLE DROP TRAILERS

{ make: "DOUBLE DROP TRAILERS", model: "XL SPECIALIZED" },
{ make: "DOUBLE DROP TRAILERS", model: "FONTAINE" },
{ make: "DOUBLE DROP TRAILERS", model: "TRAIL KING" },
{ make: "DOUBLE DROP TRAILERS", model: "ALPHA HD" },
{ make: "DOUBLE DROP TRAILERS", model: "BRANDT" },
{ make: "DOUBLE DROP TRAILERS", model: "JET" },
{ make: "DOUBLE DROP TRAILERS", model: "KALYN SIEBERT" },
{ make: "DOUBLE DROP TRAILERS", model: "MANAC" },
{ make: "DOUBLE DROP TRAILERS", model: "MUV-ALL" },
{ make: "DOUBLE DROP TRAILERS", model: "TALBERT" },
{ make: "DOUBLE DROP TRAILERS", model: "ATOKA" },
{ make: "DOUBLE DROP TRAILERS", model: "BWS" },
{ make: "DOUBLE DROP TRAILERS", model: "DORSEY" },
{ make: "DOUBLE DROP TRAILERS", model: "ETNYRE" },
{ make: "DOUBLE DROP TRAILERS", model: "EXTREME" },
{ make: "DOUBLE DROP TRAILERS", model: "GLOBE" },
{ make: "DOUBLE DROP TRAILERS", model: "KAUFMAN" },
{ make: "DOUBLE DROP TRAILERS", model: "LANDOLL" },
{ make: "DOUBLE DROP TRAILERS", model: "LEDWELL" },
{ make: "DOUBLE DROP TRAILERS", model: "OVERBILT" },
{ make: "DOUBLE DROP TRAILERS", model: "PAISANO" },
{ make: "DOUBLE DROP TRAILERS", model: "TALBERT" },
{ make: "DOUBLE DROP TRAILERS", model: "TEMISKO" },
{ make: "DOUBLE DROP TRAILERS", model: "WALTRON" },
{ make: "DOUBLE DROP TRAILERS", model: "WILSON" },
{ make: "DOUBLE DROP TRAILERS", model: "OTHER" },

  // DROP DECK TRAILERS

{ make: "DROP DECK TRAILERS", model: "DORSEY" },
{ make: "DROP DECK TRAILERS", model: "FONTAINE" },
{ make: "DROP DECK TRAILERS", model: "REITNOUER" },
{ make: "DROP DECK TRAILERS", model: "MANAC" },
{ make: "DROP DECK TRAILERS", model: "WABASH" },
{ make: "DROP DECK TRAILERS", model: "TRANSCRAFT" },
{ make: "DROP DECK TRAILERS", model: "DOONAN" },
{ make: "DROP DECK TRAILERS", model: "NEVILLE BUILT" },
{ make: "DROP DECK TRAILERS", model: "DOONAN SPECIALIZED" },
{ make: "DROP DECK TRAILERS", model: "DEMCO" },
{ make: "DROP DECK TRAILERS", model: "AAA" },
{ make: "DROP DECK TRAILERS", model: "ACE" },
{ make: "DROP DECK TRAILERS", model: "BEHNKE" },
{ make: "DROP DECK TRAILERS", model: "BENSON" },
{ make: "DROP DECK TRAILERS", model: "BRAZOS" },
{ make: "DROP DECK TRAILERS", model: "BWS" },
{ make: "DROP DECK TRAILERS", model: "DEMCO" },
{ make: "DROP DECK TRAILERS", model: "DOEPKER" },
{ make: "DROP DECK TRAILERS", model: "DURA HALL" },
{ make: "DROP DECK TRAILERS", model: "EAST" },
{ make: "DROP DECK TRAILERS", model: "ETNYRE" },
{ make: "DROP DECK TRAILERS", model: "EXTREME" },
{ make: "DROP DECK TRAILERS", model: "FELLING" },
{ make: "DROP DECK TRAILERS", model: "FRUEHAUF" },
{ make: "DROP DECK TRAILERS", model: "FWR" },
{ make: "DROP DECK TRAILERS", model: "GINCOR" },
{ make: "DROP DECK TRAILERS", model: "GREAT DANE" },
{ make: "DROP DECK TRAILERS", model: "IRON LITE" },
{ make: "DROP DECK TRAILERS", model: "JAMIESON" },
{ make: "DROP DECK TRAILERS", model: "JET" },
{ make: "DROP DECK TRAILERS", model: "KAYLN SIEBERT" },
{ make: "DROP DECK TRAILERS", model: "KAUFMAN" },
{ make: "DROP DECK TRAILERS", model: "LANDOLL" },
{ make: "DROP DECK TRAILERS", model: "LEDWELL" },
{ make: "DROP DECK TRAILERS", model: "LOAD KING" },
{ make: "DROP DECK TRAILERS", model: "LOAD TRAIL" },
{ make: "DROP DECK TRAILERS", model: "LODE KING" },
{ make: "DROP DECK TRAILERS", model: "MAC TRLR" },
{ make: "DROP DECK TRAILERS", model: "MAS TRLR" },
{ make: "DROP DECK TRAILERS", model: "MAXITRANS" },
{ make: "DROP DECK TRAILERS", model: "MIDLAND" },
{ make: "DROP DECK TRAILERS", model: "MUV-ALL" },
{ make: "DROP DECK TRAILERS", model: "NUTTALL" },
{ make: "DROP DECK TRAILERS", model: "OVERBILT" },
{ make: "DROP DECK TRAILERS", model: "PITTS" },
{ make: "DROP DECK TRAILERS", model: "PRESTIGE" },
{ make: "DROP DECK TRAILERS", model: "RAJA" },
{ make: "DROP DECK TRAILERS", model: "RENN" },
{ make: "DROP DECK TRAILERS", model: "STONESTAR" },
{ make: "DROP DECK TRAILERS", model: "TALBERT" },
{ make: "DROP DECK TRAILERS", model: "TRAIL KING" },
{ make: "DROP DECK TRAILERS", model: "TRAILBOSS" },
{ make: "DROP DECK TRAILERS", model: "TRAIL-EZE" },
{ make: "DROP DECK TRAILERS", model: "WABASH" },
{ make: "DROP DECK TRAILERS", model: "VIKING" },
{ make: "DROP DECK TRAILERS", model: "WADE" },
{ make: "DROP DECK TRAILERS", model: "WILSON" },
{ make: "DROP DECK TRAILERS", model: "XL SPECIALIZED" },
{ make: "DROP DECK TRAILERS", model: "OTHER" },

  // END DUMP TRAILERS

{ make: "END DUMP TRAILERS", model: "MAC TRAILER MFG" },
{ make: "END DUMP TRAILERS", model: "EAST" },
{ make: "END DUMP TRAILERS", model: "TRAVIS" },
{ make: "END DUMP TRAILERS", model: "CLEMENT" },
{ make: "END DUMP TRAILERS", model: "ARMOR LITE" },
{ make: "END DUMP TRAILERS", model: "TRAILSTAR" },
{ make: "END DUMP TRAILERS", model: "ARNES" },
{ make: "END DUMP TRAILERS", model: "VANTAGE" },
{ make: "END DUMP TRAILERS", model: "CONSTR TRLR SPEC" },
{ make: "END DUMP TRAILERS", model: "RANCO" },
{ make: "END DUMP TRAILERS", model: "AFM" },
{ make: "END DUMP TRAILERS", model: "ALFAB" },
{ make: "END DUMP TRAILERS", model: "ALUMATECH" },
{ make: "END DUMP TRAILERS", model: "APM" },
{ make: "END DUMP TRAILERS", model: "ARTEX" },
{ make: "END DUMP TRAILERS", model: "BEALL" },
{ make: "END DUMP TRAILERS", model: "AXLE" },
{ make: "END DUMP TRAILERS", model: "BENSON" },
{ make: "END DUMP TRAILERS", model: "BRAZOS" },
{ make: "END DUMP TRAILERS", model: "BTE" },
{ make: "END DUMP TRAILERS", model: "CANCADE" },
{ make: "END DUMP TRAILERS", model: "CANUCK" },
{ make: "END DUMP TRAILERS", model: "CBB" },
{ make: "END DUMP TRAILERS", model: "CMC" },
{ make: "END DUMP TRAILERS", model: "COBRA" },
{ make: "END DUMP TRAILERS", model: "CORAS" },
{ make: "END DUMP TRAILERS", model: "CPS" },
{ make: "END DUMP TRAILERS", model: "CROSS COUNTRY" },
{ make: "END DUMP TRAILERS", model: "DELOUPE" },
{ make: "END DUMP TRAILERS", model: "DIERZEN" },
{ make: "END DUMP TRAILERS", model: "DOEPKER" },
{ make: "END DUMP TRAILERS", model: "DORSEY" },
{ make: "END DUMP TRAILERS", model: "DRAGON PRODUCTS" },
{ make: "END DUMP TRAILERS", model: "DURA HALL" },
{ make: "END DUMP TRAILERS", model: "E-PAK MFG" },
{ make: "END DUMP TRAILERS", model: "EVERLITE" },
{ make: "END DUMP TRAILERS", model: "EXA" },
{ make: "END DUMP TRAILERS", model: "FREIGHTMASTER" },
{ make: "END DUMP TRAILERS", model: "FREIGHTMORE TRANS" },
{ make: "END DUMP TRAILERS", model: "FRUEHAUF" },
{ make: "END DUMP TRAILERS", model: "GALLEGOS" },
{ make: "END DUMP TRAILERS", model: "GBB" },
{ make: "END DUMP TRAILERS", model: "GLOBE" },
{ make: "END DUMP TRAILERS", model: "GORSKI" },
{ make: "END DUMP TRAILERS", model: "GTC" },
{ make: "END DUMP TRAILERS", model: "H&H TRLR" },
{ make: "END DUMP TRAILERS", model: "HAHNZ" },
{ make: "END DUMP TRAILERS", model: "HAMELEX WHITE" },
{ make: "END DUMP TRAILERS", model: "HEIL" },
{ make: "END DUMP TRAILERS", model: "HERCULES" },
{ make: "END DUMP TRAILERS", model: "HICKS" },
{ make: "END DUMP TRAILERS", model: "HILBILT" },
{ make: "END DUMP TRAILERS", model: "HITCHCOCK" },
{ make: "END DUMP TRAILERS", model: "HOBBS" },
{ make: "END DUMP TRAILERS", model: "IRON LITE" },
{ make: "END DUMP TRAILERS", model: "JAMIESON" },
{ make: "END DUMP TRAILERS", model: "KRUZ" },
{ make: "END DUMP TRAILERS", model: "LOAD KING" },
{ make: "END DUMP TRAILERS", model: "LOADLINE" },
{ make: "END DUMP TRAILERS", model: "LOEWEN" },
{ make: "END DUMP TRAILERS", model: "LUFKIN" },
{ make: "END DUMP TRAILERS", model: "LUSTY" },
{ make: "END DUMP TRAILERS", model: "MANAC" },
{ make: "END DUMP TRAILERS", model: "MARS" },
{ make: "END DUMP TRAILERS", model: "MATE" },
{ make: "END DUMP TRAILERS", model: "MAXITRAN" },
{ make: "END DUMP TRAILERS", model: "MIDLAND" },
{ make: "END DUMP TRAILERS", model: "MONTONE" },
{ make: "END DUMP TRAILERS", model: "MOORE" },
{ make: "END DUMP TRAILERS", model: "MSR" },
{ make: "END DUMP TRAILERS", model: "MTM" },
{ make: "END DUMP TRAILERS", model: "MUSCAT" },
{ make: "END DUMP TRAILERS", model: "NUESTAR" },
{ make: "END DUMP TRAILERS", model: "NUTTALL" },
{ make: "END DUMP TRAILERS", model: "PALMER" },
{ make: "END DUMP TRAILERS", model: "PEAK" },
{ make: "END DUMP TRAILERS", model: "PUMA" },
{ make: "END DUMP TRAILERS", model: "RAGLAN" },
{ make: "END DUMP TRAILERS", model: "RANCO" },
{ make: "END DUMP TRAILERS", model: "RAVENS" },
{ make: "END DUMP TRAILERS", model: "RELIANCE" },
{ make: "END DUMP TRAILERS", model: "RENN" },
{ make: "END DUMP TRAILERS", model: "RHODES" },
{ make: "END DUMP TRAILERS", model: "ROUGHNECK" },
{ make: "END DUMP TRAILERS", model: "RTR MFG" },
{ make: "END DUMP TRAILERS", model: "SCHIEN" },
{ make: "END DUMP TRAILERS", model: "STARGATE" },
{ make: "END DUMP TRAILERS", model: "STECO" },
{ make: "END DUMP TRAILERS", model: "STONESTAR" },
{ make: "END DUMP TRAILERS", model: "SUMMIT" },
{ make: "END DUMP TRAILERS", model: "SUPERIOR" },
{ make: "END DUMP TRAILERS", model: "TEFCO" },
{ make: "END DUMP TRAILERS", model: "TI-BROOK" },
{ make: "END DUMP TRAILERS", model: "TITAN" },
{ make: "END DUMP TRAILERS", model: "TRAIL KING" },
{ make: "END DUMP TRAILERS", model: "TRIDENT" },
{ make: "END DUMP TRAILERS", model: "WARREN" },
{ make: "END DUMP TRAILERS", model: "OTHER" },

  // FLATBED TRAILERS

{ make: "FLATBED TRAILERS", model: "FONTAINE" },
{ make: "FLATBED TRAILERS", model: "REITNOUER" },
{ make: "FLATBED TRAILERS", model: "DORSEY" },
{ make: "FLATBED TRAILERS", model: "MANAC" },
{ make: "FLATBED TRAILERS", model: "GREAT DANE" },
{ make: "FLATBED TRAILERS", model: "EAST" },
{ make: "FLATBED TRAILERS", model: "MAC" },
{ make: "FLATBED TRAILERS", model: "UTILITY" },
{ make: "FLATBED TRAILERS", model: "TRANSCRAFT" },
{ make: "FLATBED TRAILERS", model: "WABASH" },
{ make: "FLATBED TRAILERS", model: "AAA" },
{ make: "FLATBED TRAILERS", model: "ALLOY" },
{ make: "FLATBED TRAILERS", model: "ALUTREC" },
{ make: "FLATBED TRAILERS", model: "AZTEC" },
{ make: "FLATBED TRAILERS", model: "BARKER" },
{ make: "FLATBED TRAILERS", model: "BENSON" },
{ make: "FLATBED TRAILERS", model: "BERG" },
{ make: "FLATBED TRAILERS", model: "BIG TEX" },
{ make: "FLATBED TRAILERS", model: "BRAZOS" },
{ make: "FLATBED TRAILERS", model: "CHAPARRAL" },
{ make: "FLATBED TRAILERS", model: "CLARK" },
{ make: "FLATBED TRAILERS", model: "CUSTOM BUILT" },
{ make: "FLATBED TRAILERS", model: "DELOUPE" },
{ make: "FLATBED TRAILERS", model: "DIRECT TRAILER" },
{ make: "FLATBED TRAILERS", model: "DOEPKER" },
{ make: "FLATBED TRAILERS", model: "DOONAN" },
{ make: "FLATBED TRAILERS", model: "DRAGON PRODUCTS" },
{ make: "FLATBED TRAILERS", model: "DYNAWELD" },
{ make: "FLATBED TRAILERS", model: "EAGER BEAVER" },
{ make: "FLATBED TRAILERS", model: "EXTREME TRAILERS" },
{ make: "FLATBED TRAILERS", model: "FELLING" },
{ make: "FLATBED TRAILERS", model: "FRUEHAUF" },
{ make: "FLATBED TRAILERS", model: "FWR" },
{ make: "FLATBED TRAILERS", model: "GINCOR" },
{ make: "FLATBED TRAILERS", model: "GOLDHOFER" },
{ make: "FLATBED TRAILERS", model: "HAULMARK" },
{ make: "FLATBED TRAILERS", model: "HOBBS" },
{ make: "FLATBED TRAILERS", model: "HYUNDAI" },
{ make: "FLATBED TRAILERS", model: "J SMITH & SONS" },
{ make: "FLATBED TRAILERS", model: "JAMIESON" },
{ make: "FLATBED TRAILERS", model: "JJ TRLR" },
{ make: "FLATBED TRAILERS", model: "KEARNEY" },
{ make: "FLATBED TRAILERS", model: "KRUEGER" },
{ make: "FLATBED TRAILERS", model: "KRUZ" },
{ make: "FLATBED TRAILERS", model: "LANDOLL" },
{ make: "FLATBED TRAILERS", model: "LEDWELL" },
{ make: "FLATBED TRAILERS", model: "LOAD KING" },
{ make: "FLATBED TRAILERS", model: "LOAD TRAIL" },
{ make: "FLATBED TRAILERS", model: "LOAD MAX" },
{ make: "FLATBED TRAILERS", model: "LODE KING" },
{ make: "FLATBED TRAILERS", model: "LOUGHLIN" },
{ make: "FLATBED TRAILERS", model: "LUFKIN" },
{ make: "FLATBED TRAILERS", model: "MAXITRANS" },
{ make: "FLATBED TRAILERS", model: "MIDLAND" },
{ make: "FLATBED TRAILERS", model: "MOORE" },
{ make: "FLATBED TRAILERS", model: "OPHEE" },
{ make: "FLATBED TRAILERS", model: "PITTS" },
{ make: "FLATBED TRAILERS", model: "PJ" },
{ make: "FLATBED TRAILERS", model: "PRESTIGE" },
{ make: "FLATBED TRAILERS", model: "PRO-HAUL" },
{ make: "FLATBED TRAILERS", model: "RAJA" },
{ make: "FLATBED TRAILERS", model: "RAVENS" },
{ make: "FLATBED TRAILERS", model: "REINKE" },
{ make: "FLATBED TRAILERS", model: "RELIANCE" },
{ make: "FLATBED TRAILERS", model: "RENN" },
{ make: "FLATBED TRAILERS", model: "RUCO" },
{ make: "FLATBED TRAILERS", model: "STONESTAR" },
{ make: "FLATBED TRAILERS", model: "THRU-WAY" },
{ make: "FLATBED TRAILERS", model: "TITAN" },
{ make: "FLATBED TRAILERS", model: "TRAIL KING" },
{ make: "FLATBED TRAILERS", model: "TOWMASTER" },
{ make: "FLATBED TRAILERS", model: "TRAIL-EZE" },
{ make: "FLATBED TRAILERS", model: "TRAILMOBILE" },
{ make: "FLATBED TRAILERS", model: "TRAIL TECH" },
{ make: "FLATBED TRAILERS", model: "VANGUARD" },
{ make: "FLATBED TRAILERS", model: "VIKING" },
{ make: "FLATBED TRAILERS", model: "WADE" },
{ make: "FLATBED TRAILERS", model: "WESTERN TRLR" },
{ make: "FLATBED TRAILERS", model: "WILSON" },
{ make: "FLATBED TRAILERS", model: "XL SPECIALIZED" },
{ make: "FLATBED TRAILERS", model: "OTHER" },

  // FRAC TRAILERS

{ make: "FRAC TRAILERS", model: "DRAGON PRODUCTS" },
{ make: "FRAC TRAILERS", model: "ROLLIGON" },
{ make: "FRAC TRAILERS", model: "HP TANK MFG" },
{ make: "FRAC TRAILERS", model: "PINNACLE" },
{ make: "FRAC TRAILERS", model: "SOUTHERN FRAC TANK" },
{ make: "FRAC TRAILERS", model: "STAR MFG" },
{ make: "FRAC TRAILERS", model: "WICHITA" },
{ make: "FRAC TRAILERS", model: "ACE" },
{ make: "FRAC TRAILERS", model: "CHANDLER" },
{ make: "FRAC TRAILERS", model: "GENECOR" },
{ make: "FRAC TRAILERS", model: "HY-TECH" },
{ make: "FRAC TRAILERS", model: "KALYN SIEBERT" },
{ make: "FRAC TRAILERS", model: "LOEWEN" },
{ make: "FRAC TRAILERS", model: "LORNES" },
{ make: "FRAC TRAILERS", model: "MERTZ" },
{ make: "FRAC TRAILERS", model: "SALTYS" },
{ make: "FRAC TRAILERS", model: "WATERFORD" },
{ make: "FRAC TRAILERS", model: "OTHER" },

  // FUEL TRAILERS

{ make: "FUEL TRAILERS", model: "HEIL" },
{ make: "FUEL TRAILERS", model: "POLAR" },
{ make: "FUEL TRAILERS", model: "MAC LTT" },
{ make: "FUEL TRAILERS", model: "BEALL" },
{ make: "FUEL TRAILERS", model: "LBT" },
{ make: "FUEL TRAILERS", model: "STEPHENS" },
{ make: "FUEL TRAILERS", model: "VANTAGE" },
{ make: "FUEL TRAILERS", model: "ADVANCE" },
{ make: "FUEL TRAILERS", model: "FRUEHAUF" },
{ make: "FUEL TRAILERS", model: "WELDIT" },
{ make: "FUEL TRAILERS", model: "BRENNER" },
{ make: "FUEL TRAILERS", model: "CIMC" },
{ make: "FUEL TRAILERS", model: "COLUMBIA" },
{ make: "FUEL TRAILERS", model: "CURRY SUPPLY" },
{ make: "FUEL TRAILERS", model: "CUSTOM BILT" },
{ make: "FUEL TRAILERS", model: "CUSTOM TRAILER" },
{ make: "FUEL TRAILERS", model: "CUSTOM TRAILERS INC" },
{ make: "FUEL TRAILERS", model: "ETNYRE" },
{ make: "FUEL TRAILERS", model: "HOCKNEY" },
{ make: "FUEL TRAILERS", model: "HOLMWOOD" },
{ make: "FUEL TRAILERS", model: "HUTCHINSON" },
{ make: "FUEL TRAILERS", model: "MARSHALL LETHLEAN" },
{ make: "FUEL TRAILERS", model: "OMEGA" },
{ make: "FUEL TRAILERS", model: "REMTEC" },
{ make: "FUEL TRAILERS", model: "TIEMAN" },
{ make: "FUEL TRAILERS", model: "TRAILMASTER" },
{ make: "FUEL TRAILERS", model: "TREMCAR" },
{ make: "FUEL TRAILERS", model: "VIM" },
{ make: "FUEL TRAILERS", model: "YOUNG" },
{ make: "FUEL TRAILERS", model: "OTHER" },

  // HOPPER - GRAIN TRAILERS

{ make: "HOPPER - GRAIN TRAILERS", model: "TIMPTE" },
{ make: "HOPPER - GRAIN TRAILERS", model: "WILSON" },
{ make: "HOPPER - GRAIN TRAILERS", model: "NEVILLE BUILT" },
{ make: "HOPPER - GRAIN TRAILERS", model: "DEMCO" },
{ make: "HOPPER - GRAIN TRAILERS", model: "LODE KING" },
{ make: "HOPPER - GRAIN TRAILERS", model: "DOEPKER" },
{ make: "HOPPER - GRAIN TRAILERS", model: "JET" },
{ make: "HOPPER - GRAIN TRAILERS", model: "CORNHUSKER" },
{ make: "HOPPER - GRAIN TRAILERS", model: "MERITT" },
{ make: "HOPPER - GRAIN TRAILERS", model: "STOUGHTON" },
{ make: "HOPPER - GRAIN TRAILERS", model: "ACE" },
{ make: "HOPPER - GRAIN TRAILERS", model: "ARMOR LITE" },
{ make: "HOPPER - GRAIN TRAILERS", model: "BERG" },
{ make: "HOPPER - GRAIN TRAILERS", model: "CONSTR TRLR SPEC" },
{ make: "HOPPER - GRAIN TRAILERS", model: "CPS" },
{ make: "HOPPER - GRAIN TRAILERS", model: "EBY" },
{ make: "HOPPER - GRAIN TRAILERS", model: "HAUL ALL" },
{ make: "HOPPER - GRAIN TRAILERS", model: "ITM" },
{ make: "HOPPER - GRAIN TRAILERS", model: "LEDWELL" },
{ make: "HOPPER - GRAIN TRAILERS", model: "LOADLINE" },
{ make: "HOPPER - GRAIN TRAILERS", model: "MAGNOLIA TRLR" },
{ make: "HOPPER - GRAIN TRAILERS", model: "MAURER" },
{ make: "HOPPER - GRAIN TRAILERS", model: "MAXXIM" },
{ make: "HOPPER - GRAIN TRAILERS", model: "PLATINUM" },
{ make: "HOPPER - GRAIN TRAILERS", model: "PRESTIGE" },
{ make: "HOPPER - GRAIN TRAILERS", model: "STAR" },
{ make: "HOPPER - GRAIN TRAILERS", model: "TAIPAN" },
{ make: "HOPPER - GRAIN TRAILERS", model: "TITAN" },
{ make: "HOPPER - GRAIN TRAILERS", model: "TRAIL KING" },
{ make: "HOPPER - GRAIN TRAILERS", model: "WARREN" },
{ make: "HOPPER - GRAIN TRAILERS", model: "WESTERN TRLR" },
{ make: "HOPPER - GRAIN TRAILERS", model: "WHEELER" },
{ make: "HOPPER - GRAIN TRAILERS", model: "WILKENS" },
{ make: "HOPPER - GRAIN TRAILERS", model: "OTHER" },

  // HORSE TRAILERS

{ make: "HORSE TRAILERS", model: "VALLEY TRAILERS" },
{ make: "HORSE TRAILERS", model: "BISON COACH" },
{ make: "HORSE TRAILERS", model: "CIMARRON" },
{ make: "HORSE TRAILERS", model: "SHADOW TRAILERS" },
{ make: "HORSE TRAILERS", model: "MERHOW" },
{ make: "HORSE TRAILERS", model: "SUNDOWNER" },
{ make: "HORSE TRAILERS", model: "BAR M TRAILERS" },
{ make: "HORSE TRAILERS", model: "TRAILS WEST" },
{ make: "HORSE TRAILERS", model: "FEATHERLITE" },
{ make: "HORSE TRAILERS", model: "HART" },
{ make: "HORSE TRAILERS", model: "4-STAR" },
{ make: "HORSE TRAILERS", model: "AMACSA" },
{ make: "HORSE TRAILERS", model: "BARRETT" },
{ make: "HORSE TRAILERS", model: "BELLAMY" },
{ make: "HORSE TRAILERS", model: "BIG VALLEY" },
{ make: "HORSE TRAILERS", model: "BLOOMER" },
{ make: "HORSE TRAILERS", model: "CALICO" },
{ make: "HORSE TRAILERS", model: "CHARMAC" },
{ make: "HORSE TRAILERS", model: "CM TRAILERS" },
{ make: "HORSE TRAILERS", model: "DELTA" },
{ make: "HORSE TRAILERS", model: "DIXIE" },
{ make: "HORSE TRAILERS", model: "DURALITE" },
{ make: "HORSE TRAILERS", model: "ECLIPSE" },
{ make: "HORSE TRAILERS", model: "ELITE TRAILER MFG" },
{ make: "HORSE TRAILERS", model: "EXISS" },
{ make: "HORSE TRAILERS", model: "FRONTIER" },
{ make: "HORSE TRAILERS", model: "GREAT DANE" },
{ make: "HORSE TRAILERS", model: "HAWK" },
{ make: "HORSE TRAILERS", model: "HOOSIER" },
{ make: "HORSE TRAILERS", model: "INTEGRITY" },
{ make: "HORSE TRAILERS", model: "KIEFER" },
{ make: "HORSE TRAILERS", model: "LAKOTA" },
{ make: "HORSE TRAILERS", model: "LEGEND" },
{ make: "HORSE TRAILERS", model: "LOGAN COACH" },
{ make: "HORSE TRAILERS", model: "MERHOW" },
{ make: "HORSE TRAILERS", model: "RIVER VALLEY" },
{ make: "HORSE TRAILERS", model: "S&S DURA LINE" },
{ make: "HORSE TRAILERS", model: "SHADOW TRAILERS" },
{ make: "HORSE TRAILERS", model: "SMC TRAILERS" },
{ make: "HORSE TRAILERS", model: "SOONER" },
{ make: "HORSE TRAILERS", model: "SUNDOWNER" },
{ make: "HORSE TRAILERS", model: "TRAILS WEST" },
{ make: "HORSE TRAILERS", model: "UNSPECIFIED" },
{ make: "HORSE TRAILERS", model: "OTHER" },

  // INDUSTRIAL GAS

{ make: "INDUSTRIAL GAS", model: "MISSISSIPPI" },
{ make: "INDUSTRIAL GAS", model: "WESTMOR INDUSTRIES" },
{ make: "INDUSTRIAL GAS", model: "LUBBOCK" },
{ make: "INDUSTRIAL GAS", model: "TRAMCO" },
{ make: "INDUSTRIAL GAS", model: "TRINITY INDUSTRIES INC." },
{ make: "INDUSTRIAL GAS", model: "DALWORTH" },
{ make: "INDUSTRIAL GAS", model: "FRUEHAUF" },
{ make: "INDUSTRIAL GAS", model: "EVANS" },
{ make: "INDUSTRIAL GAS", model: "POLAR" },
{ make: "INDUSTRIAL GAS", model: "BEAIRD" },
{ make: "INDUSTRIAL GAS", model: "ACRO" },
{ make: "INDUSTRIAL GAS", model: "BEDARD" },
{ make: "INDUSTRIAL GAS", model: "CHEROKEE" },
{ make: "INDUSTRIAL GAS", model: "COUNTRYSIDE" },
{ make: "INDUSTRIAL GAS", model: "CRYENCO" },
{ make: "INDUSTRIAL GAS", model: "DALLAS" },
{ make: "INDUSTRIAL GAS", model: "DELTA" },
{ make: "INDUSTRIAL GAS", model: "ENDERBY ANDERSON" },
{ make: "INDUSTRIAL GAS", model: "KLEESPIE" },
{ make: "INDUSTRIAL GAS", model: "MARSHALL LETHLEAN" },
{ make: "INDUSTRIAL GAS", model: "MAXFIELD" },
{ make: "INDUSTRIAL GAS", model: "MINNESOTA" },
{ make: "INDUSTRIAL GAS", model: "SUPERIOR" },
{ make: "INDUSTRIAL GAS", model: "TRINITY" },
{ make: "INDUSTRIAL GAS", model: "OTHER" },

 // LIQUID FOOD GRADE

{ make: "LIQUID FOOD GRADE", model: "WALKER" },
{ make: "LIQUID FOOD GRADE", model: "POLAR" },
{ make: "LIQUID FOOD GRADE", model: "BRENNAR" },
{ make: "LIQUID FOOD GRADE", model: "STE" },
{ make: "LIQUID FOOD GRADE", model: "TREMCAR" },
{ make: "LIQUID FOOD GRADE", model: "BULK" },
{ make: "LIQUID FOOD GRADE", model: "MAC LTT" },
{ make: "LIQUID FOOD GRADE", model: "WABASH" },
{ make: "LIQUID FOOD GRADE", model: "WESTMARK" },
{ make: "LIQUID FOOD GRADE", model: "BAR-BEL" },
{ make: "LIQUID FOOD GRADE", model: "ALMOUNT" },
{ make: "LIQUID FOOD GRADE", model: "BEALL" },
{ make: "LIQUID FOOD GRADE", model: "BLUEGRASS" },
{ make: "LIQUID FOOD GRADE", model: "BRUDER" },
{ make: "LIQUID FOOD GRADE", model: "BYFORD" },
{ make: "LIQUID FOOD GRADE", model: "HEIL" },
{ make: "LIQUID FOOD GRADE", model: "TES" },
{ make: "LIQUID FOOD GRADE", model: "OTHER" },

 // LIVE FLOOR TRAILERS

{ make: "LIVE FLOOR TRAILERS", model: "MAC TRAILER MFG" },
{ make: "LIVE FLOOR TRAILERS", model: "BTR" },
{ make: "LIVE FLOOR TRAILERS", model: "KAYLN SIEBERT" },
{ make: "LIVE FLOOR TRAILERS", model: "WILKENS" },
{ make: "LIVE FLOOR TRAILERS", model: "PEERLESS" },
{ make: "LIVE FLOOR TRAILERS", model: "ITI" },
{ make: "LIVE FLOOR TRAILERS", model: "AULICK IND" },
{ make: "LIVE FLOOR TRAILERS", model: "DORSEY" },
{ make: "LIVE FLOOR TRAILERS", model: "TITAN" },
{ make: "LIVE FLOOR TRAILERS", model: "MAS TRAILERS" },
{ make: "LIVE FLOOR TRAILERS", model: "ABS" },
{ make: "LIVE FLOOR TRAILERS", model: "ARTEX" },
{ make: "LIVE FLOOR TRAILERS", model: "AULICK IND" },
{ make: "LIVE FLOOR TRAILERS", model: "BARKER" },
{ make: "LIVE FLOOR TRAILERS", model: "BOOMER" },
{ make: "LIVE FLOOR TRAILERS", model: "DELOUPE" },
{ make: "LIVE FLOOR TRAILERS", model: "EAST" },
{ make: "LIVE FLOOR TRAILERS", model: "ETNYRE" },
{ make: "LIVE FLOOR TRAILERS", model: "FEHR" },
{ make: "LIVE FLOOR TRAILERS", model: "GINCOR" },
{ make: "LIVE FLOOR TRAILERS", model: "H & S" },
{ make: "LIVE FLOOR TRAILERS", model: "HITCH COCK" },
{ make: "LIVE FLOOR TRAILERS", model: "IMCO" },
{ make: "LIVE FLOOR TRAILERS", model: "MEYER" },
{ make: "LIVE FLOOR TRAILERS", model: "RTR" },
{ make: "LIVE FLOOR TRAILERS", model: "STECO" },
{ make: "LIVE FLOOR TRAILERS", model: "TRAIL KING" },
{ make: "LIVE FLOOR TRAILERS", model: "TRAVIS" },
{ make: "LIVE FLOOR TRAILERS", model: "TROUT RIVER" },
{ make: "LIVE FLOOR TRAILERS", model: "WILSON" },
{ make: "LIVE FLOOR TRAILERS", model: "OTHER" },

  // LIVESTOCK TRAILERS

{ make: "LIVESTOCK TRAILERS", model: "EBY" },
{ make: "LIVESTOCK TRAILERS", model: "FEATHERLITE" },
{ make: "LIVESTOCK TRAILERS", model: "WILSON" },
{ make: "LIVESTOCK TRAILERS", model: "CORN PRO" },
{ make: "LIVESTOCK TRAILERS", model: "DURALITE" },
{ make: "LIVESTOCK TRAILERS", model: "AMACSA" },
{ make: "LIVESTOCK TRAILERS", model: "CALICO" },
{ make: "LIVESTOCK TRAILERS", model: "VALLEY TRAILERS" },
{ make: "LIVESTOCK TRAILERS", model: "APEX" },
{ make: "LIVESTOCK TRAILERS", model: "SHADOW TRAILERS INC" },
{ make: "LIVESTOCK TRAILERS", model: "ARION" },
{ make: "LIVESTOCK TRAILERS", model: "BAR M TRAILERS" },
{ make: "LIVESTOCK TRAILERS", model: "BARRETT" },
{ make: "LIVESTOCK TRAILERS", model: "BIG BEND" },
{ make: "LIVESTOCK TRAILERS", model: "BISON" },
{ make: "LIVESTOCK TRAILERS", model: "BOSS" },
{ make: "LIVESTOCK TRAILERS", model: "CHAPARRAL" },
{ make: "LIVESTOCK TRAILERS", model: "CIMARRON" },
{ make: "LIVESTOCK TRAILERS", model: "CIRCLE D" },
{ make: "LIVESTOCK TRAILERS", model: "CMI" },
{ make: "LIVESTOCK TRAILERS", model: "CORN PRO" },
{ make: "LIVESTOCK TRAILERS", model: "CUSTOM CLASSIC" },
{ make: "LIVESTOCK TRAILERS", model: "DELCO" },
{ make: "LIVESTOCK TRAILERS", model: "DELTA" },
{ make: "LIVESTOCK TRAILERS", model: "DURALITE" },
{ make: "LIVESTOCK TRAILERS", model: "EAGLE X" },
{ make: "LIVESTOCK TRAILERS", model: "EAST T EXAS" },
{ make: "LIVESTOCK TRAILERS", model: "EXISS" },
{ make: "LIVESTOCK TRAILERS", model: "FRONTIER" },
{ make: "LIVESTOCK TRAILERS", model: "GOOSENECK" },
{ make: "LIVESTOCK TRAILERS", model: "GR TRAILERS" },
{ make: "LIVESTOCK TRAILERS", model: "HILLSBORO" },
{ make: "LIVESTOCK TRAILERS", model: "KIEFER" },
{ make: "LIVESTOCK TRAILERS", model: "KODIAK" },
{ make: "LIVESTOCK TRAILERS", model: "KPE" },
{ make: "LIVESTOCK TRAILERS", model: "LANDOLL" },
{ make: "LIVESTOCK TRAILERS", model: "MERHOW" },
{ make: "LIVESTOCK TRAILERS", model: "MERRITT" },
{ make: "LIVESTOCK TRAILERS", model: "MORITZ INTL" },
{ make: "LIVESTOCK TRAILERS", model: "NECKOVER" },
{ make: "LIVESTOCK TRAILERS", model: "RAWMAXX" },
{ make: "LIVESTOCK TRAILERS", model: "S&S DURALINE" },
{ make: "LIVESTOCK TRAILERS", model: "S&S" },
{ make: "LIVESTOCK TRAILERS", model: "SHADOW TRAILERS INC" },
{ make: "LIVESTOCK TRAILERS", model: "SHOP BUILT" },
{ make: "LIVESTOCK TRAILERS", model: "STOCKLINE" },
{ make: "LIVESTOCK TRAILERS", model: "STOLL" },
{ make: "LIVESTOCK TRAILERS", model: "SUNDOWNER" },
{ make: "LIVESTOCK TRAILERS", model: "SWIFT BUILT" },
{ make: "LIVESTOCK TRAILERS", model: "TITAN" },
{ make: "LIVESTOCK TRAILERS", model: "TRAILMANN" },
{ make: "LIVESTOCK TRAILERS", model: "TRAILS WEST" },
{ make: "LIVESTOCK TRAILERS", model: "TRAVALONG" },
{ make: "LIVESTOCK TRAILERS", model: "TRI STAR" },
{ make: "LIVESTOCK TRAILERS", model: "UNSPECIFIED" },
{ make: "LIVESTOCK TRAILERS", model: "VALLEY TRAILERS" },
{ make: "LIVESTOCK TRAILERS", model: "W&W" },
{ make: "LIVESTOCK TRAILERS", model: "WILSON" },
{ make: "LIVESTOCK TRAILERS", model: "OTHER" },

  // LOG TRAILERS

{ make: "LOG TRAILERS", model: "PITTS" },
{ make: "LOG TRAILERS", model: "MCLENDON" },
{ make: "LOG TRAILERS", model: "BWS" },
{ make: "LOG TRAILERS", model: "MANAC" },
{ make: "LOG TRAILERS", model: "BIG JOHN" },
{ make: "LOG TRAILERS", model: "WALLENSTEIN" },
{ make: "LOG TRAILERS", model: "KAUFMAN" },
{ make: "LOG TRAILERS", model: "DELOUPE" },
{ make: "LOG TRAILERS", model: "DOEPKER" },
{ make: "LOG TRAILERS", model: "CUSTOM BILT" },
{ make: "LOG TRAILERS", model: "ARNES" },
{ make: "LOG TRAILERS", model: "DORSEY" },
{ make: "LOG TRAILERS", model: "EAST" },
{ make: "LOG TRAILERS", model: "ELPHINSTONE" },
{ make: "LOG TRAILERS", model: "F&R" },
{ make: "LOG TRAILERS", model: "FONTAINE" },
{ make: "LOG TRAILERS", model: "FREFLYT" },
{ make: "LOG TRAILERS", model: "GREAT LAKES" },
{ make: "LOG TRAILERS", model: "HRD" },
{ make: "LOG TRAILERS", model: "KAUFMAN" },
{ make: "LOG TRAILERS", model: "KENNEDY" },
{ make: "LOG TRAILERS", model: "MAGNOLIA" },
{ make: "LOG TRAILERS", model: "MAXITRANS" },
{ make: "LOG TRAILERS", model: "PEERLESS" },
{ make: "LOG TRAILERS", model: "PELLITER" },
{ make: "LOG TRAILERS", model: "ROTOBEC" },
{ make: "LOG TRAILERS", model: "STONE STAR" },
{ make: "LOG TRAILERS", model: "SUPERIOR" },
{ make: "LOG TRAILERS", model: "TEMISKO" },
{ make: "LOG TRAILERS", model: "TIMMINS" },
{ make: "LOG TRAILERS", model: "TRAIL EX" },
{ make: "LOG TRAILERS", model: "TRANSPORT" },
{ make: "LOG TRAILERS", model: "VIKING" },
{ make: "LOG TRAILERS", model: "OTHER" },
  
 // LOWBOY TRAILERS

{ make: "LOWBOY TRAILERS", model: "FONTAINE" },
{ make: "LOWBOY TRAILERS", model: "XL SPECIALIZED" },
{ make: "LOWBOY TRAILERS", model: "PITTS" },
{ make: "LOWBOY TRAILERS", model: "KAYLN SIEBERT" },
{ make: "LOWBOY TRAILERS", model: "TRAIL KING" },
{ make: "LOWBOY TRAILERS", model: "TALBERT" },
{ make: "LOWBOY TRAILERS", model: "BRANDT" },
{ make: "LOWBOY TRAILERS", model: "KAUFMAN" },
{ make: "LOWBOY TRAILERS", model: "ALPHA HD" },
{ make: "LOWBOY TRAILERS", model: "EAGER BEAVER" },
{ make: "LOWBOY TRAILERS", model: "AAA" },
{ make: "LOWBOY TRAILERS", model: "ALPHA HD" },
{ make: "LOWBOY TRAILERS", model: "ASPEN" },
{ make: "LOWBOY TRAILERS", model: "ATOKA" },
{ make: "LOWBOY TRAILERS", model: "BRAZOS" },
{ make: "LOWBOY TRAILERS", model: "BWS" },
{ make: "LOWBOY TRAILERS", model: "CHOICE" },
{ make: "LOWBOY TRAILERS", model: "COZAD" },
{ make: "LOWBOY TRAILERS", model: "DELOUPE" },
{ make: "LOWBOY TRAILERS", model: "DOEPKER" },
{ make: "LOWBOY TRAILERS", model: "DORSEY" },
{ make: "LOWBOY TRAILERS", model: "DRAKE" },
{ make: "LOWBOY TRAILERS", model: "DYNAWELD" },
{ make: "LOWBOY TRAILERS", model: "ETNYRE" },
{ make: "LOWBOY TRAILERS", model: "FELLING" },
{ make: "LOWBOY TRAILERS", model: "FWR" },
{ make: "LOWBOY TRAILERS", model: "GLOBE" },
{ make: "LOWBOY TRAILERS", model: "GOLDHOFER" },
{ make: "LOWBOY TRAILERS", model: "HYSTER" },
{ make: "LOWBOY TRAILERS", model: "INTERSTATE" },
{ make: "LOWBOY TRAILERS", model: "JAMIESON" },
{ make: "LOWBOY TRAILERS", model: "JET" },
{ make: "LOWBOY TRAILERS", model: "KAUFMAN" },
{ make: "LOWBOY TRAILERS", model: "K-LINE" },
{ make: "LOWBOY TRAILERS", model: "LANDOLL" },
{ make: "LOWBOY TRAILERS", model: "LEDWELL" },
{ make: "LOWBOY TRAILERS", model: "LIDDELL" },
{ make: "LOWBOY TRAILERS", model: "LOAD KING" },
{ make: "LOWBOY TRAILERS", model: "LOADCRAFT" },
{ make: "LOWBOY TRAILERS", model: "MANAC" },
{ make: "LOWBOY TRAILERS", model: "MCLENDON" },
{ make: "LOWBOY TRAILERS", model: "MIDLAND" },
{ make: "LOWBOY TRAILERS", model: "MTE" },
{ make: "LOWBOY TRAILERS", model: "MURRAY" },
{ make: "LOWBOY TRAILERS", model: "MUV-ALL" },
{ make: "LOWBOY TRAILERS", model: "NEVILLE BUILT" },
{ make: "LOWBOY TRAILERS", model: "NUTTALL" },
{ make: "LOWBOY TRAILERS", model: "OVERBILT" },
{ make: "LOWBOY TRAILERS", model: "PACESETTER" },
{ make: "LOWBOY TRAILERS", model: "PEERLESS" },
{ make: "LOWBOY TRAILERS", model: "RAJA" },
{ make: "LOWBOY TRAILERS", model: "ROGERS" },
{ make: "LOWBOY TRAILERS", model: "SIEBERT" },
{ make: "LOWBOY TRAILERS", model: "STONESTAR" },
{ make: "LOWBOY TRAILERS", model: "TEMISKO" },
{ make: "LOWBOY TRAILERS", model: "TOWMASTER" },
{ make: "LOWBOY TRAILERS", model: "TRAILBOSS" },
{ make: "LOWBOY TRAILERS", model: "TRAIL-EZE" },
{ make: "LOWBOY TRAILERS", model: "TTSA" },
{ make: "LOWBOY TRAILERS", model: "VIKING" },
{ make: "LOWBOY TRAILERS", model: "WITZCO CHALLENGER" },
{ make: "LOWBOY TRAILERS", model: "OTHER" },

  // NON CODE TANK TRAILERS

{ make: "NON CODE TANK TRAILERS", model: "POLAR" },
{ make: "NON CODE TANK TRAILERS", model: "WALKER" },
{ make: "NON CODE TANK TRAILERS", model: "BRENNER" },
{ make: "NON CODE TANK TRAILERS", model: "HEIL" },
{ make: "NON CODE TANK TRAILERS", model: "MAC LTT" },
{ make: "NON CODE TANK TRAILERS", model: "STE" },
{ make: "NON CODE TANK TRAILERS", model: "FRUEHAUF" },
{ make: "NON CODE TANK TRAILERS", model: "BULK" },
{ make: "NON CODE TANK TRAILERS", model: "BEALL" },
{ make: "NON CODE TANK TRAILERS", model: "REMTEC" },
{ make: "NON CODE TANK TRAILERS", model: "ACRO" },
{ make: "NON CODE TANK TRAILERS", model: "ADVANCE" },
{ make: "NON CODE TANK TRAILERS", model: "BAR-BEL" },
{ make: "NON CODE TANK TRAILERS", model: "BEDARD" },
{ make: "NON CODE TANK TRAILERS", model: "BUTLER" },
{ make: "NON CODE TANK TRAILERS", model: "CEI PACER" },
{ make: "NON CODE TANK TRAILERS", model: "DOMATEX" },
{ make: "NON CODE TANK TRAILERS", model: "DRAGON PRODUCTS" },
{ make: "NON CODE TANK TRAILERS", model: "EASTERN TECH" },
{ make: "NON CODE TANK TRAILERS", model: "ETNYRE" },
{ make: "NON CODE TANK TRAILERS", model: "KARIKOOL" },
{ make: "NON CODE TANK TRAILERS", model: "KROHNERT" },
{ make: "NON CODE TANK TRAILERS", model: "LBT" },
{ make: "NON CODE TANK TRAILERS", model: "MUELLER" },
{ make: "NON CODE TANK TRAILERS", model: "NEVILLE BUILT" },
{ make: "NON CODE TANK TRAILERS", model: "NOVA" },
{ make: "NON CODE TANK TRAILERS", model: "OVERLAND" },
{ make: "NON CODE TANK TRAILERS", model: "STEPHENS" },
{ make: "NON CODE TANK TRAILERS", model: "TREMCAR" },
{ make: "NON CODE TANK TRAILERS", model: "WABASH" },
{ make: "NON CODE TANK TRAILERS", model: "WESTMARK" },
{ make: "NON CODE TANK TRAILERS", model: "OTHER" },

  // PNUEMATIC TRAILERS

{ make: "PNUEMATIC TRAILERS", model: "HEIL" },
{ make: "PNUEMATIC TRAILERS", model: "MAC TRAILER MFG" },
{ make: "PNUEMATIC TRAILERS", model: "POLAR" },
{ make: "PNUEMATIC TRAILERS", model: "FRUEHAUF" },
{ make: "PNUEMATIC TRAILERS", model: "J&L" },
{ make: "PNUEMATIC TRAILERS", model: "TREMCAR" },
{ make: "PNUEMATIC TRAILERS", model: "STEPHENS" },
{ make: "PNUEMATIC TRAILERS", model: "VANTAGE" },
{ make: "PNUEMATIC TRAILERS", model: "LBT" },
{ make: "PNUEMATIC TRAILERS", model: "TRAIL KING" },
{ make: "PNUEMATIC TRAILERS", model: "ADVANCE" },
{ make: "PNUEMATIC TRAILERS", model: "ALDURA" },
{ make: "PNUEMATIC TRAILERS", model: "APPCO" },
{ make: "PNUEMATIC TRAILERS", model: "BEALL" },
{ make: "PNUEMATIC TRAILERS", model: "BEDARD" },
{ make: "PNUEMATIC TRAILERS", model: "BUTLER" },
{ make: "PNUEMATIC TRAILERS", model: "CEI PACER" },
{ make: "PNUEMATIC TRAILERS", model: "EXA" },
{ make: "PNUEMATIC TRAILERS", model: "GALLEGOS" },
{ make: "PNUEMATIC TRAILERS", model: "JAMIESON" },
{ make: "PNUEMATIC TRAILERS", model: "KING" },
{ make: "PNUEMATIC TRAILERS", model: "LEDWELL" },
{ make: "PNUEMATIC TRAILERS", model: "PENSKE" },
{ make: "PNUEMATIC TRAILERS", model: "RAGLAN" },
{ make: "PNUEMATIC TRAILERS", model: "RETESA" },
{ make: "PNUEMATIC TRAILERS", model: "TROXELL" },
{ make: "PNUEMATIC TRAILERS", model: "WALINGA" },
{ make: "PNUEMATIC TRAILERS", model: "WARREN" },
{ make: "PNUEMATIC TRAILERS", model: "WILCO" },
{ make: "PNUEMATIC TRAILERS", model: "OTHER" },

  // POLE TRAILERS

{ make: "POLE TRAILERS", model: "LOAD KING" },
{ make: "POLE TRAILERS", model: "BUTLER" },
{ make: "POLE TRAILERS", model: "JJ TRAILER" },
{ make: "POLE TRAILERS", model: "BROOKS BROTHER" },
{ make: "POLE TRAILERS", model: "CHALLENGER" },
{ make: "POLE TRAILERS", model: "CZ ENG" },
{ make: "POLE TRAILERS", model: "LANE" },
{ make: "POLE TRAILERS", model: "TUF MFG" },
{ make: "POLE TRAILERS", model: "K-DEE" },
{ make: "POLE TRAILERS", model: "KIEFER" },
{ make: "POLE TRAILERS", model: "BIG TEX" },
{ make: "POLE TRAILERS", model: "BROOKS BROTHER" },
{ make: "POLE TRAILERS", model: "FEHR BROS" },
{ make: "POLE TRAILERS", model: "FELLING" },
{ make: "POLE TRAILERS", model: "GLENN ENG" },
{ make: "POLE TRAILERS", model: "HOGG & DAVIS" },
{ make: "POLE TRAILERS", model: "HOMEMADE" },
{ make: "POLE TRAILERS", model: "J&J" },
{ make: "POLE TRAILERS", model: "MORAN" },
{ make: "POLE TRAILERS", model: "OVERBILT" },
{ make: "POLE TRAILERS", model: "PITTS" },
{ make: "POLE TRAILERS", model: "REELSTRONG" },
{ make: "POLE TRAILERS", model: "ROBCOL" },
{ make: "POLE TRAILERS", model: "SHOP BUILT" },
{ make: "POLE TRAILERS", model: "SPECIALTY FLEET" },
{ make: "POLE TRAILERS", model: "TALBERT" },
{ make: "POLE TRAILERS", model: "WHITES WELDING" },
{ make: "POLE TRAILERS", model: "OTHER" },

  // PUP TRAILERS

{ make: "PUP TRAILERS", model: "MIDLAND" },
{ make: "PUP TRAILERS", model: "GORSKI" },
{ make: "PUP TRAILERS", model: "HYUNDAI" },
{ make: "PUP TRAILERS", model: "WABASH" },
{ make: "PUP TRAILERS", model: "MAXITRANS" },
{ make: "PUP TRAILERS", model: "FWR" },
{ make: "PUP TRAILERS", model: "WILDHORSE" },
{ make: "PUP TRAILERS", model: "FRUEHAUF" },
{ make: "PUP TRAILERS", model: "CLEMENT" },
{ make: "PUP TRAILERS", model: "HAMELEX WHITE" },
{ make: "PUP TRAILERS", model: "BEALL" },
{ make: "PUP TRAILERS", model: "CORNHUSKER" },
{ make: "PUP TRAILERS", model: "CUSTOM BILT" },
{ make: "PUP TRAILERS", model: "GREAT DANE" },
{ make: "PUP TRAILERS", model: "JASPER" },
{ make: "PUP TRAILERS", model: "MUSCAT" },
{ make: "PUP TRAILERS", model: "OSW" },
{ make: "PUP TRAILERS", model: "PEERLESS" },
{ make: "PUP TRAILERS", model: "RANCO" },
{ make: "PUP TRAILERS", model: "STRICK" },
{ make: "PUP TRAILERS", model: "TRAILMOBILE" },
{ make: "PUP TRAILERS", model: "OTHER" },

  // REEL - CABLE TRAILERS

{ make: "REEL - CABLE TRAILERS", model: "TSE" },
{ make: "REEL - CABLE TRAILERS", model: "SHERMAN REILLY" },
{ make: "REEL - CABLE TRAILERS", model: "LANE" },
{ make: "REEL - CABLE TRAILERS", model: "FELLING" },
{ make: "REEL - CABLE TRAILERS", model: "WAGNER - SMITH" },
{ make: "REEL - CABLE TRAILERS", model: "SAUBER" },
{ make: "REEL - CABLE TRAILERS", model: "ROOSE" },
{ make: "REEL - CABLE TRAILERS", model: "LOAD KING" },
{ make: "REEL - CABLE TRAILERS", model: "CONDUX" },
{ make: "REEL - CABLE TRAILERS", model: "JJ TRAILER" },
{ make: "REEL - CABLE TRAILERS", model: "BAZOOKA" },
{ make: "REEL - CABLE TRAILERS", model: "BROOKS BROTHERS" },
{ make: "REEL - CABLE TRAILERS", model: "CUSTOM BILT" },
{ make: "REEL - CABLE TRAILERS", model: "EAGLE" },
{ make: "REEL - CABLE TRAILERS", model: "FALCAN" },
{ make: "REEL - CABLE TRAILERS", model: "HALDILKA" },
{ make: "REEL - CABLE TRAILERS", model: "HOGG & DAVIS" },
{ make: "REEL - CABLE TRAILERS", model: "J&J" },
{ make: "REEL - CABLE TRAILERS", model: "JJ TRLR" },
{ make: "REEL - CABLE TRAILERS", model: "KIEFER" },
{ make: "REEL - CABLE TRAILERS", model: "LUCON" },
{ make: "REEL - CABLE TRAILERS", model: "MGS" },
{ make: "REEL - CABLE TRAILERS", model: "OASIS" },
{ make: "REEL - CABLE TRAILERS", model: "REELSTRONG" },
{ make: "REEL - CABLE TRAILERS", model: "SLABACH" },
{ make: "REEL - CABLE TRAILERS", model: "SPECIALTY FLEET" },
{ make: "REEL - CABLE TRAILERS", model: "STELLAR" },
{ make: "REEL - CABLE TRAILERS", model: "UNKNOWN" },
{ make: "REEL - CABLE TRAILERS", model: "UTILITY" },
{ make: "REEL - CABLE TRAILERS", model: "WHEELER REELER" },
{ make: "REEL - CABLE TRAILERS", model: "WHITES WELDING" },
{ make: "REEL - CABLE TRAILERS", model: "ZIERKE" },
{ make: "REEL - CABLE TRAILERS", model: "OTHER" },

 // REEFER TRAILERS

{ make: "REEFER TRAILERS", model: "UTILITY" },
{ make: "REEFER TRAILERS", model: "GREAT DANE" },
{ make: "REEFER TRAILERS", model: "WABASH" },
{ make: "REEFER TRAILERS", model: "VANGUARD" },
{ make: "REEFER TRAILERS", model: "HYUNDAI" },
{ make: "REEFER TRAILERS", model: "CIMC" },
{ make: "REEFER TRAILERS", model: "KIDRON" },
{ make: "REEFER TRAILERS", model: "MAXITRANS" },
{ make: "REEFER TRAILERS", model: "FTE" },
{ make: "REEFER TRAILERS", model: "HACKNEY" },
{ make: "REEFER TRAILERS", model: "FAIRFAX" },
{ make: "REEFER TRAILERS", model: "MANAC" },
{ make: "REEFER TRAILERS", model: "MAXICUBE" },
{ make: "REEFER TRAILERS", model: "SCHMITZ" },
{ make: "REEFER TRAILERS", model: "STOUGHTON" },
{ make: "REEFER TRAILERS", model: "TRAILMOBILE" },
{ make: "REEFER TRAILERS", model: "VAWDREY" },
{ make: "REEFER TRAILERS", model: "OTHER" },

  // ROLL OFF TRAILERS

{ make: "ROLL OFF TRAILERS", model: "BENLEE" },
{ make: "ROLL OFF TRAILERS", model: "DRAGON PRODUCTS" },
{ make: "ROLL OFF TRAILERS", model: "GALBREATH" },
{ make: "ROLL OFF TRAILERS", model: "ACE" },
{ make: "ROLL OFF TRAILERS", model: "CLEMENT" },
{ make: "ROLL OFF TRAILERS", model: "G&H MNFG" },
{ make: "ROLL OFF TRAILERS", model: "ARNES" },
{ make: "ROLL OFF TRAILERS", model: "CHAGNON" },
{ make: "ROLL OFF TRAILERS", model: "PRECSION EQUI" },
{ make: "ROLL OFF TRAILERS", model: "WASTEQUIP" },
{ make: "ROLL OFF TRAILERS", model: "ACE" },
{ make: "ROLL OFF TRAILERS", model: "ARNES" },
{ make: "ROLL OFF TRAILERS", model: "BOBKO" },
{ make: "ROLL OFF TRAILERS", model: "DENTONI" },
{ make: "ROLL OFF TRAILERS", model: "DUNRIGHT" },
{ make: "ROLL OFF TRAILERS", model: "GREAT DANE" },
{ make: "ROLL OFF TRAILERS", model: "J M CHANTAL" },
{ make: "ROLL OFF TRAILERS", model: "LANDOLL" },
{ make: "ROLL OFF TRAILERS", model: "MOORE" },
{ make: "ROLL OFF TRAILERS", model: "OSHKOSH" },
{ make: "ROLL OFF TRAILERS", model: "SHOP BILT" },
{ make: "ROLL OFF TRAILERS", model: "STECO" },
{ make: "ROLL OFF TRAILERS", model: "UNSPECIFIED" },
{ make: "ROLL OFF TRAILERS", model: "WABASH" },
{ make: "ROLL OFF TRAILERS", model: "WASTEQUIP" },
{ make: "ROLL OFF TRAILERS", model: "WILSON" },
{ make: "ROLL OFF TRAILERS", model: "OTHER" },

  // SANITARY TRAILERS

{ make: "SANITARY TRAILERS", model: "WALKER" },
{ make: "SANITARY TRAILERS", model: "TREMCAR" },
{ make: "SANITARY TRAILERS", model: "POLAR" },
{ make: "SANITARY TRAILERS", model: "BRENNER" },
{ make: "SANITARY TRAILERS", model: "WABASH" },
{ make: "SANITARY TRAILERS", model: "BEALL" },
{ make: "SANITARY TRAILERS", model: "BAR-BEL" },
{ make: "SANITARY TRAILERS", model: "STE" },
{ make: "SANITARY TRAILERS", model: "ENGLE FAB" },
{ make: "SANITARY TRAILERS", model: "FRUEHAUF" },
{ make: "SANITARY TRAILERS", model: "BLUEGRASS" },
{ make: "SANITARY TRAILERS", model: "MAC LTT" },
{ make: "SANITARY TRAILERS", model: "MUELLER" },
{ make: "SANITARY TRAILERS", model: "NOVA" },
{ make: "SANITARY TRAILERS", model: "SUPERIOR" },
{ make: "SANITARY TRAILERS", model: "OTHER" },

  // SIDE DUMP TRAILERS

{ make: "SIDE DUMP TRAILERS", model: "SMITHCO" },
{ make: "SIDE DUMP TRAILERS", model: "SIDE DUMP IND" },
{ make: "SIDE DUMP TRAILERS", model: "JET" },
{ make: "SIDE DUMP TRAILERS", model: "SIDUMPR" },
{ make: "SIDE DUMP TRAILERS", model: "DEMCO" },
{ make: "SIDE DUMP TRAILERS", model: "ARNES" },
{ make: "SIDE DUMP TRAILERS", model: "CROSS COUNTRY" },
{ make: "SIDE DUMP TRAILERS", model: "LOAD KING" },
{ make: "SIDE DUMP TRAILERS", model: "MIDLAND" },
{ make: "SIDE DUMP TRAILERS", model: "TRAIL KING" },
{ make: "SIDE DUMP TRAILERS", model: "AAA" },
{ make: "SIDE DUMP TRAILERS", model: "AZMEB" },
{ make: "SIDE DUMP TRAILERS", model: "BRUCE ROCK" },
{ make: "SIDE DUMP TRAILERS", model: "CANUCK" },
{ make: "SIDE DUMP TRAILERS", model: "DOEPKER" },
{ make: "SIDE DUMP TRAILERS", model: "FIVE STAR" },
{ make: "SIDE DUMP TRAILERS", model: "FREIGHT WEST TRLR" },
{ make: "SIDE DUMP TRAILERS", model: "FREIGHTMORE TRANS" },
{ make: "SIDE DUMP TRAILERS", model: "HOWARD PORTER" },
{ make: "SIDE DUMP TRAILERS", model: "JAMIESON" },
{ make: "SIDE DUMP TRAILERS", model: "LOADLINE" },
{ make: "SIDE DUMP TRAILERS", model: "LUSTY" },
{ make: "SIDE DUMP TRAILERS", model: "MANAC" },
{ make: "SIDE DUMP TRAILERS", model: "MARS" },
{ make: "SIDE DUMP TRAILERS", model: "MOORE" },
{ make: "SIDE DUMP TRAILERS", model: "RANCO" },
{ make: "SIDE DUMP TRAILERS", model: "R-WAY" },
{ make: "SIDE DUMP TRAILERS", model: "TRAIL KING" },
{ make: "SIDE DUMP TRAILERS", model: "TRISTAR" },
{ make: "SIDE DUMP TRAILERS", model: "XL SPECIALIZED" },
{ make: "SIDE DUMP TRAILERS", model: "OTHER" },

 // TAG TRAILERS

{ make: "TAG TRAILERS", model: "MIDLAND" },
{ make: "TAG TRAILERS", model: "TALBERT" },
{ make: "TAG TRAILERS", model: "TRAILBOSS" },
{ make: "TAG TRAILERS", model: "FWR" },
{ make: "TAG TRAILERS", model: "PITTS" },
{ make: "TAG TRAILERS", model: "TRAIL KING" },
{ make: "TAG TRAILERS", model: "EAGER BEAVER" },
{ make: "TAG TRAILERS", model: "FELLING" },
{ make: "TAG TRAILERS", model: "AAA" },
{ make: "TAG TRAILERS", model: "INTERSTATE" },
{ make: "TAG TRAILERS", model: "BEHNKE" },
{ make: "TAG TRAILERS", model: "BRANDT" },
{ make: "TAG TRAILERS", model: "BWS" },
{ make: "TAG TRAILERS", model: "CROSS COUNTRY" },
{ make: "TAG TRAILERS", model: "DORSEY" },
{ make: "TAG TRAILERS", model: "EAST TEXAS" },
{ make: "TAG TRAILERS", model: "GLOBE" },
{ make: "TAG TRAILERS", model: "HUDSON" },
{ make: "TAG TRAILERS", model: "KAUFMAN" },
{ make: "TAG TRAILERS", model: "LOAD TRAIL" },
{ make: "TAG TRAILERS", model: "LUCON" },
{ make: "TAG TRAILERS", model: "MANAC" },
{ make: "TAG TRAILERS", model: "NORSTAR" },
{ make: "TAG TRAILERS", model: "NORTHEAST" },
{ make: "TAG TRAILERS", model: "OLYMPIC" },
{ make: "TAG TRAILERS", model: "OVERBILT" },
{ make: "TAG TRAILERS", model: "ROGERS" },
{ make: "TAG TRAILERS", model: "STONESTAR" },
{ make: "TAG TRAILERS", model: "TOWMASTER" },
{ make: "TAG TRAILERS", model: "TRAILMAX" },
{ make: "TAG TRAILERS", model: "UTILITY" },
{ make: "TAG TRAILERS", model: "WITZCO" },
{ make: "TAG TRAILERS", model: "XL SPECIALIZED" },
{ make: "TAG TRAILERS", model: "ZIEMAN" },
{ make: "TAG TRAILERS", model: "OTHER" },

 // TANK TRAILERS

{ make: "TANK TRAILERS", model: "POLAR" },
{ make: "TANK TRAILERS", model: "HEIL" },
{ make: "TANK TRAILERS", model: "BRENNER" },
{ make: "TANK TRAILERS", model: "MAC TRAILER MFG" },
{ make: "TANK TRAILERS", model: "WALKER" },
{ make: "TANK TRAILERS", model: "FRUEHAUF" },
{ make: "TANK TRAILERS", model: "MAC LTT" },
{ make: "TANK TRAILERS", model: "TREMCAR" },
{ make: "TANK TRAILERS", model: "STE" },
{ make: "TANK TRAILERS", model: "BEALL" },
{ make: "TANK TRAILERS", model: "AAA" },
{ make: "TANK TRAILERS", model: "ACE" },
{ make: "TANK TRAILERS", model: "ACRO" },
{ make: "TANK TRAILERS", model: "ADVANCE" },
{ make: "TANK TRAILERS", model: "ALDURA" },
{ make: "TANK TRAILERS", model: "BAR-BEL" },
{ make: "TANK TRAILERS", model: "BEDARD" },
{ make: "TANK TRAILERS", model: "BULK" },
{ make: "TANK TRAILERS", model: "BUTLER" },
{ make: "TANK TRAILERS", model: "COLOMBIA" },
{ make: "TANK TRAILERS", model: "COMPTANK" },
{ make: "TANK TRAILERS", model: "CONQUEST" },
{ make: "TANK TRAILERS", model: "CUSTOM" },
{ make: "TANK TRAILERS", model: "DEMCO" },
{ make: "TANK TRAILERS", model: "DRAGON" },
{ make: "TANK TRAILERS", model: "ETNYRE" },
{ make: "TANK TRAILERS", model: "EXA" },
{ make: "TANK TRAILERS", model: "GALLEGOS" },
{ make: "TANK TRAILERS", model: "GALYEAN" },
{ make: "TANK TRAILERS", model: "HARMON" },
{ make: "TANK TRAILERS", model: "HUTCHINSON" },
{ make: "TANK TRAILERS", model: "J & L" },
{ make: "TANK TRAILERS", model: "JAMEISON" },
{ make: "TANK TRAILERS", model: "KARIKOOL" },
{ make: "TANK TRAILERS", model: "LEDWELL" },
{ make: "TANK TRAILERS", model: "LUBBOCK" },
{ make: "TANK TRAILERS", model: "MARSHALL LETHLEAN" },
{ make: "TANK TRAILERS", model: "MISSISSIPPI" },
{ make: "TANK TRAILERS", model: "NEVILLE" },
{ make: "TANK TRAILERS", model: "REMTEC" },
{ make: "TANK TRAILERS", model: "RETESA" },
{ make: "TANK TRAILERS", model: "STEPHENS" },
{ make: "TANK TRAILERS", model: "STONESTAR" },
{ make: "TANK TRAILERS", model: "TRAIL KING" },
{ make: "TANK TRAILERS", model: "TRAILMASTER" },
{ make: "TANK TRAILERS", model: "TRAILMOBILE" },
{ make: "TANK TRAILERS", model: "TRAMCO" },
{ make: "TANK TRAILERS", model: "TROXELL" },
{ make: "TANK TRAILERS", model: "VANTAGE" },
{ make: "TANK TRAILERS", model: "WABASH" },
{ make: "TANK TRAILERS", model: "WELDIT" },
{ make: "TANK TRAILERS", model: "WESTMOR" },
{ make: "TANK TRAILERS", model: "WILCO" },
{ make: "TANK TRAILERS", model: "OTHER" },

 // UTILITY TRAILERS

{ make: "UTILITY TRAILERS", model: "ALUMA" },
{ make: "UTILITY TRAILERS", model: "MCCLAIN" },
{ make: "UTILITY TRAILERS", model: "SURE-TRAC" },
{ make: "UTILITY TRAILERS", model: "COASTLINE" },
{ make: "UTILITY TRAILERS", model: "DIAMOND T" },
{ make: "UTILITY TRAILERS", model: "H&H" },
{ make: "UTILITY TRAILERS", model: "TRITON" },
{ make: "UTILITY TRAILERS", model: "TAYLOR-WAY" },
{ make: "UTILITY TRAILERS", model: "DOOLITTLE" },
{ make: "UTILITY TRAILERS", model: "MIDSOTA" },
{ make: "UTILITY TRAILERS", model: "BIG TEX" },
{ make: "UTILITY TRAILERS", model: "CAN-AM" },
{ make: "UTILITY TRAILERS", model: "CHILTON" },
{ make: "UTILITY TRAILERS", model: "TIMPTE" },
{ make: "UTILITY TRAILERS", model: "YACHT CLUB" },
{ make: "UTILITY TRAILERS", model: "OTHER" },

 // VACUUM EXCAVATORS TRAILERS

{ make: "VACUUM EXCAVATORS TRAILERS", model: "VERMEER" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "DITCH WITCH" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "VAC TRON" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "RING-O-MATIC" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "VAC CON" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "VAC-EX" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "VACMASTERS" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "VACSTAR" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "VAC-U-VATOR HYDROVAC" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "E.H. WACHS" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "LONESTAR" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "PACIFIC TEK" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "SHARP EQUIPMENT" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "WASTECORP PUMPS" },
{ make: "VACUUM EXCAVATORS TRAILERS", model: "OTHER" },

  // VACUUM TANK TRAILERS

{ make: "VACUUM TANK TRAILERS", model: "DRAGON PRODUCTS" },
{ make: "VACUUM TANK TRAILERS", model: "TROXELL" },
{ make: "VACUUM TANK TRAILERS", model: "GALYEAN" },
{ make: "VACUUM TANK TRAILERS", model: "EXA" },
{ make: "VACUUM TANK TRAILERS", model: "ALDURA" },
{ make: "VACUUM TANK TRAILERS", model: "GALLEGOS" },
{ make: "VACUUM TANK TRAILERS", model: "LONESTAR TRAILER" },
{ make: "VACUUM TANK TRAILERS", model: "POLAR" },
{ make: "VACUUM TANK TRAILERS", model: "RETESA" },
{ make: "VACUUM TANK TRAILERS", model: "SOUTHERN VAC" },
{ make: "VACUUM TANK TRAILERS", model: "ACE" },
{ make: "VACUUM TANK TRAILERS", model: "BRENNER" },
{ make: "VACUUM TANK TRAILERS", model: "DOMATEX" },
{ make: "VACUUM TANK TRAILERS", model: "FRUEHAUF" },
{ make: "VACUUM TANK TRAILERS", model: "HEIL" },
{ make: "VACUUM TANK TRAILERS", model: "KEITH HUBER" },
{ make: "VACUUM TANK TRAILERS", model: "KRUZ" },
{ make: "VACUUM TANK TRAILERS", model: "LOEWEN" },
{ make: "VACUUM TANK TRAILERS", model: "MAC LTT" },
{ make: "VACUUM TANK TRAILERS", model: "MAS TRAILERS" },
{ make: "VACUUM TANK TRAILERS", model: "MENARD" },
{ make: "VACUUM TANK TRAILERS", model: "MOUNTAIN WEST" },
{ make: "VACUUM TANK TRAILERS", model: "OVERLAND" },
{ make: "VACUUM TANK TRAILERS", model: "PCI" },
{ make: "VACUUM TANK TRAILERS", model: "PIONEER" },
{ make: "VACUUM TANK TRAILERS", model: "PRESVAC" },
{ make: "VACUUM TANK TRAILERS", model: "PUMA" },
{ make: "VACUUM TANK TRAILERS", model: "SOUTHERN WELDING" },
{ make: "VACUUM TANK TRAILERS", model: "STAR MFG" },
{ make: "VACUUM TANK TRAILERS", model: "STE" },
{ make: "VACUUM TANK TRAILERS", model: "STEPHENS" },
{ make: "VACUUM TANK TRAILERS", model: "STONESTAR" },
{ make: "VACUUM TANK TRAILERS", model: "TIGER" },
{ make: "VACUUM TANK TRAILERS", model: "TRAILMASTER" },
{ make: "VACUUM TANK TRAILERS", model: "VE ENTERPRISES" },
{ make: "VACUUM TANK TRAILERS", model: "VERMEER" },
{ make: "VACUUM TANK TRAILERS", model: "WABASH" },
{ make: "VACUUM TANK TRAILERS", model: "OTHER" },

  // VAN TRAILERS

{ make: "VAN TRAILERS", model: "ALLOY" },
{ make: "VAN TRAILERS", model: "AZTEC" },
{ make: "VAN TRAILERS", model: "BUDD" },
{ make: "VAN TRAILERS", model: "CAN CAR" },
{ make: "VAN TRAILERS", model: "COMET" },
{ make: "VAN TRAILERS", model: "DI-MOND" },
{ make: "VAN TRAILERS", model: "DORSEY" },
{ make: "VAN TRAILERS", model: "FONTAINE" },
{ make: "VAN TRAILERS", model: "FREIGHTLINER" },
{ make: "VAN TRAILERS", model: "FRUEHAUF" },
{ make: "VAN TRAILERS", model: "GINDY" },
{ make: "VAN TRAILERS", model: "GREAT DANE" },
{ make: "VAN TRAILERS", model: "HAULMARK" },
{ make: "VAN TRAILERS", model: "HOLLAND" },
{ make: "VAN TRAILERS", model: "HYUNDAI" },
{ make: "VAN TRAILERS", model: "KENT" },
{ make: "VAN TRAILERS", model: "KENTUCKY" },
{ make: "VAN TRAILERS", model: "LUFKIN" },
{ make: "VAN TRAILERS", model: "MANAC" },
{ make: "VAN TRAILERS", model: "MI-T-M" },
{ make: "VAN TRAILERS", model: "MOND" },
{ make: "VAN TRAILERS", model: "MONON" },
{ make: "VAN TRAILERS", model: "PINE" },
{ make: "VAN TRAILERS", model: "STOUGHTON" },
{ make: "VAN TRAILERS", model: "STRICK" },
{ make: "VAN TRAILERS", model: "TRAILMOBILE" },
{ make: "VAN TRAILERS", model: "UTILITY" },
{ make: "VAN TRAILERS", model: "VANGUARD" },
{ make: "VAN TRAILERS", model: "WABASH" },
{ make: "VAN TRAILERS", model: "WANCO" },
{ make: "VAN TRAILERS", model: "WELLS CARGO" },
{ make: "VAN TRAILERS", model: "CON-WAY MFG" },
{ make: "VAN TRAILERS", model: "ATRO" },
{ make: "VAN TRAILERS", model: "OTHER" },

  // WASTE SLUDGE TANK TRAILERS

{ make: "WASTE SLUDGE TANK TRAILERS", model: "POLAR" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "BRENNER" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "GEA" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "HEIL" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "FRUEHAUF" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "STE" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "BOSS" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "CUSTOM TRLR" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "DRAGON PRODUCTS" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "LEDWELL" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "BUTLER" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "NORTHERN" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "SUNSHINE" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "TEC" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "TRAILMASTER" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "TREMCAR" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "WALKER" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "WESTMARK" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "WORLEY WELDING WORKS" },
{ make: "WASTE SLUDGE TANK TRAILERS", model: "OTHER" },

  // WATER TANK TRAILERS

{ make: "WATER TANK TRAILERS", model: "DEMCO" },
{ make: "WATER TANK TRAILERS", model: "AAA" },
{ make: "WATER TANK TRAILERS", model: "POLAR" },
{ make: "WATER TANK TRAILERS", model: "NEVILLE BUILT" },
{ make: "WATER TANK TRAILERS", model: "MARSHALL LETHLEAN" },
{ make: "WATER TANK TRAILERS", model: "STONESTAR" },
{ make: "WATER TANK TRAILERS", model: "BRENNER" },
{ make: "WATER TANK TRAILERS", model: "WALKER" },
{ make: "WATER TANK TRAILERS", model: "FRUEHAUF" },
{ make: "WATER TANK TRAILERS", model: "ADVANCE" },
{ make: "WATER TANK TRAILERS", model: "BEALL" },
{ make: "WATER TANK TRAILERS", model: "CUSTOM BILT" },
{ make: "WATER TANK TRAILERS", model: "DUO LIFT" },
{ make: "WATER TANK TRAILERS", model: "FREIGHTMORE TRANSPORT" },
{ make: "WATER TANK TRAILERS", model: "GALYEAN" },
{ make: "WATER TANK TRAILERS", model: "GTE" },
{ make: "WATER TANK TRAILERS", model: "HEIL" },
{ make: "WATER TANK TRAILERS", model: "HOCKNEY" },
{ make: "WATER TANK TRAILERS", model: "JAMIESON" },
{ make: "WATER TANK TRAILERS", model: "KOCKUMS" },
{ make: "WATER TANK TRAILERS", model: "STE" },
{ make: "WATER TANK TRAILERS", model: "TIEMAN" },
{ make: "WATER TANK TRAILERS", model: "UTA TRAILERS" },
{ make: "WATER TANK TRAILERS", model: "WESTANK" },
{ make: "WATER TANK TRAILERS", model: "WESTMARK" },
{ make: "WATER TANK TRAILERS", model: "OTHER" },

  // WATER TRAILERS - BUMPER PULL

{ make: "WATER TRAILERS - BUMPER PULL", model: "MULTIQUIP" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "WYLIE" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "UNSPECIFIED" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "FRUEHAUF" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "CUSTOM BILT" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "MI-T-M" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "ALTEC" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "BEALL" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "BEVERDAM" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "COURANT" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "ALTEC" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "BEALL" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "CUSTOM BILT" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "GENERAC" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "HARBEN" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "HEC" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "HEIL" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "HOT JET" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "IPSAM" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "KUBE" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "MI-T-M" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "NIECE" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "POLAR" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "SHOP MADE" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "VIM" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "WATER TRAILERS NET" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "WOMA" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "YSM" },
{ make: "WATER TRAILERS - BUMPER PULL", model: "OTHER" },

  
  // OTHER TRAILERS
  { make: "OTHER TRAILERS", model: "OTHER" },
];

export default trailersTaxonomy;
