const trencherDnaKeywords = [
  /* -------------------- */
  /* MACHINE TYPE DNA */
  /* -------------------- */

  "CHAIN TRENCHER",
  "WHEEL TRENCHER",
  "ROCKWHEEL",
  "ROCKWHEEL TRENCHER",
  "MICRO TRENCHER",
  "VIBRATORY PLOW",
  "CABLE PLOW",
  "STATIC PLOW",
  "RIDE ON TRENCHER",
  "WALK BEHIND TRENCHER",
  "TRACK TRENCHER",
  "WHEELED TRENCHER",
  "HEAVY ROCK TRENCHER",
  "UTILITY TRENCHER",
  "PIPELINE TRENCHER",
  "SIDE CUT TRENCHER",
  "CENTER MOUNT TRENCHER",
  "TRACTOR MOUNTED TRENCHER",
  "SKID STEER TRENCHER",
  "ATTACHMENT TRENCHER",

  /* -------------------- */
  /* CHASSIS DNA */
  /* -------------------- */

  "RIDE ON CHASSIS",
  "WALK BEHIND CHASSIS",
  "TRACKED CHASSIS",
  "WHEELED CHASSIS",
  "RUBBER TRACK CHASSIS",
  "STEEL TRACK CHASSIS",
  "ARTICULATED CHASSIS",
  "RIGID FRAME",
  "LOW PROFILE CHASSIS",
  "COMPACT CHASSIS",
  "HEAVY DUTY FRAME",
  "ROCK TRENCHER FRAME",
  "TRACTOR MOUNT FRAME",
  "PLOW CARRIER",
  "TRENCHER CARRIER",
  "REAR MOUNT TRENCHER",
  "FRONT MOUNT TRENCHER",
  "MID MOUNT TRENCHER",

  /* -------------------- */
  /* TRENCHER BOOM DNA */
  /* -------------------- */

  "TRENCHER BOOM",
  "DIGGING BOOM",
  "HYDRAULIC BOOM",
  "MANUAL BOOM",
  "CENTER MOUNT BOOM",
  "SIDE SHIFT BOOM",
  "SIDE MOUNT BOOM",
  "REAR MOUNT BOOM",
  "OFFSET BOOM",
  "FIXED BOOM",
  "ADJUSTABLE BOOM",
  "DEEP DIG BOOM",
  "STANDARD BOOM",
  "HEAVY DUTY BOOM",
  "ROCK BOOM",
  "BOOM EXTENSION",
  "BOOM CRUMBER",
  "BOOM LIFT CYLINDER",
  "BOOM DEPTH CONTROL",
  "BOOM FLOAT",
  "BOOM GUARDS",

  /* -------------------- */
  /* CHAIN SYSTEM DNA */
  /* -------------------- */

  "DIGGING CHAIN",
  "TRENCHER CHAIN",
  "EARTH CHAIN",
  "ROCK CHAIN",
  "COMBO CHAIN",
  "COMBINATION CHAIN",
  "CUP CHAIN",
  "SHARK CHAIN",
  "BULLET CHAIN",
  "TOOTH CHAIN",
  "DOUBLE STANDARD CHAIN",
  "DOUBLE HEAVY CHAIN",
  "ANTI BACKFLEX CHAIN",
  "HEAVY DUTY CHAIN",
  "CHAIN DRIVE",
  "HYDRAULIC CHAIN DRIVE",
  "CHAIN SPROCKET",
  "CHAIN IDLER",
  "CHAIN TENSIONER",
  "HYDRAULIC CHAIN TENSIONER",
  "GREASE CHAIN TENSIONER",
  "DIGGING CHAIN GUIDE",
  "CHAIN CLEANER",
  "CHAIN GUARD",

  /* -------------------- */
  /* TOOTH / CUP DNA */
  /* -------------------- */

  "CUP TEETH",
  "SHARK TEETH",
  "ROCK TEETH",
  "BULLET TEETH",
  "CARBIDE TEETH",
  "DIGGING TEETH",
  "FROST TEETH",
  "COMBO TEETH",
  "EARTH TEETH",
  "CUP CUTTERS",
  "SIDE CUTTERS",
  "CENTER CUTTERS",
  "TOOTH HOLDERS",
  "TOOTH POCKETS",
  "BOLT ON TEETH",
  "WELD ON TEETH",
  "REPLACEABLE TEETH",
  "ROCK PICKS",
  "CARBIDE PICKS",
  "CUTTER BITS",
  "BIT HOLDERS",

  /* -------------------- */
  /* ROCKWHEEL DNA */
  /* -------------------- */

  "ROCKWHEEL",
  "WHEEL TRENCHER",
  "CUTTING WHEEL",
  "ROCK SAW",
  "MICRO TRENCH WHEEL",
  "DUAL WHEEL CUTTER",
  "SEGMENTED WHEEL",
  "CARBIDE WHEEL",
  "ROCKWHEEL TEETH",
  "CARBIDE PICKS",
  "WHEEL DRIVE",
  "HYDRAULIC WHEEL DRIVE",
  "DIRECT WHEEL DRIVE",
  "WHEEL DEPTH CONTROL",
  "WHEEL SIDE SHIFT",
  "WHEEL CLEANOUT",
  "WHEEL GUARD",
  "CUTTING DRUM",
  "CUTTER WHEEL",
  "WHEEL WIDTH KIT",

  /* -------------------- */
  /* MICROTRENCH DNA */
  /* -------------------- */

  "MICRO TRENCHER",
  "MICRO TRENCH WHEEL",
  "NARROW CUT WHEEL",
  "FIBER WHEEL",
  "CUT AND VAC SYSTEM",
  "VACUUM SPOIL SYSTEM",
  "WATER COOLING SYSTEM",
  "DUST SUPPRESSION",
  "SLURRY CONTROL",
  "DEPTH GUIDE",
  "CURB FOLLOWER",
  "SAW BLADE CUTTER",
  "DIAMOND BLADE",
  "CARBIDE BLADE",
  "MICROTRENCH SPOIL CONVEYOR",

  /* -------------------- */
  /* PLOW SYSTEM DNA */
  /* -------------------- */

  "VIBRATORY PLOW",
  "CABLE PLOW",
  "STATIC PLOW",
  "PLOW BLADE",
  "VIBRATORY BLADE",
  "PLOW BOOT",
  "CABLE BOOT",
  "PIPE BOOT",
  "CONDUIT BOOT",
  "FEED CHUTE",
  "PLOW SHANK",
  "PLOW KNIFE",
  "HYDRAULIC PLOW",
  "REAR PLOW",
  "SIDE PLOW",
  "CENTER MOUNT PLOW",
  "PLOW LIFT",
  "PLOW SWING",
  "PLOW STEER",
  "PLOW DEPTH CONTROL",
  "PLOW VIBRATION",
  "VIBRATORY DRIVE",
  "PLOW REEL CARRIER",

  /* -------------------- */
  /* DRIVE SYSTEM DNA */
  /* -------------------- */

  "HYDROSTATIC",
  "HYDROSTATIC DRIVE",
  "MECHANICAL DRIVE",
  "HYDRAULIC DRIVE",
  "TRACK DRIVE",
  "WHEEL DRIVE",
  "ALL WHEEL DRIVE",
  "4WD",
  "2WD",
  "CREEP DRIVE",
  "CREEPER DRIVE",
  "TWO SPEED TRAVEL",
  "VARIABLE SPEED DRIVE",
  "PLANETARY FINAL DRIVE",
  "DIRECT DRIVE",
  "CHAIN DRIVE",
  "BELT DRIVE",
  "GROUND DRIVE",
  "DIGGING DRIVE",
  "PLOW DRIVE",
  "COUNTER ROTATION",

  /* -------------------- */
  /* TRACK / TIRE DNA */
  /* -------------------- */

  "RUBBER TRACK",
  "STEEL TRACK",
  "TRACK MACHINE",
  "WHEELED MACHINE",
  "LGP",
  "LOW GROUND PRESSURE",
  "WIDE TRACK",
  "NARROW TRACK",
  "OSCILLATING TRACK FRAME",
  "RIGID TRACK FRAME",
  "SUSPENDED TRACK FRAME",
  "CRAWLER TRACK",
  "TRACK PADS",
  "TRACK CHAIN",
  "TRACK TENSIONER",
  "PNEUMATIC TIRES",
  "SOLID TIRES",
  "FOAM FILLED TIRES",
  "FLOTATION TIRES",
  "BAR LUG TIRES",
  "TURF TIRES",
  "DUAL TIRES",
  "TIRE CHAINS",

  /* -------------------- */
  /* STEERING DNA */
  /* -------------------- */

  "ARTICULATED STEERING",
  "CRAB STEER",
  "FRONT STEER",
  "REAR STEER",
  "ALL WHEEL STEER",
  "TRACK STEERING",
  "SKID STEER",
  "HYDROSTATIC STEERING",
  "HYDRAULIC STEERING",
  "PIVOT STEERING",
  "STEERING AXLE",
  "OSCILLATING AXLE",
  "PLOW STEERING",
  "REAR STEER MODE",
  "COORDINATED STEER",

  /* -------------------- */
  /* HYDRAULIC SYSTEM DNA */
  /* -------------------- */

  "OPEN CENTER HYDRAULICS",
  "CLOSED CENTER HYDRAULICS",
  "LOAD SENSING HYDRAULICS",
  "PRESSURE COMPENSATED HYDRAULICS",
  "AUX HYDRAULICS",
  "AUXILIARY HYDRAULICS",
  "HIGH FLOW",
  "HIGH FLOW HYDRAULICS",
  "STANDARD FLOW HYDRAULICS",
  "TRENCHER HYDRAULICS",
  "PLOW HYDRAULICS",
  "BOOM HYDRAULICS",
  "CONVEYOR HYDRAULICS",
  "AUGER HYDRAULICS",
  "REEL HYDRAULICS",
  "HYDRAULIC QUICK COUPLERS",
  "HYDRAULIC COOLER",
  "HYDRAULIC OIL COOLER",
  "HYDRAULIC MOTOR",
  "VARIABLE DISPLACEMENT PUMP",
  "ELECTROHYDRAULIC CONTROLS",

  /* -------------------- */
  /* CONVEYOR / SPOIL DNA */
  /* -------------------- */

  "SPOIL CONVEYOR",
  "SPOIL AUGER",
  "CLEANOUT AUGER",
  "SIDE AUGER",
  "DISCHARGE AUGER",
  "CROSS AUGER",
  "CONVEYOR BELT",
  "HYDRAULIC CONVEYOR",
  "FOLDING CONVEYOR",
  "SWING CONVEYOR",
  "SIDE DISCHARGE CONVEYOR",
  "LEFT DISCHARGE",
  "RIGHT DISCHARGE",
  "DUAL SPOIL AUGERS",
  "AUGER EXTENSIONS",
  "CRUMBER BAR",
  "CLEANOUT SHOE",
  "TRENCH CLEANER",
  "SPOIL DEFLECTOR",

  /* -------------------- */
  /* GRADE / DEPTH DNA */
  /* -------------------- */

  "DEPTH CONTROL",
  "MANUAL DEPTH CONTROL",
  "HYDRAULIC DEPTH CONTROL",
  "AUTOMATIC DEPTH CONTROL",
  "LASER CONTROL",
  "GPS READY",
  "GNSS READY",
  "GRADE CONTROL",
  "LASER READY",
  "GRADE SENSOR",
  "DEPTH SENSOR",
  "SLOPE SENSOR",
  "BOOM POSITION SENSOR",
  "PLOW DEPTH SENSOR",
  "WHEEL DEPTH SENSOR",
  "AUTO DEPTH",
  "DEPTH INDICATOR",
  "CUT DEPTH CONTROL",

  /* -------------------- */
  /* ATTACHMENT DNA */
  /* -------------------- */

  "TRENCHER ATTACHMENT",
  "PLOW ATTACHMENT",
  "ROCKWHEEL ATTACHMENT",
  "BACKHOE ATTACHMENT",
  "BORE ATTACHMENT",
  "ROD PUSHER",
  "REEL CARRIER",
  "CABLE REEL",
  "CONDUIT REEL",
  "PIPE REEL",
  "BACKFILL BLADE",
  "6 WAY BLADE",
  "DOZER BLADE",
  "BORING ATTACHMENT",
  "ROD BOX",
  "HYDRA BORE",
  "DRILL ROD",
  "AUGER BORING ATTACHMENT",
  "VACUUM ATTACHMENT",
  "TRENCH BACKFILLER",
  "POWER TAKEOFF ATTACHMENT",

  /* -------------------- */
  /* CAB / GUARDING DNA */
  /* -------------------- */

  "ROPS",
  "OPEN ROPS",
  "FOPS",
  "C/H/A",
  "ENCLOSED CAB",
  "AIR CONDITIONED CAB",
  "HEATED CAB",
  "CANOPY",
  "OPERATOR PLATFORM",
  "WALK BEHIND CONTROLS",
  "RIDE ON CONTROLS",
  "JOYSTICK CONTROLS",
  "PILOT CONTROLS",
  "ELECTROHYDRAULIC CONTROLS",
  "FULL GUARDING",
  "ROCK GUARDS",
  "DEBRIS GUARDS",
  "CHAIN GUARDS",
  "WHEEL GUARDS",
  "ENGINE GUARDS",
  "HYDRAULIC LINE GUARDS",
  "BELLY GUARDS",
  "TRACK GUARDS",

  /* -------------------- */
  /* STABILIZER DNA */
  /* -------------------- */

  "STABILIZERS",
  "HYDRAULIC STABILIZERS",
  "REAR STABILIZERS",
  "FRONT STABILIZERS",
  "OUTRIGGERS",
  "HYDRAULIC OUTRIGGERS",
  "LEVELING JACKS",
  "SIDE STABILIZERS",
  "TRENCHER STABILIZERS",
  "PLOW STABILIZERS",
  "STABILIZER PADS",
  "AUTO LEVELING",
  "SELF LEVELING",

  /* -------------------- */
  /* AUTOMATION / TRACKING DNA */
  /* -------------------- */

  "TELEMATICS",
  "REMOTE DIAGNOSTICS",
  "GPS TRACKING",
  "FLEET MANAGEMENT",
  "BORE TRACKING",
  "LINE LOCATOR",
  "GUIDANCE READY",
  "AUTO DEPTH CONTROL",
  "MACHINE CONTROL READY",
  "LOAD CONTROL",
  "ENGINE LOAD CONTROL",
  "AUTO CREEP",
  "AUTO IDLE",
  "AUTO SHUTDOWN",
  "DIAGNOSTIC DISPLAY",
  "MULTIFUNCTION DISPLAY",
  "CAMERA SYSTEM",
  "REAR CAMERA",

  /* -------------------- */
  /* COOLING DNA */
  /* -------------------- */

  "HIGH CAPACITY COOLING",
  "HYDRAULIC OIL COOLER",
  "REVERSING FAN",
  "AUTO REVERSING FAN",
  "DEBRIS PACKAGE",
  "DEBRIS SCREEN",
  "RADIATOR SCREEN",
  "ROCK TRENCHER COOLING PACKAGE",
  "HIGH AMBIENT COOLING",
  "SWING OUT COOLER",
  "COOLING CLEANOUT",

  /* -------------------- */
  /* POWERTRAIN DNA */
  /* -------------------- */

  "DIESEL ENGINE",
  "GAS ENGINE",
  "ELECTRIC MOTOR",
  "BATTERY ELECTRIC",
  "TURBOCHARGED",
  "INTERCOOLED",
  "COMMON RAIL",
  "MECHANICAL INJECTION",
  "ELECTRONIC ENGINE",
  "AUTO IDLE",
  "ENGINE SHUTDOWN TIMER",
  "COLD WEATHER PACKAGE",
  "BLOCK HEATER",
  "ETHER START",
  "CLUTCH DRIVE",
  "PTO DRIVE",

  /* -------------------- */
  /* SAFETY / ELECTRICAL DNA */
  /* -------------------- */

  "LED LIGHTS",
  "WORK LIGHT PACKAGE",
  "BEACON",
  "STROBE LIGHT",
  "BACKUP ALARM",
  "TRAVEL ALARM",
  "EMERGENCY STOP",
  "OPERATOR PRESENCE SYSTEM",
  "SEAT BELT",
  "PARK BRAKE",
  "BATTERY DISCONNECT",
  "MASTER DISCONNECT",
  "FIRE SUPPRESSION",
  "AUTO LUBE",
  "CENTRALIZED GREASING",
  "SERVICE LOCKS",
  "VANDAL GUARDS",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-DEF",
  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4",
  "TIER 4 FINAL",
  "T4F",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF",
  "DEF DELETE"
];

export default trencherDnaKeywords;
