const truckDnaKeywords = [

  /* -------------------- */
  /* CAB CONFIGURATION DNA */
  /* -------------------- */

  "DAY CAB",
  "SLEEPER",
  "MID ROOF SLEEPER",
  "HIGH ROOF SLEEPER",
  "FLAT TOP SLEEPER",
  "INTEGRATED SLEEPER",
  "DOUBLE BUNK",
  "STUDIO SLEEPER",
  "CREW CAB",
  "REGULAR CAB",
  "EXTENDED CAB",
  "CHASSIS CAB",
  "LOW CAB FORWARD",
  "LCF",
  "CABOVER",
  "COE",
  "CONVENTIONAL",
  "SET BACK AXLE",
  "SET FORWARD AXLE",
  "ALUMINUM CAB",
  "STEEL CAB",
  "HIGH VISIBILITY CAB",
  "WORKSTATION INTERIOR",
  "AIR RIDE CAB",
  "SUSPENDED CAB",
  "CAB GUARD",
  "HEADACHE RACK",

  /* -------------------- */
  /* CHASSIS / FRAME DNA */
  /* -------------------- */

  "STRAIGHT FRAME",
  "DOUBLE FRAME",
  "SINGLE FRAME",
  "REINFORCED FRAME",
  "HEAVY DUTY FRAME",
  "SEVERE DUTY FRAME",
  "HIGH TENSILE FRAME",
  "FRAME LINER",
  "BBC",
  "SHORT WHEELBASE",
  "LONG WHEELBASE",
  "LOW PROFILE CHASSIS",
  "SEVERE SERVICE CHASSIS",
  "VOCATIONAL CHASSIS",
  "HIGH RAIL CHASSIS",
  "PTO READY CHASSIS",
  "ROLL OFF CHASSIS",
  "HOOKLIFT CHASSIS",
  "MIXER CHASSIS",
  "CRANE CHASSIS",

  /* -------------------- */
  /* AXLE DNA */
  /* -------------------- */

  "SINGLE AXLE",
  "TANDEM AXLE",
  "TRI AXLE",
  "QUAD AXLE",
  "PUSHER AXLE",
  "TAG AXLE",
  "DROP AXLE",
  "LIFT AXLE",
  "STEERABLE LIFT AXLE",
  "NON STEER LIFT AXLE",
  "PUSH AXLE",
  "REAR LIFT AXLE",
  "FRONT LIFT AXLE",
  "OSCILLATING AXLE",
  "PLANETARY AXLES",
  "HEAVY DUTY AXLES",
  "MERITOR AXLES",
  "DANA AXLES",
  "EATON AXLES",

  /* -------------------- */
  /* SUSPENSION DNA */
  /* -------------------- */

  "AIR RIDE",
  "SPRING RIDE",
  "WALKING BEAM",
  "HENDRICKSON",
  "HENDRICKSON HAULMAAX",
  "HENDRICKSON PRIMAAX",
  "CHALMERS",
  "NEWAY",
  "REYCO",
  "TORQUE ROD SUSPENSION",
  "MULTILEAF SPRING",
  "TAPER LEAF SPRING",
  "RUBBER BLOCK SUSPENSION",
  "AIR LEAF SUSPENSION",
  "FOUR BAG AIR RIDE",
  "EIGHT BAG AIR RIDE",
  "CAB AIR SUSPENSION",
  "AIR GLIDE",
  "LOW AIR LEAF",
  "HEAVY HAUL SUSPENSION",

  /* -------------------- */
  /* DIFFERENTIAL / TRACTION DNA */
  /* -------------------- */

  "LOCKING DIFFERENTIAL",
  "FULL LOCKERS",
  "INTERAXLE LOCK",
  "CROSS LOCK",
  "POWER DIVIDER",
  "TRACTION CONTROL",
  "LIMITED SLIP DIFFERENTIAL",
  "LOCKING REARS",
  "MERITOR DIFFERENTIAL",
  "EATON DIFFERENTIAL",
  "DRIVER CONTROLLED LOCKERS",
  "AUTO LOCKING DIFFERENTIAL",

  /* -------------------- */
  /* DRIVE CONFIGURATION DNA */
  /* -------------------- */

  "4X2",
  "4X4",
  "6X2",
  "6X4",
  "6X6",
  "8X4",
  "8X6",
  "8X8",
  "10X4",
  "10X6",
  "10X8",
  "ALL WHEEL DRIVE",
  "FRONT DRIVE AXLE",
  "REAR DRIVE AXLE",
  "TANDEM DRIVE",
  "DUAL DRIVE",
  "HEAVY HAUL DRIVE",
  "OFF ROAD DRIVE",

  /* -------------------- */
  /* TRANSMISSION DNA */
  /* -------------------- */

  "AUTOMATIC",
  "MANUAL TRANSMISSION",
  "AUTOMATED MANUAL",
  "EATON FULLER",
  "ALLISON",
  "DETROIT DT12",
  "ULTRASHIFT",
  "AUTO SHIFT",
  "13 SPEED",
  "18 SPEED",
  "10 SPEED",
  "9 SPEED",
  "6 SPEED",
  "5 SPEED",
  "DIRECT DRIVE",
  "OVERDRIVE",
  "DOUBLE OVERDRIVE",
  "TORQUE CONVERTER",
  "SYNCHRONIZED TRANSMISSION",
  "TWO SPEED REAR",
  "CREEPER GEAR",

  /* -------------------- */
  /* ENGINE DNA */
  /* -------------------- */

  "CUMMINS",
  "DETROIT",
  "CAT",
  "PACCAR",
  "MAXXFORCE",
  "DURAMAX",
  "POWERSTROKE",
  "TURBOCHARGED",
  "INTERCOOLED",
  "COMMON RAIL",
  "MECHANICAL INJECTION",
  "ELECTRONIC ENGINE",
  "NATURAL GAS",
  "CNG",
  "LNG",
  "HYBRID",
  "ELECTRIC",
  "BATTERY ELECTRIC",
  "DIESEL",
  "LP GAS",
  "AUTO IDLE",
  "ENGINE BRAKE",
  "JAKE BRAKE",

  /* -------------------- */
  /* PTO / HYDRAULIC DNA */
  /* -------------------- */

  "PTO",
  "DUAL PTO",
  "LIVE PTO",
  "HOT SHIFT PTO",
  "SPLIT SHAFT PTO",
  "CHELSEA PTO",
  "MUNCIE PTO",
  "WET KIT",
  "HYDRAULIC SYSTEM",
  "HYDRAULIC TANK",
  "HYDRAULIC PUMP",
  "LOAD SENSING HYDRAULICS",
  "AUX HYDRAULICS",
  "HIGH FLOW HYDRAULICS",
  "HYDRAULIC COOLER",
  "HYDRAULIC WINCH",
  "HYDRAULIC STABILIZERS",

  /* -------------------- */
  /* DUMP / HOIST DNA */
  /* -------------------- */

  "DUMP BODY",
  "HALF ROUND BODY",
  "SQUARE BODY",
  "END DUMP",
  "SIDE DUMP",
  "TRANSFER DUMP",
  "BELLY DUMP",
  "BOTTOM DUMP",
  "HIGH LIFT GATE",
  "AIR TAILGATE",
  "COAL BODY",
  "LIGHT MATERIAL BODY",
  "AR BODY",
  "HARDOX BODY",
  "SCISSOR HOIST",
  "TELESCOPIC HOIST",
  "UNDERBODY HOIST",
  "DOUBLE ACTING HOIST",
  "ELECTRIC TARP",
  "ROLL TARP",

  /* -------------------- */
  /* BODY SYSTEM DNA */
  /* -------------------- */

  "ROLL OFF",
  "HOOKLIFT",
  "VACUUM TRUCK",
  "HYDROVAC",
  "WATER TRUCK",
  "FUEL/LUBE TRUCK",
  "SERVICE BODY",
  "MECHANICS BODY",
  "CRANE BODY",
  "BOOM TRUCK",
  "KNUCKLE BOOM",
  "WRECKER",
  "ROLLBACK",
  "FLATBED",
  "STAKE BED",
  "BOX TRUCK",
  "CURTAIN SIDE",
  "MIXER BODY",
  "REFUSE BODY",
  "GRAPPLE BODY",
  "LOGGING BODY",
  "VACUUM TANK",
  "SEPTIC TANK",
  "TANKER BODY",
  "DRY BULK BODY",
  "BULK FEED BODY",
  "LIVE FLOOR",
  "WALKING FLOOR",
  "CHIPPER BODY",
  "ATTENUATOR BODY",

  /* -------------------- */
  /* CRANE / BOOM DNA */
  /* -------------------- */

  "SERVICE CRANE",
  "TELESCOPIC CRANE",
  "ARTICULATING CRANE",
  "ROTATOR",
  "HYDRAULIC OUTRIGGERS",
  "CRANE STABILIZERS",
  "WINCH",
  "PLANETARY WINCH",
  "MAN BASKET READY",
  "AUXILIARY WINCH",
  "JIB",
  "FLY JIB",
  "LOAD MOMENT INDICATOR",
  "LMI",
  "ANTI TWO BLOCK",

  /* -------------------- */
  /* TOWING / RECOVERY DNA */
  /* -------------------- */

  "INTEGRATED WRECKER",
  "UNDERLIFT",
  "WHEEL LIFT",
  "SELF LOADER",
  "ROTATOR WRECKER",
  "HEAVY WRECKER",
  "MEDIUM DUTY WRECKER",
  "LIGHT DUTY WRECKER",
  "SLIDE BED",
  "TILT BED",
  "REPO WHEEL LIFT",
  "RECOVERY WINCH",
  "DUAL WINCH",
  "SIDE RECOVERY",
  "BOOM RECOVERY",
  "UNDER REACH",

  /* -------------------- */
  /* TANK / VACUUM DNA */
  /* -------------------- */

  "VACUUM SYSTEM",
  "POSITIVE DISPLACEMENT BLOWER",
  "WET VAC",
  "DRY VAC",
  "HYDRO EXCAVATION SYSTEM",
  "JETTER SYSTEM",
  "WATER BLASTER",
  "DEBRIS TANK",
  "WATER TANK",
  "STAINLESS TANK",
  "ALUMINUM TANK",
  "FUEL TANK",
  "LUBE SYSTEM",
  "HOSE REEL",
  "BOOM SYSTEM",
  "ARTICULATING BOOM",
  "HYDRAULIC BOOM",

  /* -------------------- */
  /* STEERING DNA */
  /* -------------------- */

  "POWER STEERING",
  "HYDRAULIC STEERING",
  "DUAL STEERING BOX",
  "SELF STEER AXLE",
  "ALL WHEEL STEER",
  "CRAB STEER",
  "REAR STEER",
  "FRONT AXLE SETBACK",

  /* -------------------- */
  /* BRAKE / RETARDER DNA */
  /* -------------------- */

  "AIR BRAKES",
  "HYDRAULIC BRAKES",
  "DISC BRAKES",
  "DRUM BRAKES",
  "RETARDER",
  "TRANSMISSION RETARDER",
  "EXHAUST BRAKE",
  "ABS",
  "HILL HOLD",
  "SPRING BRAKES",

  /* -------------------- */
  /* TIRE / WHEEL DNA */
  /* -------------------- */

  "ALUMINUM WHEELS",
  "STEEL WHEELS",
  "SUPER SINGLE",
  "DUALS",
  "LOW PROFILE TIRES",
  "FLOATATION TIRES",
  "OFF ROAD TIRES",
  "MUD TIRES",
  "DRIVE TIRES",
  "STEER TIRES",
  "RECAPPED TIRES",
  "WIDE BASE TIRES",
  "PNEUMATIC TIRES",

  /* -------------------- */
  /* ELECTRICAL / LIGHTING DNA */
  /* -------------------- */

  "LED LIGHTS",
  "WORK LIGHT PACKAGE",
  "STROBE LIGHTS",
  "BEACON",
  "AUXILIARY LIGHTING",
  "DUAL ALTERNATORS",
  "HIGH OUTPUT ALTERNATOR",
  "BATTERY DISCONNECT",
  "MASTER DISCONNECT",
  "INVERTER",
  "POWER INVERTER",
  "JUMP START POSTS",
  "BLOCK HEATER",

  /* -------------------- */
  /* SAFETY / AUTOMATION DNA */
  /* -------------------- */

  "TELEMATICS",
  "REMOTE START",
  "REMOTE DIAGNOSTICS",
  "CAMERA SYSTEM",
  "360 CAMERA",
  "BACKUP CAMERA",
  "LANE ASSIST",
  "COLLISION MITIGATION",
  "ADAPTIVE CRUISE",
  "BLIND SPOT MONITOR",
  "LOAD SCALE",
  "AUTO GREASER",
  "CENTRAL LUBE",
  "FIRE SUPPRESSION",
  "DRIVER MONITORING",
  "GPS TRACKING",
  "E LOG READY",

  /* -------------------- */
  /* HITCH / TOW DNA */
  /* -------------------- */

  "FIFTH WHEEL",
  "AIR SLIDE FIFTH WHEEL",
  "FIXED FIFTH WHEEL",
  "GOOSENECK HITCH",
  "PINTLE HITCH",
  "RECEIVER HITCH",
  "DRAWBAR",
  "TRAILER BRAKE CONTROLLER",
  "GLAD HANDS",
  "TRAILER AIR SUPPLY",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-EMISSIONS",
  "PRE-DEF",
  "TIER 3",
  "TIER 4",
  "T4F",
  "STAGE V",
  "EGR",
  "SCR",
  "DPF",
  "DEF",
  "DEF DELETE",
  "EGR DELETE",
  "NO DEF",
  "NO DPF"
];

export default truckDnaKeywords;
