// TRUCKS

const trucksTaxonomy = [
  
  // AMBULANCE

{ make: "AMBULANCE", model: "CHEVROLET" },
{ make: "AMBULANCE", model: "FORD" },
{ make: "AMBULANCE", model: "FREIGHTLINER" },
{ make: "AMBULANCE", model: "INTERNATIONAL" },
{ make: "AMBULANCE", model: "RAM" },
{ make: "AMBULANCE", model: "SPARTAN" },
{ make: "AMBULANCE", model: "STERLING" },
{ make: "AMBULANCE", model: "TOYOTA" },
{ make: "AMBULANCE", model: "OTHER" },
  
 // ATTENUATOR TRUCKS

{ make: "ATTENUATOR TRUCKS", model: "FORD" },
{ make: "ATTENUATOR TRUCKS", model: "FREIGHTLINER" },
{ make: "ATTENUATOR TRUCKS", model: "GMC" },
{ make: "ATTENUATOR TRUCKS", model: "HINO" },
{ make: "ATTENUATOR TRUCKS", model: "INTERNATIONAL" },
{ make: "ATTENUATOR TRUCKS", model: "KENWORTH" },
{ make: "ATTENUATOR TRUCKS", model: "MACK" },
{ make: "ATTENUATOR TRUCKS", model: "OTHER" },
  
  // BEVERAGE TRUCKS

{ make: "BEVERAGE TRUCKS", model: "CHEVROLET" },
{ make: "BEVERAGE TRUCKS", model: "FORD" },
{ make: "BEVERAGE TRUCKS", model: "FRIGHTLINER" },
{ make: "BEVERAGE TRUCKS", model: "HINO" },
{ make: "BEVERAGE TRUCKS", model: "INTERNATIONAL" },
{ make: "BEVERAGE TRUCKS", model: "ISUZU" },
{ make: "BEVERAGE TRUCKS", model: "KENWORTH" },
{ make: "BEVERAGE TRUCKS", model: "MACK" },
{ make: "BEVERAGE TRUCKS", model: "PETERBILT" },
{ make: "BEVERAGE TRUCKS", model: "RAM" },
{ make: "BEVERAGE TRUCKS", model: "OTHER" },
  
 // BOOM TRUCKS CRANES

{ make: "BOOM TRUCKS CRANES", model: "MANITEX" },
{ make: "BOOM TRUCKS CRANES", model: "NATIONAL" },
{ make: "BOOM TRUCKS CRANES", model: "STELLAR" },
{ make: "BOOM TRUCKS CRANES", model: "TEREX" },
{ make: "BOOM TRUCKS CRANES", model: "ALTEC" },
{ make: "BOOM TRUCKS CRANES", model: "IMT" },
{ make: "BOOM TRUCKS CRANES", model: "ELLIOTT" },
{ make: "BOOM TRUCKS CRANES", model: "PALFINGER" },
{ make: "BOOM TRUCKS CRANES", model: "LOAD KING" },
{ make: "BOOM TRUCKS CRANES", model: "XCMG" },
{ make: "BOOM TRUCKS CRANES", model: "AUTO CRANE" },
{ make: "BOOM TRUCKS CRANES", model: "BOCKER" },
{ make: "BOOM TRUCKS CRANES", model: "CAPTAIN" },
{ make: "BOOM TRUCKS CRANES", model: "CONDOR" },
{ make: "BOOM TRUCKS CRANES", model: "CRANE WORKS" },
{ make: "BOOM TRUCKS CRANES", model: "DALL'AGLIO NEWCRANES" },
{ make: "BOOM TRUCKS CRANES", model: "DFI" },
{ make: "BOOM TRUCKS CRANES", model: "DONGYANG" },
{ make: "BOOM TRUCKS CRANES", model: "FURUKAWA" },
{ make: "BOOM TRUCKS CRANES", model: "GARLAND" },
{ make: "BOOM TRUCKS CRANES", model: "LIFTMOORE" },
{ make: "BOOM TRUCKS CRANES", model: "MAINTAINER" },
{ make: "BOOM TRUCKS CRANES", model: "MAXLIFT" },
{ make: "BOOM TRUCKS CRANES", model: "PIONEER" },
{ make: "BOOM TRUCKS CRANES", model: "QMC" },
{ make: "BOOM TRUCKS CRANES", model: "REVOLUTION" },
{ make: "BOOM TRUCKS CRANES", model: "RO STINGER" },
{ make: "BOOM TRUCKS CRANES", model: "SIMON-RO" },
{ make: "BOOM TRUCKS CRANES", model: "SKYHOOK" },
{ make: "BOOM TRUCKS CRANES", model: "SUMMIT TRUCK BODIES" },
{ make: "BOOM TRUCKS CRANES", model: "TADANO" },
{ make: "BOOM TRUCKS CRANES", model: "UNIC" },
{ make: "BOOM TRUCKS CRANES", model: "USTC" },
{ make: "BOOM TRUCKS CRANES", model: "VENTURO" },
{ make: "BOOM TRUCKS CRANES", model: "WELDCO HYDRALIFT" },
{ make: "BOOM TRUCKS CRANES", model: "WILKIE" },
{ make: "BOOM TRUCKS CRANES", model: "OTHER" },

 // BOX TRUCKS

{ make: "BOX TRUCKS", model: "FREIGHTLINER" },
{ make: "BOX TRUCKS", model: "INTERNATIONAL" },
{ make: "BOX TRUCKS", model: "ISUZU" },
{ make: "BOX TRUCKS", model: "HINO" },
{ make: "BOX TRUCKS", model: "FORD" },
{ make: "BOX TRUCKS", model: "GMC" },
{ make: "BOX TRUCKS", model: "CHEVROLET" },
{ make: "BOX TRUCKS", model: "KENWORTH" },
{ make: "BOX TRUCKS", model: "MACK" },
{ make: "BOX TRUCKS", model: "PETERBILT" },
{ make: "BOX TRUCKS", model: "BATTLE MOTORS" },
{ make: "BOX TRUCKS", model: "BOLLINGER" },
{ make: "BOX TRUCKS", model: "GREEN POWER" },
{ make: "BOX TRUCKS", model: "GREENKRAFT" },
{ make: "BOX TRUCKS", model: "MERCEDES-BENZ" },
{ make: "BOX TRUCKS", model: "MITSUBISHI" },
{ make: "BOX TRUCKS", model: "MULLIN" },
{ make: "BOX TRUCKS", model: "RAM" },
{ make: "BOX TRUCKS", model: "RIZON" },
{ make: "BOX TRUCKS", model: "STERLING" },
{ make: "BOX TRUCKS", model: "UD" },
{ make: "BOX TRUCKS", model: "VOLVO" },
{ make: "BOX TRUCKS", model: "WESTERN STAR" },
{ make: "BOX TRUCKS", model: "WORKHORSE" },
{ make: "BOX TRUCKS", model: "OTHER" },

  // BUCKET TRUCKS

{ make: "BUCKET TRUCKS", model: "ALTEC" },
{ make: "BUCKET TRUCKS", model: "VERSALIFT" },
{ make: "BUCKET TRUCKS", model: "TEREX" },
{ make: "BUCKET TRUCKS", model: "DUR-A-LIFT" },
{ make: "BUCKET TRUCKS", model: "ETI" },
{ make: "BUCKET TRUCKS", model: "PALFINGER" },
{ make: "BUCKET TRUCKS", model: "HI RANGER" },
{ make: "BUCKET TRUCKS", model: "POSI-PLUS" },
{ make: "BUCKET TRUCKS", model: "UTEM" },
{ make: "BUCKET TRUCKS", model: "RH" },
{ make: "BUCKET TRUCKS", model: "AXIONLIFT" },
{ make: "BUCKET TRUCKS", model: "CUSTERS" },
{ make: "BUCKET TRUCKS", model: "ELLIOTT" },
{ make: "BUCKET TRUCKS", model: "HOLAN" },
{ make: "BUCKET TRUCKS", model: "LIFTALL" },
{ make: "BUCKET TRUCKS", model: "LAODKING" },
{ make: "BUCKET TRUCKS", model: "MAINTAINER" },
{ make: "BUCKET TRUCKS", model: "MTI" },
{ make: "BUCKET TRUCKS", model: "NORSTAR" },
{ make: "BUCKET TRUCKS", model: "SIMON-TELELECT" },
{ make: "BUCKET TRUCKS", model: "SKYLIFT" },
{ make: "BUCKET TRUCKS", model: "SKYLIFT/VERSALIFT" },
{ make: "BUCKET TRUCKS", model: "SKYVAN" },
{ make: "BUCKET TRUCKS", model: "SVABO-LIFTEN" },
{ make: "BUCKET TRUCKS", model: "TECO" },
{ make: "BUCKET TRUCKS", model: "TELELIFT" },
{ make: "BUCKET TRUCKS", model: "TELSTA" },
{ make: "BUCKET TRUCKS", model: "VAN LADDER" },
{ make: "BUCKET TRUCKS", model: "OTHER" },

// CUB & CHASSIS TRUCKS

{ make: "CUB & CHASSIS TRUCKS", model: "INTERNATIONAL" },
{ make: "CUB & CHASSIS TRUCKS", model: "FORD" },
{ make: "CUB & CHASSIS TRUCKS", model: "ISUZU" },
{ make: "CUB & CHASSIS TRUCKS", model: "PETERBILT" },
{ make: "CUB & CHASSIS TRUCKS", model: "KENWORTH" },
{ make: "CUB & CHASSIS TRUCKS", model: "FREIGHTLINER" },
{ make: "CUB & CHASSIS TRUCKS", model: "MACK" },
{ make: "CUB & CHASSIS TRUCKS", model: "HINO" },
{ make: "CUB & CHASSIS TRUCKS", model: "CHEVROLET" },
{ make: "CUB & CHASSIS TRUCKS", model: "WESTERN STAR" },
{ make: "CUB & CHASSIS TRUCKS", model: "ACELA" },
{ make: "CUB & CHASSIS TRUCKS", model: "AMERICAN LAFRANCE" },
{ make: "CUB & CHASSIS TRUCKS", model: "AUTOCAR" },
{ make: "CUB & CHASSIS TRUCKS", model: "BATTLE MOTORS" },
{ make: "CUB & CHASSIS TRUCKS", model: "BOLLINGER" },
{ make: "CUB & CHASSIS TRUCKS", model: "BROCKWAY" },
{ make: "CUB & CHASSIS TRUCKS", model: "CATERPILLAR" },
{ make: "CUB & CHASSIS TRUCKS", model: "CCC" },
{ make: "CUB & CHASSIS TRUCKS", model: "DENNIS EAGLE" },
{ make: "CUB & CHASSIS TRUCKS", model: "DIAMOND REO" },
{ make: "CUB & CHASSIS TRUCKS", model: "DODGE" },
{ make: "CUB & CHASSIS TRUCKS", model: "GMC" },
{ make: "CUB & CHASSIS TRUCKS", model: "GREEN POWER" },
{ make: "CUB & CHASSIS TRUCKS", model: "GREENKRAFT" },
{ make: "CUB & CHASSIS TRUCKS", model: "LION" },
{ make: "CUB & CHASSIS TRUCKS", model: "MAN" },
{ make: "CUB & CHASSIS TRUCKS", model: "MITSUBISHI" },
{ make: "CUB & CHASSIS TRUCKS", model: "MULLEN" },
{ make: "CUB & CHASSIS TRUCKS", model: "OSHKOSH" },
{ make: "CUB & CHASSIS TRUCKS", model: "RAM" },
{ make: "CUB & CHASSIS TRUCKS", model: "RIZON" },
{ make: "CUB & CHASSIS TRUCKS", model: "SEA" },
{ make: "CUB & CHASSIS TRUCKS", model: "SINOTRUK" },
{ make: "CUB & CHASSIS TRUCKS", model: "STERLING" },
{ make: "CUB & CHASSIS TRUCKS", model: "UD" },
{ make: "CUB & CHASSIS TRUCKS", model: "VOLVO" },
{ make: "CUB & CHASSIS TRUCKS", model: "WHITE/GMC" },
{ make: "CUB & CHASSIS TRUCKS", model: "OTHER" },

 // CAR HAULER TRUCKS

{ make: "CAR HAULER TRUCKS", model: "FREIGHTLINER" },
{ make: "CAR HAULER TRUCKS", model: "HINO" },
{ make: "CAR HAULER TRUCKS", model: "INTERNATIONAL" },
{ make: "CAR HAULER TRUCKS", model: "KENWORTH" },
{ make: "CAR HAULER TRUCKS", model: "MACK" },
{ make: "CAR HAULER TRUCKS", model: "PETERBILT" },
{ make: "CAR HAULER TRUCKS", model: "SHOW HAULER" },
{ make: "CAR HAULER TRUCKS", model: "STERLING" },
{ make: "CAR HAULER TRUCKS", model: "VOLVO" },
{ make: "CAR HAULER TRUCKS", model: "WESTERN STAR" },
{ make: "CAR HAULER TRUCKS", model: "OTHER" },
  
  // CHIPPER TRUCKS

{ make: "CHIPPER TRUCKS", model: "CHEVROLET" },
{ make: "CHIPPER TRUCKS", model: "FORD" },
{ make: "CHIPPER TRUCKS", model: "FREIGHTLINER" },
{ make: "CHIPPER TRUCKS", model: "GMC" },
{ make: "CHIPPER TRUCKS", model: "HINO" },
{ make: "CHIPPER TRUCKS", model: "INTERNATIONAL" },
{ make: "CHIPPER TRUCKS", model: "ISUZU" },
{ make: "CHIPPER TRUCKS", model: "KENWORTH" },
{ make: "CHIPPER TRUCKS", model: "MACK" },
{ make: "CHIPPER TRUCKS", model: "PETERBILT" },
{ make: "CHIPPER TRUCKS", model: "RAM" },
{ make: "CHIPPER TRUCKS", model: "SCANIA" },
{ make: "CHIPPER TRUCKS", model: "STERLING" },
{ make: "CHIPPER TRUCKS", model: "OTHER" },

 // CURTAIN SIDE TRUCKS

{ make: "CURTAIN SIDE TRUCKS", model: "FORD" },
{ make: "CURTAIN SIDE TRUCKS", model: "FREIGHTLINERF" },
{ make: "CURTAIN SIDE TRUCKS", model: "GMC" },
{ make: "CURTAIN SIDE TRUCKS", model: "HINO" },
{ make: "CURTAIN SIDE TRUCKS", model: "INTERNATIONAL" },
{ make: "CURTAIN SIDE TRUCKS", model: "ISUZU" },
{ make: "CURTAIN SIDE TRUCKS", model: "KENWORTH" },
{ make: "CURTAIN SIDE TRUCKS", model: "MACK" },
{ make: "CURTAIN SIDE TRUCKS", model: "PETERBILT" },
{ make: "CURTAIN SIDE TRUCKS", model: "VOLVO" },
{ make: "CURTAIN SIDE TRUCKS", model: "OTHER" },

  // DAY CAB TRUCKS

{ make: "DAY CAB TRUCKS", model: "FREIGHTLINER" },
{ make: "DAY CAB TRUCKS", model: "INTERNATIONAL" },
{ make: "DAY CAB TRUCKS", model: "PETERBILT" },
{ make: "DAY CAB TRUCKS", model: "KENWORTH" },
{ make: "DAY CAB TRUCKS", model: "MACK" },
{ make: "DAY CAB TRUCKS", model: "VOLVO" },
{ make: "DAY CAB TRUCKS", model: "WESTERN STAR" },
{ make: "DAY CAB TRUCKS", model: "STERLING" },
{ make: "DAY CAB TRUCKS", model: "FORD" },
{ make: "DAY CAB TRUCKS", model: "UNSPECIFIED" },
{ make: "DAY CAB TRUCKS", model: "AM GENERAL" },
{ make: "DAY CAB TRUCKS", model: "AUTOCAR" },
{ make: "DAY CAB TRUCKS", model: "BATTLE MOTORS" },
{ make: "DAY CAB TRUCKS", model: "BMY" },
{ make: "DAY CAB TRUCKS", model: "CATERPILLAR" },
{ make: "DAY CAB TRUCKS", model: "CHEVROLET" },
{ make: "DAY CAB TRUCKS", model: "CLINE" },
{ make: "DAY CAB TRUCKS", model: "KAISER" },
{ make: "DAY CAB TRUCKS", model: "KIZER" },
{ make: "DAY CAB TRUCKS", model: "MAN" },
{ make: "DAY CAB TRUCKS", model: "NIKOLA" },
{ make: "DAY CAB TRUCKS", model: "OSHKOSH" },
{ make: "DAY CAB TRUCKS", model: "RAM" },
{ make: "DAY CAB TRUCKS", model: "SINOTRUK" },
{ make: "DAY CAB TRUCKS", model: "WHITE / GMC" },
{ make: "DAY CAB TRUCKS", model: "OTHER" },

  // DIGGER DERRICKS

{ make: "DIGGER DERRICKS", model: "ALTEC" },
{ make: "DIGGER DERRICKS", model: "ELLIOTT" },
{ make: "DIGGER DERRICKS", model: "HIAB" },
{ make: "DIGGER DERRICKS", model: "IMT" },
{ make: "DIGGER DERRICKS", model: "NATIONAL" },
{ make: "DIGGER DERRICKS", model: "PITMAN" },
{ make: "DIGGER DERRICKS", model: "SDP" },
{ make: "DIGGER DERRICKS", model: "SIMON-TELELECT" },
{ make: "DIGGER DERRICKS", model: "SKYLIFT" },
{ make: "DIGGER DERRICKS", model: "TELELECT" },
{ make: "DIGGER DERRICKS", model: "TEREX" },
{ make: "DIGGER DERRICKS", model: "UTV INTERNATIONAL" },
{ make: "DIGGER DERRICKS", model: "VERSALIFT" },
{ make: "DIGGER DERRICKS", model: "OTHER" },

  // DUMP - TRANSFER TRUCKS

{ make: "DUMP - TRANSFER TRUCKS", model: "FREIGHTLINER" },
{ make: "DUMP - TRANSFER TRUCKS", model: "INTERNATIONAL" },
{ make: "DUMP - TRANSFER TRUCKS", model: "KENWORTH" },
{ make: "DUMP - TRANSFER TRUCKS", model: "MACK" },
{ make: "DUMP - TRANSFER TRUCKS", model: "PETERBILT" },
{ make: "DUMP - TRANSFER TRUCKS", model: "RELIANCE" },
{ make: "DUMP - TRANSFER TRUCKS", model: "SINOTRUCK" },
{ make: "DUMP - TRANSFER TRUCKS", model: "VOLVO" },
{ make: "DUMP - TRANSFER TRUCKS", model: "WESTERN STAR" },
{ make: "DUMP - TRANSFER TRUCKS", model: "OTHER" },

  // DUMP TRUCKS

{ make: "DUMP TRUCKS", model: "KENWORTH" },
{ make: "DUMP TRUCKS", model: "PETERBILT" },
{ make: "DUMP TRUCKS", model: "MACK" },
{ make: "DUMP TRUCKS", model: "FORD" },
{ make: "DUMP TRUCKS", model: "FREIGHTLINER" },
{ make: "DUMP TRUCKS", model: "WESTERN STAR" },
{ make: "DUMP TRUCKS", model: "INTERNATIONAL" },
{ make: "DUMP TRUCKS", model: "VOLVO" },
{ make: "DUMP TRUCKS", model: "ISUZU" },
{ make: "DUMP TRUCKS", model: "CHEVROLET" },
{ make: "DUMP TRUCKS", model: "AM GENERAL" },
{ make: "DUMP TRUCKS", model: "AMERICAN LAFRANCE" },
{ make: "DUMP TRUCKS", model: "AUTOCAR" },
{ make: "DUMP TRUCKS", model: "BATTLE MOTORS" },
{ make: "DUMP TRUCKS", model: "BMY" },
{ make: "DUMP TRUCKS", model: "CATERPILLAR" },
{ make: "DUMP TRUCKS", model: "CHEVROLET" },
{ make: "DUMP TRUCKS", model: "DODGE" },
{ make: "DUMP TRUCKS", model: "FOTON" },
{ make: "DUMP TRUCKS", model: "GMC" },
{ make: "DUMP TRUCKS", model: "HINO" },
{ make: "DUMP TRUCKS", model: "HOWO" },
{ make: "DUMP TRUCKS", model: "IVECO" },
{ make: "DUMP TRUCKS", model: "KAISER" },
{ make: "DUMP TRUCKS", model: "MAN" },
{ make: "DUMP TRUCKS", model: "MARMON" },
{ make: "DUMP TRUCKS", model: "MERCEDES-BENZ" },
{ make: "DUMP TRUCKS", model: "MITSUBISHI" },
{ make: "DUMP TRUCKS", model: "OSHKOSH" },
{ make: "DUMP TRUCKS", model: "RAM" },
{ make: "DUMP TRUCKS", model: "RIZON" },
{ make: "DUMP TRUCKS", model: "SAIC IVECO HONGYAN" },
{ make: "DUMP TRUCKS", model: "SCANIA" },
{ make: "DUMP TRUCKS", model: "SHACMAN" },
{ make: "DUMP TRUCKS", model: "SINOTRUK" },
{ make: "DUMP TRUCKS", model: "STERLING" },
{ make: "DUMP TRUCKS", model: "UD" },
{ make: "DUMP TRUCKS", model: "WHITE" },
{ make: "DUMP TRUCKS", model: "WHITE/GMC" },
{ make: "DUMP TRUCKS", model: "XCMG" },
{ make: "DUMP TRUCKS", model: "OTHER" },

 // EXPEDITOR TRUCKS

{ make: "EXPEDITOR TRUCKS", model: "FREIGHTLINER" },
{ make: "EXPEDITOR TRUCKS", model: "HINO" },
{ make: "EXPEDITOR TRUCKS", model: "KENWORTH" },
{ make: "EXPEDITOR TRUCKS", model: "PETERBILT" },
{ make: "EXPEDITOR TRUCKS", model: "VOLVO" },
{ make: "EXPEDITOR TRUCKS", model: "WESTERN STAR" },
{ make: "EXPEDITOR TRUCKS", model: "OTHER" },

 // FARM TRUCKS / GRAIN TRUCK S

{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "INTERNATIONAL" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "FREIGHTLINER" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "FORD" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "KENWORTH" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "CHEVROLET" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "PETERBILT" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "MACK" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "GMC" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "UNSPECIFIED" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "STRELING" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "AUTOCAR" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "DIAMOND REO" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "DODGE" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "FEDERAL" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "REO" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "STERLING" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "VOLVO" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "WESTERN STAR" },
{ make: "FARM TRUCKS / GRAIN TRUCK S", model: "OTHER" },

 // FIRE TRUCKS

{ make: "FIRE TRUCKS", model: "INTERNATIONAL" },
{ make: "FIRE TRUCKS", model: "FREIGHTLINER" },
{ make: "FIRE TRUCKS", model: "FORD" },
{ make: "FIRE TRUCKS", model: "E-ONE" },
{ make: "FIRE TRUCKS", model: "PIERCE" },
{ make: "FIRE TRUCKS", model: "OSHKOSH" },
{ make: "FIRE TRUCKS", model: "SPARTAN" },
{ make: "FIRE TRUCKS", model: "AMERICAN LAFRANCE" },
{ make: "FIRE TRUCKS", model: "GMC" },
{ make: "FIRE TRUCKS", model: "KME" },
{ make: "FIRE TRUCKS", model: "AMERTEK" },
{ make: "FIRE TRUCKS", model: "CHEVROLET" },
{ make: "FIRE TRUCKS", model: "CROWN" },
{ make: "FIRE TRUCKS", model: "DODGE" },
{ make: "FIRE TRUCKS", model: "DUPLEX" },
{ make: "FIRE TRUCKS", model: "FERRARA" },
{ make: "FIRE TRUCKS", model: "GRUMMAN" },
{ make: "FIRE TRUCKS", model: "HME" },
{ make: "FIRE TRUCKS", model: "KME" },
{ make: "FIRE TRUCKS", model: "MACK" },
{ make: "FIRE TRUCKS", model: "MERCEDES-BENZ" },
{ make: "FIRE TRUCKS", model: "PETERBILT" },
{ make: "FIRE TRUCKS", model: "ROSENBAUER" },
{ make: "FIRE TRUCKS", model: "SEAGRAVE" },
{ make: "FIRE TRUCKS", model: "SIMON" },
{ make: "FIRE TRUCKS", model: "SUTPHEN" },
{ make: "FIRE TRUCKS", model: "TOYOTA" },
{ make: "FIRE TRUCKS", model: "OTHER" },

  // FLATBED TRUCKS

{ make: "FLATBED TRUCKS", model: "FREIGHTLINER" },
{ make: "FLATBED TRUCKS", model: "FORD" },
{ make: "FLATBED TRUCKS", model: "INTERNATIONAL" },
{ make: "FLATBED TRUCKS", model: "CHEVROLET" },
{ make: "FLATBED TRUCKS", model: "RAM" },
{ make: "FLATBED TRUCKS", model: "PETERBILT" },
{ make: "FLATBED TRUCKS", model: "ISUZU" },
{ make: "FLATBED TRUCKS", model: "KENWORTH" },
{ make: "FLATBED TRUCKS", model: "HINO" },
{ make: "FLATBED TRUCKS", model: "STRELING" },
{ make: "FLATBED TRUCKS", model: "AM GENERAL" },
{ make: "FLATBED TRUCKS", model: "AUTOCAR" },
{ make: "FLATBED TRUCKS", model: "BOLLINGER" },
{ make: "FLATBED TRUCKS", model: "CHANGAN" },
{ make: "FLATBED TRUCKS", model: "DIAMOND REO" },
{ make: "FLATBED TRUCKS", model: "DODGE" },
{ make: "FLATBED TRUCKS", model: "FABCO" },
{ make: "FLATBED TRUCKS", model: "MACK" },
{ make: "FLATBED TRUCKS", model: "MITSUBISHI" },
{ make: "FLATBED TRUCKS", model: "MULLEN" },
{ make: "FLATBED TRUCKS", model: "NISSAN" },
{ make: "FLATBED TRUCKS", model: "STEWART - STEVENSON" },
{ make: "FLATBED TRUCKS", model: "STUDABAKER" },
{ make: "FLATBED TRUCKS", model: "UD" },
{ make: "FLATBED TRUCKS", model: "VOLVO" },
{ make: "FLATBED TRUCKS", model: "WESTERN STAR" },
{ make: "FLATBED TRUCKS", model: "WHITE" },
{ make: "FLATBED TRUCKS", model: "WHITE/GMC" },
{ make: "FLATBED TRUCKS", model: "WORKHORSE" },
{ make: "FLATBED TRUCKS", model: "OTHER" },

  // FLATBED-DUMP TRUCKS

{ make: "FLATBED-DUMP TRUCKS", model: "CHEVROLET" },
{ make: "FLATBED-DUMP TRUCKS", model: "FORD" },
{ make: "FLATBED-DUMP TRUCKS", model: "FREIGHTLINER" },
{ make: "FLATBED-DUMP TRUCKS", model: "GMC" },
{ make: "FLATBED-DUMP TRUCKS", model: "HINO" },
{ make: "FLATBED-DUMP TRUCKS", model: "INTERNATIONAL" },
{ make: "FLATBED-DUMP TRUCKS", model: "ISUZU" },
{ make: "FLATBED-DUMP TRUCKS", model: "KENWORTH" },
{ make: "FLATBED-DUMP TRUCKS", model: "MACK" },
{ make: "FLATBED-DUMP TRUCKS", model: "PETERBILT" },
{ make: "FLATBED-DUMP TRUCKS", model: "RAM STERLING" },
{ make: "FLATBED-DUMP TRUCKS", model: "WESTERN STAR" },
{ make: "FLATBED-DUMP TRUCKS", model: "OTHER" },

 // FORESTRY BUCKET TRUCKS

{ make: "FORESTRY BUCKET TRUCKS", model: "CHEVROLET" },
{ make: "FORESTRY BUCKET TRUCKS", model: "DODGE" },
{ make: "FORESTRY BUCKET TRUCKS", model: "FORD" },
{ make: "FORESTRY BUCKET TRUCKS", model: "FREIGHTLINER" },
{ make: "FORESTRY BUCKET TRUCKS", model: "GMC" },
{ make: "FORESTRY BUCKET TRUCKS", model: "INTERNATIONAL" },
{ make: "FORESTRY BUCKET TRUCKS", model: "KENWORTH" },
{ make: "FORESTRY BUCKET TRUCKS", model: "PETERBILT" },
{ make: "FORESTRY BUCKET TRUCKS", model: "RAM STERLING" },
{ make: "FORESTRY BUCKET TRUCKS", model: "VOLVO" },
{ make: "FORESTRY BUCKET TRUCKS", model: "WESTERN STAR" },
{ make: "FORESTRY BUCKET TRUCKS", model: "OTHER" },

  // FUEL & LUBE TRUCKS

{ make: "FUEL & LUBE TRUCKS", model: "PETERBILT" },
{ make: "FUEL & LUBE TRUCKS", model: "KENWORTH" },
{ make: "FUEL & LUBE TRUCKS", model: "INTERNATIONAL" },
{ make: "FUEL & LUBE TRUCKS", model: "FREIGHTLINER" },
{ make: "FUEL & LUBE TRUCKS", model: "FORD" },
{ make: "FUEL & LUBE TRUCKS", model: "MACK" },
{ make: "FUEL & LUBE TRUCKS", model: "WESTERN STAR" },
{ make: "FUEL & LUBE TRUCKS", model: "CHEVROLET" },
{ make: "FUEL & LUBE TRUCKS", model: "STERLING" },
{ make: "FUEL & LUBE TRUCKS", model: "GMC" },
{ make: "FUEL & LUBE TRUCKS", model: "AM GENERAL" },
{ make: "FUEL & LUBE TRUCKS", model: "CARCO INDUSTRIES" },
{ make: "FUEL & LUBE TRUCKS", model: "EAM" },
{ make: "FUEL & LUBE TRUCKS", model: "HOWO" },
{ make: "FUEL & LUBE TRUCKS", model: "ISUZU" },
{ make: "FUEL & LUBE TRUCKS", model: "OSHKOSH" },
{ make: "FUEL & LUBE TRUCKS", model: "RAM" },
{ make: "FUEL & LUBE TRUCKS", model: "VOLKSWAGON" },
{ make: "FUEL & LUBE TRUCKS", model: "VOLVO" },
{ make: "FUEL & LUBE TRUCKS", model: "OTHER" },

  // GARBAGE TRUCKS

{ make: "GARBAGE TRUCKS", model: "MACK" },
{ make: "GARBAGE TRUCKS", model: "PETERBILT" },
{ make: "GARBAGE TRUCKS", model: "KENWORTH" },
{ make: "GARBAGE TRUCKS", model: "FREIGHTLINER" },
{ make: "GARBAGE TRUCKS", model: "INTERNATIONAL" },
{ make: "GARBAGE TRUCKS", model: "AUTOCAR" },
{ make: "GARBAGE TRUCKS", model: "WESTERN STAR" },
{ make: "GARBAGE TRUCKS", model: "VOLVO" },
{ make: "GARBAGE TRUCKS", model: "ISUZU" },
{ make: "GARBAGE TRUCKS", model: "CCC" },
{ make: "GARBAGE TRUCKS", model: "AMERICAN LAFRANCE" },
{ make: "GARBAGE TRUCKS", model: "BATTLE MOTORS" },
{ make: "GARBAGE TRUCKS", model: "CATREPILLAR" },
{ make: "GARBAGE TRUCKS", model: "DENNIS EAGLE" },
{ make: "GARBAGE TRUCKS", model: "FORD" },
{ make: "GARBAGE TRUCKS", model: "GMC" },
{ make: "GARBAGE TRUCKS", model: "HINO" },
{ make: "GARBAGE TRUCKS", model: "ISUZU" },
{ make: "GARBAGE TRUCKS", model: "LODA" },
{ make: "GARBAGE TRUCKS", model: "MITSUBISHI FUSO" },
{ make: "GARBAGE TRUCKS", model: "OSHKOSH" },
{ make: "GARBAGE TRUCKS", model: "RAM" },
{ make: "GARBAGE TRUCKS", model: "RIZON" },
{ make: "GARBAGE TRUCKS", model: "STERLING" },
{ make: "GARBAGE TRUCKS", model: "WHITE" },
{ make: "GARBAGE TRUCKS", model: "OTHER" },

  // GRAPPLE TRUCKS

{ make: "GRAPPLE TRUCKS", model: "FREIGHTLINER" },
{ make: "GRAPPLE TRUCKS", model: "INTERNATIONAL" },
{ make: "GRAPPLE TRUCKS", model: "MACK" },
{ make: "GRAPPLE TRUCKS", model: "KENWORTH" },
{ make: "GRAPPLE TRUCKS", model: "PETERBILT" },
{ make: "GRAPPLE TRUCKS", model: "WESTERN STAR" },
{ make: "GRAPPLE TRUCKS", model: "STERLING" },
{ make: "GRAPPLE TRUCKS", model: "FORD" },
{ make: "GRAPPLE TRUCKS", model: "HINO" },
{ make: "GRAPPLE TRUCKS", model: "VOLVO" },
{ make: "GRAPPLE TRUCKS", model: "BATTLE MOTORS" },
{ make: "GRAPPLE TRUCKS", model: "CATERPILLAR" },
{ make: "GRAPPLE TRUCKS", model: "CHEVROLET" },
{ make: "GRAPPLE TRUCKS", model: "GMC" },
{ make: "GRAPPLE TRUCKS", model: "OTHER" },

  // HOOKLIFT TRUCKS

{ make: "HOOKLIFT TRUCKS", model: "KENWORTH" },
{ make: "HOOKLIFT TRUCKS", model: "FREIGHTLINER" },
{ make: "HOOKLIFT TRUCKS", model: "INTERNATIONAL" },
{ make: "HOOKLIFT TRUCKS", model: "PETERBILT" },
{ make: "HOOKLIFT TRUCKS", model: "FORD" },
{ make: "HOOKLIFT TRUCKS", model: "MACK" },
{ make: "HOOKLIFT TRUCKS", model: "ISUZU" },
{ make: "HOOKLIFT TRUCKS", model: "HINO" },
{ make: "HOOKLIFT TRUCKS", model: "CHEVROLET" },
{ make: "HOOKLIFT TRUCKS", model: "RAM" },
{ make: "HOOKLIFT TRUCKS", model: "AUTOCAR" },
{ make: "HOOKLIFT TRUCKS", model: "SCANIA" },
{ make: "HOOKLIFT TRUCKS", model: "STERLING" },
{ make: "HOOKLIFT TRUCKS", model: "WESTERN STAR" },
{ make: "HOOKLIFT TRUCKS", model: "OTHER" },

// HOT SHOT TRUCKS

{ make: "HOT SHOT TRUCKS", model: "CHEVROLET" },
{ make: "HOT SHOT TRUCKS", model: "FORD" },
{ make: "HOT SHOT TRUCKS", model: "FREIGHTLINER" },
{ make: "HOT SHOT TRUCKS", model: "GMC" },
{ make: "HOT SHOT TRUCKS", model: "INTERNATIONAL" },
{ make: "HOT SHOT TRUCKS", model: "PETERBILT" },
{ make: "HOT SHOT TRUCKS", model: "RAM" },
{ make: "HOT SHOT TRUCKS", model: "OTHER" },

 // KNUCKLE BOOM CRANE TRUCK S

{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "FASSI" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "HIAB" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "PALFINGER" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "CORMACH" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "PM" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "IMT" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "DALL'AGLIO NEWCRANES" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "BIK" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "EFFER" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "COPMA" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "AMCO VEBA" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "ATLAS" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "AUTOCRANE" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "AXIONLIFT" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "BIK" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "CASCADE" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "CANAB" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "FEC" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "FERRARI" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "HEILA" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "HMF" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "HYVA" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "ING BONFIGLIOLI" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "KENNIS" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "KLAAS" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "MAGNUM" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "MANITEX" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "MARCHESI" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "MAXILIFT" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "MKG" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "NATIONAL" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "PENZ" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "PESCI" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "PRECISIION HUSKY" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "PRENTICE" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "STELLAR" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "TEREX" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "TICO" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "TOIMIL" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "UNSPECIFIED" },
{ make: "KNUCKLE BOOM CRANE TRUCK S", model: "OTHER" }, 

// LANDSCAPE TRUCKS

{ make: "LANDSCAPE TRUCKS", model: "BOLLINGER" },
{ make: "LANDSCAPE TRUCKS", model: "CHEVROLET" },
{ make: "LANDSCAPE TRUCKS", model: "FORD" },
{ make: "LANDSCAPE TRUCKS", model: "FREIGHTLINER" },
{ make: "LANDSCAPE TRUCKS", model: "GMC" },
{ make: "LANDSCAPE TRUCKS", model: "HINO" },
{ make: "LANDSCAPE TRUCKS", model: "INTERNATIONAL" },
{ make: "LANDSCAPE TRUCKS", model: "ISUZU" },
{ make: "LANDSCAPE TRUCKS", model: "MITSUBISHI FUSO" },
{ make: "LANDSCAPE TRUCKS", model: "PETERBILT" },
{ make: "LANDSCAPE TRUCKS", model: "RAM" },
{ make: "LANDSCAPE TRUCKS", model: "RIZON" },
{ make: "LANDSCAPE TRUCKS", model: "UD" },
{ make: "LANDSCAPE TRUCKS", model: "OTHER" },

// LOGGING TRUCKS

{ make: "LOGGING TRUCKS", model: "FORD" },
{ make: "LOGGING TRUCKS", model: "FREIGHTLINER" },
{ make: "LOGGING TRUCKS", model: "GMC" },
{ make: "LOGGING TRUCKS", model: "INTERNATIONAL" },
{ make: "LOGGING TRUCKS", model: "KENWORTH" },
{ make: "LOGGING TRUCKS", model: "MACK" },
{ make: "LOGGING TRUCKS", model: "PETERBILT" },
{ make: "LOGGING TRUCKS", model: "STERLING" },
{ make: "LOGGING TRUCKS", model: "VOLVO" },
{ make: "LOGGING TRUCKS", model: "WESTERN STAR" },
{ make: "LOGGING TRUCKS", model: "WHITE/GMC" },
{ make: "LOGGING TRUCKS", model: "OTHER" },

 // MISCELLANEOUS TRUCKS

{ make: "MISCELLANEOUS TRUCKS", model: "FORD" },
{ make: "MISCELLANEOUS TRUCKS", model: "FREIGHTLINER" },
{ make: "MISCELLANEOUS TRUCKS", model: "INTERNATIONAL" },
{ make: "MISCELLANEOUS TRUCKS", model: "KENWORTH" },
{ make: "MISCELLANEOUS TRUCKS", model: "AM GENERAL" },
{ make: "MISCELLANEOUS TRUCKS", model: "ISUZU" },
{ make: "MISCELLANEOUS TRUCKS", model: "CHEVROLET" },
{ make: "MISCELLANEOUS TRUCKS", model: "PETERBILT" },
{ make: "MISCELLANEOUS TRUCKS", model: "GMC" },
{ make: "MISCELLANEOUS TRUCKS", model: "MERCEDES-BENZ" },
{ make: "MISCELLANEOUS TRUCKS", model: "AUTOCAR" },
{ make: "MISCELLANEOUS TRUCKS", model: "BMY" },
{ make: "MISCELLANEOUS TRUCKS", model: "DODGE" },
{ make: "MISCELLANEOUS TRUCKS", model: "HINO" },
{ make: "MISCELLANEOUS TRUCKS", model: "KES EQUIPMENT INC" },
{ make: "MISCELLANEOUS TRUCKS", model: "MACK" },
{ make: "MISCELLANEOUS TRUCKS", model: "MITSUBISHI FUSO" },
{ make: "MISCELLANEOUS TRUCKS", model: "OSHKOSH" },
{ make: "MISCELLANEOUS TRUCKS", model: "PREVOST" },
{ make: "MISCELLANEOUS TRUCKS", model: "RAM" },
{ make: "MISCELLANEOUS TRUCKS", model: "RENAULT" },
{ make: "MISCELLANEOUS TRUCKS", model: "SPARTAN" },
{ make: "MISCELLANEOUS TRUCKS", model: "STERLING" },
{ make: "MISCELLANEOUS TRUCKS", model: "TOYOTA" },
{ make: "MISCELLANEOUS TRUCKS", model: "VOLVO" },
{ make: "MISCELLANEOUS TRUCKS", model: "WESTERN STAR" },
{ make: "MISCELLANEOUS TRUCKS", model: "WHITE" },
{ make: "MISCELLANEOUS TRUCKS", model: "XCMG" },
{ make: "MISCELLANEOUS TRUCKS", model: "OTHER" },

// MIXER TRUCKS

{ make: "MIXER TRUCKS", model: "MACK" },
{ make: "MIXER TRUCKS", model: "KENWORTH" },
{ make: "MIXER TRUCKS", model: "PETERBILT" },
{ make: "MIXER TRUCKS", model: "INTERNATIONAL" },
{ make: "MIXER TRUCKS", model: "FREIGHTLINER" },
{ make: "MIXER TRUCKS", model: "VOLVO" },
{ make: "MIXER TRUCKS", model: "TEREX" },
{ make: "MIXER TRUCKS", model: "OSHKOSH" },
{ make: "MIXER TRUCKS", model: "WESTERN STAR" },
{ make: "MIXER TRUCKS", model: "STERLING" },
{ make: "MIXER TRUCKS", model: "ADVANCE" },
{ make: "MIXER TRUCKS", model: "AMERICAN LAFRANCE" },
{ make: "MIXER TRUCKS", model: "AUTOCAR" },
{ make: "MIXER TRUCKS", model: "CATERPILLAR" },
{ make: "MIXER TRUCKS", model: "CHEVROLET" },
{ make: "MIXER TRUCKS", model: "FORD" },
{ make: "MIXER TRUCKS", model: "GMC" },
{ make: "MIXER TRUCKS", model: "HOWO" },
{ make: "MIXER TRUCKS", model: "INDIANA PHOENIX" },
{ make: "MIXER TRUCKS", model: "SINOTRUK" },
{ make: "MIXER TRUCKS", model: "STERLING" },
{ make: "MIXER TRUCKS", model: "TEREX" },
{ make: "MIXER TRUCKS", model: "UD" },
{ make: "MIXER TRUCKS", model: "XCMG" },
{ make: "MIXER TRUCKS", model: "OTHER" },
{ make: "MIXER TRUCKS", model: "OTHER" },

 // PASSENGER BUS

{ make: "PASSENGER BUS", model: "IC BUS" },
{ make: "PASSENGER BUS", model: "BLUEBIRD" },
{ make: "PASSENGER BUS", model: "INTERNATIONAL" },
{ make: "PASSENGER BUS", model: "UNSPECIFIED" },
{ make: "PASSENGER BUS", model: "FREIGHTLINER" },
{ make: "PASSENGER BUS", model: "THOMAS BUILT BUSES" },
{ make: "PASSENGER BUS", model: "MCI" },
{ make: "PASSENGER BUS", model: "GRANDE WEST" },
{ make: "PASSENGER BUS", model: "PREVOST" },
{ make: "PASSENGER BUS", model: "SPARTAN" },
{ make: "PASSENGER BUS", model: "CAIO" },
{ make: "PASSENGER BUS", model: "EAGLE" },
{ make: "PASSENGER BUS", model: "GILLIG" },
{ make: "PASSENGER BUS", model: "LION" },
{ make: "PASSENGER BUS", model: "TEMSA" },
{ make: "PASSENGER BUS", model: "VOLVO" },
{ make: "PASSENGER BUS", model: "OTHER" }, 

 // PICKUP TRUCKS

{ make: "PICKUP TRUCKS", model: "FORD" },
{ make: "PICKUP TRUCKS", model: "CHEVROLET" },
{ make: "PICKUP TRUCKS", model: "RAM" },
{ make: "PICKUP TRUCKS", model: "GMC" },
{ make: "PICKUP TRUCKS", model: "DODGE" },
{ make: "PICKUP TRUCKS", model: "UNSPECIFIED" },
{ make: "PICKUP TRUCKS", model: "TOYOTA" },
{ make: "PICKUP TRUCKS", model: "NISSAN" },
{ make: "PICKUP TRUCKS", model: "JEEP" },
{ make: "PICKUP TRUCKS", model: "INTERNATIONAL" },
{ make: "PICKUP TRUCKS", model: "HONDA" },
{ make: "PICKUP TRUCKS", model: "ISUZU" },
{ make: "PICKUP TRUCKS", model: "STERLING" },
{ make: "PICKUP TRUCKS", model: "TESLA" },
{ make: "PICKUP TRUCKS", model: "OTHER" }, 

// PLOW / SPREADER TRUCKS

{ make: "PLOW / SPREADER TRUCKS", model: "INTERNATIONAL" },
{ make: "PLOW / SPREADER TRUCKS", model: "FREIGHTLINER" },
{ make: "PLOW / SPREADER TRUCKS", model: "FORD" },
{ make: "PLOW / SPREADER TRUCKS", model: "STERLING" },
{ make: "PLOW / SPREADER TRUCKS", model: "MACK" },
{ make: "PLOW / SPREADER TRUCKS", model: "WESTERN STAR" },
{ make: "PLOW / SPREADER TRUCKS", model: "CHEVROLET" },
{ make: "PLOW / SPREADER TRUCKS", model: "KENWORTH" },
{ make: "PLOW / SPREADER TRUCKS", model: "PETERBILT" },
{ make: "PLOW / SPREADER TRUCKS", model: "GMC" },
{ make: "PLOW / SPREADER TRUCKS", model: "DODGE" },
{ make: "PLOW / SPREADER TRUCKS", model: "OSHKOSH" },
{ make: "PLOW / SPREADER TRUCKS", model: "RAM" },
{ make: "PLOW / SPREADER TRUCKS", model: "MERCEDES-BENZ" },
{ make: "PLOW / SPREADER TRUCKS", model: "VOLVO" },
{ make: "PLOW / SPREADER TRUCKS", model: "WALTER" },
{ make: "PLOW / SPREADER TRUCKS", model: "OTHER" },

  // RECYCLING TRUCKS

{ make: "RECYCLING TRUCKS", model: "AUTOCAR" },
{ make: "RECYCLING TRUCKS", model: "BATTLE MOTORS" },
{ make: "RECYCLING TRUCKS", model: "FORD" },
{ make: "RECYCLING TRUCKS", model: "FREIGHTLINER" },
{ make: "RECYCLING TRUCKS", model: "INTERNATIONAL" },
{ make: "RECYCLING TRUCKS", model: "MACK" },
{ make: "RECYCLING TRUCKS", model: "PETERBILT" },
{ make: "RECYCLING TRUCKS", model: "STERLING" },
{ make: "RECYCLING TRUCKS", model: "VOLVO" },
{ make: "RECYCLING TRUCKS", model: "OTHER" },

// RV HAULER / TOTER TRUCKS

{ make: "RV HAULER / TOTER TRUCKS", model: "CHEVROLET" },
{ make: "RV HAULER / TOTER TRUCKS", model: "FORD" },
{ make: "RV HAULER / TOTER TRUCKS", model: "FREIGHTLINER" },
{ make: "RV HAULER / TOTER TRUCKS", model: "GMC" },
{ make: "RV HAULER / TOTER TRUCKS", model: "INTERNATIONAL" },
{ make: "RV HAULER / TOTER TRUCKS", model: "KENWORTH" },
{ make: "RV HAULER / TOTER TRUCKS", model: "MACK" },
{ make: "RV HAULER / TOTER TRUCKS", model: "PETERBILT" },
{ make: "RV HAULER / TOTER TRUCKS", model: "RAM" },
{ make: "RV HAULER / TOTER TRUCKS", model: "OTHER" },

  // SERVICE TRUCKS / UTILITY / MECHANIC

{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "FORD" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "RAM" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "CHEVROLET" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "INTERNATIONAL" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "FREIGHTLINER" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "PETERBILT" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "KENWORTH" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "GMC" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "MACK" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "DODGE" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "HINO" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "ISUZU" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "MERCEDES-BENZ" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "MITSUBISHI FUSO" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "MULLEN" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "RIZON" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "STERLING" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "TOYOTA" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "UNSPECIFIED" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "VOLVO" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "WESTERN STAR" },
{ make: "SERVICE TRUCKS / UTILITY / MECHANIC", model: "OTHER" },

  // SHUTTLE BUS

{ make: "SHUTTLE BUS", model: "CHEVROLET" },
{ make: "SHUTTLE BUS", model: "FORD" },
{ make: "SHUTTLE BUS", model: "FREIGHTLINER" },
{ make: "SHUTTLE BUS", model: "GLAVAL" },
{ make: "SHUTTLE BUS", model: "GMC" },
{ make: "SHUTTLE BUS", model: "GREEN POWER" },
{ make: "SHUTTLE BUS", model: "IC BUS" },
{ make: "SHUTTLE BUS", model: "INTERNATIONAL" },
{ make: "SHUTTLE BUS", model: "MICRO BIRD" },
{ make: "SHUTTLE BUS", model: "STARTRANS BUS" },
{ make: "SHUTTLE BUS", model: "OTHER" },

  // SLEEPER TRUCKS

{ make: "SLEEPER TRUCKS", model: "FREIGHTLINER" },
{ make: "SLEEPER TRUCKS", model: "PETERBILT" },
{ make: "SLEEPER TRUCKS", model: "KENWORTH" },
{ make: "SLEEPER TRUCKS", model: "VOLVO" },
{ make: "SLEEPER TRUCKS", model: "INTERNATIONAL" },
{ make: "SLEEPER TRUCKS", model: "MACK" },
{ make: "SLEEPER TRUCKS", model: "WESTERN STAR" },
{ make: "SLEEPER TRUCKS", model: "UNSPECIFIED" },
{ make: "SLEEPER TRUCKS", model: "WHITE/GMC" },
{ make: "SLEEPER TRUCKS", model: "DAF" },
{ make: "SLEEPER TRUCKS", model: "AUTOCAR" },
{ make: "SLEEPER TRUCKS", model: "CHEVROLET" },
{ make: "SLEEPER TRUCKS", model: "FORD" },
{ make: "SLEEPER TRUCKS", model: "GMC" },
{ make: "SLEEPER TRUCKS", model: "HINO" },
{ make: "SLEEPER TRUCKS", model: "IVECO" },
{ make: "SLEEPER TRUCKS", model: "MERCEDES-BENZ" },
{ make: "SLEEPER TRUCKS", model: "NIKOLA" },
{ make: "SLEEPER TRUCKS", model: "RENAULT" },
{ make: "SLEEPER TRUCKS", model: "SCANIA" },
{ make: "SLEEPER TRUCKS", model: "SHACMAN" },
{ make: "SLEEPER TRUCKS", model: "SINOTRUK" },
{ make: "SLEEPER TRUCKS", model: "STERLING" },
{ make: "SLEEPER TRUCKS", model: "WHITE/GMC" },
{ make: "SLEEPER TRUCKS", model: "XCMG" },
{ make: "SLEEPER TRUCKS", model: "OTHER" },

  // STAKE BED TRUCKS

{ make: "STAKE BED TRUCKS", model: "FORD" },
{ make: "STAKE BED TRUCKS", model: "INTERNATIONAL" },
{ make: "STAKE BED TRUCKS", model: "RAM" },
{ make: "STAKE BED TRUCKS", model: "FREIGHTLINER" },
{ make: "STAKE BED TRUCKS", model: "ISUZU" },
{ make: "STAKE BED TRUCKS", model: "HINO" },
{ make: "STAKE BED TRUCKS", model: "CHEVROLET" },
{ make: "STAKE BED TRUCKS", model: "PETERBILT" },
{ make: "STAKE BED TRUCKS", model: "MACK" },
{ make: "STAKE BED TRUCKS", model: "KENWORTH" },
{ make: "STAKE BED TRUCKS", model: "BOLLINGER" },
{ make: "STAKE BED TRUCKS", model: "DODGE" },
{ make: "STAKE BED TRUCKS", model: "GMC" },
{ make: "STAKE BED TRUCKS", model: "LION" },
{ make: "STAKE BED TRUCKS", model: "RIZON" },
{ make: "STAKE BED TRUCKS", model: "STERLING" },
{ make: "STAKE BED TRUCKS", model: "VOLVO" },
{ make: "STAKE BED TRUCKS", model: "OTHER" },

  // STONE SLINGER TRUCKS

{ make: "STONE SLINGER TRUCKS", model: "FREIGHTLINER" },
{ make: "STONE SLINGER TRUCKS", model: "INTERNATIONAL" },
{ make: "STONE SLINGER TRUCKS", model: "KENWORTH" },
{ make: "STONE SLINGER TRUCKS", model: "MACK" },
{ make: "STONE SLINGER TRUCKS", model: "PETERBILT" },
{ make: "STONE SLINGER TRUCKS", model: "STERLING" },
{ make: "STONE SLINGER TRUCKS", model: "VOLVO" },
{ make: "STONE SLINGER TRUCKS", model: "WESTERN STAR" },
{ make: "STONE SLINGER TRUCKS", model: "OTHER" },

  // TANK TRUCKS

{ make: "TANK TRUCKS", model: "FREIGHTLINER" },
{ make: "TANK TRUCKS", model: "INTERNATIONAL" },
{ make: "TANK TRUCKS", model: "PETERBILT" },
{ make: "TANK TRUCKS", model: "KENWORTH" },
{ make: "TANK TRUCKS", model: "FORD" },
{ make: "TANK TRUCKS", model: "MACK" },
{ make: "TANK TRUCKS", model: "WESTERN STAR" },
{ make: "TANK TRUCKS", model: "STERLING" },
{ make: "TANK TRUCKS", model: "HINO" },
{ make: "TANK TRUCKS", model: "VOLVO" },
{ make: "TANK TRUCKS", model: "AM GENERAL" },
{ make: "TANK TRUCKS", model: "AMERICAN LAFRANCE" },
{ make: "TANK TRUCKS", model: "AUTOCAR" },
{ make: "TANK TRUCKS", model: "BMY" },
{ make: "TANK TRUCKS", model: "CATERPILLAR" },
{ make: "TANK TRUCKS", model: "CHEVROLET" },
{ make: "TANK TRUCKS", model: "GMC" },
{ make: "TANK TRUCKS", model: "ISUZU" },
{ make: "TANK TRUCKS", model: "MAN" },
{ make: "TANK TRUCKS", model: "OSHKOSH" },
{ make: "TANK TRUCKS", model: "RAM" },
{ make: "TANK TRUCKS", model: "SINOTRUK" },
{ make: "TANK TRUCKS", model: "WHITE/GMC" },
{ make: "TANK TRUCKS", model: "OTHER" },

  // TOW TRUCKS

{ make: "TOW TRUCKS", model: "INTERNATIONAL" },
{ make: "TOW TRUCKS", model: "RAM" },
{ make: "TOW TRUCKS", model: "PETERBILT" },
{ make: "TOW TRUCKS", model: "FREIGHTLINER" },
{ make: "TOW TRUCKS", model: "FORD" },
{ make: "TOW TRUCKS", model: "KENWORTH" },
{ make: "TOW TRUCKS", model: "HINO" },
{ make: "TOW TRUCKS", model: "MACK" },
{ make: "TOW TRUCKS", model: "CHEVROLET" },
{ make: "TOW TRUCKS", model: "ISUZU" },
{ make: "TOW TRUCKS", model: "AM GENERAL" },
{ make: "TOW TRUCKS", model: "AUTOCAR" },
{ make: "TOW TRUCKS", model: "BMY" },
{ make: "TOW TRUCKS", model: "CATERPILLAR" },
{ make: "TOW TRUCKS", model: "DODGE" },
{ make: "TOW TRUCKS", model: "GMC" },
{ make: "TOW TRUCKS", model: "HENDRICKSON" },
{ make: "TOW TRUCKS", model: "ISUZU" },
{ make: "TOW TRUCKS", model: "STERLING" },
{ make: "TOW TRUCKS", model: "UD" },
{ make: "TOW TRUCKS", model: "UNSPECIFIED" },
{ make: "TOW TRUCKS", model: "VOLVO" },
{ make: "TOW TRUCKS", model: "WESTERN STAR" },
{ make: "TOW TRUCKS", model: "WHITE/GMC" },
{ make: "TOW TRUCKS", model: "OTHER" },

// TRUCK BODIES

{ make: "TRUCK BODIES", model: "MORGAN" },
{ make: "TRUCK BODIES", model: "NORSTAR" },
{ make: "TRUCK BODIES", model: "BEDROCK" },
{ make: "TRUCK BODIES", model: "EBY" },
{ make: "TRUCK BODIES", model: "SWAPLOADER" },
{ make: "TRUCK BODIES", model: "CM" },
{ make: "TRUCK BODIES", model: "HILLSBORO" },
{ make: "TRUCK BODIES", model: "SUPER PRODUCTS" },
{ make: "TRUCK BODIES", model: "CRYSTEEL" },
{ make: "TRUCK BODIES", model: "RUGBY" },
{ make: "TRUCK BODIES", model: "A.M. HAIRE" },
{ make: "TRUCK BODIES", model: "ADVANCE FAB" },
{ make: "TRUCK BODIES", model: "AGASSIZ" },
{ make: "TRUCK BODIES", model: "ALFAB" },
{ make: "TRUCK BODIES", model: "ALFRED" },
{ make: "TRUCK BODIES", model: "ALMAC" },
{ make: "TRUCK BODIES", model: "ALUMA" },
{ make: "TRUCK BODIES", model: "ALUM-LINE" },
{ make: "TRUCK BODIES", model: "ALVAN" },
{ make: "TRUCK BODIES", model: "AMERICAN BODY WORKS" },
{ make: "TRUCK BODIES", model: "AMERICAN EAGLE" },
{ make: "TRUCK BODIES", model: "AMERICAN ROLL-OFF" },
{ make: "TRUCK BODIES", model: "AMERICAN TRUCK AND TRAILER" },
{ make: "TRUCK BODIES", model: "AMH" },
{ make: "TRUCK BODIES", model: "AM-TANKS" },
{ make: "TRUCK BODIES", model: "ARBORTECHS" },
{ make: "TRUCK BODIES", model: "ARE" },
{ make: "TRUCK BODIES", model: "ARNES" },
{ make: "TRUCK BODIES", model: "AULICK IND" },
{ make: "TRUCK BODIES", model: "AUTO CRANE" },
{ make: "TRUCK BODIES", model: "BEALL" },
{ make: "TRUCK BODIES", model: "BEAU-ROC" },
{ make: "TRUCK BODIES", model: "BEDROCK" },
{ make: "TRUCK BODIES", model: "BENLEE" },
{ make: "TRUCK BODIES", model: "BENSON" },
{ make: "TRUCK BODIES", model: "BESLER" },
{ make: "TRUCK BODIES", model: "NBIANCHI" },
{ make: "TRUCK BODIES", model: "BIBEAU" },
{ make: "TRUCK BODIES", model: "BOMAX" },
{ make: "TRUCK BODIES", model: "BOSS" },
{ make: "TRUCK BODIES", model: "BOSTON STEEL" },
{ make: "TRUCK BODIES", model: "BRADFORD BUILT" },
{ make: "TRUCK BODIES", model: "BRAMCO" },
{ make: "TRUCK BODIES", model: "BRAND FX" },
{ make: "TRUCK BODIES", model: "BRANDON" },
{ make: "TRUCK BODIES", model: "BRAZOS" },
{ make: "TRUCK BODIES", model: "BRENNER" },
{ make: "TRUCK BODIES", model: "BROWN" },
{ make: "TRUCK BODIES", model: "BROWN INDUSTRIIES" },
{ make: "TRUCK BODIES", model: "BUCKS FAB" },
{ make: "TRUCK BODIES", model: "BULLDOG BODIES" },
{ make: "TRUCK BODIES", model: "BUTLER BEDS" },
{ make: "TRUCK BODIES", model: "BWISE" },
{ make: "TRUCK BODIES", model: "C5 MFG" },
{ make: "TRUCK BODIES", model: "CACTUS DUMP BODIES" },
{ make: "TRUCK BODIES", model: "CADET" },
{ make: "TRUCK BODIES", model: "CANCADE" },
{ make: "TRUCK BODIES", model: "CANUCK" },
{ make: "TRUCK BODIES", model: "APITAL CITY TRLR INC" },
{ make: "TRUCK BODIES", model: "CAS" },
{ make: "TRUCK BODIES", model: "CENTRAL TRUCK BODY" },
{ make: "TRUCK BODIES", model: "CENTURY" },
{ make: "TRUCK BODIES", model: "CHEVROLET" },
{ make: "TRUCK BODIES", model: "CHEVRON" },
{ make: "TRUCK BODIES", model: "CIRCLE D" },
{ make: "TRUCK BODIES", model: "CM" },
{ make: "TRUCK BODIES", model: "COBRA" },
{ make: "TRUCK BODIES", model: "COLT" },
{ make: "TRUCK BODIES", model: "COMMERCIAL BABCOCK" },
{ make: "TRUCK BODIES", model: "COMPLETE" },
{ make: "TRUCK BODIES", model: "CONSHOHOCKEN STEEL PRODUCTS" },
{ make: "TRUCK BODIES", model: "CONYERS TRUCK BODIES" },
{ make: "TRUCK BODIES", model: "CROWN MFG" },
{ make: "TRUCK BODIES", model: "CROWNLINE" },
{ make: "TRUCK BODIES", model: "CRYSTEEL" },
{ make: "TRUCK BODIES", model: "CURRY SUPPLY" },
{ make: "TRUCK BODIES", model: "CUSCO" },
{ make: "TRUCK BODIES", model: "CUSTOM" },
{ make: "TRUCK BODIES", model: "CUSTOM BILT" },
{ make: "TRUCK BODIES", model: "DADEE MFG" },
{ make: "TRUCK BODIES", model: "DAKOTA" },
{ make: "TRUCK BODIES", model: "DAKOTA BODIES" },
{ make: "TRUCK BODIES", model: "DANIELS" },
{ make: "TRUCK BODIES", model: "DELTA STAG" },
{ make: "TRUCK BODIES", model: "DELTA WASECA" },
{ make: "TRUCK BODIES", model: "DEMCO" },
{ make: "TRUCK BODIES", model: "DEMOTE FAB" },
{ make: "TRUCK BODIES", model: "DEMOUNTABLE CONCEPTS" },
{ make: "TRUCK BODIES", model: "DENVER TRUCK SALES" },
{ make: "TRUCK BODIES", model: "DEWEZE" },
{ make: "TRUCK BODIES", model: "DODGE" },
{ make: "TRUCK BODIES", model: "DOUBLE L" },
{ make: "TRUCK BODIES", model: "DRAGON" },
{ make: "TRUCK BODIES", model: "DUMPERDOGG" },
{ make: "TRUCK BODIES", model: "DURABODY" },
{ make: "TRUCK BODIES", model: "DURACLASS" },
{ make: "TRUCK BODIES", model: "DURAMAG" },
{ make: "TRUCK BODIES", model: "DUTEC" },
{ make: "TRUCK BODIES", model: "EAST EBY" },
{ make: "TRUCK BODIES", model: "EMI" },
{ make: "TRUCK BODIES", model: "ERIE" },
{ make: "TRUCK BODIES", model: "ETNYRE" },
{ make: "TRUCK BODIES", model: "ETTS" },
{ make: "TRUCK BODIES", model: "FAB SHOP" },
{ make: "TRUCK BODIES", model: "FALKOPING" },
{ make: "TRUCK BODIES", model: "FIBERLINE" },
{ make: "TRUCK BODIES", model: "FONTAINE" },
{ make: "TRUCK BODIES", model: "FORD" },
{ make: "TRUCK BODIES", model: "FORT FABRICATION AND WELDING" },
{ make: "TRUCK BODIES", model: "FOURGONS LECLAIR" },
{ make: "TRUCK BODIES", model: "FRIESENS WELDING" },
{ make: "TRUCK BODIES", model: "FRONTIER" },
{ make: "TRUCK BODIES", model: "FRUEHAUF" },
{ make: "TRUCK BODIES", model: "FUTURE LINE" },
{ make: "TRUCK BODIES", model: "GALBREATH" },
{ make: "TRUCK BODIES", model: "GALION" },
{ make: "TRUCK BODIES", model: "GALION GODWIN" },
{ make: "TRUCK BODIES", model: "GAPVAX" },
{ make: "TRUCK BODIES", model: "GILETTA" },
{ make: "TRUCK BODIES", model: "GLOBAL EXOTRANS" },
{ make: "TRUCK BODIES", model: "GMC" },
{ make: "TRUCK BODIES", model: "GODWIN" },
{ make: "TRUCK BODIES", model: "GOOD GUYS" },
{ make: "TRUCK BODIES", model: "GOOSENECK" },
{ make: "TRUCK BODIES", model: "GR" },
{ make: "TRUCK BODIES", model: "GRAIN MASTER" },
{ make: "TRUCK BODIES", model: "GRANITE TRUCK BODIES" },
{ make: "TRUCK BODIES", model: "GREAT DANE" },
{ make: "TRUCK BODIES", model: "GSE & E" },
{ make: "TRUCK BODIES", model: "H.O.I" },
{ make: "TRUCK BODIES", model: "HACKNEY" },
{ make: "TRUCK BODIES", model: "HARBOR TRUCK VAN" },
{ make: "TRUCK BODIES", model: "HEIL" },
{ make: "TRUCK BODIES", model: "HENDERSON" },
{ make: "TRUCK BODIES", model: "HERCULES" },
{ make: "TRUCK BODIES", model: "HERITAGE" },
{ make: "TRUCK BODIES", model: "HEWITT" },
{ make: "TRUCK BODIES", model: "HIAB" },
{ make: "TRUCK BODIES", model: "HIGHBALL FABRICATIONS" },
{ make: "TRUCK BODIES", model: "HILLSBORO" },
{ make: "TRUCK BODIES", model: "HILLTIP" },
{ make: "TRUCK BODIES", model: "HIPPO MFG" },
{ make: "TRUCK BODIES", model: "HITCHCOCK" },
{ make: "TRUCK BODIES", model: "HOLMES" },
{ make: "TRUCK BODIES", model: "HOMEMADE" },
{ make: "TRUCK BODIES", model: "HRG" },
{ make: "TRUCK BODIES", model: "HUTCHINSON" },
{ make: "TRUCK BODIES", model: "HYUNDAI" },
{ make: "TRUCK BODIES", model: "HYVA" },
{ make: "TRUCK BODIES", model: "IMT" },
{ make: "TRUCK BODIES", model: "IRON OX" },
{ make: "TRUCK BODIES", model: "IRON VALLEY EQUIPMENT" },
{ make: "TRUCK BODIES", model: "ITB" },
{ make: "TRUCK BODIES", model: "J & I" },
{ make: "TRUCK BODIES", model: "J & J" },
{ make: "TRUCK BODIES", model: "J & J TRUCK BODIES" },
{ make: "TRUCK BODIES", model: "JACO" },
{ make: "TRUCK BODIES", model: "JENKINS" },
{ make: "TRUCK BODIES", model: "JENSEN" },
{ make: "TRUCK BODIES", model: "JERR-DAN" },
{ make: "TRUCK BODIES", model: "JOHNSON" },
{ make: "TRUCK BODIES", model: "KANN" },
{ make: "TRUCK BODIES", model: "KEEVAC" },
{ make: "TRUCK BODIES", model: "KENTUCKY" },
{ make: "TRUCK BODIES", model: "KENWORTH" },
{ make: "TRUCK BODIES", model: "KERSTEN" },
{ make: "TRUCK BODIES", model: "KIDRON" },
{ make: "TRUCK BODIES", model: "KLEESPIE" },
{ make: "TRUCK BODIES", model: "KLEIN" },
{ make: "TRUCK BODIES", model: "KNAPHEIDE" },
{ make: "TRUCK BODIES", model: "K-PAC" },
{ make: "TRUCK BODIES", model: "LABRIE" },
{ make: "TRUCK BODIES", model: "LANAU" },
{ make: "TRUCK BODIES", model: "LARAMIE" },
{ make: "TRUCK BODIES", model: "LARGO TANK" },
{ make: "TRUCK BODIES", model: "LEDWELL" },
{ make: "TRUCK BODIES", model: "LIFT BODIES INC" },
{ make: "TRUCK BODIES", model: "LIFTPRO" },
{ make: "TRUCK BODIES", model: "LOAD TRAIL" },
{ make: "TRUCK BODIES", model: "LOADLINE" },
{ make: "TRUCK BODIES", model: "LOADMASTER" },
{ make: "TRUCK BODIES", model: "LOEWEN" },
{ make: "TRUCK BODIES", model: "LOEWEN BUILT" },
{ make: "TRUCK BODIES", model: "LOGAN FARM EQUIP" },
{ make: "TRUCK BODIES", model: "MAC LTT" },
{ make: "TRUCK BODIES", model: "MAC TRAILERS MFG" },
{ make: "TRUCK BODIES", model: "MAINTAINER" },
{ make: "TRUCK BODIES", model: "MARION" },
{ make: "TRUCK BODIES", model: "MARTIN" },
{ make: "TRUCK BODIES", model: "MAXON" },
{ make: "TRUCK BODIES", model: "MAXX DUMP BODIES" },
{ make: "TRUCK BODIES", model: "MAXXD" },
{ make: "TRUCK BODIES", model: "MCCLAIN GALION" },
{ make: "TRUCK BODIES", model: "MCNEILUS" },
{ make: "TRUCK BODIES", model: "METRO" },
{ make: "TRUCK BODIES", model: "MICKEY" },
{ make: "TRUCK BODIES", model: "MINORU" },
{ make: "TRUCK BODIES", model: "MITSUBISHI FUSO" },
{ make: "TRUCK BODIES", model: "MONROE" },
{ make: "TRUCK BODIES", model: "MORGAN" },
{ make: "TRUCK BODIES", model: "MORITZ INTERNATIONAL" },
{ make: "TRUCK BODIES", model: "MULTI VANS" },
{ make: "TRUCK BODIES", model: "MULTILIFT" },
{ make: "TRUCK BODIES", model: "NAHANNI IND" },
{ make: "TRUCK BODIES", model: "NUESTAR" },
{ make: "TRUCK BODIES", model: "NEW WAY" },
{ make: "TRUCK BODIES", model: "NORSTAR" },
{ make: "TRUCK BODIES", model: "NORTHEAST" },
{ make: "TRUCK BODIES", model: "NORTHEAST INDUSTRIAL MFG" },
{ make: "TRUCK BODIES", model: "NOSE CONE" },
{ make: "TRUCK BODIES", model: "NRC" },
{ make: "TRUCK BODIES", model: "OHNSORG" },
{ make: "TRUCK BODIES", model: "OILMENS" },
{ make: "TRUCK BODIES", model: "OSCO TANK" },
{ make: "TRUCK BODIES", model: "OX BODIES" },
{ make: "TRUCK BODIES", model: "PIASANO" },
{ make: "TRUCK BODIES", model: "PALFINGER" },
{ make: "TRUCK BODIES", model: "PARKER" },
{ make: "TRUCK BODIES", model: "PARKHURST" },
{ make: "TRUCK BODIES", model: "PCI" },
{ make: "TRUCK BODIES", model: "PEAK" },
{ make: "TRUCK BODIES", model: "PERKINS" },
{ make: "TRUCK BODIES", model: "PIEDMONT" },
{ make: "TRUCK BODIES", model: "PJ TRUCK BEDS" },
{ make: "TRUCK BODIES", model: "POLAR" },
{ make: "TRUCK BODIES", model: "PREMIER TRUCK BODIES" },
{ make: "TRUCK BODIES", model: "PRESVAC" },
{ make: "TRUCK BODIES", model: "PROGRESS" },
{ make: "TRUCK BODIES", model: "PRONGHORN" },
{ make: "TRUCK BODIES", model: "R/S GODWIN" },
{ make: "TRUCK BODIES", model: "RAM" },
{ make: "TRUCK BODIES", model: "RAVENS" },
{ make: "TRUCK BODIES", model: "READING" },
{ make: "TRUCK BODIES", model: "REED" },
{ make: "TRUCK BODIES", model: "REITEN" },
{ make: "TRUCK BODIES", model: "RELIANCE" },
{ make: "TRUCK BODIES", model: "RHODES" },
{ make: "TRUCK BODIES", model: "ROCK SOLID TRUCK BODIES" },
{ make: "TRUCK BODIES", model: "ROCKPORT" },
{ make: "TRUCK BODIES", model: "ROC-TEC" },
{ make: "TRUCK BODIES", model: "ROGERS" },
{ make: "TRUCK BODIES", model: "ROLL OFFS USA" },
{ make: "TRUCK BODIES", model: "ROYAL TRUCK BODIES" },
{ make: "TRUCK BODIES", model: "RTR MFG" },
{ make: "TRUCK BODIES", model: "RUFNEK" },
{ make: "TRUCK BODIES", model: "RUGBY" },
{ make: "TRUCK BODIES", model: "R-WAY" },
{ make: "TRUCK BODIES", model: "RX3" },
{ make: "TRUCK BODIES", model: "S&H" },
{ make: "TRUCK BODIES", model: "SALT DOG" },
{ make: "TRUCK BODIES", model: "SCHIEN" },
{ make: "TRUCK BODIES", model: "SCHMIDT" },
{ make: "TRUCK BODIES", model: "SCOTT" },
{ make: "TRUCK BODIES", model: "SE INC" },
{ make: "TRUCK BODIES", model: "SHOP BUILT" },
{ make: "TRUCK BODIES", model: "SMYRNA" },
{ make: "TRUCK BODIES", model: "SNO-WAY" },
{ make: "TRUCK BODIES", model: "SNOWEX" },
{ make: "TRUCK BODIES", model: "SOUTHCO" },
{ make: "TRUCK BODIES", model: "SPRAY KING" },
{ make: "TRUCK BODIES", model: "STAHL" },
{ make: "TRUCK BODIES", model: "STAR MFG" },
{ make: "TRUCK BODIES", model: "STELLAR" },
{ make: "TRUCK BODIES", model: "SUMMIT" },
{ make: "TRUCK BODIES", model: "SUPER CITY" },
{ make: "TRUCK BODIES", model: "SUPER PRODUCTS" },
{ make: "TRUCK BODIES", model: "SUPERIOR" },
{ make: "TRUCK BODIES", model: "SUPREME" },
{ make: "TRUCK BODIES", model: "SUPREME CORP" },
{ make: "TRUCK BODIES", model: "SURE-TRAC" },
{ make: "TRUCK BODIES", model: "SWAP HOGG" },
{ make: "TRUCK BODIES", model: "SWAPLOADER" },
{ make: "TRUCK BODIES", model: "SWENSON" },
{ make: "TRUCK BODIES", model: "SWITCH N GO" },
{ make: "TRUCK BODIES", model: "T&B WATER TRUCKS" },
{ make: "TRUCK BODIES", model: "TAFCO" },
{ make: "TRUCK BODIES", model: "TECO" },
{ make: "TRUCK BODIES", model: "TESCO" },
{ make: "TRUCK BODIES", model: "TFI" },
{ make: "TRUCK BODIES", model: "TG MOUNTAINEER" },
{ make: "TRUCK BODIES", model: "THERMO KING" },
{ make: "TRUCK BODIES", model: "TIGER" },
{ make: "TRUCK BODIES", model: "TODCO" },
{ make: "TRUCK BODIES", model: "TPL" },
{ make: "TRUCK BODIES", model: "TRAILSTAR" },
{ make: "TRUCK BODIES", model: "TRAILTECH" },
{ make: "TRUCK BODIES", model: "TRANSIT" },
{ make: "TRUCK BODIES", model: "TRUCKCRAFT" },
{ make: "TRUCK BODIES", model: "TWIN STAR EQUIP" },
{ make: "TRUCK BODIES", model: "US TANK INDUSTRIES" },
{ make: "TRUCK BODIES", model: "UNICELL" },
{ make: "TRUCK BODIES", model: "UNKNOWN" },
{ make: "TRUCK BODIES", model: "UNSPECIFIED" },
{ make: "TRUCK BODIES", model: "US TRUCK BODY" },
{ make: "TRUCK BODIES", model: "UTILMASTER" },
{ make: "TRUCK BODIES", model: "UTILITY BODY" },
{ make: "TRUCK BODIES", model: "VACTOR" },
{ make: "TRUCK BODIES", model: "VALEW" },
{ make: "TRUCK BODIES", model: "VALLEY ENTERPRISES" },
{ make: "TRUCK BODIES", model: "VENCO" },
{ make: "TRUCK BODIES", model: "VENTURES MFG" },
{ make: "TRUCK BODIES", model: "VIKING CIVES" },
{ make: "TRUCK BODIES", model: "VIRGINIAN" },
{ make: "TRUCK BODIES", model: "VOTH" },
{ make: "TRUCK BODIES", model: "VULCAN" },
{ make: "TRUCK BODIES", model: "WABASH" },
{ make: "TRUCK BODIES", model: "WALKER" },
{ make: "TRUCK BODIES", model: "WARNER" },
{ make: "TRUCK BODIES", model: "WARREN" },
{ make: "TRUCK BODIES", model: "WASTEQUIP" },
{ make: "TRUCK BODIES", model: "WAYNE" },
{ make: "TRUCK BODIES", model: "WELDIT" },
{ make: "TRUCK BODIES", model: "WESTERN" },
{ make: "TRUCK BODIES", model: "WESTERN TRAILERS" },
{ make: "TRUCK BODIES", model: "WESTMARK" },
{ make: "TRUCK BODIES", model: "WILDHORSE" },
{ make: "TRUCK BODIES", model: "WILLIAMSEN" },
{ make: "TRUCK BODIES", model: "WIL-RO" },
{ make: "TRUCK BODIES", model: "YOUNG TANKS" },
{ make: "TRUCK BODIES", model: "ZIMMERMAN" },
{ make: "TRUCK BODIES", model: "OTHER" },

// VANS

{ make: "VANS", model: "FORD" },
{ make: "VANS", model: "MERCEDES-BENZ" },
{ make: "VANS", model: "FREIGHTLINER" },
{ make: "VANS", model: "CHEVROLET" },
{ make: "VANS", model: "RAM" },
{ make: "VANS", model: "GMC" },
{ make: "VANS", model: "NISSAN" },
{ make: "VANS", model: "DODGE" },
{ make: "VANS", model: "CHRYSLER" },
{ make: "VANS", model: "MIDWEST AUTO DESIGN" },
{ make: "VANS", model: "BRIGHTDROP" },
{ make: "VANS", model: "COLLINS" },
{ make: "VANS", model: "GRECH RV" },
{ make: "VANS", model: "HARBINGER" },
{ make: "VANS", model: "HONDA" },
{ make: "VANS", model: "ISUZU" },
{ make: "VANS", model: "KIA" },
{ make: "VANS", model: "LA WEST COACHES" },
{ make: "VANS", model: "MACK" },
{ make: "VANS", model: "MICRO BIRD" },
{ make: "VANS", model: "MULLEN" },
{ make: "VANS", model: "OGV" },
{ make: "VANS", model: "PACIFIC" },
{ make: "VANS", model: "RENAULT" },
{ make: "VANS", model: "TOYOTA" },
{ make: "VANS", model: "UNSPECIFIED" },
{ make: "VANS", model: "UTILMASTER" },
{ make: "VANS", model: "VOLSWAGON" },
{ make: "VANS", model: "WORKHORSE" },
{ make: "VANS", model: "XOS" },
{ make: "VANS", model: "OTHER" },

// VANS

{ make: "VANS", model: "FORD" },
{ make: "VANS", model: "MERCEDES-BENZ" },
{ make: "VANS", model: "FREIGHTLINER" },
{ make: "VANS", model: "CHEVROLET" },
{ make: "VANS", model: "RAM" },
{ make: "VANS", model: "GMC" },
{ make: "VANS", model: "NISSAN" },
{ make: "VANS", model: "DODGE" },
{ make: "VANS", model: "CHRYSLER" },
{ make: "VANS", model: "MIDWEST AUTO DESIGN" },
{ make: "VANS", model: "BRIGHTDROP" },
{ make: "VANS", model: "COLLINS" },
{ make: "VANS", model: "GRECH RV" },
{ make: "VANS", model: "HARBINGER" },
{ make: "VANS", model: "HONDA" },
{ make: "VANS", model: "ISUZU" },
{ make: "VANS", model: "KIA" },
{ make: "VANS", model: "LA WEST COACHES" },
{ make: "VANS", model: "MACK" },
{ make: "VANS", model: "MICRO BIRD" },
{ make: "VANS", model: "MULLEN" },
{ make: "VANS", model: "OGV" },
{ make: "VANS", model: "PACIFIC" },
{ make: "VANS", model: "RENAULT" },
{ make: "VANS", model: "TOYOTA" },
{ make: "VANS", model: "UNSPECIFIED" },
{ make: "VANS", model: "UTILMASTER" },
{ make: "VANS", model: "VOLSWAGON" },
{ make: "VANS", model: "WORKHORSE" },
{ make: "VANS", model: "XOS" },
{ make: "VANS", model: "OTHER" },

// WINCH / OILFIELD TRUCKS

{ make: "WINCH / OILFIELD TRUCKS", model: "PETERBILT" },
{ make: "WINCH / OILFIELD TRUCKS", model: "KENWORTH" },
{ make: "WINCH / OILFIELD TRUCKS", model: "MACK" },
{ make: "WINCH / OILFIELD TRUCKS", model: "INTERNATIONAL WESTERN STAR" },
{ make: "WINCH / OILFIELD TRUCKS", model: "FORD" },
{ make: "WINCH / OILFIELD TRUCKS", model: "FRIGHTLINER" },
{ make: "WINCH / OILFIELD TRUCKS", model: "HINO" },
{ make: "WINCH / OILFIELD TRUCKS", model: "CHEVROLET" },
{ make: "WINCH / OILFIELD TRUCKS", model: "AM GENERAL" },
{ make: "WINCH / OILFIELD TRUCKS", model: "OSHKOSH" },
{ make: "WINCH / OILFIELD TRUCKS", model: "VOLVO" },
{ make: "WINCH / OILFIELD TRUCKS", model: "GMC" },
{ make: "WINCH / OILFIELD TRUCKS", model: "OTHER" },

  // OTHER TRUCKS
  { make: "OTHER TRUCKS", model: "OTHER" },
];

export default trucksTaxonomy;
