// UTILITY CARTS

const utilityCartsTaxonomy = [
 // JOHN DEERE
{ make: "JOHN DEERE", model: "AMT600" },
{ make: "JOHN DEERE", model: "AMT626" },
{ make: "JOHN DEERE", model: "GATOR" },
{ make: "JOHN DEERE", model: "GATOR CX" },
{ make: "JOHN DEERE", model: "GATOR GS" },
{ make: "JOHN DEERE", model: "GATOR GX" },
{ make: "JOHN DEERE", model: "GATOR HPX" },
{ make: "JOHN DEERE", model: "GATOR HPX615E" },
{ make: "JOHN DEERE", model: "GATOR HPX815E" },
{ make: "JOHN DEERE", model: "GATOR RSX 850I" },
{ make: "JOHN DEERE", model: "GATOR RSX 850I TRAIL" },
{ make: "JOHN DEERE", model: "GATOR RSX 860E" },
{ make: "JOHN DEERE", model: "GATOR RSX 860I" },
{ make: "JOHN DEERE", model: "GATOR RSX 860M" },
{ make: "JOHN DEERE", model: "GATOR T520" },
{ make: "JOHN DEERE", model: "GATOR TE" },
{ make: "JOHN DEERE", model: "GATOR TH" },
{ make: "JOHN DEERE", model: "GATOR TS" },
{ make: "JOHN DEERE", model: "GATOR TURF" },
{ make: "JOHN DEERE", model: "GATOR TX" },
{ make: "JOHN DEERE", model: "GATOR TX TURF" },
{ make: "JOHN DEERE", model: "GATOR XUV 550" },
{ make: "JOHN DEERE", model: "GATOR XUV 550 S4" },
{ make: "JOHN DEERE", model: "GATOR XUV 560" },
{ make: "JOHN DEERE", model: "GATOR XUV 560 S4" },
{ make: "JOHN DEERE", model: "GATOR XUV 560E" },
{ make: "JOHN DEERE", model: "GATOR XUV 560E S4" },
{ make: "JOHN DEERE", model: "GATOR XUV 590E" },
{ make: "JOHN DEERE", model: "GATOR XUV 590E S4" },
{ make: "JOHN DEERE", model: "GATOR 590I" },
{ make: "JOHN DEERE", model: "GATOR 590I S4" },
{ make: "JOHN DEERE", model: "GATOR 590M" },
{ make: "JOHN DEERE", model: "GATOR 590M S4" },
{ make: "JOHN DEERE", model: "GATOR 590M SE" },
{ make: "JOHN DEERE", model: "GATOR XUV 620I" },
{ make: "JOHN DEERE", model: "GATOR 620I SE" },
{ make: "JOHN DEERE", model: "GATOR 625I" },
{ make: "JOHN DEERE", model: "GATOR XUV 825E" },
{ make: "JOHN DEERE", model: "GATOR XUV 825I" },
{ make: "JOHN DEERE", model: "GATOR XUV 825I S4" },
{ make: "JOHN DEERE", model: "GATOR XUV 825M" },
{ make: "JOHN DEERE", model: "GATOR XUV 825M S4" },
{ make: "JOHN DEERE", model: "GATOR XUV 835E" },
{ make: "JOHN DEERE", model: "GAOR XUV 835M" },
{ make: "JOHN DEERE", model: "GATOR XUV 835M HONOR EDITION" },
{ make: "JOHN DEERE", model: "GATOR XUV 835M HVAC" },
{ make: "JOHN DEERE", model: "GATOR CXUV 835M HVAC HONOR" },
{ make: "JOHN DEERE", model: "GATOR XUV 835R" },
{ make: "JOHN DEERE", model: "GATOR XUV 835R SIGNATURE" },
{ make: "JOHN DEERE", model: "GATOR XUV 845E" },
{ make: "JOHN DEERE", model: "GATOR XUV 845M" },
{ make: "JOHN DEERE", model: "GATOR XUV 845R" },
{ make: "JOHN DEERE", model: "GATOR XUV 850D" },
{ make: "JOHN DEERE", model: "GATOR XUV 855D" },
{ make: "JOHN DEERE", model: "GATOR XUV 855D S4" },
{ make: "JOHN DEERE", model: "GATOR 855M" },
{ make: "JOHN DEERE", model: "GATOR 855M S4" },
{ make: "JOHN DEERE", model: "GATOR XUV 865M " },
{ make: "JOHN DEERE", model: "GATOR XUV 865M S4" },
{ make: "JOHN DEERE", model: "GATOR XUV 865M HVAC" },
{ make: "JOHN DEERE", model: "GATOR XUV 865R" },
{ make: "JOHN DEERE", model: "GATOR XUV 875M" },
{ make: "JOHN DEERE", model: "GATOR XUV 875R" },
{ make: "JOHN DEERE", model: "M-GATOR 6X4" },
{ make: "JOHN DEERE", model: "PROGATOR 2020" },
{ make: "JOHN DEERE", model: "PROGATOR 2020A" },
{ make: "JOHN DEERE", model: "PROGATOR 2030" },
{ make: "JOHN DEERE", model: "PROGATOR 2030A" },
{ make: "JOHN DEERE", model: "TRAIL GATOR" },
{ make: "JOHN DEERE", model: "TRAIL GATOR HPX" },
{ make: "JOHN DEERE", model: "OTHER" },

  // KUBOTA
{ make: "KUBOTA", model: "RTV400-A" },
{ make: "KUBOTA", model: "RTV400CI" },
{ make: "KUBOTA", model: "RTV400CI-A" },
{ make: "KUBOTA", model: "RTV400CI-H" },
{ make: "KUBOTA", model: "RTV400CIR-A" },
{ make: "KUBOTA", model: "RTV500" },
{ make: "KUBOTA", model: "RTV500-H" },
{ make: "KUBOTA", model: "RTV500R-A" },
{ make: "KUBOTA", model: "RTV520D" },
{ make: "KUBOTA", model: "RTV520D-AS" },
{ make: "KUBOTA", model: "RTV900" },
{ make: "KUBOTA", model: "RTV900-EU" },
{ make: "KUBOTA", model: "RTV900G" },
{ make: "KUBOTA", model: "RTV900R" },
{ make: "KUBOTA", model: "RTV900R6-A" },
{ make: "KUBOTA", model: "RTV900W6H" },
{ make: "KUBOTA", model: "RTV900W9A" },
{ make: "KUBOTA", model: "RTV900XT" },
{ make: "KUBOTA", model: "RTV900XTR" },
{ make: "KUBOTA", model: "RTV900XTS" },
{ make: "KUBOTA", model: "RTV900XTW" },
{ make: "KUBOTA", model: "RTV1100" },
{ make: "KUBOTA", model: "RTV1100C" },
{ make: "KUBOTA", model: "RTV1140" },
{ make: "KUBOTA", model: "RTV1140CPX" },
{ make: "KUBOTA", model: "RTV1140CPX-H" },
{ make: "KUBOTA", model: "RTV1140PXR-A" },
{ make: "KUBOTA", model: "RTV1140CPX-UK" },
{ make: "KUBOTA", model: "RTV-X" },
{ make: "KUBOTA", model: "RTV-X CREW" },
{ make: "KUBOTA", model: "RTV-XG850 SIDEKICK" },
{ make: "KUBOTA", model: "RTV-X900" },
{ make: "KUBOTA", model: "RTV-X900G" },
{ make: "KUBOTA", model: "RTV-X900R" },
{ make: "KUBOTA", model: "RTV-X900W" },
{ make: "KUBOTA", model: "RTV-X1110" },
{ make: "KUBOTA", model: "RTV-X1100C" },
{ make: "KUBOTA", model: "RTV-X1100CW-H" },
{ make: "KUBOTA", model: "RTV-X1100CR" },
{ make: "KUBOTA", model: "RTV-X1100CRL-A" },
{ make: "KUBOTA", model: "RTV-X1100CW" },
{ make: "KUBOTA", model: "RTV-X1100CWL-A" },
{ make: "KUBOTA", model: "RTV-X1120" },
{ make: "KUBOTA", model: "RTV-X1120D" },
{ make: "KUBOTA", model: "RTV-X1120DR" },
{ make: "KUBOTA", model: "RTV-X1120DW" },
{ make: "KUBOTA", model: "RTV-X1120WLH" },
{ make: "KUBOTA", model: "RTV-X1130" },
{ make: "KUBOTA", model: "RTV-X1140" },
{ make: "KUBOTA", model: "RTV-X1140W" },
{ make: "KUBOTA", model: "RTV-X CAB" },
{ make: "KUBOTA", model: "RTV-X LONG BED" },
{ make: "KUBOTA", model: "OTHER" },
  
  // POLARIS

{ make: "POLARIS", model: "ACE 900SP" },
{ make: "POLARIS", model: "ACE 150 EFI" },
{ make: "POLARIS", model: "ACE 500" },
{ make: "POLARIS", model: "ACE 570" },
{ make: "POLARIS", model: "ACE 570 SP" },
{ make: "POLARIS", model: "ACE 900 XC" },
{ make: "POLARIS", model: "BRUTUS HD PTO" },
{ make: "POLARIS", model: "BRUTUS HD" },
{ make: "POLARIS", model: "BRUTUS HDPTO DELUXE" },
{ make: "POLARIS", model: "EV LSV" },
{ make: "POLARIS", model: "GEM E2" },
{ make: "POLARIS", model: "GEM E4" },
{ make: "POLARIS", model: "GEM E6" },
{ make: "POLARIS", model: "GEM EL XD" },
{ make: "POLARIS", model: "GENERAL 1000" },
{ make: "POLARIS", model: "GENERAL 1000 DELUXE" },
{ make: "POLARIS", model: "GENERAL 1000 EPS" },
{ make: "POLARIS", model: "GENERAL 1000 EPS DELUXE" },
{ make: "POLARIS", model: "GENERAL 1000 PREMIUM" },
{ make: "POLARIS", model: "GENERAL 1000 SPORT" },
{ make: "POLARIS", model: "GENERAL 4 1000" },
{ make: "POLARIS", model: "GENERAL 4 1000 DELUXE" },
{ make: "POLARIS", model: "GENERAL 4 1000 EPS" },
{ make: "POLARIS", model: "GENERAL 4 1000 PREMIUM" },
{ make: "POLARIS", model: "GENERAL 4 1000 SPORT" },
{ make: "POLARIS", model: "GENERAL XP 4 1000 DELUXE" },
{ make: "POLARIS", model: "GENERAL XP 4 PREMIUM " },
{ make: "POLARIS", model: "GENERAL XP 4 SPORT" },
{ make: "POLARIS", model: "GENERAL XP 4 ULTIMATE" },
{ make: "POLARIS", model: "GENERAL XP 4 1000" },
{ make: "POLARIS", model: "GENERAL XP 4 1000 PREMIUM" },
{ make: "POLARIS", model: "GENERAL XP 4 1000 SPORT" },
{ make: "POLARIS", model: "GENERAL XP 4 1000 ULTIMATE" },
{ make: "POLARIS", model: "GENERAL XP 1000 DELUXE" },
{ make: "POLARIS", model: "GENERAL XP 1000 PREMIUM " },
{ make: "POLARIS", model: "GENERAL XP 1000 SPORT" },
{ make: "POLARIS", model: "GENERAL XP ULTIMATE" },
{ make: "POLARIS", model: "GENERAL XP 1000" },
{ make: "POLARIS", model: "GENERAL XP 1000 ULTIMATE" },
{ make: "POLARIS", model: "PRO XD 2000D" },
{ make: "POLARIS", model: "PRO XD 2000G" },
{ make: "POLARIS", model: "PRO XD 4000D" },
{ make: "POLARIS", model: "PRO XD 4000G" },
{ make: "POLARIS", model: "PRO XD FULL-SIZE DIESEL" },
{ make: "POLARIS", model: "PRO XD FULL-SIZE DIESEL CREW" },
{ make: "POLARIS", model: "PRO XD FULL-SIZE GAS" },
{ make: "POLARIS", model: "PRO XD FULL-SIZE GAS CREW" },
{ make: "POLARIS", model: "PRO XD MID-SIZE GAS" },
{ make: "POLARIS", model: "PRO XD MID-SIZE GAS CREW" },
{ make: "POLARIS", model: "PRO XD FS DIESEL " },
{ make: "POLARIS", model: "PRO XD FS DIESEL CREW" },
{ make: "POLARIS", model: "PRO XD FS GAS" },
{ make: "POLARIS", model: "PRO XD FS GAS CREW" },
{ make: "POLARIS", model: "PRO XD MS GAS" },
{ make: "POLARIS", model: "PRO XD MS GAS CREW" },
{ make: "POLARIS", model: "RANGER " },
{ make: "POLARIS", model: "RANGER 6X6" },
{ make: "POLARIS", model: "RANGER 6X6 700" },
{ make: "POLARIS", model: "RANGER 6X6 800" },
{ make: "POLARIS", model: "RANGER 6X6 900" },
{ make: "POLARIS", model: "RANFGER 150EFI" },
{ make: "POLARIS", model: "RANGER 150 EFI" },
{ make: "POLARIS", model: "RANGER 400" },
{ make: "POLARIS", model: "RANGER 500" },
{ make: "POLARIS", model: "RANGER 500EFI" },
{ make: "POLARIS", model: "RANGER 570" },
{ make: "POLARIS", model: "RANGER 570EFI" },
{ make: "POLARIS", model: "RANGER 570EPS" },
{ make: "POLARIS", model: "RANGER 570FS" },
{ make: "POLARIS", model: "RANGER 570 FULL-SIZE" },
{ make: "POLARIS", model: "RANGER 570 MID-SIZE" },
{ make: "POLARIS", model: "RANGER 570 PREMIUM" },
{ make: "POLARIS", model: "RANGER 700EFI" },
{ make: "POLARIS", model: "RANGER 700XP" },
{ make: "POLARIS", model: "RANGER 800" },
{ make: "POLARIS", model: "RANGER 800EFI" },
{ make: "POLARIS", model: "RANGER 800HD" },
{ make: "POLARIS", model: "RANGER 800XP" },
{ make: "POLARIS", model: "RANGER 1000" },
{ make: "POLARIS", model: "RANGER 1000 EPS" },
{ make: "POLARIS", model: "RANGER 1000 PREMIUM" },
{ make: "POLARIS", model: "RANGER 1000 SPORT" },
{ make: "POLARIS", model: "RANGER 1000 SOHC" },
{ make: "POLARIS", model: "RANGER 1000 XP" },
{ make: "POLARIS", model: "RANGER ETX" },
{ make: "POLARIS", model: "RANGER EV" },
{ make: "POLARIS", model: "RANGER EV LI-ION" },
{ make: "POLARIS", model: "RANGER SP570" },
{ make: "POLARIS", model: "RANGER SP 570 NORTHSTAR" },
{ make: "POLARIS", model: "RANGER SP 570 PREMIUM" },
{ make: "POLARIS", model: "RANGER SP 570" },
{ make: "POLARIS", model: "RANGER SP 570 SPORT" },
{ make: "POLARIS", model: "RANGER TM" },
{ make: "POLARIS", model: "RANGER XP" },
{ make: "POLARIS", model: "RANGER XP 700 EFI" },
{ make: "POLARIS", model: "RANGER XP 800 EFI" },
{ make: "POLARIS", model: "RANGER XP 800 EPS" },
{ make: "POLARIS", model: "RANGER XP 900" },
{ make: "POLARIS", model: "RANGER XP 900 EFI" },
{ make: "POLARIS", model: "RANGER XP 900 EPS" },
{ make: "POLARIS", model: "RANGER XP 900 EPS HUNTER" },
{ make: "POLARIS", model: "RANGER 900 EPS LE" },
{ make: "POLARIS", model: "RANGER EPS PREMIUM" },
{ make: "POLARIS", model: "RANGER XP 900HD" },
{ make: "POLARIS", model: "RANGER XP 900 HIGH LIFTER" },
{ make: "POLARIS", model: "RANGER XP 900 NORTHSTAR" },
{ make: "POLARIS", model: "RANGER XP 900 PREMIUM" },
{ make: "POLARIS", model: "RANGER XP 900 TRAIL EDITION" },
{ make: "POLARIS", model: "RANGER XP 1000" },
{ make: "POLARIS", model: "RANGER XP 1000 EPS" },
{ make: "POLARIS", model: "RANGER XP 1000 EPS BACK COUNTRY LE" },
{ make: "POLARIS", model: "RANGER XP 1000 EPS HIGH LIFTER " },
{ make: "POLARIS", model: "RANGER XP 1000 EPS NORTHSTAR" },
{ make: "POLARIS", model: "RANGER XP 1000 EPS PREMIUM" },
{ make: "POLARIS", model: "RANGER XP 1000 EPS RANCH " },
{ make: "POLARIS", model: "RANGER XP 1000 NORTHSTAR PREMIUM" },
{ make: "POLARIS", model: "RANGER XP 1000 NORTHSTAR TRAIL BOSS" },
{ make: "POLARIS", model: "RANGER XP 1000 NORTHSTAR ULTIMATE" },
{ make: "POLARIS", model: "RANGER XP 1000 PREMIUM" },
{ make: "POLARIS", model: "RANGER XP 1000 TEXAS" },
{ make: "POLARIS", model: "RANGER XP 1000 BIG GAME EDITION" },
{ make: "POLARIS", model: "RANGER XP 1000 HIGH LIFTER" },
{ make: "POLARIS", model: "RANGER XP 1000 NORTHSTAR EDITION" },
{ make: "POLARIS", model: "RANGER XP 1000 RANCH EDITION" },
{ make: "POLARIS", model: "RANGER XP 1000 SPORT" },
{ make: "POLARIS", model: "RANGER XP 1000 TRAIL BOSS" },
{ make: "POLARIS", model: "RANGER XP 1000 WATERFOWL EDITION" },
{ make: "POLARIS", model: "RANGER XP KINETIC PREMIUM" },
{ make: "POLARIS", model: "RANGER XP KINETIC ULTIMATE" },
{ make: "POLARIS", model: "RANGER CREW" },
{ make: "POLARIS", model: "RANGER CREW 500" },
{ make: "POLARIS", model: "RANGER CREW 570" },
{ make: "POLARIS", model: "RANGER CREW 570EFI" },
{ make: "POLARIS", model: "RANGER CREW 570FS" },
{ make: "POLARIS", model: "RANGER CREW 570-4" },
{ make: "POLARIS", model: "RANGER CREW 570 FULL-SIZE" },
{ make: "POLARIS", model: "RANGER CREW 570 MID-SIZE" },
{ make: "POLARIS", model: "RANGER CREW 800" },
{ make: "POLARIS", model: "RANGER CREW 800EFI" },
{ make: "POLARIS", model: "RANGER CREW 900" },
{ make: "POLARIS", model: "RANGER CREW 900 EPS" },
{ make: "POLARIS", model: "RANGER CREW 900 PREMIUM" },
{ make: "POLARIS", model: "RANGER CREW 1000" },
{ make: "POLARIS", model: "RANGER CREW 1000 EPS" },
{ make: "POLARIS", model: "RANGER CREW 1000 PREMIUM" },
{ make: "POLARIS", model: "RANGER CREW 1000 SPORT" },
{ make: "POLARIS", model: "RANGER CREW DIESEL " },
{ make: "POLARIS", model: "RANGER CREW DIESEL 1000" },
{ make: "POLARIS", model: "RANGER CREW DIESEL 1000 PREMIUM" },
{ make: "POLARIS", model: "RANGER CREW SP 570" },
{ make: "POLARIS", model: "RANGER CREW SP 570 NORTHSTAR " },
{ make: "POLARIS", model: "RANGER CREW SP 570 PREMIUM" },
{ make: "POLARIS", model: "RANGER CREW SP 570 SPORT" },
{ make: "POLARIS", model: "RANGER CREW" },
{ make: "POLARIS", model: "RANGER CREW XP 900-6" },
{ make: "POLARIS", model: "RANGER CREW XP 900 EPS" },
{ make: "POLARIS", model: "RANGER CREW XP 900 HIGH LIFTER" },
{ make: "POLARIS", model: "RANGER CREW XP 900 NORTHSTAR" },
{ make: "POLARIS", model: "RANGER CREW XP 900 PREMIUM" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 " },
{ make: "POLARIS", model: "RANGER CREW XP 1000 EPS" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 EPS NORTHSTAR" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 NORTHSTAR PREMIUM" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 NORTHSTAR TEXAS EDITION" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 NORTHSTAR TRAIL BOSS" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 NORTHSTAR ULTIMATE" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 PREMIUM" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 TEXAS EDITION" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 BIG GAME EDITION" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 HIGH LIFTER" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 NORTHSTAR EDITION" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 RANCH EDITION" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 SPORT" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 TRAIL BOSS" },
{ make: "POLARIS", model: "RANGER CREW XP 1000 WATERFOWL EDITION" },
{ make: "POLARIS", model: "RANGER CREW XD 1500 NORTHSTAR PREMIUM" },
{ make: "POLARIS", model: "RANGER CREW XD 1500 NORTHSTAR ULTIMATE" },
{ make: "POLARIS", model: "RANGER CREW XD 1500 PREMIUM" },
{ make: "POLARIS", model: "RANGER CREW XD 1500 ULTIMATE" },
{ make: "POLARIS", model: "RANGER DIESEL " },
{ make: "POLARIS", model: "RANGER DIESEL 1000" },
{ make: "POLARIS", model: "RANGER DIESEL 1000 PREMIUM" },
{ make: "POLARIS", model: "RANGER RZR 170" },
{ make: "POLARIS", model: "RANGER RZR 570" },
{ make: "POLARIS", model: "RANGER RZR 800" },
{ make: "POLARIS", model: "RANGER XD 1500 NORTHSTAR PREMIUM" },
{ make: "POLARIS", model: "RANGER XD 1500 NORTHSTAR ULTIMATE" },
{ make: "POLARIS", model: "RANGER XD 1500 PREMIUM" },
{ make: "POLARIS", model: "RANGER XD 1500 ULTIMATE" },
{ make: "POLARIS", model: "RANGER XD 1500" },
{ make: "POLARIS", model: "RANGER XD 1500 NORTHSTAR EDITION" },
{ make: "POLARIS", model: "RZR 4 800 EPS" },
{ make: "POLARIS", model: "RZR 4 900 EPS" },
{ make: "POLARIS", model: "RZR 4 900 EPS TRAIL" },
{ make: "POLARIS", model: "RZR 200 EFI" },
{ make: "POLARIS", model: "RZR 170 EFI" },
{ make: "POLARIS", model: "RZR 570" },
{ make: "POLARIS", model: "RZR 570 EFI" },
{ make: "POLARIS", model: "RZR 570 EPS" },
{ make: "POLARIS", model: "RZR 570 TRAIL" },
{ make: "POLARIS", model: "RZR 800" },
{ make: "POLARIS", model: "RZR 800 EPS" },
{ make: "POLARIS", model: "RZR 900" },
{ make: "POLARIS", model: "RZR 900 EPS" },
{ make: "POLARIS", model: "RZR 900 EPS TRAIL " },
{ make: "POLARIS", model: "RZR 900 EPS XC" },
{ make: "POLARIS", model: "RZR 900 XP " },
{ make: "POLARIS", model: "RZR RS1" },
{ make: "POLARIS", model: "RZR S 800 EFI" },
{ make: "POLARIS", model: "RZR S 900" },
{ make: "POLARIS", model: "RZR S 900 EPS" },
{ make: "POLARIS", model: "RZR S 1000" },
{ make: "POLARIS", model: "RZR S 1000 EPS" },
{ make: "POLARIS", model: "RZR XP 4 1000" },
{ make: "POLARIS", model: "RZR XP 4 1000 PREMIUM" },
{ make: "POLARIS", model: "RZR XP 4 1000 SPORT" },
{ make: "POLARIS", model: "RZR XP 4 1000 ULTIMATE" },
{ make: "POLARIS", model: "RZR XP 4 1000 HIGH LIFTER" },
{ make: "POLARIS", model: "RZR XP 4 1000 RIDE COMMAND" },
{ make: "POLARIS", model: "RZR XP 4 TURBO EPS" },
{ make: "POLARIS", model: "RZR XP 4 TURBO FOX " },
{ make: "POLARIS", model: "RZR XP 4 TURBO S" },
{ make: "POLARIS", model: "RZR XP 4 TURBO S VELOCITY" },
{ make: "POLARIS", model: "RZR XP 4 TURBO S PREMIUM" },
{ make: "POLARIS", model: "RZR XP TURBO S VELOCITY" },
{ make: "POLARIS", model: "RZR XP 900" },
{ make: "POLARIS", model: "RZR XP 1000" },
{ make: "POLARIS", model: "RZR XP 1000 EPS" },
{ make: "POLARIS", model: "RZR XP 1000 SPORT" },
{ make: "POLARIS", model: "RZR XP 1000 TRAILS AND ROCKS" },
{ make: "POLARIS", model: "RZR XP 1000 ULTIMATE" },
{ make: "POLARIS", model: "RZR XP 1000 HIGH LIFTER" },
{ make: "POLARIS", model: "RZR XP 1000 PREMIUM" },
{ make: "POLARIS", model: "RZR XP 1000 RIDE COMMAND" },
{ make: "POLARIS", model: "RZR XP S 4 1000 ULTIMATE" },
{ make: "POLARIS", model: "RZR XP S 900" },
{ make: "POLARIS", model: "RZR XP S 1000" },
{ make: "POLARIS", model: "RZR XP TURBO S VELOCITY" },
{ make: "POLARIS", model: "RZR XP TURBO EPS" },
{ make: "POLARIS", model: "RZR XP TURBO S VELOCITY" },
{ make: "POLARIS", model: "RZR XP TURBO" },
{ make: "POLARIS", model: "RZR XP TURBO S" },
{ make: "POLARIS", model: "RZR XP TURBO S PREMIUM" },
{ make: "POLARIS", model: "RZR 1000" },
{ make: "POLARIS", model: "RZR PRO R 4 PREMIUM" },
{ make: "POLARIS", model: "RZR PRO R 4 SPORT" },
{ make: "POLARIS", model: "RZR PRO R 4 ULTIMATE" },
{ make: "POLARIS", model: "RZR PRO R PREMIUM" },
{ make: "POLARIS", model: "RZR PRO R ULTIMATE" },
{ make: "POLARIS", model: "RZR PRO R" },
{ make: "POLARIS", model: "RZR PRO R 4" },
{ make: "POLARIS", model: "RZR PRO S 4 PREMIUM" },
{ make: "POLARIS", model: "RZR PRO S 4 SPORT" },
{ make: "POLARIS", model: "RZR PRO S 4 ULTIMATE " },
{ make: "POLARIS", model: "RZR PRO S PREMIUM" },
{ make: "POLARIS", model: "RZR PRO S SPORT" },
{ make: "POLARIS", model: "RZR PRO S ULTIMATE" },
{ make: "POLARIS", model: "RZR PRO XP " },
{ make: "POLARIS", model: "RZR PRO XP 4 PREMIUM" },
{ make: "POLARIS", model: "RZR PRO XP 4 SPORT" },
{ make: "POLARIS", model: "RZR PRO XP 4 ULTIMATE " },
{ make: "POLARIS", model: "RZR PRO XP PREMIUM" },
{ make: "POLARIS", model: "RZR PRO XP SPORT" },
{ make: "POLARIS", model: "RZR PRO XP ULTIMATE" },
{ make: "POLARIS", model: "RZR PRO XP 4" },
{ make: "POLARIS", model: "RZR PRO XP 4 LE" },
{ make: "POLARIS", model: "RZR TRAIL PREMIUM" },
{ make: "POLARIS", model: "RZR TRAIL S 1000 PREMIUM" },
{ make: "POLARIS", model: "RZR TRAIL S 1000 ULTIMATE " },
{ make: "POLARIS", model: "RZR TRAIL ULTIMATE " },
{ make: "POLARIS", model: "RZR TRAIL" },
{ make: "POLARIS", model: "RZR TRAIL S 900" },
{ make: "POLARIS", model: "RZR TRAIL S 900 PREMIUM" },
{ make: "POLARIS", model: "RZR TRAIL S 1000" },
{ make: "POLARIS", model: "RZR TURBO R 4 PREMIUM" },
{ make: "POLARIS", model: "RZR TURBO R 4 ULTIMATE " },
{ make: "POLARIS", model: "RZR TURBO R PREMIUM" },
{ make: "POLARIS", model: "RZR TURBO R ULTIMATE" },
{ make: "POLARIS", model: "RZR TURBO R" },
{ make: "POLARIS", model: "RZR TURBO R 4" },
{ make: "POLARIS", model: "RZR TURBO S" },
{ make: "POLARIS", model: "XPEDITION ADV 5 NORTHSTAR " },
{ make: "POLARIS", model: "XPEDITION ADV 5 ULTIMATE" },
{ make: "POLARIS", model: "XPEDITION ADV NORTHSTAR " },
{ make: "POLARIS", model: "XPEDITION ADV ULTIMATE" },
{ make: "POLARIS", model: "XPEDITION XP 5 NORTHSTAR " },
{ make: "POLARIS", model: "XPEDITION XP NORTHSTAR " },
{ make: "POLARIS", model: "XPEDITION XP ULTIMATE" },
{ make: "POLARIS", model: "XPEDITION ADV" },
{ make: "POLARIS", model: "XPEDITION ADV 5" },
{ make: "POLARIS", model: "XPEDITION XP" },
{ make: "POLARIS", model: "XPEDITION XP 5" },
{ make: "POLARIS", model: "SPORTSMAN 450 H.O." },
{ make: "POLARIS", model: "SPORTSMAN 570" },
{ make: "POLARIS", model: "SPORTSMAN 570 EPS" },
{ make: "POLARIS", model: "SPORTSMAN 570 PREMIUM" },
{ make: "POLARIS", model: "SPORTSMAN 570 ULTIMATE TRAIL" },
{ make: "POLARIS", model: "SPORTSMAN 850" },
{ make: "POLARIS", model: "SPORTSMAN 850 PREMIUM" },
{ make: "POLARIS", model: "SPORTSMAN XP 1000" },
{ make: "POLARIS", model: "SPORTSMAN XP 1000 PREMIUM" },
{ make: "POLARIS", model: "SPORTSMAN XP 1000 ULTIMATE TRAIL" },
{ make: "POLARIS", model: "SPORTSMAN 6X6 570" },
{ make: "POLARIS", model: "SPORTSMAN TOURING 570" },
{ make: "POLARIS", model: "SPORTSMAN TOURING 850" },
{ make: "POLARIS", model: "SPORTSMAN TOURING XP 1000" },
{ make: "POLARIS", model: "SCRAMBLER 850" },
{ make: "POLARIS", model: "SCRAMBLER XP 1000" },
{ make: "POLARIS", model: "PHOENIX 200" },
{ make: "POLARIS", model: "OUTLAW 70 EFI" },
{ make: "POLARIS", model: "OUTLAW 110 EFI" },
{ make: "POLARIS", model: "OTHER" },

 // KAWASAKI

{ make: "KAWASAKI", model: "KAF820FJF" },
{ make: "KAWASAKI", model: "KAF950G" },
{ make: "KAWASAKI", model: "MULE 500" },
{ make: "KAWASAKI", model: "MULE 520" },
{ make: "KAWASAKI", model: "MULE 550" },
{ make: "KAWASAKI", model: "MULE 600" },
{ make: "KAWASAKI", model: "MULE 610" },
{ make: "KAWASAKI", model: "MULE 610 4X4" },
{ make: "KAWASAKI", model: "MULE 610 XC" },
{ make: "KAWASAKI", model: "MULE 610 XC CAMO" },
{ make: "KAWASAKI", model: "MULE 1000" },
{ make: "KAWASAKI", model: "MULE 2020" },
{ make: "KAWASAKI", model: "MULE 2030" },
{ make: "KAWASAKI", model: "MULE 2010" },
{ make: "KAWASAKI", model: "MULE 2500" },
{ make: "KAWASAKI", model: "MULE 2510" },
{ make: "KAWASAKI", model: "MULE 2510 4X4" },
{ make: "KAWASAKI", model: "MULE 2510 DIESEL" },
{ make: "KAWASAKI", model: "MULE 2520" },
{ make: "KAWASAKI", model: "MULE 3000" },
{ make: "KAWASAKI", model: "MULE 3010" },
{ make: "KAWASAKI", model: "MULE 3010 4X4" },
{ make: "KAWASAKI", model: "MULE 3010 DIESEL" },
{ make: "KAWASAKI", model: "MULE 3010 TRANS 4X4" },
{ make: "KAWASAKI", model: "MULE 3010 TRAN 4X4" },
{ make: "KAWASAKI", model: "MULE 3020" },
{ make: "KAWASAKI", model: "MULE 4000" },
{ make: "KAWASAKI", model: "MULE 4000 2X4" },
{ make: "KAWASAKI", model: "MULE 4010 4X4" },
{ make: "KAWASAKI", model: "MULE 4010 4X4 CAMO" },
{ make: "KAWASAKI", model: "MULE 4010 4X4 FE" },
{ make: "KAWASAKI", model: "MULE 4010 TRANS 4X4" },
{ make: "KAWASAKI", model: "MULE 4010 TRANS 4X4 CAMO" },
{ make: "KAWASAKI", model: "MULE 4010 TRANS 4X4 DIESEL" },
{ make: "KAWASAKI", model: "MULE 4010 TRANS 4X4 FE" },
{ make: "KAWASAKI", model: "MULE 4010 TRANS 4X4 SE" },
{ make: "KAWASAKI", model: "MULE PRO FX 820 EPS" },
{ make: "KAWASAKI", model: "MULE PRO DX" },
{ make: "KAWASAKI", model: "MULE PRO DX EPS" },
{ make: "KAWASAKI", model: "MULE PRO DX EPS DIESEL" },
{ make: "KAWASAKI", model: "MULE PRO DX EPS LE" },
{ make: "KAWASAKI", model: "MULE PRO DXT" },
{ make: "KAWASAKI", model: "MULE PRO DXT EPS" },
{ make: "KAWASAKI", model: "MULE PRO DXT EPS DIESEL" },
{ make: "KAWASAKI", model: "MULE PRO DXT EPS FE" },
{ make: "KAWASAKI", model: "MULE PRO DXT EPS LE" },
{ make: "KAWASAKI", model: "MULE PRO FX" },
{ make: "KAWASAKI", model: "MULE PRO FX1000 HD" },
{ make: "KAWASAKI", model: "MULE PRO FX1000 HD EDITION" },
{ make: "KAWASAKI", model: "MULE PRO FX EPS" },
{ make: "KAWASAKI", model: "MULE PRO FX EPS CAMO" },
{ make: "KAWASAKI", model: "MULE PRO FX EPS LE" },
{ make: "KAWASAKI", model: "MULE PRO FX EPS RANCH EDITION" },
{ make: "KAWASAKI", model: "MULE PRO FXR" },
{ make: "KAWASAKI", model: "MULE PRO FXR 1000" },
{ make: "KAWASAKI", model: "MUL EPRO FXR 1000 LE" },
{ make: "KAWASAKI", model: "MULE PRO FXR 1000 LE" },
{ make: "KAWASAKI", model: "MULE PRO FXR 1000 SE" },
{ make: "KAWASAKI", model: "MULE PRO FXR EPS" },
{ make: "KAWASAKI", model: "MULE PRO FXR EPS LE" },
{ make: "KAWASAKI", model: "MULE PRO FXT " },
{ make: "KAWASAKI", model: "MULE PRO FXT 820 EPS" },
{ make: "KAWASAKI", model: "MULE PRO FXT 1000 LE" },
{ make: "KAWASAKI", model: "MULE PRO FXT 1000 LE CAMO" },
{ make: "KAWASAKI", model: "MULE PRO FXT 1000 LE RANCH " },
{ make: "KAWASAKI", model: "MULE PRO FXT 1000 PLATINUM RANCH " },
{ make: "KAWASAKI", model: "MULE PRO FXT EPS" },
{ make: "KAWASAKI", model: "MULE PRO FXT EPS CAMO" },
{ make: "KAWASAKI", model: "MULE PRO FXT EPS LE" },
{ make: "KAWASAKI", model: "MULE PRO FXT EPS RANCH EDITION" },
{ make: "KAWASAKI", model: "MUL EPRO FXT EPS LE " },
{ make: "KAWASAKI", model: "MULE PRO FXT RANCH " },
{ make: "KAWASAKI", model: "MULE PRO FXT RANCH PLATINUM " },
{ make: "KAWASAKI", model: "MULE PRO FXT RANCH EDITION" },
{ make: "KAWASAKI", model: "MULE PRO FXT RANCH EDITION DIESEL" },
{ make: "KAWASAKI", model: "MULE PRO FXT RANCH EDITION PLATINUM" },
{ make: "KAWASAKI", model: "MULE PRO MX" },
{ make: "KAWASAKI", model: "MULE PRO MX EPS" },
{ make: "KAWASAKI", model: "MULE PRO MX EPS CAMO" },
{ make: "KAWASAKI", model: "MULE PRO MX EPS LE" },
{ make: "KAWASAKI", model: "MULE PRO MX EPS SE" },
{ make: "KAWASAKI", model: "MULE PRO MX LE" },
{ make: "KAWASAKI", model: "MULE PRO MX SE" },
{ make: "KAWASAKI", model: "MULE SX" },
{ make: "KAWASAKI", model: "MULE SX 4X4" },
{ make: "KAWASAKI", model: "MULE SX 4X4 FE" },
{ make: "KAWASAKI", model: "MULE SX 4X4 FI" },
{ make: "KAWASAKI", model: "MULE SX 4X4 FI CAMO" },
{ make: "KAWASAKI", model: "MULE SX 4X4 XC" },
{ make: "KAWASAKI", model: "MULE SX 4X4 XC CAMO" },
{ make: "KAWASAKI", model: "MULE SX 4X4 XC FI" },
{ make: "KAWASAKI", model: "MULE SX 4X4 XC LE FI" },
{ make: "KAWASAKI", model: "MULE SX 4X4 XC SE FI" },
{ make: "KAWASAKI", model: "RIDGE CREW" },
{ make: "KAWASAKI", model: "RIDGE CREW HVAC" },
{ make: "KAWASAKI", model: "RIDGE CREW LIMITED HVAC" },
{ make: "KAWASAKI", model: "RIDGE CREW PLATINUM RANCH EDITION HVAC" },
{ make: "KAWASAKI", model: "RIDGE CREW ST HVAC " },
{ make: "KAWASAKI", model: "RIDGE HVAC" },
{ make: "KAWASAKI", model: "RIDGE LIMITED HVAC " },
{ make: "KAWASAKI", model: "RIDGE RANCH EDITION " },
{ make: "KAWASAKI", model: "RIDGE RANCH EDITION HVAC" },
{ make: "KAWASAKI", model: "RIDGE XR HVAC" },
{ make: "KAWASAKI", model: "RIDGE PLATINUM RANCH EDITION HVAC " },
{ make: "KAWASAKI", model: "RIDGE ST HVAC " },
{ make: "KAWASAKI", model: "RIDGE XR CREW HVAC " },
{ make: "KAWASAKI", model: "RIDGE PLATINUM RANCH EDITION HVAC " },
{ make: "KAWASAKI", model: "RIDGE ST HVAC " },
{ make: "KAWASAKI", model: "RIDGE XR CREW HVAC " },
{ make: "KAWASAKI", model: "RIDGE XR CREW LIMITED HVAC " },
{ make: "KAWASAKI", model: "RIDGE XR DELUXE HVAC " },
{ make: "KAWASAKI", model: "RIDGE XR CREW RANCH EDITION HVAC" },
{ make: "KAWASAKI", model: "RIDGE XR CREW PLATINUM RANCH EDITION HVAC" },
{ make: "KAWASAKI", model: "RIDGE XR LIMITED HVAC" },
{ make: "KAWASAKI", model: "RIDGE XR RANCH EDITION HVAC" },
{ make: "KAWASAKI", model: "RIDGE XR PLATINUM RANCH EDITION HVAC" },
{ make: "KAWASAKI", model: "TERYX " },
{ make: "KAWASAKI", model: "TERYX 750" },
{ make: "KAWASAKI", model: "TERYX 750 FI" },
{ make: "KAWASAKI", model: "TERYX 750 FI 4X4" },
{ make: "KAWASAKI", model: "TERYX 750 FI 4X4 LE" },
{ make: "KAWASAKI", model: "TERYX 750 FI 4X4 SPORT" },
{ make: "KAWASAKI", model: "TERYX 750 LE" },
{ make: "KAWASAKI", model: "TERYX 800" },
{ make: "KAWASAKI", model: "TERYX 800 EPS" },
{ make: "KAWASAKI", model: "TERYX 800 EPS CAMO" },
{ make: "KAWASAKI", model: "TERYX 800 EPS LE" },
{ make: "KAWASAKI", model: "TERYX 800EPS LE" },
{ make: "KAWASAKI", model: "TERYX KRX 4 1000" },
{ make: "KAWASAKI", model: "TERYX KRX 4 1000 ES" },
{ make: "KAWASAKI", model: "TERYX KRX 4 1000 LE" },
{ make: "KAWASAKI", model: "TERYX KRX 4 1000 LIFTED EDITION " },
{ make: "KAWASAKI", model: "TERYX KRX 4 1000 SE" },
{ make: "KAWASAKI", model: "TERYX KRX1000" },
{ make: "KAWASAKI", model: "TERYX KRX1000 ES" },
{ make: "KAWASAKI", model: "TERYX KRX1000 ES SPECIAL EDITION" },
{ make: "KAWASAKI", model: "TERYX KRX1000 LE" },
{ make: "KAWASAKI", model: "TERYX KRX1000 SE" },
{ make: "KAWASAKI", model: "TERYX KRX1000 TRAIL EDITION" },
{ make: "KAWASAKI", model: "TERYX LE" },
{ make: "KAWASAKI", model: "TERYX S LE" },
{ make: "KAWASAKI", model: "TERYX S SE" },
{ make: "KAWASAKI", model: "TERYX4" },
{ make: "KAWASAKI", model: "TERYX4 800" },
{ make: "KAWASAKI", model: "TERYX4 800 CAMO" },
{ make: "KAWASAKI", model: "TERYX4 800 LE" },
{ make: "KAWASAKI", model: "TERYX4 800 SE" },
{ make: "KAWASAKI", model: "TERYX4 S LE " },
{ make: "KAWASAKI", model: "TERYX4 S SE" },
{ make: "KAWASAKI", model: "TERYX4 H2" },
{ make: "KAWASAKI", model: "TERYX H2" },
{ make: "KAWASAKI", model: "TERYX H2 DELUXE" },
{ make: "KAWASAKI", model: "TERYX H2 DELUXE ES" },
{ make: "KAWASAKI", model: "TERYX 5 H2" },
{ make: "KAWASAKI", model: "TERYX 5 H2 DELUXE" },
{ make: "KAWASAKI", model: "TERYX 5 H2 DELUXE ES" },
{ make: "KAWASAKI", model: "TERYX H2 DELUXE ES" },
{ make: "KAWASAKI", model: "BRUTE FORCE 300" },
{ make: "KAWASAKI", model: "BRUTE FORCE 650" },
{ make: "KAWASAKI", model: "BRUTE FORCE 650 4X4" },
{ make: "KAWASAKI", model: "BRUTE FORCE 650 4X4I" },
{ make: "KAWASAKI", model: "BRUTE FORCE 750" },
{ make: "KAWASAKI", model: "BRUTE FORCE 750 4X4I" },
{ make: "KAWASAKI", model: "BRUTE FORCE 750 4X4I EPS" },
{ make: "KAWASAKI", model: "BRUTE FORCE 750 EPS" },
{ make: "KAWASAKI", model: "BRUTE FORCE 750 EPS CAMO" },
{ make: "KAWASAKI", model: "BRUTE FORCE 750 EPS LE" },
{ make: "KAWASAKI", model: "KFX 50" },
{ make: "KAWASAKI", model: "KFX 90" },
{ make: "KAWASAKI", model: "KFX 400" },
{ make: "KAWASAKI", model: "KFX 450R" },
{ make: "KAWASAKI", model: "PRAIRIE 300" },
{ make: "KAWASAKI", model: "PRAIRIE 360" },
{ make: "KAWASAKI", model: "PRAIRIE 400" },
{ make: "KAWASAKI", model: "PRAIRIE 650" },
{ make: "KAWASAKI", model: "PRAIRIE 700" },
{ make: "KAWASAKI", model: "BAYOU 220" },
{ make: "KAWASAKI", model: "BAYOU 250" },
{ make: "KAWASAKI", model: "BAYOU 300" },
{ make: "KAWASAKI", model: "BAYOU 400" },
{ make: "KAWASAKI", model: "OTHER" },

 // BOBCAT

{ make: "BOBCAT", model: "2100" },
{ make: "BOBCAT", model: "2100S" },
{ make: "BOBCAT", model: "2200" },
{ make: "BOBCAT", model: "2200D" },
{ make: "BOBCAT", model: "2200G" },
{ make: "BOBCAT", model: "2300" },
{ make: "BOBCAT", model: "2400" },
{ make: "BOBCAT", model: "3400" },
{ make: "BOBCAT", model: "3400D" },
{ make: "BOBCAT", model: "3400G" },
{ make: "BOBCAT", model: "3400XL" },
{ make: "BOBCAT", model: "3400XD" },
{ make: "BOBCAT", model: "3450" },
{ make: "BOBCAT", model: "3600" },
{ make: "BOBCAT", model: "3650" },
{ make: "BOBCAT", model: "TOOLCAT 5600" },
{ make: "BOBCAT", model: "TOOLCAT 5610" },
{ make: "BOBCAT", model: "TOOLCAT UW53" },
{ make: "BOBCAT", model: "TOOLCAT UW56" },
{ make: "BOBCAT", model: "UV34" },
{ make: "BOBCAT", model: "UV34D" },
{ make: "BOBCAT", model: "UV34G" },
{ make: "BOBCAT", model: "UV34XLD" },
{ make: "BOBCAT", model: "UV34XLG" },
{ make: "BOBCAT", model: "UV34XL" },
{ make: "BOBCAT", model: "UV34XL DIESEL" },
{ make: "BOBCAT", model: "UV34XL GAS" },
{ make: "BOBCAT", model: "OTHER" },
  
 // CAN-AM

{ make: "CAN-AM", model: "COMMANDER 1000 X" },
{ make: "CAN-AM", model: "COMMANDER 1000R DPS" },
{ make: "CAN-AM", model: "COMMANDER DPS 700" },
{ make: "CAN-AM", model: "COMMANDER DPS 800R" },
{ make: "CAN-AM", model: "COMMANDER DPS 1000R" },
{ make: "CAN-AM", model: "COMMANDER LIMITED 1000" },
{ make: "CAN-AM", model: "COMMANDER LIMITED 1000R" },
{ make: "CAN-AM", model: "COMMANDER MAX 1000 DPS" },
{ make: "CAN-AM", model: "COMMANDER MAX DPS 1000R" },
{ make: "CAN-AM", model: "COMMANDER MAX LIMITED 1000R" },
{ make: "CAN-AM", model: "COMMANDER MAX XT 1000R" },
{ make: "CAN-AM", model: "COMMANDER MAX XT-P 1000R" },
{ make: "CAN-AM", model: "COMMANDER XT 700" },
{ make: "CAN-AM", model: "COMMANDER XT 1000" },
{ make: "CAN-AM", model: "COMMANDER XT 1000R" },
{ make: "CAN-AM", model: "COMMANDER XT-P 1000" },
{ make: "CAN-AM", model: "COMMANDER XT P 1000" },
{ make: "CAN-AM", model: "COMMANDER XT-P 1000R" },
{ make: "CAN-AM", model: "COMMANDER XT P 1000R" },
{ make: "CAN-AM", model: "DEFENDER 6X6 LIMITED " },
{ make: "CAN-AM", model: "DEFENDER 6X6 LIMITED HD10" },
{ make: "CAN-AM", model: "DEFENDER 6X6 LIMITED HD11" },
{ make: "CAN-AM", model: "DEFENDER 6X6 XT HD10" },
{ make: "CAN-AM", model: "DEFENDER 6X6 XT HD11" },
{ make: "CAN-AM", model: "DEFENDER HD5" },
{ make: "CAN-AM", model: "DEFENDER HD7" },
{ make: "CAN-AM", model: "DEFENDER HD7 DPS" },
{ make: "CAN-AM", model: "DEFENDER HD8" },
{ make: "CAN-AM", model: "DEFENDER HD8 DPS" },
{ make: "CAN-AM", model: "DEFENDER HD9" },
{ make: "CAN-AM", model: "DEFENDER HD9 DPS" },
{ make: "CAN-AM", model: "DEFENDER HD10" },
{ make: "CAN-AM", model: "DEFENDER HD10 DPS" },
{ make: "CAN-AM", model: "DEFENDER HD10 XT" },
{ make: "CAN-AM", model: "DEFENDER HD10 X MR" },
{ make: "CAN-AM", model: "DEFENDER LIMITED CAB HD10" },
{ make: "CAN-AM", model: "DEFENDER LIMITED HD10" },
{ make: "CAN-AM", model: "DEFENDER LIMITED HD11" },
{ make: "CAN-AM", model: "DEFENDER LONE STAR HD10" },
{ make: "CAN-AM", model: "DEFENDER LONE STAR HD11" },
{ make: "CAN-AM", model: "DEFENDER MAX HD7" },
{ make: "CAN-AM", model: "DEFENDER MAX HD7 DPS" },
{ make: "CAN-AM", model: "DEFENDER MAX HD8" },
{ make: "CAN-AM", model: "DEFENDER MAX HD8 DPS" },
{ make: "CAN-AM", model: "DEFENDER MAX HD9" },
{ make: "CAN-AM", model: "DEFENDER MAX HD9 DPS" },
{ make: "CAN-AM", model: "DEFENDER MAX HD10" },
{ make: "CAN-AM", model: "DEFENDER MAX HD10 DPS" },
{ make: "CAN-AM", model: "DEFENDER MAX HD10 XT" },
{ make: "CAN-AM", model: "DEFENDER MAX LIMITED HD10" },
{ make: "CAN-AM", model: "DEFENDER MAX LIMITED HD11" },
{ make: "CAN-AM", model: "DEFENDER MAX LONE STAR CAB HD11" },
{ make: "CAN-AM", model: "DEFENDER MAX LONE STAR HD10" },
{ make: "CAN-AM", model: "DEFENDER MAX LONE STAR HD11" },
{ make: "CAN-AM", model: "DEFENDER MAX XT HD9" },
{ make: "CAN-AM", model: "DEFENDER MAX XT HD10" },
{ make: "CAN-AM", model: "DEFENDER MAX XT HD11" },
{ make: "CAN-AM", model: "DEFENDER MAX XT HD11 CAB " },
{ make: "CAN-AM", model: "DEFENDER MAX X MR HD10" },
{ make: "CAN-AM", model: "DEFENDER MAX X MR HD11" },
{ make: "CAN-AM", model: "DEFENDER PRO HD10" },
{ make: "CAN-AM", model: "DEFENDER PRO LIMITED CAB HD10" },
{ make: "CAN-AM", model: "DEFENDER PRO LIMITED HD10" },
{ make: "CAN-AM", model: "DEFENDER PRO LONE STAR HD10" },
{ make: "CAN-AM", model: "DEFENDER PRO XT HD10" },
{ make: "CAN-AM", model: "DEFENDER PRO XT HD11" },
{ make: "CAN-AM", model: "DEFENDER X MR HD10" },
{ make: "CAN-AM", model: "DEFENDER X MR HD11" },
{ make: "CAN-AM", model: "DEFENDER XT HD7" },
{ make: "CAN-AM", model: "DEFENDER XT HD8" },
{ make: "CAN-AM", model: "DEFENDER XT HD9" },
{ make: "CAN-AM", model: "DEFENDER XT HD10" },
{ make: "CAN-AM", model: "DEFENDER XT HD10 CAB " },
{ make: "CAN-AM", model: "DEFENDER XT HD11" },
{ make: "CAN-AM", model: "DEFENDER XT HDT11 CAB " },
{ make: "CAN-AM", model: "MAVERICK 1000R" },
{ make: "CAN-AM", model: "MAVERICK 1000R DPS" },
{ make: "CAN-AM", model: "MAVERICK 1000R X MR" },
{ make: "CAN-AM", model: "MAVERICK 1000R X RS" },
{ make: "CAN-AM", model: "MAVERICK 1000R X XC" },
{ make: "CAN-AM", model: "MAVERICK MAX 1000R DPS" },
{ make: "CAN-AM", model: "MAVERICK MAX X DS 1000R TURBO" },
{ make: "CAN-AM", model: "MAVERICK MAX X DS TURBO R" },
{ make: "CAN-AM", model: "MAVERICK MAX X MR 1000R" },
{ make: "CAN-AM", model: "MAVERICK MAX X RS 1000R TURBO" },
{ make: "CAN-AM", model: "MAVERICK R" },
{ make: "CAN-AM", model: "MAVERICK R MAX X" },
{ make: "CAN-AM", model: "MEVERICK R MAX X RC" },
{ make: "CAN-AM", model: "MAVERICK R MAX X RC" },
{ make: "CAN-AM", model: "MAVERICK R MAX X RS" },
{ make: "CAN-AM", model: "MAVERICK R X" },
{ make: "CAN-AM", model: "MAVERICK R X RC" },
{ make: "CAN-AM", model: "MAVERICK R X RS" },
{ make: "CAN-AM", model: "MAVERICK R X RS SMART-SHOX" },
{ make: "CAN-AM", model: "MAVERICK SPORT" },
{ make: "CAN-AM", model: "MAVERICK SPORT DPS 1000" },
{ make: "CAN-AM", model: "MEVERICK SPORT DPS 1000R" },
{ make: "CAN-AM", model: "MAVERICK SPORT DPS 1000R" },
{ make: "CAN-AM", model: "MAVERICK SPORT MAX DPS 1000R" },
{ make: "CAN-AM", model: "MAVERICK SPORT X MR 1000R" },
{ make: "CAN-AM", model: "MAVERICK SPORT X RC 1000R    " },
{ make: "CAN-AM", model: "MAVERICK SPORT X XC 1000R" },
{ make: "CAN-AM", model: "MAVERICK TRAIL 1000" },
{ make: "CAN-AM", model: "MAVERICK TRAIL DPS 700" },
{ make: "CAN-AM", model: "MAVERICK TRAIL DPS 800" },
{ make: "CAN-AM", model: "MAVERICK TRAIL DPS 1000" },
{ make: "CAN-AM", model: "MAVERICK X DS 1000R TURBO" },
{ make: "CAN-AM", model: "MAVERICK X DS TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X MR 1000R" },
{ make: "CAN-AM", model: "MAVERICK X RS 1000R" },
{ make: "CAN-AM", model: "MAVERICK X RS TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X3 DS TURBO" },
{ make: "CAN-AM", model: "MAVERICK X3 DS TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X3 DS TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK X3 MAX DS TURBO" },
{ make: "CAN-AM", model: "MAVERICK X3 MAX DS TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X3 MAX DS TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK X3 MAX RS TURBO " },
{ make: "CAN-AM", model: "MAVERICK X3 MAX RS TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X3 MAX RS TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK X3 MAX X DS TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X3 MAX X DS TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK X3 MAX X MR TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK X3 MAX X RC TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK X3 MAX X RS TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X3 MAX X RS TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK X3 RS TURBO" },
{ make: "CAN-AM", model: "MAVERICK X3 RS TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X3 RS TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK X3 X DS TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X3 X DS TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK X3 X MR TURBO" },
{ make: "CAN-AM", model: "MAVERICK X3 X MR TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X3 X MR TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK X3 X RC TURBO" },
{ make: "CAN-AM", model: "MAVERICK X3 X RC TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X3 X RC TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK X3 X RS TURBO" },
{ make: "CAN-AM", model: "MAVERICK X3 X RS TURBO R" },
{ make: "CAN-AM", model: "MAVERICK X3 X RS TURBO RR" },
{ make: "CAN-AM", model: "MAVERICK XC DPS 1000R" },
{ make: "CAN-AM", model: "TRAXTER HD8T" },
{ make: "CAN-AM", model: "TRAXTER HD9" },
{ make: "CAN-AM", model: "TRAXTER HD10" },
{ make: "CAN-AM", model: "TRAXTER MAX HD10" },
{ make: "CAN-AM", model: "TRAXTER PRO HD10" },
{ make: "CAN-AM", model: "TRAXTER XU HD10" },
{ make: "CAN-AM", model: "TRAXTER XU MAX HD10" },
{ make: "CAN-AM", model: "TRAXTER XU T HD10" },
{ make: "CAN-AM", model: "OTHER" },

  
 // CF MOTO

{ make: "CF MOTO", model: "UFORCE 600" },
{ make: "CF MOTO", model: "UFORCE 600 EPS" },
{ make: "CF MOTO", model: "UFORCE 600 TOURING" },
{ make: "CF MOTO", model: "UFORCE 800" },
{ make: "CF MOTO", model: "UFORCE 800 EPS" },
{ make: "CF MOTO", model: "UFORCE 800XL " },
{ make: "CF MOTO", model: "UFORCE 1000" },
{ make: "CF MOTO", model: "UFORCE 1000 EPS" },
{ make: "CF MOTO", model: "UFORCE 1000 XL " },
{ make: "CF MOTO", model: "UFORCE 1000 XL EPS" },
{ make: "CF MOTO", model: "UFORCE U6 EV" },
{ make: "CF MOTO", model: "UFORCE U10 PRO " },
{ make: "CF MOTO", model: "UFORCE U10 XL PRO " },
{ make: "CF MOTO", model: "UFORCE U10 XL PRO HIGHLAND " },
{ make: "CF MOTO", model: "UFORCE U10 PRO HIGHLAND" },
{ make: "CF MOTO", model: "ZFORCE 500" },
{ make: "CF MOTO", model: "ZFORCE 500 TRAIL" },
{ make: "CF MOTO", model: "ZFORCE 600" },
{ make: "CF MOTO", model: "ZFORCE 800" },
{ make: "CF MOTO", model: "ZFORCE 800 EPS" },
{ make: "CF MOTO", model: "ZFORCE 800 EPS TRAIL " },
{ make: "CF MOTO", model: "ZFORCE 800 EX" },
{ make: "CF MOTO", model: "ZFORCE 800 EX EPS" },
{ make: "CF MOTO", model: "ZFORCE 800 TRAIL " },
{ make: "CF MOTO", model: "ZFORCE 950" },
{ make: "CF MOTO", model: "ZFORCE 950 H.O. EX" },
{ make: "CF MOTO", model: "ZFORCE 950 SPORT" },
{ make: "CF MOTO", model: "ZFORCE 950 SPORT 4 " },
{ make: "CF MOTO", model: "ZFORCE 950 TRAIL " },
{ make: "CF MOTO", model: "ZFORCE 950 TRAIL G2" },
{ make: "CF MOTO", model: "ZFORCE 950 SPORT G2" },
{ make: "CF MOTO", model: "ZFORCE 950 SPORT R" },
{ make: "CF MOTO", model: "ZFORCE 950 SPORT R 4" },
{ make: "CF MOTO", model: "ZFORCE 950 H.O. SPORT" },
{ make: "CF MOTO", model: "ZFORCE 1000" },
{ make: "CF MOTO", model: "ZFORCE 1000 SPORT" },
{ make: "CF MOTO", model: "ZFORCE 1000 R SPORT" },
{ make: "CF MOTO", model: "ZFORCE 1000 R 4" },
{ make: "CF MOTO", model: "OTHER" },

  // TORO

{ make: "TORO", model: "WORKMAN 1100" },
{ make: "TORO", model: "WORKMAN 1110" },
{ make: "TORO", model: "WORKMAN 2100" },
{ make: "TORO", model: "WORKMAN 2110" },
{ make: "TORO", model: "WORKMAN 3100" },
{ make: "TORO", model: "WORKMAN 3200" },
{ make: "TORO", model: "WORKMAN 3300" },
{ make: "TORO", model: "WORKMAN 3300D" },
{ make: "TORO", model: "WORKMAN 4200" },
{ make: "TORO", model: "WORKMAN 4300D" },
{ make: "TORO", model: "WORKMAN 4300" },
{ make: "TORO", model: "WORKMAN E2605" },
{ make: "TORO", model: "WORKMAN GTX" },
{ make: "TORO", model: "WORKMAN GTX EFI" },
{ make: "TORO", model: "WORKMAN GTX ELECTRIC" },
{ make: "TORO", model: "WORKMAN HD" },
{ make: "TORO", model: "WORKMAN HDX" },
{ make: "TORO", model: "WORKMAN HDX 4WD" },
{ make: "TORO", model: "WORKMAN HDX AUTO" },
{ make: "TORO", model: "WORKMAN HDX-D" },
{ make: "TORO", model: "WORKMAN HDXD" },
{ make: "TORO", model: "WORKMAN HDX-D 4WD" },
{ make: "TORO", model: "WORKMAN MD" },
{ make: "TORO", model: "WORKMAN MDE" },
{ make: "TORO", model: "WORKMAN MDX" },
{ make: "TORO", model: "WORKMAN MDX-D" },
{ make: "TORO", model: "WORKMAN UTX 2-PASS" },
{ make: "TORO", model: "WORKMAN UTX 4-PASS" },
{ make: "TORO", model: "WORKMAN UTX DIESEL 2-PASS" },
{ make: "TORO", model: "WORKMAN UTX DIESEL 4-PASS" },
{ make: "TORO", model: "WORKMAN UTX GAS 2-PASS" },
{ make: "TORO", model: "WORKMAN UTX GAS 4-PASS" },
{ make: "TORO", model: "WORKMAN UTX LITHIUM 2-PASS" },
{ make: "TORO", model: "WORKMAN UTX LITHIUM 4-PASS" },
{ make: "TORO", model: "OTHER" },
  
 // CLUB CAR

{ make: "CLUB CAR", model: "411" },
{ make: "CLUB CAR", model: "1200" },
{ make: "CLUB CAR", model: "CARRYALL 1" },
{ make: "CLUB CAR", model: "CARRYALL 2" },
{ make: "CLUB CAR", model: "CARRYALL 2 PLUS" },
{ make: "CLUB CAR", model: "CARRYALL 6" },
{ make: "CLUB CAR", model: "CARRYALL 252" },
{ make: "CLUB CAR", model: "CARRYALL 272" },
{ make: "CLUB CAR", model: "CARRYALL 300" },
{ make: "CLUB CAR", model: "CARRYALL 500" },
{ make: "CLUB CAR", model: "CARRYALL 502" },
{ make: "CLUB CAR", model: "CARRYALL 550" },
{ make: "CLUB CAR", model: "CARRYALL 700" },
{ make: "CLUB CAR", model: "CARRYALL 710 LSV" },
{ make: "CLUB CAR", model: "CARRYALL 1000" },
{ make: "CLUB CAR", model: "CARRYALL 1000 LSV" },
{ make: "CLUB CAR", model: "CARRYALL 1500" },
{ make: "CLUB CAR", model: "CARRYALL 1500 2WD" },
{ make: "CLUB CAR", model: "CARRYALL 1500 4WD" },
{ make: "CLUB CAR", model: "CARRYALL 1700" },
{ make: "CLUB CAR", model: "CARRYALL 1700 4WD" },
{ make: "CLUB CAR", model: "CARYALL 100" },
{ make: "CLUB CAR", model: "CARRYALL 100" },
{ make: "CLUB CAR", model: "CARRYALL 411" },
{ make: "CLUB CAR", model: "CARRYALL 700" },
{ make: "CLUB CAR", model: "CARRYALL 700 LSV" },
{ make: "CLUB CAR", model: "URBAN L7E" },
{ make: "CLUB CAR", model: "URBAN LSV" },
{ make: "CLUB CAR", model: "URBAN N1" },
{ make: "CLUB CAR", model: "XRT 800" },
{ make: "CLUB CAR", model: "XRT 810" },
{ make: "CLUB CAR", model: "XRT 850" },
{ make: "CLUB CAR", model: "XRT 900" },
{ make: "CLUB CAR", model: "XRT 950" },
{ make: "CLUB CAR", model: "XRT 1200" },
{ make: "CLUB CAR", model: "XRT 1500" },
{ make: "CLUB CAR", model: "XRT 1500 2WD" },
{ make: "CLUB CAR", model: "XRT 1500 4WD" },
{ make: "CLUB CAR", model: "XRT 1550" },
{ make: "CLUB CAR", model: "XRT 1550 SE" },
{ make: "CLUB CAR", model: "OTHER" },

  // HONDA

{ make: "HONDA", model: "BIG RED" },
{ make: "HONDA", model: "MUV700" },
{ make: "HONDA", model: "PIONEER 500" },
{ make: "HONDA", model: "PIONEER 520" },
{ make: "HONDA", model: "PIONEER 700" },
{ make: "HONDA", model: "PIONEER 700 DELUXE" },
{ make: "HONDA", model: "PIONEER 700 FOREST " },
{ make: "HONDA", model: "PIONEER 700-4" },
{ make: "HONDA", model: "PIONEER 700-4 DELUXE" },
{ make: "HONDA", model: "PIONEER 700-4 FOREST" },
{ make: "HONDA", model: "PIONEER 1000" },
{ make: "HONDA", model: "PIONEER 1000 DELUXE" },
{ make: "HONDA", model: "PIONEER 1000 EPS" },
{ make: "HONDA", model: "PIONEER 1000 FOREST " },
{ make: "HONDA", model: "PIONEER 1000 LE" },
{ make: "HONDA", model: "PIONEER 1000 TRAIL" },
{ make: "HONDA", model: "PIONEER 1000-5" },
{ make: "HONDA", model: "PIONEER 1000-5 DELUXE" },
{ make: "HONDA", model: "PIONEER 1000-5 LE" },
{ make: "HONDA", model: "PIONEER 1000-5 FOREST" },
{ make: "HONDA", model: "PIONEER 1000-5 TRAIL" },
{ make: "HONDA", model: "PIONEER 1000-5 SPECIAL EDITION " },
{ make: "HONDA", model: "PIONEER 1000-5TRAIL SPECIAL EDITION" },
{ make: "HONDA", model: "PIONEER 1000-6 DELUXE CREW" },
{ make: "HONDA", model: "TALON 1000R" },
{ make: "HONDA", model: "TALON 1000R FOX LIVE VALVE" },
{ make: "HONDA", model: "TALON 1000R-4 FOX LIVE VALVE " },
{ make: "HONDA", model: "TALON 1000RS" },
{ make: "HONDA", model: "TALON 1000R SPECIAL EDITION" },
{ make: "HONDA", model: "TALON 1000X" },
{ make: "HONDA", model: "TALON 1000X FOX LIVE VALVE" },
{ make: "HONDA", model: "TALON 1000X-4" },
{ make: "HONDA", model: "TALON 1000X-4 FOX LIVE VALVE" },
{ make: "HONDA", model: "TALON 1000X-4 SPECIAL EDITION" },
{ make: "HONDA", model: "TALON 1000XS" },
{ make: "HONDA", model: "TALON 1000XS-4" },
{ make: "HONDA", model: "OTHER" },

 // AMERICAN LANDMASTER

{ make: "AMERICAN LANDMASTER", model: "AMP 4X2" },
{ make: "AMERICAN LANDMASTER", model: "AMP 4X4" },
{ make: "AMERICAN LANDMASTER", model: "AMP CREW 4X4" },
{ make: "AMERICAN LANDMASTER", model: "AMD HD" },
{ make: "AMERICAN LANDMASTER", model: "EV 4X2" },
{ make: "AMERICAN LANDMASTER", model: "EV 4X4" },
{ make: "AMERICAN LANDMASTER", model: "L4 4X2" },
{ make: "AMERICAN LANDMASTER", model: "L4 4X4" },
{ make: "AMERICAN LANDMASTER", model: "L5" },
{ make: "AMERICAN LANDMASTER", model: "L5W" },
{ make: "AMERICAN LANDMASTER", model: "L7" },
{ make: "AMERICAN LANDMASTER", model: "L7 UNTAMED" },
{ make: "AMERICAN LANDMASTER", model: "L7 CREW " },
{ make: "AMERICAN LANDMASTER", model: "L7X" },
{ make: "AMERICAN LANDMASTER", model: "LS350" },
{ make: "AMERICAN LANDMASTER", model: "LS450" },
{ make: "AMERICAN LANDMASTER", model: "LS550" },
{ make: "AMERICAN LANDMASTER", model: "LS670" },
{ make: "AMERICAN LANDMASTER", model: "N6" },
{ make: "AMERICAN LANDMASTER", model: "N7" },
{ make: "AMERICAN LANDMASTER", model: "N7 CREW" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR 350" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR 400" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR 450" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR 550" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR 670" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR CREW 4X4" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR LS350" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR LS450" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR LS550" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR LS670" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR LSC2" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR LSC4" },
{ make: "AMERICAN LANDMASTER", model: "LANDSTAR LSC4 4X4" },
{ make: "AMERICAN LANDMASTER", model: "OTHER" },

  // ARCTIC CAT

{ make: "ARCTIC CAT", model: "700XT" },
{ make: "ARCTIC CAT", model: "HD500XT" },
{ make: "ARCTIC CAT", model: "HDX500 XT" },
{ make: "ARCTIC CAT", model: "HDX700 EFI" },
{ make: "ARCTIC CAT", model: "HDX 700 XT" },
{ make: "ARCTIC CAT", model: "HDX 700 CREW XT" },
{ make: "ARCTIC CAT", model: "PROWLER 500 HDX" },
{ make: "ARCTIC CAT", model: "PROWLER 500 HDX XT" },
{ make: "ARCTIC CAT", model: "PROWLER 550" },
{ make: "ARCTIC CAT", model: "PROWLER 550 XT" },
{ make: "ARCTIC CAT", model: "PROWLER 650" },
{ make: "ARCTIC CAT", model: "PROWLER 650 H1" },
{ make: "ARCTIC CAT", model: "PROWLER 650 XT" },
{ make: "ARCTIC CAT", model: "PROWLER 700" },
{ make: "ARCTIC CAT", model: "PROWLER 700 HDX" },
{ make: "ARCTIC CAT", model: "PROWLER 700 XT" },
{ make: "ARCTIC CAT", model: "PROWLER 700 XTX" },
{ make: "ARCTIC CAT", model: "PROWLER 700 XTX EFI" },
{ make: "ARCTIC CAT", model: "PROWLER 1000 XT" },
{ make: "ARCTIC CAT", model: "PROWLER 1000 XTZ" },
{ make: "ARCTIC CAT", model: "PROWLER 1000 XTZPROWLER PRO " },
{ make: "ARCTIC CAT", model: "PROWLER PRO " },
{ make: "ARCTIC CAT", model: "PROWLER PRO CREW " },
{ make: "ARCTIC CAT", model: "PROWLER PRO CREW RANCH" },
{ make: "ARCTIC CAT", model: "PROWLER PRO CREW XT" },
{ make: "ARCTIC CAT", model: "PROWLER PRO EPS" },
{ make: "ARCTIC CAT", model: "PROWLER PRO RANCH" },
{ make: "ARCTIC CAT", model: "PROWLER PRO XT" },
{ make: "ARCTIC CAT", model: "PROWLER XT" },
{ make: "ARCTIC CAT", model: "WILDCAT" },
{ make: "ARCTIC CAT", model: "WILDCAT 4" },
{ make: "ARCTIC CAT", model: "WILDCAT 4X" },
{ make: "ARCTIC CAT", model: "WILDCAT 700" },
{ make: "ARCTIC CAT", model: "WILDCAT 1000" },
{ make: "ARCTIC CAT", model: "WILDCAT SPORT" },
{ make: "ARCTIC CAT", model: "WILDCAT SPORT XT" },
{ make: "ARCTIC CAT", model: "WILDCAT TRAIL" },
{ make: "ARCTIC CAT", model: "WILDCAT TRAIL XT" },
{ make: "ARCTIC CAT", model: "WILDCAT X" },
{ make: "ARCTIC CAT", model: "WILDCAT XX" },
{ make: "ARCTIC CAT", model: "WILDCAT XX LTD" },
{ make: "ARCTIC CAT", model: "WILDCAT XX SE" },
{ make: "ARCTIC CAT", model: "WILDCAT XX XT" },
{ make: "ARCTIC CAT", model: "OTHER" },

  // ARGO

{ make: "ARGO", model: "750HDI" },
{ make: "ARGO", model: "AURORA 800SX" },
{ make: "ARGO", model: "AURORA 800 SX HUNT MASTER" },
{ make: "ARGO", model: "AURORA 850" },
{ make: "ARGO", model: "AURORA 850SX-R" },
{ make: "ARGO", model: "AURORA 850 SX" },
{ make: "ARGO", model: "AURORA 850 SX HUNT MASTER" },
{ make: "ARGO", model: "AURORA 850 SX-R HUNT MASTER" },
{ make: "ARGO", model: "AURORA 950" },
{ make: "ARGO", model: "AURORA 950 SX" },
{ make: "ARGO", model: "AURORA 950 SX HUNT MASTER" },
{ make: "ARGO", model: "AURORA 950 SX-R" },
{ make: "ARGO", model: "AURORA 950 BIGFOOT MX8" },
{ make: "ARGO", model: "AURORA 950 SAR 8X8" },
{ make: "ARGO", model: "AURORA PRO 950 XT 8X8" },
{ make: "ARGO", model: "AVENGER 8X8 750 EFI " },
{ make: "ARGO", model: "AVENGER 8X8 STX" },
{ make: "ARGO", model: "AVENGER 8X8 STR" },
{ make: "ARGO", model: "AVENGER 8X8 HUNT MASTER" },
{ make: "ARGO", model: "AVENGER 750EFI" },
{ make: "ARGO", model: "AVENGER 700 8X8" },
{ make: "ARGO", model: "AVENGER 750 8X8" },
{ make: "ARGO", model: "AVENGER 800 8X8" },
{ make: "ARGO", model: "CONQUEST 8X8" },
{ make: "ARGO", model: "CONQUEST 8X8 OUTFITTER" },
{ make: "ARGO", model: "CONQUEST 8X8 PRO" },
{ make: "ARGO", model: "CONQUEST 8X8 XT" },
{ make: "ARGO", model: "FRONTIER 650HO 8X8 SCOUT " },
{ make: "ARGO", model: "FRONTIER 650 6X6" },
{ make: "ARGO", model: "FRONTIER 650 8X8" },
{ make: "ARGO", model: "FRONTIER 700 SCOUT " },
{ make: "ARGO", model: "FRONTIER 700 6X6" },
{ make: "ARGO", model: "FRONTIER 700 8X8" },
{ make: "ARGO", model: "FRONTIER 700 SCOUT 6X6" },
{ make: "ARGO", model: "FRONTIER 700 SCOUT 8X8" },
{ make: "ARGO", model: "FRONTIER PRO 700 XT 6X6" },
{ make: "ARGO", model: "FRONTIER PRO 700 XT 8X8" },
{ make: "ARGO", model: "MAGNUM XF 500 LE" },
{ make: "ARGO", model: "MAGNUM XF 500" },
{ make: "ARGO", model: "MAGNUM XF 500 EPS" },
{ make: "ARGO", model: "MAGNUM XF 500 LE EPS" },
{ make: "ARGO", model: "SASQUATCH XTX" },
{ make: "ARGO", model: "XTI" },
{ make: "ARGO", model: "XTV 6X6" },
{ make: "ARGO", model: "XTV 8X8" },
{ make: "ARGO", model: "BIGFOOT 6X6" },
{ make: "ARGO", model: "BIGFOOT 8X8" },
{ make: "ARGO", model: "RESPONSE 8X8" },
{ make: "ARGO", model: "VANGUARD 6X6" },
{ make: "ARGO", model: "VANGUARD 8X8" },
{ make: "ARGO", model: "OTHER" },

 // BAD BOY

{ make: "BAD BOY", model: "BANDIT 550" },
{ make: "BAD BOY", model: "BANDIT 750" },
{ make: "BAD BOY", model: "RECOIL" },
{ make: "BAD BOY", model: "RECOIL IS" },
{ make: "BAD BOY", model: "RECOIL 4X4" },
{ make: "BAD BOY", model: "RECOIL IS CREW" },
{ make: "BAD BOY", model: "RECOIL CREW 4X4" },
{ make: "BAD BOY", model: "AMBUSH" },
{ make: "BAD BOY", model: "AMBUSH IS" },
{ make: "BAD BOY", model: "AMBUSH IS 4X4" },
{ make: "BAD BOY", model: "AMBUSH IS CREW" },
{ make: "BAD BOY", model: "AMBUSH IS CREW 4X4" },
{ make: "BAD BOY", model: "STAMPEDE" },
{ make: "BAD BOY", model: "STAMPEDE 900" },
{ make: "BAD BOY", model: "STAMPEDE 900 EPS" },
{ make: "BAD BOY", model: "STAMPEDE 900 4X4" },
{ make: "BAD BOY", model: "STAMPEDE 900 4X4 EPS" },
{ make: "BAD BOY", model: "STAMPEDE XTR" },
{ make: "BAD BOY", model: "STAMPEDE XTR EPS" },
{ make: "BAD BOY", model: "STAMPEDE 4" },
{ make: "BAD BOY", model: "STAMPEDE 4 EPS" },
{ make: "BAD BOY", model: "STAMPEDE 4X4" },
{ make: "BAD BOY", model: "STAMPEDE 4X4 EPS" },
{ make: "BAD BOY", model: "OTHER" },

  // BENNCHE

{ make: "BENNCHE", model: "TBOSS 420" },
{ make: "BENNCHE", model: "TBOSS 500" },
{ make: "BENNCHE", model: "TBOSS 550" },
{ make: "BENNCHE", model: "TBOSS 560" },
{ make: "BENNCHE", model: "TBOSS 750" },
{ make: "BENNCHE", model: "TBOSS 750 CREW" },
{ make: "BENNCHE", model: "TBOSS 750X" },
{ make: "BENNCHE", model: "TBOSS 760" },
{ make: "BENNCHE", model: "TBOSS 760 CREW" },
{ make: "BENNCHE", model: "COWBOY 250" },
{ make: "BENNCHE", model: "COWBOY 400" },
{ make: "BENNCHE", model: "COWBOY 500" },
{ make: "BENNCHE", model: "COWBOY 700" },
{ make: "BENNCHE", model: "GRAY WOLF 200" },
{ make: "BENNCHE", model: "GRAY WOLF 400" },
{ make: "BENNCHE", model: "GRAY WOLF 500" },
{ make: "BENNCHE", model: "GRAY WOLF 700" },
{ make: "BENNCHE", model: "SPIRE 250" },
{ make: "BENNCHE", model: "SPIRE 800" },
{ make: "BENNCHE", model: "WARRIOR 800" },
{ make: "BENNCHE", model: "OTHER" },

  // CORVUS

{ make: "CORVUS", model: "TERRAIN DX4" },
{ make: "CORVUS", model: "TERRAIN DX4 CAB" },
{ make: "CORVUS", model: "TERRAION DX4 PRO " },
{ make: "CORVUS", model: "TERRAIN DX4 PRO" },
{ make: "CORVUS", model: "TERRAIN DX4 EPS" },
{ make: "CORVUS", model: "TERRAIN DX4 CAB EPS" },
{ make: "CORVUS", model: "TERRAIN DX4 PRO EPS" },
{ make: "CORVUS", model: "TERRAIN EX4" },
{ make: "CORVUS", model: "TERRAIN EX4 EPS" },
{ make: "CORVUS", model: "TERRAIN EX4 CAB" },
{ make: "CORVUS", model: "TERRAIN EX4 PRO" },
{ make: "CORVUS", model: "TERRAIN EX4 PRO EPS" },
{ make: "CORVUS", model: "TERRAIN EX4 PRO CAB" },
{ make: "CORVUS", model: "TERRAIN EX4 PRO CAB EPS" },
{ make: "CORVUS", model: "TERRAIN EX4 CAB EPS" },
{ make: "CORVUS", model: "OTHER" },

 // HISUN

{ make: "HISUN", model: "AXIS 700" },
{ make: "HISUN", model: "AXIS 500" },
{ make: "HISUN", model: "AXIS 750" },
{ make: "HISUN", model: "HS400" },
{ make: "HISUN", model: "HS500" },
{ make: "HISUN", model: "HS700" },
{ make: "HISUN", model: "HS750" },
{ make: "HISUN", model: "HS1000" },
{ make: "HISUN", model: "SECTOR 250" },
{ make: "HISUN", model: "SECTOR 450" },
{ make: "HISUN", model: "SECTOR 550" },
{ make: "HISUN", model: "SECTOR 550 EPS" },
{ make: "HISUN", model: "SECTOR 750" },
{ make: "HISUN", model: "SECTOR 750 EPS" },
{ make: "HISUN", model: "SECTOR 750 CREW" },
{ make: "HISUN", model: "SECTOR 750 CREW EPS" },
{ make: "HISUN", model: "SECTOR 1000" },
{ make: "HISUN", model: "SECTOR 1000 EPS" },
{ make: "HISUN", model: "SECTOR 1000 CREW EPS" },
{ make: "HISUN", model: "SECTOR E1" },
{ make: "HISUN", model: "SECTOR E1 LITHIUM" },
{ make: "HISUN", model: "STRIKE 250" },
{ make: "HISUN", model: "STRIKE 550" },
{ make: "HISUN", model: "STRIKE 750" },
{ make: "HISUN", model: "STRIKE 1000" },
{ make: "HISUN", model: "VECTOR 500" },
{ make: "HISUN", model: "VECTOR 700" },
{ make: "HISUN", model: "VECTOR 750" },
{ make: "HISUN", model: "VECTOR 1000" },
{ make: "HISUN", model: "OTHER" },

 // GREENWORKS

{ make: "GREENWORKS", model: "CU400W" },
{ make: "GREENWORKS", model: "CU500SB" },
{ make: "GREENWORKS", model: "CU800SB" },
{ make: "GREENWORKS", model: "CU800SC" },
{ make: "GREENWORKS", model: "CU800W" },
{ make: "GREENWORKS", model: "CU400S" },
{ make: "GREENWORKS", model: "CU500S" },
{ make: "GREENWORKS", model: "CU500W" },
{ make: "GREENWORKS", model: "OTHER" },

 // GRAVELY

{ make: "GRAVELY", model: "ATLAS JSV 3400SD" },
{ make: "GRAVELY", model: "ATLAS JSV 3400" },
{ make: "GRAVELY", model: "ATLAS JSV 3400 EFI" },
{ make: "GRAVELY", model: "ATLAS JSV 3400SD DIESEL" },
{ make: "GRAVELY", model: "ATLAS JSV 6400" },
{ make: "GRAVELY", model: "ATLAS JSV 6400 EFI" },
{ make: "GRAVELY", model: "ATLAS JSV 6400 CREW" },
{ make: "GRAVELY", model: "ATLAS JSV 6400D" },
{ make: "GRAVELY", model: "ATLAS JSV3400" },
{ make: "GRAVELY", model: "TREKER 440RX" },
{ make: "GRAVELY", model: "TREKER 420" },
{ make: "GRAVELY", model: "TREKER 4200" },
{ make: "GRAVELY", model: "TREKER 440" },
{ make: "GRAVELY", model: "TREKER 4410" },
{ make: "GRAVELY", model: "TREKER 4420" },
{ make: "GRAVELY", model: "TREKER 4420D" },
{ make: "GRAVELY", model: "TREKER 4440" },
{ make: "GRAVELY", model: "TREKER 4470" },
{ make: "GRAVELY", model: "TREKER 6400" },
{ make: "GRAVELY", model: "OTHER" },

  // E-Z-GO

{ make: "E-Z-GO", model: "GXT7" },
{ make: "E-Z-GO", model: "GXT800" },
{ make: "E-Z-GO", model: "GXT1000" },
{ make: "E-Z-GO", model: "GXT1500" },
{ make: "E-Z-GO", model: "MPT800" },
{ make: "E-Z-GO", model: "MPT1000" },
{ make: "E-Z-GO", model: "MPT1000E" },
{ make: "E-Z-GO", model: "MPT1200" },
{ make: "E-Z-GO", model: "MPT1200G" },
{ make: "E-Z-GO", model: "MPT1200E" },
{ make: "E-Z-GO", model: "MPT1500" },
{ make: "E-Z-GO", model: "TERRAIN 250" },
{ make: "E-Z-GO", model: "TERRAIN 500" },
{ make: "E-Z-GO", model: "TERRAIN 1000" },
{ make: "E-Z-GO", model: "TERRAIN 1500" },
{ make: "E-Z-GO", model: "TERRAIN 250 ELECTRIC" },
{ make: "E-Z-GO", model: "TERRAIN 250 GAS" },
{ make: "E-Z-GO", model: "TERRAIN 500 ELECTRIC" },
{ make: "E-Z-GO", model: "TERRAIN 500 GAS" },
{ make: "E-Z-GO", model: "TERRAIN 1000 GAS" },
{ make: "E-Z-GO", model: "TERRAIN 1500 GAS" },
{ make: "E-Z-GO", model: "EXPRESS S4" },
{ make: "E-Z-GO", model: "EXPRESS S4 ELITE" },
{ make: "E-Z-GO", model: "EXPRESS S4 GAS" },
{ make: "E-Z-GO", model: "EXPRESS S6" },
{ make: "E-Z-GO", model: "EXPRESS S6 ELITE" },
{ make: "E-Z-GO", model: "EXPRESS S6 GAS" },
{ make: "E-Z-GO", model: "EXPRESS L6" },
{ make: "E-Z-GO", model: "EXPRESS L6 ELITE" },
{ make: "E-Z-GO", model: "EXPRESS L6 GAS" },
{ make: "E-Z-GO", model: "FREEDOM TXT" },
{ make: "E-Z-GO", model: "FREEDOM RXV" },
{ make: "E-Z-GO", model: "TXT" },
{ make: "E-Z-GO", model: "RXV" },
{ make: "E-Z-GO", model: "HAULER 800" },
{ make: "E-Z-GO", model: "HAULER 800X" },
{ make: "E-Z-GO", model: "HAULER 1000" },
{ make: "E-Z-GO", model: "HAULER 1200" },
{ make: "E-Z-GO", model: "HAULER PRO" },
{ make: "E-Z-GO", model: "HAULER PRO-X" },
{ make: "E-Z-GO", model: "ST SPORT" },
{ make: "E-Z-GO", model: "ST 350" },
{ make: "E-Z-GO", model: "ST 400" },
{ make: "E-Z-GO", model: "ST 480" },
{ make: "E-Z-GO", model: "ST 4X4" },
{ make: "E-Z-GO", model: "OTHER" },

  // CUB CADET

{ make: "CUB CADET", model: "BIG COUNTRY " },
{ make: "CUB CADET", model: "BIG COUNTRY 4X2" },
{ make: "CUB CADET", model: "BIG COUNTRY 4X4" },
{ make: "CUB CADET", model: "BIG COUNTRY 6X4" },
{ make: "CUB CADET", model: "CHALLENGER 400" },
{ make: "CUB CADET", model: "CHALLENGER 400 4X4" },
{ make: "CUB CADET", model: "CHALLENGER 400LX" },
{ make: "CUB CADET", model: "CHALLENGER 500" },
{ make: "CUB CADET", model: "CHALLENGER 550" },
{ make: "CUB CADET", model: "CHALLENGER 700" },
{ make: "CUB CADET", model: "CHALLENGER 700 4X4" },
{ make: "CUB CADET", model: "CHALLENGER 750" },
{ make: "CUB CADET", model: "CHALLENGER 750EPS" },
{ make: "CUB CADET", model: "CHALLENGER 750 CREW" },
{ make: "CUB CADET", model: "CHALLENGER 750 EPS CREW" },
{ make: "CUB CADET", model: "CHALLENGER M750 EPS" },
{ make: "CUB CADET", model: "CHALLENGER M550" },
{ make: "CUB CADET", model: "CHALLENGER MX 750" },
{ make: "CUB CADET", model: "CHALLENGER MX 750 EPS" },
{ make: "CUB CADET", model: "VOLUNTEER" },
{ make: "CUB CADET", model: "VOLUNTEER 4X2" },
{ make: "CUB CADET", model: "VOLUNTEER 4X4" },
{ make: "CUB CADET", model: "VOLUNTEER 4X4 EFI" },
{ make: "CUB CADET", model: "VOLUNTEER 4X4D" },
{ make: "CUB CADET", model: "VOLUNTEER 4X4D EFI" },
{ make: "CUB CADET", model: "VOLUNTEER WT" },
{ make: "CUB CADET", model: "VOLUNTEER WT CAB" },
{ make: "CUB CADET", model: "VOLUNTEER WT EFI" },
{ make: "CUB CADET", model: "VOLUNTEER WT DIESEL" },
{ make: "CUB CADET", model: "OTHER" },

  // HUNTVE

{ make: "HUNTVE", model: "GAME CHANGER " },
{ make: "HUNTVE", model: "GAME CHANGER ELECTRIC" },
{ make: "HUNTVE", model: "GAME CHANGER 4X4" },
{ make: "HUNTVE", model: "GAME CHANGER 4X4 CREW" },
{ make: "HUNTVE", model: "GAME CHANGER GAS" },
{ make: "HUNTVE", model: "GAME CHANGER DIESEL" },
{ make: "HUNTVE", model: "TERLINGUA" },
{ make: "HUNTVE", model: "TERLINGUA 4X4" },
{ make: "HUNTVE", model: "TERLINGUA CREW" },
{ make: "HUNTVE", model: "SWITCHBACK" },
{ make: "HUNTVE", model: "SWITCHBACK 4X4" },
{ make: "HUNTVE", model: "OTHER" },

// IR

{ make: "IR", model: "IRET13" },
{ make: "IR", model: "OTHER" },

// INTIMIDATOR

{ make: "INTIMIDATOR", model: "CLASSIC 750" },
{ make: "INTIMIDATOR", model: "CLASSIC 1000" },
{ make: "INTIMIDATOR", model: "CLASSIC CREW 750" },
{ make: "INTIMIDATOR", model: "CLASSIC CREW 1000" },
{ make: "INTIMIDATOR", model: "FRX" },
{ make: "INTIMIDATOR", model: "GC1K TGB 1000" },
{ make: "INTIMIDATOR", model: "GC1K TGB 1000 STAGE 1" },
{ make: "INTIMIDATOR", model: "GC1K TGB STAGE 2" },
{ make: "INTIMIDATOR", model: "GC1K TGB 1000 STAGE 3" },
{ make: "INTIMIDATOR", model: "GC1K CREW TGB 1000" },
{ make: "INTIMIDATOR", model: "GC1K CREW TGB 1000 STAGE 1" },
{ make: "INTIMIDATOR", model: "GC1K CREW TGB 1000 STAGE 2" },
{ make: "INTIMIDATOR", model: "GC1K CREW TGB 1000 STAGE 3" },
{ make: "INTIMIDATOR", model: "GC1K TGB 1000 TRUCK " },
{ make: "INTIMIDATOR", model: "GC1K TRUCK" },
{ make: "INTIMIDATOR", model: "GC1K CREW" },
{ make: "INTIMIDATOR", model: "GC1K CREW DIESEL" },
{ make: "INTIMIDATOR", model: "GC1K DIESEL" },
{ make: "INTIMIDATOR", model: "TRUCK 2500" },
{ make: "INTIMIDATOR", model: "TRUCK 2500 CREW" },
{ make: "INTIMIDATOR", model: "TRUCK 2500 STAGE 1" },
{ make: "INTIMIDATOR", model: "TRUCK 2500 STAGE 2" },
{ make: "INTIMIDATOR", model: "TRUCK 2500 STAGE 3" },
{ make: "INTIMIDATOR", model: "OTHER" },

 // KIOTI

{ make: "KIOTI", model: "K9 2400" },
{ make: "KIOTI", model: "K9 2400 CAB" },
{ make: "KIOTI", model: "K9 2410" },
{ make: "KIOTI", model: "K9 2410 CAB" },
{ make: "KIOTI", model: "K9 2440" },
{ make: "KIOTI", model: "K9 2440 CAB" },
{ make: "KIOTI", model: "K9 2440 CHASSIS CAB" },
{ make: "KIOTI", model: "MECHRON 2200" },
{ make: "KIOTI", model: "MECHRON 2200 PS" },
{ make: "KIOTI", model: "MECHRON 2200 SE" },
{ make: "KIOTI", model: "MECHRON 2210" },
{ make: "KIOTI", model: "MECHRON 2210 PS" },
{ make: "KIOTI", model: "MECHRON 2210 SE" },
{ make: "KIOTI", model: "MECHRON 2230" },
{ make: "KIOTI", model: "MECHRON 2240" },
{ make: "KIOTI", model: "OTHER" },
  
  // MAHINDRA

{ make: "MAHINDRA", model: "IMPACT XTV 750B" },
{ make: "MAHINDRA", model: "IMPACT XTV 750C" },
{ make: "MAHINDRA", model: "IMPACT XTV 750S" },
{ make: "MAHINDRA", model: "IMPACT XTV 750S FLEXHAULER" },
{ make: "MAHINDRA", model: "IMPACT XTV 1000S" },
{ make: "MAHINDRA", model: "IMPACT XTV 1000S FLEXHAULER" },
{ make: "MAHINDRA", model: "IMPACT XTV 1000 GAS" },
{ make: "MAHINDRA", model: "IMPACT XTV 1000 DIESEL" },
{ make: "MAHINDRA", model: "RETRIEVER 750" },
{ make: "MAHINDRA", model: "RETRIEVER 1000" },
{ make: "MAHINDRA", model: "RETRIEVER 1000 FLEXHAULER" },
{ make: "MAHINDRA", model: "RETRIEVER 1000 GAS" },
{ make: "MAHINDRA", model: "RETRIEVER 1000 DIESEL" },
{ make: "MAHINDRA", model: "ROXOR" },
{ make: "MAHINDRA", model: "ROXOR ALL WEATHER " },
{ make: "MAHINDRA", model: "ROXOR LE" },
{ make: "MAHINDRA", model: "ROXOR SE" },
{ make: "MAHINDRA", model: "ROXOR HD" },
{ make: "MAHINDRA", model: "ROXOR HD ALL WEATHER " },
{ make: "MAHINDRA", model: "ROXOR BASE" },
{ make: "MAHINDRA", model: "ROXOR LIMITED EDITION" },
{ make: "MAHINDRA", model: "OTHER" },

// NEW HOLLAND

{ make: "NEW HOLLAND", model: "RUSTLER 115" },
{ make: "NEW HOLLAND", model: "RUSTLER 120" },
{ make: "NEW HOLLAND", model: "RUSTLER 125" },
{ make: "NEW HOLLAND", model: "RUSTLER 850" },
{ make: "NEW HOLLAND", model: "RUSTLER 850 2-PASSENGER" },
{ make: "NEW HOLLAND", model: "RUSTLER 850 4-PASSENGER" },
{ make: "NEW HOLLAND", model: "RUSTLER 850 CREW" },
{ make: "NEW HOLLAND", model: "RUSTLER 850 EPS" },
{ make: "NEW HOLLAND", model: "RUSTLER 850 GAS" },
{ make: "NEW HOLLAND", model: "RUSTLER 850 DIESEL" },
{ make: "NEW HOLLAND", model: "RUSTLER 950" },
{ make: "NEW HOLLAND", model: "RUSTLER 950 2-PASSENGER" },
{ make: "NEW HOLLAND", model: "RUSTLER 950 4-PASSENGER" },
{ make: "NEW HOLLAND", model: "RUSTLER 950 CREW" },
{ make: "NEW HOLLAND", model: "RUSTLER 950 EPS" },
{ make: "NEW HOLLAND", model: "RUSTLER 950 GAS" },
{ make: "NEW HOLLAND", model: "RUSTLER 950 DIESEL" },
{ make: "NEW HOLLAND", model: "OTHER" },

 // SD LANCH

{ make: "SD LANCH", model: "IRET 13" },
{ make: "SD LANCH", model: "OTHER" },
  
  // SCHERP

{ make: "SCHERP", model: "N1200" },
{ make: "SCHERP", model: "PRO 1000" },
{ make: "SCHERP", model: "PRO 1000 XT" },
{ make: "SCHERP", model: "PRO 1000 CREW" },
{ make: "SCHERP", model: "PRO 1000 CREW XT" },
{ make: "SCHERP", model: "OTHER" },
  
 // SUBURAU

{ make: "SUBURAU", model: "SAMBAR" },
{ make: "SUBURAU", model: "SAMBAR DIAS" },
{ make: "SUBURAU", model: "SAMBAR TRUCK" },
{ make: "SUBURAU", model: "SAMBAR VAN" },
{ make: "SUBURAU", model: "OTHER" },

// TAYLOR-DUNN

{ make: "TAYLOR-DUNN", model: "B5-440-36" },
{ make: "TAYLOR-DUNN", model: "B5-440-48" },
{ make: "TAYLOR-DUNN", model: "B5-540-48" },
{ make: "TAYLOR-DUNN", model: "B5-540-48XL" },
{ make: "TAYLOR-DUNN", model: "B0-150" },
{ make: "TAYLOR-DUNN", model: "B0-248" },
{ make: "TAYLOR-DUNN", model: "B1-100" },
{ make: "TAYLOR-DUNN", model: "B1-400" },
{ make: "TAYLOR-DUNN", model: "B2-48" },
{ make: "TAYLOR-DUNN", model: "B2-48V" },
{ make: "TAYLOR-DUNN", model: "BIGFOOT" },
{ make: "TAYLOR-DUNN", model: "BIGFOOT XL" },
{ make: "TAYLOR-DUNN", model: "C-425" },
{ make: "TAYLOR-DUNN", model: "C-432" },
{ make: "TAYLOR-DUNN", model: "GT-370" },
{ make: "TAYLOR-DUNN", model: "R-380" },
{ make: "TAYLOR-DUNN", model: "SC-100" },
{ make: "TAYLOR-DUNN", model: "TT-316" },
{ make: "TAYLOR-DUNN", model: "TT-316-36" },
{ make: "TAYLOR-DUNN", model: "TT-316-48" },
{ make: "TAYLOR-DUNN", model: "UTILITY VEHICLE" },
{ make: "TAYLOR-DUNN", model: "OTHER" },
  
 // SUZUKI

{ make: "SUZUKI", model: "CARRY" },
{ make: "SUZUKI", model: "CARRY 4WD" },
{ make: "SUZUKI", model: "CARRY TRUCK" },
{ make: "SUZUKI", model: "CARRY VAN" },
{ make: "SUZUKI", model: "CARRY DA16T" },
{ make: "SUZUKI", model: "CARRY DD51T" },
{ make: "SUZUKI", model: "CARRY DB41T" },
{ make: "SUZUKI", model: "EBD-DA65T" },
{ make: "SUZUKI", model: "Q.U.V." },
{ make: "SUZUKI", model: "QUV" },
{ make: "SUZUKI", model: "EVERY" },
{ make: "SUZUKI", model: "EVERY JOIN" },
{ make: "SUZUKI", model: "OTHER" },

 // TUATAR

{ make: "TUATAR", model: "1000 EFI" },
{ make: "TUATAR", model: "1500E" },
{ make: "TUATAR", model: "1500 EFI" },
{ make: "TUATAR", model: "1500D" },
{ make: "TUATAR", model: "1500 DIESEL" },
{ make: "TUATAR", model: "OTHER" },

// YAMAHA

{ make: "YAMAHA", model: "RHINO 450" },
{ make: "YAMAHA", model: "RHINO 660" },
{ make: "YAMAHA", model: "RHINO 660SE" },
{ make: "YAMAHA", model: "RHINO 700" },
{ make: "YAMAHA", model: "RHINO 700 FI" },
{ make: "YAMAHA", model: "RHINO 700 EPS" },
{ make: "YAMAHA", model: "RHINO 700 SPORT EDITION" },
{ make: "YAMAHA", model: "UMAX ONE EFI" },
{ make: "YAMAHA", model: "UMAX RALLY 2+2" },
{ make: "YAMAHA", model: "UMAX RALLY AC" },
{ make: "YAMAHA", model: "UMAX RALLY EFI" },
{ make: "YAMAHA", model: "UMX AC" },
{ make: "YAMAHA", model: "UMX EFI" },
{ make: "YAMAHA", model: "UMX GAS" },
{ make: "YAMAHA", model: "VIKING " },
{ make: "YAMAHA", model: "VIKING 700" },
{ make: "YAMAHA", model: "VIKING EPS" },
{ make: "YAMAHA", model: "VIKING EPS RANCH" },
{ make: "YAMAHA", model: "VIKING FI" },
{ make: "YAMAHA", model: "VIKING RANCH EDITION" },
{ make: "YAMAHA", model: "VIKING VI" },
{ make: "YAMAHA", model: "VIKING VI EPS" },
{ make: "YAMAHA", model: "VIKING VI EPS RANCH EDITION" },
{ make: "YAMAHA", model: "WOLVERINE" },
{ make: "YAMAHA", model: "WOLVERINE 450" },
{ make: "YAMAHA", model: "WOLVERINE 700" },
{ make: "YAMAHA", model: "WOLVERINE 850" },
{ make: "YAMAHA", model: "WOLVERINE RMAX2 1000" },
{ make: "YAMAHA", model: "WOLVERINE RMAX2 1000 LE" },
{ make: "YAMAHA", model: "WOLVERINE RMAX2 1000 R-SPEC" },
{ make: "YAMAHA", model: "WOLVERINE RMAX2 1000 SPORT" },
{ make: "YAMAHA", model: "WOLVERINE RMAX2 1000 XT-R" },
{ make: "YAMAHA", model: "WOLVERINE RMAX4 1000" },
{ make: "YAMAHA", model: "WOLVERINE RMAX4 1000 LE" },
{ make: "YAMAHA", model: "WOLVERINE RMAX4 1000 R-SPEC" },
{ make: "YAMAHA", model: "WOLVERINE RMAX4 1000 XT-R" },
{ make: "YAMAHA", model: "WOLVERINE R-SPEC" },
{ make: "YAMAHA", model: "WOLVERINE R-SPEC EPS" },
{ make: "YAMAHA", model: "WOLVERINE X2" },
{ make: "YAMAHA", model: "WOLVERINE X2 850 XT-R" },
{ make: "YAMAHA", model: "WOLVERINE X2 R-SPEC" },
{ make: "YAMAHA", model: "WOLVERINE X2 XT-R" },
{ make: "YAMAHA", model: "WOLVERINE X4" },
{ make: "YAMAHA", model: "WOLVERINE X4 850 XT-R" },
{ make: "YAMAHA", model: "WOLVERINE X4 SE" },
{ make: "YAMAHA", model: "WOLVERINE X2 850 R-SPEC " },
{ make: "YAMAHA", model: "YXZ1000R" },
{ make: "YAMAHA", model: "YXZ1000R SE" },
{ make: "YAMAHA", model: "YXZ1000R SS" },
{ make: "YAMAHA", model: "YXZ1000R SS XT-R" },
{ make: "YAMAHA", model: "YXZ1000R SS SE" },
{ make: "YAMAHA", model: "OTHER" },

  // VITACCI

{ make: "VITACCI", model: "BLADE FX250" },
{ make: "VITACCI", model: "BLADE 150" },
{ make: "VITACCI", model: "BLADE 200" },
{ make: "VITACCI", model: "BLADE 250" },
{ make: "VITACCI", model: "CONQUEROR 100DLX" },
{ make: "VITACCI", model: "CONQUEROR 125" },
{ make: "VITACCI", model: "CONQUEROR 150" },
{ make: "VITACCI", model: "MAXIMUS 800 EFI" },
{ make: "VITACCI", model: "MAXIMUS 800" },
{ make: "VITACCI", model: "ROVER ELECTRIC" },
{ make: "VITACCI", model: "ROVER 200" },
{ make: "VITACCI", model: "ROVER 200 EFI" },
{ make: "VITACCI", model: "VICTORY 450 PRO " },
{ make: "VITACCI", model: "VICTORY 450" },
{ make: "VITACCI", model: "VICTORY 450 EFI" },
{ make: "VITACCI", model: "OTHER" },

 // YANMAR

{ make: "YANMAR", model: "BRAHMA YU1000D" },
{ make: "YANMAR", model: "BULL YU700G" },
{ make: "YANMAR", model: "LONGHORN YU700GMP" },
{ make: "YANMAR", model: "BULL YU700" },
{ make: "YANMAR", model: "BULL YU700GMP" },
{ make: "YANMAR", model: "BULL YU700GMPH" },
{ make: "YANMAR", model: "LONGHORN YU700" },
{ make: "YANMAR", model: "LONGHORN YU700GMPH" },
{ make: "YANMAR", model: "BRAHMA YU700" },
{ make: "YANMAR", model: "BRAHMA YU700G" },
{ make: "YANMAR", model: "BRAHMA YU700GMP" },
{ make: "YANMAR", model: "BRAHMA YU1000" },
{ make: "YANMAR", model: "BRAHMA YU1000G" },
{ make: "YANMAR", model: "BULL YU1000D" },
{ make: "YANMAR", model: "LONGHORN YU1000D" },
{ make: "YANMAR", model: "OTHER" },
  
];

export default utilityCartsTaxonomy;
