const wheelLoaderDnaKeywords = [
  /* -------------------- */
  /* MACHINE TYPE DNA */
  /* -------------------- */

  "COMPACT WHEEL LOADER",
  "ARTICULATED WHEEL LOADER",
  "PRODUCTION WHEEL LOADER",
  "LARGE WHEEL LOADER",
  "MINING WHEEL LOADER",
  "TOOL CARRIER",
  "INTEGRATED TOOL CARRIER",
  "IT LOADER",
  "TC LOADER",
  "TOOLMASTER",
  "FORK LOADER",
  "HIGH LIFT LOADER",
  "HIGH DUMP LOADER",
  "TELESCOPIC WHEEL LOADER",
  "ELECTRIC WHEEL LOADER",
  "HYBRID WHEEL LOADER",
  "WASTE HANDLER",
  "FORESTRY LOADER",
  "MATERIAL HANDLER",
  "REHANDLER",

  /* -------------------- */
  /* CHASSIS / FRAME DNA */
  /* -------------------- */

  "ARTICULATED FRAME",
  "RIGID FRAME",
  "COMPACT FRAME",
  "FULL SIZE FRAME",
  "HEAVY DUTY FRAME",
  "REINFORCED FRAME",
  "LOW PROFILE CHASSIS",
  "HIGH CLEARANCE CHASSIS",
  "STANDARD WHEELBASE",
  "LONG WHEELBASE",
  "SHORT WHEELBASE",
  "OSCILLATING REAR AXLE",
  "CENTER ARTICULATION",
  "REAR FRAME",
  "FRONT FRAME",
  "COUNTERWEIGHT FRAME",
  "HEAVY DUTY AXLES",
  "PLANETARY AXLES",

  /* -------------------- */
  /* LOADER ARM / LINKAGE DNA */
  /* -------------------- */

  "STANDARD LIFT",
  "HIGH LIFT",
  "EXTENDED REACH",
  "LONG BOOM",
  "STANDARD BOOM",
  "Z BAR",
  "Z BAR LINKAGE",
  "PARALLEL LIFT",
  "PARALLEL LINKAGE",
  "TOOL CARRIER LINKAGE",
  "INTEGRATED TOOL CARRIER LINKAGE",
  "IT LINKAGE",
  "TORQUE PARALLEL",
  "TP LINKAGE",
  "XT LINKAGE",
  "XR LINKAGE",
  "TM LINKAGE",
  "HIGH TILT",
  "HIGH TIP LINKAGE",
  "QUICK COUPLER LINKAGE",
  "SELF LEVELING",
  "RETURN TO DIG",
  "BOOM FLOAT",
  "BUCKET POSITIONER",
  "KICKOUTS",

  /* -------------------- */
  /* BUCKET SYSTEM DNA */
  /* -------------------- */

  "GENERAL PURPOSE BUCKET",
  "GP BUCKET",
  "LIGHT MATERIAL BUCKET",
  "HIGH CAPACITY BUCKET",
  "ROCK BUCKET",
  "HEAVY DUTY BUCKET",
  "SEVERE DUTY BUCKET",
  "COAL BUCKET",
  "WOOD CHIP BUCKET",
  "SNOW BUCKET",
  "WASTE BUCKET",
  "REHANDLING BUCKET",
  "SIDE DUMP BUCKET",
  "HIGH DUMP BUCKET",
  "MULTI PURPOSE BUCKET",
  "4 IN 1 BUCKET",
  "GRAPPLE BUCKET",
  "LOG GRAPPLE BUCKET",
  "SPADE NOSE BUCKET",
  "STRAIGHT EDGE BUCKET",
  "TOOTH BUCKET",
  "SMOOTH EDGE BUCKET",
  "BOLT ON CUTTING EDGE",
  "WELD ON CUTTING EDGE",
  "REVERSIBLE CUTTING EDGE",
  "SEGMENTED CUTTING EDGE",
  "BUCKET TEETH",
  "ROCK TEETH",
  "ESCO TEETH",
  "HENSLEY TEETH",
  "CAT TEETH",
  "SIDE CUTTERS",
  "LIP SHROUDS",
  "HEEL SHROUDS",
  "WEAR PLATES",
  "AR BUCKET",
  "HARDOX BUCKET",

  /* -------------------- */
  /* FORK SYSTEM DNA */
  /* -------------------- */

  "FORKS",
  "PALLET FORKS",
  "CONSTRUCTION FORKS",
  "BLOCK FORKS",
  "PIPE FORKS",
  "LUMBER FORKS",
  "LOG FORKS",
  "UTILITY FORKS",
  "HEAVY DUTY FORKS",
  "HYDRAULIC FORKS",
  "FORK POSITIONER",
  "HYDRAULIC FORK POSITIONER",
  "SIDE SHIFT FORKS",
  "SIDE SHIFT CARRIAGE",
  "WIDE CARRIAGE",
  "STANDARD CARRIAGE",
  "QUICK ATTACH FORKS",
  "PIN ON FORKS",
  "FORK EXTENSIONS",
  "FORK BACKREST",
  "FORK CARRIAGE",

  /* -------------------- */
  /* COUPLER DNA */
  /* -------------------- */

  "QUICK COUPLER",
  "HYDRAULIC COUPLER",
  "MANUAL COUPLER",
  "HYDRAULIC QUICK COUPLER",
  "PIN ON",
  "PIN ON BUCKET",
  "JRB COUPLER",
  "ACS COUPLER",
  "CAT COUPLER",
  "VOLVO COUPLER",
  "DEERE COUPLER",
  "KOMATSU COUPLER",
  "EURO COUPLER",
  "ISO COUPLER",
  "HOOK TYPE COUPLER",
  "WEDGE LOCK COUPLER",
  "COUPLER LOCK",
  "COUPLER SAFETY LOCK",

  /* -------------------- */
  /* HYDRAULIC SYSTEM DNA */
  /* -------------------- */

  "OPEN CENTER HYDRAULICS",
  "CLOSED CENTER HYDRAULICS",
  "LOAD SENSING HYDRAULICS",
  "PRESSURE COMPENSATED HYDRAULICS",
  "VARIABLE DISPLACEMENT PUMP",
  "PISTON PUMP",
  "GEAR PUMP",
  "HYDRAULIC COOLER",
  "HYDRAULIC FILTER",
  "ELECTRO HYDRAULIC CONTROLS",
  "PROPORTIONAL HYDRAULICS",
  "LIFT CYLINDERS",
  "TILT CYLINDERS",
  "STEERING CYLINDERS",
  "BUCKET CYLINDERS",
  "HIGH PRESSURE HYDRAULICS",
  "HYDRAULIC QUICK COUPLERS",
  "HYDRAULIC OIL COOLER",

  /* -------------------- */
  /* AUXILIARY HYDRAULIC DNA */
  /* -------------------- */

  "AUX HYDRAULICS",
  "AUXILIARY HYDRAULICS",
  "THIRD VALVE",
  "FOURTH VALVE",
  "THIRD FUNCTION",
  "FOURTH FUNCTION",
  "HIGH FLOW",
  "HIGH FLOW HYDRAULICS",
  "STANDARD FLOW",
  "ATTACHMENT HYDRAULICS",
  "COUPLER HYDRAULICS",
  "GRAPPLE HYDRAULICS",
  "FORK POSITIONER HYDRAULICS",
  "MULTI FUNCTION HYDRAULICS",
  "CONTINUOUS FLOW",
  "FRONT AUXILIARY LINES",

  /* -------------------- */
  /* STEERING DNA */
  /* -------------------- */

  "ARTICULATED STEERING",
  "CENTER ARTICULATION",
  "HYDRAULIC STEERING",
  "LOAD SENSING STEERING",
  "JOYSTICK STEERING",
  "COMMAND STEERING",
  "STEERING WHEEL",
  "CRAB STEER",
  "STEREO STEERING",
  "REAR AXLE STEERING",
  "ALL WHEEL STEER",
  "FRAME STEER",
  "STEERING LOCK",
  "ARTICULATION LOCK",

  /* -------------------- */
  /* DIFFERENTIAL / TRACTION DNA */
  /* -------------------- */

  "DIFFERENTIAL LOCK",
  "FRONT DIFFERENTIAL LOCK",
  "REAR DIFFERENTIAL LOCK",
  "LIMITED SLIP",
  "LIMITED SLIP DIFFERENTIAL",
  "AUTO LOCKING DIFFERENTIAL",
  "OPEN DIFFERENTIAL",
  "NO SPIN DIFFERENTIAL",
  "TRACTION CONTROL",
  "RIM PULL CONTROL",
  "ANTI SLIP CONTROL",
  "AXLE LOCK",
  "LOCKING AXLES",
  "PLANETARY FINAL DRIVES",

  /* -------------------- */
  /* TRANSMISSION / DRIVE DNA */
  /* -------------------- */

  "POWERSHIFT",
  "HYDROSTATIC",
  "HYDROSTATIC DRIVE",
  "CVT",
  "HVT",
  "XE DRIVE",
  "HYBRID DRIVE",
  "ELECTRIC DRIVE",
  "TORQUE CONVERTER",
  "LOCKUP TORQUE CONVERTER",
  "DIRECT DRIVE",
  "PLANETARY TRANSMISSION",
  "AUTOMATIC TRANSMISSION",
  "AUTO SHIFT",
  "MANUAL SHIFT",
  "FNR SHUTTLE",
  "FINGERTIP SHIFT",
  "4WD",
  "ALL WHEEL DRIVE",
  "FRONT AXLE DRIVE",
  "REAR AXLE DRIVE",
  "FINAL DRIVES",
  "CREEPER SPEED",

  /* -------------------- */
  /* RIDE CONTROL DNA */
  /* -------------------- */

  "RIDE CONTROL",
  "BOOM SUSPENSION",
  "LOAD RIDE CONTROL",
  "HYDRAULIC RIDE CONTROL",
  "ACCUMULATOR RIDE CONTROL",
  "AUTO RIDE CONTROL",
  "RIDE CONTROL ACCUMULATORS",
  "LOAD CUSHION",
  "BOOM DAMPING",
  "TRAVEL DAMPING",

  /* -------------------- */
  /* TIRE / WHEEL DNA */
  /* -------------------- */

  "RADIAL TIRES",
  "BIAS TIRES",
  "LSW TIRES",
  "LOW SIDEWALL TIRES",
  "SOLID TIRES",
  "FOAM FILLED TIRES",
  "PNEUMATIC TIRES",
  "FLOTATION TIRES",
  "WIDE BASE TIRES",
  "ROCK TIRES",
  "L5 TIRES",
  "L4 TIRES",
  "L3 TIRES",
  "L2 TIRES",
  "SMOOTH TIRES",
  "TRACTION TIRES",
  "INDUSTRIAL TIRES",
  "AG TIRES",
  "TURF TIRES",
  "CHAIN READY",
  "TIRE CHAINS",
  "WHEEL LOADER CHAINS",
  "ALUMINUM WHEELS",
  "STEEL WHEELS",
  "WHEEL GUARDS",
  "RIM PULL",

  /* -------------------- */
  /* CAB / OPERATOR DNA */
  /* -------------------- */

  "ROPS",
  "FOPS",
  "OPEN ROPS",
  "CAB",
  "ENCLOSED CAB",
  "C/H/A",
  "AIR CONDITIONED CAB",
  "HEATED CAB",
  "PRESSURIZED CAB",
  "LOW PROFILE CAB",
  "HIGH VISIBILITY CAB",
  "PANORAMIC CAB",
  "FORESTRY CAB",
  "WASTE HANDLER CAB",
  "DEMOLITION CAB",
  "AIR RIDE SEAT",
  "SUSPENSION SEAT",
  "HEATED SEAT",
  "JOYSTICK CONTROLS",
  "PILOT CONTROLS",
  "ELECTRO HYDRAULIC CONTROLS",
  "STEERING WHEEL CONTROLS",
  "MULTIFUNCTION DISPLAY",
  "TOUCHSCREEN DISPLAY",
  "REAR CAMERA",
  "SIDE CAMERA",
  "360 CAMERA",
  "CAMERA SYSTEM",
  "LED LIGHTS",
  "WORK LIGHT PACKAGE",
  "BEACON",

  /* -------------------- */
  /* GUARDING DNA */
  /* -------------------- */

  "FULL GUARDING",
  "WASTE PACKAGE",
  "FORESTRY PACKAGE",
  "SEVERE DUTY PACKAGE",
  "ROCK GUARDS",
  "BELLY GUARDS",
  "BOTTOM GUARDS",
  "AXLE GUARDS",
  "DRIVE SHAFT GUARDS",
  "CYLINDER GUARDS",
  "LIFT CYLINDER GUARDS",
  "TILT CYLINDER GUARDS",
  "HOSE GUARDS",
  "LIGHT GUARDS",
  "FENDER GUARDS",
  "REAR GUARDS",
  "RADIATOR GUARD",
  "POWERTRAIN GUARD",
  "WINDOW GUARDS",
  "WINDSHIELD GUARD",
  "CAB GUARDS",
  "FALLING OBJECT GUARD",
  "FOPS GUARDING",

  /* -------------------- */
  /* BOOM / LIFT DNA */
  /* -------------------- */

  "STANDARD BOOM",
  "HIGH LIFT BOOM",
  "LONG BOOM",
  "EXTENDED REACH BOOM",
  "TELESCOPIC BOOM",
  "PARALLEL BOOM",
  "Z BAR BOOM",
  "TOOL CARRIER BOOM",
  "HIGH DUMP BOOM",
  "LIFT ARM",
  "LOADER ARM",
  "HIGH LIFT ARMS",
  "STANDARD LIFT ARMS",
  "LIFT CYLINDERS",
  "BOOM KICKOUT",
  "LIFT KICKOUT",
  "RETURN TO CARRY",
  "RETURN TO DIG",
  "BOOM FLOAT",
  "PAYLOAD LIFT SYSTEM",

  /* -------------------- */
  /* COUNTERWEIGHT DNA */
  /* -------------------- */

  "STANDARD COUNTERWEIGHT",
  "HEAVY COUNTERWEIGHT",
  "ADDITIONAL COUNTERWEIGHT",
  "REAR COUNTERWEIGHT",
  "HIGH LIFT COUNTERWEIGHT",
  "LOGGING COUNTERWEIGHT",
  "FORK COUNTERWEIGHT",
  "WASTE HANDLER COUNTERWEIGHT",
  "COUNTERWEIGHT GUARD",
  "COUNTERWEIGHT PACKAGE",

  /* -------------------- */
  /* TOOL CARRIER DNA */
  /* -------------------- */

  "TOOL CARRIER",
  "INTEGRATED TOOL CARRIER",
  "IT",
  "TC",
  "TOOLMASTER",
  "TM",
  "PARALLEL LIFT TOOL CARRIER",
  "QUICK COUPLER TOOL CARRIER",
  "HYDRAULIC COUPLER TOOL CARRIER",
  "FORK CARRIAGE TOOL CARRIER",
  "AUX HYDRAULIC TOOL CARRIER",
  "TELESCOPIC TOOL CARRIER",
  "AG HANDLER",
  "MATERIAL HANDLER",
  "REHANDLER",
  "HIGH LIFT TOOL CARRIER",

  /* -------------------- */
  /* FORESTRY / WASTE DNA */
  /* -------------------- */

  "FORESTRY PACKAGE",
  "WASTE PACKAGE",
  "WASTE HANDLER",
  "LANDFILL PACKAGE",
  "MILLYARD PACKAGE",
  "LOG HANDLER PACKAGE",
  "LOG GRAPPLE",
  "LOG FORKS",
  "HIGH TIP BUCKET",
  "TRASH GUARDS",
  "DEBRIS PACKAGE",
  "DEBRIS SCREEN",
  "REVERSING FAN",
  "AUTO REVERSING FAN",
  "HIGH CAPACITY COOLING",
  "FIRE SUPPRESSION",
  "SOLID TIRES",
  "FOAM FILLED TIRES",
  "AXLE GUARDS",
  "BELLY GUARDS",
  "RADIATOR GUARD",

  /* -------------------- */
  /* AUTOMATION / PAYLOAD DNA */
  /* -------------------- */

  "PAYLOAD SYSTEM",
  "SCALE SYSTEM",
  "ONBOARD SCALE",
  "LOAD SCALE",
  "BUCKET SCALE",
  "LOADRITE",
  "CAT PAYLOAD",
  "DEERE PAYLOAD WEIGHING",
  "KOMATSU LOADMETER",
  "VOLVO LOAD ASSIST",
  "WEIGHLOG",
  "TRIMBLE LOADRITE",
  "PAYLOAD PRINTER",
  "LOAD COUNTER",
  "MACHINE CONTROL READY",
  "GRADE CONTROL READY",
  "AUTODIG",
  "AUTO DIG",
  "AUTO BUCKET FILL",
  "BUCKET FILL ASSIST",
  "TRACTION ASSIST",
  "RIMPULL CONTROL",
  "TELEMATICS",
  "PRODUCT LINK",
  "JD LINK",
  "KOMTRAX",
  "CARETRACK",
  "REMOTE DIAGNOSTICS",

  /* -------------------- */
  /* COOLING DNA */
  /* -------------------- */

  "HIGH CAPACITY COOLING",
  "HIGH AMBIENT COOLING",
  "COOLING PACKAGE",
  "WASTE COOLING PACKAGE",
  "FORESTRY COOLING PACKAGE",
  "REVERSING FAN",
  "AUTO REVERSING FAN",
  "VARIABLE SPEED FAN",
  "HYDRAULIC FAN",
  "DEBRIS SCREEN",
  "RADIATOR SCREEN",
  "COOLER SCREEN",
  "SWING OUT COOLER",
  "COOLING CLEANOUT",
  "HYDRAULIC OIL COOLER",
  "TRANSMISSION COOLER",
  "AXLE OIL COOLER",

  /* -------------------- */
  /* POWERTRAIN DNA */
  /* -------------------- */

  "DIESEL ENGINE",
  "ELECTRIC WHEEL LOADER",
  "BATTERY ELECTRIC",
  "HYBRID",
  "DIESEL ELECTRIC",
  "XE POWERTRAIN",
  "XPOWER",
  "EV LOADER",
  "TURBOCHARGED",
  "INTERCOOLED",
  "COMMON RAIL",
  "MECHANICAL INJECTION",
  "ELECTRONIC ENGINE",
  "AUTO IDLE",
  "AUTO SHUTDOWN",
  "ECO MODE",
  "POWER MODE",
  "REVERSING FAN",
  "BLOCK HEATER",
  "COLD WEATHER PACKAGE",
  "ETHER START",

  /* -------------------- */
  /* BRAKE / SAFETY DNA */
  /* -------------------- */

  "WET DISC BRAKES",
  "DRY DISC BRAKES",
  "HYDRAULIC BRAKES",
  "SERVICE BRAKES",
  "PARK BRAKE",
  "TRANSMISSION PARK BRAKE",
  "SECONDARY BRAKES",
  "BRAKE COOLING",
  "BACKUP ALARM",
  "TRAVEL ALARM",
  "OBJECT DETECTION",
  "PROXIMITY DETECTION",
  "SEAT BELT",
  "OPERATOR PRESENCE SYSTEM",
  "FIRE SUPPRESSION",
  "BATTERY DISCONNECT",
  "MASTER DISCONNECT",
  "AUTO LUBE",
  "CENTRALIZED GREASING",

  /* -------------------- */
  /* EMISSIONS DNA */
  /* -------------------- */

  "PRE-DEF",
  "PRE-EMISSIONS",
  "TIER 1",
  "TIER 2",
  "TIER 3",
  "INTERIM TIER 4",
  "TIER 4",
  "TIER 4 FINAL",
  "T4F",
  "STAGE IIIA",
  "STAGE IIIB",
  "STAGE IV",
  "STAGE V",
  "EGR",
  "SCR",
  "DEF",
  "DPF",
  "DOC",
  "NO DEF",
  "NO DPF",
  "DEF DELETE"
];

export default wheelLoaderDnaKeywords;
