import { useState } from "react";
const DEFAULT_SKINS=[{id:"v12",label:"V12"},{id:"steel",label:"STEEL"},{id:"blueprint",label:"BLUE"},{id:"industrial",label:"INDUSTRIAL"}];
export default function IXIAosCardHeaderControls({canAdd=false,canEdit=false,canTransact=false,editing=false,onAdd=null,onToggleEdit=null,onTransact=null,onHide=null,onDelete=null,onOpenConsole=null,skinId="",skinOptions=[],onSkinChange=null}){
 const[menuOpen,setMenuOpen]=useState(false),[localSkinId,setLocalSkinId]=useState("v12");function stop(e){e?.preventDefault?.();e?.stopPropagation?.()}const supplied=Array.isArray(skinOptions)?skinOptions.filter(o=>o&&typeof o==="object"&&String(o.id||"").trim()):[],resolvedOptions=Array.from(new Map([...DEFAULT_SKINS,...supplied].map(o=>[String(o.id||"").trim(),o])).values()),resolvedSkinId=String(skinId||localSkinId||"v12").trim();function chooseSkin(e,id){stop(e);setLocalSkinId(id);onSkinChange?.(id);setMenuOpen(false)}
 return <div className={`ixi-aos-card-header-controls skin-${resolvedSkinId}`} data-card-skin={resolvedSkinId} onPointerDown={e=>e.stopPropagation()}>
  {canAdd?<button type="button" className="header-action add" aria-label="Add related object" title="Add related object" onClick={e=>{stop(e);onAdd?.()}}><span className="cmd-icon">＋</span><small>ADD</small></button>:null}
  {canEdit?<button type="button" className={`header-action edit ${editing?"active":""}`} aria-label="Edit this object" title="Edit this object" onClick={e=>{stop(e);if(!editing)onToggleEdit?.()}}><span className="cmd-icon pencil">✎</span><small>EDIT</small></button>:null}
  {canTransact&&typeof onTransact==="function"?<button type="button" className="header-action transact" aria-label="Open IXI TRAN$ACT" title="Open IXI TRAN$ACT" onClick={e=>{stop(e);onTransact?.()}}><span className="cmd-icon dollar">$</span><small>TRAN$ACT</small></button>:null}
  <div className="menu-shell"><button type="button" className="header-action menu" aria-label="More actions" title="More actions" onClick={e=>{stop(e);setMenuOpen(c=>!c)}}><span className="cmd-icon dots">⋮</span><small>MORE</small></button>
   {menuOpen?<div className="header-menu" onClick={e=>e.stopPropagation()}><div className="skin-menu-group"><div className="menu-label">SKIN</div>{resolvedOptions.map(option=>{const id=String(option.id||"").trim(),label=String(option.label||id).trim();return <button key={id} type="button" className={id===resolvedSkinId?"skin-option active":"skin-option"} onClick={e=>chooseSkin(e,id)}>{label}{id===resolvedSkinId?<span>✓</span>:null}</button>})}</div>{typeof onOpenConsole==="function"?<button type="button" onClick={e=>{stop(e);setMenuOpen(false);onOpenConsole?.()}}>OPEN CONSOLE</button>:null}{typeof onHide==="function"?<button type="button" onClick={e=>{stop(e);setMenuOpen(false);onHide?.()}}>HIDE</button>:null}{typeof onDelete==="function"?<button type="button" className="danger" onClick={e=>{stop(e);setMenuOpen(false);onDelete?.()}}>DELETE</button>:null}</div>:null}
  </div>
  <style jsx>{`
   .ixi-aos-card-header-controls{position:absolute;top:7px;right:7px;height:42px;display:flex;align-items:stretch;gap:4px;z-index:180}.header-action{width:41px;height:42px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:1px;padding:2px 0 1px;border:1px solid rgba(255,255,255,.13);border-radius:6px;background:linear-gradient(180deg,rgba(255,255,255,.035),rgba(255,255,255,.012));color:rgba(255,255,255,.76);box-shadow:inset 0 1px rgba(255,255,255,.035);cursor:pointer}.cmd-icon{height:25px;display:grid;place-items:center;color:rgba(255,255,255,.84);font-family:Arial,sans-serif;font-size:20px;font-weight:400;line-height:1}.add .cmd-icon,.transact .cmd-icon{color:#ffc400}.add .cmd-icon{font-size:25px}.transact .cmd-icon{font-size:27px}.pencil{font-size:21px;transform:rotate(-8deg)}.dots{font-size:22px}.header-action small{display:block;color:rgba(255,255,255,.58);font-size:4.8px;font-weight:950;letter-spacing:.025em;line-height:7px;white-space:nowrap}.header-action.transact{border-color:rgba(255,196,0,.28);background:linear-gradient(180deg,rgba(255,196,0,.055),rgba(255,196,0,.012))}.header-action.transact small{color:#ffc400;font-size:4.2px}.header-action:hover,.header-action.active{border-color:rgba(255,196,0,.48);background:linear-gradient(180deg,rgba(255,196,0,.08),rgba(255,196,0,.02));color:#ffc400}.menu-shell{position:relative}.header-menu{position:absolute;top:47px;right:0;width:132px;max-height:305px;overflow-y:auto;display:flex;flex-direction:column;gap:4px;padding:6px;border:1px solid rgba(255,255,255,.10);border-radius:6px;background:rgba(8,8,8,.985);box-shadow:0 14px 30px rgba(0,0,0,.46);z-index:300}.skin-menu-group{display:flex;flex-direction:column;gap:3px;margin-bottom:2px;padding-bottom:5px;border-bottom:1px solid rgba(255,255,255,.06)}.menu-label{padding:2px 6px 1px;color:rgba(255,255,255,.28);font-size:5px;font-weight:950;letter-spacing:.08em}.header-menu button{width:100%;height:25px;padding:0 7px;border:1px solid rgba(255,255,255,.06);border-radius:4px;background:rgba(255,255,255,.02);color:rgba(255,255,255,.62);font-size:6px;font-weight:950;text-align:left;cursor:pointer}.header-menu button:hover,.header-menu button.skin-option.active{border-color:rgba(255,196,0,.28);color:#ffc400}.header-menu button.skin-option{display:flex;align-items:center;justify-content:space-between;flex:0 0 25px}.header-menu button.danger:hover{border-color:rgba(229,62,62,.44);color:rgb(255,112,112)}
  `}</style>
 </div>
}
