import { useEffect, useMemo, useState } from "react";
import { createIXIFreightOrder, loadIXIFreightEvents, loadIXIFreightOrders, runIXIFreightAction } from "./IXIFreightClient";
import { createIXIFreightOrderInput, freightVariance, IXI_FREIGHT_ACTION_BY_STATUS, IXI_FREIGHT_PURPOSES, validateIXIFreightOrderInput, invoiceCharges } from "./IXIFreightContract";
import { createAndMatchIXIFreightInvoice } from "./IXIFreightCommands";
import IXIFreightStyles from "./IXIFreightStyles";

const clean=value=>String(value??"").trim();
const usd=value=>Number(value||0).toLocaleString("en-US",{style:"currency",currency:"USD"});
const today=()=>new Date().toISOString().slice(0,10);
const commandId=prefix=>`${prefix}-${globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2,8)}`}`;
const purposeLabel=value=>clean(value).replace(/-/g," ").toUpperCase();

function blankOrder(context={}){return{
  commandId:commandId("FRT"),purpose:"acquisition-inbound",mode:"external-carrier",carrierName:"",carrierPassportId:"",payer:"company",customerRebill:false,
  originObjectId:"",originLabel:clean(context.location?.label),originAddress:"",destinationObjectId:"",destinationLabel:"",destinationAddress:"",routeMiles:"",weight:"",
  requestedPickupAt:"",scheduledPickupAt:"",expectedDeliveryAt:"",quotedAmount:"",agreedAmount:"",permitEstimate:"",escortEstimate:"",fuelSurchargeEstimate:"",otherEstimate:"",notes:""
}}
function blankInvoice(){return{documentType:"carrier-invoice",invoiceNumber:"",invoiceDate:today(),dueDate:"",actualCostTotal:"",freight:"",permits:"",escort:"",detention:"",fuelSurcharge:"",other:"",documentReference:"",notes:"",sourceBillDocumentId:""}}
const ACTION_LABEL={request:"REQUEST FREIGHT",award:"AWARD LOAD",dispatch:"DISPATCH",pickup:"PICKED UP",deliver:"DELIVERED"};

export default function IXIFreightApp({context={},object={},onBack=null,onRecordChange=null,onFinancialRecordsChange=null}){
  const passportId=clean(context.primary?.passportId||object.passportId);
  const [orders,setOrders]=useState([]),[selectedId,setSelectedId]=useState(""),[mode,setMode]=useState("queue"),[tab,setTab]=useState("order");
  const [draft,setDraft]=useState(()=>blankOrder(context)),[invoice,setInvoice]=useState(blankInvoice),[events,setEvents]=useState([]);
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[errors,setErrors]=useState({}),[varianceApproved,setVarianceApproved]=useState(false),[varianceNote,setVarianceNote]=useState("");
  const order=useMemo(()=>orders.find(item=>clean(item?.identity?.freightOrderId)===selectedId)||null,[orders,selectedId]);
  const variance=freightVariance(order||{}),nextAction=IXI_FREIGHT_ACTION_BY_STATUS[clean(order?.status)],invoiceTotal=invoiceCharges(invoice).amount;

  async function refresh(signal){
    if(!passportId){setError("MACHINE PASSPORT IS REQUIRED FOR FREIGHT.");setLoading(false);return}
    try{setLoading(true);const found=await loadIXIFreightOrders(passportId,{signal});setOrders(found);setError("")}catch(err){if(err?.name!=="AbortError")setError(clean(err?.message)||"FREIGHT ORDERS COULD NOT LOAD.")}finally{setLoading(false)}
  }
  useEffect(()=>{const controller=new AbortController();refresh(controller.signal);return()=>controller.abort()},[passportId]);
  useEffect(()=>{if(!selectedId){setEvents([]);return}const controller=new AbortController();loadIXIFreightEvents(selectedId,{signal:controller.signal}).then(setEvents).catch(()=>setEvents([]));return()=>controller.abort()},[selectedId,order?.identity?.revision]);
  function patch(key,value){setDraft(current=>({...current,[key]:value}))}
  function patchInvoice(key,value){setInvoice(current=>({...current,[key]:value}))}
  function upsert(next){setOrders(current=>[next,...current.filter(item=>clean(item?.identity?.freightOrderId)!==clean(next?.identity?.freightOrderId))]);setSelectedId(clean(next?.identity?.freightOrderId));return next}
  async function notify(next,action,payload={}){upsert(next);await onRecordChange?.(next,{action,payload});return next}

  async function saveOrder(){
    if(busy)return;const payload=createIXIFreightOrderInput({context,object,input:draft}),validation=validateIXIFreightOrderInput(payload);setErrors(validation.errors);
    if(!validation.valid){setError(Object.values(validation.errors)[0]);return}
    setBusy(true);setError("");try{const next=await createIXIFreightOrder(payload);await notify(next,"create");setMode("record");setTab("order")}catch(err){setError(clean(err?.message)||"FREIGHT ORDER COULD NOT BE CREATED.")}finally{setBusy(false)}
  }
  async function act(action,body={}){
    if(!order||busy)return;setBusy(true);setError("");try{const next=await runIXIFreightAction(selectedId,action,{commandId:commandId(`freight-${action}`),...body});await notify(next,action);if(action==="deliver")setTab("reconcile")}catch(err){setError(clean(err?.message)||"FREIGHT ACTION FAILED.")}finally{setBusy(false)}
  }
  async function matchInvoice(){
    if(!order||busy)return;setBusy(true);setError("");try{const result=await createAndMatchIXIFreightInvoice({order,input:invoice,context,object});await onFinancialRecordsChange?.();await notify(result.order,"invoice-match",{financialDocumentId:result.financialDocumentId});setInvoice(blankInvoice());setTab("reconcile")}catch(err){setError(clean(err?.message)||"CARRIER INVOICE COULD NOT BE MATCHED.")}finally{setBusy(false)}
  }
  async function reconcile(){await act("reconcile",{varianceApproved,varianceNote})}
  const status=clean(order?.status||"draft"),statusClass=["delivered","reconciled","paid","closed"].includes(status)?"good":["cancelled"].includes(status)?"bad":"";

  function Queue(){return <><div className="fr-section">MACHINE FREIGHT</div>{orders.length?orders.map(item=><div className="fr-card" key={item.identity?.freightOrderId}><button onClick={()=>{setSelectedId(item.identity.freightOrderId);setMode("record");setTab("order")}}><strong>{item.identity?.freightOrderId}</strong><span>{purposeLabel(item.purpose?.type)} · {purposeLabel(item.status)}</span><span>{item.route?.origin?.label||item.route?.origin?.address||"ORIGIN"} → {item.route?.destination?.label||item.route?.destination?.address||"DESTINATION"}</span><span>{item.execution?.carrierName||"CARRIER NOT ASSIGNED"} · {usd(item.economics?.expectedTotal)}</span></button></div>):<div className="fr-empty">NO FREIGHT ORDERS FOR THIS MACHINE.</div>}<div className="fr-actions one"><button className="fr-btn primary" onClick={()=>{setDraft(blankOrder(context));setErrors({});setError("");setMode("new")}}>+ NEW FREIGHT ORDER</button></div></>}
  function NewOrder(){return <><div className="fr-section">ROUTE &amp; RESPONSIBILITY</div><div className="fr-grid">
    <label className="fr-field"><span>PURPOSE</span><select value={draft.purpose} onChange={e=>patch("purpose",e.target.value)}>{IXI_FREIGHT_PURPOSES.map(value=><option key={value} value={value}>{purposeLabel(value)}</option>)}</select></label>
    <label className="fr-field"><span>MODE</span><select value={draft.mode} onChange={e=>patch("mode",e.target.value)}><option value="external-carrier">EXTERNAL CARRIER</option><option value="internal-fleet">INTERNAL FLEET</option></select></label>
    <label className="fr-field wide"><span>CARRIER / TRANSPORTER</span><input className={errors.carrierName?"invalid":""} value={draft.carrierName} onChange={e=>patch("carrierName",e.target.value)}/></label>
    <label className="fr-field"><span>ORIGIN</span><input className={errors.origin?"invalid":""} value={draft.originLabel} onChange={e=>patch("originLabel",e.target.value)}/></label>
    <label className="fr-field"><span>DESTINATION</span><input className={errors.destination?"invalid":""} value={draft.destinationLabel} onChange={e=>patch("destinationLabel",e.target.value)}/></label>
    <label className="fr-field"><span>ORIGIN ADDRESS</span><input value={draft.originAddress} onChange={e=>patch("originAddress",e.target.value)}/></label>
    <label className="fr-field"><span>DESTINATION ADDRESS</span><input value={draft.destinationAddress} onChange={e=>patch("destinationAddress",e.target.value)}/></label>
    <label className="fr-field"><span>MILES</span><input inputMode="decimal" value={draft.routeMiles} onChange={e=>patch("routeMiles",e.target.value)}/></label><label className="fr-field"><span>MACHINE WEIGHT</span><input inputMode="decimal" value={draft.weight} onChange={e=>patch("weight",e.target.value)}/></label>
    <label className="fr-field"><span>REQUESTED PICKUP</span><input type="datetime-local" value={draft.requestedPickupAt} onChange={e=>patch("requestedPickupAt",e.target.value)}/></label><label className="fr-field"><span>EXPECTED DELIVERY</span><input type="datetime-local" value={draft.expectedDeliveryAt} onChange={e=>patch("expectedDeliveryAt",e.target.value)}/></label>
  </div><div className="fr-section">COMMERCIAL CONTROL</div><div className="fr-grid">
    <label className="fr-field"><span>QUOTED</span><input inputMode="decimal" value={draft.quotedAmount} onChange={e=>patch("quotedAmount",e.target.value)}/></label><label className="fr-field"><span>AGREED BASE</span><input inputMode="decimal" value={draft.agreedAmount} onChange={e=>patch("agreedAmount",e.target.value)}/></label>
    <label className="fr-field"><span>PERMITS EST.</span><input inputMode="decimal" value={draft.permitEstimate} onChange={e=>patch("permitEstimate",e.target.value)}/></label><label className="fr-field"><span>ESCORT EST.</span><input inputMode="decimal" value={draft.escortEstimate} onChange={e=>patch("escortEstimate",e.target.value)}/></label>
    <label className="fr-field"><span>FUEL EST.</span><input inputMode="decimal" value={draft.fuelSurchargeEstimate} onChange={e=>patch("fuelSurchargeEstimate",e.target.value)}/></label><label className="fr-field"><span>OTHER EST.</span><input inputMode="decimal" value={draft.otherEstimate} onChange={e=>patch("otherEstimate",e.target.value)}/></label>
    <label className="fr-field"><span>RESPONSIBILITY</span><select value={draft.payer} onChange={e=>patch("payer",e.target.value)}><option value="company">COMPANY</option><option value="buyer">BUYER</option><option value="seller">SELLER</option><option value="customer">CUSTOMER</option></select></label><label className="fr-field"><span>CUSTOMER REBILL</span><select value={draft.customerRebill?"yes":"no"} onChange={e=>patch("customerRebill",e.target.value==="yes")}><option value="no">NO</option><option value="yes">YES</option></select></label>
    <label className="fr-field wide"><span>NOTES / SPECIAL INSTRUCTIONS</span><textarea value={draft.notes} onChange={e=>patch("notes",e.target.value)}/></label>
  </div><div className="fr-actions"><button className="fr-btn" onClick={()=>setMode("queue")}>CANCEL</button><button className="fr-btn primary" disabled={busy} onClick={saveOrder}>{busy?"CREATING…":"CREATE FREIGHT ORDER"}</button></div></>}
  function Order(){return <><div className="fr-kpis"><div className="fr-kpi"><span>EXPECTED</span><strong>{usd(order?.economics?.expectedTotal)}</strong></div><div className="fr-kpi"><span>ACTUAL</span><strong>{usd(order?.economics?.actualTotal)}</strong></div></div><div className="fr-section">ORDER</div><div className="fr-row"><span>PURPOSE</span><b>{purposeLabel(order?.purpose?.type)}</b></div><div className="fr-row"><span>CARRIER</span><b>{order?.execution?.carrierName||"NOT ASSIGNED"}</b></div><div className="fr-row"><span>MODE</span><b>{purposeLabel(order?.execution?.mode)}</b></div><div className="fr-row"><span>RESPONSIBILITY</span><b>{purposeLabel(order?.metadata?.payer||"company")}</b></div><div className="fr-section">ROUTE</div><div className="fr-row"><span>ORIGIN</span><b>{order?.route?.origin?.label||order?.route?.origin?.address||"—"}</b></div><div className="fr-row"><span>DESTINATION</span><b>{order?.route?.destination?.label||order?.route?.destination?.address||"—"}</b></div><div className="fr-row"><span>MILES</span><b>{order?.route?.actualMiles??order?.route?.routeMiles??0}</b></div>{nextAction?<div className="fr-actions one"><button className="fr-btn primary" disabled={busy} onClick={()=>act(nextAction)}>{ACTION_LABEL[nextAction]}</button></div>:null}{nextAction==="dispatch"&&!clean(order?.route?.destination?.containerId||order?.route?.destination?.objectId)?<div className="fr-note">ASSIGN A CANONICAL AOS DESTINATION OBJECT BEFORE DISPATCH. THE ORDER AND INVOICE WORKFLOW REMAIN AVAILABLE.</div>:null}</>}
  function Move(){return <><div className="fr-section">EXECUTION</div>{[["STATUS",purposeLabel(status)],["REQUESTED PICKUP",order?.execution?.requestedPickupAt||"—"],["SCHEDULED PICKUP",order?.execution?.scheduledPickupAt||"—"],["ACTUAL PICKUP",order?.execution?.actualPickupAt||"—"],["EXPECTED DELIVERY",order?.execution?.expectedDeliveryAt||"—"],["ACTUAL DELIVERY",order?.execution?.actualDeliveryAt||"—"],["MOVEMENT",order?.movement?.movementId||"NOT CREATED"]].map(([label,value])=><div className="fr-row" key={label}><span>{label}</span><b>{value}</b></div>)}{nextAction?<div className="fr-actions one"><button className="fr-btn primary" disabled={busy} onClick={()=>act(nextAction)}>{ACTION_LABEL[nextAction]}</button></div>:null}</>}
  function Reconcile(){const canInvoice=!["reconciled","paid","closed","cancelled"].includes(status);return <><div className="fr-kpis"><div className="fr-kpi"><span>APPROVED / EXPECTED</span><strong className={!variance.hasExpected?"unset":""}>{variance.hasExpected?usd(variance.expected):"NOT SET"}</strong></div><div className={`fr-kpi ${variance.approvalRequired?"warn":""}`}><span>INVOICED / ACTUAL</span><strong>{usd(variance.actual)}</strong></div><div className={`fr-kpi ${variance.approvalRequired?"warn":""}`}><span>VARIANCE</span><strong className={!variance.hasExpected?"unset":""}>{variance.hasExpected?usd(variance.variance):"N/A"}</strong></div><div className="fr-kpi"><span>OPEN PAYABLE</span><strong>{usd(order?.financial?.openPayableTotal)}</strong></div></div>
    {canInvoice?<><div className="fr-section">RECORD ACTUAL CARRIER COST</div><div className="fr-grid"><label className="fr-field"><span>TYPE</span><select value={invoice.documentType} onChange={e=>patchInvoice("documentType",e.target.value)}><option value="carrier-invoice">INVOICE</option><option value="carrier-credit">CREDIT</option></select></label><label className="fr-field"><span>INVOICE / CREDIT #</span><input value={invoice.invoiceNumber} onChange={e=>patchInvoice("invoiceNumber",e.target.value)}/></label><label className="fr-field"><span>INVOICE DATE</span><input type="date" value={invoice.invoiceDate} onChange={e=>patchInvoice("invoiceDate",e.target.value)}/></label><label className="fr-field"><span>DUE DATE</span><input type="date" value={invoice.dueDate} onChange={e=>patchInvoice("dueDate",e.target.value)}/></label><label className="fr-field wide actual-total"><span>TOTAL ACTUAL COST</span><input inputMode="decimal" value={invoice.actualCostTotal} onChange={e=>patchInvoice("actualCostTotal",e.target.value)} placeholder="0.00"/></label><div className="fr-hint wide">ENTER THE TOTAL ONLY, OR ITEMIZE IT BELOW. IF BOTH ARE USED, THEY MUST MATCH.</div>{[["freight","BASE FREIGHT"],["fuelSurcharge","FUEL SURCHARGE"],["permits","PERMITS"],["escort","ESCORT"],["detention","DETENTION"],["other","OTHER"]].map(([key,label])=><label className="fr-field" key={key}><span>{label}</span><input inputMode="decimal" value={invoice[key]} onChange={e=>patchInvoice(key,e.target.value)}/></label>)}<label className="fr-field wide"><span>INVOICE DOCUMENT REFERENCE</span><input value={invoice.documentReference} onChange={e=>patchInvoice("documentReference",e.target.value)} placeholder="AWS key / document URL"/></label><label className="fr-field wide"><span>NOTES</span><textarea value={invoice.notes} onChange={e=>patchInvoice("notes",e.target.value)}/></label></div><div className="fr-row total"><span>DOCUMENT TOTAL</span><b>{usd(invoiceTotal)}</b></div><div className="fr-actions one"><button className="fr-btn primary" disabled={busy} onClick={matchInvoice}>{busy?"RECORDING…":"RECORD ACTUAL + CREATE BILL"}</button></div></>:null}
    <div className="fr-section">MATCHED CARRIER DOCUMENTS</div>{(order?.invoices||[]).length?(order.invoices||[]).map(item=><div className={`fr-invoice ${item.documentType==="carrier-credit"?"credit":""}`} key={item.invoiceId}><div><b>{item.invoiceNumber}</b><strong>{item.documentType==="carrier-credit"?"− ":""}{usd(item.amount)}</strong></div><small>{purposeLabel(item.documentType)} · BILL/CREDIT {item.billDocumentId}</small></div>):<div className="fr-empty compact">NO CARRIER DOCUMENTS RECORDED.</div>}
    {status==="billed"?<><label className="fr-check"><input type="checkbox" checked={varianceApproved} onChange={e=>setVarianceApproved(e.target.checked)}/><span>APPROVE VARIANCE ABOVE TOLERANCE ({usd(variance.tolerance)})</span></label><label className="fr-field"><span>RECONCILIATION / VARIANCE NOTE</span><textarea value={varianceNote} onChange={e=>setVarianceNote(e.target.value)}/></label><div className="fr-actions one"><button className="fr-btn good" disabled={busy||variance.approvalRequired&&!varianceApproved} onClick={reconcile}>RECONCILE FREIGHT</button></div></>:null}</>}
  function Audit(){return <><div className="fr-section">IMMUTABLE ACTIVITY</div>{events.length?events.slice().reverse().map((event,index)=><div className="fr-event" key={event.eventId||index}><time>{event.occurredAt||event.createdAt||""} · {event.actorId||"IXI"}</time><strong>{purposeLabel(event.eventType)}</strong></div>):<div className="fr-empty">NO ACTIVITY EVENTS RETURNED.</div>}<div className="fr-section">CONTROL</div><div className="fr-row"><span>REVISION</span><b>{order?.identity?.revision||0}</b></div><div className="fr-row"><span>SCHEMA</span><b>{order?.schema||"—"}</b></div><div className="fr-row"><span>CREATED</span><b>{order?.audit?.createdAt||"—"}</b></div><div className="fr-row"><span>UPDATED</span><b>{order?.audit?.updatedAt||"—"}</b></div></>}

  return <div className="ixi-freight"><div className="fr-head"><div><strong>{mode==="new"?"NEW FREIGHT ORDER":order?.identity?.freightOrderId||"FREIGHT"}</strong><small>IXI TRAN$ACT · MACHINE LOGISTICS</small></div>{mode==="record"?<div className={`fr-status ${statusClass}`}>{purposeLabel(status)}</div>:null}</div>{mode==="record"?<div className="fr-tabs"><button className={tab==="order"?"on":""} onClick={()=>setTab("order")}>ORDER</button><button className={tab==="move"?"on":""} onClick={()=>setTab("move")}>MOVE</button><button className={tab==="reconcile"?"on":""} onClick={()=>setTab("reconcile")}>RECONCILE</button><button className={tab==="audit"?"on":""} onClick={()=>setTab("audit")}>AUDIT</button></div>:null}<div className="fr-body">{loading?<div className="fr-empty">LOADING FREIGHT…</div>:mode==="new"?NewOrder():mode==="record"&&order?(tab==="order"?Order():tab==="move"?Move():tab==="reconcile"?Reconcile():Audit()):Queue()}{error?<div className="fr-error" role="alert">{error}</div>:null}</div><div className="fr-foot"><button onClick={()=>mode==="record"?setMode("queue"):onBack?.()}>{mode==="record"?"ALL FREIGHT":"TRAN$ACT"}</button><button onClick={()=>onBack?.()}>CLOSE</button></div><IXIFreightStyles/></div>
}
