import { useEffect, useMemo, useState } from "react";
import { amendIXIFreightOrder, createIXIFreightOrder, loadIXIFreightEvents, loadIXIFreightOrders, runIXIFreightAction } from "./IXIFreightClient";
import { createIXIFreightOrderInput, freightVariance, IXI_FREIGHT_ACTION_BY_STATUS, IXI_FREIGHT_PURPOSES, validateIXIFreightOrderInput, invoiceCharges } from "./IXIFreightContract";
import { createAndMatchIXIFreightInvoice } from "./IXIFreightCommands";
import IXIFreightStyles from "./IXIFreightStyles";
import { IXI_TRANSACT_LOCALES, useIXITransactLocale } from "../../IXITransactLocale";

const clean=value=>String(value??"").trim();
const usd=(value,locale="en-US")=>Number(value||0).toLocaleString(locale,{style:"currency",currency:"USD"});
const today=()=>new Date().toISOString().slice(0,10);
const commandId=prefix=>`${prefix}-${globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2,8)}`}`;
const purposeLabel=value=>clean(value).replace(/-/g," ").toUpperCase();
const readableDateTime=(value,locale="en-US")=>{const raw=clean(value);if(!raw)return "—";const parsed=new Date(raw);return Number.isNaN(parsed.getTime())?raw:parsed.toLocaleString(locale,{month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit"})};
const editableDateTime=value=>clean(value).slice(0,16);
const FREIGHT_ROW_STYLE={width:"100%",minWidth:0,maxWidth:"100%",display:"grid",gridTemplateColumns:"96px minmax(0,1fr)",alignItems:"start",columnGap:"8px",padding:"5px 0",borderBottom:"1px solid #202823"};
const FREIGHT_ROW_TOTAL_STYLE={marginTop:"4px",borderTop:"1px solid #344039"};
const FREIGHT_LABEL_STYLE={minWidth:0,color:"#939d97"};
const FREIGHT_VALUE_STYLE={display:"block",minWidth:0,maxWidth:"100%",textAlign:"right",whiteSpace:"normal",overflowWrap:"anywhere",wordBreak:"break-word",lineHeight:1.25};

function FreightDataRow({label,value,total=false}){const text=clean(value)||"—";return <div className={`ixi-freight-data-row${total?" total":""}`} data-freight-row={label} style={total?{...FREIGHT_ROW_STYLE,...FREIGHT_ROW_TOTAL_STYLE}:FREIGHT_ROW_STYLE}><span style={FREIGHT_LABEL_STYLE}>{label}</span><b title={text} style={FREIGHT_VALUE_STYLE}>{text}</b></div>}

function blankOrder(context={}){return{
  commandId:commandId("FRT"),purpose:"acquisition-inbound",mode:"external-carrier",carrierName:"",carrierPassportId:"",payer:"company",customerRebill:false,
  originObjectId:"",originLabel:clean(context.location?.label),originAddress:"",destinationObjectId:"",destinationLabel:"",destinationAddress:"",routeMiles:"",weight:"",
  requestedPickupAt:"",scheduledPickupAt:"",expectedDeliveryAt:"",quotedAmount:"",agreedAmount:"",permitEstimate:"",escortEstimate:"",fuelSurchargeEstimate:"",otherEstimate:"",notes:""
}}
function draftFromOrder(order={}){return{
  commandId:commandId("FRT-AMEND"),purpose:clean(order?.purpose?.type||"other"),mode:clean(order?.execution?.mode||"external-carrier"),carrierName:clean(order?.execution?.carrierName),carrierPassportId:clean(order?.execution?.carrierPassportId),payer:clean(order?.metadata?.payer||"company"),customerRebill:Boolean(order?.metadata?.customerRebill),
  originObjectId:clean(order?.route?.origin?.objectId),originLabel:clean(order?.route?.origin?.label),originAddress:clean(order?.route?.origin?.address),destinationObjectId:clean(order?.route?.destination?.containerId||order?.route?.destination?.objectId),destinationLabel:clean(order?.route?.destination?.label),destinationAddress:clean(order?.route?.destination?.address),routeMiles:String(order?.route?.routeMiles??""),weight:String(order?.asset?.weight??""),
  requestedPickupAt:editableDateTime(order?.execution?.requestedPickupAt),scheduledPickupAt:editableDateTime(order?.execution?.scheduledPickupAt),expectedDeliveryAt:editableDateTime(order?.execution?.expectedDeliveryAt),quotedAmount:String(order?.economics?.quotedAmount??""),agreedAmount:String(order?.economics?.agreedAmount??""),permitEstimate:String(order?.economics?.permitEstimate??""),escortEstimate:String(order?.economics?.escortEstimate??""),fuelSurchargeEstimate:String(order?.economics?.fuelSurchargeEstimate??""),otherEstimate:String(order?.economics?.otherEstimate??""),notes:clean(order?.metadata?.notes),changeReason:""
}}
function blankInvoice(){return{documentType:"carrier-invoice",invoiceNumber:"",invoiceDate:today(),dueDate:"",actualCostTotal:"",freight:"",permits:"",escort:"",detention:"",fuelSurcharge:"",other:"",documentReference:"",notes:"",sourceBillDocumentId:""}}
const ACTION_LABEL={request:"REQUEST FREIGHT",award:"AWARD LOAD",dispatch:"DISPATCH",pickup:"PICKED UP",deliver:"DELIVERED"};

export default function IXIFreightApp({context={},object={},onBack=null,onRecordChange=null,onFinancialRecordsChange=null}){
  const {locale,t,setLocale}=useIXITransactLocale();
  const label=value=>t(purposeLabel(value));
  const errorMessage=(err,fallback)=>t(clean(err?.message)||fallback);
  const money=value=>usd(value,locale);
  const dateTime=value=>readableDateTime(value,locale);
  const passportId=clean(context.primary?.passportId||object.passportId);
  const [orders,setOrders]=useState([]),[selectedId,setSelectedId]=useState(""),[mode,setMode]=useState("queue"),[tab,setTab]=useState("order");
  const [draft,setDraft]=useState(()=>blankOrder(context)),[invoice,setInvoice]=useState(blankInvoice),[events,setEvents]=useState([]);
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[errors,setErrors]=useState({}),[varianceApproved,setVarianceApproved]=useState(false),[varianceNote,setVarianceNote]=useState("");
  const order=useMemo(()=>orders.find(item=>clean(item?.identity?.freightOrderId)===selectedId)||null,[orders,selectedId]);
  const variance=freightVariance(order||{}),nextAction=IXI_FREIGHT_ACTION_BY_STATUS[clean(order?.status)],invoiceTotal=invoiceCharges(invoice).amount;

  async function refresh(signal){
    if(!passportId){setError(t("MACHINE PASSPORT IS REQUIRED FOR FREIGHT."));setLoading(false);return}
    try{setLoading(true);const found=await loadIXIFreightOrders(passportId,{signal});setOrders(found);setError("")}catch(err){if(err?.name!=="AbortError")setError(errorMessage(err,"FREIGHT ORDERS COULD NOT LOAD."))}finally{setLoading(false)}
  }
  useEffect(()=>{const controller=new AbortController();refresh(controller.signal);return()=>controller.abort()},[passportId]);
  useEffect(()=>{if(!selectedId){setEvents([]);return}const controller=new AbortController();loadIXIFreightEvents(selectedId,{signal:controller.signal}).then(setEvents).catch(()=>setEvents([]));return()=>controller.abort()},[selectedId,order?.identity?.revision]);
  function patch(key,value){setDraft(current=>({...current,[key]:value}))}
  function patchInvoice(key,value){setInvoice(current=>({...current,[key]:value}))}
  function upsert(next){setOrders(current=>[next,...current.filter(item=>clean(item?.identity?.freightOrderId)!==clean(next?.identity?.freightOrderId))]);setSelectedId(clean(next?.identity?.freightOrderId));return next}
  async function notify(next,action,payload={}){upsert(next);await onRecordChange?.(next,{action,payload});return next}

  async function saveOrder(){
    if(busy)return;const payload=createIXIFreightOrderInput({context,object,input:draft}),validation=validateIXIFreightOrderInput(payload);setErrors(validation.errors);
    if(!validation.valid){setError(t(Object.values(validation.errors)[0]));return}
    const editing=mode==="edit";
    if(editing&&status==="requested"&&!clean(draft.changeReason)){setError(t("A CHANGE REASON IS REQUIRED AFTER FREIGHT HAS BEEN REQUESTED."));return}
    setBusy(true);setError("");try{
      const next=editing
        ?await amendIXIFreightOrder(selectedId,{commandId:commandId("freight-amend"),expectedRevision:Number(order?.identity?.revision||0),changeReason:clean(draft.changeReason),amendment:{
          asset:{weight:payload.asset.weight},purpose:payload.purpose,route:payload.route,
          execution:{mode:payload.execution.mode,carrierName:payload.execution.carrierName,carrierPassportId:payload.execution.carrierPassportId,requestedPickupAt:payload.execution.requestedPickupAt,scheduledPickupAt:payload.execution.scheduledPickupAt,expectedDeliveryAt:payload.execution.expectedDeliveryAt},
          economics:payload.economics,metadata:payload.metadata,
        }})
        :await createIXIFreightOrder(payload);
      await notify(next,editing?"amend":"create");setMode("record");setTab("order")
    }catch(err){setError(errorMessage(err,editing?"FREIGHT ORDER COULD NOT BE UPDATED.":"FREIGHT ORDER COULD NOT BE CREATED."))}finally{setBusy(false)}
  }
  async function act(action,body={}){
    if(!order||busy)return;setBusy(true);setError("");try{const next=await runIXIFreightAction(selectedId,action,{commandId:commandId(`freight-${action}`),...body});await notify(next,action);if(action==="deliver")setTab("reconcile")}catch(err){setError(errorMessage(err,"FREIGHT ACTION FAILED."))}finally{setBusy(false)}
  }
  async function matchInvoice(){
    if(!order||busy)return;setBusy(true);setError("");try{const result=await createAndMatchIXIFreightInvoice({order,input:invoice,context,object});await onFinancialRecordsChange?.();await notify(result.order,"invoice-match",{financialDocumentId:result.financialDocumentId});setInvoice(blankInvoice());setTab("reconcile")}catch(err){setError(errorMessage(err,"CARRIER INVOICE COULD NOT BE MATCHED."))}finally{setBusy(false)}
  }
  async function reconcile(){await act("reconcile",{varianceApproved,varianceNote})}
  const status=clean(order?.status||"draft"),statusClass=["delivered","reconciled","paid","closed"].includes(status)?"good":["cancelled"].includes(status)?"bad":"",canEditOrder=["draft","requested"].includes(status);

  function Queue(){return <><div className="fr-section">{t("MACHINE FREIGHT")}</div>{orders.length?orders.map(item=><div className="fr-card" key={item.identity?.freightOrderId}><button onClick={()=>{setSelectedId(item.identity.freightOrderId);setMode("record");setTab("order")}}><strong>{item.identity?.freightOrderId}</strong><span>{label(item.purpose?.type)} · {label(item.status)}</span><span>{item.route?.origin?.label||item.route?.origin?.address||t("ORIGIN")} → {item.route?.destination?.label||item.route?.destination?.address||t("DESTINATION")}</span><span>{item.execution?.carrierName||t("CARRIER NOT ASSIGNED")} · {money(item.economics?.expectedTotal)}</span></button></div>):<div className="fr-empty">{t("NO FREIGHT ORDERS FOR THIS MACHINE.")}</div>}<div className="fr-actions one"><button className="fr-btn primary" onClick={()=>{setDraft(blankOrder(context));setErrors({});setError("");setMode("new")}}>{t("+ NEW FREIGHT ORDER")}</button></div></>}
  function NewOrder(){return <><div className="fr-section">{t("ROUTE & RESPONSIBILITY")}</div><div className="fr-grid">
    <label className="fr-field"><span>{t("PURPOSE")}</span><select value={draft.purpose} onChange={e=>patch("purpose",e.target.value)}>{IXI_FREIGHT_PURPOSES.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label>
    <label className="fr-field"><span>{t("MODE")}</span><select value={draft.mode} onChange={e=>patch("mode",e.target.value)}><option value="external-carrier">{t("EXTERNAL CARRIER")}</option><option value="internal-fleet">{t("INTERNAL FLEET")}</option></select></label>
    <label className="fr-field wide"><span>{t("CARRIER / TRANSPORTER")}</span><input className={errors.carrierName?"invalid":""} value={draft.carrierName} onChange={e=>patch("carrierName",e.target.value)}/></label>
    <label className="fr-field"><span>{t("ORIGIN")}</span><input className={errors.origin?"invalid":""} value={draft.originLabel} onChange={e=>patch("originLabel",e.target.value)}/></label>
    <label className="fr-field"><span>{t("DESTINATION")}</span><input className={errors.destination?"invalid":""} value={draft.destinationLabel} onChange={e=>patch("destinationLabel",e.target.value)}/></label>
    <label className="fr-field"><span>{t("ORIGIN ADDRESS")}</span><input value={draft.originAddress} onChange={e=>patch("originAddress",e.target.value)}/></label>
    <label className="fr-field"><span>{t("DESTINATION ADDRESS")}</span><input value={draft.destinationAddress} onChange={e=>patch("destinationAddress",e.target.value)}/></label>
    <label className="fr-field"><span>{t("MILES")}</span><input inputMode="decimal" value={draft.routeMiles} onChange={e=>patch("routeMiles",e.target.value)}/></label><label className="fr-field"><span>{t("MACHINE WEIGHT")}</span><input inputMode="decimal" value={draft.weight} onChange={e=>patch("weight",e.target.value)}/></label>
    <label className="fr-field"><span>{t("REQUESTED PICKUP")}</span><input type="datetime-local" value={draft.requestedPickupAt} onChange={e=>patch("requestedPickupAt",e.target.value)}/></label><label className="fr-field"><span>{t("SCHEDULED PICKUP")}</span><input type="datetime-local" value={draft.scheduledPickupAt} onChange={e=>patch("scheduledPickupAt",e.target.value)}/></label><label className="fr-field"><span>{t("EXPECTED DELIVERY")}</span><input type="datetime-local" value={draft.expectedDeliveryAt} onChange={e=>patch("expectedDeliveryAt",e.target.value)}/></label>
  </div><div className="fr-section">{t("COMMERCIAL CONTROL")}</div><div className="fr-grid">
    <label className="fr-field"><span>{t("QUOTED")}</span><input inputMode="decimal" value={draft.quotedAmount} onChange={e=>patch("quotedAmount",e.target.value)}/></label><label className="fr-field"><span>{t("AGREED BASE")}</span><input inputMode="decimal" value={draft.agreedAmount} onChange={e=>patch("agreedAmount",e.target.value)}/></label>
    <label className="fr-field"><span>{t("PERMITS EST.")}</span><input inputMode="decimal" value={draft.permitEstimate} onChange={e=>patch("permitEstimate",e.target.value)}/></label><label className="fr-field"><span>{t("ESCORT EST.")}</span><input inputMode="decimal" value={draft.escortEstimate} onChange={e=>patch("escortEstimate",e.target.value)}/></label>
    <label className="fr-field"><span>{t("FUEL EST.")}</span><input inputMode="decimal" value={draft.fuelSurchargeEstimate} onChange={e=>patch("fuelSurchargeEstimate",e.target.value)}/></label><label className="fr-field"><span>{t("OTHER EST.")}</span><input inputMode="decimal" value={draft.otherEstimate} onChange={e=>patch("otherEstimate",e.target.value)}/></label>
    <label className="fr-field"><span>{t("RESPONSIBILITY")}</span><select value={draft.payer} onChange={e=>patch("payer",e.target.value)}><option value="company">{t("COMPANY")}</option><option value="buyer">{t("BUYER")}</option><option value="seller">{t("SELLER")}</option><option value="customer">{t("CUSTOMER")}</option></select></label><label className="fr-field"><span>{t("CUSTOMER REBILL")}</span><select value={draft.customerRebill?"yes":"no"} onChange={e=>patch("customerRebill",e.target.value==="yes")}><option value="no">{t("NO")}</option><option value="yes">{t("YES")}</option></select></label>
    <label className="fr-field wide"><span>{t("NOTES / SPECIAL INSTRUCTIONS")}</span><textarea value={draft.notes} onChange={e=>patch("notes",e.target.value)}/></label>
    {mode==="edit"&&status==="requested"?<label className="fr-field wide"><span>{t("CHANGE REASON")}</span><textarea value={draft.changeReason} onChange={e=>patch("changeReason",e.target.value)} required/></label>:null}
  </div><div className="fr-actions"><button className="fr-btn" onClick={()=>setMode(mode==="edit"?"record":"queue")}>{t(mode==="edit"?"CANCEL EDIT":"CANCEL")}</button><button className="fr-btn primary" disabled={busy} onClick={saveOrder}>{busy?t(mode==="edit"?"SAVING…":"CREATING…"):t(mode==="edit"?"SAVE CHANGES":"CREATE FREIGHT ORDER")}</button></div></>}
  function Order(){return <><div className="fr-kpis"><div className="fr-kpi"><span>{t("EXPECTED")}</span><strong>{money(order?.economics?.expectedTotal)}</strong></div><div className="fr-kpi"><span>{t("ACTUAL")}</span><strong>{money(order?.economics?.actualTotal)}</strong></div></div><div className="fr-section">{t("ORDER")}</div><FreightDataRow label={t("PURPOSE")} value={label(order?.purpose?.type)}/><FreightDataRow label={t("CARRIER")} value={order?.execution?.carrierName||t("NOT ASSIGNED")}/><FreightDataRow label={t("MODE")} value={label(order?.execution?.mode)}/><FreightDataRow label={t("RESPONSIBILITY")} value={label(order?.metadata?.payer||"company")}/><div className="fr-section">{t("ROUTE")}</div><FreightDataRow label={t("ORIGIN")} value={order?.route?.origin?.label||order?.route?.origin?.address||"—"}/><FreightDataRow label={t("DESTINATION")} value={order?.route?.destination?.label||order?.route?.destination?.address||"—"}/><FreightDataRow label={t("MILES")} value={order?.route?.actualMiles??order?.route?.routeMiles??0}/>{canEditOrder?<div className="fr-actions one"><button className="fr-btn" disabled={busy} onClick={()=>{setDraft(draftFromOrder(order));setErrors({});setError("");setMode("edit")}}>{t("EDIT ORDER")}</button></div>:null}{nextAction?<div className="fr-actions one"><button className="fr-btn primary" disabled={busy} onClick={()=>act(nextAction)}>{t(ACTION_LABEL[nextAction])}</button></div>:null}{nextAction==="dispatch"&&!clean(order?.route?.destination?.containerId||order?.route?.destination?.objectId)?<div className="fr-note">{t("ASSIGN A CANONICAL AOS DESTINATION OBJECT BEFORE DISPATCH. THE ORDER AND INVOICE WORKFLOW REMAIN AVAILABLE.")}</div>:null}</>}
  function Move(){return <><div className="fr-section">{t("EXECUTION")}</div>{[[t("STATUS"),label(status)],[t("REQUESTED PICKUP"),dateTime(order?.execution?.requestedPickupAt)],[t("SCHEDULED PICKUP"),dateTime(order?.execution?.scheduledPickupAt)],[t("ACTUAL PICKUP"),dateTime(order?.execution?.actualPickupAt)],[t("EXPECTED DELIVERY"),dateTime(order?.execution?.expectedDeliveryAt)],[t("ACTUAL DELIVERY"),dateTime(order?.execution?.actualDeliveryAt)],[t("MOVEMENT"),order?.movement?.movementId||t("NOT CREATED")]].map(([rowLabel,value])=><FreightDataRow label={rowLabel} value={value} key={rowLabel}/>)}{nextAction?<div className="fr-actions one"><button className="fr-btn primary" disabled={busy} onClick={()=>act(nextAction)}>{t(ACTION_LABEL[nextAction])}</button></div>:null}</>}
  function Reconcile(){const canInvoice=!["reconciled","paid","closed","cancelled"].includes(status);return <><div className="fr-kpis"><div className="fr-kpi"><span>{t("APPROVED / EXPECTED")}</span><strong className={!variance.hasExpected?"unset":""}>{variance.hasExpected?money(variance.expected):t("NOT SET")}</strong></div><div className={`fr-kpi ${variance.approvalRequired?"warn":""}`}><span>{t("INVOICED / ACTUAL")}</span><strong>{money(variance.actual)}</strong></div><div className={`fr-kpi ${variance.approvalRequired?"warn":""}`}><span>{t("VARIANCE")}</span><strong className={!variance.hasExpected?"unset":""}>{variance.hasExpected?money(variance.variance):"N/A"}</strong></div><div className="fr-kpi"><span>{t("OPEN PAYABLE")}</span><strong>{money(order?.financial?.openPayableTotal)}</strong></div></div>
    {canInvoice?<><div className="fr-section">{t("RECORD ACTUAL CARRIER COST")}</div><div className="fr-grid"><label className="fr-field"><span>{t("TYPE")}</span><select value={invoice.documentType} onChange={e=>patchInvoice("documentType",e.target.value)}><option value="carrier-invoice">{t("INVOICE")}</option><option value="carrier-credit">{t("CREDIT")}</option></select></label><label className="fr-field"><span>{t("INVOICE / CREDIT #")}</span><input value={invoice.invoiceNumber} onChange={e=>patchInvoice("invoiceNumber",e.target.value)}/></label><label className="fr-field"><span>{t("INVOICE DATE")}</span><input type="date" value={invoice.invoiceDate} onChange={e=>patchInvoice("invoiceDate",e.target.value)}/></label><label className="fr-field"><span>{t("DUE DATE")}</span><input type="date" value={invoice.dueDate} onChange={e=>patchInvoice("dueDate",e.target.value)}/></label><label className="fr-field wide actual-total"><span>{t("TOTAL ACTUAL COST")}</span><input inputMode="decimal" value={invoice.actualCostTotal} onChange={e=>patchInvoice("actualCostTotal",e.target.value)} placeholder="0.00"/></label><div className="fr-hint wide">{t("ENTER THE TOTAL ONLY, OR ITEMIZE IT BELOW. IF BOTH ARE USED, THEY MUST MATCH.")}</div>{[["freight","BASE FREIGHT"],["fuelSurcharge","FUEL SURCHARGE"],["permits","PERMITS"],["escort","ESCORT"],["detention","DETENTION"],["other","OTHER"]].map(([key,rowLabel])=><label className="fr-field" key={key}><span>{t(rowLabel)}</span><input inputMode="decimal" value={invoice[key]} onChange={e=>patchInvoice(key,e.target.value)}/></label>)}<label className="fr-field wide"><span>{t("INVOICE DOCUMENT REFERENCE")}</span><input value={invoice.documentReference} onChange={e=>patchInvoice("documentReference",e.target.value)} placeholder={t("AWS KEY / DOCUMENT URL")}/></label><label className="fr-field wide"><span>{t("NOTES")}</span><textarea value={invoice.notes} onChange={e=>patchInvoice("notes",e.target.value)}/></label></div><FreightDataRow label={t("DOCUMENT TOTAL")} value={money(invoiceTotal)} total/><div className="fr-actions one"><button className="fr-btn primary" disabled={busy} onClick={matchInvoice}>{t(busy?"RECORDING…":"RECORD ACTUAL + CREATE BILL")}</button></div></>:null}
    <div className="fr-section">{t("MATCHED CARRIER DOCUMENTS")}</div>{(order?.invoices||[]).length?(order.invoices||[]).map(item=><div className={`fr-invoice ${item.documentType==="carrier-credit"?"credit":""}`} key={item.invoiceId}><div><b>{item.invoiceNumber}</b><strong>{item.documentType==="carrier-credit"?"− ":""}{money(item.amount)}</strong></div><small>{label(item.documentType)} · {t("BILL/CREDIT")} {item.billDocumentId}</small></div>):<div className="fr-empty compact">{t("NO CARRIER DOCUMENTS RECORDED.")}</div>}
    {status==="billed"?<><label className="fr-check"><input type="checkbox" checked={varianceApproved} onChange={e=>setVarianceApproved(e.target.checked)}/><span>{t("APPROVE VARIANCE ABOVE TOLERANCE")} ({money(variance.tolerance)})</span></label><label className="fr-field"><span>{t("RECONCILIATION / VARIANCE NOTE")}</span><textarea value={varianceNote} onChange={e=>setVarianceNote(e.target.value)}/></label><div className="fr-actions one"><button className="fr-btn good" disabled={busy||variance.approvalRequired&&!varianceApproved} onClick={reconcile}>{t("RECONCILE FREIGHT")}</button></div></>:null}</>}
  function Audit(){return <><div className="fr-section">{t("IMMUTABLE ACTIVITY")}</div>{events.length?events.slice().reverse().map((event,index)=><div className="fr-event" key={event.eventId||index}><time>{dateTime(event.occurredAt||event.createdAt)} · {event.actorId||"IXI"}</time><strong>{label(event.eventType)}</strong></div>):<div className="fr-empty">{t("NO ACTIVITY EVENTS RETURNED.")}</div>}<div className="fr-section">{t("CONTROL")}</div><FreightDataRow label={t("REVISION")} value={order?.identity?.revision||0}/><FreightDataRow label={t("SCHEMA")} value={order?.schema||"—"}/><FreightDataRow label={t("CREATED")} value={dateTime(order?.audit?.createdAt)}/><FreightDataRow label={t("UPDATED")} value={dateTime(order?.audit?.updatedAt)}/></>}

  return <div className="ixi-freight"><div className="fr-head"><div><strong>{mode==="new"?t("NEW FREIGHT ORDER"):mode==="edit"?t("EDIT ORDER"):order?.identity?.freightOrderId||t("FREIGHT")}</strong><small>IXI TRAN$ACT · {t("MACHINE LOGISTICS")}</small></div><div className="fr-head-actions"><div className="fr-lang" aria-label="Language"><button className={locale===IXI_TRANSACT_LOCALES.ENGLISH?"on":""} onClick={()=>setLocale(IXI_TRANSACT_LOCALES.ENGLISH)}>ENG</button><span>/</span><button className={locale===IXI_TRANSACT_LOCALES.SPANISH_MEXICO?"on":""} onClick={()=>setLocale(IXI_TRANSACT_LOCALES.SPANISH_MEXICO)}>ESP</button></div>{mode==="record"?<div className={`fr-status ${statusClass}`}>{label(status)}</div>:null}</div></div>{mode==="record"?<div className="fr-tabs"><button className={tab==="order"?"on":""} onClick={()=>setTab("order")}>{t("ORDER")}</button><button className={tab==="move"?"on":""} onClick={()=>setTab("move")}>{t("MOVE")}</button><button className={tab==="reconcile"?"on":""} onClick={()=>setTab("reconcile")}>{t("RECONCILE")}</button><button className={tab==="audit"?"on":""} onClick={()=>setTab("audit")}>{t("AUDIT")}</button></div>:null}<div className="fr-body">{loading?<div className="fr-empty">{t("LOADING FREIGHT…")}</div>:mode==="new"||mode==="edit"?NewOrder():mode==="record"&&order?(tab==="order"?Order():tab==="move"?Move():tab==="reconcile"?Reconcile():Audit()):Queue()}{error?<div className="fr-error" role="alert">{error}</div>:null}</div><div className="fr-foot"><button onClick={()=>mode==="record"||mode==="edit"?setMode("queue"):onBack?.()}>{t(mode==="record"||mode==="edit"?"ALL FREIGHT":"TRAN$ACT")}</button><button onClick={()=>onBack?.()}>{t("CLOSE")}</button></div><IXIFreightStyles/></div>
}
