const clean=v=>String(v??"").trim();const arr=v=>Array.isArray(v)?v:[];const num=v=>Number.isFinite(Number(v))?Number(v):0;const money=v=>Math.round(num(v)*100)/100;const now=()=>new Date().toISOString();
function actor(a={}){return{actorId:clean(a.passportId||a.employeeId||a.userId||a.id),actorLabel:clean(a.displayName||a.name||a.label)};}
function event(type,a={},extra={}){return{eventId:`SQ-${type.toUpperCase()}-${Date.now()}`,type,occurredAt:now(),...actor(a),...extra};}
export function sendIXIServiceQuote(r={},input={},a={}){if(["accepted","converted"].includes(r.status))throw new Error("Accepted quote cannot be resent as a mutable revision");const e=event("quote-sent",a,{revision:r.identity?.revision,channel:clean(input.channel||"email"),recipient:clean(input.recipient)});return{...r,status:"sent",delivery:{...(r.delivery||{}),sentAt:r.delivery?.sentAt||e.occurredAt,lastSentAt:e.occurredAt,channel:e.channel,recipient:e.recipient},activity:[...arr(r.activity),e],audit:{...(r.audit||{}),updatedAt:e.occurredAt}};}
export function markIXIServiceQuoteViewed(r={},a={}){const e=event("quote-viewed",a,{revision:r.identity?.revision});return{...r,status:r.status==="sent"?"viewed":r.status,delivery:{...(r.delivery||{}),viewedAt:e.occurredAt},activity:[...arr(r.activity),e],audit:{...(r.audit||{}),updatedAt:e.occurredAt}};}
export function requestIXIServiceQuoteChanges(r={},input={},a={}){const e=event("changes-requested",a,{message:clean(input.message),revision:r.identity?.revision});return{...r,status:"changes-requested",activity:[...arr(r.activity),e],audit:{...(r.audit||{}),updatedAt:e.occurredAt}};}
export function declineIXIServiceQuote(r={},input={},a={}){const e=event("quote-declined",a,{reason:clean(input.reason),revision:r.identity?.revision});return{...r,status:"declined",acceptance:{...(r.acceptance||{}),status:"declined"},activity:[...arr(r.activity),e],audit:{...(r.audit||{}),updatedAt:e.occurredAt}};}
export function acceptIXIServiceQuote(r={},input={},a={}){const ids=arr(input.acceptedOptionIds).filter(Boolean);const accepted=r.options?.filter(o=>o.required||ids.includes(o.optionId))||[];const authorized=money(accepted.reduce((s,o)=>s+num(o.customerTotal),0)+num(r.commercial?.taxAmount));const e=event("quote-accepted",a,{revision:r.identity?.revision,acceptedOptionIds:accepted.map(o=>o.optionId),authorizedRevenue:authorized,acceptedBy:clean(input.acceptedBy),method:clean(input.method),customerPoNumber:clean(input.customerPoNumber)});return{...r,status:"accepted",economics:{...(r.economics||{}),authorizedRevenue:authorized},acceptance:{status:"accepted",acceptedRevision:r.identity?.revision,acceptedOptionIds:e.acceptedOptionIds,acceptedBy:e.acceptedBy,acceptedAt:e.occurredAt,method:e.method,signatureDocumentId:clean(input.signatureDocumentId),customerPoNumber:e.customerPoNumber},activity:[...arr(r.activity),e],audit:{...(r.audit||{}),updatedAt:e.occurredAt}};}
export function reviseIXIServiceQuote(r={},nextDraft={},input={},a={}){if(r.status==="accepted"||r.status==="converted")throw new Error("Accepted quote is frozen. Use Change Order.");const snapshot={revision:r.identity?.revision,status:r.status,quotedRevenue:r.economics?.quotedRevenue,options:r.options,request:r.request,commercial:r.commercial,delivery:r.delivery,archivedAt:now()};const revision=Math.max(1,num(r.identity?.revision))+1;const e=event("quote-revised",a,{previousRevision:r.identity?.revision,nextRevision:revision,reason:clean(input.reason)});return{...nextDraft,identity:{...(nextDraft.identity||{}),serviceQuoteId:r.identity?.serviceQuoteId,number:r.identity?.number,revision,clientRequestId:r.identity?.clientRequestId},revisions:[...arr(r.revisions),snapshot],status:"draft",activity:[...arr(r.activity),e],audit:{...(r.audit||{}),updatedAt:e.occurredAt}};}
export function addIXIServiceChangeOrder(r={},input={},a={}){if(!["accepted","converted"].includes(r.status))throw new Error("Change Order requires accepted Service Quote");const amount=money(input.amount),e=event("change-order-created",a,{changeOrderId:clean(input.changeOrderId)||`CO-${arr(r.changeOrders).length+1}`,description:clean(input.description),amount,status:"pending"});return{...r,changeOrders:[...arr(r.changeOrders),e],activity:[...arr(r.activity),e],audit:{...(r.audit||{}),updatedAt:e.occurredAt}};}
export function approveIXIServiceChangeOrder(r={},id="",input={},a={}){let delta=0;const occurredAt=now();const changes=arr(r.changeOrders).map(co=>{if(co.changeOrderId!==id)return co;delta=num(co.amount);return{...co,status:"accepted",acceptedAt:occurredAt,acceptedBy:clean(input.acceptedBy),method:clean(input.method)};});const e={eventId:`SQ-CO-ACCEPT-${Date.now()}`,type:"change-order-accepted",occurredAt,...actor(a),changeOrderId:id,amount:delta};return{...r,changeOrders:changes,economics:{...(r.economics||{}),changeOrderAuthorized:money(num(r.economics?.changeOrderAuthorized)+delta),authorizedRevenue:money(num(r.economics?.authorizedRevenue)+delta)},activity:[...arr(r.activity),e],audit:{...(r.audit||{}),updatedAt:occurredAt}};}
export function convertIXIServiceQuoteToWorkOrder(r={},workOrderId="",a={}){if(r.status!=="accepted")throw new Error("Service Quote must be accepted before creating work");const e=event("service-work-order-created",a,{workOrderId:clean(workOrderId)});return{...r,status:"converted",related:{...(r.related||{}),customerServiceWorkOrderId:clean(workOrderId)},activity:[...arr(r.activity),e],audit:{...(r.audit||{}),updatedAt:e.occurredAt}};}
export default{sendIXIServiceQuote,markIXIServiceQuoteViewed,requestIXIServiceQuoteChanges,declineIXIServiceQuote,acceptIXIServiceQuote,reviseIXIServiceQuote,addIXIServiceChangeOrder,approveIXIServiceChangeOrder,convertIXIServiceQuoteToWorkOrder};