const clean=v=>String(v??"").trim();
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const money=v=>Math.round(num(v)*100)/100;
const arr=v=>Array.isArray(v)?v:[];
const obj=v=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
export const IXI_ASSET_SALE_SCHEMA="ixi-asset-sale-v1";
export const IXI_ASSET_SALE_TYPES=Object.freeze(["sale","auction-sale","trade","transfer","total-loss","scrap","other"]);
export function createIXIAssetSaleDraft({context={},input={}}={}){const p=obj(context.primary),a=obj(context.actor),salePrice=money(input.salePrice),received=arr(input.receipts).reduce((s,x)=>s+num(x.amount),0),now=new Date().toISOString();return{schema:IXI_ASSET_SALE_SCHEMA,identity:{saleId:clean(input.saleId),number:clean(input.number),clientRequestId:clean(input.clientRequestId)||`SALE-${Date.now()}`},context:{assetPassportId:clean(p.passportId),assetObjectId:clean(p.objectId),assetObjectType:clean(p.objectType),assetLabel:clean(p.label),entityPassportId:clean(context.entity?.passportId),locationPassportId:clean(context.location?.passportId),locationLabel:clean(context.location?.label),actorPassportId:clean(a.passportId),actorId:clean(a.employeeId||a.userId||a.id),actorLabel:clean(a.displayName||a.name||a.label)},sale:{type:IXI_ASSET_SALE_TYPES.includes(clean(input.type))?clean(input.type):"sale",buyerPassportId:clean(input.buyerPassportId),buyerId:clean(input.buyerId),buyerLabel:clean(input.buyerLabel),buyerContact:clean(input.buyerContact),buyerEmail:clean(input.buyerEmail),buyerPhone:clean(input.buyerPhone),saleDate:clean(input.saleDate),salePrice,currency:"USD",terms:clean(input.terms||"DUE ON SALE"),dueDate:clean(input.dueDate),buyerPoNumber:clean(input.buyerPoNumber),billOfSaleNumber:clean(input.billOfSaleNumber),hoursAtSale:num(input.hoursAtSale),milesAtSale:num(input.milesAtSale),notes:clean(input.notes)},collection:{status:received>=salePrice&&salePrice>0?"paid":"unpaid",receipts:arr(input.receipts),amountReceived:money(received),balanceDue:money(Math.max(0,salePrice-received))},documents:arr(input.documents),passportState:{ownershipState:"sold",custodyState:"buyer",effectiveDate:clean(input.saleDate)},settlement:{status:"not-started",settlementId:""},status:"draft",audit:{createdAt:now,createdBy:clean(a.passportId||a.employeeId||a.userId),createdByLabel:clean(a.displayName||a.name||a.label),updatedAt:now},activity:[]};}
export function validateIXIAssetSale(r={}){const e={};if(!clean(r.context?.assetPassportId||r.context?.assetObjectId))e.asset="required";if(!clean(r.sale?.buyerLabel))e.buyer="required";if(!clean(r.sale?.saleDate))e.saleDate="required";if(!(num(r.sale?.salePrice)>=0))e.salePrice="invalid";return{valid:Object.keys(e).length===0,errors:e};}
export default{createIXIAssetSaleDraft,validateIXIAssetSale,IXI_ASSET_SALE_SCHEMA};