import { useMemo, useState } from "react";

import { createIXIRentalIncome } from "./IXIRentalIncomeCommands";
import { createIXIRentalIncomeDraft, validateIXIRentalIncome } from "./IXIRentalIncomeContract";
import { applyIXIRentalIncomeEconomics, extendIXIRentalIncome, offRentIXIRentalIncome, closeIXIRentalIncome } from "./IXIRentalIncomeRecordEngine";
import IXIRentalIncomeStyles from "./IXIRentalIncomeStyles";

const clean = value => String(value ?? "").trim();
const money = value => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value || 0));
const today = () => new Date().toISOString().slice(0, 10);
const emptyCharge = () => ({ type: "other", label: "", amount: "", recurrence: "one-time", notes: "" });

const COPY = {
  en: { title:"RENTAL INCOME", record:"RENTAL INCOME RECORD", customer:"CUSTOMER / RENTED TO", agreement:"RENTAL AGREEMENT #", start:"ON RENT DATE", expected:"EXPECTED RETURN", rate:"RENTAL RATE", basis:"RATE BASIS", included:"INCLUDED USAGE", overage:"OVERAGE RATE", customerLocation:"CUSTOMER / JOB LOCATION", purpose:"JOB / PURPOSE", contact:"RESPONSIBLE CONTACT", meter:"METER / CONDITION OUT", meterType:"METER TYPE", startMeter:"START METER", fuelOut:"FUEL OUT", conditionOut:"CONDITION OUT", terms:"RENTAL TERMS", delivery:"DELIVERY CHARGE", pickup:"PICKUP CHARGE", waiver:"DAMAGE WAIVER CHARGE", insurance:"INSURANCE CHARGE", environmental:"ENVIRONMENTAL / OTHER", tax:"EST. TAX", deposit:"DEPOSIT", fuelRequirement:"FUEL RETURN REQUIREMENT", otherTerms:"OTHER TERMS", docs:"AGREEMENT / EVIDENCE", notes:"NOTES", startRental:"START RENTAL", startSub:"Create RNTINC record · customer custody + projected revenue", economics:"RENTAL REVENUE", usage:"USAGE", extend:"EXTEND RENTAL", offRent:"OFF RENT", close:"CLOSE RENTAL", history:"ACTIVITY", actualOffRent:"ACTUAL OFF-RENT DATE", endMeter:"ENDING METER", fuelIn:"FUEL IN", conditionIn:"RETURN CONDITION / DAMAGE", returnRef:"RETURN / PICKUP REFERENCE", completeOffRent:"COMPLETE OFF-RENT", newExpected:"NEW EXPECTED RETURN", saveExtension:"SAVE EXTENSION", back:"‹ TRAN$ACT" },
  es: { title:"INGRESO DE RENTA", record:"REGISTRO DE INGRESO DE RENTA", customer:"CLIENTE / RENTADO A", agreement:"CONTRATO DE RENTA #", start:"FECHA DE INICIO", expected:"DEVOLUCIÓN ESPERADA", rate:"TARIFA DE RENTA", basis:"BASE DE TARIFA", included:"USO INCLUIDO", overage:"TARIFA DE EXCESO", customerLocation:"UBICACIÓN DEL CLIENTE / TRABAJO", purpose:"TRABAJO / PROPÓSITO", contact:"CONTACTO RESPONSABLE", meter:"MEDIDOR / CONDICIÓN DE SALIDA", meterType:"TIPO DE MEDIDOR", startMeter:"MEDIDOR INICIAL", fuelOut:"COMBUSTIBLE DE SALIDA", conditionOut:"CONDICIÓN DE SALIDA", terms:"TÉRMINOS DE RENTA", delivery:"CARGO DE ENTREGA", pickup:"CARGO DE RECOGIDA", waiver:"CARGO DE PROTECCIÓN DE DAÑOS", insurance:"CARGO DE SEGURO", environmental:"AMBIENTAL / OTROS", tax:"IMPUESTO EST.", deposit:"DEPÓSITO", fuelRequirement:"REQUISITO DE COMBUSTIBLE", otherTerms:"OTROS TÉRMINOS", docs:"CONTRATO / EVIDENCIA", notes:"NOTAS", startRental:"INICIAR RENTA", startSub:"Crear RNTINC · custodia del cliente + ingreso proyectado", economics:"INGRESOS DE RENTA", usage:"USO", extend:"EXTENDER RENTA", offRent:"TERMINAR RENTA", close:"CERRAR RENTA", history:"ACTIVIDAD", actualOffRent:"FECHA REAL DE DEVOLUCIÓN", endMeter:"MEDIDOR FINAL", fuelIn:"COMBUSTIBLE FINAL", conditionIn:"CONDICIÓN DE DEVOLUCIÓN / DAÑO", returnRef:"REFERENCIA DE DEVOLUCIÓN", completeOffRent:"COMPLETAR DEVOLUCIÓN", newExpected:"NUEVA DEVOLUCIÓN ESPERADA", saveExtension:"GUARDAR EXTENSIÓN", back:"‹ TRAN$ACT" }
};

function Field({ label, children }) { return <div className="rinc-field"><label>{label}</label>{children}</div>; }
function Input({ value, onChange, ...props }) { return <input value={value} onChange={event => onChange(event.target.value)} {...props} />; }
function daysBetween(start, end) { if (!start) return 0; const a = new Date(`${start}T12:00:00`); const b = new Date(`${end || today()}T12:00:00`); if (Number.isNaN(a.getTime()) || Number.isNaN(b.getTime()) || b < a) return 0; return Math.max(1, Math.ceil((b.getTime() - a.getTime()) / 86400000)); }

export default function IXIRentalIncomeApp({ context = {}, object = {}, initialRecord = null, relatedTransactions = [], language = "en", onLanguageChange = null, onBack = null, onRecordChange = null }) {
  const primary = context.primary || {};
  const actor = context.actor || {};
  const [lang, setLang] = useState(language === "es" ? "es" : "en");
  const t = COPY[lang];
  const [record, setRecord] = useState(initialRecord);
  const [saving, setSaving] = useState(false);
  const [errors, setErrors] = useState({});

  const [customerName, setCustomerName] = useState("");
  const [customerContact, setCustomerContact] = useState("");
  const [rentalAgreementNumber, setRentalAgreementNumber] = useState("");
  const [serialNumber, setSerialNumber] = useState(clean(object.serialNumber || object.serial || object.publicData?.serialNumber));
  const [startDate, setStartDate] = useState(today());
  const [expectedReturnDate, setExpectedReturnDate] = useState("");
  const [baseRate, setBaseRate] = useState("");
  const [rateUnit, setRateUnit] = useState("month");
  const [includedUsage, setIncludedUsage] = useState("");
  const [overageRate, setOverageRate] = useState("");
  const [customerLocation, setCustomerLocation] = useState("");
  const [jobOrPurpose, setJobOrPurpose] = useState("");
  const [responsibleContact, setResponsibleContact] = useState("");
  const [meterType, setMeterType] = useState("hours");
  const [startMeter, setStartMeter] = useState(clean(object.hours || object.publicData?.hours));
  const [fuelOut, setFuelOut] = useState("");
  const [conditionOut, setConditionOut] = useState("");
  const [deliveryCharge, setDeliveryCharge] = useState("");
  const [pickupCharge, setPickupCharge] = useState("");
  const [damageWaiverCharge, setDamageWaiverCharge] = useState("");
  const [insuranceCharge, setInsuranceCharge] = useState("");
  const [environmentalFee, setEnvironmentalFee] = useState("");
  const [taxesEstimate, setTaxesEstimate] = useState("");
  const [deposit, setDeposit] = useState("");
  const [fuelReturnRequirement, setFuelReturnRequirement] = useState("");
  const [otherTerms, setOtherTerms] = useState("");
  const [charges, setCharges] = useState([]);
  const [documents, setDocuments] = useState([]);
  const [notes, setNotes] = useState("");

  const [extendOpen, setExtendOpen] = useState(false);
  const [newExpectedReturn, setNewExpectedReturn] = useState("");
  const [extensionNotes, setExtensionNotes] = useState("");
  const [offRentOpen, setOffRentOpen] = useState(false);
  const [actualOffRentDate, setActualOffRentDate] = useState(today());
  const [endMeter, setEndMeter] = useState("");
  const [fuelIn, setFuelIn] = useState("");
  const [conditionIn, setConditionIn] = useState("");
  const [returnReference, setReturnReference] = useState("");

  const input = useMemo(() => ({ customerName, customerContact, rentalAgreementNumber, assetPassportId:primary.passportId, assetObjectId:primary.objectId, assetObjectType:primary.objectType, assetLabel:primary.label, serialNumber, startDate, expectedReturnDate, baseRate, rateUnit, includedUsage, includedUsageUnit:meterType === "miles" ? "miles" : "hours", overageRate, customerLocation, jobOrPurpose, responsibleContact, meterType, startMeter, fuelOut, conditionOut, deliveryCharge, pickupCharge, damageWaiverCharge, insuranceCharge, environmentalFee, taxesEstimate, deposit, fuelReturnRequirement, otherTerms, charges, documents, notes }), [customerName, customerContact, rentalAgreementNumber, primary, serialNumber, startDate, expectedReturnDate, baseRate, rateUnit, includedUsage, overageRate, customerLocation, jobOrPurpose, responsibleContact, meterType, startMeter, fuelOut, conditionOut, deliveryCharge, pickupCharge, damageWaiverCharge, insuranceCharge, environmentalFee, taxesEstimate, deposit, fuelReturnRequirement, otherTerms, charges, documents, notes]);
  const preview = useMemo(() => createIXIRentalIncomeDraft({ context, input }), [context, input]);
  const liveRecord = useMemo(() => record ? applyIXIRentalIncomeEconomics(record, relatedTransactions) : null, [record, relatedTransactions]);

  function changeLang(next) { setLang(next); onLanguageChange?.(next); }
  function updateCharge(index, key, value) { setCharges(list => list.map((item, i) => i === index ? { ...item, [key]: value } : item)); }
  function addDocs(files, type = "document") { const next = Array.from(files || []).map((file, index) => ({ documentId:`RINC-DOC-${Date.now()}-${index}`, type, fileName:file.name, mimeType:file.type, size:file.size, status:"local-pending-upload" })); setDocuments(current => [...current, ...next]); }

  async function startRental() {
    const check = validateIXIRentalIncome(preview); setErrors(check.errors); if (!check.valid) return;
    setSaving(true);
    try { const result = await createIXIRentalIncome({ object:{ ...object, passportId:primary.passportId, objectId:primary.objectId, objectType:primary.objectType, label:primary.label }, context, input, metadata:{ source:"ixi-transact-rental-income" } }); const next = applyIXIRentalIncomeEconomics(result.record, relatedTransactions); setRecord(next); setNewExpectedReturn(next.period?.expectedReturnDate || ""); await onRecordChange?.(next, { action:"create", response:result.response }, context); } finally { setSaving(false); }
  }
  async function saveExtension() { try { const next = applyIXIRentalIncomeEconomics(extendIXIRentalIncome(record, { expectedReturnDate:newExpectedReturn, notes:extensionNotes }, actor), relatedTransactions); setRecord(next); setExtendOpen(false); setExtensionNotes(""); await onRecordChange?.(next, { action:"extend", expectedReturnDate:newExpectedReturn }, context); } catch (error) { setErrors({ extension:error.message }); } }
  async function completeOffRent() { try { const next = applyIXIRentalIncomeEconomics(offRentIXIRentalIncome(record, { actualOffRentDate, endMeter, fuelIn, conditionIn, returnReference }, actor), relatedTransactions, actualOffRentDate); setRecord(next); setOffRentOpen(false); await onRecordChange?.(next, { action:"off-rent", actualOffRentDate }, context); } catch (error) { setErrors({ offRent:error.message }); } }
  async function closeRental() { try { const next = applyIXIRentalIncomeEconomics(closeIXIRentalIncome(record, actor), relatedTransactions, record?.period?.actualOffRentDate); setRecord(next); await onRecordChange?.(next, { action:"close" }, context); } catch (error) { setErrors({ close:error.message }); } }

  if (liveRecord) {
    const r = liveRecord; const isClosed = r.status === "closed"; const isOffRent = r.status === "off-rent" || isClosed; const expected = clean(r.period?.expectedReturnDate); const currentDate = today(); const overdue = !isOffRent && expected && currentDate > expected; const daysOut = daysBetween(r.period?.startDate, r.period?.actualOffRentDate || currentDate); const overage = Number(r.usage?.overageUsage || 0);
    return <div className="ixi-rinc">
      <div className="rinc-top"><div><div className="rinc-kicker">IXI TRAN$ACT</div><div className="rinc-title">{t.record}</div><div className="rinc-id">{r.identity?.number || r.identity?.rentalIncomeId}</div></div><div className="rinc-lang"><button className={lang === "en" ? "on" : ""} onClick={() => changeLang("en")}>ENG</button><button className={lang === "es" ? "on" : ""} onClick={() => changeLang("es")}>ESP</button></div></div>
      <div className="rinc-context"><strong>{r.ownedAsset?.label}</strong><small>OWNED BY US · {isOffRent ? "RETURNED" : "CUSTOMER CUSTODY"} · {r.customer?.name}</small></div>
      <div className={`rinc-status ${isClosed ? "closed" : overdue ? "overdue" : "active"}`}><div className="rinc-status-head"><strong className={isClosed ? "rinc-ok" : overdue ? "rinc-bad" : "rinc-warn"}>{isClosed ? "CLOSED" : isOffRent ? "OFF RENT" : overdue ? "PAST EXPECTED RETURN" : "RENTED OUT"}</strong><b>{daysOut} DAYS</b></div><div className="rinc-metrics"><div className="rinc-metric"><span>ON RENT</span><b>{r.period?.startDate || "—"}</b></div><div className="rinc-metric"><span>{isOffRent ? "OFF RENT" : "EXPECTED"}</span><b>{r.period?.actualOffRentDate || r.period?.expectedReturnDate || "—"}</b></div><div className="rinc-metric"><span>RATE</span><b>{money(r.rate?.baseRate)} / {clean(r.rate?.unit).toUpperCase()}</b></div></div>{overdue ? <div className="rinc-callout rinc-bad">Asset remains in customer custody after the expected return date. Projected rental revenue continues until OFF RENT is recorded.</div> : null}</div>
      <div className="rinc-section">{t.economics}</div><div className="rinc-money"><span>PROJECTED BASE</span><b>{money(r.economics?.projectedBaseRevenue)}</b></div><div className="rinc-money"><span>PROJECTED OVERAGE</span><b className={Number(r.economics?.projectedOverageRevenue || 0) > 0 ? "rinc-overage" : ""}>{money(r.economics?.projectedOverageRevenue)}</b></div><div className="rinc-money"><span>PROJECTED ANCILLARY</span><b>{money(r.economics?.projectedAncillaryRevenue)}</b></div><div className="rinc-total"><span>PROJECTED RENTAL REVENUE</span><strong>{money(r.economics?.projectedRevenue)}</strong></div><div className="rinc-money"><span>INVOICED</span><b>{money(r.economics?.invoicedRevenue)}</b></div><div className="rinc-money"><span>RECEIVED</span><b>{money(r.economics?.receivedRevenue)}</b></div><div className="rinc-money"><span>OUTSTANDING A/R</span><b>{money(r.economics?.outstandingReceivable)}</b></div><div className="rinc-callout">Rental Income tracks the agreement, custody, usage and projected asset income. Customer invoices and payments remain separate canonical records.</div>
      <div className="rinc-section">{t.usage}</div><div className="rinc-metrics"><div className="rinc-metric"><span>START {clean(r.usage?.meterType).toUpperCase()}</span><b>{r.usage?.startMeter ?? "—"}</b></div><div className="rinc-metric"><span>USED</span><b>{r.usage?.usage || 0}</b></div><div className="rinc-metric"><span>OVERAGE</span><b className={overage > 0 ? "rinc-overage" : ""}>{overage}</b></div></div><div className="rinc-row"><div className="rinc-row-top"><strong>CUSTOMER</strong><b>{r.customer?.name}</b></div><small>{r.customer?.rentalAgreementNumber ? `AGREEMENT ${r.customer.rentalAgreementNumber}` : "NO AGREEMENT NUMBER"}</small></div>
      {!isOffRent ? <><div className="rinc-action-grid"><button className="rinc-secondary" onClick={() => { setNewExpectedReturn(r.period?.expectedReturnDate || ""); setExtendOpen(v => !v); }}>{t.extend}</button><button className="rinc-primary" onClick={() => setOffRentOpen(v => !v)}>{t.offRent}</button></div>{extendOpen ? <div className="rinc-row"><Field label={t.newExpected}><input type="date" value={newExpectedReturn} onChange={e => setNewExpectedReturn(e.target.value)} /></Field><Field label="EXTENSION NOTE"><Input value={extensionNotes} onChange={setExtensionNotes} /></Field><button className="rinc-primary" onClick={saveExtension}>{t.saveExtension}</button></div> : null}{offRentOpen ? <div className="rinc-row"><Field label={t.actualOffRent}><input type="date" value={actualOffRentDate} onChange={e => setActualOffRentDate(e.target.value)} /></Field><div className="rinc-grid2"><Field label={t.endMeter}><Input value={endMeter} onChange={setEndMeter} inputMode="decimal" /></Field><Field label={t.fuelIn}><Input value={fuelIn} onChange={setFuelIn} /></Field></div><Field label={t.conditionIn}><textarea value={conditionIn} onChange={e => setConditionIn(e.target.value)} /></Field><Field label={t.returnRef}><Input value={returnReference} onChange={setReturnReference} /></Field><button className="rinc-primary" onClick={completeOffRent}>{t.completeOffRent}</button></div> : null}</> : !isClosed ? <button className="rinc-primary" onClick={closeRental}>{t.close}</button> : null}
      <div className="rinc-section">{t.history}</div><div className="rinc-history">{(r.activity || []).slice().reverse().map(item => <div className="rinc-row" key={item.eventId}><div className="rinc-row-top"><strong>{clean(item.type).replace(/-/g, " ").toUpperCase()}</strong><b>{clean(item.nextExpectedReturnDate || item.actualOffRentDate || "")}</b></div><small>{item.actorLabel || r.audit?.createdByLabel} · {item.occurredAt}</small></div>)}</div>{Object.keys(errors).length ? <div className="rinc-error">{Object.values(errors).join(" · ")}</div> : null}<button className="rinc-secondary" onClick={() => onBack?.()}>{t.back}</button><div className="rinc-foot">The asset remains ours throughout the rental. OFF RENT ends customer custody and stops projected rental revenue.</div><IXIRentalIncomeStyles />
    </div>;
  }

  return <div className="ixi-rinc">
    <div className="rinc-top"><div><div className="rinc-kicker">IXI TRAN$ACT</div><div className="rinc-title">{t.title}</div></div><div className="rinc-lang"><button className={lang === "en" ? "on" : ""} onClick={() => changeLang("en")}>ENG</button><button className={lang === "es" ? "on" : ""} onClick={() => changeLang("es")}>ESP</button></div></div>
    <div className="rinc-context"><strong>{primary.label || "SELECT OWNED ASSET"}</strong><small>OWNED ASSET · {context.location?.label || "NO LOCATION"} · {clean(actor.displayName || actor.name || actor.label) || "NO EMPLOYEE"}</small></div>
    <div className="rinc-section">CUSTOMER / RENTAL</div><Field label={t.customer}><Input value={customerName} onChange={setCustomerName} /></Field><div className="rinc-grid2"><Field label="CUSTOMER CONTACT"><Input value={customerContact} onChange={setCustomerContact} /></Field><Field label={t.agreement}><Input value={rentalAgreementNumber} onChange={setRentalAgreementNumber} /></Field></div><Field label="ASSET SERIAL / UNIT #"><Input value={serialNumber} onChange={setSerialNumber} /></Field>
    <div className="rinc-section">PERIOD / RATE</div><div className="rinc-grid2"><Field label={t.start}><input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} /></Field><Field label={t.expected}><input type="date" value={expectedReturnDate} onChange={e => setExpectedReturnDate(e.target.value)} /></Field></div><div className="rinc-grid2"><Field label={t.rate}><Input value={baseRate} onChange={setBaseRate} inputMode="decimal" /></Field><Field label={t.basis}><select value={rateUnit} onChange={e => setRateUnit(e.target.value)}><option value="hour">HOUR</option><option value="day">DAY</option><option value="week">WEEK</option><option value="month">MONTH</option></select></Field></div><div className="rinc-grid2"><Field label={t.included}><Input value={includedUsage} onChange={setIncludedUsage} inputMode="decimal" /></Field><Field label={t.overage}><Input value={overageRate} onChange={setOverageRate} inputMode="decimal" /></Field></div>
    <div className="rinc-section">CUSTOMER CUSTODY</div><Field label={t.customerLocation}><Input value={customerLocation} onChange={setCustomerLocation} /></Field><Field label={t.purpose}><Input value={jobOrPurpose} onChange={setJobOrPurpose} /></Field><Field label={t.contact}><Input value={responsibleContact} onChange={setResponsibleContact} /></Field>
    <div className="rinc-section">{t.meter}</div><div className="rinc-grid2"><Field label={t.meterType}><select value={meterType} onChange={e => setMeterType(e.target.value)}><option value="hours">HOURS</option><option value="miles">MILES</option><option value="none">NONE</option></select></Field><Field label={t.startMeter}><Input value={startMeter} onChange={setStartMeter} inputMode="decimal" /></Field></div><Field label={t.fuelOut}><Input value={fuelOut} onChange={setFuelOut} placeholder="FULL / 3/4 / 50%" /></Field><Field label={t.conditionOut}><textarea value={conditionOut} onChange={e => setConditionOut(e.target.value)} /></Field>
    <div className="rinc-section">{t.terms}</div><div className="rinc-grid2"><Field label={t.delivery}><Input value={deliveryCharge} onChange={setDeliveryCharge} inputMode="decimal" /></Field><Field label={t.pickup}><Input value={pickupCharge} onChange={setPickupCharge} inputMode="decimal" /></Field><Field label={t.waiver}><Input value={damageWaiverCharge} onChange={setDamageWaiverCharge} inputMode="decimal" /></Field><Field label={t.insurance}><Input value={insuranceCharge} onChange={setInsuranceCharge} inputMode="decimal" /></Field><Field label={t.environmental}><Input value={environmentalFee} onChange={setEnvironmentalFee} inputMode="decimal" /></Field><Field label={t.tax}><Input value={taxesEstimate} onChange={setTaxesEstimate} inputMode="decimal" /></Field></div><Field label={t.deposit}><Input value={deposit} onChange={setDeposit} inputMode="decimal" /></Field><Field label={t.fuelRequirement}><Input value={fuelReturnRequirement} onChange={setFuelReturnRequirement} /></Field><Field label={t.otherTerms}><textarea value={otherTerms} onChange={e => setOtherTerms(e.target.value)} /></Field>
    <div className="rinc-section">ADDITIONAL CHARGES</div>{charges.map((charge, index) => <div className="rinc-row" key={index}><div className="rinc-grid2"><Field label="TYPE"><select value={charge.type} onChange={e => updateCharge(index, "type", e.target.value)}><option value="other">OTHER</option><option value="delivery">DELIVERY</option><option value="pickup">PICKUP</option><option value="fuel">FUEL</option><option value="waiver">DAMAGE WAIVER</option><option value="environmental">ENVIRONMENTAL</option></select></Field><Field label="AMOUNT"><Input value={charge.amount} onChange={v => updateCharge(index, "amount", v)} inputMode="decimal" /></Field></div><Field label="LABEL"><Input value={charge.label} onChange={v => updateCharge(index, "label", v)} /></Field><button className="rinc-secondary" onClick={() => setCharges(list => list.filter((_, i) => i !== index))}>REMOVE</button></div>)}<button className="rinc-secondary" onClick={() => setCharges(list => [...list, emptyCharge()])}>+ ADD CHARGE</button>
    <div className="rinc-total"><span>STARTING PROJECTED REVENUE</span><strong>{money(Number(baseRate || 0) + Number(deliveryCharge || 0) + Number(pickupCharge || 0) + Number(damageWaiverCharge || 0) + Number(insuranceCharge || 0) + Number(environmentalFee || 0) + Number(taxesEstimate || 0))}</strong></div>
    <div className="rinc-section">{t.docs}</div><div className="rinc-docs"><label><input type="file" accept="application/pdf,image/*" hidden multiple onChange={e => addDocs(e.target.files, "rental-agreement")} /><button type="button" onClick={e => e.currentTarget.parentElement.querySelector("input").click()}>+ RENTAL AGREEMENT</button></label><label><input type="file" accept="image/*" hidden multiple onChange={e => addDocs(e.target.files, "condition-photo")} /><button type="button" onClick={e => e.currentTarget.parentElement.querySelector("input").click()}>+ OUT CONDITION PHOTOS</button></label><label><input type="file" accept="application/pdf,image/*" hidden multiple onChange={e => addDocs(e.target.files, "delivery-ticket")} /><button type="button" onClick={e => e.currentTarget.parentElement.querySelector("input").click()}>+ DELIVERY TICKET</button></label><label><input type="file" accept="application/pdf,image/*" hidden multiple onChange={e => addDocs(e.target.files, "other")} /><button type="button" onClick={e => e.currentTarget.parentElement.querySelector("input").click()}>+ OTHER</button></label></div>{documents.length ? <div className="rinc-row"><small>{documents.length} document(s) staged for canonical attachment.</small></div> : null}
    <Field label={t.notes}><textarea value={notes} onChange={e => setNotes(e.target.value)} /></Field>{Object.keys(errors).length ? <div className="rinc-error">CUSTOMER, OWNED ASSET, START DATE, EXPECTED RETURN AND RATE ARE REQUIRED.</div> : null}<button className="rinc-primary" onClick={startRental} disabled={saving}>{saving ? "STARTING..." : t.startRental}<small style={{ display:"block", fontSize:5 }}>{t.startSub}</small></button><button className="rinc-secondary" onClick={() => onBack?.()}>{t.back}</button><div className="rinc-foot">Rental Income does not transfer ownership. It records temporary customer custody and projects revenue until OFF RENT.</div><IXIRentalIncomeStyles />
  </div>;
}
