import{createIXIAosFinancialObjectReference,mergeIXIAosFinancialReferences}from"../../../financial-runtime/IXIAosFinancialRuntimeAdapter";
import{createIXITransactJournalEntry,postIXITransactJournalEntry,closeIXITransactPeriod}from"../../../financial-runtime/IXITransactDesktopClient";
import{runIXIActionNoticeLifecycle}from"../../../../ixi-object-system/IXIActionNoticeEngine";
import{validateIXIJournalEntry}from"./IXIGeneralLedgerContract";
const clean=v=>String(v??"").trim();const num=v=>Number.isFinite(Number(v))?Number(v):0;
function refs(context={},journal=null){const list=[];for(const[candidate,role]of[[context.entity||{},"entity"],[context.location||{},"location"],[context.actor||{},"employee"]]){const ref=createIXIAosFinancialObjectReference({object:candidate,role});if(ref)list.push(ref);}if(journal?.source?.financialDocumentId)list.push({externalId:journal.source.financialDocumentId,role:"source-financial-document",label:journal.source.documentNumber||journal.source.financialDocumentId,objectType:journal.source.documentType||"financial-document"});return mergeIXIAosFinancialReferences(list);}
function responseId(response={}){return clean(response.financialDocument?.financialDocumentId||response.data?.record?.financialDocument?.financialDocumentId||response.record?.financialDocument?.financialDocumentId||response.financialDocument?.documentId||response.document?.documentId||response.record?.documentId||response.id);}
function responseRevision(response={}){const revision=Number(response.record?.server?.revision??response.persistence?.data?.record?.server?.revision??response.data?.record?.server?.revision);return Number.isInteger(revision)&&revision>0?revision:0;}
export async function postIXIJournalEntry({object={},context={},journal={},metadata={},signal}={}){const check=validateIXIJournalEntry(journal);if(!check.valid){const e=new Error("Journal Entry is incomplete or unbalanced.");e.validation=check;throw e;}const sourceId=clean(journal.source?.financialDocumentId),ruleVersion=clean(journal.posting?.ruleVersion),commandId=clean(journal.identity?.journalEntryId)||`JE-${Date.now()}`,references=refs(context,journal),idempotencyRoot=`ixi-gl:${sourceId||commandId}:${ruleVersion||"manual"}`;let draftResponse=null;const response=await runIXIActionNoticeLifecycle({objectId:clean(context.primary?.objectId||context.primary?.passportId||object.objectId||object.passportId),commandId,source:"ixi-transact-general-ledger",savingMessage:"VALIDATING AND POSTING JOURNAL...",successMessage:"JOURNAL POSTED",errorMessage:error=>clean(error?.message)||"JOURNAL POST FAILED — DRAFT PRESERVED",operation:async()=>{draftResponse=await createIXITransactJournalEntry({documentNumber:clean(journal.identity?.number),documentDate:`${clean(journal.period)}-01`,period:clean(journal.period),currency:"USD",status:"draft",financialState:"draft",description:clean(journal.description),sourceFinancialDocumentId:sourceId,sourceDocumentType:clean(journal.source?.documentType),sourceDocumentNumber:clean(journal.source?.documentNumber),postingRuleId:clean(journal.posting?.ruleId),postingRuleVersion:ruleVersion,lines:journal.lines,dimensions:journal.dimensions,totalDebit:num(journal.totals?.debits),totalCredit:num(journal.totals?.credits),references,metadata:{reversalOf:clean(journal.posting?.reversalOf),...metadata}},{commandId:`${commandId}:draft`,idempotencyKey:`${idempotencyRoot}:draft`,signal,metadata:{...metadata,transactModule:"general-ledger",glEvent:"journal-draft",sourceFinancialDocumentId:sourceId,period:clean(journal.period),ruleVersion}});const financialDocumentId=responseId(draftResponse),expectedRevision=responseRevision(draftResponse);if(!financialDocumentId||!expectedRevision)throw new Error("Journal draft persisted without a postable document revision.");return postIXITransactJournalEntry({financialDocumentId,expectedRevision,commandId:`${commandId}:post`,idempotencyKey:`${idempotencyRoot}:post`,signal,metadata:{...metadata,transactModule:"general-ledger",glEvent:"journal-post",sourceFinancialDocumentId:sourceId,period:clean(journal.period),ruleVersion}});}});const postedAt=new Date().toISOString();return{response,draftResponse,record:{...journal,identity:{...(journal.identity||{}),journalEntryId:responseId(response)||responseId(draftResponse)||journal.identity?.journalEntryId},posting:{...(journal.posting||{}),status:"posted",postedAt},audit:{...(journal.audit||{}),updatedAt:postedAt},activity:[...(journal.activity||[]),{eventId:`GL-POST-${Date.now()}`,type:"journal-posted",occurredAt:postedAt,actorLabel:clean(context.actor?.displayName||context.actor?.name||context.actor?.label)}]}};}
export async function postIXIPeriodClose({context={},period={},metadata={},signal}={}){const value=clean(period.period||period.identity?.number),commandId=`CLOSE-${value}`;return closeIXITransactPeriod({period:value,currency:"USD",commandId,idempotencyKey:`ixi-gl-period-close:${clean(period.entityPassportId)}:${value}`,metadata:{...metadata,transactModule:"general-ledger",glEvent:"period-close"},signal});}
export default{postIXIJournalEntry,postIXIPeriodClose};
