import{createIXIJournalEntry,IXI_GL_RULE_VERSION}from"./IXIGeneralLedgerContract";
const clean=v=>String(v??"").trim();const num=v=>Number.isFinite(Number(v))?Number(v):0;const money=v=>Math.round(num(v)*100)/100;const arr=v=>Array.isArray(v)?v:[];
function source(r={}){return r.input||r.financialDocument?.input||r.document?.input||r;}
function docType(r={}){return clean(r.documentType||r.type||r.financialDocument?.documentType||r.document?.documentType||r.metadata?.documentType).toLowerCase();}
function docId(r={}){return clean(r.documentId||r.id||r.financialDocument?.documentId||r.document?.documentId||r.identity?.billDocumentId||r.identity?.invoiceId||r.identity?.serviceInvoiceId||r.identity?.saleId);}
function docNumber(r={}){const s=source(r);return clean(s.documentNumber||s.invoiceNumber||r.documentNumber||r.identity?.number||r.identity?.billNumber||r.metadata?.saleNumber||docId(r));}
function amount(r={}){const s=source(r);return money(s.amount??s.total??s.subtotal??r.amount??r.financialDocument?.amount);}
function ref(r={},role=""){const refs=arr(source(r).references||r.references||r.financialDocument?.references);return refs.find(x=>clean(x.role).toLowerCase()===role)||null;}
function dimensions(r={}){return{entityPassportId:clean(ref(r,"entity")?.passportId),locationPassportId:clean(ref(r,"location")?.passportId),assetPassportId:clean(ref(r,"asset")?.passportId),customerPassportId:clean(ref(r,"customer")?.passportId),vendorPassportId:clean(ref(r,"vendor")?.passportId),workOrderId:clean(ref(r,"work-order")?.externalId),purchaseOrderId:clean(ref(r,"purchase-order")?.externalId)};}
function periodOf(r={}){const s=source(r),raw=clean(s.documentDate||s.invoiceDate||s.effectiveDate||s.occurredAt||r.createdAt||r.audit?.createdAt);if(/^\d{4}-\d{2}/.test(raw))return raw.slice(0,7);const d=new Date(raw||Date.now());return Number.isNaN(d.getTime())?"":`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;}
function category(r={}){return clean(source(r).category||r.category||r.metadata?.category).toLowerCase();}
function accountName(chart={},code=""){return chart.accounts?.find(a=>a.code===code)?.name||code;}
function line(chart,code,side,value,memo="",dims={}){return{accountCode:code,accountName:accountName(chart,code),debit:side==="debit"?money(value):0,credit:side==="credit"?money(value):0,memo,dimensions:dims};}
function expenseAccount(r={}){const c=category(r);if(c.includes("fuel"))return"6200";if(c.includes("freight")||c.includes("transport"))return"6300";if(c.includes("tech"))return"6400";if(c.includes("repair")||c.includes("service")||c.includes("maintenance")||c.includes("part"))return"6110";return"6900";}
function revenueAccount(r={}){const s=source(r),kind=clean(s.invoiceType||r.metadata?.invoiceType||r.metadata?.transactModule).toLowerCase();if(kind.includes("service"))return"4300";if(kind.includes("rental"))return"4200";if(kind.includes("sale")||r.metadata?.assetSale)return"4100";return"4100";}
function cashAccount(r={}){const s=source(r),id=clean(s.accountId||r.metadata?.accountId);if(id&&clean(s.accountName).toLowerCase().includes("payroll"))return"1020";if(id&&clean(s.accountName).toLowerCase().includes("petty"))return"1050";return"1010";}
function matchedCustomRule(record={},rules=[]){const type=docType(record),cat=category(record);return arr(rules).filter(r=>r.active!==false).sort((a,b)=>num(b.priority)-num(a.priority)).find(r=>(!clean(r.documentType)||clean(r.documentType).toLowerCase()===type)&&(!clean(r.categoryContains)||cat.includes(clean(r.categoryContains).toLowerCase())))||null;}
export function classifyIXIFinancialDocument({record={},chart={},rules=[],actor={}}={}){const type=docType(record),amt=amount(record),s=source(record),dims=dimensions(record),period=periodOf(record),entityPassportId=clean(dims.entityPassportId||chart.entityPassportId),custom=matchedCustomRule(record,rules);if(!docId(record))return{status:"exception",reason:"missing-source-document-id",source:record};if(!(amt>0)&&type!=="work-order"&&type!=="purchase-order"&&type!=="quote")return{status:"exception",reason:"missing-positive-amount",source:record};if(custom){const lines=[line(chart,custom.debitAccount,"debit",amt,custom.memo||docNumber(record),dims),line(chart,custom.creditAccount,"credit",amt,custom.memo||docNumber(record),dims)];return{status:"ready",ruleId:clean(custom.ruleId||"custom"),journal:createIXIJournalEntry({sourceDocument:{documentId:docId(record),documentType:type,documentNumber:docNumber(record)},period,entityPassportId,description:clean(custom.description||`${type} ${docNumber(record)}`),lines,dimensions:dims,ruleId:clean(custom.ruleId||"custom"),ruleVersion:clean(custom.version||IXI_GL_RULE_VERSION),actor})};}
 let ruleId="",lines=[];
 if(type==="invoice"){ruleId="invoice-receivable";lines=[line(chart,"1100","debit",amt,docNumber(record),dims),line(chart,revenueAccount(record),"credit",amt,docNumber(record),dims)];}
 else if(type==="bill"){ruleId="bill-payable";const cap=Boolean(s.capitalizable||r.metadata?.capitalizable||r.metadata?.acquisitionPeriod);lines=[line(chart,cap?"1510":expenseAccount(record),"debit",amt,docNumber(record),dims),line(chart,"2000","credit",amt,docNumber(record),dims)];}
 else if(type==="expense"){ruleId="expense-paid";const paidWith=clean(s.paymentMethod||s.paidWith||r.metadata?.paymentMethod).toLowerCase(),credit=paidWith.includes("card")?"2100":cashAccount(record);lines=[line(chart,expenseAccount(record),"debit",amt,docNumber(record),dims),line(chart,credit,"credit",amt,docNumber(record),dims)];}
 else if(type==="payment"){const dir=clean(s.direction||s.financialState).toLowerCase(),cls=clean(s.transactionClass||r.metadata?.transactionClass).toLowerCase();if(cls==="account-transfer"){ruleId="treasury-transfer";lines=[line(chart,clean(s.toAccountName).toLowerCase().includes("payroll")?"1020":"1010","debit",amt,docNumber(record),dims),line(chart,clean(s.fromAccountName).toLowerCase().includes("payroll")?"1020":"1010","credit",amt,docNumber(record),dims)];}else if(cls==="opening-balance"){ruleId="treasury-opening";lines=[line(chart,cashAccount(record),"debit",amt,docNumber(record),dims),line(chart,"3000","credit",amt,docNumber(record),dims)];}else if(cls==="cash-adjustment"){ruleId="treasury-adjustment";const inbound=dir==="in"||dir==="received";lines=inbound?[line(chart,cashAccount(record),"debit",amt,docNumber(record),dims),line(chart,"3000","credit",amt,docNumber(record),dims)]:[line(chart,"6900","debit",amt,docNumber(record),dims),line(chart,cashAccount(record),"credit",amt,docNumber(record),dims)];}else if(dir==="in"||dir==="received"){ruleId="payment-received";lines=[line(chart,cashAccount(record),"debit",amt,docNumber(record),dims),line(chart,"1100","credit",amt,docNumber(record),dims)];}else if(dir==="out"||dir==="paid"){ruleId="payment-paid";lines=[line(chart,"2000","debit",amt,docNumber(record),dims),line(chart,cashAccount(record),"credit",amt,docNumber(record),dims)];}}
 else if(type==="credit"){const dir=clean(s.direction||r.direction).toLowerCase();if(dir==="in"){ruleId="vendor-credit";lines=[line(chart,"2000","debit",amt,docNumber(record),dims),line(chart,expenseAccount(record),"credit",amt,docNumber(record),dims)];}else{ruleId="customer-credit";lines=[line(chart,revenueAccount(record),"debit",amt,docNumber(record),dims),line(chart,"1100","credit",amt,docNumber(record),dims)];}}
 else if(["purchase-order","quote","work-order","time-entry","collection","payables-control","settlement"].includes(type))return{status:"non-posting",reason:"operational-or-memo-document",source:record};
 else return{status:"exception",reason:`no-posting-rule:${type||"unknown"}`,source:record};
 const journal=createIXIJournalEntry({sourceDocument:{documentId:docId(record),documentType:type,documentNumber:docNumber(record)},period,entityPassportId,description:`${type.toUpperCase()} · ${docNumber(record)}`,lines,dimensions:dims,ruleId,ruleVersion:IXI_GL_RULE_VERSION,actor});return{status:journal.totals.balanced?"ready":"exception",reason:journal.totals.balanced?"":"unbalanced",ruleId,journal,source:record};}
export function buildIXIGLPostingProjection({financialRecords=[],chart={},rules=[],postedJournals=[],actor={}}={}){const postedSourceIds=new Set(arr(postedJournals).filter(j=>j.posting?.status==="posted"&&!j.posting?.reversedBy).map(j=>clean(j.source?.financialDocumentId)).filter(Boolean)),results=arr(financialRecords).map(r=>classifyIXIFinancialDocument({record:r,chart,rules,actor})),ready=results.filter(x=>x.status==="ready"&&!postedSourceIds.has(clean(x.journal?.source?.financialDocumentId))),exceptions=results.filter(x=>x.status==="exception"),nonPosting=results.filter(x=>x.status==="non-posting"),alreadyPosted=results.filter(x=>x.journal&&postedSourceIds.has(clean(x.journal.source.financialDocumentId)));return{ready,exceptions,nonPosting,alreadyPosted,counts:{total:results.length,ready:ready.length,exceptions:exceptions.length,nonPosting:nonPosting.length,posted:alreadyPosted.length}};}
export default{classifyIXIFinancialDocument,buildIXIGLPostingProjection};