import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
async function importSource(relativePath){const absolute=path.resolve(process.cwd(),relativePath),source=await fs.readFile(absolute,"utf8"),encoded=Buffer.from(`${source}\n//# sourceURL=${pathToFileURL(absolute).href}`).toString("base64");return import(`data:text/javascript;base64,${encoded}`)}
const adapter=await importSource("components/ixi-transact-dashboard/data/IXITransactDesktopWorkspaceAdapter.js"),executiveAdapter=await importSource("components/ixi-transact-dashboard/data/IXITransactDashboardProjectionAdapter.js"),queryContract=await importSource("components/ixi-transact-dashboard/data/IXITransactDashboardQueryContract.js"),actionRegistry=await importSource("components/ixi-transact-dashboard/data/IXITransactRecordActionRegistry.js");
const emptyExecutive=executiveAdapter.createIXIExecutiveDesktopModel({});assert.equal(emptyExecutive.kpis.revenue,null,"Missing Executive revenue must remain unknown, not fabricated zero.");assert.equal(emptyExecutive.kpis.cash,null,"Missing Executive cash must remain unknown, not fabricated zero.");assert.equal(emptyExecutive.financialPosition.assets,null,"Missing balance-sheet truth must remain unknown.");
const emptyAR=adapter.createIXIARDesktopModel({});assert.deepEqual(emptyAR.receivables,[]);assert.equal(emptyAR.totals.totalAR,null);assert.equal(emptyAR.pagination.hasNext,false);
const emptyAP=adapter.createIXIAPDesktopModel({});assert.deepEqual(emptyAP.payables,[]);assert.equal(emptyAP.pagination.hasPrevious,false);
const emptyPO=adapter.createIXIPurchaseOrdersDesktopModel({});assert.deepEqual(emptyPO.purchaseOrders,[]);assert.equal(emptyPO.pagination.totalCount,null);
const emptyOperations=adapter.createIXIOperationsDesktopModel({});assert.deepEqual(emptyOperations.workOrders,[]);assert.equal(emptyOperations.pagination.cursor,"");
const noStatement=adapter.createIXIReconciliationDesktopModel({treasury:{accounts:[{accountId:"CASH-1",name:"Operating",bookBalance:1000,lastStatementBalance:null}]}});assert.equal(noStatement.accounts[0].status,"needs-statement");assert.equal(noStatement.accounts[0].difference,null);assert.equal(noStatement.summary.needsStatement,1);
const outOfBalance=adapter.createIXIReconciliationDesktopModel({treasury:{accounts:[{accountId:"CASH-2",name:"Operating",bookBalance:1000,lastStatementBalance:975}]}});assert.equal(outOfBalance.accounts[0].status,"out-of-balance");assert.equal(outOfBalance.accounts[0].difference,25);assert.equal(outOfBalance.summary.openDifference,25);
const balanced=adapter.createIXIReconciliationDesktopModel({treasury:{accounts:[{accountId:"CASH-3",name:"Operating",bookBalance:1000,lastStatementBalance:1000}]}});assert.equal(balanced.accounts[0].status,"reconciled");assert.equal(balanced.summary.reconciled,1);
const normalizedActions=actionRegistry.normalizeIXITransactRecordActions([{id:"record-ar-payment",enabled:true},{id:"record-ar-payment",enabled:true},{id:"void-po",allowed:false,reason:"Closed period"},{id:"server-injected-javascript",enabled:true}]);assert.deepEqual(normalizedActions.map(action=>action.id),["record-ar-payment","void-po"]);assert.equal(normalizedActions[0].requiresInput,true);assert.equal(normalizedActions[1].enabled,false);assert.equal(normalizedActions[1].dangerous,true);assert.deepEqual(actionRegistry.getUnknownIXITransactRecordActionIds([{id:"server-injected-javascript"}]),["server-injected-javascript"]);assert.equal(actionRegistry.canExecuteIXITransactRecordAction({id:"issue-po",enabled:true}),true);assert.equal(actionRegistry.canExecuteIXITransactRecordAction({id:"record-ap-payment",enabled:true}),false);
assert.deepEqual(queryContract.getIXITransactWorkspaceIncludes("reconciliation"),["treasury","attention"]);assert.deepEqual(queryContract.getIXITransactWorkspaceIncludes("purchase-orders"),["purchase-orders","attention"]);assert.deepEqual(queryContract.getIXITransactWorkspaceIncludes("sales"),["ar","reporting"]);assert.deepEqual(queryContract.getIXITransactWorkspaceIncludes("invoices"),["ar"]);assert.deepEqual(queryContract.getIXITransactWorkspaceIncludes("service"),["operations","work-orders","ar","attention"],"Service needs fulfillment plus canonical service-invoice A/R truth.");
const invalid=queryContract.validateIXITransactDashboardQuery(queryContract.createIXITransactDashboardQuery());assert.equal(invalid.ok,false);assert.ok(invalid.errors.some(error=>error.code==="entity-scope-required"));assert.ok(invalid.errors.some(error=>error.code==="period-required"));const valid=queryContract.validateIXITransactDashboardQuery(queryContract.createIXITransactDashboardQuery({scope:{entityPassportIds:["passport:entity:test"]},period:{accountingPeriod:"2026-08"},include:["ar"]}));assert.equal(valid.ok,true);
console.log("IXI TRAN$ACT dashboard contract verification passed.");
