import{createIXIAosObjectFinancialDocument,createIXIAosFinancialObjectReference,mergeIXIAosFinancialReferences}from"../../../financial-runtime/IXIAosFinancialRuntimeAdapter";
import{runIXIActionNoticeLifecycle}from"../../../../ixi-object-system/IXIActionNoticeEngine";
const clean=value=>String(value??"").trim();
const num=value=>Number.isFinite(Number(value))?Number(value):0;
function refs(context={},account={},object={}){const list=[];for(const[candidate,role]of[[context.entity||{},"entity"],[context.location||{},"location"],[context.actor||{},"employee"],[object||{},"object"]]){const ref=createIXIAosFinancialObjectReference({object:candidate,role});if(ref)list.push(ref);}if(account?.identity?.accountId)list.push({externalId:account.identity.accountId,role:"cash-account",label:account.account?.name||account.identity.number,objectType:"financial-account"});return mergeIXIAosFinancialReferences(list);}
function responseId(response={}){return clean(response.financialDocument?.documentId||response.document?.documentId||response.documentId||response.id);}
async function post({object={},context={},account={},input={},transactionClass="",direction="",description="",metadata={},signal}={}){const amount=Math.round(num(input.amount)*100)/100;if(!(amount>=0))throw new Error("Invalid Treasury amount.");const commandId=clean(input.clientRequestId)||`TR-${transactionClass}-${Date.now()}`;const references=refs(context,account,object);const canonicalDirection=direction==="transfer"?"neutral":direction;return runIXIActionNoticeLifecycle({objectId:clean(context.primary?.objectId||context.primary?.passportId||object.objectId||object.passportId),commandId,source:`ixi-transact-treasury-${transactionClass}`,savingMessage:"POSTING TO IXI FINANCIAL...",successMessage:"TREASURY POSTED",errorMessage:error=>clean(error?.message)||"TREASURY POST FAILED",operation:()=>createIXIAosObjectFinancialDocument({object,documentType:"payment",commandId,idempotencyKey:`ixi-treasury:${commandId}`,signal,input:{currency:clean(input.currency||account.account?.currency||"USD").toUpperCase(),amount,total:amount,documentDate:clean(input.date),effectiveDate:clean(input.date),status:"posted",financialState:"posted",direction:canonicalDirection,transactionClass,accountId:clean(account.identity?.accountId),accountName:clean(account.account?.name),method:clean(input.method||"book-entry"),reference:clean(input.reference),description,nonRevenue:true,nonExpense:true,references,...input.extra},additionalReferences:references,metadata:{...metadata,transactModule:"treasury",transactionClass,accountId:clean(account.identity?.accountId)}})});}
export async function postIXITreasuryOpeningBalance({object={},context={},account={},metadata={},signal}={}){if(account.opening?.posted)return{response:null,financialDocumentId:account.opening?.financialDocumentId||""};const response=await post({object,context,account,input:{amount:account.opening?.amount,date:account.opening?.effectiveDate,reference:account.opening?.reference,currency:account.account?.currency,method:"opening-balance"},transactionClass:"opening-balance",direction:"in",description:`Opening balance · ${account.account?.name}`,metadata,signal});return{response,financialDocumentId:responseId(response)};}
export async function postIXITreasuryAdjustment({object={},context={},account={},input={},metadata={},signal}={}){const amount=Math.round(num(input.amount)*100)/100;if(!(amount>0))throw new Error("Adjustment amount must be greater than zero.");if(!clean(input.reason))throw new Error("Adjustment reason is required.");const response=await post({object,context,account,input:{amount,date:input.date,reference:input.reference,currency:account.account?.currency,method:"adjustment",extra:{reason:clean(input.reason)}},transactionClass:"cash-adjustment",direction:clean(input.direction)==="out"?"out":"in",description:`Cash adjustment · ${clean(input.reason)}`,metadata,signal});return{response,financialDocumentId:responseId(response)};}
export async function postIXITreasuryTransfer({object={},context={},fromAccount={},toAccount={},input={},metadata={},signal}={}){const amount=Math.round(num(input.amount)*100)/100;if(!(amount>0))throw new Error("Transfer amount must be greater than zero.");if(!clean(fromAccount.identity?.accountId)||!clean(toAccount.identity?.accountId))throw new Error("Both transfer accounts are required.");if(clean(fromAccount.identity.accountId)===clean(toAccount.identity.accountId))throw new Error("Transfer accounts must be different.");const response=await post({object,context,account:fromAccount,input:{amount,date:input.date,reference:input.reference,currency:fromAccount.account?.currency,method:"internal-transfer",extra:{fromAccountId:fromAccount.identity.accountId,toAccountId:toAccount.identity.accountId,fromAccountName:fromAccount.account?.name,toAccountName:toAccount.account?.name}},transactionClass:"account-transfer",direction:"transfer",description:`Transfer · ${fromAccount.account?.name} → ${toAccount.account?.name}`,metadata,signal});return{response,financialDocumentId:responseId(response)};}
export default{postIXITreasuryOpeningBalance,postIXITreasuryAdjustment,postIXITreasuryTransfer};
