import {useEffect,useRef,useState} from 'react';
import {salesRequest} from './salesDeskClient';
const FIELDS=['name','company','phone','email','address','source','interest','preference','category','budget','timeframe'];
export default function SalesDeskImport({onClose,onSaved}) {
  const dialog=useRef(null),batch=useRef(null),lock=useRef(false);
  const [rows,setRows]=useState([]),[headers,setHeaders]=useState([]),[mapping,setMapping]=useState({}),[preview,setPreview]=useState(null),[selected,setSelected]=useState([]),[results,setResults]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{dialog.current.showModal();},[]);
  useEffect(()=>{const guard=e=>{if(busy){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[busy]);
  const read=async file=>{if(!file)return;setError('');setPreview(null);setResults({});try{if(file.size>2*1024*1024)throw new Error('Choose a CSV under 2 MB.');const {default:Papa}=await import('papaparse');const parsed=Papa.parse(await file.text(),{header:true,skipEmptyLines:'greedy',transformHeader:h=>h.trim()});if(parsed.errors.length)throw new Error(`CSV needs correction: ${parsed.errors[0].message}`);if(!parsed.data.length || parsed.data.length>500)throw new Error('Choose a CSV containing one to 500 contacts.');const fields=parsed.meta.fields || [];setHeaders(fields);setRows(parsed.data);setMapping(Object.fromEntries(FIELDS.map(key=>[key,fields.find(h=>h.toLowerCase().replace(/[ _-]/g,'')===key) || ''])));}catch(e){setRows([]);setError(e.message);}};
  const review=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const values=rows.map(row=>Object.fromEntries(FIELDS.map(key=>[key,mapping[key] ? String(row[mapping[key]] || '').trim() : ''])));const result=await salesRequest('import/preview',{body:{rows:values}});setPreview(result.rows);setSelected(result.rows.filter(r=>r.status==='ready').map(r=>r.index));setResults({});batch.current=crypto.randomUUID();}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}};
  const commit=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');let saved=0;try{const pending=preview.filter(row=>selected.includes(row.index) && results[row.index]?.status!=='saved');for(let i=0;i<pending.length;i+=25){const response=await salesRequest('import/commit',{body:{batchId:batch.current,rows:pending.slice(i,i+25).map(row=>({index:row.index,value:row.value}))}});setResults(old=>({...old,...Object.fromEntries(response.results.map(row=>[row.index,row]))}));saved+=response.results.filter(r=>r.status==='saved').length;}if(saved)onSaved();}catch(e){setError(`${e.message} Completed rows remain saved. Retry resumes the remaining selection.`);}finally{lock.current=false;setBusy(false);}};
  const remaining=selected.filter(index=>results[index]?.status!=='saved').length;
  return <dialog ref={dialog} className="sales-dialog sales-import" aria-labelledby="sales-import-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><header><div><span className="sales-eyebrow">REVIEW BEFORE IMPORTING</span><h2 id="sales-import-title">CONTACT IMPORT</h2></div><button disabled={busy} onClick={onClose} aria-label="Close import">×</button></header><div className="sales-dialog-body"><p>Choose your contact CSV, map its columns, then review each row. Existing email and phone matches are preserved.</p><input type="file" accept=".csv,text/csv" aria-label="Contact CSV" disabled={busy} onChange={e=>read(e.target.files?.[0])}/>{error && <p className="sales-error" role="alert">{error}</p>}{rows.length>0 && !preview && <><div className="sales-fields sales-import-mapping">{FIELDS.map(key=><label className="sales-field" key={key}><span>{key.toUpperCase()}{key==='name' ? ' *' : ''}</span><select value={mapping[key] || ''} disabled={busy} onChange={e=>setMapping(m=>({...m,[key]:e.target.value}))}><option value="">{key==='name' ? 'Choose name column' : 'Skip'}</option>{headers.map(h=><option key={h}>{h}</option>)}</select></label>)}</div><button className="sales-primary" disabled={busy || !mapping.name} onClick={review}>REVIEW {rows.length} CONTACTS</button></>}{preview && <><div className="sales-actions"><button disabled={busy || Object.keys(results).length>0} onClick={()=>setPreview(null)}>CHANGE MAPPING</button><button disabled={busy} onClick={()=>setSelected(preview.filter(r=>r.status==='ready').map(r=>r.index))}>SELECT READY</button><button disabled={busy} onClick={()=>setSelected([])}>CLEAR SELECTION</button></div><div className="sales-data-scroll"><table className="sales-data-table"><thead><tr><th>IMPORT</th><th>CONTACT</th><th>REVIEW</th></tr></thead><tbody>{preview.map(row=><tr key={row.index}><td><input type="checkbox" aria-label={`Import row ${row.index+1}`} disabled={busy || row.status!=='ready' || results[row.index]?.status==='saved'} checked={selected.includes(row.index)} onChange={e=>setSelected(v=>e.target.checked ? [...v,row.index] : v.filter(i=>i!==row.index))}/></td><td><strong>{row.value?.name || `Row ${row.index+1}`}</strong><small>{row.value?.email} {row.value?.phone}</small></td><td><span className="sales-stage">{results[row.index]?.status || row.status}</span><small>{results[row.index]?.message || row.message}</small></td></tr>)}</tbody></table></div><div className="sales-editor-actions"><span>{Object.values(results).filter(r=>r.status==='saved').length} SAVED · {remaining} SELECTED REMAINING</span><button className="sales-primary" disabled={busy || !remaining} onClick={commit}>{busy ? 'IMPORTING…' : `IMPORT ${remaining}`}</button></div></>}</div></dialog>;
}
