import {useEffect,useRef,useState} from 'react';
import {salesRequest} from './salesDeskClient';
const money=(cents,currency='USD')=>cents==null ? 'Not recorded' : new Intl.NumberFormat('en-US',{style:'currency',currency}).format(cents/100);
export default function SalesDeskFinancials({deal,onClose,onSaved}) {
  const dialog=useRef(null),[data,setData]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[busy,setBusy]=useState(false);
  useEffect(()=>{dialog.current.showModal();},[]);
  useEffect(()=>{const controller=new AbortController();setData(null);setError('');salesRequest(`financial/${deal.id}`,{signal:controller.signal}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[deal.id,retry]);
  const link=async row=>{setBusy(true);setError('');try{const fresh=await salesRequest(`records/deals/${deal.id}`);const result=await salesRequest('commands',{body:{kind:'deals',commandId:crypto.randomUUID(),revision:fresh.record.revision,record:{...fresh.record,financialDocumentIds:[...new Set([...(fresh.record.financialDocumentIds || []),row.id])]}}});onSaved('deals',result.record);setRetry(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);}};
  const table=(rows,matching=false)=><div className="sales-compare-scroll"><table className="sales-data-table"><thead><tr><th>DATE / NUMBER</th><th>TYPE</th><th>AMOUNT</th><th>STATUS</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.date || 'Not recorded'}<strong>{row.number}</strong><small>Revision {row.revision}</small></td><td>{row.type.toUpperCase()}</td><td>{money(row.amountCents,row.currency)}</td><td><span className="sales-stage">{row.paymentStatus || row.status}</span>{row.review && <small>Review in TRAN$ACT</small>}</td><td>{matching ? <button disabled={busy} onClick={()=>link(row)}>LINK TO DEAL</button> : <a href={`/transact?passport=${encodeURIComponent(deal.machines?.[0]?.passportId || '')}&record=${encodeURIComponent(row.id)}`}>VIEW ↗</a>}</td></tr>)}</tbody></table></div>;
  return <dialog ref={dialog} className="sales-dialog sales-comparison" aria-labelledby="deal-financial-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><header><div><span className="sales-eyebrow">{deal.title} · {deal.customerName}</span><h2 id="deal-financial-title">TRAN$ACT RECORDS</h2></div><button disabled={busy} onClick={onClose} aria-label="Close deal financials">×</button></header><div className="sales-dialog-body">{error && <p role="alert" className="sales-error">{error}<button disabled={busy} onClick={()=>setRetry(v=>v+1)}>RETRY</button></p>}{!data && !error && <p role="status">Loading the actual transaction records…</p>}{data && <><div className="sales-list-summary"><span>UPDATED {new Date(data.generatedAt).toLocaleTimeString()}</span><button disabled={busy} onClick={()=>setRetry(v=>v+1)}>REFRESH</button></div>{data.sales.map(sale=><div className="sales-sale-facts" key={sale.saleId}><strong>{sale.state?.toUpperCase() || 'SALE RECORD'}</strong><span>DATE SOLD <b>{sale.saleDate || 'Not recorded'}</b></span><span>SALE PRICE <b>{money(sale.salePrice==null ? null : Math.round(sale.salePrice*100),sale.currency)}</b></span><span>BUYER <b>{sale.buyerLabel || 'Not recorded'}</b></span><span>SOLD BY <b>{sale.soldByLabel || 'Not recorded'}</b></span><span>SETTLEMENT <b>{sale.settlementStatus?.toUpperCase() || 'Not recorded'}</b></span></div>)}{data.linked.length ? table(data.linked) : <p>No transactions are linked to this deal yet. Prepare a quote or review the matching records below.</p>}{data.matches.length>0 && <><h3>MACHINE & CUSTOMER MATCHES</h3><p>Review the transaction before linking it to this deal.</p>{table(data.matches,true)}</>}</>}</div></dialog>;
}
