import {useEffect,useRef,useState} from 'react';
import {salesRequest} from './salesDeskClient';
import {dateInZone,localZone} from '../../lib/sales-desk/calendar.mjs';
export const WORK_BUCKETS=[['today','TODAY'],['overdue','OVERDUE'],['unassigned','UNASSIGNED'],['upcoming','NEXT 7 DAYS'],['new','NEW INQUIRIES'],['waiting','WAITING ON CUSTOMER'],['approval','NEEDS APPROVAL'],['quiet','NO UPDATE · 7 DAYS'],['reminders','REMINDERS'],['all','ALL OPEN WORK']];
export function useSalesWork(actor,revision,bucket,scope){
  const [data,setData]=useState({items:[],counts:{},total:0}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[tick,setTick]=useState(0),seq=useRef(0);
  const zone=localZone(),today=dateInZone(new Date(),zone),params=new URLSearchParams({zone,today,scope,bucket,limit:'100'}).toString();
  useEffect(()=>{const current=++seq.current,c=new AbortController();setLoading(true);setError('');salesRequest(`work?${params}`,{signal:c.signal}).then(r=>{if(current===seq.current)setData(r);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(current===seq.current)setLoading(false);});return()=>c.abort();},[revision,params,tick]);
  useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')setTick(n=>n+1);};const t=setInterval(refresh,60000);window.addEventListener('focus',refresh);return()=>{clearInterval(t);window.removeEventListener('focus',refresh);};},[]);
  const more=async()=>{const current=seq.current;setLoading(true);try{const r=await salesRequest(`work?${params}&offset=${data.items.length}`);if(current===seq.current)setData(d=>({...r,items:[...d.items,...r.items]}));}catch(e){setError(e.message);}finally{if(current===seq.current)setLoading(false);}};
  return {data,error,loading,more,refresh:()=>setTick(n=>n+1)};
}
export default function SalesDeskDaily({work,actor,team,bucket,setBucket,scope,setScope,onOpen,onContext,onCreate}) {
  const {data,error,loading,more,refresh}=work;
  return <section className="sales-panel sales-daily" aria-label="Daily sales work"><header className="sales-panel-heading"><div><span className="sales-eyebrow">CUSTOMERS · COMMITMENTS · NEXT ACTION</span><h2>WHAT NEEDS YOU</h2></div><button className="sales-primary" disabled={!actor.canWrite} onClick={onCreate}>+ FOLLOW-UP</button></header>
    <div className="sales-work-filters"><select aria-label="Sales work scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="mine">MY WORK</option>{actor.canReadAll && <option value="team">TEAM WORK</option>}</select><select aria-label="Sales work queue" value={bucket} onChange={e=>setBucket(e.target.value)}>{WORK_BUCKETS.map(([key,label])=><option value={key} key={key}>{label} · {data.counts[key] ?? '—'}</option>)}</select><button onClick={refresh}>REFRESH ↻</button></div>
    {error && <p role="alert" className="sales-error">{error}</p>}<div className="sales-daily-list" aria-busy={loading}>{loading ? <p role="status" className="sales-empty">Updating your work queue…</p> : data.items.length ? data.items.map(event=><article key={event.key} className="sales-work-item"><button className="sales-work-main" onClick={()=>onOpen(event.kind,event.record)}><span className="sales-eyebrow">{event.activityType.replace('-',' ').toUpperCase()} · {event.kind==='deals' ? event.record.stage.toUpperCase() : 'FOLLOW-UP'}</span><strong>{event.title}</strong><span>{event.customerName || 'No linked customer'}{event.date && ` · ${event.date}${event.time ? ` ${event.time}` : ''}`}</span><small>{team.find(m=>m.principalId===event.assignedTo)?.name || (event.assignedTo ? 'Assigned member' : 'UNASSIGNED')}{event.record.waitingOn && ` · WAITING ON ${event.record.waitingOn.toUpperCase()}`}</small></button><div><button onClick={()=>onOpen(event.kind,event.record)}>{!event.assignedTo && actor.canAssign ? 'ASSIGN / REVIEW' : 'OPEN'}</button>{event.dealId && <button onClick={()=>onContext(event)}>OPEN DEAL ↗</button>}</div></article>) : !error && <div className="sales-start"><span className="sales-start-icon">✓</span><h3>No work in this queue.</h3><p>Choose another queue or schedule the next commitment.</p></div>}{!loading && data.items.length<data.total && <button className="sales-wide" onClick={more}>LOAD MORE · {data.items.length} OF {data.total}</button>}</div><footer className="sales-calendar-footer">{data.total} ITEMS · {localZone()} · Refreshed {data.generatedAt ? new Date(data.generatedAt).toLocaleTimeString() : '—'}</footer></section>;
}
