import {useEffect,useRef,useState} from 'react';
import {buyerMachine,createBuyerPdf,downloadBuyerPdf} from '../../lib/sales-desk/buyerPackage.mjs';
import {salesRequest} from './salesDeskClient';
export default function SalesDeskPackage({deal,machines,record,readOnly,onClose,onSaved}) {
  const dialog=useRef(null),command=useRef(null),lock=useRef(false);
  const [title,setTitle]=useState(record?.title || `${deal.title} · Machine selection`),[message,setMessage]=useState(record?.message || ''),[includePrice,setIncludePrice]=useState(true),[includeSerial,setIncludeSerial]=useState(true),[selected,setSelected]=useState((record?.machines || machines).slice(0,20).map(m=>m.key)),[saved,setSaved]=useState(record || null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>{dialog.current.showModal();},[]);
  const snapshots=saved?.machines || machines.filter(m=>selected.includes(m.key)).map(m=>buyerMachine(m.item,{includePrice,includeSerial}));
  const reset=()=>{command.current=null;};
  const save=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');if(!command.current)command.current={kind:'packages',commandId:crypto.randomUUID(),record:{dealId:deal.id,title,message,machines:snapshots}};try{const r=await salesRequest('commands',{body:command.current});setSaved(r.record);onSaved?.();}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}};
  const download=async()=>{if(lock.current || !saved)return;lock.current=true;setBusy(true);setError('');try{const result=await createBuyerPdf(saved);downloadBuyerPdf(result.blob,saved.title);setNotice(result.missingPhotos.length ? `PDF downloaded. Photos could not be included for: ${result.missingPhotos.join(', ')}. Review before sharing.` : 'PDF downloaded. Ready for your review and sharing.');}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}};
  return <dialog ref={dialog} className="sales-dialog" aria-labelledby="sales-package-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><header><div><span className="sales-eyebrow">BUYER PRESENTATION</span><h2 id="sales-package-title">{saved ? 'SAVED PACKAGE' : 'REVIEW YOUR PACKAGE'}</h2></div><button disabled={busy} onClick={onClose} aria-label="Close buyer package">×</button></header><div className="sales-dialog-body"><p>Prepared for <strong>{saved?.customerName || deal.customerName}</strong>. Only the machine details shown below will appear in the PDF.</p>{!saved && <><fieldset className="sales-fields" disabled={busy || readOnly}><label className="sales-field wide"><span>TITLE</span><input maxLength={150} value={title} onChange={e=>{setTitle(e.target.value);reset();}}/></label><label className="sales-field wide"><span>MESSAGE TO BUYER</span><textarea maxLength={1000} value={message} onChange={e=>{setMessage(e.target.value);reset();}}/></label><label className="sales-check"><input type="checkbox" checked={includePrice} onChange={e=>{setIncludePrice(e.target.checked);reset();}}/> Asking prices</label><label className="sales-check"><input type="checkbox" checked={includeSerial} onChange={e=>{setIncludeSerial(e.target.checked);reset();}}/> Serial numbers</label></fieldset><h3>SELECT MACHINES · {selected.length} / 20</h3>{machines.map(m=><label className="sales-check" key={m.key}><input type="checkbox" disabled={busy || readOnly || (!selected.includes(m.key) && selected.length>=20)} checked={selected.includes(m.key)} onChange={e=>{setSelected(v=>e.target.checked ? [...v,m.key] : v.filter(key=>key!==m.key));reset();}}/>{m.item.title}</label>)}{machines.length<deal.machines.length && <p className="sales-error">{deal.machines.length-machines.length} deal machine(s) are no longer in the available catalog and cannot be included in a new package.</p>}</>}{snapshots.map(m=><article className="sales-package-machine" key={m.key}>{m.image && <img src={m.image} alt={m.title}/>}<div><h3>{m.title}</h3><p>{[m.hours && `${m.hours} hours`,m.location].filter(Boolean).join(' · ')}</p>{m.price && <strong>ASKING PRICE {m.price}</strong>}{m.serialNumber && <p>SN {m.serialNumber}</p>}<small>{m.passportId}</small></div></article>)}{saved?.message && <p>{saved.message}</p>}{error && <p className="sales-error" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}<div className="sales-editor-actions"><span>{saved ? `SAVED VERSION ${saved.revision} · ${saved.createdAt.slice(0,10)}` : 'REVIEWED SNAPSHOT'}</span>{saved ? <button className="sales-primary" disabled={busy} onClick={download}>{busy ? 'PREPARING PDF…' : 'DOWNLOAD PDF'}</button> : <button className="sales-primary" disabled={readOnly || busy || !snapshots.length || !title.trim()} onClick={save}>{busy ? 'SAVING…' : 'SAVE REVIEWED PACKAGE'}</button>}</div></div></dialog>;
}
