import {useMemo} from 'react';
import {ACTIVITY_TYPES,localZone} from '../../lib/sales-desk/calendar.mjs';
export default function SalesScheduleFields({value,patch,deal=false}) {
  const zones=useMemo(()=>[...new Set([value.timeZone || localZone(),'UTC',...(Intl.supportedValuesOf?.('timeZone') || ['America/Chicago','America/New_York','America/Denver','America/Los_Angeles'])])],[value.timeZone]);
  return <>
    <label className="sales-field"><span>ACTIVITY TYPE</span><select value={value.activityType || 'follow-up'} onChange={e=>patch('activityType',e.target.value)}>{ACTIVITY_TYPES.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label>
    <label className="sales-field"><span>SCHEDULE</span><select value={value.allDay===false ? 'timed' : 'day'} onChange={e=>patch('allDay',e.target.value==='day')}><option value="day">All day / due date</option><option value="timed">Specific time</option></select></label>
    {value.allDay===false && <><label className="sales-field"><span>START TIME</span><input type="time" required value={value.startTime || '09:00'} onChange={e=>patch('startTime',e.target.value)}/></label><label className="sales-field"><span>DURATION · MINUTES</span><input type="number" required min={5} max={1440} step={5} value={value.durationMinutes ?? 30} onChange={e=>patch('durationMinutes',Number(e.target.value))}/></label></>}
    <label className="sales-field"><span>TIME ZONE</span><select value={value.timeZone || localZone()} onChange={e=>patch('timeZone',e.target.value)}>{zones.map(z=><option key={z}>{z}</option>)}</select></label>
    <label className="sales-field"><span>IN-APP REMINDER</span><select value={value.reminderMinutes ?? 15} onChange={e=>patch('reminderMinutes',Number(e.target.value))}>{[[-1,'None'],[0,'At start'],[5,'5 minutes before'],[15,'15 minutes before'],[30,'30 minutes before'],[60,'1 hour before'],[1440,'1 day before']].map(([n,label])=><option key={n} value={n}>{label}</option>)}</select></label>
    <label className="sales-field wide"><span>LOCATION / MEETING DETAILS</span><input maxLength={500} value={value.location || ''} onChange={e=>patch('location',e.target.value)}/></label>
    {value.allDay===false && <details className="wide sales-schedule-note"><summary>Clock-change handling</summary><label>When a time occurs twice<select aria-label="Clock-change occurrence" value={value.disambiguation || 'earlier'} onChange={e=>patch('disambiguation',e.target.value)}><option value="earlier">Use the first occurrence</option><option value="later">Use the second occurrence</option></select></label></details>}
    <p className="wide sales-schedule-note">Reminders appear while Sales Desk is open. All-day reminders use 9:00 AM in the selected time zone.</p>
    {deal && <><label className="sales-field"><span>NEXT ACTION STATUS</span><select value={value.actionCompleted ? 'done' : 'open'} onChange={e=>patch('actionCompleted',e.target.value==='done')}><option value="open">OPEN</option><option value="done">COMPLETED</option></select></label><label className="sales-field"><span>WAITING ON</span><select value={value.waitingOn || ''} onChange={e=>patch('waitingOn',e.target.value)}><option value="">Active work</option><option value="customer">Customer</option><option value="approval">Internal approval</option></select></label><label className="sales-field wide"><span>NEXT ACTION OUTCOME</span><textarea maxLength={2000} value={value.actionOutcome || ''} onChange={e=>patch('actionOutcome',e.target.value)}/></label></>}
    <label className="sales-check wide"><input type="checkbox" checked={value.canceled===true} onChange={e=>patch('canceled',e.target.checked)}/> Cancel this {deal ? 'next action' : 'appointment'} and retain its history</label>
  </>;
}
