import {useEffect,useRef,useState} from 'react';
import {salesRequest} from './salesDeskClient';
export default function SalesDeskInquiries({actor,revision,onDeal,onChanged,onCreate}) {
  const [data,setData]=useState({items:[],total:0}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[issues,setIssues]=useState([]),[status,setStatus]=useState(''),[query,setQuery]=useState(''),[tick,setTick]=useState(0),[automatic,setAutomatic]=useState(false);
  const lock=useRef(false),controller=useRef(null),listSequence=useRef(0),mounted=useRef(true);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
  useEffect(()=>{const seq=++listSequence.current,c=new AbortController();setLoading(true);const t=setTimeout(()=>salesRequest(`records/inquiries?limit=100&q=${encodeURIComponent(query)}`,{signal:c.signal}).then(r=>{if(seq===listSequence.current)setData(r);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(seq===listSequence.current)setLoading(false);}),180);return()=>{clearTimeout(t);c.abort();};},[revision,tick,query]);
  const sync=async()=>{
    if(lock.current || !actor.canManageTeam || !actor.canWrite)return;lock.current=true;setBusy(true);setError('');setIssues([]);controller.current=new AbortController();const until=new Date().toISOString();let saved=0,existing=0,page=1,totalPages=1,failed=[];
    try{do{setStatus(`Checking inquiry page ${page}${totalPages>1 ? ` of ${totalPages}` : ''}…`);const r=await salesRequest('inquiries/sync',{signal:controller.current.signal,body:{page,until}});saved+=r.results.filter(v=>v.status==='saved').length;existing+=r.results.filter(v=>v.status==='existing').length;failed.push(...r.results.filter(v=>v.status==='error'),...(r.issues || []));totalPages=r.totalPages;page++;if(failed.length)break;}while(page<=totalPages);if(mounted.current){setIssues(failed);setStatus(`${saved} new inquiries connected · ${existing} already connected${failed.length ? ` · ${failed.length} need review` : ''}`);setTick(n=>n+1);onChanged();}}catch(e){if(mounted.current && e.name!=='AbortError')setError(`Sync stopped after ${saved} new inquiries. Saved work is retained; retry resumes safely. ${e.message}`);}finally{lock.current=false;if(mounted.current)setBusy(false);}
  };
  useEffect(()=>{if(!automatic)return;const t=setInterval(()=>{if(document.visibilityState==='visible')sync();},120000);return()=>clearInterval(t);},[automatic,actor]);
  const more=async()=>{const seq=listSequence.current;setLoading(true);try{const r=await salesRequest(`records/inquiries?limit=100&offset=${data.items.length}&q=${encodeURIComponent(query)}`);if(seq===listSequence.current)setData(d=>({...r,items:[...d.items,...r.items]}));}catch(e){setError(e.message);}finally{if(seq===listSequence.current)setLoading(false);}};
  return <section className="sales-panel sales-inquiries" aria-label="Sales inquiries"><header className="sales-panel-heading"><div><span className="sales-eyebrow">ORIGINAL MESSAGE · CUSTOMER · MACHINE</span><h2>INCOMING BUSINESS</h2></div><button className="sales-primary" disabled={!actor.canWrite} onClick={onCreate}>+ INQUIRY</button>{actor.canManageTeam && <button className="sales-primary" disabled={busy || !actor.canWrite} onClick={sync}>{busy ? 'SYNCING…' : 'SYNC MARKETPLACE INQUIRIES'}</button>}</header><div className="sales-work-filters"><input type="search" aria-label="Search inquiries" placeholder="Find an inquiry…" value={query} onChange={e=>setQuery(e.target.value)}/>{actor.canManageTeam && <label className="sales-check"><input type="checkbox" checked={automatic} onChange={e=>{setAutomatic(e.target.checked);if(e.target.checked)sync();}}/> Refresh every 2 minutes while open</label>}</div>{status && <p className="sales-calendar-notice" role="status">{status}</p>}{error && <p className="sales-error" role="alert">{error}</p>}{issues.length>0 && <div className="sales-error" role="alert">{issues.map((issue,i)=><p key={i}>{issue.sourceId}: {issue.message}</p>)}</div>}<div className="sales-daily-list" aria-busy={loading}>{loading && !data.items.length ? <p className="sales-empty">Loading inquiries…</p> : data.items.length ? data.items.map(item=><article className="sales-inquiry" key={item.id}><div><span className="sales-eyebrow">{item.source}{item.sourceDetail ? ` · ${item.sourceDetail}` : ''} · {new Date(item.receivedAt).toLocaleString()}</span><h3>{item.title || item.machine?.title || "General inquiry"}</h3><strong>{item.buyer.name}</strong><p>{[item.buyer.phone,item.buyer.email].filter(Boolean).join(' · ')}</p><blockquote>{item.message || 'No conversation notes recorded.'}</blockquote><button onClick={()=>onDeal({id:item.dealId})}>OPEN CONNECTED DEAL ↗</button></div></article>) : <div className="sales-start"><h3>Your inquiries, connected.</h3><p>{actor.canManageTeam ? 'Add a phone call or outside lead with + Inquiry, or sync marketplace inquiries to connect each original message with its customer, machine, and sales opportunity. Repeated syncs preserve existing work.' : 'Add a phone call or outside lead with + Inquiry. Inquiries also appear here when their connected deals are assigned to you.'}</p></div>}{data.items.length<data.total && <button className="sales-wide" onClick={more} disabled={loading}>LOAD MORE</button>}</div></section>;
}
