import {useEffect,useMemo,useRef,useState} from 'react';
import {salesRequest} from './salesDeskClient';
import {calendarRange,calendarDays,dateInZone,dateLabel,eventsByDay,localZone,moveAnchor,moveRecord} from '../../lib/sales-desk/calendar.mjs';

export default function SalesDeskCalendar({actor,team,revision,onOpen,onContext,onCreate,onSaved}) {
  const [view,setView]=useState('week'),[zone,setZone]=useState(localZone),[anchor,setAnchor]=useState(()=>dateInZone()),[scope,setScope]=useState('mine');
  const [completed,setCompleted]=useState(false),[data,setData]=useState({items:[],total:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  const [move,setMove]=useState(null),[saving,setSaving]=useState(false),[moveError,setMoveError]=useState(''),[notice,setNotice]=useState('');
  const sequence=useRef(0),dragged=useRef(null),moveDialog=useRef(null),moveCommand=useRef(null),saveLock=useRef(false),previewLock=useRef(false);
  const range=useMemo(()=>calendarRange(anchor,view),[anchor,view]),days=useMemo(()=>calendarDays(range.from,range.to),[range]);
  const grouped=useMemo(()=>eventsByDay(data.items,days,zone),[data.items,days,zone]);
  const params=new URLSearchParams({...range,zone,scope,includeCompleted:String(completed),limit:'200'}).toString();
  useEffect(()=>{const seq=++sequence.current,c=new AbortController();setLoading(true);setError('');setData({items:[],total:0});salesRequest(`calendar?${params}`,{signal:c.signal}).then(r=>{if(seq===sequence.current)setData(r);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(seq===sequence.current)setLoading(false);});return()=>c.abort();},[params,revision,refresh]);
  useEffect(()=>{const tick=()=>{if(document.visibilityState==='visible')setRefresh(n=>n+1);};const timer=setInterval(tick,60000);window.addEventListener('focus',tick);return()=>{clearInterval(timer);window.removeEventListener('focus',tick);};},[]);
  useEffect(()=>{if(move)moveDialog.current?.showModal();},[move]);
  const more=async()=>{const seq=sequence.current;setLoading(true);try{const r=await salesRequest(`calendar?${params}&offset=${data.items.length}`);if(seq===sequence.current)setData(d=>({...r,items:[...d.items,...r.items]}));}catch(e){setError(e.message);}finally{if(seq===sequence.current)setLoading(false);}};
  const drop=async(date)=>{
    const event=dragged.current;dragged.current=null;if(!event || !actor.canWrite || saving || move || previewLock.current)return;
    previewLock.current=true;
    const record=moveRecord(event,date,zone);setMoveError('');setNotice('Checking the new time…');
    try{const preview=await salesRequest('calendar/preview',{body:{kind:event.kind,record}});setMove({event,record,conflicts:preview.conflicts,date});moveCommand.current={kind:event.kind,revision:event.revision,record,commandId:crypto.randomUUID()};setNotice('');}catch(e){setError(e.message);setNotice('');}finally{previewLock.current=false;}
  };
  const saveMove=async()=>{if(saveLock.current)return;saveLock.current=true;setSaving(true);setMoveError('');try{const r=await salesRequest('commands',{body:moveCommand.current});onSaved(move.event.kind,r.record);setMove(null);moveCommand.current=null;setRefresh(n=>n+1);setNotice(r.conflicts?.length ? `Rescheduled. ${r.conflicts.length} overlapping commitment(s) need review.` : 'Rescheduled and saved everywhere.');}catch(e){setMoveError(e.message);}finally{setSaving(false);saveLock.current=false;}};
  const member=id=>team.find(m=>m.principalId===id)?.name || (id ? 'Assigned member' : 'Unassigned');
  const card=(event,date)=> <article key={`${event.key}:${date}`} className={`sales-calendar-event ${event.completed || event.canceled ? 'is-complete' : ''}`} draggable={actor.canWrite && !event.completed && !event.canceled} onDragStart={e=>{dragged.current=event;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',event.key);}} onDragEnd={()=>{dragged.current=null;}}>
    <button onClick={()=>onOpen(event.kind,event.record)}><span className="sales-event-time">{event.allDay ? 'ALL DAY' : date===event.date ? event.time : 'CONTINUES'} <small>{event.activityType.replace('-',' ').toUpperCase()}</small></span><strong>{event.title}</strong><span>{event.customerName || event.dealTitle || 'Sales appointment'}</span><small>{member(event.assignedTo)}{event.completed ? ' · COMPLETED' : event.canceled ? ' · CANCELED' : ''}</small>{event.location && <small>{event.location}</small>}</button>
    {event.dealId && <button className="sales-event-context" onClick={()=>onContext(event)}>OPEN DEAL ↗</button>}
  </article>;
  return <section className="sales-calendar sales-panel" aria-label="Sales calendar">
    <header className="sales-panel-heading"><div><span className="sales-eyebrow">YOUR COMMITMENTS · ONE CONNECTED SCHEDULE</span><h2>{view==='month' ? dateLabel(anchor,{month:'long',year:'numeric',day:undefined}) : view==='day' ? dateLabel(anchor,{weekday:'long',year:'numeric'}) : `${dateLabel(range.from)} – ${dateLabel(range.to,{year:'numeric'})}`}</h2></div><button className="sales-primary" disabled={!actor.canWrite} onClick={()=>onCreate(anchor)}>+ APPOINTMENT</button></header>
    <div className="sales-calendar-controls"><div className="sales-segment" aria-label="Calendar view">{['day','week','month','agenda'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v.toUpperCase()}</button>)}</div><div className="sales-date-nav"><button aria-label="Previous calendar period" onClick={()=>setAnchor(moveAnchor(anchor,view,-1))}>‹</button><button onClick={()=>setAnchor(dateInZone(new Date(),zone))}>TODAY</button><button aria-label="Next calendar period" onClick={()=>setAnchor(moveAnchor(anchor,view,1))}>›</button><input type="date" aria-label="Calendar date" value={anchor} onChange={e=>{if(e.target.value)setAnchor(e.target.value);}}/></div><select aria-label="Calendar scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="mine">MY CALENDAR</option>{actor.canReadAll && <option value="team">TEAM CALENDAR</option>}</select><select aria-label="Calendar time zone" value={zone} onChange={e=>setZone(e.target.value)}>{[...new Set([localZone(),'UTC','America/Chicago','America/New_York','America/Denver','America/Los_Angeles',zone])].map(z=><option key={z}>{z}</option>)}</select><label className="sales-check"><input type="checkbox" checked={completed} onChange={e=>setCompleted(e.target.checked)}/> Completed / canceled</label></div>
    {error && <p className="sales-error" role="alert">{error}<button onClick={()=>setRefresh(n=>n+1)}>RETRY</button></p>}{notice && <p className="sales-calendar-notice" role="status">{notice}</p>}
    <div className={`sales-calendar-scroll calendar-${view}`} aria-busy={loading}>
      {loading && !data.items.length ? <p className="sales-empty" role="status">Loading your schedule…</p> : view==='agenda' ? <div className="sales-agenda">{data.items.length ? days.filter(day=>grouped.get(day).length).map(day=><section key={day}><h3>{dateLabel(day,{weekday:'long'})}</h3>{grouped.get(day).map(e=>card(e,day))}</section>) : <div className="sales-start"><h3>Your next 30 days are clear.</h3><p>Schedule a call, inspection, appointment, pickup, or delivery.</p></div>}</div> : <div className={`sales-calendar-grid ${view==='day' ? 'one-day' : ''}`}>{days.map(day=>{const events=grouped.get(day);return <section className={`sales-calendar-day ${day===dateInZone(new Date(),zone) ? 'is-today' : ''} ${view==='month' && day.slice(0,7)!==anchor.slice(0,7) ? 'outside-month' : ''}`} key={day} aria-label={dateLabel(day,{weekday:'long',year:'numeric'})} onDragOver={e=>{if(dragged.current && actor.canWrite)e.preventDefault();}} onDrop={e=>{e.preventDefault();drop(day);}}><header><button onClick={()=>{setAnchor(day);setView('day');}}>{dateLabel(day,{weekday:'short',month:undefined})}</button><button disabled={!actor.canWrite} onClick={()=>onCreate(day)} aria-label={`Add appointment ${day}`}>+</button></header>{events.map(event=>card(event,day))}{!events.length && view==='day' && <p className="sales-empty">No scheduled work. Add an appointment to get started.</p>}</section>;})}</div>}
      {data.items.length<data.total && <button className="sales-wide" onClick={more} disabled={loading}>LOAD MORE · {data.items.length} OF {data.total}</button>}
    </div><footer className="sales-calendar-footer"><span>{data.total} COMMITMENTS · {zone}</span><span>Drag to reschedule · Open to edit or complete</span></footer>
    {move && <dialog className="sales-dialog sales-move-dialog" ref={moveDialog} aria-label="Confirm reschedule" onCancel={e=>{e.preventDefault();if(!saving)setMove(null);}}><header><h2>RESCHEDULE</h2><button aria-label="Cancel reschedule" disabled={saving} onClick={()=>setMove(null)}>×</button></header><div className="sales-dialog-body"><h3>{move.event.title}</h3><p>Move to {dateLabel(move.date,{weekday:'long',year:'numeric'})}{move.record.allDay===false ? ` at ${move.record.startTime} · ${zone}` : ' · all day'}?</p>{move.conflicts.length>0 && <div className="sales-error"><strong>OVERLAPPING COMMITMENTS</strong>{move.conflicts.map((c,i)=><p key={i}>{c.title}</p>)}</div>}{moveError && <p role="alert" className="sales-error">{moveError}</p>}<button className="sales-primary" disabled={saving} onClick={saveMove}>{saving ? 'SAVING…' : moveError ? 'RETRY SAVE' : 'CONFIRM RESCHEDULE'}</button></div></dialog>}
  </section>;
}
