import { useMemo, useState } from "react";
import IXIMachineRail from "../../../IXIMachineRail";
import IXICollectionThumbRail from "../../../ixi-object-system/IXICollectionThumbRail";
import IXIAosPrimaryMediaPanel from "../../card-runtime/modules/IXIAosPrimaryMediaPanel";
import IXIAosInlineAddress from "../../card-runtime/modules/IXIAosInlineAddress";
import IXIAosInlineMetricStrip from "../../card-runtime/modules/IXIAosInlineMetricStrip";
import IXIAosRelationshipInfrastructurePanel from "../../card-runtime/modules/IXIAosRelationshipInfrastructurePanel";
import IXIAosCardHeaderControls from "../../card-runtime/modules/IXIAosCardHeaderControls";

const NATIVE_WIDTH=298,NATIVE_HEIGHT=471,RAIL_RESERVE=19,THUMB_RAIL_HEIGHT=57,PREVIEW_INFO_HEIGHT=22,ACTIONS_HEIGHT=23,ACTIONS_LIFT=5,RELATIONSHIP_ACTION_GAP=5,HEADER_HEIGHT=42;
const LOWER_STACK_HEIGHT=THUMB_RAIL_HEIGHT+ACTIONS_LIFT+ACTIONS_HEIGHT+RELATIONSHIP_ACTION_GAP;
const SKINS=[{id:"v12",label:"V12"},{id:"steel",label:"STEEL"},{id:"blueprint",label:"BLUE"},{id:"industrial",label:"INDUSTRIAL"}];
function safeObject(v){return v&&typeof v==="object"&&!Array.isArray(v)?v:{}}
function clean(v){return String(v||"").trim()}
function getItemId(item={},index=0){return clean(item?.objectId||item?.id||item?.uuid||`item-${index}`)}
function getItemImage(item={}){const media=Array.isArray(item?.media)?item.media:[];const first=media.find(e=>typeof e==="string"?Boolean(clean(e)):Boolean(e?.url||e?.src||e?.imageUrl));if(typeof first==="string")return first;return clean(first?.url||first?.src||first?.imageUrl||item?.imageUrl||item?.imageUrls?.[0]||item?.images?.[0]?.url)}
function getItemLabel(item={},index=0){return clean(item?.displayName||item?.name||item?.title||[item?.fields?.year,item?.fields?.make,item?.fields?.model].filter(Boolean).join(" ")||`OBJECT ${index+1}`)}
export const CARD_001_LOCATION=Object.freeze({cardNumber:1,templateSlug:"location-standard",nativeWidth:NATIVE_WIDTH,nativeHeight:NATIVE_HEIGHT,railReserve:RAIL_RESERVE,label:"Location",section:"LOCATIONS & FACILITIES"});

export default function IXIAosCard001Location({object={},projection=null,objects=[],ixiState={},onIxiStateChange=null,onSaveObject=null,onAddObject=null,onHideObject=null,onDeleteObject=null,onOpenConsole=null,onRecall=null,onBoard=null,onReturn=null,onExposeObject=null,skinId="v12",onSkinChange=null,onSendFront=null,onSendBack=null,onCycleColor=null,onCycleOutline=null,armedDestination="",onSendToArmedDestination=null}){
 const objectId=String(object?.objectId||object?.id||"");
 const [saving,setSaving]=useState(false),[selectedChildIndex,setSelectedChildIndex]=useState(0),[mediaDraft,setMediaDraft]=useState(()=>Array.isArray(object?.media)?object.media:[]);
 const editDraft=safeObject(ixiState?.editDraft),draftFields=safeObject(editDraft?.fields),editing=Boolean(ixiState?.editing),activeSkin=clean(ixiState?.cardSkin)||clean(skinId)||"v12",draftDisplayName=editDraft?.displayName??object?.displayName??"MIDLAND YARD";
 const runtimeObject=useMemo(()=>({...object,displayName:draftDisplayName,media:mediaDraft,fields:{...safeObject(object?.fields),...draftFields}}),[object,draftDisplayName,draftFields,mediaDraft]);
 const childItems=Array.isArray(objects)?objects:[],activeChildIndex=childItems.length?Math.min(Math.max(selectedChildIndex,0),childItems.length-1):-1,activeChild=activeChildIndex>=0?childItems[activeChildIndex]:null,activeChildTitle=activeChild?getItemLabel(activeChild,activeChildIndex):"NO OBJECT SELECTED";
 function patchField(fieldId,value){if(objectId)onIxiStateChange?.(objectId,{editDraft:{...editDraft,fields:{...draftFields,[fieldId]:value}}})}
 function patchDisplayName(value){if(objectId)onIxiStateChange?.(objectId,{editDraft:{...editDraft,displayName:value,fields:{...draftFields}}})}
 function addPhoto(photo){const url=clean(photo?.url);if(url)setMediaDraft(current=>[{url,name:clean(photo?.name),type:clean(photo?.type),size:Number(photo?.size||0),source:"user-upload"},...current])}
 function beginEdit(){if(objectId)onIxiStateChange?.(objectId,{editing:true,editDraft:{displayName:object?.displayName||"MIDLAND YARD",fields:{...safeObject(object?.fields)}}})}
 async function saveEdit(){if(!objectId||saving)return;setSaving(true);try{await onSaveObject?.({objectId,object:runtimeObject,displayName:runtimeObject.displayName,fields:{...safeObject(runtimeObject?.fields)},media:[...mediaDraft]});onIxiStateChange?.(objectId,{editing:false,editDraft:null})}finally{setSaving(false)}}
 function cancelEdit(){setMediaDraft(Array.isArray(object?.media)?object.media:[]);onIxiStateChange?.(objectId,{editing:false,editDraft:null})}
 function changeSkin(next){if(!next)return;if(objectId)onIxiStateChange?.(objectId,{cardSkin:next});onSkinChange?.(next,runtimeObject)}
 function previewPrevious(e){e?.preventDefault?.();e?.stopPropagation?.();if(childItems.length)setSelectedChildIndex(c=>c<=0?childItems.length-1:c-1)}
 function previewNext(e){e?.preventDefault?.();e?.stopPropagation?.();if(childItems.length)setSelectedChildIndex(c=>c>=childItems.length-1?0:c+1)}
 function exposeSelected(e){e?.preventDefault?.();e?.stopPropagation?.();if(activeChild)onExposeObject?.(activeChild,runtimeObject)}
 const metrics={moduleType:"inline-metric-strip",config:{metrics:[{metricId:"assets",label:"ASSETS",source:"projection",key:"assetCount",type:"number"},{metricId:"value",label:"VALUE",source:"projection",key:"totalAssetValue",type:"money"},{metricId:"employees",label:"EMPLOYEES",source:"projection",key:"employeeCount",type:"number"}]}};
 return <div className={`card001 card board-color-none board-outline-1 skin-${activeSkin}`}>
  <header className="header"><div className="identity"><span>LOCATIONS &amp; FACILITIES</span>{editing?<input className="name-input" value={draftDisplayName} autoFocus onPointerDown={e=>e.stopPropagation()} onChange={e=>patchDisplayName(e.target.value)}/>:<strong>{runtimeObject.displayName}</strong>}</div><IXIAosCardHeaderControls canAdd canEdit editing={editing} onAdd={onAddObject} onToggleEdit={beginEdit} onHide={onHideObject} onDelete={onDeleteObject} onOpenConsole={onOpenConsole} skinOptions={SKINS} activeSkinId={activeSkin} onSkinChange={changeSkin}/></header>
  <main className="body"><div className="photo"><IXIAosPrimaryMediaPanel object={runtimeObject} moduleDefinition={{config:{height:158}} editing={editing} onAddPhoto={addPhoto}/></div><div className="preview-info-strip"><strong title={activeChildTitle}>{activeChildTitle}</strong><span className="preview-position">{activeChild?`${activeChildIndex+1}/${childItems.length}`:"0/0"}</span><button type="button" className="preview-out" disabled={!activeChild} onPointerDown={e=>e.stopPropagation()} onClick={exposeSelected}>OUT ↗</button></div><div className="address"><IXIAosInlineAddress object={runtimeObject} editing={editing} onFieldChange={patchField}/></div><div className="metrics"><IXIAosInlineMetricStrip object={runtimeObject} projection={projection} moduleDefinition={metrics}/></div><div className="relationships"><IXIAosRelationshipInfrastructurePanel object={runtimeObject} moduleDefinition={{config:{title:"RELATIONSHIPS & INFRASTRUCTURE",height:150}}/></div>{editing?<div className="edit-actions"><button disabled={saving} onClick={saveEdit}>SAVE</button><button disabled={saving} onClick={cancelEdit}>CANCEL</button></div>:null}</main>
  <div className="actions"><button onClick={()=>onRecall?.(runtimeObject)}>↻ <span>RECALL</span></button><button onClick={()=>onBoard?.(runtimeObject)}>▦ <span>BOARD</span></button><button onClick={()=>onReturn?.(runtimeObject)}>↩ <span>RETURN</span></button></div>
  <div className="photo-rail"><IXICollectionThumbRail items={childItems} activeItemIndex={activeChildIndex} getItemId={getItemId} getItemImage={getItemImage} getItemLabel={getItemLabel} onSelectItem={(item,index)=>setSelectedChildIndex(index)}/>{childItems.length>1?<><button className="card-photo-nav left" onPointerDown={e=>e.stopPropagation()} onClick={previewPrevious}>‹</button><button className="card-photo-nav right" onPointerDown={e=>e.stopPropagation()} onClick={previewNext}>›</button></>:null}</div>
  <IXIMachineRail listing={runtimeObject} saved={false} boardColor="none" boardOutline={1} machineFace={1} onSendFront={onSendFront} onSendBack={onSendBack} onCycleColor={onCycleColor} onCycleOutline={onCycleOutline} armedDestination={armedDestination} onSendToArmedDestination={onSendToArmedDestination}/>
  <style jsx global>{`
   .card001,.card001 *{box-sizing:border-box}.card001{--bg:#101010;--panel:#0a0a0a;--border:rgba(255,255,255,.10);--soft:rgba(255,255,255,.045);--accent:#ffc400;--link:#00c2ff;--text:#f4f4f4;position:relative;width:${NATIVE_WIDTH}px;height:${NATIVE_HEIGHT}px;overflow:hidden;border:1px solid var(--border);border-radius:14px;background:linear-gradient(180deg,rgba(255,255,255,.025),transparent 30%),var(--bg);color:var(--text);box-shadow:inset 0 1px 0 rgba(255,255,255,.04),0 18px 34px rgba(0,0,0,.42)}
   .card001.skin-steel{--bg:#111416;--panel:#171b1d;--border:rgba(210,220,224,.23);--soft:rgba(210,220,224,.11);--accent:#d9dde0;--link:#ffc400;background:linear-gradient(135deg,#1a1d1f,#0d0f10)}.card001.skin-blueprint{--bg:#071119;--panel:#081923;--border:rgba(61,184,255,.26);--soft:rgba(61,184,255,.13);--accent:#54c7ff;--link:#54c7ff;background:linear-gradient(180deg,#0a1720,#050b10)}.card001.skin-industrial{--bg:#15110a;--panel:#1d160c;--border:rgba(255,190,65,.25);--soft:rgba(255,190,65,.11);--accent:#ffc400;--link:#ffc400;background:linear-gradient(135deg,#1e170c,#0e0b07)}
   .card001 .header{position:absolute;inset:0 0 auto;height:${HEADER_HEIGHT}px;padding:7px 12px 3px;display:flex;align-items:flex-start;justify-content:space-between;gap:8px;border-bottom:1px solid var(--soft);z-index:5}.card001 .identity{min-width:0;flex:1}.card001 .identity span{display:block;color:var(--accent);font-size:6.5px;font-weight:950;letter-spacing:.08em}.card001 .identity strong{display:block;margin-top:4px;overflow:hidden;color:var(--text);font-size:17px;font-weight:950;line-height:1;text-overflow:ellipsis;white-space:nowrap}.card001 .name-input{width:148px;height:20px;margin-top:2px;padding:0 5px;border:1px solid var(--accent);border-radius:4px;background:#090909;color:var(--text);font-size:13px;font-weight:950;outline:none;text-transform:uppercase}
   .card001 .body{position:absolute;top:${HEADER_HEIGHT}px;left:0;right:0;bottom:${RAIL_RESERVE+LOWER_STACK_HEIGHT}px;display:flex;flex-direction:column;overflow:hidden}.card001 .photo{flex:none}.card001 .preview-info-strip{height:${PREVIEW_INFO_HEIGHT}px;display:grid;grid-template-columns:minmax(0,1fr) 32px 52px;align-items:center;border-top:1px solid var(--soft);border-bottom:1px solid var(--soft);background:var(--panel)}.card001 .preview-info-strip strong{min-width:0;overflow:hidden;padding:0 7px;color:rgba(255,255,255,.86);font-size:7.5px;font-weight:950;text-overflow:ellipsis;white-space:nowrap}.card001 .preview-position{color:rgba(255,255,255,.30);font-size:6.5px;font-weight:900;text-align:center}.card001 .preview-out{height:100%;border:0;border-left:1px solid var(--soft);background:transparent;color:var(--accent);font-size:7px;font-weight:950}.card001 .address{width:258px;margin:-3px auto 0;text-align:center}.card001 .metrics{width:270px;margin:-5px auto 0}.card001 .relationships{flex:1;min-height:0;margin:5px 6px 0;overflow:hidden}.card001 .address .ixi-aos-inline-address{justify-content:center!important;text-align:center!important}.card001 .address .ixi-aos-inline-address strong{width:100%!important;text-align:center!important}.card001 .metrics .ixi-aos-inline-metrics{width:270px!important;min-height:31px!important;justify-content:center!important;gap:18px!important;padding:3px 2px!important;border-top:1px solid var(--soft)!important;border-bottom:1px solid var(--soft)!important;background:rgba(255,255,255,.012)!important}.card001 .metrics .ixi-aos-inline-metric span{font-size:7.5px!important;color:var(--accent)!important;letter-spacing:.055em!important}.card001 .metrics .ixi-aos-inline-metric strong{font-size:12px!important;color:#fff!important;font-weight:950!important}.card001 .relationships .ixi-aos-relationship-panel{height:100%!important;min-height:0!important}.card001 .relationships .ixi-face-section-title{color:var(--accent)!important;font-size:6.5px!important;letter-spacing:.08em!important}
   .card001 .edit-actions{position:absolute;right:7px;top:2px;display:flex;gap:4px;z-index:10}.card001 .edit-actions button{height:20px;padding:0 7px;border:1px solid var(--soft);border-radius:4px;background:var(--panel);color:var(--accent);font-size:6px;font-weight:950}.card001 .actions{position:absolute;left:6px;right:6px;bottom:${RAIL_RESERVE+THUMB_RAIL_HEIGHT+ACTIONS_LIFT}px;height:${ACTIONS_HEIGHT}px;display:flex;align-items:center;justify-content:center;gap:6px;z-index:20}.card001 .actions button{height:19px;min-width:77px;padding:0 7px;border:1px solid var(--soft);border-radius:4px;background:rgba(255,255,255,.018);color:var(--link);font-size:8px;font-weight:950}.card001 .actions span{margin-left:3px;color:rgba(255,255,255,.62);font-size:6px;font-weight:950}.card001 .photo-rail{position:absolute;left:0;right:0;bottom:${RAIL_RESERVE}px;width:${NATIVE_WIDTH}px;height:${THUMB_RAIL_HEIGHT}px;overflow:hidden;z-index:21}.card001 .card-photo-nav{position:absolute;top:50%;transform:translateY(-50%);width:22px;height:${THUMB_RAIL_HEIGHT}px;border:0;background:rgba(0,0,0,.06);color:rgba(255,255,255,.42);font-size:28px;z-index:30}.card001 .card-photo-nav.left{left:0}.card001 .card-photo-nav.right{right:0}.card001 .photo-rail .ixi-collection-thumb-rail{width:${NATIVE_WIDTH}px!important;height:${THUMB_RAIL_HEIGHT}px!important;padding:2px 7px!important;align-items:center!important}.card001 .photo-rail .ixi-collection-thumb{height:53px!important}.card001 .ixi-aos-primary-media-panel{border-left:0!important;border-right:0!important;border-radius:0!important}
  `}</style>
 </div>
}