export const chassisParts = [
  {
    id: "chassis",
    index: "01",
    code: "IXI-CH-FRAME",
    name: "Command Chassis",
    short: "Spatial frame for every working surface",
    layer: "STRUCTURE",
    status: "PRODUCTION",
    version: "1.0",
    introduced: "2026-09-06",
    purpose:
      "Own the placement of the central command area and every peripheral station as one responsive system.",
    benefit:
      "Objects stay spatially understandable while the operator moves between board, pockets, stacks and Console work.",
    specs: [
      "680px maximum command center",
      "150 × 102px pocket stations",
      "Wide and stacked desktop arrangements",
      "Mobile command-center-only mode",
    ],
    inputs: ["workspace children", "viewport width", "station state"],
    outputs: ["command center", "left stations", "right stations"],
    sources: ["components/ixi-chassis/IXIChassis.js"],
    use: "Use as the single spatial owner around an IXI workspace board.",
  },
  {
    id: "board",
    index: "02",
    code: "IXI-CH-BOARD",
    name: "Board Surface",
    short: "Primary placement field for working objects",
    layer: "STRUCTURE",
    status: "PRODUCTION",
    version: "1.0",
    introduced: "2026-09-06",
    purpose:
      "Present sortable machine, seller and system objects in a wrapping surface with scale-aware spacing.",
    benefit:
      "The customer can arrange real work in one field without losing object size, sequence or ownership context.",
    specs: [
      "Row-wrap layout",
      "Scale-preset column and row gaps",
      "Fixed native object footprint",
      "Optional centered rows",
    ],
    inputs: ["objects", "scaleMode", "columnGap", "rowGap"],
    outputs: ["sortable object field", "stable card geometry"],
    sources: [
      "components/ixi-chassis/IXIBoard.js",
      "components/ixi-chassis/IXIBoardSurface.jsx",
    ],
    use: "Use as the canonical home surface for active workspace objects.",
  },
  {
    id: "mount",
    index: "03",
    code: "IXI-CH-MOUNT",
    name: "Object Mount",
    short: "Sortable, family-aware board position",
    layer: "DATA",
    status: "PRODUCTION",
    version: "1.0",
    introduced: "2026-09-06",
    purpose:
      "Resolve each object identity and family before mounting it into the sortable board contract.",
    benefit:
      "Machines, seller objects and system containers can share one board without becoming the same kind of object.",
    specs: [
      "rectSortingStrategy",
      "board container identity",
      "machine/seller/container families",
      "24-card progressive batches",
    ],
    inputs: ["object identity", "object family", "reorder behavior"],
    outputs: ["sortable mount", "drag source metadata"],
    sources: ["components/ixi-chassis/IXIBoard.js"],
    use: "Use whenever an object enters the central board surface.",
  },
  {
    id: "console-slot",
    index: "04",
    code: "IXI-CH-CON",
    name: "Console Expansion",
    short: "Adjacent operating depth attached to an object",
    layer: "COMMANDS",
    status: "PRODUCTION",
    version: "1.0",
    introduced: "2026-09-06",
    purpose:
      "Reserve additional horizontal footprint when a machine opens left, right or Transact Console slots.",
    benefit:
      "Focused work expands from the machine that initiated it and preserves the object-to-operation relationship.",
    specs: [
      "Saved slot depth",
      "Legacy left/right depth fallback",
      "298px native Console panel",
      "Depth-aware object footprint",
    ],
    inputs: ["consoleSlots", "left/right open state", "Transact depth"],
    outputs: ["expanded footprint", "adjacent Console surface"],
    sources: [
      "components/ixi-chassis/IXIBoard.js",
      "components/ixi-chassis/IXIObjectConsoleRouter.js",
    ],
    use: "Use when an object becomes a live operating session rather than a passive card.",
  },
  {
    id: "pockets",
    index: "05",
    code: "IXI-CH-PKT4",
    name: "Pocket Stations",
    short: "Four peripheral object destinations",
    layer: "COMMANDS",
    status: "PRODUCTION",
    version: "1.0",
    introduced: "2026-09-06",
    purpose:
      "Provide two left and two right destinations with closed, peek, open and armed interaction states.",
    benefit:
      "Operators can stage supporting objects beside the board without burying the primary work.",
    specs: [
      "L2 / L1 / R1 / R2 order",
      "150 × 102px stations",
      "Four 24px action targets",
      "15 × 4px visual marks",
    ],
    inputs: ["container contents", "pocket mode", "armedDestination"],
    outputs: ["closed", "peek", "open", "armed destination"],
    sources: ["components/ixi-chassis/IXIChassis.js", "pages/aos/work.js"],
    use: "Use for persistent side work, destinations and compact workflow staging.",
  },
  {
    id: "stacks",
    index: "06",
    code: "IXI-CH-STK2",
    name: "Active Stacks",
    short: "Top and bottom rapid-access destinations",
    layer: "COMMANDS",
    status: "PRODUCTION",
    version: "1.0",
    introduced: "2026-09-06",
    purpose:
      "Create explicit stackTop and stackBottom destinations for object movement outside the main board sequence.",
    benefit:
      "Operators can hold active work above or below the board while keeping the primary layout intact.",
    specs: [
      "stackTop container",
      "stackBottom container",
      "Distinct 24px targets",
      "Yellow occupied-state signal",
    ],
    inputs: ["dragged object", "target container", "stack contents"],
    outputs: ["top stack", "bottom stack", "occupancy signal"],
    sources: ["components/ixi-chassis/IXIChassis.js", "pages/aos/work.js"],
    use: "Use as fast, explicit holding surfaces for active objects.",
  },
  {
    id: "responsive",
    index: "07",
    code: "IXI-CH-RWD",
    name: "Responsive Geometry",
    short: "One spatial grammar across launch widths",
    layer: "STRUCTURE",
    status: "PRODUCTION",
    version: "1.0",
    introduced: "2026-09-06",
    purpose:
      "Reflow four horizontal pocket stations into paired vertical columns, then remove peripheral stations on small screens.",
    benefit:
      "The board remains usable at constrained widths without horizontal page overflow or false precision.",
    specs: [
      "Wide mode ≥1255px",
      "Stacked mode 851–1254px",
      "Command-only mode ≤850px",
      "Hit targets retained in stacked mode",
    ],
    inputs: ["viewport width", "control-half", "station gap"],
    outputs: ["wide", "stacked", "command-only"],
    sources: ["components/ixi-chassis/IXIChassis.js"],
    use: "Use automatically; pages consume the chassis instead of defining station placement.",
  },
];

export function getChassisPart(id) {
  return chassisParts.find((part) => part.id === id) || chassisParts[0];
}
