import {useMemo} from "react";
import IXIEnterpriseDataTable from "../components/IXIEnterpriseDataTable";
import useIXIWorkspaceFilters from "../hooks/useIXIWorkspaceFilters";
const money=(v,c="USD")=>v===null||v===undefined?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(v));
const clean=v=>String(v??"").trim();
export default function IXIAccountsReceivableDesktop({model={},onOpenRecord,filters={},onFiltersChange}){
 const f=useIXIWorkspaceFilters({filters,onFiltersChange,defaultStatus:"all",defaultSort:"daysPastDue",defaultDirection:"desc"});
 const rows=useMemo(()=>{const q=f.search.toLowerCase();const list=(model.receivables||[]).filter(r=>{const status=clean(r.status);return(f.status==="all"||status===f.status)&&(!q||[r.customerLabel,r.invoiceNumber,r.invoiceId].some(v=>clean(v).toLowerCase().includes(q)))});return list.slice().sort((a,b)=>{const av=a?.[f.sort],bv=b?.[f.sort];const result=typeof av==="number"&&typeof bv==="number"?av-bv:String(av??"").localeCompare(String(bv??""));return f.direction==="asc"?result:-result})},[model.receivables,f.search,f.status,f.sort,f.direction]);
 const t=model.totals||{},open=r=>onOpenRecord?.({...r,title:r.customerLabel,sourceRecordId:r.invoiceId||r.invoiceNumber,sourceRecordType:"invoice",workspace:"ar",detail:`${r.invoiceNumber||"INVOICE"} · ${r.daysPastDue||0} days past due`});
 const columns=useMemo(()=>[{key:"customerLabel",label:"CUSTOMER",width:"1.45fr",sortable:true,render:r=><strong>{r.customerLabel||"CUSTOMER"}</strong>},{key:"invoiceNumber",label:"INVOICE",width:".9fr",sortable:true,value:r=>r.invoiceNumber||r.invoiceId},{key:"originalAmount",label:"ORIGINAL",width:".8fr",sortable:true,render:r=>money(r.originalAmount,model.currency)},{key:"received",label:"RECEIVED",width:".8fr",sortable:true,render:r=>money(r.received,model.currency)},{key:"balance",label:"OPEN",width:".8fr",sortable:true,render:r=><b>{money(r.balance,model.currency)}</b>},{key:"dueDate",label:"DUE",width:".9fr",sortable:true},{key:"daysPastDue",label:"AGE",width:".55fr",sortable:true,render:r=>`${r.daysPastDue||0}D`},{key:"status",label:"STATUS",width:".7fr",sortable:true,render:r=><span className={clean(r.status).toLowerCase()==="overdue"?"td-red":"td-green"}>{clean(r.status).toUpperCase()||"OPEN"}</span>}],[model.currency]);
 return <section className="td-workspace"><div className="td-workspace-title"><div><span>MONEY IN · RECEIVABLE CONTROL</span><h1>ACCOUNTS RECEIVABLE</h1><p>Canonical invoices, payments, credits, promises and disputes.</p></div><input className="td-workspace-search" value={f.search} onChange={e=>f.setSearch(e.target.value)} onBlur={f.flushSearch} onKeyDown={e=>{if(e.key==="Enter")f.flushSearch()}} placeholder="CUSTOMER / INVOICE"/></div><div className="td-kpi-strip">{[["TOTAL A/R",t.totalAR],["CURRENT",t.current],["1–30",t.days1to30],["31–60",t.days31to60],["61–90",t.days61to90],["90+",t.days90plus]].map(([l,v])=><div className="td-kpi" key={l}><span>{l}</span><strong>{money(v,model.currency)}</strong></div>)}</div><div className="td-toolbar"><button type="button" className={f.status==="all"?"on":""} onClick={()=>f.setStatus("all")}>ALL</button><button type="button" className={f.status==="overdue"?"on":""} onClick={()=>f.setStatus("overdue")}>OVERDUE</button><span>OVERDUE {money(t.overdue,model.currency)}</span></div><IXIEnterpriseDataTable columns={columns} rows={rows} rowKey={r=>r.invoiceId||r.invoiceNumber} onRowOpen={open} sortKey={f.sort} sortDirection={f.direction} onSort={f.setSort} cursor={f.cursor||null} hasNext={Boolean(model.pagination?.hasNext)} hasPrevious={Boolean(model.pagination?.hasPrevious)} onNext={()=>f.setCursor(model.pagination?.nextCursor||"")} onPrevious={()=>f.setCursor(model.pagination?.previousCursor||"")} emptyLabel="NO RECEIVABLE ROWS RETURNED FOR THIS SCOPE." ariaLabel="IXI accounts receivable"/></section>;
}
