import {useEffect,useMemo,useState} from "react";
import {fetchMosObjects} from "../../../../../lib/mos/ixiMosClient";
import {createIXIAssetMove} from "../../../../../lib/freight/ixiFreightClient";
import {filterAssetMoveDestinations,getCurrentMoveOrigin,getFreightAsset,getFreightEntityId} from "../freight/IXIFreightContract";

const clean=v=>String(v??"").trim();
export default function IXIAssetMoveApp({context={},object={},onBack=null,onRecordChange=null}){
 const asset=useMemo(()=>getFreightAsset(context,object),[context,object]);const entityId=useMemo(()=>getFreightEntityId(context,object),[context,object]);const origin=useMemo(()=>getCurrentMoveOrigin(context,object),[context,object]);
 const[objects,setObjects]=useState([]),[toId,setToId]=useState(""),[moveType,setMoveType]=useState("location"),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(null);
 useEffect(()=>{if(!entityId)return;fetchMosObjects({entityId}).then(r=>setObjects((r.objects||r.data||[]).filter(x=>clean(x.objectId||x.id)!==asset.objectId))).catch(e=>setError(e.message))},[entityId,asset.objectId]);
 const destinations=useMemo(()=>filterAssetMoveDestinations(objects,{asset,moveType}),[objects,asset,moveType]);
 useEffect(()=>{if(toId&&!destinations.some(x=>clean(x.objectId||x.id)===toId))setToId("")},[moveType,destinations,toId]);
 const to=destinations.find(x=>clean(x.objectId||x.id)===toId)||null;
 async function complete(){setBusy(true);setError("");try{const result=await createIXIAssetMove({entityId,asset,moveType,from:origin,to:{objectId:toId,containerId:clean(to?.containerId||toId),passportId:clean(to?.passportId||to?.ixiPassportId),label:clean(to?.displayName||to?.name)},notes:note,effectiveAt:new Date().toISOString()});setDone(result.assetMove);await onRecordChange?.(result.assetMove,{action:"complete"},context)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div style={{height:"100%",padding:10,fontFamily:"Inter,Arial,sans-serif",background:"#f5f6f7",color:"#111",boxSizing:"border-box",overflow:"auto"}}><div style={{display:"flex",justifyContent:"space-between",borderBottom:"2px solid #111",paddingBottom:7}}><div><div style={{fontSize:8,fontWeight:900,letterSpacing:1.2}}>IXI TRAN$ACT</div><div style={{fontSize:18,fontWeight:900}}>ASSET MOVE</div></div><button onClick={onBack} style={{height:28}}>‹ TRAN$ACT</button></div><div style={{background:"#111",color:"#fff",padding:8,borderRadius:5,marginTop:8}}><b style={{fontSize:12}}>{asset.label}</b><div style={{fontSize:8,opacity:.75}}>{asset.passportId}</div></div>{error?<div style={{marginTop:7,padding:6,border:"1px solid #d99",background:"#fee",fontSize:8}}>{error}</div>:null}{done?<div style={{marginTop:10,padding:10,background:"#fff",border:"1px solid #ccc",borderRadius:5}}><div style={{fontSize:8,fontWeight:900}}>MOVE COMPLETE</div><div style={{fontSize:12,fontWeight:900,marginTop:4}}>{done.move?.from?.label||origin.label} → {done.move?.to?.label}</div><div style={{fontSize:8,marginTop:4}}>{done.identity?.assetMoveId}</div></div>:<><div style={{fontSize:8,fontWeight:900,marginTop:10}}>MOVE TYPE</div><select value={moveType} onChange={e=>setMoveType(e.target.value)} style={{width:"100%",padding:7,marginTop:4}}><option value="location">LOCATION</option><option value="custody">CUSTODY</option><option value="assigned-user">ASSIGNED USER</option></select><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,marginTop:8}}><div><label style={{fontSize:7,fontWeight:900}}>FROM</label><input disabled value={origin.label||"CURRENT"} style={{width:"100%",padding:7}}/></div><div><label style={{fontSize:7,fontWeight:900}}>TO — AOS OBJECT</label><select value={toId} onChange={e=>setToId(e.target.value)} style={{width:"100%",padding:7}}><option value="">SELECT</option>{destinations.map(x=><option key={clean(x.objectId||x.id)} value={clean(x.objectId||x.id)}>{clean(x.displayName||x.name||x.title)}</option>)}</select></div></div><div style={{marginTop:8}}><label style={{fontSize:7,fontWeight:900}}>NOTE</label><textarea value={note} onChange={e=>setNote(e.target.value)} style={{width:"100%",minHeight:55,padding:7}}/></div><button disabled={busy||!toId||!asset.passportId} onClick={complete} style={{width:"100%",marginTop:10,padding:9,background:"#111",color:"#fff",border:0,borderRadius:4,fontWeight:900,fontSize:9}}>{busy?"MOVING...":"COMPLETE MOVE"}</button></>}</div>
}
