import { useState } from "react";
import IXIMachineRail from "../../../IXIMachineRail";
import IXIAosCardHeaderControls from "../../card-runtime/modules/IXIAosCardHeaderControls";

const W=298,H=471,RAIL=19,HEADER=43;
const SKINS=[{id:"v12",label:"V12"},{id:"steel",label:"STEEL"},{id:"blueprint",label:"BLUE"},{id:"industrial",label:"INDUSTRIAL"}];
const clean=v=>String(v??"").trim();
const money=v=>{const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n):clean(v)||"—"};

function Section({title,children}){return <section className="f3-section"><div className="f3-title">{title}</div><div className="f3-body">{children}</div></section>}
function Row({label,value,editing,onChange,type="text",accent=false}){return <div className="f3-row"><span>{label}</span>{editing&&onChange?<input type={type} value={value??""} onChange={e=>onChange(e.target.value)}/>:<strong className={accent?"accent":""}>{clean(value)||"—"}</strong>}</div>}
function MoneyRow({label,value,editing,onChange,accent=false}){return <div className="f3-row"><span>{label}</span>{editing&&onChange?<input type="number" value={value??""} onChange={e=>onChange(e.target.value)}/>:<strong className={accent?"accent":""}>{money(value)}</strong>}</div>}
function Relationship({label,value}){return <button type="button" className="f3-rel"><span>{label}</span><strong>{value}</strong><b>›</b></button>}

export const LOCATION_FACE_3_FINANCIAL=Object.freeze({faceNumber:3,faceId:"location-f3-financial",label:"FINANCIAL INFORMATION",variants:["owned","leased"],version:12});

export default function IXIAosLocationFace3Financial({object={},ixiState={},onIxiStateChange=null,onSaveObject=null,onAddObject=null,onHideObject=null,onDeleteObject=null,onOpenConsole=null,skinId="v12",onSkinChange=null,onSendFront=null,onSendBack=null,onCycleColor=null,onCycleOutline=null,armedDestination="",onSendToArmedDestination=null}){
 const objectId=clean(object?.objectId||object?.id), saved=ixiState?.face3SavedFields&&typeof ixiState.face3SavedFields==="object"?ixiState.face3SavedFields:(object?.fields||{});
 const [editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[draft,setDraft]=useState(()=>({...saved}));
 const fields=editing?draft:saved, mode=clean(fields.ownershipStatus).toLowerCase()==="leased"?"leased":"owned", displayName=clean(object?.displayName)||"YARD NAME";
 const activeSkin=clean(ixiState?.face3Skin)||clean(skinId)||"v12";
 const patch=(k,v)=>setDraft(c=>({...c,[k]:v}));
 const begin=()=>{setDraft({...saved});setEditing(true)}; const cancel=()=>{setDraft({...saved});setEditing(false)};
 async function save(){if(saving)return;setSaving(true);try{onIxiStateChange?.(objectId,{face3SavedFields:{...draft},editingFace3:false});await onSaveObject?.({objectId,object:{...object,fields:{...(object?.fields||{}),...draft}},fields:{...(object?.fields||{}),...draft},face:3});setEditing(false)}finally{setSaving(false)}}
 function changeSkin(id){onIxiStateChange?.(objectId,{face3Skin:id});onSkinChange?.(id,object)}
 const totalMonthly=Number(fields.electric||4250)+Number(fields.water||1150)+Number(fields.sewer||980)+Number(fields.naturalGas||2100)+Number(fields.internetPhone||350)+Number(fields.wasteTrash||420)+Number(fields.propertyTaxMonthly||2980)+Number(fields.insuranceMonthly||1450)+Number(fields.otherCosts||450);
 const leaseMonthly=Number(fields.baseRentMonthly||18750)+Number(fields.camMonthly||4250)+Number(fields.propertyTaxMonthly||2980)+Number(fields.insuranceMonthly||1450)+Number(fields.otherNnnMonthly||1000);
 return <div className={`ixi-location-f3 skin-${activeSkin}`}>
  <header className="f3-header"><div className="f3-identity"><span>LOCATIONS &amp; FACILITIES</span><strong>{displayName}</strong></div>{editing?<div className="f3-edit-actions"><button disabled={saving} onClick={save}>SAVE</button><button disabled={saving} onClick={cancel}>CANCEL</button></div>:<IXIAosCardHeaderControls canAdd canEdit onAdd={onAddObject} onToggleEdit={begin} onHide={onHideObject} onDelete={onDeleteObject} onOpenConsole={onOpenConsole} skinId={activeSkin} skinOptions={SKINS} onSkinChange={changeSkin}/>}</header>
  <div className="f3-scroll">
   <div className={`status ${mode}`}><div><span>OWNERSHIP STATUS</span><strong>{mode==="owned"?"OWNED":"LEASED"}</strong><small>{mode==="owned"?clean(fields.ownershipType)||"FEE SIMPLE":clean(fields.leaseType)||"OPERATING LEASE"}</small></div><div><span>{mode==="owned"?"ACQUIRED":"LEASE START"}</span><strong>{mode==="owned"?clean(fields.acquiredDate)||"MAR 12, 2018":clean(fields.leaseStartDate)||"MAR 12, 2023"}</strong></div></div>
   <div className="two-col">
    <Section title={mode==="owned"?"PROPERTY OWNER":"LANDLORD / LESSOR"}><Row label="ENTITY" value={mode==="owned"?(fields.propertyOwner||"IRONXCHANGE HOLDINGS LLC"):(fields.landlord||"DFW INDUSTRIAL HOLDINGS LLC")} editing={editing} onChange={v=>patch(mode==="owned"?"propertyOwner":"landlord",v)}/><Row label="CONTACT" value={mode==="owned"?(fields.ownerContact||"JOHN CARTER"):(fields.landlordContact||"JOHN MILLER")} editing={editing} onChange={v=>patch(mode==="owned"?"ownerContact":"landlordContact",v)}/><Row label="PHONE" value={mode==="owned"?(fields.ownerPhone||"432-555-0186"):(fields.landlordPhone||"214-555-0186")} editing={editing} onChange={v=>patch(mode==="owned"?"ownerPhone":"landlordPhone",v)}/></Section>
    <Section title="PROPERTY MANAGER"><Row label="NAME" value={fields.propertyManager||"JOHN CARTER"} editing={editing} onChange={v=>patch("propertyManager",v)}/><Row label="PHONE" value={fields.managerPhone||"432-555-0186"} editing={editing} onChange={v=>patch("managerPhone",v)}/><Row label="EMAIL" value={fields.managerEmail||"yard@ironxchange.com"} editing={editing} onChange={v=>patch("managerEmail",v)}/></Section>
   </div>
   {mode==="owned"?<>
    <Section title="PROPERTY OVERVIEW"><div className="two-col inner"><div><Row label="PROPERTY TYPE" value={fields.propertyType||"Industrial"} editing={editing} onChange={v=>patch("propertyType",v)}/><Row label="PARCEL / ASSET ID" value={fields.parcelId||"IXI-2400-DFW"} editing={editing} onChange={v=>patch("parcelId",v)}/><Row label="LAND AREA" value={fields.landArea||"8.42 Acres"} editing={editing} onChange={v=>patch("landArea",v)}/><Row label="BUILDING AREA" value={fields.buildingArea||"42,600 Sq Ft"} editing={editing} onChange={v=>patch("buildingArea",v)}/><Row label="YEAR BUILT" value={fields.yearBuilt||"2005"} editing={editing} onChange={v=>patch("yearBuilt",v)}/><Row label="ZONING" value={fields.zoning||"Industrial"} editing={editing} onChange={v=>patch("zoning",v)}/></div><div><MoneyRow label="LAND VALUE" value={fields.landValue||2750000} editing={editing} onChange={v=>patch("landValue",v)}/><MoneyRow label="IMPROVEMENT VALUE" value={fields.improvementValue||6000000} editing={editing} onChange={v=>patch("improvementValue",v)}/><MoneyRow label="APPRAISED VALUE" value={fields.appraisedValue||8750000} editing={editing} onChange={v=>patch("appraisedValue",v)} accent/><MoneyRow label="CURRENT VALUE" value={fields.currentValue||8750000} editing={editing} onChange={v=>patch("currentValue",v)}/></div></div></Section>
    <Section title="OPERATING COSTS (MONTHLY)"><div className="two-col inner"><div><MoneyRow label="ELECTRIC" value={fields.electric||4250} editing={editing} onChange={v=>patch("electric",v)}/><MoneyRow label="WATER" value={fields.water||1150} editing={editing} onChange={v=>patch("water",v)}/><MoneyRow label="SEWER" value={fields.sewer||980} editing={editing} onChange={v=>patch("sewer",v)}/><MoneyRow label="NATURAL GAS" value={fields.naturalGas||2100} editing={editing} onChange={v=>patch("naturalGas",v)}/></div><div><MoneyRow label="INTERNET / PHONE" value={fields.internetPhone||350} editing={editing} onChange={v=>patch("internetPhone",v)}/><MoneyRow label="WASTE / TRASH" value={fields.wasteTrash||420} editing={editing} onChange={v=>patch("wasteTrash",v)}/><MoneyRow label="PROPERTY TAX" value={fields.propertyTaxMonthly||2980} editing={editing} onChange={v=>patch("propertyTaxMonthly",v)}/><MoneyRow label="INSURANCE" value={fields.insuranceMonthly||1450} editing={editing} onChange={v=>patch("insuranceMonthly",v)}/></div></div><div className="total"><span>TOTAL MONTHLY COSTS</span><strong>{money(totalMonthly)}</strong></div></Section>
    <Section title="ANNUAL SUMMARY (YTD)"><div className="summary-grid"><div><span>TOTAL REVENUE</span><strong>{money(fields.revenueYtd||2130450)}</strong></div><div><span>TOTAL EXPENSES</span><strong>{money(fields.expensesYtd||1073200)}</strong></div><div><span>NET INCOME</span><strong>{money(fields.netIncomeYtd||1057250)}</strong></div></div></Section>
   </>:<>
    <Section title="LEASE OVERVIEW"><div className="two-col inner"><div><Row label="LEASE TYPE" value={fields.leaseType||"NNN (TRIPLE NET)"} editing={editing} onChange={v=>patch("leaseType",v)}/><Row label="LEASE START" value={fields.leaseStartDate||"MAR 12, 2023"} editing={editing} onChange={v=>patch("leaseStartDate",v)}/><Row label="LEASE END" value={fields.leaseEndDate||"MAR 11, 2028"} editing={editing} onChange={v=>patch("leaseEndDate",v)}/><Row label="RENEWAL OPTION" value={fields.renewalOption||"1 – 5 YR OPTION"} editing={editing} onChange={v=>patch("renewalOption",v)}/><Row label="NOTICE REQUIRED" value={fields.noticeRequired||"180 DAYS"} editing={editing} onChange={v=>patch("noticeRequired",v)}/></div><div><MoneyRow label="MONTHLY BASE RENT" value={fields.baseRentMonthly||18750} editing={editing} onChange={v=>patch("baseRentMonthly",v)}/><MoneyRow label="ANNUAL BASE RENT" value={fields.annualBaseRent||225000} editing={editing} onChange={v=>patch("annualBaseRent",v)}/><Row label="RENT ESCALATION" value={fields.rentEscalation||"3.00%"} editing={editing} onChange={v=>patch("rentEscalation",v)}/><Row label="NEXT ESCALATION" value={fields.nextEscalation||"MAR 12, 2026"} editing={editing} onChange={v=>patch("nextEscalation",v)}/></div></div></Section>
    <Section title="LEASE TERMS & COST STRUCTURE"><MoneyRow label="BASE RENT" value={fields.baseRentMonthly||18750} editing={editing} onChange={v=>patch("baseRentMonthly",v)}/><MoneyRow label="CAM / OPEX" value={fields.camMonthly||4250} editing={editing} onChange={v=>patch("camMonthly",v)}/><MoneyRow label="PROPERTY TAX (PASS-THRU)" value={fields.propertyTaxMonthly||2980} editing={editing} onChange={v=>patch("propertyTaxMonthly",v)}/><MoneyRow label="INSURANCE (PASS-THRU)" value={fields.insuranceMonthly||1450} editing={editing} onChange={v=>patch("insuranceMonthly",v)}/><MoneyRow label="OTHER NNN" value={fields.otherNnnMonthly||1000} editing={editing} onChange={v=>patch("otherNnnMonthly",v)}/><div className="total leased"><span>TOTAL MONTHLY OCCUPANCY COST</span><strong>{money(leaseMonthly)}</strong></div></Section>
   </>}
   <Section title="NOTES"><div className="notes">{editing?<textarea value={fields.financialNotes||""} onChange={e=>patch("financialNotes",e.target.value)}/>:<strong>{clean(fields.financialNotes)||(mode==="owned"?"Primary yard for DFW region.":"Triple Net lease. Tenant responsible for utilities, insurance and property tax.")}</strong>}</div></Section>
   <Section title="RELATIONSHIPS & INFRASTRUCTURE"><div className="rels">{(mode==="owned"?[["BUDGET","FY2026"],["INSURANCE","POLICY"],["TAX RECORD","2025"],["UTILITY ACCOUNTS","5 ACCOUNTS"],["MAINTENANCE PLAN","DFW-YARD-MP"]]:[["LEASE AGREEMENT","LEASE-DFW-2400"],["INSURANCE POLICY","POL-DFW-2400"],["UTILITY ACCOUNTS","5 ACCOUNTS"],["LANDLORD CONTACT","JOHN MILLER"],["RENEWAL REMINDER","NOV 11, 2027"]]).map(([l,v])=><Relationship key={l} label={l} value={v}/>)}</div></Section>
  </div>
  <IXIMachineRail listing={object} saved={false} boardColor="none" boardOutline={1} machineFace={3} onSendFront={onSendFront} onSendBack={onSendBack} onCycleColor={onCycleColor} onCycleOutline={onCycleOutline} armedDestination={armedDestination} onSendToArmedDestination={onSendToArmedDestination}/>
  <style jsx global>{`
   .ixi-location-f3,.ixi-location-f3 *{box-sizing:border-box;font-family:Arial,Helvetica,sans-serif}.ixi-location-f3{--bg:#0d0f0f;--panel:#111414;--panel2:#090b0b;--border:rgba(255,255,255,.10);--soft:rgba(255,255,255,.055);--accent:#ffc400;--good:#83d31b;--lease:#b66cff;position:relative;width:${W}px;height:${H}px;overflow:hidden;border:1px solid var(--border);border-radius:14px;background:var(--bg);color:#eee}.ixi-location-f3.skin-steel{--bg:#111416;--panel:#191c1e;--border:rgba(220,230,235,.20);--accent:#d9dde0}.ixi-location-f3.skin-blueprint{--bg:#071119;--panel:#0b1a24;--border:rgba(61,184,255,.24);--accent:#54c7ff}.ixi-location-f3.skin-industrial{--bg:#171108;--panel:#21190d;--border:rgba(255,190,65,.24);--accent:#ffc400}.f3-header{position:absolute;inset:0 0 auto;height:${HEADER}px;padding:7px 10px;border-bottom:1px solid var(--soft);z-index:5}.f3-identity span{display:block;color:var(--